Repository jax-ml/jax, pull requests merged in 2019-10, with the labels that each got.

#1420 Use finfo(dtype).tiny as uniform minval
  jax/random.py
Labels: cla: yes

#1424 Fixed links to Colabs in docs/notebooks
  README.md
Labels: cla: yes

#1429 fix debug_nans for multiple-result primitives
  jax/config.py
  jax/interpreters/xla.py
  tests/debug_nans_test.py
Labels: cla: yes

#1425 Added support for testing Colab notebooks.
  .travis.yml
  README.md
  docs/README.md
  docs/conf.py
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/autodiff_cookbook.ipynb
Labels: cla: yes

#1414 Refactor pytree munging inside lax.root.
  jax/lax/lax_control_flow.py
Labels: cla: yes

#1437 Typo: Gradeints -> Gradients
  README.md
Labels: cla: yes

#1436 Fix initializers and add tests
  jax/nn/initializers.py
  tests/nn_test.py
Labels: cla: yes

#1427 Move epsilon term in optimizers.rmsprop into sqrt
  jax/experimental/optimizers.py
Labels: cla: yes

#1428 Fix typo in initial_step_size d2 calculation
  jax/experimental/ode.py
Labels: cla: yes

#1441 Fix typo in notebook JSON
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
Labels: cla: yes, documentation

#1438 thread through some debug metadata to XLA
  jax/core.py
  jax/interpreters/xla.py
Labels: cla: yes

#1442 WIP: Add a pylintrc to make it easire to use linter
  jax/numpy/lax_numpy.py
  pylintrc
Labels: cla: yes

#1423 Added How_JAX_primitives_work colab
  .gitignore
  docs/index.rst
  docs/notebooks/How_JAX_primitives_work.ipynb
Labels: cla: yes

#1446 [Done] Fixed selu activation
  jax/nn/functions.py
Labels: cla: yes

#1457 Add a .readthedocs.yml file
  .readthedocs.yml
  readthedocs.yml
Labels: cla: yes

#1462 fix XLA metadata for primitives with many args
  jax/core.py
  jax/interpreters/partial_eval.py
  jax/interpreters/xla.py
  tests/lax_control_flow_test.py
Labels: cla: yes

#1456 Remove `dot` primitive in favor of reusing `dot_general`
  jax/lax/lax.py
  jax/lax/lax_parallel.py
  tests/batching_test.py
  tests/masking_test.py
Labels: cla: yes

#1468 Test docs
  .github/workflows/build_mac_jaxlib.yml
  .gitignore
  .readthedocs.yml
  README.md
  WORKSPACE
  docs/conf.py
  docs/index.rst
  docs/notebooks/How_JAX_primitives_work.ipynb
  jax/core.py
  jax/interpreters/partial_eval.py
  jax/interpreters/xla.py
  jax/lax/lax.py
  jax/lax/lax_parallel.py
  jax/nn/functions.py
  jax/numpy/lax_numpy.py
  jaxlib/version.py
  pylintrc
  readthedocs.yml
  tests/batching_test.py
  tests/lax_control_flow_test.py
  tests/masking_test.py
Labels: cla: no

#1469 Disable auto-execution of notebooks
  docs/conf.py
Labels: cla: yes

#1470 Fixed the readthedocs documentation build
  docs/conf.py
  docs/requirements.txt
Labels: cla: yes

#1471 Fixed the readthedocs documentation build
  docs/requirements.txt
Labels: cla: yes, documentation

#1464 Use the XLA HLO implementation of symmetric Eigendecomposition as a f…
  jax/lax_linalg.py
  tests/linalg_test.py
Labels: cla: yes

#1477 Make eigh JVP work for batched inputs.
  jax/lax_linalg.py
  tests/linalg_test.py
Labels: cla: yes

#1479 Move variables inside functions to avoid flags errors, remove matplotlib dependency
  jax/experimental/ode.py
Labels: cla: yes

#1480 Preserve precision config in dot_general transpose rule
  jax/lax/lax.py
  tests/lax_test.py
Labels: cla: yes

#1478 Add experimental support for XLA infeed/outfeed.
  jax/abstract_arrays.py
  jax/interpreters/pxla.py
  jax/interpreters/xla.py
  jax/lax/lax.py
  tests/infeed_test.py
Labels: cla: yes

#1474 Create developer documentation.
  README.md
  docs/README.md
  docs/conf.py
  docs/developer.rst
  docs/index.rst
Labels: cla: yes, documentation

#1481 Register OrderedDict as a pytree type.
  jax/tree_util.py
  tests/tree_util_tests.py
Labels: cla: yes

#1485 Emit a better error if mismatched axis sizes are passed to pmap.
  jax/interpreters/pxla.py
  tests/pmap_test.py
Labels: cla: yes

#1489 Update XLA release to include GPU memory corruption fix.
  WORKSPACE
Labels: cla: yes

#1463 Change device_put to take a `device` argument instead of `device_num`.
  jax/api.py
  jax/interpreters/pxla.py
  jax/interpreters/xla.py
  jax/lib/__init__.py
  tests/api_test.py
Labels: cla: yes

#1492 Adds dirichlet to __init__.py, making it usable
  jax/scipy/stats/__init__.py
Labels: cla: yes

#1495 Add a separate build matrix entry for documentation testing.
  .travis.yml
Labels: cla: yes, documentation

#1422 Rm duplicates from end_nodes in toposort
  jax/util.py
Labels: cla: yes

#1490 Remove unnecessary zero checks from JVP rules in lax_linalg
  jax/lax_linalg.py
Labels: cla: yes

#1501 Fix list rendering in RTD for primitives.ipynb
  docs/notebooks/How_JAX_primitives_work.ipynb
Labels: cla: yes

#1499 Fixes Readme links to notebooks
  README.md
Labels: cla: yes

#1504 Use collections.abc.Sequence in favor of collections.Sequence
  jax/numpy/lax_numpy.py
Labels: cla: yes

#1505 Add Token to core.pytype_aval_mappings.
  jax/interpreters/xla.py
Labels: cla: yes

#1506 Add text to documentation and to jaxlib version check suggesting a pip update.
  README.md
  jax/lib/__init__.py
Labels: cla: yes

#1508 Describe minimum OS version requirements in README.md.
  README.md
Labels: cla: yes

#1507 Move lax.tie_in inside lax.full_like onto the fill value instead the …
  jax/lax/lax.py
  tests/lax_numpy_test.py
Labels: cla: yes

#1511 Delete experimental/lapax.
  jax/experimental/lapax.py
  tests/lapax_test.py
Labels: cla: yes

#1513 try following jupyterlab/jupyter-renderers#212 to fix travis
  .travis.yml
Labels: cla: yes

#1419 Multivariate normal distribution support
  jax/random.py
  tests/random_test.py
Labels: cla: yes

#1514 document pmap with pytrees, fixes #1486
  jax/api.py
Labels: cla: yes

#1512 handle complex dtypes in psum
  jax/lax/lax_parallel.py
  tests/pmap_test.py
Labels: cla: yes

#1493 Moved all notebooks to docs/notebooks.
  README.md
  docs/conf.py
  docs/developer.rst
  docs/index.rst
  docs/notebooks/Neural_Network_and_Data_Loading.ipynb
  docs/notebooks/XLA_in_Python.ipynb
  docs/notebooks/maml.ipynb
  docs/notebooks/neural_network_with_tfds_data.ipynb
  docs/notebooks/score_matching.ipynb
  docs/notebooks/vmapped_log_probs.ipynb
  docs/requirements.txt
  notebooks/README.md
  notebooks/score_matching.ipynb
  notebooks/vmapped log-probs.ipynb
Labels: cla: yes, documentation

#1525 improve broadcast_to, add error checks
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#1523 - sign missing from loss function definition
  examples/resnet50.py
Labels: cla: yes

#1524 broadcast arguments in jax.numpy.take_along_axis
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#1402 lax.custom_linear_solve primitive
  jax/lax/lax_control_flow.py
  tests/lax_control_flow_test.py
Labels: cla: yes

#1540 Fix numpy version check that fails for development numpy versions.
  jax/numpy/lax_numpy.py
Labels: cla: yes

#1541 Add i0e and i1e Bessel functions.
  docs/jax.scipy.rst
  jax/lax/lax.py
  jax/scipy/special.py
  tests/lax_scipy_test.py
Labels: cla: yes

#1542 Add some @jit decorators to non-primitive lax functions.
  jax/lax/lax.py
  tests/lax_test.py
Labels: cla: yes

#1543 Fix lax_reference implementations of erf_inv, conj, complex.
  jax/lax_reference.py
  tests/lax_scipy_test.py
  tests/lax_test.py
Labels: cla: yes

#1544 Remove -Wno-c++98-c++11-compat directive from jaxlib BUILD file.
  jaxlib/BUILD
Labels: cla: yes

#1546 Remove stale reference to lapax.py.
  docs/jax.lax.rst
  jax/BUILD
Labels: cla: yes

#1547 Add sklearn to Travis, for documentation building.
  .travis.yml
  docs/conf.py
  docs/index.rst
Labels: cla: yes, documentation

#1538 Fix NaNs in grad(jax.nn.elu) for large positive inputs.
  jax/nn/functions.py
  tests/nn_test.py
Labels: cla: yes

#1515 try simplifying random.multivariate_normal api
  jax/random.py
  tests/random_test.py
Labels: cla: yes

#1549 make lax.broadcast_in_dim work on scalars
  jax/lax/lax.py
  tests/lax_numpy_test.py
Labels: cla: yes

#1537 Fix grad(jit(custom_linear_solve)) encounters ad_util.Zero in backwars pass
  jax/lax_linalg.py
  tests/lax_control_flow_test.py
Labels: cla: yes

#1556 Switch to gelu approximation in jax.nn
  jax/nn/functions.py
Labels: cla: yes

#1553 Add tests for float16 support in lax_test.py.
  jax/lax/__init__.py
  jax/lax/lax.py
  jax/numpy/lax_numpy.py
  jax/test_util.py
  tests/lax_numpy_test.py
  tests/lax_test.py
Labels: cla: yes

#1557 Relax tolerance of np.sinc test.
  tests/lax_numpy_test.py
Labels: cla: yes

#1560 Relax test tolerance for float16 remainder test.
  tests/lax_numpy_test.py
Labels: cla: yes

#1551 Improved the type checking for uses of scan.
  jax/lax/lax_control_flow.py
  tests/lax_control_flow_test.py
Labels: better_errors, cla: yes

#1573 fixed cross-entropy losses in mnist examples (fixes #1023)
  examples/differentially_private_sgd.py
  examples/mnist_classifier.py
  examples/mnist_classifier_fromscratch.py
  examples/spmd_mnist_classifier_fromscratch.py
Labels: cla: yes

#1578 Fix issue #1576
  jax/lax/lax.py
Labels: cla: yes

#1572 Use redthedocs links for Colabs
  README.md
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/How_JAX_primitives_work.ipynb
Labels: cla: yes, documentation

#1581 add test for fori_loop index batching
  tests/lax_control_flow_test.py
Labels: cla: yes

#1586 Add test for pytree handling of subclasses of collections.namedtuple.
  tests/tree_util_tests.py
Labels: cla: yes

#1587 Disable some tests that fail.
  jax/BUILD
  tests/fft_test.py
  tests/lax_control_flow_test.py
  tests/nn_test.py
Labels: cla: yes

#1588 Delete XRT references from jax.
  jax/lib/__init__.py
  jax/lib/xla_bridge.py
Labels: cla: yes

#1589 Move gradient test tolerance specification to the correct check_grads…
  tests/lax_control_flow_test.py
Labels: cla: yes

#1528 Align momentum optimizer with conventional parameterization and add Nesterov
  jax/experimental/optimizers.py
Labels: cla: yes

#1591 fix orthogonal initializer and reenable test
  jax/nn/initializers.py
  tests/nn_test.py
Labels: cla: yes

#1592 Re-enable some TPU tests in lax_control_flow_test
  tests/lax_control_flow_test.py
Labels: cla: yes

#1570 Support closures in all arguments of lax.custom_root
  docs/jax.lax.rst
  jax/lax/lax_control_flow.py
  tests/lax_control_flow_test.py
Labels: cla: yes

#1593 Add some type helpers to lax_numpy.
  docs/jax.numpy.rst
  jax/lax_linalg.py
  jax/numpy/lax_numpy.py
  jax/random.py
  tests/lax_numpy_test.py
  tests/linalg_test.py
  tests/random_test.py
Labels: cla: yes

#1434 [Waiting Reviews]: Fixes the parameters descriptions
  jax/numpy/lax_numpy.py
  jax/scipy/linalg.py
  jax/scipy/special.py
  jax/scipy/stats/bernoulli.py
  jax/scipy/stats/beta.py
  jax/scipy/stats/cauchy.py
  jax/scipy/stats/dirichlet.py
  jax/scipy/stats/expon.py
  jax/scipy/stats/gamma.py
  jax/scipy/stats/laplace.py
  jax/scipy/stats/multivariate_normal.py
  jax/scipy/stats/norm.py
  jax/scipy/stats/pareto.py
  jax/scipy/stats/t.py
  jax/scipy/stats/uniform.py
Labels: cla: yes

#1597 Fix definition of jax.numpy.divmod for floating-point types.
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#1594 Add np.fft.ifftn
  jax/lax/lax.py
  jax/numpy/fft.py
  tests/fft_test.py
Labels: cla: yes

#1601 Disable LaxControlFlowTest.test_custom_root_with_custom_linear_solve on TPU.
  tests/lax_control_flow_test.py
Labels: cla: yes

#1585 Support mxstep for ode
  jax/experimental/ode.py
Labels: cla: yes

#1603 Increment jax and jaxlib versions.
  WORKSPACE
  build/install_xla_in_source_tree.sh
  jax/version.py
  jaxlib/version.py
Labels: cla: yes

#1604 Add trivial implementations of eigvals/eigvalsh
  jax/numpy/linalg.py
  tests/linalg_test.py
Labels: cla: yes

#1607 Update XLA.
  WORKSPACE
Labels: cla: yes

#1609 Update XLA to fix CUDA build failure.
  WORKSPACE
Labels: cla: yes

#1610 Update XLA to fix another CUDA build problem.
  WORKSPACE
Labels: cla: yes

#1613 vmap improvements
  jax/api.py
  jax/api_util.py
  jax/interpreters/ad.py
  jax/interpreters/batching.py
  jax/tree_util.py
  tests/api_test.py
  tests/batching_test.py
  tests/tree_util_tests.py
Labels: better_errors, cla: yes, documentation

#1608 Implement Poisson distribution for jax.scipy.stats
  jax/scipy/stats/__init__.py
  jax/scipy/stats/poisson.py
  tests/scipy_stats_test.py
Labels: cla: yes

#1605 fix a leak where compiled results lived too long
  jax/api.py
  jax/interpreters/ad.py
  jax/linear_util.py
  tests/api_test.py
Labels: cla: yes
