Repository jax-ml/jax, pull requests merged in 2019-11, with the labels that each got.

#1618 Import nn in jax/__init__.py.
  jax/__init__.py
Labels: cla: yes

#1619 Use --repo_env instead of --action_env to configure Python and CUDA.
  build/build.py
Labels: cla: yes

#1616 Docstring fixes for lax.custom_linear_solve
  docs/jax.numpy.rst
  jax/lax/lax_control_flow.py
Labels: cla: yes

#1622 avoid generating a trivial gather from numpy indexing
  jax/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: cla: yes

#1626 Fix behavior of np.logaddexp/logaddexp2 and scipy.special.logsumexp f…
  jax/numpy/lax_numpy.py
  jax/scipy/special.py
  tests/lax_numpy_test.py
  tests/lax_scipy_test.py
Labels: cla: yes

#1631 avoid staging out some trivial convert_element_types
  jax/lax/lax.py
Labels: cla: yes

#1614 Reimplemented fixpoint computation for scan.
  jax/lax/lax_control_flow.py
  tests/lax_control_flow_test.py
Labels: cla: yes

#1633 Fix transpose rule for psum.
  jax/lax/lax_parallel.py
  tests/pmap_test.py
Labels: cla: yes

#1634 Disable complex eigvalsh test on TPU.
  tests/linalg_test.py
Labels: cla: yes

#1620 Add optix to experimental
  jax/BUILD
  jax/experimental/optix.py
  tests/optix_test.py
Labels: cla: yes

#1641 fix indexing error after #1622 involving empty result
  jax/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: cla: yes

#1642 Add missing parameter to make_tuple
  jax/interpreters/xla.py
Labels: cla: yes

#1648 Fix integer overflow for large matrices in linear algebra kernels.
  jaxlib/cusolver.cc
  jaxlib/lapack.pyx
Labels: cla: yes

#1582 Add custom interpreter notebook
  docs/index.rst
  docs/notebooks/Writing_custom_interpreters_in_Jax.ipynb
Labels: cla: yes

#1650 Fix np.clip broadcasting across a_min and a_max
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#1662 Update XLA.
  WORKSPACE
Labels: cla: yes

#1661 Expose global_norm in optix
  jax/experimental/optix.py
Labels: cla: yes

#1653 Faster test collection, second try
  jax/test_util.py
  tests/batching_test.py
  tests/fft_test.py
  tests/lax_numpy_indexing_test.py
  tests/lax_numpy_test.py
  tests/lax_scipy_test.py
  tests/lax_test.py
  tests/linalg_test.py
  tests/scipy_stats_test.py
Labels: cla: yes

#1664 Hoist loop-invariant residuals out of scan in partial eval
  jax/lax/lax_control_flow.py
  tests/lax_control_flow_test.py
Labels: cla: yes

#1666 minor cleanups in xla.py
  jax/interpreters/xla.py
  tests/core_test.py
Labels: cla: yes

#1658 make linspace, logspace, geomspace jittable and differentiable in start and stop args
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#1669 Update jaxlib version in README.md.
  README.md
Labels: cla: yes

#1673 Add TPU Driver to jaxlib
  build/BUILD.bazel
  build/install_xla_in_source_tree.sh
Labels: cla: yes

#1674 fix degenerate case behavior of linspace
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#1654 [doc] Note that building jaxlib from source isn't always necessary
  docs/developer.rst
Labels: cla: yes

#1667 simplify [p]xla.py by in-lining single-caller function
  jax/api.py
  jax/interpreters/pxla.py
  jax/interpreters/xla.py
  jax/lax/lax.py
  jax/lax/lax_control_flow.py
  jax/lax/lax_parallel.py
  tests/pmap_test.py
Labels: cla: yes

#1682 fix nested pmap bug (thanks @thenerdstation)
  jax/interpreters/pxla.py
  tests/parallel_test.py
  tests/pmap_test.py
Labels: cla: yes

#1683 patch lax.axis_index, add warning about soft_pmap
  jax/api.py
  jax/interpreters/pxla.py
  tests/parallel_test.py
  tests/pmap_test.py
Labels: cla: yes

#1687 Fix the DeviceArray __repr__ function to include the dtype.
  jax/interpreters/xla.py
Labels: cla: yes

#1685 Strengthened type checking for while and cond
  docs/developer.rst
  jax/lax/lax_control_flow.py
  tests/lax_control_flow_test.py
Labels: cla: yes

#1574 Added JAX pytrees notebook
  jax/lax/lax_control_flow.py
  tests/lax_control_flow_test.py
Labels: cla: yes, documentation

#1690 Add type checks that verify JVP primal inputs have the same types as …
  jax/api.py
  tests/api_test.py
Labels: cla: yes

#1691 Add stricter type checks for the start_indices arguments to dynamic_s…
  jax/lax/lax.py
  tests/lax_test.py
Labels: cla: yes

#1692 Remove test_util.check_raises_regexp.
  jax/test_util.py
  tests/api_test.py
  tests/lax_test.py
  tests/pmap_test.py
Labels: cla: yes

#1693 Add a type check that verifies the lower and upper arguments to lax.f…
  jax/lax/lax_control_flow.py
  tests/lax_control_flow_test.py
Labels: cla: yes

#1675 Add TPU Driver as JAX backend for high-performance access to Google Cloud TPU hardware.
  jax/lib/__init__.py
  jax/lib/xla_bridge.py
Labels: cla: yes

#1694 fix shard_args logic, closes #1688
  jax/interpreters/pxla.py
Labels: cla: yes

#1697 improve grad error message without enough args
  jax/api.py
  tests/api_test.py
Labels: cla: yes

#1698 improve docs on shape/dtype loop stability
  jax/lax/lax_control_flow.py
  tests/lax_control_flow_test.py
Labels: cla: yes

#1695 Move internal type-related functions into a new (internal) jax.types …
  jax/abstract_arrays.py
  jax/api.py
  jax/dtypes.py
  jax/interpreters/xla.py
  jax/lax/lax.py
  jax/lax/lax_control_flow.py
  jax/lax/lax_parallel.py
  jax/lax_linalg.py
  jax/lib/xla_bridge.py
  jax/numpy/fft.py
  jax/numpy/lax_numpy.py
  jax/numpy/linalg.py
  jax/random.py
  jax/test_util.py
  tests/lax_numpy_indexing_test.py
  tests/lax_numpy_test.py
  tests/lax_test.py
  tests/linalg_test.py
  tests/random_test.py
Labels: cla: yes

#1700 Drop protobuf dependency from the `jax` package. It appears unused.
  setup.py
Labels: cla: yes

#1702 Update XLA.
  WORKSPACE
  build/build.py
  build/build_wheel_docker_entrypoint.sh
Labels: cla: yes

#1701 Change test tolerance logic not to choose tolerance values based on f…
  jax/lax/lax_fft.py
  jax/test_util.py
  tests/api_test.py
  tests/batching_test.py
  tests/core_test.py
  tests/fft_test.py
  tests/lax_control_flow_test.py
  tests/lax_numpy_einsum_test.py
  tests/lax_numpy_test.py
  tests/lax_scipy_test.py
  tests/lax_test.py
  tests/linalg_test.py
  tests/masking_test.py
  tests/multibackend_test.py
  tests/nn_test.py
  tests/optimizers_test.py
  tests/random_test.py
  tests/scipy_stats_test.py
Labels: cla: yes

#1706 An implementation of an experimental syntactic sugar for 'for' and `while` loops and conditionals.
  docs/jax.experimental.loops.rst
  docs/jax.experimental.rst
  jax/experimental/loops.py
  jax/interpreters/partial_eval.py
  tests/loops_test.py
Labels: cla: yes, enhancement

#1709 Change scalar promotion rules to prefer array types over scalar types.
  jax/abstract_arrays.py
  jax/core.py
  jax/dtypes.py
  jax/interpreters/batching.py
  jax/interpreters/xla.py
  jax/lax/lax.py
  jax/lax/lax_control_flow.py
  jax/lib/xla_bridge.py
  jax/numpy/lax_numpy.py
  jax/numpy/linalg.py
  jax/random.py
  jax/test_util.py
  tests/api_test.py
  tests/batching_test.py
  tests/dtypes_test.py
  tests/lax_control_flow_test.py
  tests/lax_numpy_test.py
  tests/lax_test.py
  tests/masking_test.py
  tests/optimizers_test.py
  tests/pmap_test.py
Labels: cla: yes

#1713 Avoid out-of-bounds dereference for arity-0 nodes.
  jaxlib/pytree.cc
Labels: cla: yes

#1714 Relax test tolerance for core_test jvp tests.
  tests/core_test.py
Labels: cla: yes

#1716 Add type check that indexers are integers or boolean values.
  jax/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: cla: yes

#1717 Check for None in indexer dtype check.
  jax/numpy/lax_numpy.py
Labels: cla: yes

#1718 Implement the __pos__ operator on JAX arrays.
  jax/core.py
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#1707 Bump jaxlib version in README
  README.md
Labels: cla: yes

#1721 fix reference cycle in jaxpr tracing using weakrefs
  jax/core.py
  jax/interpreters/partial_eval.py
  jax/interpreters/pxla.py
  jax/lax/lax_control_flow.py
  tests/core_test.py
Labels: cla: yes

#1711 Add support for scipy.ndimage.map_coordinates with order=0 and order=1
  jax/numpy/lax_numpy.py
  jax/scipy/__init__.py
  jax/scipy/ndimage.py
  tests/scipy_ndimage_test.py
Labels: cla: yes

#1727 fix multi-host pmap, disambiguate nrep
  jax/interpreters/pxla.py
Labels: cla: yes

#1725 Fix typo
  docs/notebooks/How_JAX_primitives_work.ipynb
Labels: cla: yes

#1726 Fix typo
  docs/notebooks/How_JAX_primitives_work.ipynb
Labels: cla: yes

#1627 Implementation of np.signbit
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#1724 Add jax.scipy.ndimage to online docs
  docs/jax.scipy.rst
Labels: cla: yes

#1729 Add refcount logic for rvjp deletion
  rvjp.py
Labels: cla: yes

#1720 Add bfloat16 support to JAX.
  jax/abstract_arrays.py
  jax/dtypes.py
  jax/lax/lax.py
  jax/lax_reference.py
  jax/numpy/lax_numpy.py
  jax/test_util.py
  tests/lax_numpy_test.py
  tests/lax_test.py
Labels: cla: yes

#1734 Minor documentation fixes.
  README.md
  docs/jax.numpy.rst
Labels: cla: yes

#1735 Fix test failure for jax.numpy.signbit(bfloat16) on TPU.
  jax/numpy/lax_numpy.py
Labels: cla: yes

#1736 Implement batching rule for lax._select_and_gather_add
  jax/interpreters/batching.py
  jax/lax/__init__.py
  jax/lax/lax.py
  tests/lax_test.py
Labels: cla: yes

#1722 Use double-where trick to avoid NaNs in grad(sinc)
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#1739 Build Mac wheels for Python 3.8 with scipy 1.3.2.
  build/build_jaxlib_wheels_macos.sh
Labels: cla: yes

#1741 Add jit decorators to most functions in jax.scipy.linalg.
  jax/scipy/linalg.py
Labels: cla: yes

#1728 Add precision to jax.numpy functions that use lax.dot_general
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#1742 jaxlib build improvements
  build/Dockerfile
  build/build_jaxlib_wheels.sh
Labels: cla: yes

#1743 Relax test tolerances to fix flakiness.
  tests/lax_numpy_test.py
Labels: cla: yes

#1740 Fix bug in jax repeat which caused a value error for repeat arguments…
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#1746 Remove `as_abstract_val`.
  jax/interpreters/partial_eval.py
Labels: cla: yes

#1744 Disable failing test
  tests/lax_test.py
Labels: cla: yes

#1750 Add jax.numpy.dtype as an alias of numpy.dtype.
  jax/numpy/lax_numpy.py
Labels: cla: yes

#1751 Relax test tolerances to reduce flakiness.
  tests/batching_test.py
  tests/core_test.py
  tests/lax_numpy_test.py
  tests/lax_test.py
  tests/linalg_test.py
Labels: cla: yes

#1752 Minor fixes to tests.
  tests/dtypes_test.py
  tests/loops_test.py
  tests/optix_test.py
Labels: cla: yes

#1757 Revert support for building a non-GPU build with --config=cuda enabled.
  build/build.py
  build/build_wheel_docker_entrypoint.sh
Labels: cla: yes

#1756 Add a handwritten ThreeFry2x32 CUDA kernel.
  WORKSPACE
  build/BUILD.bazel
  build/build.py
  build/install_xla_in_source_tree.sh
  jax/interpreters/batching.py
  jax/lax/__init__.py
  jax/lib/__init__.py
  jax/random.py
  jaxlib/BUILD
  jaxlib/cublas.cc
  jaxlib/cuda_prng.py
  jaxlib/cuda_prng_kernels.cc
  jaxlib/cuda_prng_kernels.cu.cc
  jaxlib/cuda_prng_kernels.h
  jaxlib/cusolver.cc
  jaxlib/kernel_helpers.h
  tests/random_test.py
Labels: cla: yes

#1758 Added notebook for PyTrees
  docs/index.rst
  docs/jax.experimental.vectorize.rst
  docs/jax.random.rst
  docs/jax.tree_util.rst
  docs/notebooks/JAX_pytrees.ipynb
  jax/tree_util.py
Labels: cla: yes

#1759 Remove `join_pvals`
  jax/interpreters/partial_eval.py
Labels: cla: yes

#1760 Add error checking to PRNG CUDA kernel.
  jaxlib/BUILD
  jaxlib/cublas.cc
  jaxlib/cuda_prng_kernels.cu.cc
  jaxlib/cusolver.cc
  jaxlib/gpu_kernel_helpers.cc
  jaxlib/gpu_kernel_helpers.h
Labels: cla: yes

#1761 raise an error on jit-of-multi-host-pmap
  jax/interpreters/xla.py
Labels: cla: yes

#1730 enable kernel regression example test
  examples/examples_test.py
Labels: cla: yes

#1762 Remove 'backend' argument from device_put.
  jax/api.py
  jax/interpreters/pxla.py
  jax/interpreters/xla.py
  jax/lib/xla_bridge.py
  tests/api_test.py
Labels: cla: yes

#1765 Update minimum jaxlib to 0.1.36.
  jax/lib/__init__.py
Labels: cla: yes

#1767 Pin the minimum jaxlib version in travis.yml.
  .travis.yml
Labels: cla: yes

#1770 fix grad of jit caching bug
  jax/interpreters/ad.py
  jax/interpreters/xla.py
  jax/linear_util.py
  tests/api_test.py
Labels: cla: yes

#1768 Fix some missing docstrings for Numpy functions.
  jax/numpy/lax_numpy.py
Labels: cla: yes

#1771 Add loops BUILD target.
  jax/BUILD
Labels: cla: yes

#1773 Make jax.numpy.broadcast_to consistent with numpy.
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#1774 Simplify einsum implementation.
  jax/numpy/lax_numpy.py
Labels: cla: yes

#1775 Simplify jax.numpy.tensordot by using lax.dot_general.
  jax/numpy/lax_numpy.py
Labels: cla: yes

#1772 Wrap optix rules in a namedtuple with init/apply
  jax/experimental/optix.py
  tests/optix_test.py
Labels: cla: yes

#1777 Add error checking that arguments of jvp are tuples
  jax/api.py
  tests/api_test.py
  tests/generated_fun_test.py
Labels: cla: yes

#1778 Remove degenerate non-contracting special case from jax.numpy.einsum.
  jax/numpy/lax_numpy.py
Labels: cla: yes

#1780 Fix variable name in error message
  jax/interpreters/xla.py
Labels: cla: yes

#1766 Changed api.make_jaxpr to return a TypedJaxpr
  docs/notebooks/Writing_custom_interpreters_in_Jax.ipynb
  jax/api.py
  jax/core.py
  jax/test_util.py
  tests/api_test.py
  tests/batching_test.py
  tests/core_test.py
  tests/lax_control_flow_test.py
  tests/lax_numpy_indexing_test.py
  tests/lax_numpy_test.py
Labels: cla: yes

#1785 Cleaned some test warnings.
  tests/api_test.py
  tests/lax_control_flow_test.py
  tests/lax_test.py
  tests/pmap_test.py
Labels: cla: yes

#1783 Implement np.flip with axis = None
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes
