Repository jax-ml/jax, pull requests merged in 2020-04, with the labels that each got.

#2560 Remove unused argument from pxla.shard_args
  jax/interpreters/pxla.py
Labels: cla: yes

#2552 Ensure the global trace_state is restored on errors in loops
  jax/experimental/loops.py
  tests/loops_test.py
Labels: cla: yes

#2567 Fix error message
  jax/experimental/stax.py
Labels: cla: yes

#2528 Add `jax.tree_util.all_leaves(iterable)`
  jax/tree_util.py
  jaxlib/pytree.cc
  tests/tree_util_tests.py
Labels: cla: yes, enhancement

#2569 Replace CHECK with assert.
  jaxlib/pytree.cc
Labels: cla: yes

#2512 Fix some missing cases of broadcasting in np.einsum.
  jax/numpy/lax_numpy.py
  tests/lax_numpy_einsum_test.py
Labels: cla: yes

#1177 enable beta test on float64 values
  tests/random_test.py
Labels: cla: yes

#1473 Fix issue 1465: fix jit in example
  examples/advi.py
Labels: cla: yes

#2571 Fix incorrect raise in np.clip and add a test.
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#1529 Implementation of np.ldexp and np.frexp
  jax/numpy/lax_numpy.py
  jax/test_util.py
  tests/lax_numpy_test.py
Labels: cla: yes

#2575 Fix missing type promotion accidentally removed by #2512.
  jax/numpy/lax_numpy.py
Labels: cla: yes

#2562 Refactor shard_args ShardedDeviceArray slow path.
  jax/interpreters/pxla.py
Labels: cla: yes

#2577 Revert "Refactor shard_args ShardedDeviceArray slow path. (#2562)"
  jax/interpreters/pxla.py
Labels: cla: yes

#2579 Disable test with float16 on TPU
  jax/test_util.py
  tests/lax_numpy_test.py
Labels: cla: yes

#2580 Another attempt to disable new failing test on TPU
  tests/lax_numpy_test.py
Labels: cla: yes

#2581 post process call of jet!
  jax/experimental/jet.py
  tests/jet_test.py
Labels: cla: yes

#2584 Revert jax.numpy.matmul to pre-#2512 version.
  jax/numpy/lax_numpy.py
Labels: cla: yes

#2587 re-enable travis mypy testing (typo broke it)
  .travis.yml
  jax/core.py
  tests/api_test.py
  tests/lax_control_flow_test.py
  tests/loops_test.py
Labels: cla: yes

#2593 add full lower to custom_jvp/vjp call bind
  jax/custom_derivatives.py
  tests/api_test.py
Labels: cla: yes

#2592 add trace state check tearDown to JaxTestCase
  jax/test_util.py
  tests/api_test.py
  tests/lax_control_flow_test.py
  tests/loops_test.py
  tests/parallel_test.py
Labels: cla: yes

#2563 add callable typechecks to more api.py functions
  jax/api.py
Labels: cla: yes

#2561 FIX: batch norm w/ no scale, center
  jax/experimental/stax.py
  tests/stax_test.py
Labels: cla: yes

#2596 Reimplement np.cumsum and np.cumprod in terms of a parallel prefix scan.
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#2597 Make reduce_prod differentiable to arbitrary order.
  jax/lax/lax.py
  tests/lax_test.py
Labels: cla: yes

#2566 Implement scipy.sparse.linalg.cg (second try)
  docs/jax.scipy.rst
  jax/scipy/sparse/__init__.py
  jax/scipy/sparse/linalg.py
  tests/lax_scipy_sparse_test.py
Labels: cla: yes

#2599 Fix grad(logit) to use defjvps and enable it in tests
  jax/scipy/special.py
  tests/lax_scipy_test.py
Labels: cla: yes

#2591 make tracers tree-pretty-print their contents
  jax/core.py
Labels: cla: yes

#2601 Fix error handling when an attempt is made to pmap a scalar.
  jax/interpreters/pxla.py
Labels: better_errors, cla: yes

#2600 Support pytrees in jax.scipy.linalg.cg
  jax/scipy/sparse/linalg.py
  tests/lax_scipy_sparse_test.py
Labels: cla: yes

#2471 Fix lax.broadcast_shapes returning numpy ints in shape tuple
  jax/lax/lax.py
  tests/lax_test.py
Labels: cla: yes

#2614 Add backend-specific lowering for cumsum/cumprod on TPU.
  jax/interpreters/xla.py
  jax/lax/lax.py
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
  tests/lax_test.py
Labels: cla: yes

#2617 Handle n==0 case in TPU cumsum/cumprod.
  jax/lax/lax.py
Labels: cla: yes

#2615 Add some missing functions to documentation.
  docs/jax.nn.rst
  docs/jax.numpy.rst
Labels: cla: yes

#2616 Also enable nan checking for complex numbers
  jax/interpreters/xla.py
Labels: cla: yes

#2618 cumsum is linear, so its gradient can be linear also.
  jax/lax/lax.py
Labels: cla: yes

#2619 DOC: note how derivatives are computed for CG
  jax/scipy/sparse/linalg.py
Labels: cla: yes

#2621 Add import from scipy.sparse
  jax/scipy/__init__.py
  jax/scipy/sparse/linalg.py
Labels: cla: yes

#2623 Remove unnecessary code in colabs
  docs/notebooks/Neural_Network_and_Data_Loading.ipynb
  docs/notebooks/autodiff_cookbook.ipynb
  docs/notebooks/neural_network_with_tfds_data.ipynb
  docs/notebooks/vmapped_log_probs.ipynb
Labels: cla: yes

#2610 Add support for interpolation options in quantile() and percentile()
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#2624 Enable a disabled convolution test.
  tests/lax_test.py
Labels: cla: yes

#2627 jit(): raise TypeError if called on generator function
  jax/api.py
  tests/api_test.py
Labels: cla: yes

#2626 Make median() more efficient & handle infs correctly
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#2625 Mark primitive parameters as keyword-only arguments in rules in lax.py.
  jax/lax/lax.py
Labels: cla: yes

#2633 Enable some GPU and TPU tests that now pass.
  tests/lax_test.py
Labels: cla: yes

#2636 Glob over subdirectories in top-level BUILD file.
  jax/BUILD
Labels: cla: yes

#2638 Fully stage out scan under jit.
  jax/lax/lax_control_flow.py
  tests/api_test.py
Labels: cla: yes

#2641 Update scan jaxpr documentation.
  docs/jaxpr.rst
Labels: cla: yes

#2631 Implement np.copysign
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#2637 Add jet rules for expm1 and log1p
  jax/experimental/jet.py
  tests/jet_test.py
Labels: cla: yes

#2642 Add implementation of np.trunc
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#2646 Add a link to Google's codesearch for JAX.
  README.md
Labels: cla: yes

#2644 Add type annotations to user-facing functions in lax.py
  jax/lax/lax.py
Labels: cla: yes

#2647 Fix up previous jaxpr.rst commit.
  docs/jaxpr.rst
Labels: cla: yes

#2654 fix jaxpr invar avals
  jax/interpreters/partial_eval.py
Labels: cla: yes

#2573 Disable gradients of custom_linear_solve for complex dtypes
  jax/lax/lax_control_flow.py
  tests/lax_control_flow_test.py
Labels: cla: yes

#2485 Use custom_jvp for lax.custom_root.
  jax/lax/lax_control_flow.py
  tests/lax_control_flow_test.py
Labels: cla: yes

#2455 Added type annotations and comments related to partial evaluation.
  docs/developer.rst
  docs/notebooks/Writing_custom_interpreters_in_Jax.ipynb
  jax/api.py
  jax/core.py
  jax/custom_derivatives.py
  jax/experimental/loops.py
  jax/interpreters/ad.py
  jax/interpreters/batching.py
  jax/interpreters/partial_eval.py
  jax/interpreters/pxla.py
  jax/interpreters/sharded_jit.py
  jax/interpreters/xla.py
  jax/lax/lax.py
  jax/lax/lax_control_flow.py
  jax/test_util.py
  tests/core_test.py
  tests/lax_control_flow_test.py
  tests/lax_numpy_test.py
  tests/linalg_test.py
  tests/random_test.py
Labels: cla: yes

#2659 Fix type hints for pytype
  jax/interpreters/partial_eval.py
Labels: cla: yes

#2602 make float and complex builtins error on Tracers
  jax/core.py
  tests/api_test.py
Labels: cla: yes

#2655 Renable custom_linear_solve and cg with complex values
  jax/lax/lax_control_flow.py
  jax/scipy/sparse/linalg.py
  tests/lax_control_flow_test.py
  tests/lax_scipy_sparse_test.py
Labels: cla: yes

#2656 Docstring for test_util.check_grads
  jax/test_util.py
Labels: cla: yes

#2658 Fixes a fallthrough in the tensordot axes verification logic
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#2635 Add batch_group_count to conv_general_dilated.
  jax/lax/lax.py
  jaxlib/version.py
  tests/lax_test.py
Labels: cla: yes

#2665 Add "callback_transform", two examples, and tests.
  jax/experimental/callback.py
  tests/callback_test.py
Labels: cla: yes

#2666 Remove unnecessary pip code
  cloud_tpu_colabs/JAX_demo.ipynb
  cloud_tpu_colabs/Lorentz_ODE_Solver.ipynb
  cloud_tpu_colabs/Pmap_Cookbook.ipynb
  cloud_tpu_colabs/Wave_Equation.ipynb
  examples/control.py
  examples/control_test.py
  jax/scipy/stats/logistic.py
Labels: cla: yes

#2250 Port np.roots
  docs/jax.numpy.rst
  jax/numpy/__init__.py
  jax/numpy/polynomial.py
  tests/polynomial_test.py
Labels: cla: yes

#2668 Update XLA.
  WORKSPACE
Labels: cla: yes

#2670 Remove a workaround for a long-fixed XLA type conversion bug.
  jax/lax/lax.py
Labels: cla: yes

#2673 add missing instantiate_zeros in custom_jvp
  jax/custom_derivatives.py
  tests/api_test.py
Labels: cla: yes

#2669 Fix crash for NaN eigenvalues.
  jaxlib/lapack.pyx
  tests/linalg_test.py
Labels: cla: yes

#2675 Add numpy and scipy convolution wrappers
  jax/numpy/lax_numpy.py
  jax/scipy/__init__.py
  jax/scipy/signal.py
  tests/lax_numpy_test.py
  tests/scipy_signal_test.py
Labels: cla: yes

#2678 Added missing import warnings
  jax/scipy/signal.py
Labels: cla: yes

#2679 Relax tolerance for new test on TPU
  tests/lax_numpy_test.py
Labels: cla: yes

#2681 Improve error message for indexing into an empty dimension
  jax/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: cla: yes

#2688 Add implementation of np.rollaxis
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#2689 Relax tolerance for LaxBackedNumpyTests.testConvolutions
  tests/lax_numpy_test.py
Labels: cla: yes

#2674 Make pytest run over JAX tests warning clean, and error on warnings.
  .travis.yml
  jax/lax/lax.py
  jax/lax/lax_fft.py
  jax/lax_reference.py
  jax/numpy/lax_numpy.py
  jax/test_util.py
  pytest.ini
  tests/api_test.py
  tests/lax_numpy_indexing_test.py
  tests/lax_numpy_test.py
  tests/lax_scipy_sparse_test.py
  tests/lax_test.py
  tests/linalg_test.py
  tests/parallel_test.py
  tests/pmap_test.py
  tests/random_test.py
  tests/tree_util_tests.py
Labels: cla: yes

#2693 Import std::isnan from cmath rather than assuming it is in the global…
  jaxlib/lapack.pyx
Labels: cla: yes

#2677 Add `--export_dir` and `--baseline_dir` flags to benchmark.py.
  benchmarks/benchmark.py
Labels: cla: yes

#2695 Add implementation of numpy packbits() and unpackbits()
  docs/jax.numpy.rst
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#2699 Update XLA.
  WORKSPACE
Labels: cla: yes

#2696 Implement jax.ops.index_mul.
  docs/jax.ops.rst
  jax/lax/lax.py
  jax/ops/__init__.py
  jax/ops/scatter.py
  tests/lax_numpy_indexing_test.py
Labels: cla: yes

#2698 add custom_jvp for logaddexp / logaddexp2
  jax/interpreters/ad.py
  jax/lax/__init__.py
  jax/numpy/lax_numpy.py
  jax/test_util.py
  tests/lax_numpy_test.py
  tests/nn_test.py
Labels: cla: yes

#2701 Add missing functions to autodoc lists
  docs/jax.numpy.rst
  docs/jax.scipy.rst
Labels: cla: yes

#2703 Update XLA.
  WORKSPACE
Labels: cla: yes

#2702 Fix packbits/unpackbits tests
  tests/lax_numpy_test.py
Labels: cla: yes

#2704 Make type of value_and_grad slightly more precise.
  jax/api.py
Labels: cla: yes

#2692 Fix minor typo in cell
  docs/notebooks/autodiff_cookbook.ipynb
Labels: cla: yes

#2707 Update semantics of to_dlpack.
  jax/dlpack.py
  tests/array_interoperability_test.py
Labels: cla: yes

#2687 Add type annotations to optix.
  jax/experimental/optix.py
Labels: cla: yes

#2710 Update np.linalg docs with missing funcitons
  docs/jax.numpy.rst
Labels: cla: yes

#2711 Implement numpy fmin() & fmax()
  docs/jax.numpy.rst
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#2686 Add some type annotations to jax.random and jnp.ndarray.
  .gitignore
  jax/numpy/lax_numpy.py
  jax/random.py
Labels: cla: yes

#2652 jet of pow using comp with exp, mul, log
  jax/experimental/jet.py
  tests/jet_test.py
Labels: cla: yes

#2713 Fix some test failures.
  jax/BUILD
  jax/experimental/callback.py
  jax/scipy/signal.py
  tests/array_interoperability_test.py
  tests/jet_test.py
  tests/lax_scipy_sparse_test.py
  tests/profiler_test.py
  tests/scipy_signal_test.py
Labels: cla: yes

#2706 Instantiate RNG in testcase instead of test harness in a few more pla…
  tests/lax_numpy_test.py
Labels: cla: yes

#2715 Plumb precision argument into convolution in signal.py
  jax/scipy/signal.py
Labels: cla: yes

#2717 Fixup complex values and tol in tests for jax.scipy.linalg.sparse.cg
  jax/scipy/sparse/linalg.py
  tests/lax_scipy_sparse_test.py
Labels: cla: yes

#2722 Explicitly build specific CUDA capabilities.
  build/build.py
Labels: cla: yes

#2723 Add a dynamic type check that the value returned by an XLA translatio…
  jax/interpreters/xla.py
Labels: cla: yes

#2142 Allow ShardedDeviceArrays to represent arbitrary data shardings.
  jax/interpreters/pxla.py
  jax/lax/lax.py
  tests/benchmarks/xla.py
  tests/pmap_test.py
Labels: cla: yes

#2727 Add type hint to fix pytype error.
  jax/interpreters/pxla.py
Labels: cla: yes

#2726 Implement numpy.linalg.multi_dot
  docs/jax.numpy.rst
  jax/numpy/linalg.py
  jax/third_party/numpy/linalg.py
  tests/linalg_test.py
Labels: cla: yes

#2733 Update XLA.
  WORKSPACE
Labels: cla: yes

#2730 Temporarily make ShardedDeviceArray.__init__ optionally accept old si…
  jax/interpreters/pxla.py
Labels: cla: yes

#2732 Fix some bugs in _reshape_sharded_device_array
  jax/lax/lax.py
  tests/pmap_test.py
Labels: cla: yes

#2738 Actually use xla._device_put_scalar for device-putting scalars
  jax/interpreters/xla.py
Labels: cla: yes

#2740 Release jaxlib 0.1.44.
  README.md
  docs/CHANGELOG.rst
Labels: cla: yes

#2724 Add numpy.rint to lax numpy
  docs/jax.numpy.rst
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#2741 Add a regression test that runs the same computation on all devices t…
  tests/api_test.py
Labels: cla: yes

#2746 fix scipy_signal_test convolve failures
  tests/scipy_signal_test.py
Labels: cla: yes

#2743 Some cleanup and reformatting in `xla.py`.
  jax/interpreters/xla.py
Labels: cla: yes

#2497 Add a better error message for grad of while not supported
  jax/interpreters/partial_eval.py
  jax/lax/lax_control_flow.py
  tests/lax_control_flow_test.py
Labels: cla: yes

#2754 Assert that reduction computations don't have constants.
  jax/lax/lax.py
Labels: cla: yes

#2750 Raise an error if stop_gradient is called on non-arrays
  jax/lax/lax.py
  jax/numpy/linalg.py
  jax/scipy/linalg.py
  tests/lax_test.py
Labels: cla: yes

#2684 Syntactic sugar for indexed update functions.
  docs/jax.ops.rst
  jax/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: cla: yes

#2757 skip two unreliable tests
  tests/lax_test.py
  tests/linalg_test.py
Labels: cla: yes

#2758 Update automatic jaxlib install command to use nvidia-smi instead of …
  README.md
Labels: cla: yes

#2761 Fixes in the FAQ for RST
  docs/CHANGELOG.rst
  docs/conf.py
  docs/faq.rst
Labels: cla: yes

#2762 Added FAQ entry about relationship between VJP and JVP
  docs/faq.rst
Labels: cla: yes

#2719 Delete cotangent references on their last use
  jax/interpreters/ad.py
Labels: cla: yes

#2773 Fix confusing documentation typo.
  jax/api.py
Labels: cla: yes

#2760 Implement np.unique
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#2778 Add pmean to lax documentation
  docs/jax.lax.rst
Labels: cla: yes

#2764 Fix docstring for jax.random.beta ("Bernoulli" -> "Beta")
  jax/random.py
Labels: cla: yes

#2780 Skip jnp.unique test on GPU
  tests/lax_numpy_test.py
Labels: cla: yes

#2763 Add AdaMax optimizer
  jax/experimental/optimizers.py
  tests/optimizers_test.py
Labels: cla: yes

#2752 Add FIXMEs for AD type errors
  jax/interpreters/ad.py
Labels: cla: yes

#2785 Bump jaxlib version to 0.1.45 and update WORKSPACE and CHANGELOG.
  WORKSPACE
  docs/CHANGELOG.rst
  jaxlib/version.py
Labels: cla: yes

#2786 try optimize=True default with einsum
  jax/numpy/lax_numpy.py
Labels: cla: yes

#2789 apply is_stable=True to sort translation rules
  jax/lax/lax.py
  tests/lax_numpy_test.py
  tests/lax_scipy_sparse_test.py
Labels: cla: yes

#2788 factor out process_map / post_process_map
  jax/core.py
  jax/interpreters/ad.py
  jax/interpreters/batching.py
  jax/interpreters/parallel.py
  jax/interpreters/partial_eval.py
  jax/interpreters/pxla.py
  tests/pmap_test.py
Labels: cla: yes

#2508 Added clearer error message for tracers in numpy.split
  docs/faq.rst
  jax/abstract_arrays.py
  jax/core.py
  jax/numpy/lax_numpy.py
  tests/api_test.py
  tests/lax_numpy_test.py
  tests/loops_test.py
Labels: better_errors, cla: yes

#2798 Switch jaxlib Python code to use the lower-level xla.ops API when bui…
  jaxlib/cuda_prng.py
  jaxlib/cusolver.py
  jaxlib/lapack.pyx
Labels: cla: yes

#2799 small typo fix
  README.md
Labels: cla: yes

#2801 loosen scipy convolve test tolerance (GPU flaky)
  tests/scipy_signal_test.py
Labels: cla: yes

#2794 Add explicit derivative for jax.numpy.linalg.pinv.
  jax/lax_linalg.py
  jax/numpy/linalg.py
  tests/linalg_test.py
Labels: cla: yes

#2653 Add jet rule for tanh
  jax/experimental/jet.py
  tests/jet_test.py
Labels: cla: yes

#2803 use _max instead of max, fix #2795
  jax/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: cla: yes

#2804 for custom_jvp/vjp nondiff_argnums, call stop_gradient
  jax/custom_derivatives.py
  tests/api_test.py
Labels: cla: yes

#2806 stop_gradient_p -> ad_util.py, re-enable some mypy
  jax/ad_util.py
  jax/custom_derivatives.py
  jax/experimental/jet.py
  jax/lax/lax.py
  jax/lax/lax_control_flow.py
  mypy.ini
Labels: cla: yes

#2807 rewrite axis_index implementation, use custom bind
  jax/interpreters/pxla.py
  tests/pmap_test.py
Labels: cla: yes

#2808 Remove usage of xla_client.{Computation,ComputationBuilder}.
  docs/notebooks/How_JAX_primitives_work.ipynb
  jax/api.py
  jax/interpreters/pxla.py
  jax/interpreters/xla.py
  jax/lax/lax.py
  jax/lax/lax_control_flow.py
  jax/lax/lax_fft.py
  jax/lax/lax_parallel.py
  jax/lax_linalg.py
  jax/lazy.py
  jax/lib/xla_bridge.py
  jax/random.py
  tests/api_test.py
  tests/infeed_test.py
  tests/metadata_test.py
Labels: cla: yes

#2810 Make ShardedDeviceArray._value threadsafe again.
  jax/interpreters/pxla.py
  tests/pmap_test.py
Labels: cla: yes

#2811 Pin mypy version in .travis.yml.
  .travis.yml
Labels: cla: yes

#2812 use static_argnums in xla_computation
  jax/api.py
  tests/api_test.py
Labels: cla: yes

#2816 Add jet rules
  jax/experimental/jet.py
  tests/jet_test.py
Labels: cla: yes

#1568 Feature/permutation
  jax/random.py
  tests/random_test.py
Labels: cla: yes

#2817 Fix time issues in odeint reverse mode
  jax/experimental/ode.py
Labels: cla: yes

#2818 add ode test file
  tests/ode_test.py
Labels: cla: yes
