Repository jax-ml/jax, pull requests merged in 2020-10, with the labels that each got.

#4039 Grad of int
  jax/__init__.py
  jax/abstract_arrays.py
  jax/ad_util.py
  jax/api.py
  jax/core.py
  jax/dtypes.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/control_flow_ops_test.py
  jax/interpreters/ad.py
  jax/interpreters/xla.py
  jax/lax/lax.py
  jax/lib/xla_bridge.py
  jax/numpy/lax_numpy.py
  tests/api_test.py
  tests/jet_test.py
  tests/lax_numpy_indexing_test.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#4430 Fix dtype behavior with float0s in CustomVJP.
  jax/core.py
  jax/interpreters/ad.py
Labels: cla: yes, pull ready

#4419 Add --exclude_test_targets to test_util
  jax/test_util.py
Labels: cla: yes, pull ready

#4431 Remove scalar float0 XLA representation.
  jax/interpreters/xla.py
  jax/lib/xla_bridge.py
Labels: cla: yes, pull ready

#4434 reduce test-case count of the numpy-dispatch CI check
  .github/workflows/ci-build.yaml
Labels: cla: yes, pull ready

#4413 numpy histogramdd implementation
  docs/jax.numpy.rst
  jax/numpy/__init__.py
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#4429 Add support for `all_to_all` in vmap
  jax/interpreters/pxla.py
  jax/lax/lax_parallel.py
  tests/batching_test.py
  tests/pmap_test.py
Labels: cla: yes, pull ready

#4439 Change select_and_scatter_add's batching rule to avoid unrolling.
  jax/lax/__init__.py
  jax/lax/lax.py
  tests/lax_vmap_test.py
Labels: cla: yes, pull ready

#4438 Adds an approximate=... keyword argument to jax.nn.gelu to select bet…
  jax/nn/functions.py
  tests/nn_test.py
Labels: cla: yes, pull ready

#4441 Implement jnp.choose
  docs/jax.numpy.rst
  jax/numpy/__init__.py
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#4445 skip test that fails due to known xla:cpu bug
  tests/lax_autodiff_test.py
Labels: cla: yes, pull ready

#4443 Improve errors for failed compilations w/ core.concrete_or_error
  jax/numpy/lax_numpy.py
Labels: better_errors, cla: yes, pull ready

#4446 Fix differentially_private_sgd.py Example
  examples/differentially_private_sgd.py
Labels: cla: yes, pull ready

#4442 Edit and fix rendering problems in lax.cond docstring.
  jax/lax/lax_control_flow.py
Labels: cla: yes, pull ready

#4444 Call check_user_dtype on all user dtypes
  jax/lax/lax.py
  jax/numpy/lax_numpy.py
Labels: better_errors, cla: yes, pull ready

#4455 Update Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
Labels: cla: yes, pull ready

#4456 remove redundant if-else
  tests/lax_control_flow_test.py
Labels: cla: yes, pull ready

#4458 Update XLA.
  WORKSPACE
Labels: cla: yes, pull ready

#4457 equation context for undefined var reads in jaxpr typechecker
  jax/core.py
  tests/core_test.py
Labels: cla: yes, pull ready

#4460 [jax2tf] Added Getting Started notebook
  jax/experimental/jax2tf/JAX2TF_getting_started.ipynb
  jax/experimental/jax2tf/README.md
Labels: cla: yes, pull ready

#4463 Revert "[jax2tf] Added Getting Started notebook (#4460)"
  jax/experimental/jax2tf/JAX2TF_getting_started.ipynb
  jax/experimental/jax2tf/README.md
Labels: cla: yes

#4464 minor change to test source sync
  jax/traceback_util.py
Labels: cla: yes, pull ready

#4467 update version and changelog for pypi
  docs/CHANGELOG.rst
  jax/version.py
Labels: cla: yes, pull ready

#4468 [jax2tf] Add the getting started notebook
  jax/experimental/jax2tf/JAX2TF_getting_started.ipynb
  jax/experimental/jax2tf/README.md
Labels: cla: yes, pull ready

#4479 Ignore an incorrect mypy error.
  jax/linear_util.py
  tests/jax_jit_test.py
Labels: cla: yes, pull ready

#4482 early return for non-existent path prefixes
  jax/traceback_util.py
Labels: cla: yes, pull ready

#4485 Switch implementation of jnp.isnan(x) to x != x.
  jax/numpy/lax_numpy.py
Labels: cla: yes, pull ready

#4489 test fixes in jax_jit_test
  tests/jax_jit_test.py
Labels: cla: yes, pull ready

#4491 remove an always-skipped lax_numpy test
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#4475 [jax2tf] Fix min_max and add_mul harnesses.
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes, pull ready

#4501 [jax2tf] Ensure that in tests TF does not constant-fold in eager mode…
  jax/experimental/jax2tf/tests/control_flow_ops_test.py
  jax/experimental/jax2tf/tests/tf_test_util.py
Labels: cla: yes, pull ready

#4500 Recast int/bool tangents to float0 in custom_jvp/vjps
  jax/custom_derivatives.py
  jax/interpreters/ad.py
  tests/api_test.py
Labels: cla: yes, pull ready

#4502 Enable TPU linalg tests that now pass.
  tests/linalg_test.py
Labels: cla: yes, pull ready

#4498 Add a flag to control the C++ jax.jit behavior.
  jax/api.py
Labels: cla: yes, pull ready

#4507 Update XLA.
  WORKSPACE
Labels: cla: yes, pull ready

#4508 Skip 2nd order grad in expm tests.
  tests/linalg_test.py
Labels: cla: yes, pull ready

#4161 raise_to_shaped: preserve weak_type by default
  jax/core.py
  jax/custom_derivatives.py
  jax/experimental/jax2tf/jax2tf.py
  jax/interpreters/ad.py
  jax/lax/lax_control_flow.py
  tests/core_test.py
  tests/lax_control_flow_test.py
  tests/multi_device_test.py
  tests/pmap_test.py
Labels: cla: yes, pull ready

#4511 move a debug_nans test into debug_nans test file
  tests/api_test.py
  tests/debug_nans_test.py
Labels: cla: yes, pull ready

#4512 lax_control_flow: retry via function rather than via loop
  jax/lax/lax_control_flow.py
  tests/lax_control_flow_test.py
Labels: cla: yes, pull ready

#4515 re-enable lax autodiff test
  tests/lax_autodiff_test.py
Labels: cla: yes, pull ready

#4514 remove mysterious code that is no longer needed
  jax/lax/lax_control_flow.py
Labels: cla: yes, pull ready

#4517 optimize scan partial_eval to fix #4510
  jax/core.py
  jax/lax/lax_control_flow.py
Labels: cla: yes, pull ready

#4518 [jax2tf] Fix the behavior for shift when the shift amount is negative…
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/primitives_with_limited_support.md.template
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
  jax/experimental/jax2tf/tests/tf_test_util.py
Labels: cla: yes, pull ready

#4470 [jax2tf] Port jax2tf to use omnistaging
  jax/core.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/tf_test_util.py
Labels: cla: yes, pull ready

#4526 make scan fwd raw extensive inputs as DeviceArray
  jax/lax/lax_control_flow.py
  tests/lax_control_flow_test.py
Labels: cla: yes, pull ready

#4524 Fix extraneous dtype warning in jnp.mean
  jax/numpy/lax_numpy.py
Labels: better_errors, cla: yes, pull ready

#4065 Use local version identifiers to distribute cuda jaxlib wheels.
  README.md
  build/build_jaxlib_wheels.sh
  build/build_wheel_docker_entrypoint.sh
  build/generate_release_index.py
  build/setup.py
Labels: cla: yes, pull ready

#4532 [jax2tf] Ensure jax2tf still works without omnistaging
  jax/experimental/jax2tf/jax2tf.py
Labels: cla: yes, pull ready

#4509 Mark pmin and pmax as multi-host supported.
  jax/lax/lax_parallel.py
Labels: cla: yes, pull ready

#4538 ignore mypy error in jax2tf
  jax/experimental/jax2tf/jax2tf.py
Labels: cla: yes, pull ready

#4542 fix jax2tf readme typo: "differentiaion"
  jax/experimental/jax2tf/README.md
Labels: cla: yes, pull ready

#4440 wrap long line
  jax/numpy/lax_numpy.py
Labels: cla: yes, pull ready

#4546 Fix batching_test flakiness on GPU.
  tests/batching_test.py
Labels: cla: yes, pull ready

#4554 Update XLA in WORKSPACE
  WORKSPACE
Labels: cla: yes, pull ready

#4547 Enrich the error messages with the bound names that are available.
  jax/api.py
  jax/core.py
  jax/experimental/general_map.py
Labels: cla: yes, pull ready

#4548 Ensure values returned by jax.random.truncated_normal() are in range.
  jax/random.py
  tests/random_test.py
Labels: cla: yes, pull ready

#4543 remove a double warning message with asarray
  jax/numpy/lax_numpy.py
Labels: cla: yes, pull ready

#4522 [jax2tf] Add paths that do not use XLA in conv_general_dilated.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes, pull ready

#4561 Add stop_gradients around lax.nextafter to fix TFP gradient errors fo…
  jax/random.py
Labels: cla: yes, pull ready

#4530 Cleanup: remove extraneous device_put
  jax/lax/lax.py
Labels: cla: yes, pull ready

#4562 [jax2tf] Added paths without einsum for dot_general.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes, pull ready

#4556 BUG: fix indexing error
  jax/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: cla: yes, pull ready

#4570 assume less about source locations in jaxpr_util_test
  tests/jaxpr_util_test.py
Labels: cla: yes, pull ready

#4563 Improve pmap axis error in the presence of pytrees
  jax/api.py
Labels: cla: yes, pull ready

#4567 Update jaxlib build scripts to build CUDA 11.1 wheels.
  build/build_jaxlib_wheels.sh
  build/install_cuda.sh
Labels: cla: yes, pull ready

#4573 update version and changelog for pypi
  docs/CHANGELOG.rst
  jax/interpreters/xla.py
  jax/version.py
Labels: cla: yes, pull ready

#4360 [jax2tf] Added support for shape polymorphism conversion.
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/control_flow_ops_test.py
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/primitives_test.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  jax/experimental/jax2tf/tests/tf_test_util.py
  jax/interpreters/masking.py
Labels: cla: yes, pull ready

#4577 update version and changelog for pypi
  docs/CHANGELOG.rst
  jax/version.py
Labels: cla: yes, pull ready

#4584 Fix typo.
  tests/jax_jit_test.py
Labels: cla: yes, pull ready

#4578 Change scatter JVP rule to avoid using floating-point representation …
  jax/lax/lax.py
Labels: cla: yes, pull ready

#4579 multi-buf: fix donated_invars in _xla_callable
  jax/api.py
  jax/interpreters/pxla.py
  jax/interpreters/xla.py
Labels: cla: yes, pull ready

#4582 Fix CUDA launch error when generating an empty PRNG array.
  jax/random.py
  tests/random_test.py
Labels: cla: yes, pull ready

#4535 don't generate lazy iota/eye/tri/delta with omnistaging
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/lax/lax.py
  jax/random.py
  tests/api_test.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#4586 Support specifying precision as a tuple of precision enums
  jax/lax/lax.py
  jax/numpy/lax_numpy.py
  tests/lax_test.py
Labels: cla: yes, pull ready

#4575 Check that the init_value in reduce_window is indeed a scalar.
  jax/lax/lax.py
  tests/lax_test.py
Labels: cla: yes, pull ready

#4541 Export expit and logsumexp in jax.nn.functions
  docs/jax.nn.rst
  jax/nn/__init__.py
  jax/nn/functions.py
Labels: cla: yes, pull ready

#4589 [jax2tf] Added a non-XLA conversion path for reduce_window_max.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/primitive_harness.py
Labels: cla: yes, pull ready

#4587 Improve documentation for a number of lax functions.
  docs/jax.lax.rst
  jax/lax/lax.py
  jax/lax/lax_control_flow.py
Labels: cla: yes, pull ready

#4595 allow custom_vjp bwd to return Nones for zeros
  jax/custom_derivatives.py
  tests/api_test.py
Labels: cla: yes, pull ready

#4599 Fix incorrect slice gradient when a slice has zero size and striding.
  jax/lax/lax.py
  tests/lax_autodiff_test.py
Labels: cla: yes, pull ready

#4602 remove an extraneous replace_float0s
  jax/interpreters/ad.py
  tests/api_test.py
Labels: cla: yes, pull ready

#4603 Optimize lax.associative_scan, reimplement cumsum, etc. on top of associative_scan.
  docs/jax.lax.rst
  jax/experimental/jet.py
  jax/lax/__init__.py
  jax/lax/lax.py
  jax/lax/lax_control_flow.py
  tests/lax_control_flow_test.py
Labels: cla: yes, pull ready

#4605 temporarily work around a bug that #4008 will fix
  jax/custom_derivatives.py
Labels: cla: yes, pull ready

#4596 [jax2tf] Implemented conversion for triangular_solve.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes, pull ready

#4607 [jax2tf] Remove the argument type promotion in jax2tf.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/primitive_harness.py
Labels: cla: yes, pull ready

#4608 [host_callback] Added support for remat.
  jax/experimental/host_callback.py
  jax/interpreters/xla.py
  tests/host_callback_test.py
Labels: cla: yes, pull ready

#4614 Add a reverse=... argument to lax.cumsum/cumprod/...
  jax/experimental/jet.py
  jax/lax/lax_control_flow.py
  tests/lax_autodiff_test.py
  tests/lax_test.py
  tests/lax_vmap_test.py
Labels: cla: yes, pull ready

#4593 Fix init with constant Poly shapes
  jax/interpreters/masking.py
Labels: cla: yes, pull ready

#3712 clean up jax internals in preparation for only allowing hashable values passed as static args
  docs/notebooks/vmapped_log_probs.ipynb
  jax/numpy/lax_numpy.py
  tests/generated_fun_test.py
  tests/lax_numpy_test.py
  tests/pmap_test.py
  tests/polynomial_test.py
Labels: cla: yes, pull ready

#4620 Add default implementation of process_custom_jvp_call process_custom_vjp_call to `jax.experimental.callback`
  jax/experimental/callback.py
  tests/callback_test.py
Labels: cla: yes, pull ready

#4621 Move jax.numpy internals into jax._src.numpy.
  jax/_src/numpy/__init__.py
  jax/_src/numpy/fft.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/linalg.py
  jax/_src/numpy/polynomial.py
  jax/_src/numpy/util.py
  jax/_src/numpy/vectorize.py
  jax/_src/scipy/linalg.py
  jax/_src/scipy/ndimage.py
  jax/_src/scipy/signal.py
  jax/_src/scipy/special.py
  jax/_src/scipy/stats/bernoulli.py
  jax/_src/scipy/stats/beta.py
  jax/_src/scipy/stats/cauchy.py
  jax/_src/scipy/stats/dirichlet.py
  jax/_src/scipy/stats/expon.py
  jax/_src/scipy/stats/gamma.py
  jax/_src/scipy/stats/geom.py
  jax/_src/scipy/stats/laplace.py
  jax/_src/scipy/stats/logistic.py
  jax/_src/scipy/stats/multivariate_normal.py
  jax/_src/scipy/stats/norm.py
  jax/_src/scipy/stats/pareto.py
  jax/_src/scipy/stats/poisson.py
  jax/_src/scipy/stats/t.py
  jax/_src/scipy/stats/uniform.py
  jax/lax/lax_parallel.py
  jax/lax_linalg.py
  jax/numpy/__init__.py
  jax/numpy/fft.py
  jax/numpy/linalg.py
  jax/ops/scatter.py
  jax/random.py
  jax/third_party/numpy/linalg.py
  tests/masking_test.py
  tests/polynomial_test.py
Labels: cla: yes, pull ready

#4623 fix api.linearize type check, and ConcreteArray lattice joins
  jax/api.py
  jax/core.py
  tests/api_test.py
Labels: cla: yes, pull ready

#4625 Make pad more robust to non-hashable values.
  jax/_src/numpy/lax_numpy.py
Labels: cla: yes, pull ready

#4624 Make `ConvGeneralDilatedDimensionNumbers` type public
  jax/lax/__init__.py
Labels: cla: yes, pull ready

#4634 Import jax.nn.functions by default to fix breakage.
  jax/nn/__init__.py
Labels: cla: yes, pull ready

#4613 [jax2tf] Implemented conversion of lu_p using _convert_jax_impl.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes, pull ready

#4616 [jax2tf] Implemented a conversion for linear_solve_p
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes, pull ready

#4642 A couple of typo/gap fixes in PRNG design notes
  design_notes/prng.md
Labels: cla: yes, pull ready

#4641 Add deprecation warning for indexing with non-tuple sequences
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#4580 Update README, CHANGELOG, and jaxlib.__version__ for new jaxlib release
  README.md
  docs/CHANGELOG.rst
  jaxlib/version.py
Labels: cla: yes, pull ready

#4571 Mention how to turn on logging in "No GPU/TPU found" warning.
  jax/lib/xla_bridge.py
Labels: cla: yes, pull ready

#4647 update version and changelog for pypi
  docs/CHANGELOG.rst
  jax/version.py
Labels: cla: yes, pull ready

#4652 Add missing jax.scipy.stats distributions to the docs.
  docs/jax.scipy.rst
  jax/scipy/stats/__init__.py
Labels: cla: yes, pull ready

#4655 Don't turn on C++ jit by default until we're sure it works everywhere.
  jax/api.py
Labels: cla: yes, pull ready

#4656 Update XLA.
  WORKSPACE
  docs/CHANGELOG.rst
Labels: cla: yes, pull ready

#4657 Update README and jaxlib.__version__ for new jaxlib release
  README.md
  jaxlib/version.py
Labels: cla: yes, pull ready

#4662 added test skips based on jaxlib version
  tests/array_interoperability_test.py
Labels: cla: yes, pull ready

#4664 fixes on #4008
  docs/custom_vjp_update.md
  jax/custom_derivatives.py
Labels: cla: yes, pull ready

#4663 improve an escaped tracer error
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: cla: yes, pull ready

#4665 fix a custom_jvp vmap bug from @dpfau
  jax/custom_derivatives.py
  tests/api_test.py
Labels: cla: yes, pull ready

#4650 Ensure that check_jaxpr is done with abstract values
  jax/core.py
Labels: cla: yes, pull ready

#4459 Add `lax.conv_general_dilated_patches`
  docs/jax.lax.rst
  jax/_src/lax/lax.py
  jax/_src/lax/other.py
  jax/lax/__init__.py
  tests/lax_test.py
Labels: cla: yes, pull ready

#4635 [impl] Add support for setdiff1d
  docs/jax.numpy.rst
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#4644 Also convert numpy arrays to hashable values.
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#4681 Fix a bug in `make_jaxpr`, as static-arguments should be passed as is
  jax/api.py
Labels: cla: yes, pull ready

#4684 Cleanup: pass function name rather than function object
  jax/_src/numpy/lax_numpy.py
Labels: cla: yes, pull ready

#4685 make lax.dynamic_slice transpose handle symbolic zeros
  jax/_src/lax/lax.py
Labels: cla: yes, pull ready

#4686 redo #4535 lazy simplification
  jax/_src/lax/lax.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/random.py
  tests/api_test.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#4658 [multi-buf] simplify custom object test avals
  tests/custom_object_test.py
Labels: cla: yes, pull ready

#4661 Emit a warning on non-hashable static arguments in jax.jit.
  jax/api.py
  jax/api_util.py
Labels: cla: yes, pull ready

#4700 Add PocketFFT mirror to fix download problems for some Bazel versions.
  third_party/pocketfft/workspace.bzl
Labels: cla: yes, pull ready

#4698 add jax.custom_gradient wrapper for jax.custom_vjp
  jax/api.py
  jax/custom_derivatives.py
  tests/api_test.py
Labels: cla: yes, pull ready

#4702 FIX: example usage of optimizers API in module docstring
  jax/experimental/optimizers.py
Labels: cla: yes, pull ready

#4709 update version and changelog for pypi
  docs/CHANGELOG.rst
  jax/version.py
Labels: cla: yes, pull ready

#4707 register filtered stack trace path exclusions from outside of `traceback_util`
  jax/abstract_arrays.py
  jax/ad_util.py
  jax/api.py
  jax/api_util.py
  jax/core.py
  jax/custom_derivatives.py
  jax/dtypes.py
  jax/experimental/callback.py
  jax/interpreters/__init__.py
  jax/interpreters/sharded_jit.py
  jax/lazy.py
  jax/linear_util.py
  jax/pprint_util.py
  jax/source_info_util.py
  jax/traceback_util.py
  jax/tree_util.py
  jax/util.py
Labels: cla: yes, pull ready

#4695 Fixes #4692 and #4594
  jax/_src/scipy/optimize/line_search.py
  jax/_src/scipy/optimize/minimize.py
  tests/scipy_optimize_test.py
Labels: cla: yes, pull ready

#4708 fix jit docstring's formatting
  jax/api.py
Labels: cla: yes, pull ready

#4713 simplify select jvp
  jax/_src/lax/lax.py
  jax/experimental/jet.py
  jax/lax/__init__.py
  tests/lax_test.py
Labels: cla: yes, pull ready

#4716 Update CHANGELOG
  docs/CHANGELOG.rst
Labels: cla: yes, pull ready

#4726 remove unused import
  jax/api_util.py
Labels: cla: yes, pull ready

#4720 mention static_argnum values should be immutable
  jax/api.py
Labels: cla: yes, pull ready

#4727 [jax2tf] Expanding jax2tf shape polymorphism.
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/__init__.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  jax/interpreters/masking.py
Labels: cla: yes, pull ready

#4731 Add explicit tests of weak/strong promotion semantics
  tests/dtypes_test.py
Labels: cla: yes, pull ready

#4691 [jax2tf] Fix implementation and tests of select_and_scatter_add conversion.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes, pull ready

#4706 Add support for vmap collectives in control flow primitives
  jax/_src/lax/control_flow.py
  jax/_src/lax/parallel.py
  jax/core.py
  jax/custom_derivatives.py
  jax/interpreters/batching.py
  jax/interpreters/pxla.py
  tests/lax_control_flow_test.py
Labels: cla: yes, pull ready

#4732 Add reference on RK45
  jax/experimental/ode.py
Labels: cla: yes, pull ready

#4738 Expand type promotion test to cover x32 mode
  tests/dtypes_test.py
Labels: cla: yes, pull ready

#4737 Switch to declarative weak dtype promotion rules.
  jax/dtypes.py
  jax/interpreters/partial_eval.py
  tests/dtypes_test.py
Labels: cla: yes, pull ready

#4736 [jax2tf] Reduce number of tests for the conversion of scatter.
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/primitive_harness.py
Labels: cla: yes, pull ready

#4735 [jax2tf] Cleanup FFT conversion and reduce the number of tests.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes, pull ready

#3422 link to nn libraries in readme
  README.md
Labels: cla: yes, pull ready

#4739 revise pytree docs to remove contradiction
  docs/pytrees.rst
Labels: cla: yes, pull ready

#4740 [jax2tf] Reduce number of tests for select_and_gather_add.
  jax/experimental/jax2tf/tests/primitive_harness.py
Labels: cla: yes, pull ready
