Repository jax-ml/jax, pull requests merged in 2020-02, with the labels that each got.

#2136 fix remat with nontrivial env
  jax/api.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: cla: yes

#2137 Upgrade bazel from 0.29.1 to 1.2.1
  build/build.py
Labels: cla: yes

#2147 Bump cell execution timeout
  docs/conf.py
Labels: cla: yes

#2145 Make stax pooling layers accept `spec=None`
  jax/experimental/stax.py
Labels: cla: yes

#2138 Better batching rule for triangular_solve
  jax/lax_linalg.py
  tests/linalg_test.py
Labels: cla: yes

#2150 Avoid accidental type promotion in gamma sampler gradient.
  jax/random.py
  tests/random_test.py
Labels: cla: yes

#2149 Add jax.scipy.stats.logistic to documentation.
  docs/jax.scipy.rst
Labels: cla: yes

#2159 Fix precision in triangular solve batching test for TPUs
  tests/linalg_test.py
Labels: cla: yes

#2158 WIP sharded_jit implementation
  jax/interpreters/sharded_jit.py
Labels: cla: yes

#2162 Update linspace edgecase to match numpy fix.
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#1850 Add np.fft.fftshift/ifftshift
  jax/numpy/fft.py
  tests/fft_test.py
Labels: cla: yes

#2034 Added dtype arg for NN initializer factory methods
  jax/nn/initializers.py
  tests/nn_test.py
Labels: cla: yes

#1959 An attempt to remove freevars from JAXPR.
  CHANGELOG.md
  docs/notebooks/Writing_custom_interpreters_in_Jax.ipynb
  jax/api.py
  jax/core.py
  jax/interpreters/ad.py
  jax/interpreters/partial_eval.py
  jax/interpreters/pxla.py
  jax/interpreters/xla.py
  jax/lax/lax.py
  jax/lax/lax_control_flow.py
  jax/test_util.py
  tests/api_test.py
Labels: cla: yes

#2165 Canonicalize the shape in the wrapper functions in random.py.
  jax/abstract_arrays.py
  jax/lax/lax.py
  jax/random.py
  tests/random_test.py
Labels: cla: yes

#2171 Fix type error in partial_eval.py.
  jax/interpreters/partial_eval.py
Labels: cla: yes

#2167 Simplify bound_subjaxprs.
  jax/core.py
  jax/experimental/loops.py
  jax/interpreters/ad.py
  jax/interpreters/partial_eval.py
  jax/interpreters/pxla.py
  jax/interpreters/sharded_jit.py
  jax/interpreters/xla.py
  jax/lax/lax_control_flow.py
  jax/test_util.py
  tests/api_test.py
Labels: cla: yes

#2169 Disabled tests known to fail on Mac, and optionally slow tests.
  CHANGELOG.md
  docs/developer.rst
  jax/api.py
  jax/config.py
  jax/interpreters/xla.py
  jax/numpy/lax_numpy.py
  jax/test_util.py
  tests/lax_control_flow_test.py
  tests/lax_test.py
  tests/linalg_test.py
  tests/nn_test.py
Labels: cla: yes

#2186 Ensure AxisEnv is instantiated with tuples
  jax/interpreters/pxla.py
  jax/interpreters/xla.py
  tests/pmap_test.py
Labels: cla: yes

#2183 make pmap inside of eager scan work, fixes #2018
  jax/interpreters/pxla.py
  jax/interpreters/xla.py
  jax/lax/lax.py
  jax/lax/lax_control_flow.py
  tests/pmap_test.py
Labels: cla: yes

#2182 Use 64-bit integers for indexing if any tensor dimension exceeds 2^31…
  jax/numpy/lax_numpy.py
Labels: cla: yes

#2191 relax the ndim>=1 condition of tensordot
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#2125 Implementation of np.linalg.{cond, tensorinv}
  jax/numpy/linalg.py
  jax/third_party/__init__.py
  jax/third_party/numpy/LICENSE
  jax/third_party/numpy/__init__.py
  jax/third_party/numpy/linalg.py
  tests/linalg_test.py
Labels: cla: yes

#2193 fix cond batching bug reading axis size
  jax/lax/lax_control_flow.py
Labels: cla: yes

#2196 Fix broken link in README
  README.md
Labels: cla: yes

#2192 Fix expm(zeros((n, n))) == NaN. (#2131)
  jax/scipy/linalg.py
  tests/linalg_test.py
Labels: cla: yes

#2119 Implementation of np.linalg.tensorsolve.
  jax/numpy/linalg.py
  jax/third_party/numpy/linalg.py
  tests/linalg_test.py
Labels: cla: yes

#2202 Added License to new files
  jax/third_party/__init__.py
  jax/third_party/numpy/__init__.py
  jax/third_party/numpy/linalg.py
Labels: cla: yes

#2204 Disable linalg_test.testCond.
  tests/linalg_test.py
Labels: cla: yes

#2207 Reenable convolution gradient tests on TPU that now pass.
  tests/lax_test.py
Labels: cla: yes

#2208 Add missing sources to jax build.
  jax/BUILD
Labels: cla: yes

#2205 Removed copyright from third-party/numpy
  jax/third_party/README.md
  jax/third_party/__init__.py
  jax/third_party/numpy/__init__.py
  jax/third_party/numpy/linalg.py
Labels: cla: yes

#2194 Fix Gotchas notebook regarding control flow differentiation.
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
Labels: cla: yes

#2199 Fix inconsistent indentation in `JaxprTrace.default_process_primitive`.
  jax/interpreters/partial_eval.py
Labels: cla: yes

#2176 Simplify Jaxpr: remove the bound_subjaxpr field, all subjaxprs are in…
  CHANGELOG.md
  jax/core.py
  jax/interpreters/ad.py
  jax/interpreters/partial_eval.py
  jax/interpreters/pxla.py
  jax/interpreters/sharded_jit.py
  jax/interpreters/xla.py
  jax/test_util.py
  tests/api_test.py
  tests/linalg_test.py
Labels: cla: yes

#2213 fix multi-device error messages
  .travis.yml
  jax/interpreters/xla.py
Labels: cla: yes

#2214 more nonlinear evaluation in backward_pass.py
  jax/interpreters/ad.py
  jax/lax/lax_control_flow.py
  tests/api_test.py
Labels: cla: yes

#2217 Try downloading bazel before using pre-installed bazel.
  build/build.py
Labels: cla: yes

#2218 Return error number in build.py on bad bazel version.
  build/build.py
Labels: cla: yes

#2146 Add jax.numpy.vectorize
  docs/jax.rst
  jax/experimental/vectorize.py
  jax/numpy/__init__.py
  jax/numpy/vectorize.py
  tests/lax_numpy_vectorize_test.py
Labels: cla: yes

#2144 Consolidate LU solve logic from scipy/numpy in lax_linalg.lu_solve
  jax/lax_linalg.py
  jax/numpy/linalg.py
  jax/scipy/linalg.py
  tests/linalg_test.py
Labels: cla: yes

#2212 Prefix PRNG Part 1: test for reproducible PRNG across JAX versions
  tests/random_test.py
Labels: cla: yes

#2221 Fix minor bug in bernoulli.pmf
  jax/scipy/stats/bernoulli.py
Labels: cla: yes

#2223 Make `core.call_p` a call primitive.
  jax/core.py
Labels: cla: yes

#2216 Added the first draft of the Jaxpr documentation.
  docs/index.rst
  docs/jax.dlpack.rst
  docs/jax.rst
  docs/jax_internal_api.rst
  docs/jaxpr.rst
  docs/modules.rst
  jax/api.py
  jax/core.py
  jax/interpreters/batching.py
  jax/test_util.py
  jax/tree_util.py
  tests/api_test.py
Labels: cla: yes

#2017 Allow shapecheck of PixelCNN++
  jax/api.py
  jax/interpreters/masking.py
  jax/interpreters/xla.py
  jax/lax/lax.py
  jax/lax/lax_control_flow.py
  jax/numpy/lax_numpy.py
  jax/random.py
  tests/masking_test.py
Labels: cla: yes

#1786 Adding `broadcast_argnums` to `pmap` for allowing similar behaviour t…
  CHANGELOG.md
  jax/api.py
  tests/pmap_test.py
Labels: cla: yes

#2228 Docstring typo
  jax/random.py
Labels: cla: yes

#2227 Disable PRED dlpack test.
  tests/array_interoperability_test.py
Labels: cla: yes

#2229 Update XLA.
  WORKSPACE
Labels: cla: yes

#2230 Fix sha256 sum for XLA release.
  WORKSPACE
Labels: cla: yes

#2231 _scatter_jvp bug fix
  jax/interpreters/masking.py
  jax/lax/lax.py
Labels: cla: yes

#2235 Removed a couple of slow notebooks from RTD auto-rendering.
  docs/conf.py
  docs/developer.rst
  docs/jaxpr.rst
  docs/notebooks/autodiff_cookbook.ipynb
Labels: cla: yes

#2238 Fixed the name of the excluded notebook
  docs/conf.py
Labels: cla: yes

#2240 Add `jax.nn.one_hot(x, num_classes, dtype)`.
  jax/nn/functions.py
  tests/nn_test.py
Labels: cla: yes

#2234 Set `call_p.multiple_results` to True
  jax/core.py
Labels: cla: yes

#2233 Expanded the error messages due to re-using tracers saved in global s…
  jax/core.py
  jax/experimental/loops.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: better_errors, cla: yes

#2244 Correct sign mistake in complex autodiff docs
  docs/notebooks/autodiff_cookbook.ipynb
Labels: cla: yes

#2246 Revert "Allow shapecheck of PixelCNN++ (#2017)"
  jax/api.py
  jax/interpreters/masking.py
  jax/interpreters/xla.py
  jax/lax/lax.py
  jax/lax/lax_control_flow.py
  jax/numpy/lax_numpy.py
  jax/random.py
  tests/lax_numpy_indexing_test.py
  tests/masking_test.py
Labels: cla: yes

#2247 Improve developer documentation.
  build/build.py
  docs/developer.rst
Labels: cla: yes

#2257 add np.copy method to abstract arrays
  jax/api.py
  jax/numpy/lax_numpy.py
  tests/api_test.py
Labels: cla: yes

#2220 Faster gradient rules for {numpy,scipy}.linalg.solve
  jax/numpy/linalg.py
  jax/scipy/linalg.py
Labels: cla: yes

#2259 Use input dtype for constants in jax.nn.gelu
  jax/nn/functions.py
  tests/nn_test.py
Labels: cla: yes

#2262 Disable newly added test on TPU (no float16)
  tests/nn_test.py
Labels: cla: yes

#2267 Update WORKSPACE to setup upstream dependencies.
  WORKSPACE
Labels: cla: yes

#2268 fix unit handling in vmap of cond
  jax/lax/lax_control_flow.py
  tests/lax_control_flow_test.py
Labels: cla: yes

#2265 Add "edge" support for pad
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#2269 Disable linalg_test:testMatrix power on TPU
  tests/linalg_test.py
Labels: cla: yes

#2272 Revert "add np.copy method to abstract arrays (#2257)"
  jax/api.py
  jax/numpy/lax_numpy.py
  tests/api_test.py
Labels: cla: yes

#2277 Add a jit around lax_linalg.lu_pivots_to_permutation
  jax/lax_linalg.py
Labels: cla: yes

#2280 Add an experimental lax.top_k operator.
  jax/lax/lax.py
  tests/lax_test.py
Labels: cla: yes

#2286 Always jit scipy.ndimage.map_coordinates
  jax/scipy/ndimage.py
Labels: cla: yes

#2289 Unbreak build and update XLA.
  WORKSPACE
  build/build.py
Labels: cla: yes

#2292 Add nested pmap image to demo notebook.
  cloud_tpu_colabs/NeurIPS_2019_JAX_demo.ipynb
  cloud_tpu_colabs/images/nested_pmap.png
Labels: cla: yes

#2293 Shrink nested pmap image in demo notebook.
  cloud_tpu_colabs/NeurIPS_2019_JAX_demo.ipynb
Labels: cla: yes

#2278 Minor fixes to docs related to jax.numpy.vectorize
  docs/jax.experimental.rst
  docs/jax.experimental.vectorize.rst
  docs/jax.rst
  jax/numpy/lax_numpy.py
Labels: cla: yes

#2252 Moved CHANGELOG to docs
  CHANGELOG.md
  README.md
  docs/CHANGELOG.rst
  docs/index.rst
Labels: cla: yes

#2239 Use int32 for counters in optix.
  jax/experimental/optix.py
Labels: cla: yes

#2279 Fixes minor typo in the document "How JAX primitives work"
  docs/notebooks/How_JAX_primitives_work.ipynb
Labels: cla: yes, documentation

#2290 Fix abstract evaluation rule for lax.top_k.
  jax/lax/lax.py
  tests/lax_test.py
Labels: cla: yes

#2258 Minor dedupe xla/pxla tracing code.
  jax/interpreters/partial_eval.py
  jax/interpreters/pxla.py
  jax/interpreters/sharded_jit.py
  jax/interpreters/xla.py
Labels: cla: yes

#2309 Added .pytype cache to .gitignore
  .gitignore
Labels: cla: yes

#2266 examples from control: MPC, ILQR, and LQR
  examples/control.py
  examples/control_test.py
Labels: cla: yes

#2312 Add the optix.py documentation to the RTD
  docs/developer.rst
  docs/jax.experimental.optix.rst
  docs/jax.experimental.rst
  jax/experimental/optix.py
Labels: cla: yes

#2319 Reference deduped precision issue.
  cloud_tpu_colabs/README.md
Labels: cla: yes

#2327 Remove check comparing shift/axis and input dimensions in np.roll
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#2321 fix vjp odeint
  jax/experimental/ode.py
Labels: cla: yes

#2333 Recommend using pip for jaxlib more strongly in the dev guide
  docs/developer.rst
Labels: cla: yes

#2335 Fix LaxVmap test tolerances.
  tests/lax_test.py
Labels: cla: yes

#2331 Address Issue 2330
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes
