Repository jax-ml/jax, pull requests merged in 2020-09, with the labels that each got.

#4169 [Ready to be submitted] Add more features to the C++ jax.jit.
  WORKSPACE
  jax/api.py
  jaxlib/version.py
  tests/api_test.py
  tests/jax_jit_test.py
Labels: cla: yes

#4185 [jax2tf] Indicate the version of TF used in tests in README.
  jax/experimental/jax2tf/README.md
Labels: cla: yes

#4188 copysign: promote to inexact to match numpy & support unsigned inputs
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#4190 better jax.numpy.tile implementation
  jax/numpy/lax_numpy.py
Labels: cla: yes

#4197 Add array_split (#70)
  docs/jax.numpy.rst
  jax/numpy/__init__.py
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#4192 [jax2tf] Implementation of random_gamma
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/primitives_test.py
  jax/random.py
Labels: cla: yes

#4200 [jax2tf] Flip the with_gradient=True; was flipped back by mistake
  jax/experimental/jax2tf/jax2tf.py
Labels: cla: yes

#4181 Add reverse flag in associative scan
  jax/lax/lax_control_flow.py
  tests/lax_control_flow_test.py
Labels: cla: yes

#4204 [jax2tf] Use the JAX impl rule for threefry instead of writing our own
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes

#4201 [jax2tf] Cleanup the correctness stats layout.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/tf_test_util.py
Labels: cla: yes

#4208 [jax2tf] Fix random.split when jax_exable_x64
  jax/experimental/jax2tf/tests/primitives_test.py
  jax/random.py
Labels: cla: yes

#4209 [jax2tf] Expand coverage of primitives by categorize.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes

#4210 Add more context to the axis_frame error message.
  jax/core.py
Labels: cla: yes

#4213 [jax2tf] Fix missing complex64 TPU corner case of scatter_{add,mul}
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/correctness_stats.py
Labels: cla: yes

#4214 [jax2tf] Fix bug in population count and move expect_tf_exception
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes

#4217 tweak lax.py shape broadcasting logic
  jax/lax/lax.py
Labels: cla: yes

#4224 updtate version and changelog for pypi
  docs/CHANGELOG.rst
  jax/version.py
Labels: cla: yes

#3913 Add test for dtype coverage of jax.numpy ufuncs
  tests/lax_numpy_test.py
Labels: cla: yes

#4231 Update jaxlib version for dlpack fix.
  WORKSPACE
  docs/CHANGELOG.rst
  jaxlib/version.py
Labels: cla: yes

#4066 jaxlib build fixes.
  build/build_wheel_docker_entrypoint.sh
  build/install_cuda.sh
Labels: cla: yes

#4234 improve lax.pad shape rule
  jax/lax/lax.py
  tests/lax_test.py
Labels: cla: yes

#4232 Fix Dockerfile wheel installation issues. #4066
  build/Dockerfile
Labels: cla: yes

#4030 [jax2tf] Clean up code for XlaGather, experimental_compile not necessary
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/primitives_test.py
  jax/experimental/jax2tf/tests/savedmodel_test.py
Labels: cla: yes

#4235 [jax2tf] Updated test_pad to test all dtypes and remove old skipped test.
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes

#4194 Add axis_index_groups support to all_gather.
  jax/lax/lax_parallel.py
  tests/pmap_test.py
Labels: cla: yes

#4236 [jax2tf] Clean up test_dynamic_slice.
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes

#4219 [jax2tf] Add a template file for documentation generation.
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/primitives_with_limited_support.md.template
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/tf_test_util.py
Labels: cla: yes

#4226 Interrupt lu transformation generators whenever an exception occurs
  jax/linear_util.py
Labels: cla: yes

#4239 Update TF dep to a passing commit hash.
  WORKSPACE
Labels: cla: yes

#4240 Update install_cuda script to specify cublas.
  build/install_cuda.sh
Labels: cla: yes

#4243 Reorder nocuda/cuda build to fail early.
  build/build_jaxlib_wheels.sh
Labels: cla: yes

#4237 [jax2tf] Moved the limitations for XlaSort to correctness_stats
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
  jax/experimental/jax2tf/tests/tf_test_util.py
Labels: cla: yes

#4246 [jax2tf] Cleanup test_unary_elementwise.
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes

#4247 [jax2tf] Fix test failure on TPUs
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/primitives_with_limited_support.md.template
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes

#4244 Add comments for residuals from f_bwd.
  docs/notebooks/Custom_derivative_rules_for_Python_code.ipynb
Labels: cla: yes

#4242 Revert "Revert "Delete batching.last. (#4148)""
  jax/api.py
  jax/interpreters/batching.py
  tests/api_test.py
Labels: cla: yes

#4241 Change lax_linalg.lu to return a permutation representation of the pa…
  jax/lax_linalg.py
  jax/numpy/linalg.py
  jax/scipy/linalg.py
Labels: cla: yes

#4251 Bump TF hash to get an upstream LLVM GCC fix.
  WORKSPACE
Labels: cla: yes

#4252 fix documentation typo
  docs/jaxpr.rst
Labels: cla: yes

#4250 Clarify when jaxlib version should be bumped.
  jaxlib/version.py
Labels: cla: yes

#4256 Update README to point to jaxlib-0.1.55.
  README.md
Labels: cla: yes

#4253 implement jnp.apply_along_axis
  docs/jax.numpy.rst
  jax/numpy/__init__.py
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#4227 Extend axis env while translating the pmapped jaxpr to XLA
  jax/core.py
  jax/interpreters/pxla.py
  tests/pmap_test.py
Labels: cla: yes

#4195 Call check_arraylike() in jax.numpy reductions
  jax/numpy/lax_numpy.py
Labels: cla: yes

#4034 Fixing weird behavior in segment_sum when num_segments is None.
  jax/ops/scatter.py
  tests/lax_numpy_indexing_test.py
Labels: cla: yes

#4267 Testing RTD build
  docs/requirements.txt
Labels: cla: yes

#4268 Move failing CPPJitTest test case to PythonJitTest
  tests/api_test.py
Labels: cla: yes

#4270 Cleanup: use _canonicalize_axis() utility where possible
  jax/numpy/lax_numpy.py
Labels: cla: yes

#4272 thread backend in pxla.replicate
  jax/interpreters/pxla.py
  tests/pmap_test.py
Labels: cla: yes

#4273 fixing typo
  docs/jaxpr.rst
Labels: cla: yes

#4276 Avoid rank promotion in np.outer
  jax/numpy/lax_numpy.py
Labels: cla: yes

#4277 Avoid rank promotion in stax biases
  jax/experimental/stax.py
Labels: cla: yes

#4263 [jax2tf] Fix lax.div_p
  jax/experimental/jax2tf/jax2tf.py
Labels: cla: yes

#4249 [jax2tf] Added the last comments from the jax2tf doc inside the correctness_stats code.
  jax/experimental/jax2tf/tests/correctness_stats.py
Labels: cla: yes

#4248 [jax2tf] Add converted primitives without tests to the generated doc.
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/primitives_with_limited_support.md.template
  jax/experimental/jax2tf/tests/correctness_stats.py
Labels: cla: yes

#4261 [jax2tf] Fix tests when running with JAX_ENABLE_X64=1.
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/primitives_with_limited_support.md.template
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes

#4101 Simplify the interface for host_callback.id_tap
  docs/CHANGELOG.rst
  jax/experimental/host_callback.py
  jax/test_util.py
  tests/host_callback_test.py
Labels: cla: yes

#4281 revert #4277 (google failure)
  jax/experimental/stax.py
Labels: cla: yes

#4283 Allow device_get to pass Python scalars through unchanged
  jax/api.py
  tests/api_test.py
Labels: cla: yes

#4279 [jax2tf] Build a primitive harness for test_type_promotion.
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes

#4282 [jax2tf] Added support for x64 for the remaining test files
  jax/experimental/jax2tf/tests/control_flow_ops_test.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/savedmodel_test.py
  jax/experimental/jax2tf/tests/stax_test.py
Labels: cla: yes

#4266 Modifies eig_p and related operations to take advantage of the new jaxlib geev API
  build/test-requirements.txt
  jax/lax_linalg.py
  jax/lib/__init__.py
  jax/numpy/linalg.py
Labels: cla: yes

#4291 Lower LU decomposition to a custom TPU implementation for float32 types.
  jax/lax_linalg.py
Labels: cla: yes

#4294 update version and changelog for pypi
  docs/CHANGELOG.rst
  jax/version.py
Labels: cla: yes

#4038 omnistaging on by default
  .github/workflows/ci-build.yaml
  docs/jaxpr.rst
  jax/api.py
  jax/config.py
  jax/core.py
  jax/custom_derivatives.py
  jax/experimental/jet.py
  jax/experimental/ode.py
  jax/interpreters/ad.py
  jax/interpreters/batching.py
  jax/interpreters/invertible_ad.py
  jax/interpreters/partial_eval.py
  jax/interpreters/pxla.py
  jax/interpreters/sharded_jit.py
  jax/interpreters/xla.py
  jax/lax/lax.py
  jax/lax/lax_control_flow.py
  jax/lax/lax_parallel.py
  jax/nn/functions.py
  jax/numpy/lax_numpy.py
  tests/api_test.py
  tests/lax_numpy_test.py
  tests/nn_test.py
Labels: cla: yes

#4286 jnp.divide: remove obsolete condition for py2 behavior
  jax/numpy/lax_numpy.py
Labels: cla: yes

#4295 tweak traceback for unbound axis names
  jax/interpreters/xla.py
Labels: cla: yes

#4287 Add api.device_put_sharded()
  jax/api.py
  tests/api_test.py
Labels: cla: yes

#4298 Fix device_put_sharded() for concrete values
  jax/api.py
Labels: cla: yes

#4297 Mention in docstring when function is not implemented
  jax/numpy/lax_numpy.py
Labels: cla: yes

#4296 Fix code rendering in optimizers documentation
  jax/experimental/optimizers.py
Labels: cla: yes

#4288 [jax2tf] Enable testing for SVD on TPU for float16
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes

#4222 [jax2tf] Add tests for the conversion of conv_general_dilated
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes

#4303 [jax2tf] Disable some convolution tests
  jax/experimental/jax2tf/tests/primitive_harness.py
Labels: cla: yes

#4304 [jax2tf] More convolution test disabling
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes

#4225 implement jnp.apply_over_axes
  docs/jax.numpy.rst
  jax/numpy/__init__.py
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#4312 improve an escaped tracer error message
  jax/core.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: cla: yes

#3398 Add jax.linear_transpose
  docs/jax.rst
  jax/__init__.py
  jax/api.py
  jax/lax/lax_control_flow.py
  jax/lax/lax_fft.py
  jax/test_util.py
  tests/api_test.py
Labels: cla: yes

#4306 [jax2tf] Fix precision casting problem in convolution.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/primitive_harness.py
Labels: cla: yes

#4264 Support non-fragmenting mask of reshape
  jax/interpreters/masking.py
  jax/lax/lax.py
  jax/numpy/lax_numpy.py
  tests/masking_test.py
Labels: cla: yes

#4315 move the trace liveness check from #4312
  jax/core.py
  tests/api_test.py
Labels: cla: yes

#4307 [jax2tf] Group error messages by dtype in pprint_limitations.
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/correctness_stats.py
Labels: cla: yes

#4317 [jax2tf] Change precision of test_conv to fix TPU tests
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes

#4319 [jax2tf] Disable complex convolution test on GPU: crash in TF
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes

#4302 Fix code quality issues
  build/build.py
  build/setup.py
  jax/abstract_arrays.py
  jax/core.py
  jax/interpreters/pxla.py
  jax/interpreters/xla.py
  jax/lax/lax.py
  jax/lax/lax_control_flow.py
  jax/lax/lax_parallel.py
  jax/lib/xla_bridge.py
  jax/numpy/fft.py
  jax/numpy/lax_numpy.py
  jax/test_util.py
  jax/tools/jax_to_hlo.py
  setup.py
  tests/batching_test.py
Labels: cla: yes

#4325 test eval_context works w/ and w/o omnistaging
  jax/core.py
  tests/api_test.py
Labels: cla: yes

#4318 Fix shape checking rule for conv_general_dilated.
  jax/lax/lax.py
  tests/lax_test.py
Labels: cla: yes

#4313 Implement jnp.ravel_multi_index()
  docs/jax.numpy.rst
  jax/numpy/__init__.py
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes

#4314 Make expm transposable and remove custom_jvp rule.
  jax/scipy/linalg.py
  tests/linalg_test.py
Labels: cla: yes

#4320 Fix conditional in eig and expand eig test suite.
  jax/lax_linalg.py
  tests/linalg_test.py
Labels: cla: yes

#4278 [jax2tf] Replace tf.math.add with tf.raw_ops.AddV2
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/primitives_with_limited_support.md.template
  jax/experimental/jax2tf/tests/correctness_stats.py
Labels: cla: yes

#4332 [jax2tf] Revert '[jax2tf] Replace tf.math.add with tf.raw_ops.AddV2 (…
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/primitives_with_limited_support.md.template
  jax/experimental/jax2tf/tests/correctness_stats.py
Labels: cla: yes

#4333 Disable testExpmGrad on TPU, pending investigation of compiler error
  tests/linalg_test.py
Labels: cla: yes

#4339 Enable complex-valued Cholesky decomposition tests on TPU>
  tests/linalg_test.py
Labels: cla: yes

#4329 fix benchmark sums
  benchmarks/pmap_benchmark.py
Labels: cla: yes

#4328 rename and simplify TypedJaxpr -> ClosedJaxpr
  docs/jax_internal_api.rst
  docs/jaxpr.rst
  jax/api.py
  jax/core.py
  jax/custom_derivatives.py
  jax/experimental/host_callback.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/loops.py
  jax/interpreters/ad.py
  jax/interpreters/batching.py
  jax/interpreters/invertible_ad.py
  jax/interpreters/partial_eval.py
  jax/interpreters/xla.py
  jax/lax/lax_control_flow.py
  tests/core_test.py
  tests/lax_control_flow_test.py
Labels: cla: yes

#4349 Fixed ppermute translation rule
  jax/lax/lax_parallel.py
Labels: cla: yes

#4330 insert a stop_gradient in lax.create_token
  jax/lax/lax.py
Labels: cla: yes, pull ready

#4353 plumb donate_argnums into jax.xla_computation
  jax/api.py
  jax/api_util.py
  tests/api_test.py
Labels: cla: yes, pull ready

#4343 [jax2tf] Add primitive conversion for cholesky_p.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes, pull ready

#4356 don't initialize the backend in xla_computation
  jax/api.py
  tests/api_test.py
Labels: cla: yes, pull ready

#4338 [jax2tf] Implementation of the conversion of eig_p.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes, pull ready

#4229 Expose jax.image.scale_and_translate
  docs/jax.image.rst
  jax/image/__init__.py
  jax/image/scale.py
  tests/image_test.py
Labels: cla: yes, pull ready

#4345 fix incorrect indentation
  jax/util.py
Labels: cla: yes, pull ready

#4347 Implement jnp.array_equiv
  docs/jax.numpy.rst
  jax/numpy/__init__.py
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#4366 Fix jnp.diff behavior on scalars
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: better_errors, cla: yes, pull ready

#4299 Improve segment_sum stability by k-way summation.
  jax/ops/scatter.py
  jax/util.py
Labels: cla: yes, pull ready

#4371 jnp.moveaxis: fix bug when axes are integer dtype
  jax/numpy/lax_numpy.py
Labels: cla: yes, pull ready

#4362 device_put_sharded: remove incorrect type annotation
  jax/api.py
Labels: cla: yes, pull ready

#4331 Use jvp(expm) to compute expm_frechet.
  jax/scipy/linalg.py
  tests/linalg_test.py
Labels: cla: yes, pull ready

#4373 avoid spurious device interactions
  jax/lax/lax.py
  tests/api_test.py
Labels: cla: yes, pull ready

#4359 Add back the batching rule for ppermute
  jax/lax/lax_parallel.py
  tests/pmap_test.py
Labels: cla: yes, pull ready

#4361 [jax2tf] Implementation of the conversion of eigh_p.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/correctness_stats.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes, pull ready

#4376 [jax2tf] Make rows of the generated documentation ordered deterministically.
  jax/experimental/jax2tf/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/correctness_stats.py
Labels: cla: yes, pull ready

#4370 Update scale_and_translate to take an explicit spatial_dims.
  jax/image/scale.py
  tests/image_test.py
Labels: cla: yes, pull ready

#4378 Fix axis_index inside nested pmaps
  jax/lax/lax_parallel.py
  tests/pmap_test.py
Labels: cla: yes, pull ready

#4377 Delete dead axis_index code
  jax/core.py
  jax/interpreters/xla.py
Labels: cla: yes, pull ready

#4381 Call _check_arraylike in jax.numpy to improve error messages
  jax/numpy/lax_numpy.py
Labels: better_errors, cla: yes, pull ready

#4393 Enable tests for complex QR decomposition on TPU.
  tests/linalg_test.py
Labels: cla: yes, pull ready

#4392 [jax2tf] Adjust tolerance in flaky float32 eigh test.
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes, pull ready

#4382 Enable fast TPU LU decomposition for complex types.
  jax/lax_linalg.py
Labels: cla: yes, pull ready

#4391 Consider lists as groups of axis names too
  jax/lax/lax_parallel.py
Labels: cla: yes, pull ready

#4398 lift randomness limit (a long-standing TODO)
  jax/random.py
  tests/random_test.py
Labels: cla: yes, pull ready

#4401 update version and changelog for pypi
  docs/CHANGELOG.rst
  jax/version.py
Labels: cla: yes, pull ready

#4400 add jax logo file
  images/jax_logo.svg
Labels: cla: yes, pull ready

#4387 [host_callback] Update the documentation
  jax/experimental/host_callback.py
Labels: cla: yes, pull ready

#4364 Adding an option to return the output tree in make_jaxpr
  jax/api.py
  tests/api_test.py
Labels: cla: yes, pull ready

#4388 Fix the abstract eval and translation rule for all_to_all
  jax/lax/lax_parallel.py
  tests/pmap_test.py
Labels: cla: yes, pull ready

#4170 Allow vmapping all_to_all and implement a (slow) CPU and GPU translation
  jax/interpreters/xla.py
  jax/lax/lax_parallel.py
  tests/pmap_test.py
Labels: cla: yes, pull ready

#4402 [host_callback] Fixes and documentation changes for omnistaging
  docs/CHANGELOG.rst
  jax/experimental/host_callback.py
  jax/lax/lax.py
  tests/host_callback_test.py
Labels: cla: yes, pull ready

#4403 [jax2tf] Fix casting in translation of eigh for empty arrays.
  jax/experimental/jax2tf/jax2tf.py
Labels: cla: yes, pull ready

#4406 [host_callback] improved logging, and add instructions for debugging
  jax/experimental/host_callback.py
  tests/host_callback_test.py
Labels: cla: yes, pull ready

#4368 jax.numpy: improved errors for invalid inputs to unary ops
  jax/numpy/lax_numpy.py
Labels: better_errors, cla: yes, pull ready

#4410 add omnistaging doc
  design_notes/omnistaging.md
Labels: cla: yes, pull ready

#4411 fix links in omnistaging doc (hopefully...)
  design_notes/omnistaging.md
Labels: cla: yes, pull ready

#4412 Use core.concrete_or_error() to improve errors in reductions
  jax/core.py
  jax/numpy/lax_numpy.py
Labels: better_errors, cla: yes, pull ready

#4342 improve a ConcretizationTypeError message from dependence on jitted function arguments
  jax/core.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: cla: yes, pull ready

#3983 Allow JAX objects to be represented by multiple buffers
  jax/api.py
  jax/core.py
  jax/interpreters/pxla.py
  jax/interpreters/sharded_jit.py
  jax/interpreters/xla.py
  jax/lax/lax.py
  tests/core_test.py
  tests/custom_object_test.py
  tests/pmap_test.py
Labels: cla: yes, pull ready

#4417 Revert "Allow JAX objects to be represented by multiple buffers"
  jax/api.py
  jax/core.py
  jax/interpreters/pxla.py
  jax/interpreters/sharded_jit.py
  jax/interpreters/xla.py
  jax/lax/lax.py
  tests/core_test.py
  tests/custom_object_test.py
  tests/pmap_test.py
Labels: cla: yes, pull ready

#4414 document setting default device and array creation
  docs/faq.rst
Labels: cla: yes, pull ready

#4421 Allow jax objects to be represented by multiple buffers
  jax/api.py
  jax/core.py
  jax/interpreters/pxla.py
  jax/interpreters/sharded_jit.py
  jax/interpreters/xla.py
  jax/lax/lax.py
  tests/core_test.py
  tests/custom_object_test.py
  tests/pmap_test.py
Labels: cla: yes, pull ready

#4425 Use `raise .. from ..` to chain exceptions
  jax/core.py
  jax/experimental/host_callback.py
  jax/experimental/jax2tf/jax2tf.py
  jax/lax/lax.py
  jax/linear_util.py
  jax/numpy/linalg.py
Labels: cla: yes, pull ready

#4384 Add test coverage for jnp.cov aweights & fweights
  jax/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#4415 Call concrete_or_error on indices() argument
  jax/numpy/lax_numpy.py
Labels: better_errors, cla: yes, pull ready
