Repository jax-ml/jax, pull requests merged in 2021-01, with the labels that each got.

#5303 Add jax.scipy.optimize to HTML docs
  docs/jax.scipy.rst
Labels: cla: yes, pull ready

#5298 Switch internal code from deflinear to deflinear2
  jax/_src/lax/control_flow.py
  jax/_src/lax/fft.py
  jax/_src/lax/lax.py
  jax/_src/lax/parallel.py
  jax/interpreters/ad.py
  jax/interpreters/sharded_jit.py
  jax/interpreters/xla.py
Labels: cla: yes, pull ready

#5317 Update XLA version.
  WORKSPACE
Labels: cla: yes, pull ready

#5316 Fix linalg.solve() and linalg.inv() for empty matrices
  jax/_src/lax/linalg.py
  jax/_src/numpy/linalg.py
  tests/linalg_test.py
Labels: cla: yes, pull ready

#4805 [RFC] Support complex dtype in random.normal
  jax/_src/random.py
  jax/dtypes.py
  tests/random_test.py
Labels: cla: yes, pull ready

#5211 Add xla translation rules that accept avals
  jax/_src/random.py
  jax/interpreters/xla.py
  tests/custom_object_test.py
Labels: cla: yes, pull ready

#5243 [host_callback] Added API to call host computations and return values to the accelerator computation
  docs/CHANGELOG.rst
  docs/developer.rst
  docs/jax.experimental.host_callback.rst
  jax/experimental/host_callback.py
  jax/interpreters/ad.py
  tests/host_callback_test.py
  tests/host_callback_to_tf_test.py
  tests/infeed_test.py
  tests/lax_control_flow_test.py
Labels: cla: yes, pull ready

#5339 [jax2tf] Fix infinite recursion when converting some bfloat16 arrays
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes, pull ready

#5341 [jax2tf] Finish the conversion of lax.sort
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/g3doc/primitives_with_limited_support.md
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
  jax/experimental/jax2tf/tests/primitive_harness.py
Labels: cla: yes, pull ready

#5324 Skip tests that are failing without omnistaging (which will not be an…
  tests/pmap_test.py
Labels: cla: yes, pull ready

#5330 clear some caches when setting up jaxpr typecheck tests
  jax/_src/lax/control_flow.py
  tests/core_test.py
  tests/lax_control_flow_test.py
Labels: cla: yes, pull ready

#5338 Updates XLA_in_Python notebook with the latest API.
  docs/notebooks/XLA_in_Python.ipynb
Labels: cla: yes, pull ready

#5334 Add types to axes in lax_numpy.
  jax/_src/numpy/lax_numpy.py
  jax/util.py
Labels: cla: yes, pull ready

#5323 Add method parameter to jax.random.multivariate_normal
  jax/_src/random.py
  tests/random_test.py
Labels: cla: yes, pull ready

#5320 Support broadcasting of batch dims in jax.numpy.linalg.solve
  jax/_src/lax/linalg.py
  tests/linalg_test.py
Labels: cla: yes, pull ready

#5314 make c++ jit dispatch sensitive to required global context
  jax/api.py
  tests/api_test.py
Labels: cla: yes, pull ready

#5340 [jax2tf] Fix/disable tests for non-omnistaging
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: cla: yes, pull ready

#5348 Use tiny for gumbel sampler
  jax/_src/random.py
Labels: cla: yes, pull ready

#5349 Simplify jax.random.logistic algorithm
  jax/_src/random.py
Labels: cla: yes, pull ready

#5343 jnp.eye(): improve input validation
  jax/_src/lax/other.py
  jax/_src/numpy/lax_numpy.py
Labels: cla: yes, pull ready

#5236 (docfix) Clarify variable names in README.md snippit
  README.md
Labels: cla: yes, pull ready

#5360 alias jax.partial to functools.partial
  jax/util.py
Labels: cla: yes, pull ready

#5363 Update XLA.
  WORKSPACE
Labels: cla: yes, pull ready

#5369 Update TF version for jaxlib 0.1.58 release
  WORKSPACE
Labels: cla: yes, pull ready

#5379 Release jax 0.2.8.
  docs/CHANGELOG.rst
  jax/version.py
Labels: cla: yes, pull ready

#5260 Use XLA AllGather op for GPU (when supported).
  jax/_src/lax/parallel.py
  jax/experimental/jax2tf/jax2tf.py
Labels: cla: yes, pull ready

#5371 Add support for 'static_broadcasted_args' in 'sharded_jit'.
  jax/interpreters/sharded_jit.py
  tests/sharded_jit_test.py
Labels: cla: yes, pull ready

#5373 Support numpy integers in arr.reshape()
  jax/_src/numpy/lax_numpy.py
Labels: bug, cla: yes, pull ready

#5203 Have the C++ path raise a cleaner error for static argnums.
  jax/api.py
Labels: cla: yes, pull ready

#5387 allow vmapped function to accept kwargs
  jax/api.py
  jax/api_util.py
  tests/batching_test.py
Labels: cla: yes, pull ready

#5390 [host_callback] Refactor to merge the implementations of id_tap and call
  jax/experimental/host_callback.py
  tests/host_callback_test.py
Labels: cla: yes, pull ready

#5225 Complex SVD JVP rule
  jax/_src/lax/linalg.py
  tests/linalg_test.py
Labels: cla: yes, pull ready

#4711 Add typing annotations and expose py.typed
  jax/_src/lax/control_flow.py
  jax/_src/nn/functions.py
  jax/api.py
  jax/py.typed
  jax/tree_util.py
Labels: cla: yes, pull ready

#5393 Fix SVD on ROCm
  jax/_src/lax/linalg.py
  jaxlib/rocm_gpu_kernel_helpers.h
  jaxlib/rocsolver.py
Labels: cla: yes, pull ready

#5342 Change segment_sum to drop out-of-bounds indices rather than wrap them.
  docs/CHANGELOG.rst
  jax/_src/numpy/lax_numpy.py
  jax/_src/ops/scatter.py
  tests/lax_numpy_indexing_test.py
Labels: cla: yes, pull ready

#5333 Support empty inputs for jnp.linalg.pinv and jnp.linalg.svd
  jax/_src/lax/linalg.py
  jax/_src/numpy/linalg.py
  tests/linalg_test.py
Labels: cla: yes, pull ready

#5397 Use py3.6-friendly subprocess.run invocation in build_wheel.py
  build/build_wheel.py
Labels: cla: yes, pull ready

#5398 Make x.reshape() error on non-integers
  jax/_src/numpy/lax_numpy.py
Labels: cla: yes, pull ready

#5402 Support numpy int in reduction axis
  jax/_src/numpy/lax_numpy.py
Labels: cla: yes, pull ready

#5403 Validate axes values in reduce_op_shape_rule
  jax/_src/lax/lax.py
Labels: cla: yes, pull ready

#5396 fix dropped import
  cloud_tpu_colabs/Lorentz_ODE_Solver.ipynb
Labels: cla: yes, pull ready

#5400 Fix pdot translation rule.
  jax/_src/lax/parallel.py
  tests/xmap_test.py
Labels: cla: yes, pull ready

#5404 Support general int axes in jnp.tile()
  jax/_src/numpy/lax_numpy.py
Labels: cla: yes, pull ready

#5420 Update XLA.
  WORKSPACE
Labels: cla: yes, pull ready

#5421 Remove some old jaxlib compatibility code.
  jax/lib/__init__.py
Labels: cla: yes, pull ready

#5413 [loops] Extend loops with support for pytrees
  docs/CHANGELOG.rst
  jax/experimental/loops.py
  tests/loops_test.py
Labels: cla: yes, pull ready

#5422 [host_callback] Fix bug when id_tap takes no arguments but has a result.
  jax/experimental/host_callback.py
  tests/host_callback_test.py
Labels: cla: yes, pull ready

#5423 Add py.typed to setup.py for PEP 561 compliance.
  setup.py
Labels: cla: yes, pull ready

#5424 Update WORKSPACE and jaxlib version to 0.1.59
  WORKSPACE
  jaxlib/version.py
Labels: cla: yes, pull ready

#5425 Remove type overloads for tree_map and tree_multimap.
  jax/tree_util.py
Labels: cla: yes, pull ready

#5429 disable test that requires omnistaging
  tests/host_callback_test.py
Labels: cla: yes, pull ready

#5430 Disable another test that requires omnistaging
  tests/host_callback_test.py
Labels: cla: yes, pull ready

#5427 Fix wrapped doc
  jax/_src/numpy/util.py
Labels: cla: yes, pull ready

#5428 Fix RST annotations
  docs/jax.scipy.rst
Labels: cla: yes, pull ready

#5431 [*.py] Rename "Arguments:" to "Args:"
  jax/_src/lax/control_flow.py
  jax/_src/lax/lax.py
  jax/interpreters/xla.py
  jax/linear_util.py
Labels: cla: yes, pull ready

#4334 [jax2tf] Add support for Add for uint32
  jax/experimental/jax2tf/g3doc/primitives_with_limited_support.md
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
Labels: cla: yes, pull ready

#5432 [jax2tf] Cleanup the way jax2tf limitations are specified
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/g3doc/jax_primitives_coverage.md
  jax/experimental/jax2tf/g3doc/jax_primitives_coverage.md.template
  jax/experimental/jax2tf/g3doc/primitives_with_limited_support.md
  jax/experimental/jax2tf/g3doc/primitives_with_limited_support.md.template
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/tf_test_util.py
Labels: cla: yes, pull ready

#5362 Make xmapped functions with no axis resources callable more than once
  jax/experimental/maps.py
  tests/xmap_test.py
Labels: cla: yes, pull ready

#5394 Update CUDA installation instructions.
  README.md
Labels: cla: yes, pull ready

#5438 Update jaxlib version, minimum jaxlib version, readme, and changelog.
  README.md
  build/test-requirements.txt
  docs/CHANGELOG.rst
  jax/lib/__init__.py
  jaxlib/version.py
Labels: cla: yes, pull ready

#5439 Update WORKSPACE file to comply with TensorFlow's downstream WORKSPAC…
  WORKSPACE
Labels: cla: yes, pull ready

#5315 CI: use python 3.9 for numpy dispatch tests
  .github/workflows/ci-build.yaml
Labels: cla: yes, pull ready

#5441 Cleanup: fix some sphinx warnings
  docs/CHANGELOG.rst
  docs/conf.py
  docs/jax.experimental.rst
Labels: cla: yes, pull ready

#5437 Dedent wrapped doc sections individually
  jax/_src/numpy/util.py
Labels: cla: yes, pull ready

#5376 [jax2tf] Remove legacy bfloat16 conversion code.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/tf_test_util.py
Labels: cla: yes, pull ready

#5224 Add flag for inf checking
  docs/CHANGELOG.rst
  jax/api.py
  jax/interpreters/xla.py
  tests/debug_nans_test.py
Labels: cla: yes, pull ready

#5412 Fix host_callback when there are non-local devices.
  jax/experimental/host_callback.py
Labels: cla: yes, pull ready

#4804 Updates ShardingSpec's docstring
  jax/interpreters/pxla.py
Labels: cla: yes, pull ready

#5435 Clean up xmap tests
  tests/xmap_test.py
Labels: cla: yes, pull ready

#5451 [jax2tf] Start using jit_compile instead of the deprecated experiment…
  jax/experimental/jax2tf/examples/saved_model_lib.py
  jax/experimental/jax2tf/examples/saved_model_main.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  jax/experimental/jax2tf/tests/tf_test_util.py
Labels: cla: yes, pull ready

#5452 [jax2tf] Reflect in the limitations that add works for uint32 in TF
  jax/experimental/jax2tf/g3doc/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
Labels: cla: yes, pull ready

#5319 add source line info to more escaped tracer errors
  jax/_src/source_info_util.py
  jax/core.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
  tests/errors_test.py
Labels: cla: yes, pull ready

#5462 avoid printing double periods in error messages
  jax/core.py
Labels: cla: yes, pull ready

#5453 Make it possible to vmap xmapped functions
  jax/experimental/maps.py
  tests/xmap_test.py
Labels: cla: yes, pull ready

#5466 bug: always return DeviceArray from lax.integer_pow
  jax/_src/lax/lax.py
Labels: cla: yes, pull ready

#5468 add BatchTrace.process_custom_vjp_call
  jax/interpreters/batching.py
  tests/api_test.py
Labels: cla: yes, pull ready

#5455 Use XLA AllGather op for GPU (attempt 2).
  jax/_src/lax/parallel.py
  jax/experimental/jax2tf/jax2tf.py
  tests/pmap_test.py
Labels: cla: yes, pull ready

#5470 [ROCm] fix build
  jaxlib/BUILD
Labels: cla: yes, pull ready

#5472 Fix ABSL build dependencies of //jaxlib:handle_pool
  jaxlib/BUILD
Labels: cla: yes, pull ready

#5213 Add support for 'preferred_element_type' arg in `dot` and `dot_general`.
  jax/_src/lax/lax.py
  jax/_src/lax/parallel.py
  jax/experimental/jax2tf/jax2tf.py
  tests/lax_test.py
Labels: cla: yes, pull ready

#5473 Clarify the CuDNN versions expected by jaxlib wheels.
  README.md
Labels: cla: yes, pull ready

#5482 add a request for PR-squashing in contributing.md
  CONTRIBUTING.md
Labels: cla: yes, pull ready

#5446 Added check for shapes of arguments in jvp, resolves issue #5226
  jax/api.py
  tests/api_test.py
Labels: cla: yes, pull ready

#5419 jnp.power: use integer_power path in all applicable cases
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#5491 add systematic pdot tests, utility functions
  jax/_src/lax/parallel.py
  tests/xmap_test.py
Labels: cla: yes, pull ready

#5477 add transformed fun src info to escaped tracer err
  jax/config.py
  jax/core.py
Labels: cla: yes, pull ready

#5478 util._wraps: correctly handle initial line indentation
  jax/_src/numpy/util.py
Labels: cla: yes, pull ready

#5495 Fix exception when tokens are used in AD.
  jax/core.py
  jax/interpreters/xla.py
  tests/api_test.py
Labels: cla: yes, pull ready

#5492 revive the leak checker, as a debug mode
  jax/_src/lax/control_flow.py
  jax/_src/util.py
  jax/api.py
  jax/config.py
  jax/core.py
  jax/custom_derivatives.py
  jax/interpreters/ad.py
  jax/interpreters/batching.py
  jax/interpreters/partial_eval.py
  jax/interpreters/pxla.py
  jax/interpreters/xla.py
  jax/linear_util.py
  tests/api_test.py
Labels: cla: yes, pull ready

#5500 add support for scipy.stats.poisson.cdf
  jax/_src/scipy/stats/poisson.py
  jax/scipy/stats/poisson.py
  tests/scipy_stats_test.py
Labels: cla: yes, pull ready

#5502 fixed testNorm
  tests/linalg_test.py
Labels: cla: yes, pull ready

#5465 Restore support for nested xmaps when using the (standard) replica lowering
  jax/experimental/maps.py
  tests/xmap_test.py
Labels: cla: yes, pull ready

#5480 Refactor how the result processing code wraps the indexing information.
  jax/interpreters/pxla.py
Labels: cla: yes, pull ready

#5508 Fix some doc build warnings
  docs/CHANGELOG.rst
  docs/conf.py
  docs/developer.rst
  docs/index.rst
  jax/_src/ops/scatter.py
  jax/_src/scipy/linalg.py
Labels: cla: yes, pull ready

#5383 Add example code to save JAX program and run using C++ runtime.
  examples/jax_cpp/BUILD
  examples/jax_cpp/main.cc
  examples/jax_cpp/prog.py
Labels: cla: yes, pull ready

#5511 Clarify tracing documentation.
  docs/jaxpr.rst
Labels: cla: yes, pull ready

#5509 Improve batched collective rule for all_gather_p
  jax/_src/lax/parallel.py
  tests/batching_test.py
Labels: cla: yes, pull ready

#5512 include closure_convert in generated docs
  docs/jax.rst
  jax/__init__.py
Labels: cla: yes, pull ready

#5426 [DOC] add Thinking In JAX doc
  docs/index.rst
  docs/notebooks/thinking_in_jax.ipynb
Labels: cla: yes, pull ready

#5490 add xeinsum, an einsum for xmap (& jnp.einsum easter egg)
  jax/_src/lax/parallel.py
  jax/_src/numpy/lax_numpy.py
  jax/lax/__init__.py
  tests/xmap_test.py
Labels: cla: yes, pull ready

#5523 Allow `jax.custom_gradient` to return vjp with singleton return value
  jax/custom_derivatives.py
  tests/api_test.py
Labels: cla: yes, pull ready

#5526 add axis_env argument to make_jaxpr
  jax/api.py
  tests/api_test.py
Labels: cla: yes, pull ready

#5528 update version and changelog for pypi
  docs/CHANGELOG.rst
  jax/version.py
Labels: cla: yes, pull ready

#5521 [JAX-GPU] Use XLA AllToAll op on GPU (for supported configurations).
  jax/_src/lax/parallel.py
Labels: cla: yes, pull ready

#5505 Add a docstring for xmap
  docs/jax.experimental.maps.rst
  jax/experimental/maps.py
Labels: cla: yes, pull ready

#5534 Update jax2tf_limitations to update the list of integral dtypes for tf.pow
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
Labels: cla: yes, pull ready

#5538 DOC: add jax.experimental.maps to index
  docs/jax.experimental.rst
Labels: cla: yes, pull ready

#5540 run CI pytest in verbose mode
  .github/workflows/ci-build.yaml
Labels: cla: yes, pull ready

#5525 add systematic pdot vjp tests
  tests/xmap_test.py
Labels: cla: yes, pull ready

#5545 DOC: fix some minor formatting issues
  docs/CHANGELOG.rst
  docs/jaxpr.rst
  docs/pytrees.rst
  jax/_src/image/scale.py
  jax/_src/lax/lax.py
  jax/_src/nn/functions.py
Labels: cla: yes, pull ready

#5547 Improve error message when a reduction function returns an invalid re…
  jax/_src/lax/lax.py
  jax/interpreters/partial_eval.py
  tests/lax_test.py
Labels: cla: yes, pull ready

#5548 Remove signatures from wrapped docstrings
  jax/_src/numpy/util.py
Labels: cla: yes, pull ready

#5551 [jax2tf] Update the limitations due to improvements in TF
  jax/experimental/jax2tf/g3doc/jax_primitives_coverage.md
  jax/experimental/jax2tf/g3doc/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/tf_test_util.py
Labels: cla: yes, pull ready

#5553 [jax2tf] Add the JAX-not-implemented to the jax2tf limitations doc
  jax/experimental/jax2tf/g3doc/jax_primitives_coverage.md
  jax/experimental/jax2tf/g3doc/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
  jax/experimental/jax2tf/tests/jax_primitives_coverage_test.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes, pull ready

#5311 Adds support for is_leaf in tree_util.tree_(multi)map
  jax/tree_util.py
  tests/tree_util_tests.py
Labels: cla: yes, pull ready

#5561 Minor doc formatting fixes
  docs/custom_vjp_update.md
  docs/index.rst
  jax/_src/scipy/optimize/minimize.py
  jax/experimental/maps.py
Labels: cla: yes, pull ready

#5558 jnp.pad: improve error handling for non-static pad_width
  jax/_src/numpy/lax_numpy.py
Labels: cla: yes, pull ready

#4262 [jax2tf] Add input and output names to the TensorFlow graph generated by jax2tf.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: cla: yes, pull ready

#5572 Pin numpy to max version 1.19, to avoid errors with 1.20
  build/test-requirements.txt
  jaxlib/setup.py
  setup.py
Labels: cla: yes, pull ready

#5559 Export split_dict from jax.util
  jax/util.py
Labels: cla: yes, pull ready

#5574 Disable the "with numpy-dispatch" test action.
  .github/workflows/ci-build.yaml
Labels: cla: yes, pull ready

#5567 update out of date comment in Pmap_Cookbook.ipynb
  cloud_tpu_colabs/Pmap_Cookbook.ipynb
Labels: cla: yes, pull ready

#5571 Improve error message for custom_vjp
  jax/custom_derivatives.py
  tests/api_test.py
Labels: better_errors, cla: yes, pull ready
