Repository jax-ml/jax, pull requests merged in 2021-08, with the labels that each got.

#7435 Use separate variable names so that we don't get buildifier warnings
  WORKSPACE
Labels: cla: yes, pull ready

#7417 Abstracts the evaluation of a single jaxpr equation
  jax/core.py
Labels: cla: yes, pull ready

#7409 Add some clarification to the async dispatch docs
  docs/async_dispatch.rst
Labels: cla: yes, pull ready

#7441 Update minimum NumPy version in jaxlib build scripts.
  build/Dockerfile
  build/build_jaxlib_wheels_macos.sh
Labels: cla: yes, pull ready

#7427 [jax2tf] Update the limitations
  jax/experimental/jax2tf/g3doc/jax_primitives_coverage.md
  jax/experimental/jax2tf/g3doc/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
  jax/experimental/jax2tf/tests/primitive_harness.py
Labels: cla: yes, pull ready

#7443 Type stubs for jaxlib.xla_extension no longer use -stubs suffix
  WORKSPACE
  build/build_wheel.py
  jaxlib/setup.py
Labels: cla: yes, pull ready

#7459 Fix the timer->timer_secs typo
  jax/lib/xla_bridge.py
Labels: cla: yes, pull ready

#7458 add ravel_pytree to generated docs
  docs/jax.flatten_util.rst
  docs/jax.rst
Labels: cla: yes, pull ready

#7455 Fix issue with infinities in logsumexp
  jax/_src/scipy/special.py
  tests/lax_scipy_test.py
Labels: cla: yes, pull ready

#7463 [jax2tf] Add shape polymorphism support for jnp.eye
  jax/_src/lax/lax.py
  jax/_src/numpy/lax_numpy.py
  jax/core.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: cla: yes, pull ready

#7462 Perform float16 dot()s in float32 on CPU.
  jax/_src/lax/lax.py
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
Labels: cla: yes, pull ready

#7470 developer docs: remove outdated mentions of Travis CI
  docs/developer.md
Labels: cla: yes, pull ready

#7469 Relax test tolerance of eigvals test.
  tests/linalg_test.py
Labels: cla: yes, pull ready

#7473 lax_numpy_test: disable implicit rank promotion in all tests
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#7475 Fix rank promotion error in jsp.special.multigammaln
  jax/_src/scipy/special.py
  tests/lax_scipy_test.py
Labels: cla: yes, pull ready

#7474 disable implicit rank promotion in lax_numpy_einsum/indexing/vectorize_test
  tests/lax_numpy_einsum_test.py
  tests/lax_numpy_indexing_test.py
  tests/lax_numpy_vectorize_test.py
Labels: cla: yes, pull ready

#7478 Fix rank promotion error in jsp.special.zeta
  jax/_src/scipy/special.py
  tests/lax_scipy_test.py
Labels: cla: yes, pull ready

#7456 Validate shapes for boolean indices
  jax/_src/numpy/lax_numpy.py
  jax/_src/ops/scatter.py
  tests/lax_numpy_indexing_test.py
Labels: cla: yes, pull ready

#7482 Fix the tolerance so that the tests will pass on GPU
  tests/lax_control_flow_test.py
  tests/masking_test.py
Labels: cla: yes, pull ready

#7422 [ROCm] Change skip_on_devices to handle device tags
  jax/test_util.py
  tests/fft_test.py
Labels: cla: yes, pull ready

#7483 [jax2tf] Fix shape polymorphism for broadcast_in_dim_transpose
  jax/_src/lax/lax.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: cla: yes, pull ready

#7492 Update commit for release
  WORKSPACE
Labels: cla: yes, pull ready

#7447 bugfix for sm3 optimizer
  jax/experimental/optimizers.py
  tests/optimizers_test.py
Labels: cla: yes, pull ready

#7476 Cleanup: remove unused test utility
  jax/test_util.py
  tests/test_util_test.py
Labels: cla: yes, pull ready

#7481 disable implicit rank promotion for jax scipy tests
  tests/lax_scipy_sparse_test.py
  tests/lax_scipy_test.py
  tests/scipy_ndimage_test.py
  tests/scipy_optimize_test.py
  tests/scipy_signal_test.py
Labels: cla: yes, pull ready

#7493 Add cublas headers. cublas_kernels BUILD target has that dependency
  jaxlib/BUILD
Labels: cla: yes, pull ready

#7485 [jax2tf] Improve support for converting functions with kwargs
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: cla: yes, pull ready

#7503 small autodidax tweaks
  docs/autodidax.ipynb
  docs/autodidax.md
  docs/autodidax.py
Labels: cla: yes, pull ready

#7512 Default to `optimal` for einsum contraction path optimization.
  jax/_src/numpy/lax_numpy.py
Labels: cla: yes, pull ready

#7516 Use bazel --version.
  build/build.py
Labels: cla: yes, pull ready

#7514 Scrub function pointers in op_name metadata in persistent compilation cache key
  jax/experimental/compilation_cache/compilation_cache.py
Labels: cla: yes, pull ready

#7519 Use trace_to_jaxpr_dynamic in variadic_reduction_jaxpr.
  jax/_src/lax/lax.py
Labels: cla: yes, pull ready

#7523 Fix the regex
  build/build.py
Labels: cla: yes, pull ready

#7521 Add missing super() call in test case setUp
  jax/experimental/jax2tf/examples/saved_model_main_test.py
Labels: cla: yes, pull ready

#7522 Cleanup: switch to new version of super()
  jax/core.py
  jax/linear_util.py
  jax/test_util.py
  tests/array_interoperability_test.py
  tests/custom_object_test.py
  tests/sharded_jit_test.py
Labels: cla: yes, pull ready

#7515 test_util: provide hook to easily set config values in test cases
  jax/test_util.py
  tests/lax_numpy_einsum_test.py
  tests/lax_numpy_indexing_test.py
  tests/lax_numpy_test.py
  tests/lax_numpy_vectorize_test.py
  tests/lax_scipy_sparse_test.py
  tests/lax_scipy_test.py
  tests/random_test.py
  tests/scipy_ndimage_test.py
  tests/scipy_optimize_test.py
  tests/scipy_signal_test.py
Labels: cla: yes, pull ready

#7525 Use MainTrace payload mechanism in experimental callback tracer.
  jax/experimental/callback.py
Labels: cla: yes, pull ready

#7527 [sparse]: add sparse rule for scan/fori_loop
  jax/experimental/sparse/transform.py
  tests/sparsify_test.py
Labels: cla: yes, pull ready

#7524 [jax2tf] Handle weakly-typed values in constant lifting correctly.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: cla: yes, pull ready

#7536 Don't try to use persistent compilation cache when running CPU computations.
  jax/experimental/compilation_cache/compilation_cache.py
  jax/interpreters/xla.py
  tests/compilation_cache_test.py
Labels: cla: yes, pull ready

#7528 Provide more informative error messages for backend initialization failures
  jax/lib/xla_bridge.py
Labels: cla: yes, pull ready

#7537 [sparse] add sparsify rule for lax.cond
  jax/experimental/sparse/transform.py
  tests/sparsify_test.py
Labels: cla: yes, pull ready

#7539 [jax2tf] Allows shape polymorphic specification to be polynomials.
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: cla: yes, pull ready

#7541 [sparse] correctly handle units in sparsify argspecs
  jax/experimental/sparse/transform.py
  tests/sparsify_test.py
Labels: cla: yes, pull ready

#7554 [sparse] bug: thread through params in sparsify
  jax/experimental/sparse/transform.py
Labels: cla: yes, pull ready

#7555 Strip debug_info and jaxpr_stack from MainTrace instances used as C++…
  jax/core.py
Labels: cla: yes, pull ready

#7557 [sparse] fix bug in input shape validation
  jax/experimental/sparse/ops.py
Labels: cla: yes, pull ready

#7556 Reword UnexpectedTracerError and add visual dividers.
  jax/core.py
Labels: cla: yes, pull ready

#7560 [sparse] fix GPU translation rule for coo/csr matmat
  jaxlib/cusparse.py
  tests/sparse_test.py
Labels: cla: yes, pull ready

#7571 [sparse] handle pytree inputs in sparsify transform
  jax/experimental/sparse/transform.py
  tests/sparsify_test.py
Labels: cla: yes, pull ready

#7566 [jax2tf] Small fixes for shape polymorphism.
  jax/_src/lax/lax.py
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: cla: yes, pull ready

#7419 Windows build related updates
  build/build.py
Labels: cla: yes, pull ready

#7572 fix advi example
  examples/advi.py
Labels: cla: yes, pull ready

#7573 Ensure reduce_axes is a tuple.
  jax/_src/api.py
Labels: cla: yes, pull ready

#7551 Do not unflatten trees with None values in grad.
  jax/_src/api.py
  tests/api_test.py
Labels: cla: yes, pull ready

#7576 [sparse] BCOO: convert inputs to jnp.array when possible
  jax/experimental/sparse/ops.py
Labels: cla: yes, pull ready

#7581 Update .gitignore since .bazelrc is now under version control.
  .gitignore
Labels: cla: yes, pull ready

#7585 Fix "Store empty" error due to debug_nans corrupting cache entries.
  jax/interpreters/xla.py
  tests/debug_nans_test.py
Labels: cla: yes, pull ready

#7591 jax.image: fix error with zero-size image resizing
  jax/_src/image/scale.py
  tests/image_test.py
Labels: cla: yes, pull ready

#7592 Add optional fill_value argument to jnp.nonzero
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#7605 Remove opensource CS link since JAX is not indexed
  README.md
Labels: cla: yes, pull ready

#7614 update version and changelog for pypi
  CHANGELOG.md
  jax/version.py
Labels: cla: yes, pull ready

#7615 add regression test for #7613
  tests/api_test.py
Labels: cla: yes, pull ready

#7619 Add dtype to string representation of ConcreteArray.
  jax/core.py
  tests/core_test.py
Labels: cla: yes, pull ready

#7620 Add nocuda jaxlib wheels to the index as well
  build/generate_release_indexes.py
Labels: cla: yes, kokoro:run, pull ready

#7624 Update workspace org_tensorflow commit
  WORKSPACE
Labels: cla: yes, pull ready

#7626 always use same object for vmap temp axis name
  jax/_src/api.py
  jax/interpreters/batching.py
  tests/api_test.py
Labels: cla: yes, pull ready

#7633 fix custom_call_status for rocm
  jaxlib/rocm_gpu_kernel_helpers.cc
Labels: cla: yes, pull ready

#7610 jax.numpy: add missing x.choose() method
  jax/_src/numpy/lax_numpy.py
Labels: cla: yes, pull ready

#7646 scipy.stats.beta: fix pdf for x=0, 1
  jax/_src/scipy/stats/beta.py
  tests/scipy_stats_test.py
Labels: cla: yes, kokoro:force-run, pull ready

#7642 [jax2tf] Update conversion of scatter for shape polymorphism
  jax/experimental/jax2tf/jax2tf.py
Labels: cla: yes, pull ready

#7386 Replaced Any with concrete types for APIs in jaxlib.xla_client
  .pre-commit-config.yaml
  jax/_src/api.py
  jax/_src/lax/lax.py
  jax/_src/source_info_util.py
  jax/_src/tree_util.py
  jax/api_util.py
  jax/experimental/host_callback.py
  jax/experimental/jax2tf/call_tf.py
  jax/experimental/optimizers.py
  jax/interpreters/partial_eval.py
  jax/interpreters/pxla.py
  jax/interpreters/xla.py
  jax/tree_util.py
Labels: cla: yes, pull ready

#7650 Adjust wording for errors involving array rank
  jax/_src/lax/lax.py
Labels: cla: yes, pull ready

#7649 fix rocm_amdgpu_targets for rocm
  .bazelrc
  build/build.py
Labels: cla: yes, pull ready

#7652 custom_vjp: automatically handle float0 cotangents
  jax/_src/custom_derivatives.py
  tests/api_test.py
Labels: cla: yes, pull ready

#7653 custom_vjp: use more symbolic zeros
  jax/_src/custom_derivatives.py
  jax/core.py
  jax/interpreters/ad.py
  jax/interpreters/batching.py
Labels: cla: yes, pull ready

#7648 Fix logsumexp issue with debug_nans and disable_jit
  jax/_src/scipy/special.py
  tests/lax_scipy_test.py
Labels: cla: yes, pull ready

#7658 [jax2tf] Added support for conversion of padding with enable_xla=False
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes, pull ready

#7660 Cleanup: remove unused import
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: cla: yes, pull ready

#7664 DOC: fix code formatting in type_promotion.rst
  docs/type_promotion.rst
Labels: cla: yes, pull ready

#7659 logsumexp: fix issue with debug_nans
  jax/_src/scipy/special.py
  tests/lax_scipy_test.py
Labels: cla: yes, pull ready

#7662 Require array-like inputs for jax.numpy set-like operations
  jax/_src/numpy/lax_numpy.py
Labels: cla: yes, pull ready

#6899 support custom PRNG implementations
  jax/__init__.py
  jax/_src/config.py
  jax/_src/prng.py
  jax/_src/random.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/prng.py
  jax/random.py
  tests/api_test.py
  tests/pmap_test.py
  tests/random_test.py
Labels: cla: yes, pull ready

#7679 cleanup: remove redundant entry from test-requirements
  build/test-requirements.txt
Labels: cla: yes, pull ready

#7678 cleanup: remove some unnecessary test boilerplate
  tests/linalg_test.py
Labels: cla: yes, pull ready

#7672 chore(ci) : setup dependabot for pip and github-actions
  .github/dependabot.yml
Labels: cla: yes, pull ready

#6750 Default to `jnp.float_` type in `nn.initializers`
  jax/_src/nn/initializers.py
  tests/jet_test.py
  tests/stax_test.py
  tests/xmap_test.py
Labels: cla: yes, pull ready

#7681 inline jit-decorated jax.random calls
  jax/_src/prng.py
  jax/_src/random.py
Labels: cla: yes, kokoro:force-run, pull ready

#7689 re-enable test for jnp.linalg.lstsq
  tests/linalg_test.py
Labels: cla: yes, pull ready

#7688 CI: bump mypy & flake8 versions to newest
  .pre-commit-config.yaml
  build/test-requirements.txt
Labels: cla: yes, pull ready

#7666 Specify weak_type in DeviceArray repr
  docs/glossary.rst
  docs/type_promotion.rst
  jax/_src/api.py
  jax/_src/custom_derivatives.py
  jax/_src/errors.py
  jax/_src/tree_util.py
  jax/interpreters/xla.py
  tests/dtypes_test.py
Labels: cla: yes, pull ready

#7680 Specify scipy in setup.py install_requires
  setup.py
Labels: cla: yes, pull ready

#7188 Add documentation for jax.device_get
  docs/jax.rst
  jax/_src/api.py
Labels: cla: yes, pull ready

#7690 Update maml.md
  docs/notebooks/maml.md
Labels: cla: yes, pull ready

#7699 jnp.where: provide fill_value for single-argument form
  jax/_src/numpy/lax_numpy.py
Labels: cla: yes, pull ready

#7705 maml.ipynb: fix sync issue
  docs/notebooks/maml.ipynb
Labels: cla: yes, kokoro:force-run, pull ready

#7704 import in the JAX namespace
  jax/__init__.py
Labels: cla: yes, pull ready

#7692 add support for scipy.special.{expn,expi,exp1}
  docs/jax.scipy.rst
  jax/_src/scipy/special.py
  jax/scipy/special.py
  tests/lax_scipy_test.py
Labels: cla: yes, pull ready

#7744 nansum/nanprod: add missing dtype validation
  jax/_src/numpy/lax_numpy.py
Labels: cla: yes, pull ready

#7732 Require array-like inputs for jnp.poly functions
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
Labels: cla: yes, pull ready

#7746 ensure lax.transpose and lax.reshape always return DeviceArrays
  jax/_src/lax/lax.py
Labels: cla: yes, pull ready

#7206 Fix while loop fixed point condition
  jax/_src/lax/control_flow.py
  jax/interpreters/batching.py
Labels: cla: yes, pull ready

#7711 Fix typo in autodidax `transpose`
  docs/autodidax.ipynb
  docs/autodidax.md
  docs/autodidax.py
Labels: cla: yes, kokoro:force-run, pull ready

#7758 Add jit to lax.fft
  jax/_src/lax/fft.py
  jax/_src/numpy/fft.py
  tests/lax_vmap_test.py
Labels: cla: yes, pull ready

#7717 Make `input_shape` explicitly integer-typed in `_reduce_jvp`
  jax/_src/lax/lax.py
  tests/lax_autodiff_test.py
Labels: cla: yes, pull ready
