Repository jax-ml/jax, pull requests merged in 2021-11, with the labels that each got.

#8421 Implement hermitian=... option on jax.numpy.linalg.svd.
  jax/_src/numpy/linalg.py
  tests/linalg_test.py
Labels: cla: yes, pull ready

#8043 DeviceArray.__iter__ returns DeviceArrays, without host sync
  jax/_src/lax/lax.py
  jax/_src/numpy/lax_numpy.py
  jax/interpreters/pxla.py
  jax/interpreters/xla.py
  tests/api_test.py
  tests/lax_test.py
Labels: cla: yes, pull ready

#8422 jax.numpy: add missing uint definition
  jax/_src/dtypes.py
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.py
Labels: cla: yes, pull ready

#8402 [sparse] add transpose rule for coo_matmat
  jax/experimental/sparse/ops.py
  tests/sparse_test.py
Labels: cla: yes, pull ready

#8426 jax.numpy: fix boolean indexing with Ellipsis
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: cla: yes, pull ready

#8424 jnp.result_type: respect default types
  jax/_src/dtypes.py
  tests/dtypes_test.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#8404 [sparse] add autodiff & transpose rules for csr primitives
  jax/experimental/sparse/ops.py
  tests/sparse_test.py
Labels: cla: yes, pull ready

#8437 Update coo_matvec and coo_matmat docstrings.
  jaxlib/cusparse.py
Labels: cla: yes, pull ready

#8433 [sparse] refactor csr_to_coo utility
  jax/experimental/sparse/ops.py
  tests/sparse_test.py
Labels: cla: yes, pull ready

#8430 jax.random.permutation: add independent keyword
  CHANGELOG.md
  jax/_src/random.py
  tests/random_test.py
Labels: cla: yes, pull ready

#8445 Print the bazel version from build.py.
  build/build.py
Labels: cla: yes, pull ready

#8459 [jax2tf] Improve the documentation for jax2tf and SavedModel
  jax/experimental/jax2tf/README.md
Labels: cla: yes, pull ready

#8464 [sparse] simplify bcoo_dot_general implementation
  jax/experimental/sparse/bcoo.py
Labels: cla: yes, pull ready

#8451 add internal `vmappable` interface (part 1)
  jax/_src/api.py
  jax/_src/lax/control_flow.py
  jax/interpreters/batching.py
  tests/api_test.py
  tests/batching_test.py
Labels: cla: yes, pull ready

#8467 generalize lax.cond to accept any number of args
  jax/_src/lax/control_flow.py
Labels: cla: yes, pull ready

#8438 [sparse]: add tracer-based implementation of sparsify
  jax/experimental/sparse/__init__.py
  jax/experimental/sparse/transform.py
  tests/sparsify_test.py
Labels: cla: yes, pull ready

#8455 [sparse] add full support for BCOO matmul operator
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: cla: yes, pull ready

#8474 generalize lax.switch to take any number of operands
  jax/_src/lax/control_flow.py
  tests/lax_control_flow_test.py
Labels: cla: yes, pull ready

#8486 jax_check_tracer_leaks: add warning about debuggers
  jax/_src/config.py
  jax/core.py
Labels: cla: yes, pull ready

#8450 Document jax.lax.Precision
  jax/_src/lax/lax.py
  jax/_src/lax/other.py
  jax/_src/lax/polar.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/scipy/eigh.py
Labels: cla: yes, pull ready

#8466 [sparse] register BCOO as a vmappable
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/ops.py
Labels: cla: yes, pull ready

#8485 colab_tpu.setup_tpu: allow user specification ot tpu driver version
  jax/tools/colab_tpu.py
Labels: cla: yes, pull ready

#8403 Generate a better error message if [pv]map receives no array arguments
  jax/_src/api.py
  tests/api_test.py
Labels: cla: yes, pull ready

#8488 fix up detection of old cond signature
  jax/_src/lax/control_flow.py
  tests/lax_control_flow_test.py
Labels: cla: yes, pull ready

#8498 refactor jax.numpy.meshgrid & improve validation
  jax/_src/numpy/lax_numpy.py
Labels: cla: yes, pull ready

#8457 [jax2tf] Fix typos.
  jax/experimental/jax2tf/shape_poly.py
Labels: cla: yes, pull ready

#8508 update version and changelog for pypi
  CHANGELOG.md
  jax/version.py
Labels: cla: yes, pull ready

#8507 [sparse] improve bcoo validation
  jax/experimental/sparse/bcoo.py
Labels: cla: yes, pull ready

#8382 small cleanups to AOT APIs
  jax/_src/api.py
  jax/interpreters/pxla.py
  tests/api_test.py
  tests/pjit_test.py
Labels: cla: yes, pull ready

#8515 [jax2tf] Improve the TF constant sharing
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/tf_test_util.py
Labels: cla: yes, pull ready

#8509 add Lowered and Compiled to the jax public package
  jax/__init__.py
Labels: cla: yes, pull ready

#8491 [sparse] bcoo_dot_general: support contraction along batch dimensions
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: cla: yes, pull ready

#8528 Make MLIR bindings build work under Bazel.
  .bazelrc
  WORKSPACE
  build/build_wheel.py
  jaxlib/mlir/_mlir_libs/BUILD.bazel
  jaxlib/setup.py
Labels: cla: yes, pull ready

#8520 jnp.percentile: use full precision for 64-bit inputs
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#8524 fix for translation to cudaDataType
  jaxlib/cusparse.cc
Labels: cla: yes, pull ready

#8532 [x64] set scalar defaults to 64-bit types
  jax/_src/dtypes.py
Labels: cla: yes, pull ready

#8546 update readme to focus on most active libraries
  README.md
Labels: cla: yes, pull ready

#8547 [sparse] add dtype assertions to several cusparse wrappers
  jaxlib/cusparse.py
Labels: cla: yes, pull ready

#8534 [x64] jnp.array: improve type inference testing
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes, kokoro:force-run, pull ready

#8535 [x64] clean up usage of dtypes.dtype
  jax/_src/lax/lax.py
  jax/_src/numpy/lax_numpy.py
  jax/experimental/djax.py
  jax/interpreters/mlir.py
Labels: cla: yes, pull ready

#8548 [sparse] re-enable bcoo_spdot_general test
  tests/sparse_test.py
Labels: cla: yes, pull ready

#8549 Enable testWhileLoopBatchedWithConstBody for GPU
  tests/lax_control_flow_test.py
Labels: cla: yes, pull ready

#8499 Properly handle bfloat16 in jnp.load()
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#8562 Update XLA.
  WORKSPACE
Labels: cla: yes, pull ready

#8561 add donate_argnums/donated_invars to AOT structs
  jax/_src/api.py
  jax/experimental/pjit.py
  jax/interpreters/pxla.py
  jax/interpreters/xla.py
  tests/api_test.py
  tests/pjit_test.py
Labels: cla: yes, pull ready

#8381 Support reshape/concatenate/broadcast on PRNGKeyArrays.
  jax/_src/numpy/lax_numpy.py
  jax/_src/prng.py
  tests/random_test.py
Labels: cla: yes, pull ready

#8564 Fix test failures and update changelog.
  CHANGELOG.md
  jax/_src/lax/lax.py
Labels: cla: yes, pull ready

#8560 [sparse] add BCOO.sum_duplicates() with nse option
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: cla: yes, pull ready

#8550 Update TFLite concrete function conversion codes to have the associat…
  jax/experimental/jax2tf/examples/tflite/mnist/README.md
  jax/experimental/jax2tf/examples/tflite/mnist/mnist.py
  jax/experimental/jax2tf/examples_eval/converters.py
Labels: cla: yes, pull ready

#8544 [x64] Add test of jnp.arange() dtype corner case
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#8559 [sparse] ensure shapes are represented as tuples
  jax/experimental/sparse/ops.py
  tests/sparse_test.py
Labels: cla: yes, pull ready

#8555 Change QR import in lax.linalg.qdwh.
  jax/_src/lax/qdwh.py
Labels: cla: yes, pull ready

#8583 Remove stray print statements
  tests/sparse_test.py
Labels: cla: yes, pull ready

#8574 Update jaxlib versions.
  CHANGELOG.md
  jaxlib/version.py
  setup.py
Labels: cla: yes, pull ready

#8516 [shape_poly] Update arange and image_resize to support shape polymorphism
  jax/_src/image/scale.py
  jax/_src/numpy/lax_numpy.py
  jax/core.py
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  tests/image_test.py
Labels: cla: yes, pull ready

#8594 Delete the XLA in Python notebook.
  docs/index.rst
  docs/notebooks/XLA_in_Python.ipynb
  docs/notebooks/XLA_in_Python.md
Labels: cla: yes, pull ready

#8581 [sparse] support type promotion in CSR/COO matmul
  jax/experimental/sparse/ops.py
  tests/sparse_test.py
Labels: cla: yes, pull ready

#8567 jnp.unique: ensure that output dtype is not affected by fill_value
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#8598 Increase minimum jaxlib version to 0.1.74.
  jax/_src/api.py
  jax/_src/lax/lax.py
  jax/_src/lax/linalg.py
  jax/experimental/compilation_cache/compilation_cache.py
  jax/interpreters/mlir.py
  jax/interpreters/pxla.py
  jax/version.py
  tests/api_test.py
  tests/debug_nans_test.py
  tests/lax_numpy_indexing_test.py
  tests/linalg_test.py
  tests/pickle_test.py
  tests/pjit_test.py
  tests/pmap_test.py
  tests/tree_util_test.py
Labels: cla: yes, pull ready

#8584 [sparse] fix batched version of BCOO.sum_duplicates
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: cla: yes, pull ready

#8601 make vmap ppermute consistent with pmap/docstring
  jax/_src/lax/parallel.py
  tests/batching_test.py
  tests/pmap_test.py
Labels: cla: yes, pull ready

#8565 [sparse] spdot_general: implement more cases
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: cla: yes, pull ready

#8602 Increment minimum jaxlib version in mypy precommit hook.
  .pre-commit-config.yaml
  jax/interpreters/pxla.py
Labels: cla: yes, pull ready

#8576 [sparse] bcoo_[sp]dot_general: require inputs to have the same type
  jax/experimental/sparse/bcoo.py
Labels: cla: yes, pull ready

#8606 Split windowed reductions and their gradients into a separate file in…
  jax/_src/lax/control_flow.py
  jax/_src/lax/lax.py
  jax/_src/lax/windowed_reductions.py
  jax/experimental/jax2tf/impl_no_xla.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jet.py
  jax/lax/__init__.py
Labels: cla: yes, pull ready

#8552 generalize jaxpr simplification machinery, fix convert_element_type simplification and add one for broadcast
  docs/jaxpr.rst
  jax/_src/lax/lax.py
  jax/core.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
  tests/host_callback_test.py
  tests/x64_context_test.py
Labels: cla: yes, pull ready

#8624 jnp.quantile: explicitly raise error for complex input
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#8643 [jax2tf] Fix formatting for README.md
  jax/experimental/jax2tf/README.md
Labels: cla: yes, pull ready

#8648 [x64] avoid dtype conversions for arange arguments
  jax/_src/numpy/lax_numpy.py
Labels: cla: yes, pull ready

#8652 Document lax.GatherScatterMode.
  docs/jax.lax.rst
  jax/_src/lax/lax.py
Labels: cla: yes, pull ready

#8449 ahead-of-time lowering and compilation for pmap
  jax/_src/api.py
  jax/interpreters/pxla.py
  tests/pmap_test.py
Labels: cla: yes, pull ready

#7839 [jax2tf] Force TF compilation for code under jax.jit.
  CHANGELOG.md
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/tf_test_util.py
Labels: cla: yes, pull ready

#8653 [x64] make x64_context_test more robust
  tests/x64_context_test.py
Labels: cla: yes, pull ready

#8657 Fix lint and mypy errors
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: cla: yes, pull ready

#8629 [x64] regularize dtype helpers
  jax/_src/api.py
  jax/_src/dtypes.py
  jax/_src/lax/lax.py
  jax/_src/numpy/lax_numpy.py
  tests/dtypes_test.py
  tests/lax_test.py
Labels: cla: yes, pull ready

#8658 Improve error when jnp.arange is used with non-constant arguments
  jax/_src/numpy/lax_numpy.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  jax/interpreters/masking.py
Labels: cla: yes, pull ready

#8656 complete annotation for XLA bridge functions that take a backend name…
  jax/_src/lib/xla_bridge.py
  jax/interpreters/pxla.py
Labels: cla: yes, pull ready

#8663 cleanup: remove stray debugging breakpoint
  jax/interpreters/batching.py
Labels: cla: yes, pull ready

#8661 [x64] Make autodiff respect weak types
  jax/_src/abstract_arrays.py
  jax/_src/ad_checkpoint.py
  jax/_src/api.py
  jax/_src/lax/lax.py
  jax/core.py
  tests/api_test.py
Labels: cla: yes, pull ready

#8676 [hcb] Cleanup to account for changes in minimum jaxlib version
  jax/experimental/host_callback.py
Labels: cla: yes, pull ready, cleanup

#8522 Add numerical comparison for jax2tf -> TFLite
  jax/experimental/jax2tf/examples_eval/all_examples.py
  jax/experimental/jax2tf/examples_eval/converters.py
  jax/experimental/jax2tf/examples_eval/converters_results.md
  jax/experimental/jax2tf/examples_eval/converters_results.md.template
  jax/experimental/jax2tf/examples_eval/examples_converter.py
  jax/experimental/jax2tf/examples_eval/examples_test.py
Labels: cla: yes, pull ready

#8668 Cleanup: remove duplicate canonicalize_axis utility
  jax/_src/lax/control_flow.py
  jax/_src/lax/lax.py
  jax/_src/random.py
  jax/_src/scipy/fft.py
  jax/_src/util.py
Labels: cla: yes, pull ready

#8671 ahead-of-time lowering and compilation frontend for xmap
  jax/experimental/maps.py
  tests/xmap_test.py
Labels: cla: yes, pull ready

#8667 custom pp_eqn rules, simpler xla_call print
  docs/jaxpr.rst
  jax/core.py
  jax/interpreters/xla.py
Labels: cla: yes, pull ready

#8692 make PmapComputation.hlo a method
  jax/interpreters/pxla.py
Labels: cla: yes, pull ready

#8665 tweak implementation of lax._array_copy (underlying jnp.array(x, copy=True))
  jax/_src/lax/lax.py
  jax/experimental/jax2tf/jax2tf.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#8694 [x64] make scan masking rule more type safe
  jax/_src/lax/control_flow.py
  tests/masking_test.py
Labels: cla: yes, pull ready

#8700 Fix MLIR CAPI DLL build
  WORKSPACE
  build/BUILD.bazel
  jaxlib/jax.bzl
  jaxlib/mlir/_mlir_libs/BUILD.bazel
Labels: cla: yes, pull ready

#8696 conv_transpose: allow padding to be specified as a list
  jax/_src/lax/convolution.py
  tests/lax_test.py
Labels: cla: yes, pull ready

#8704 [jax2tf] Implement CLIP mode for scatter.
  jax/_src/lax/slicing.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: cla: yes, pull ready

#8728 Leak checker: garbage collect before collecting hanging references.
  jax/core.py
Labels: cla: yes, pull ready

#8719 [x64] jnp.pad: preserve weak types of inputs
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#8735 Update device_get docs to mention parrallelism.
  jax/_src/api.py
Labels: cla: yes, pull ready

#8329 Fix typo in doc for barrier_wait
  jax/experimental/host_callback.py
Labels: cla: yes, pull ready

#8339 clarify code in experimental/ode
  jax/experimental/ode.py
Labels: cla: yes, pull ready
