Repository jax-ml/jax, pull requests merged in 2021-12, with the labels that each got.

#8650 Enable QDWH TPU tests.
  jax/_src/lax/qdwh.py
  tests/qdwh_test.py
Labels: cla: yes, pull ready

#8681 DOC: add FAQ section on JAX vs. Numpy performance
  docs/faq.rst
  docs/notebooks/quickstart.ipynb
  docs/notebooks/quickstart.md
Labels: cla: yes, documentation, pull ready

#8722 [x64] preserve weak types in jax.scipy.sparse solvers
  jax/_src/scipy/sparse/linalg.py
  tests/lax_scipy_sparse_test.py
Labels: cla: yes, pull ready

#8741 [x64] improve consistency in handling dtype=None
  jax/_src/dtypes.py
  jax/_src/numpy/lax_numpy.py
  jax/experimental/sparse/bcoo.py
  tests/dtypes_test.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#8742 [sparse] add sparse.empty() utility to create empty matrix
  jax/experimental/sparse/__init__.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/ops.py
  tests/sparse_test.py
Labels: cla: yes, pull ready

#8716 Refactor the lowering of remat
  jax/_src/ad_checkpoint.py
  jax/_src/lax/control_flow.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/interpreters/mlir.py
  jax/interpreters/partial_eval.py
  jax/interpreters/xla.py
Labels: cla: yes, pull ready

#8727 [jax2tf] Add tests for rng_uniform
  jax/experimental/jax2tf/g3doc/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
  jax/experimental/jax2tf/tests/primitive_harness.py
Labels: cla: yes, pull ready

#8748 [jax2tf] Improve call_tf error checking for TF functions with dynamic output shapes
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/call_tf.py
  jax/experimental/jax2tf/tests/call_tf_test.py
Labels: cla: yes, pull ready

#8753 add jax.experimental.checkify transformation
  jax/core.py
  jax/experimental/checkify.py
  tests/checkify_test.py
Labels: cla: yes, pull ready

#8718 DOC: add documentation for configuration functionality
  docs/jax.config.rst
  docs/jax.rst
Labels: cla: yes, pull ready

#8766 Update Bazel to 4.2.1.
  .bazelversion
  build/build.py
Labels: cla: yes, pull ready

#8754 lax.convert_element_type: stricter dtype validation
  jax/_src/dtypes.py
  jax/_src/lax/lax.py
  jax/_src/numpy/lax_numpy.py
  tests/dtypes_test.py
Labels: cla: yes, pull ready

#8743 [x64] ensure scatter functionality preserves weak_type
  jax/_src/ops/scatter.py
  tests/lax_numpy_indexing_test.py
Labels: cla: yes, pull ready

#8760 [x64] make jax.numpy functionality respect default dtypes
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: cla: yes, pull ready

#8773 add an assert primitive
  jax/experimental/checkify.py
  tests/checkify_test.py
Labels: cla: yes, pull ready

#8777 Update workspace file for py 3.10 release test
  WORKSPACE
Labels: cla: yes, pull ready

#8780 [sparse] BCOO.sum_duplicates: fix handling of explicit zeros
  jax/_src/numpy/lax_numpy.py
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: cla: yes, pull ready

#8768 DOC: mark jax.enable_custom_prng as transient
  jax/_src/config.py
Labels: cla: yes, pull ready

#8788 Update TF commit for jaxlib release
  WORKSPACE
Labels: pull ready

#8778 generalize assert primitive, allow recharging
  jax/experimental/checkify.py
  tests/checkify_test.py
Labels: cla: yes, pull ready

#8798 methods for retrieving IRs from each AOT stage
  jax/_src/api.py
Labels: cla: yes, pull ready

#8774 Add `profiler.annotate_function` to some internals
  jax/_src/device_array.py
  jax/_src/dispatch.py
  jax/_src/profiler.py
  jax/interpreters/partial_eval.py
  jax/interpreters/pxla.py
  jax/interpreters/xla.py
Labels: cla: yes, pull ready

#8824 Fix keyword argument confusion in jax.profiler.annotate_function deco…
  jax/_src/profiler.py
  tests/profiler_test.py
Labels: cla: yes, pull ready

#8830 jnp.lexsort: fix canonicalization of default int
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#8829 Add checkify rule for scan.
  jax/experimental/checkify.py
  tests/checkify_test.py
Labels: cla: yes, pull ready

#8842 Update WORKSPACE
  WORKSPACE
Labels: pull ready

#8792 [sparse] make JAXSparse an ABC & declare BCOO methods
  jax/experimental/sparse/_base.py
  jax/experimental/sparse/coo.py
  jax/experimental/sparse/csr.py
Labels: cla: yes, pull ready

#8838 [sparse] add sparse rule for broadcast_in_dim
  jax/experimental/sparse/__init__.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/transform.py
  tests/sparse_test.py
Labels: pull ready

#8795 [sparse] initial implementation of sparse-sparse multiply
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/transform.py
  tests/sparse_test.py
Labels: cla: yes, pull ready

#8834 [x64] add new jax_default_dtype flag
  jax/_src/config.py
  jax/_src/dtypes.py
  tests/dtypes_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#8847 Relax test tolerance for slogdet gradient test.
  tests/linalg_test.py
Labels: pull ready

#8849 [x64] minor weak_type changes to linalg.py
  jax/_src/numpy/linalg.py
  jax/_src/scipy/sparse/linalg.py
Labels: pull ready

#8843 [x64]: improve dtype mismatch errors for lax functions
  jax/_src/lax/lax.py
Labels: better_errors, pull ready

#8850 err on transformation of AOT-compiled function calls
  jax/_src/api.py
  tests/api_test.py
Labels: pull ready

#8860 Add checkify rule for while_loop.
  jax/experimental/checkify.py
  tests/checkify_test.py
Labels: pull ready

#8848 [sparse] add jvp rule for bcoo_spdot_general
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: pull ready

#8870 Add missing gmres test (part of #8849)
  tests/lax_scipy_sparse_test.py
Labels: pull ready

#8865 [x64] make x64_context tests work with updated default dtypes
  jax/experimental/x64_context.py
Labels: pull ready

#8864 [x64] make jax.experimental.loops consistent with default dtype flag
  jax/experimental/loops.py
  tests/loops_test.py
Labels: pull ready

#8861 [x64] make lax_numpy_test.py pass with 32-bit defaults
  jax/_src/test_util.py
  tests/lax_numpy_test.py
Labels: pull ready

#8873 Add `contiguous_submeshes` option to `mesh_utils.create_device_mesh()`.
  jax/experimental/mesh_utils.py
  jax/experimental/pjit.py
  jax/interpreters/pxla.py
  tests/mesh_utils_test.py
Labels: pull ready

#8868 Testing: avoid hard-coding random seeds
  examples/control_test.py
  examples/examples_test.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  tests/api_test.py
  tests/batching_test.py
  tests/host_callback_test.py
  tests/infeed_test.py
  tests/jet_test.py
  tests/lax_autodiff_test.py
  tests/lax_control_flow_test.py
  tests/lax_numpy_indexing_test.py
  tests/lax_numpy_test.py
  tests/lax_scipy_test.py
  tests/masking_test.py
  tests/ode_test.py
  tests/optimizers_test.py
  tests/pjit_test.py
  tests/pmap_test.py
  tests/polynomial_test.py
  tests/random_test.py
  tests/stax_test.py
  tests/third_party/scipy/line_search_test.py
  tests/xmap_test.py
Labels: pull ready

#8897 [sparse] fix issue with duplicate indices in BCOO.__mul__
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: pull ready

#8886 [x64] make random_test pass with jax_default_dtype_bits=32
  jax/_src/test_util.py
  tests/random_test.py
Labels: pull ready

#8902 examples tests: avoid use of private jax utilities
  examples/control_test.py
  examples/examples_test.py
Labels: pull ready

#8852 [sparse] Update bcoo_dot_general GPU translation rule.
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
  tests/sparsify_test.py
Labels: pull ready

#8678 [hcb] Simplifications to the host_calback API
  CHANGELOG.md
  jax/_src/config.py
  jax/_src/test_util.py
  jax/experimental/host_callback.py
  tests/host_callback_test.py
Labels: cla: yes, pull ready

#8763 Refactor the lowering of remat.
  jax/_src/ad_checkpoint.py
  jax/_src/lax/control_flow.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/interpreters/mlir.py
  jax/interpreters/partial_eval.py
  jax/interpreters/xla.py
Labels: cla: yes, pull ready

#8898 [x64] fix jax2tf_test for default_dtype
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: pull ready

#8929 [sparse] add sparse rule for lax.sub_p
  jax/experimental/sparse/transform.py
  tests/sparsify_test.py
Labels: pull ready

#8930 Handle the edge case where two `pjit.FROM_GDA` singletons are created.
  jax/experimental/pjit.py
  tests/pjit_test.py
Labels: pull ready

#8931 log tracing and compilation times
  jax/_src/dispatch.py
  jax/experimental/maps.py
  jax/experimental/pjit.py
  jax/interpreters/pxla.py
  tests/api_test.py
Labels: pull ready

#8876 Finish jax2tf no_xla documentation
  jax/experimental/jax2tf/converters_eval/no_xla_limitations.md
Labels: pull ready

#8938 jnp.array: remove unused device argument
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#8940 handle trivial case for ppermute batching rule
  jax/_src/lax/parallel.py
  tests/batching_test.py
Labels: pull ready

#8942 Include compute capability 8.0 SASS in jaxlib wheels.
  .bazelrc
  CHANGELOG.md
  WORKSPACE
  build/build.py
Labels: pull ready

#8952 testArray: add missing jit
  tests/lax_numpy_test.py
Labels: pull ready

#8939 jnp.array: propagate ndmin argument for memoryviews
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#8946 fix leak checker interaction with custom_jvp
  jax/interpreters/partial_eval.py
  tests/nn_test.py
Labels: pull ready

#8951 make ravel_pytree unraveler dtype-polymorphic
  jax/_src/flatten_util.py
  tests/tree_util_test.py
Labels: pull ready

#8949 add jax.block_until_ready to docs and changelog
  CHANGELOG.md
  docs/jax.rst
Labels: pull ready

#8907 [hcb] Add support for remat2 to host_callback
  CHANGELOG.md
  jax/_src/dispatch.py
  jax/core.py
  jax/experimental/host_callback.py
  jax/interpreters/partial_eval.py
  tests/host_callback_test.py
Labels: pull ready

#8934 Tweak documentation on error handling for host_callback.call()
  jax/experimental/host_callback.py
Labels: pull ready

#8926 fix: thread fill_value option
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#8948 jnp.array: use jax-style promotion for list inputs
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#8963 Add item() method to abstract arrays
  jax/_src/numpy/lax_numpy.py
  tests/api_test.py
Labels: pull ready

#8968 doc: move stub section to bottom of FAQ
  docs/faq.rst
Labels: pull ready

#8997 Make sure while_loop cond generates an error even if it returns False.
  jax/experimental/checkify.py
  tests/checkify_test.py
Labels: pull ready

#9000 Add NaN checkify rule to all lax primitives.
  jax/experimental/checkify.py
Labels: pull ready

#9002 custom_prng: generalize indexing of PRNGKeyArray
  jax/_src/numpy/lax_numpy.py
  jax/_src/prng.py
  tests/random_test.py
Labels: pull ready

#9010 Fix SyntaxError in `jax_to_ir`
  jax/tools/jax_to_ir.py
Labels: pull ready

#9033 Fix straight-through estimator example in docs (#9032)
  docs/jax-101/04-advanced-autodiff.ipynb
  docs/jax-101/04-advanced-autodiff.md
Labels: pull ready

#9037 Annotate api_boundary
  jax/_src/traceback_util.py
Labels: pull ready

#8990 checkify: small updates
  jax/experimental/checkify.py
Labels: pull ready

#8947 add limit to number of tracer provenance lines
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: pull ready

#9001 docs: add FAQ section about jit compilation & numerics
  docs/faq.rst
Labels: pull ready

#9022 [sparse] add size attribute to sparse objects
  jax/experimental/sparse/_base.py
  tests/sparse_test.py
Labels: pull ready

#9025 [sparse] mark sparse objects as unhashable
  jax/experimental/sparse/_base.py
  tests/sparse_test.py
Labels: pull ready

#9026 [sparse] make sparse.todense() work for scalars
  jax/experimental/sparse/api.py
  tests/sparse_test.py
Labels: pull ready

#9061 fix indexing with ellipsis & boolean mask
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#8390 support null shape in jax.random.poisson
  jax/_src/random.py
  tests/random_test.py
Labels: cla: yes, pull ready

#9029 Add `where=` arg to jax.nn.{softmax, log_softmax, normalize}.
  jax/_src/nn/functions.py
  tests/nn_test.py
Labels: pull ready

#9058 Update the JAX 101 tutorial: replace deprecated jax.ops.index_* functions with the new index update operators
  docs/jax-101/01-jax-basics.ipynb
  docs/jax-101/01-jax-basics.md
  jax/_src/numpy/lax_numpy.py
Labels: pull ready
