Repository jax-ml/jax, pull requests merged in 2022-01, with the labels that each got.

#9084 Clean up backwards-compatibility support for remat lowering
  jax/_src/ad_checkpoint.py
  jax/_src/lax/control_flow.py
  jax/interpreters/xla.py
Labels: pull ready

#9089 Fix test failures under Numpy 1.22.
  jax/_src/dtypes.py
  jax/_src/numpy/lax_numpy.py
  pytest.ini
  tests/lax_numpy_test.py
Labels: pull ready

#9103 [sparse] add getitem stub in JAXSparse
  jax/experimental/sparse/_base.py
Labels: pull ready

#9097 Update sphinx-related packages
  docs/requirements.txt
Labels: pull ready

#9109 clean up WrappedFun.call_wrapped refs on exception
  jax/linear_util.py
  tests/api_test.py
Labels: pull ready

#9106 remove axis name logic from standard Primitive / bind
  jax/core.py
Labels: pull ready

#8890 Add missing annotations to lax
  jax/_src/lax/lax.py
Labels: pull ready

#9074 custom vmap: entry point, batching, and JVP
  jax/_src/api.py
  jax/_src/custom_batching.py
  jax/custom_batching.py
  tests/api_test.py
Labels: pull ready

#9114 jnp.searchsorted: properly handle NaNs
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#8955 add staging logic for polymorphic shapes in jaxprs
  jax/_src/lax/lax.py
  jax/_src/lax/utils.py
  jax/core.py
  jax/interpreters/partial_eval.py
  tests/core_test.py
Labels: pull ready

#9093 Checkify: add division by zero check.
  jax/experimental/checkify.py
  tests/checkify_test.py
Labels: pull ready

#9020 Fix a type issue in odeint
  jax/experimental/ode.py
  tests/ode_test.py
Labels: pull ready

#9136 simpler jaxpr eqn params to bind params conversion
  jax/core.py
  jax/experimental/maps.py
  jax/interpreters/ad.py
  tests/core_test.py
Labels: pull ready

#9142 add JAX_BACKEND_TARGET env var, fixes #9034
  jax/_src/lib/xla_bridge.py
Labels: pull ready

#9126 Checkify: add scatter out-of-bounds error.
  jax/experimental/checkify.py
  tests/checkify_test.py
Labels: pull ready

#9128 [sparse] Generalize BCOO metadata
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/transform.py
  tests/sparse_test.py
Labels: pull ready

#9154 Fix DeviceArray class reference
  docs/glossary.rst
Labels: pull ready

#9123 Fix host_callback docs
  jax/experimental/host_callback.py
Labels: pull ready

#9143 fix jaxpr type checking error messages
  jax/core.py
  jax/experimental/maps.py
  tests/core_test.py
Labels: pull ready

#9164 checkify: tweak some organization and names
  jax/experimental/checkify.py
Labels: pull ready

#9134 custom transposition: registration, transposition, translation, and abstract evaluation
  jax/_src/api.py
  jax/_src/custom_transpose.py
  jax/custom_transpose.py
  jax/experimental/jax2tf/jax2tf.py
  tests/api_test.py
Labels: pull ready

#9162 de-duplicate util.memoize and util.cache
  jax/_src/util.py
Labels: pull ready

#8915 fix a custom_vjp post_process bug, related cleanups
  jax/_src/custom_derivatives.py
  jax/core.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/maps.py
  jax/interpreters/ad.py
  jax/interpreters/batching.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: pull ready

#8869 Remove all `stop_gradient` calls from `custom_root`.
  docs/notebooks/Custom_derivative_rules_for_Python_code.ipynb
  docs/notebooks/Custom_derivative_rules_for_Python_code.md
  jax/_src/lax/control_flow.py
  tests/lax_control_flow_test.py
Labels: pull ready

#9175 enable custom transformation "stacking"
  jax/_src/custom_api_util.py
  jax/_src/custom_batching.py
  jax/_src/custom_derivatives.py
  jax/_src/custom_transpose.py
  tests/api_test.py
Labels: pull ready

#9186 add `random.default_prng_impl` to retrieve the default PRNG implementation
  jax/_src/random.py
  jax/random.py
  tests/random_test.py
Labels: pull ready

#9178 lax.sort: regularize handling of -0.0 and -NaN
  CHANGELOG.md
  jax/_src/lax/lax.py
  tests/lax_numpy_test.py
  tests/lax_test.py
Labels: pull ready

#9127 searchsorted: use correct ordering for complex inputs
  jax/_src/lax/lax.py
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#9200 Add ensure_compile_time_eval docstring to docs
  docs/jax.rst
Labels: pull ready

#9189 [jax2tf] Add jax2tf_associative_scan_reductions flag
  CHANGELOG.md
  jax/__init__.py
  jax/_src/config.py
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: pull ready

#9205 einsum: clarify use of precision.
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#9184 jnp.unique: properly handle NaN values
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#9201 Checkify: add way to disable categories of errors.
  jax/experimental/checkify.py
  tests/checkify_test.py
Labels: pull ready

#9227 update version and changelog for pypi
  CHANGELOG.md
  jax/version.py
Labels: pull ready

#9209 [sparse] add bcoo_sort_indices
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: pull ready

#9094 lax.dynamic_update_slice: fix batching rule
  jax/_src/lax/slicing.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  tests/lax_test.py
Labels: pull ready

#9179 jax2tf: Small fix for backprop through functions using bfloat16
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: pull ready

#9230 Correct lax.while_loop type annotation
  jax/_src/lax/control_flow.py
Labels: pull ready

#9210 custom vmap: abstract eval and translation
  jax/_src/custom_batching.py
  jax/experimental/jax2tf/jax2tf.py
  tests/api_test.py
Labels: pull ready

#9236 checkify: fix and test post_process_call/map
  jax/experimental/checkify.py
  tests/checkify_test.py
Labels: pull ready

#9253 pjit: add test for basic static_argnums
  jax/experimental/pjit.py
  tests/pjit_test.py
Labels: pull ready

#9254 NotImplementedError for new_checkpoint-of-xmap
  jax/_src/lax/control_flow.py
  jax/experimental/maps.py
  jax/interpreters/partial_eval.py
  jax/interpreters/pxla.py
  tests/xmap_test.py
Labels: pull ready

#9267 re-enable tests of #8955
  jax/interpreters/partial_eval.py
  tests/core_test.py
Labels: pull ready

#9170 Fix `barrier_wait` example
  jax/experimental/host_callback.py
Labels: pull ready

#9268 jnp.angle: support deg keyword
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#8420 Support has_aux for jacfwd and jacrev
  jax/_src/api.py
  tests/api_test.py
Labels: cla: yes, pull ready

#9246 add origin info to leaked tracer error message and vmap tracers
  jax/core.py
  jax/interpreters/batching.py
  jax/interpreters/partial_eval.py
Labels: kokoro:force-run, pull ready

#9276 support generating bit widths other than 32 in `lax.rng_bit_generator`
  jax/_src/lax/lax.py
  tests/lax_test.py
  tests/random_test.py
Labels: pull ready

#9239 Eliminate redundancies in jax.scipy.linalg.expm
  jax/_src/scipy/linalg.py
Labels: pull ready

#9258 Add more documentation for buffer donation
  docs/faq.rst
  jax/_src/api.py
  jax/experimental/maps.py
  jax/experimental/pjit.py
  jax/interpreters/mlir.py
  jax/interpreters/xla.py
Labels: pull ready

#9257 [jax2tf] Improve shape polymorphism for scatter with CLIP mode
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#9295 [jax2tf] Move the no_xla_limitations documentation
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/converters_eval/README.md
  jax/experimental/jax2tf/g3doc/no_xla_limitations.md
Labels: pull ready

#9281 Fix auto-generated docstrings for JIT-compiled functions
  jax/_src/numpy/util.py
  tests/lax_numpy_test.py
Labels: pull ready

#9287 Add GDA to the API pages
  docs/jax.experimental.global_device_array.rst
  docs/jax.experimental.rst
  jax/experimental/global_device_array.py
Labels: pull ready

#9302 DOC: pin docutils==0.16 to restore bullets in lists
  docs/requirements.txt
Labels: pull ready

#9271 jnp.[nan]argmin/max: implement keepdims
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#9305 jax_jit_test: inherit from JaxTestCase
  tests/jax_jit_test.py
Labels: pull ready

#9301 disable implicit rank promotion for api_test
  tests/api_test.py
Labels: pull ready

#9300 [sparse] avoid implicit rank promotion
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
  tests/sparsify_test.py
Labels: pull ready

#9325 Make forces_retrace tests more robust
  tests/api_test.py
Labels: pull ready

#9314 Fix `max_squarings` in `jax.scipy.linalg.expm`
  jax/_src/scipy/linalg.py
Labels: pull ready

#9329 jaxpr staging: only one tracer per jaxpr variable
  jax/interpreters/partial_eval.py
Labels: pull ready

#9270 jax.numpy: add where and initial arguments to nan reductions
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#9309 linalg_test: disable implicit rank promotion
  jax/_src/lax/linalg.py
  jax/_src/numpy/linalg.py
  jax/_src/scipy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#9338 README: clarify installation instructions for Colab TPU
  README.md
Labels: pull ready

#9319 developer doc: more info on pre-commit
  docs/developer.md
Labels: kokoro:force-run, pull ready

#9339 testDisableNumpyRankPromotion: make test more robust
  tests/lax_numpy_test.py
Labels: pull ready

#9331 Update `get_compile_options` to accept Device objects.
  jax/_src/dispatch.py
  jax/_src/lib/xla_bridge.py
  jax/interpreters/pxla.py
  jax/interpreters/sharded_jit.py
  tests/host_callback_test.py
Labels: pull ready

#9343 test_util: export with_config
  jax/test_util.py
Labels: pull ready

#9352 Fix flaky testcase LaxTest.testConvTransposePaddingList on GPU.
  tests/lax_test.py
Labels: pull ready

#9353 Update XLA for jaxlib 0.1.76 release.
  CHANGELOG.md
  WORKSPACE
Labels: pull ready

#9345 DOC: add info about repeated indices to jax.ops docs
  docs/jax.ops.rst
Labels: pull ready

#9275 introduce `custom_batching.sequential_vmap`
  jax/_src/custom_batching.py
  jax/custom_batching.py
  tests/api_test.py
Labels: pull ready

#9359 Re-enable test of behavior from #8948
  tests/lax_numpy_test.py
Labels: pull ready

#9312 fix caching example in jit tutorial
  docs/jax-101/02-jitting.ipynb
  docs/jax-101/02-jitting.md
Labels: pull ready

#9341 disable implicit rank promotion in a number of remaining tests
  examples/examples_test.py
  jax/_src/lax/fft.py
  tests/batching_test.py
  tests/fft_test.py
  tests/infeed_test.py
  tests/lax_autodiff_test.py
  tests/lax_test.py
  tests/nn_test.py
  tests/pmap_test.py
  tests/qdwh_test.py
  tests/scipy_fft_test.py
  tests/scipy_stats_test.py
  tests/sharded_jit_test.py
  tests/stax_test.py
  tests/xmap_test.py
Labels: pull ready

#9368 Clarify the required NVidia driver versions in the JAX readme instruc…
  README.md
Labels: kokoro:force-run, pull ready

#9346 JaxTestCase: prevent leakage of global state
  jax/_src/test_util.py
Labels: pull ready

#9370 Increase bazel version to 5.0.0 to match TensorFlow
  .bazelversion
  CHANGELOG.md
  build/build.py
Labels: pull ready

#9373 Update pinned libtpu-nightly version for jaxlib 0.1.76
  setup.py
Labels: pull ready

#9385 Tolerate NumPy deprecation warnings when using older SciPy.
  conftest.py
  pytest.ini
Labels: pull ready

#9357 jnp.where: improve error for non-array inputs
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#9386 pjit_test: set jax_numpy_rank_promotion=raise
  tests/pjit_test.py
Labels: pull ready

#9393 Remove unused _asarray utility
  jax/_src/random.py
Labels: pull ready
