Repository jax-ml/jax, pull requests merged in 2022-10, with the labels that each got.

#12607 pure_callback: fix batching rule for multiple arguments
  jax/_src/callback.py
  tests/python_callback_test.py
Labels: pull ready

#12611 improve custom_jvp/vjp error messages
  jax/_src/custom_derivatives.py
  tests/api_test.py
Labels: better_errors, pull ready

#12624 Fix book links
  docs/notebooks/autodiff_cookbook.ipynb
  docs/notebooks/autodiff_cookbook.md
Labels: pull ready

#12612 [ROCm] Upgrade to ROCm 5.3 and associated enhancements
  build/rocm/Dockerfile.rocm
  build/rocm/run_single_gpu.py
  jaxlib/gpu_solver.py
  jaxlib/rocm/hipsolver.cc
  jaxlib/rocm/hipsolver_kernels.cc
  jaxlib/rocm/hipsolver_kernels.h
  tests/lobpcg_test.py
  tests/sparse_test.py
  tests/svd_test.py
Labels: pull ready

#12591 Add multiprocess GPU CI run with last public jaxlib release
  .github/workflows/nightly-ci-multiprocess-gpu.yml
  .github/workflows/slurm_job_scripts/multinode_pytest_jaxlib_nightly.sub
  .github/workflows/slurm_job_scripts/multinode_pytest_jaxlib_release.sub
Labels: pull ready

#12637 [typing] add full annotations for lax_numpy setops
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/setops.py
Labels: pull ready

#12628 Add an internal jtu.sample_product test decorator.
  jax/_src/test_util.py
  tests/lax_test.py
Labels: pull ready

#12653 jax.jacobian: propagate function signature to transformed function
  jax/_src/api.py
  tests/api_test.py
Labels: pull ready

#12641 Add types to jax/_src/numpy/util.py
  jax/_src/lax/lax.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
Labels: pull ready

#12639 Update version and CHANGELOG for jax 0.3.21 release
  CHANGELOG.md
  jax/version.py
Labels: pull ready

#12640 [dynamic-shapes] small fix to einsum (and indexing)
  jax/_src/lax/lax.py
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#12658 Fix collect_profile _src import
  jax/collect_profile.py
Labels: pull ready

#12657 [typing] add annotations to jax.numpy.linalg
  jax/_src/lax/lax.py
  jax/_src/numpy/linalg.py
Labels: pull ready

#12660 Migrate api_test, lax_numpy_test, and lax_vmap_test to
  jax/_src/test_util.py
  tests/api_test.py
  tests/lax_numpy_test.py
  tests/lax_vmap_test.py
Labels: pull ready

#12654 [typing] add annotations to numpy.fft
  jax/_src/numpy/fft.py
Labels: pull ready

#12642 Set JAX_PLATFORMS=tpu,cpu on TPUs
  CHANGELOG.md
  jax/_src/cloud_tpu_init.py
  jax/_src/lib/xla_bridge.py
Labels: pull ready

#12666 [typing] add types for jax.numpy.polynomial
  jax/_src/numpy/polynomial.py
Labels: pull ready

#12532 prod & sum: promote integers to default type rather than always 64
  jax/_src/numpy/reductions.py
Labels: pull ready

#12676 test: fix LaxNumpyTest:testConcatenate
  tests/lax_numpy_test.py
Labels: pull ready

#12686 Switch lax_numpy_indexing_test to use jtu.sample_product.
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#12573 [ROCM] Add TENSORFLOW_ROCM_COMMIT parameter to ROCM ci build
  build/rocm/build_rocm.sh
  build/rocm/ci_build.sh
Labels: pull ready

#12674 [typing] overloads for jnp.linalg.svd & jnp.linalg.qr
  jax/_src/basearray.pyi
  jax/_src/numpy/linalg.py
Labels: pull ready

#12678 jnp.average: support tuple axis
  jax/_src/numpy/reductions.py
  jax/_src/test_util.py
  tests/lax_numpy_operators_test.py
  tests/lax_numpy_reducers_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#12673 [typing] add type annotations to lax.linalg functions
  jax/_src/lax/linalg.py
  jax/_src/numpy/linalg.py
Labels: pull ready

#12691 fix -O / PYTHONOPTIMIZE bug
  jax/interpreters/partial_eval.py
Labels: kokoro:force-run, pull ready

#12197 [ROCm] Unit tests are fixed in ROCm
  tests/custom_linear_solve_test.py
  tests/lax_scipy_test.py
Labels: pull ready

#12693 Expand support for __jax_array__ in jnp.array.
  jax/_src/numpy/lax_numpy.py
  tests/api_test.py
Labels: pull ready

#12695 [jax2tf] Allow the use of DimPolynomial with jnp.array and binary operations
  jax/_src/numpy/lax_numpy.py
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  tests/api_test.py
Labels: pull ready

#12698 Update scipy version in jax.scipy.fft
  jax/_src/scipy/fft.py
  tests/scipy_fft_test.py
Labels: kokoro:force-run, pull ready

#12703 [ROCM] Add default setting for TENSORFLOW_ROCM_COMMIT
  build/rocm/ci_build.sh
Labels: pull ready

#12675 make device_put work with Sharding 2nd arg
  jax/_src/api.py
  jax/_src/dispatch.py
  jax/_src/numpy/lax_numpy.py
  jax/interpreters/pxla.py
  tests/api_test.py
Labels: pull ready

#12677 improve jit(f).lower(duck_args) and pjit(f).lower(duck_args)
  jax/_src/api.py
  jax/_src/stages.py
  jax/experimental/pjit.py
  jax/interpreters/pxla.py
  tests/array_test.py
  tests/pjit_test.py
Labels: pull ready

#12700 [typing] annotate jax.scipy.fft & jax.scipy.ndimage
  jax/_src/scipy/fft.py
  jax/_src/scipy/ndimage.py
Labels: pull ready

#12697 [typing] annotate lax.slicing
  jax/_src/lax/slicing.py
Labels: pull ready

#12722 Add changes accidentally omitted from
  tests/errors_test.py
  tests/image_test.py
  tests/qdwh_test.py
Labels: pull ready

#12727 [typing] add type annotations to jax.scipy.linalg
  jax/_src/scipy/linalg.py
  jax/_src/third_party/scipy/linalg.py
Labels: pull ready

#12746 changelog: add missing github commit links
  CHANGELOG.md
Labels: kokoro:force-run, pull ready

#12752 Update WORKSPACE and setup.py for jaxlib 0.3.22 release
  WORKSPACE
  setup.py
Labels: pull ready

#12738 add more info to pytree prefix key errors
  jax/_src/tree_util.py
  tests/pjit_test.py
  tests/tree_util_test.py
Labels: pull ready

#12748 [ROCm] Fixed build instructions typo
  build/rocm/README.md
Labels: pull ready

#12749 Port more tests from jtu.cases_from_list to jtu.sample_product.
  jax/_src/test_util.py
  tests/ann_test.py
  tests/callback_test.py
  tests/checkify_test.py
  tests/custom_object_test.py
  tests/debugging_primitives_test.py
  tests/for_loop_test.py
  tests/lax_numpy_operators_test.py
  tests/lax_numpy_reducers_test.py
  tests/lax_numpy_test.py
  tests/lax_numpy_vectorize_test.py
  tests/lax_test.py
  tests/linalg_test.py
  tests/scipy_optimize_test.py
Labels: pull ready

#12758 Update version.py, setup.py and CHANGELOG post jax 0.3.22 release
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: pull ready

#12766 Migrate remaining tests from jtu.cases_from_list to jtu.sample_product.
  jax/_src/test_util.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/primitives_test.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  tests/array_interoperability_test.py
  tests/host_callback_test.py
  tests/lax_autodiff_test.py
  tests/lax_numpy_reducers_test.py
  tests/lax_scipy_sparse_test.py
  tests/lax_scipy_test.py
  tests/multibackend_test.py
  tests/random_test.py
  tests/scipy_signal_test.py
  tests/scipy_stats_test.py
  tests/sparse_test.py
  tests/sparsify_test.py
  tests/stax_test.py
  tests/xmap_test.py
Labels: pull ready

#12750 Add JaxTestCase.assertNoWarnings
  jax/_src/test_util.py
  tests/lax_numpy_indexing_test.py
  tests/sparse_test.py
Labels: pull ready

#12771 DOC: switch order of custom_jvp and _wraps
  jax/_src/scipy/special.py
Labels: pull ready

#12772 Update version.py and CHANGELOG for jax 0.3.23 release
  CHANGELOG.md
  jax/version.py
Labels: pull ready

#12753 Make webpdb debugger lower priority
  jax/_src/debugger/web_debugger.py
Labels: pull ready

#12679 Avoid loading scipy eagerly.
  CHANGELOG.md
  jax/__init__.py
  jax/_src/lazy_loader.py
  jax/_src/lib/__init__.py
  jax/_src/nn/functions.py
  jax/_src/ops/special.py
  jax/_src/scipy/special.py
  jax/scipy/__init__.py
  jaxlib/lapack.cc
  jaxlib/lapack.py
  tests/BUILD
  tests/lazy_loader_module/__init__.py
  tests/lazy_loader_module/lazy_test_submodule.py
  tests/lazy_loader_test.py
  tests/linalg_test.py
Labels: pull ready

#12780 Make the etils[epath] dependency of JAX optional.
  jax/_src/dispatch.py
  jax/_src/path.py
  jax/experimental/compilation_cache/gfile_cache.py
  setup.py
Labels: pull ready

#12777 [typing] annotate jax.scipy.stats distributions
  jax/_src/scipy/stats/bernoulli.py
  jax/_src/scipy/stats/beta.py
  jax/_src/scipy/stats/betabinom.py
  jax/_src/scipy/stats/cauchy.py
  jax/_src/scipy/stats/chi2.py
  jax/_src/scipy/stats/dirichlet.py
  jax/_src/scipy/stats/expon.py
  jax/_src/scipy/stats/gamma.py
  jax/_src/scipy/stats/gennorm.py
  jax/_src/scipy/stats/geom.py
  jax/_src/scipy/stats/laplace.py
  jax/_src/scipy/stats/logistic.py
  jax/_src/scipy/stats/multinomial.py
  jax/_src/scipy/stats/multivariate_normal.py
  jax/_src/scipy/stats/nbinom.py
  jax/_src/scipy/stats/norm.py
  jax/_src/scipy/stats/pareto.py
  jax/_src/scipy/stats/poisson.py
  jax/_src/scipy/stats/t.py
  jax/_src/scipy/stats/uniform.py
Labels: pull ready

#12757 doc: note in jax.scipy.special.erf that complex inputs are not supported
  jax/_src/scipy/special.py
Labels: pull ready

#12794 Fix future numpy warning
  tests/random_test.py
Labels: pull ready

#12754 [typing] annotate jax.scipy.signal & jax.scipy.special
  jax/_src/ops/special.py
  jax/_src/scipy/signal.py
  jax/_src/scipy/special.py
  jax/_src/third_party/scipy/signal_helper.py
Labels: pull ready

#12793 expose `block_until_ready()` from jax module
  jax/__init__.py
Labels: pull ready

#12797 Ignore UserWarning as a WAR ...
  pytest.ini
Labels: pull ready

#12806 Drop absl-py as a jaxlib dependency.
  jaxlib/setup.py
Labels: pull ready

#12808 Add Python 3.11 as a compatible Python version.
  jaxlib/setup.py
  setup.py
Labels: kokoro:force-run, pull ready

#12815 Include column information in Python locations under Python 3.11.
  jax/_src/source_info_util.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/interpreters/mlir.py
  jax/interpreters/xla.py
Labels: pull ready

#12813 [typing] clarify jax._src.typing
  jax/_src/typing.py
Labels: pull ready

#12838 Fix typo.
  jax/experimental/host_callback.py
Labels: pull ready

#12810 Checkify: Only create one init_payload.
  jax/_src/checkify.py
Labels: pull ready

#12839 CI: update mypy version in pre-commit config
  .pre-commit-config.yaml
  jax/interpreters/mlir.py
Labels: pull ready

#12781 [typing] annotate jax._src.dtypes
  jax/_src/api_util.py
  jax/_src/dtypes.py
  jax/_src/lax/slicing.py
  jax/_src/lax/utils.py
  jax/_src/typing.py
  jax/core.py
Labels: pull ready

#12837 add allow_opaque_dtype to dtypes.canonicalize_dtype utility
  jax/_src/api_util.py
  jax/_src/dtypes.py
  jax/_src/lax/slicing.py
  jax/_src/lax/utils.py
  jax/_src/typing.py
  jax/core.py
Labels: pull ready

#12844 Skip unittest for stream_executor runtime
  tests/debugger_test.py
  tests/debugging_primitives_test.py
  tests/jaxpr_effects_test.py
  tests/python_callback_test.py
Labels: pull ready

#12851 [typing] annotate util.unzip2 & util.unzip3
  jax/_src/api.py
  jax/_src/dispatch.py
  jax/_src/lax/control_flow/common.py
  jax/_src/util.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/sparse/bcoo.py
  jax/interpreters/partial_eval.py
  jax/interpreters/pxla.py
Labels: pull ready

#12843 Disallow checkify-of-vmap-of-while.
  jax/_src/checkify.py
  tests/checkify_test.py
Labels: pull ready

#12683 Add JAX equivalent of scipy.stats.mode
  jax/_src/scipy/stats/_core.py
  jax/scipy/stats/__init__.py
  tests/scipy_stats_test.py
Labels: pull ready

#12853 [typing] annotate jax._src.numpy.index_tricks
  jax/_src/numpy/index_tricks.py
Labels: pull ready

#12854 [typing] annotate jax.numpy array creation routines
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#12820 initial commit of DevicesSharding (fka SimpleSharding)
  jax/_src/sharding.py
  jax/sharding.py
  tests/array_test.py
Labels: pull ready

#12863 [typing] annotate util.safe_zip
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/lax/slicing.py
  jax/_src/scipy/ndimage.py
  jax/_src/state/discharge.py
  jax/_src/tree_util.py
  jax/_src/util.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/pjit.py
  jax/interpreters/partial_eval.py
  jax/interpreters/pxla.py
Labels: pull ready

#12871 [ROCm] Fix ROCm dockerfile to remove 2020-resolver opt in.
  build/rocm/build_rocm.sh
Labels: pull ready

#12798 Add new config `jax_persistent_cache_min_instruction_count`.
  CHANGELOG.md
  jax/_src/config.py
  jax/_src/dispatch.py
  tests/compilation_cache_test.py
Labels: pull ready

#12894 [typing] annotate jax.numpy ufuncs
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/ufuncs.py
  jax/_src/scipy/ndimage.py
  jax/_src/scipy/special.py
Labels: pull ready

#12900 Test: skip JaxToNumy DLPack test on numpy 1.22
  tests/array_interoperability_test.py
Labels: pull ready

#12872 [typing] annotate jax._src.util.safe_map
  jax/_src/debugging.py
  jax/_src/dispatch.py
  jax/_src/sharding.py
  jax/_src/state/primitives.py
  jax/_src/util.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/sparse/transform.py
  jax/interpreters/mlir.py
  jax/interpreters/partial_eval.py
Labels: pull ready

#12896 Cleanup: remove unused imports in private modules
  jax/_src/ad_checkpoint.py
  jax/_src/custom_derivatives.py
  jax/_src/debugger/colab_debugger.py
  jax/_src/debugging.py
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/control_flow/solves.py
  jax/_src/lax/convolution.py
  jax/_src/lax/eigh.py
  jax/_src/lax/fft.py
  jax/_src/lax/parallel.py
  jax/_src/lax/slicing.py
  jax/_src/lax/windowed_reductions.py
  jax/_src/scipy/signal.py
  jax/_src/scipy/stats/betabinom.py
  jax/_src/sharding.py
  jax/_src/state/discharge.py
  jax/_src/state/types.py
  jax/_src/test_util.py
  jax/_src/tree_util.py
  jax/collect_profile.py
  jax/config.py
  jax/interpreters/mlir.py
  jax/interpreters/pxla.py
  jax/linear_util.py
  setup.cfg
Labels: pull ready, cleanup

#12800 improve (and shorten!) pmap errors about inconsistent axis sizes
  jax/_src/api.py
  jax/_src/tree_util.py
  tests/api_test.py
Labels: pull ready

#12912 update docs to point to jax.nn.standardize
  docs/jax.nn.rst
Labels: kokoro:force-run, pull ready

#12876 [dynamic-shapes] fix nested vmap callable annotation logic
  jax/interpreters/ad.py
  jax/interpreters/batching.py
  tests/dynamic_api_test.py
Labels: pull ready

#12904 canonicalize dtypes when loading arrays via `dlpack`
  jax/_src/dlpack.py
  tests/array_interoperability_test.py
Labels: pull ready

#12920 Fix an NameError caused by #12754
  jax/_src/third_party/scipy/signal_helper.py
Labels: pull ready

#12899 Remove unused code from jax/_src/lax/linalg.py
  jax/_src/lax/linalg.py
Labels: pull ready

#12923 Add regression test for #12920
  jax/_src/third_party/scipy/signal_helper.py
  tests/scipy_signal_test.py
Labels: kokoro:force-run, pull ready

#12925 [typing] fix incorrect type annotation on lax.argmax/argmin
  jax/_src/lax/lax.py
Labels: pull ready

#12921 [typing] add type annotations to the first several lax_numpy functions
  jax/_src/numpy/lax_numpy.py
  jax/_src/state/primitives.py
  jax/experimental/jax2tf/tests/flax_models/bilstm_classifier.py
Labels: pull ready

#12646 Implement jax.scipy.stats.truncnorm
  docs/jax.scipy.rst
  jax/_src/scipy/stats/truncnorm.py
  jax/scipy/stats/__init__.py
  jax/scipy/stats/truncnorm.py
  tests/scipy_stats_test.py
Labels: pull ready

#12950 CI: avoid raising error when wrapped function is None
  jax/_src/numpy/util.py
Labels: pull ready

#12953 Fix typo in 9419-jax-versioning.md
  docs/jep/9419-jax-versioning.md
Labels: pull ready

#12951 [typing] annotate next batch of lax_numpy
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#12957 jnp.linalg.lstsq: handle zero-size inputs
  jax/_src/numpy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#12965 [jax2tf] Fixes uses of tf.Variable in README.md
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: pull ready

#12958 jnp.gradient: call check_arraylike on inputs & clean-up implementation
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#12976 Fix jax releases URL in setup.py comments
  setup.py
Labels: pull ready

#12960 [typing] annotate next part of lax_numpy.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
  jax/_src/scipy/optimize/_lbfgs.py
  tests/lax_numpy_test.py
Labels: pull ready

#12973 tweaks to DevicesSharding / ReshapeableDevicesSharding
  jax/_src/sharding.py
  jax/sharding.py
  tests/array_test.py
Labels: pull ready

#12975 [typing] annotate next chunk of lax_numpy.py
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#12977 Skip two unit tests about custom sharding on libtpu
  jax/_src/test_util.py
  tests/debugging_primitives_test.py
  tests/pjit_test.py
Labels: pull ready

#12981 autodiff pjit partial eval with Array
  jax/experimental/pjit.py
  jax/interpreters/pxla.py
Labels: pull ready

#12990 Remove a TODO from the xmap tutorial
  docs/notebooks/xmap_tutorial.ipynb
  docs/notebooks/xmap_tutorial.md
Labels: pull ready

#12994 Clarify in JAX Basics that JAX array creation is also an operation th…
  docs/jax-101/01-jax-basics.ipynb
  docs/jax-101/01-jax-basics.md
Labels: pull ready

#12991 FAQ: fix JIT numerics discussion
  docs/faq.rst
Labels: kokoro:force-run, pull ready

#12996 [dynamic-shapes] tweak jnp.canonicalize_shape logic
  jax/_src/numpy/lax_numpy.py
  tests/dynamic_api_test.py
Labels: kokoro:force-run, pull ready

#9079 Annotate tree_util
  jax/_src/ad_checkpoint.py
  jax/_src/api_util.py
  jax/_src/lax/lax.py
  jax/_src/lax/windowed_reductions.py
  jax/_src/tree_util.py
Labels: pull ready

#12998 [typing] annotate jax.numpy reduction operations
  jax/_src/numpy/reductions.py
  jax/_src/ops/scatter.py
  jax/_src/scipy/special.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#12979 [typing] annotate jnp.pad
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#13013 [ROCm] Added gfx90a and gfx1030.
  .bazelrc
Labels: pull ready

#12989 Improve undefined axis checks
  jax/experimental/maps.py
  tests/xmap_test.py
Labels: pull ready

#13023 jax.numpy: implement window functions in terms of lax ops
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#13012 efficiently partitionable threefry PRNG 32-bit random bits implementation
  jax/_src/config.py
  jax/_src/prng.py
  tests/array_test.py
Labels: pull ready

#13010 [typing] annotate next section of lax_numpy.py
  jax/_src/numpy/index_tricks.py
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#13037 fix ci failure by skipping tests on gpu
  tests/array_test.py
Labels: pull ready

#11077 Add max step size argument to odeint
  jax/experimental/ode.py
  tests/ode_test.py
Labels: pull ready

#13022 leak checker: explain why a tracer is alive by printing a reference chain
  jax/core.py
  jax/interpreters/batching.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: pull ready

#13040 move to count-space-exhaustive partitionable Threefry RNG `random_bits`
  jax/_src/config.py
  jax/_src/prng.py
  jax/experimental/jax2tf/jax2tf.py
  tests/random_test.py
Labels: pull ready

#12670 Call _check_arraylike for jnp.linalg & jnp.fft functions
  CHANGELOG.md
  jax/_src/numpy/fft.py
  jax/_src/numpy/linalg.py
  jax/_src/third_party/numpy/linalg.py
Labels: pull ready

#13035 Point to ndarray.at from docstring of unimplemented jnp.put
  docs/jax.numpy.rst
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
  jax/numpy/__init__.py
Labels: documentation, better_errors, pull ready
