Repository jax-ml/jax, pull requests merged in 2022-08, with the labels that each got.

#11675 fix ad_checkpoint.checkpoint caching issue
  jax/_src/ad_checkpoint.py
  jax/_src/api.py
  jax/_src/config.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/loops.py
  jax/experimental/host_callback.py
  jax/interpreters/ad.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
  tests/host_callback_test.py
Labels: pull ready

#11696 MAINT: unpin autodoc-typehints
  docs/requirements.txt
Labels: pull ready

#11640 Allow jax.pmap(f).lower() to take jax.core.ShapedArray.
  jax/_src/api.py
  tests/pmap_test.py
Labels: pull ready

#11702 [sparse] remove deprecated _dedupe() method
  jax/experimental/sparse/bcoo.py
Labels: pull ready

#11673 Add `dtype` argument to `jnp.concatenate`
  jax/_src/numpy/lax_numpy.py
  jax/_src/prng.py
  tests/lax_numpy_test.py
Labels: pull ready

#11708 Fix debugger scope issue
  jax/_src/debugger/cli_debugger.py
  tests/debugger_test.py
Labels: pull ready

#11700 Remove deprecated `jax.experimental.stax`
  CHANGELOG.md
  jax/BUILD
  jax/experimental/stax.py
Labels: pull ready

#11715 Update CHANGELOG.md to include `jax.debug`
  CHANGELOG.md
Labels: pull ready

#9596 Annotate nn.initializers
  jax/_src/nn/initializers.py
  jax/nn/initializers.py
Labels: pull ready

#11725 Throw error earlier for misformatted string in jax.debug.print
  jax/_src/debugging.py
  tests/debugging_primitives_test.py
Labels: pull ready

#11734 in sharp bits notebook, add back iaml blog post link
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
Labels: kokoro:force-run, pull ready

#11720 Add enhanced bug report template
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: pull ready

#11739 bug-report.yaml: fix yaml syntax error
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: pull ready

#11740 bug-report.yml: fix markdown formatting
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: pull ready

#11717 Making sharding an arg to MHLO callback lowering
  jax/_src/debugging.py
  jax/experimental/host_callback.py
  jax/interpreters/mlir.py
Labels: pull ready

#11743 prepare to switch to new remat
  benchmarks/api_benchmark.py
  jax/_src/ad_checkpoint.py
  jax/_src/api.py
  jax/_src/errors.py
  jax/_src/test_util.py
  tests/api_test.py
Labels: pull ready

#11758 small tweaks for bint ad
  jax/_src/lax/lax.py
  jax/core.py
  jax/interpreters/partial_eval.py
  tests/dynamic_api_test.py
Labels: pull ready

#11761 add trivial convert_element_type padding rule
  jax/_src/lax/lax.py
Labels: pull ready

#11765 Remove experimental warning from xmap
  jax/experimental/maps.py
Labels: pull ready

#11764 Update the TF commit hash
  WORKSPACE
Labels: pull ready

#11767 DOC: fix docstring formatting error
  jax/_src/ad_checkpoint.py
Labels: kokoro:force-run, pull ready

#11770 Error in debug print if unused arguments are provided
  jax/_src/debugging.py
  tests/debugging_primitives_test.py
Labels: pull ready

#11768 prototype unfettered element types in jaxpr arrays
  jax/_src/api.py
  jax/_src/api_util.py
  jax/_src/dispatch.py
  jax/_src/dtypes.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/core.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  jax/interpreters/mlir.py
  tests/lax_test.py
Labels: pull ready

#11773 handle test failure in diffrax under new remat
  jax/_src/lax/control_flow/loops.py
Labels: pull ready

#11775 add api_boundary, fix flax failure with new-remat-by-default
  jax/_src/ad_checkpoint.py
Labels: pull ready

#11762 Fix jax numpy norm bug where passing `ord="inf"` always returns one
  jax/_src/numpy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#11672 Add configuration options jax_cuda_visible_devices and jax_rocm_visib…
  jax/_src/lib/xla_bridge.py
Labels: pull ready

#11792 Pin a minimum version of sphinx-book-theme to avoid bad pip dependency
  docs/requirements.txt
Labels: kokoro:force-run, pull ready

#11748 Annotate nn.initializers
  jax/_src/nn/initializers.py
  jax/nn/initializers.py
Labels: pull ready

#11793 Fix sample code block formatting in the FAQ
  docs/faq.rst
Labels: pull ready

#11796 Bump EnricoMi/publish-unit-test-result-action from 1 to 2
  .github/workflows/nightly-ci-multiprocess-gpu.yml
Labels: pull ready

#11797 jnp.linalg.matrix_rank: support stacks of matrices
  jax/_src/numpy/linalg.py
  tests/linalg_test.py
Labels: kokoro:force-run, pull ready

#11779 Increase minimum NumPy version to 1.20.
  CHANGELOG.md
  build/build.py
  jaxlib/setup.py
  setup.py
  tests/fft_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#11799 Create JAX Enhancement Proposals (JEPs).
  docs/conf.py
  docs/design_notes/index.rst
  docs/index.rst
  docs/jep/10657-sequencing-effects.md
  docs/jep/2026-custom-derivatives.md
  docs/jep/263-prng.md
  docs/jep/4410-omnistaging.md
  docs/jep/9407-type-promotion.ipynb
  docs/jep/9407-type-promotion.md
  docs/jep/9419-jax-versioning.md
  docs/jep/index.rst
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
  docs/type_promotion.rst
  jax/random.py
Labels: pull ready

#11806 Various debugger improvements
  jax/_src/debugger/core.py
  tests/debugger_test.py
Labels: pull ready

#11803 Document multiprocess GPU support.
  README.md
  docs/jax.distributed.rst
  docs/multi_process.md
  jax/_src/distributed.py
Labels: pull ready

#11712 Remove deprecated jax.experimental.optimizers
  CHANGELOG.md
  jax/BUILD
  jax/experimental/optimizers.py
Labels: pull ready

#11811 fix diffrax with new remat, do for cond what #11773 did for while_loop
  jax/_src/lax/control_flow/conditionals.py
Labels: kokoro:force-run, pull ready

#11812 fix traceback exclusion on new checkpoint
  jax/_src/ad_checkpoint.py
Labels: pull ready

#11808 Try flattening the locals/globals dict in the debugger and have a fallback if it fails
  jax/_src/debugger/core.py
  tests/debugger_test.py
Labels: pull ready

#11807 Add `spmd_axis_name` to vmap to allow constraining mapped PartitionSpecs.
  jax/_src/api.py
  jax/_src/custom_batching.py
  jax/_src/custom_derivatives.py
  jax/experimental/pjit.py
  jax/interpreters/batching.py
  tests/pjit_test.py
Labels: pull ready

#11824 defer to custom eltype for `slice` lowering rule
  jax/_src/lax/slicing.py
  tests/lax_test.py
Labels: pull ready

#11825 fix type annotation on remat
  jax/_src/api.py
Labels: pull ready

#11818 nightly multiprocess test: create issue on failure
  .github/workflows/cat_slurm_logs.py
  .github/workflows/nightly-ci-multiprocess-gpu.yml
Labels: pull ready

#11830 set new jax.remat / jax.checkpoint to be on-by-default
  CHANGELOG.md
  docs/jep/11830-new-remat-checkpoint.md
  docs/jep/index.rst
  jax/_src/config.py
Labels: pull ready, JEP

#11780 [ROCm] Update Dockerfile.rocm.
  build/rocm/Dockerfile.rocm
Labels: pull ready

#11832 Fix Python 3.11 compatibility problems.
  jax/_src/checkify.py
  jax/_src/traceback_util.py
Labels: pull ready

#11838 convert custom VJP update guide to a retroactive JEP
  docs/index.rst
  docs/jep/4008-custom-vjp-update.md
  docs/jep/index.rst
Labels: pull ready

#11833 Tests: re-enable some ufunc input tests
  tests/lax_numpy_test.py
Labels: pull ready

#11836 update `checkpoint` attributes according to `functools.wraps`
  jax/_src/api.py
Labels: kokoro:force-run, pull ready

#11846 Fix bug with integer-typed Gelu
  jax/_src/nn/functions.py
  tests/nn_test.py
Labels: pull ready

#11850 Fix bitrot in IREE Python client.
  jax/_src/iree.py
Labels: pull ready

#11852 Make vmap axis actually unconstrained by default.
  jax/experimental/pjit.py
  tests/pjit_test.py
Labels: pull ready

#11856 issue template: avoid checkboxes because they're interpreted as tasks
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: pull ready

#11862 Bump libtpu nightly version
  setup.py
Labels: pull ready

#11858 Tests: remove obsolete dtype_promotion decorators
  tests/dtypes_test.py
  tests/lax_numpy_test.py
  tests/lax_scipy_test.py
Labels: pull ready

#11877 Increase Bazel sharding of long-running CPU tests.
  tests/BUILD
Labels: pull ready

#11878 Increase Bazel sharding of scipy_signal_test on CPU.
  tests/BUILD
Labels: pull ready

#11876 Remove _ prefix from functions in jax._src.dtypes.
  jax/_src/dtypes.py
  jax/_src/nn/functions.py
  jax/_src/nn/initializers.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/polynomial.py
  jax/_src/numpy/reductions.py
  jax/_src/numpy/ufuncs.py
  jax/_src/numpy/util.py
  jax/_src/scipy/linalg.py
  jax/_src/scipy/signal.py
  tests/fft_test.py
  tests/lax_numpy_test.py
  tests/polynomial_test.py
  tests/random_test.py
  tests/scipy_signal_test.py
Labels: pull ready

#11863 Update version + changelog
  CHANGELOG.md
  jax/version.py
Labels: pull ready

#11857 jax.numpy: improve support for boolean inputs
  jax/_src/dtypes.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/ufuncs.py
  jax/_src/numpy/util.py
  tests/lax_numpy_test.py
Labels: pull ready

#11885 Fix typo in debugging docs
  docs/debugging/print_breakpoint.md
Labels: kokoro:force-run, pull ready

#11887 skip redundant `asarray` conversion in LAX numpy rewriting-take helper
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#11891 defer to custom eltype for `gather` lowering rule
  jax/_src/lax/slicing.py
  jax/interpreters/mlir.py
  tests/lax_test.py
Labels: pull ready

#11866 simplify slicing jaxprs a little
  benchmarks/api_benchmark.py
  jax/_src/lax/slicing.py
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#11890 Tests: require pillow>=9.1.0 & remove backward compatibility shims
  build/test-requirements.txt
  tests/image_test.py
Labels: pull ready

#11907 Import .bazelrc.user to allow users to override bazel options easily.
  .bazelrc
Labels: pull ready

#11899 Use --no-implicit-optional for type checking
  jax/_src/iree.py
  mypy.ini
Labels: kokoro:force-run, pull ready

#11921 un-skip polar decomp tests skipped on gpu in ad6ce74
  tests/lax_scipy_test.py
  tests/qdwh_test.py
Labels: kokoro:force-run, pull ready

#11888 Point to the conda-forge jaxlib wheels in the JAX readme.
  README.md
Labels: kokoro:force-run, pull ready

#11922 Bump XLA version.
  WORKSPACE
Labels: pull ready

#11854 Add eager pmap support
  jax/_src/api.py
  jax/_src/config.py
  jax/core.py
  jax/interpreters/pxla.py
  tests/pmap_test.py
Labels: kokoro:force-run, pull ready

#11925 pre-commit hook: update flake8, mypy, & jupytext versions
  .pre-commit-config.yaml
  docs/autodidax.md
  docs/autodidax.py
  docs/jax-101/01-jax-basics.md
  docs/jax-101/02-jitting.md
  docs/jax-101/03-vectorization.md
  docs/jax-101/04-advanced-autodiff.md
  docs/jax-101/05-random-numbers.md
  docs/jax-101/05.1-pytrees.md
  docs/jax-101/06-parallelism.md
  docs/jax-101/07-state.md
  docs/jax-101/08-pjit.md
  docs/jep/9407-type-promotion.md
  docs/notebooks/Common_Gotchas_in_JAX.md
  docs/notebooks/Custom_derivative_rules_for_Python_code.md
  docs/notebooks/How_JAX_primitives_work.md
  docs/notebooks/Neural_Network_and_Data_Loading.md
  docs/notebooks/Writing_custom_interpreters_in_Jax.md
  docs/notebooks/autodiff_cookbook.md
  docs/notebooks/convolutions.md
  docs/notebooks/neural_network_with_tfds_data.md
  docs/notebooks/quickstart.md
  docs/notebooks/thinking_in_jax.md
  docs/notebooks/vmapped_log_probs.md
  docs/notebooks/xmap_tutorial.md
  docs/transformations.md
Labels: kokoro:force-run, pull ready

#11927 Fix common typo: Tuple[X] -> Tuple[X, ...]
  docs/autodidax.ipynb
  docs/autodidax.md
  docs/autodidax.py
  jax/_src/api.py
  jax/_src/api_util.py
  jax/_src/dispatch.py
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/stages.py
  jax/_src/state/primitives.py
  jax/experimental/jax2tf/converters_eval/test_models/flax/seq2seq_lstm.py
  jax/experimental/jax2tf/impl_no_xla.py
  jax/interpreters/pxla.py
  tests/random_test.py
  tests/sparse_test.py
  tests/xmap_test.py
Labels: pull ready

#11936 build.py fixes.
  build/build.py
Labels: pull ready

#11883 Fix JIT cache context defaults
  jax/_src/config.py
  tests/api_test.py
Labels: pull ready

#11906 Add dtype arg to jnp.stack and friends
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#11934 Recommend using the cuda-nvcc package from the "nvidia" conda channel…
  README.md
Labels: pull ready

#11945 Bump test tolerance for eigenvalue test.
  tests/linalg_test.py
Labels: pull ready

#11950 delete old remat implementation
  CHANGELOG.md
  docs/jep/11830-new-remat-checkpoint.md
  jax/_src/ad_checkpoint.py
  jax/_src/api.py
  jax/_src/config.py
  jax/_src/lax/control_flow/__init__.py
  jax/_src/lax/control_flow/remat_impl.py
  jax/experimental/host_callback.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/interpreters/ad.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
  tests/host_callback_test.py
Labels: pull ready

#11931 Update WORKSPACE
  WORKSPACE
Labels: pull ready

#11962 Update XLA commit.
  WORKSPACE
Labels: pull ready

#11963 Include ABI tag in jaxlib wheels.
  jaxlib/setup.py
Labels: kokoro:force-run, pull ready

#11903 Add shape checks for lax.fft.
  jax/_src/lax/fft.py
  tests/fft_test.py
Labels: pull ready

#11966 test: fix testStack for numpy 1.24 or newer
  tests/lax_numpy_test.py
Labels: pull ready

#9137 simplify custom_jvp_call_p, remove custom_jvp_call_jaxpr_p
  jax/_src/custom_derivatives.py
  jax/core.py
  jax/custom_derivatives.py
  jax/experimental/callback.py
  jax/experimental/host_callback.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jet.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: pull ready

#11992 Array bug: make pytype_aval_mapping return a ConcreteShapedArray
  jax/experimental/array.py
Labels: kokoro:force-run, pull ready

#11995 Update XLA commit.
  WORKSPACE
Labels: pull ready

#11998 Be more selective about which MLIR pieces we build.
  build/build_wheel.py
  jaxlib/mlir/_mlir_libs/BUILD.bazel
  jaxlib/mlir/_mlir_libs/_site_initialize_0.cc
Labels: pull ready

#12000 fix custom_object_test for new Array type
  tests/custom_object_test.py
Labels: pull ready

#11996 jnp.remainder: match numpy's behavior for integer zero denominator
  jax/_src/numpy/ufuncs.py
  tests/lax_numpy_test.py
Labels: pull ready

#11991 clean up some dead code, from bad merge
  jax/_src/custom_derivatives.py
Labels: kokoro:force-run, pull ready

#11900 Add for loop transpose
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/state/primitives.py
  jax/interpreters/ad.py
  tests/lax_control_flow_test.py
Labels: pull ready

#11952 introduce key-element-type arrays and overhaul the Python PRNG key array
  jax/_src/api.py
  jax/_src/dispatch.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/lax.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/prng.py
  jax/_src/random.py
  jax/_src/test_util.py
  jax/core.py
  jax/experimental/jax2tf/g3doc/primitives_with_limited_support.md
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
  jax/interpreters/mlir.py
  jax/interpreters/pxla.py
  jax/random.py
  tests/api_test.py
  tests/batching_test.py
  tests/random_test.py
Labels: pull ready

#11867 generate lax.slice instead of lax.gather for x[<int>] or x[:<int>]
  benchmarks/api_benchmark.py
  jax/_src/numpy/lax_numpy.py
  jax/experimental/jet.py
Labels: pull ready

#12009 Disabled dlpack bfloat16 test for JAX<->cupy.
  tests/array_interoperability_test.py
Labels: pull ready

#12017 Avoid import-time dependency on jax.experimental
  jax/_src/dlpack.py
  jax/_src/numpy/ndarray.py
  jax/experimental/array.py
Labels: pull ready

#12019 Add copy_p to jax.lax namespace
  jax/lax/__init__.py
Labels: kokoro:force-run, pull ready

#12014 Add support to test gpu jaxlib nightly in CI instead of prebuilt jax/jaxlib
  .github/workflows/slurm_job_scripts/multinode_pytest.sub
  tests/distributed_multinode_test.py
Labels: pull ready

#12013 Make monoid_reducer implementation consistent with annotation
  jax/_src/lax/lax.py
Labels: pull ready

#12022 [sparse] add trivial sparse rule for lax.copy_p
  jax/experimental/sparse/transform.py
Labels: pull ready

#12036 Relax test tolerance to fix GPU CI failure.
  tests/lax_control_flow_test.py
Labels: pull ready

#12043 Add `upgrade=True` to jax_array flag so that its marked as transient …
  jax/_src/config.py
Labels: pull ready

#12021 Add padding rule for copy_p
  jax/_src/lax/lax.py
Labels: pull ready

#12046 remove 'BUG:' title prefix from bug report template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: pull ready

#12032 [ROCm] Enhance jaxlib hipsparse to reach parity with cusparse
  jaxlib/rocm/hipsparse.cc
  jaxlib/rocm/hipsparse_kernels.cc
  jaxlib/rocm/hipsparse_kernels.h
Labels: pull ready

#12054 lax.squeeze: ensure DeviceArray is returned
  jax/_src/lax/lax.py
  tests/lax_test.py
Labels: pull ready

#12035 [jax2tf] Adds note on Convolution deviations to no_xla_limitations.md
  jax/experimental/jax2tf/g3doc/no_xla_limitations.md
Labels: pull ready

#12041 Fix JVP rule for lax.pow()
  CHANGELOG.md
  jax/_src/lax/lax.py
  tests/lax_autodiff_test.py
Labels: pull ready

#11944 Remove deprecated array.tile() method
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#12069 in ad_checkpoint WrapHashably.__eq__, check _both_ are hashable
  jax/_src/ad_checkpoint.py
Labels: pull ready

#12070 fix bug issue template yaml parsing error
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: pull ready

#11946 Increase jax.distributed timeout to 5 min
  jax/_src/distributed.py
Labels: pull ready

#12087 test `jax.eval_shape` with key array inputs/outputs
  tests/random_test.py
Labels: kokoro:force-run, pull ready

#12090 Add callbacks to docs
  docs/jax.rst
Labels: pull ready

#12037 target_total_secs has type `int` but used as type `None`
  benchmarks/benchmark.py
Labels: pull ready

#12088 [sparse] add support for bcoo equivalent of lax.slice
  jax/experimental/sparse/__init__.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/transform.py
  tests/sparse_test.py
Labels: pull ready

#12081 Fix testUnaryWeakTypes
  tests/lax_test.py
Labels: pull ready

#12107 pmap_test: disable DeviceBufferToArray when jax_array=True
  tests/pmap_test.py
Labels: pull ready

#12091 generate lax.slice instead of lax.gather for more indexing cases
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#12113 Combine GPU multiprocess tests
  .github/workflows/slurm_job_scripts/multinode_pytest.sub
  tests/BUILD
  tests/distributed_multinode_test.py
  tests/multiprocess_gpu_test.py
Labels: pull ready

#12121 Update IREE backend name from "dylib" to "llvm-cpu".
  jax/_src/iree.py
Labels: pull ready

#12101 Add option to generate perfetto trace without generating link
  jax/_src/profiler.py
  jax/collect_profile.py
Labels: pull ready

#12125 Bump XLA version.
  WORKSPACE
Labels: pull ready

#12127 Add missing header to ducc build file.
  third_party/ducc/BUILD.bazel
Labels: pull ready

#12129 Enable one gpu per process for multinode GPU tests
  .github/workflows/slurm_job_scripts/multinode_pytest.sub
  tests/multiprocess_gpu_test.py
Labels: pull ready

#12112 Fix typo in debugging docs
  docs/debugging/print_breakpoint.md
Labels: pull ready

#11954 Add `for_loop` and state batching rules
  jax/_src/api.py
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/state/discharge.py
  jax/_src/state/primitives.py
  jax/_src/state/types.py
  jax/core.py
  tests/lax_control_flow_test.py
  tests/state_test.py
Labels: pull ready

#12151 Use cases_from_list to limit number of tests
  tests/state_test.py
Labels: pull ready

#11981 Add a correct jaxpr substitution for the cond primitive
  jax/_src/lax/control_flow/conditionals.py
Labels: pull ready

#12167 add `dtype` property to concrete key arrays
  jax/_src/dispatch.py
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/_src/prng.py
  jax/_src/random.py
  jax/core.py
  jax/experimental/array.py
  jax/experimental/global_device_array.py
  jax/experimental/jax2tf/jax2tf.py
  jax/interpreters/mlir.py
  jax/interpreters/pxla.py
  tests/lax_test.py
  tests/random_test.py
Labels: kokoro:force-run, pull ready

#12183 update version and changelog for pypi
  CHANGELOG.md
  jax/version.py
Labels: pull ready

#12177 test the RNG key upgrade in one of our github CI runs
  .github/workflows/ci-build.yaml
Labels: pull ready

#12184 support key array pickling
  jax/_src/prng.py
  tests/pickle_test.py
Labels: kokoro:force-run, pull ready

#12186 Throw error when 64-bit dtypes used incorrectly in pure_callback
  jax/_src/callback.py
  tests/python_callback_test.py
Labels: pull ready
