Repository jax-ml/jax, pull requests merged in 2022-05, with the labels that each got.

#10481 [sparse] implement sparse rule for lax.reshape_p
  jax/experimental/sparse/__init__.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/transform.py
  tests/sparse_test.py
  tests/sparsify_test.py
Labels: pull ready

#10524 CI: update jupytext to 0.13.8
  .pre-commit-config.yaml
  docs/autodidax.md
  docs/autodidax.py
  docs/design_notes/type_promotion.md
  docs/jax-101/01-jax-basics.md
  docs/jax-101/02-jitting.md
  docs/jax-101/03-vectorization.md
  docs/jax-101/04-advanced-autodiff.md
  docs/jax-101/05-random-numbers.md
  docs/jax-101/05.1-pytrees.md
  docs/jax-101/06-parallelism.md
  docs/jax-101/07-state.md
  docs/jax-101/08-pjit.md
  docs/notebooks/Common_Gotchas_in_JAX.md
  docs/notebooks/Custom_derivative_rules_for_Python_code.md
  docs/notebooks/How_JAX_primitives_work.md
  docs/notebooks/Neural_Network_and_Data_Loading.md
  docs/notebooks/Writing_custom_interpreters_in_Jax.md
  docs/notebooks/autodiff_cookbook.md
  docs/notebooks/convolutions.md
  docs/notebooks/neural_network_with_tfds_data.md
  docs/notebooks/quickstart.md
  docs/notebooks/thinking_in_jax.md
  docs/notebooks/vmapped_log_probs.md
  docs/notebooks/xmap_tutorial.md
  docs/transformations.md
Labels: pull ready

#10526 Don't include PTX for older GPU generations.
  .bazelrc
  build/build.py
Labels: pull ready

#10522 [remove-units] remove units from partial_eval.py
  jax/_src/api.py
  jax/experimental/maps.py
  jax/interpreters/partial_eval.py
Labels: pull ready

#10295 Add in runtime tokens for effectful jaxprs
  jax/_src/api.py
  jax/_src/dispatch.py
  jax/interpreters/mlir.py
  jax/interpreters/pxla.py
  jax/interpreters/sharded_jit.py
  tests/jaxpr_effects_test.py
Labels: pull ready

#10549 Attach callback keepalive to JIT executable
  jax/_src/api.py
  jax/_src/dispatch.py
  jax/interpreters/mlir.py
  jax/interpreters/pxla.py
  jax/interpreters/sharded_jit.py
  tests/jaxpr_effects_test.py
Labels: pull ready

#10553 Initial debug print implementation
  jax/_src/debugging.py
  tests/debugging_primitives_test.py
Labels: pull ready

#10557 Don't leak the keepalive in debug_callback lowering
  jax/_src/debugging.py
Labels: pull ready

#10564 add xla_client._version checks for mhlo.ConstOp signature
  jax/interpreters/mlir.py
  jaxlib/lapack.py
  jaxlib/pocketfft.py
Labels: pull ready

#10532 [remove-units] remove units
  jax/_src/ad_util.py
  jax/_src/custom_batching.py
  jax/_src/custom_derivatives.py
  jax/_src/dispatch.py
  jax/_src/lax/control_flow.py
  jax/core.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/maps.py
  jax/experimental/sparse/transform.py
  jax/interpreters/ad.py
  jax/interpreters/batching.py
  jax/interpreters/mlir.py
  jax/interpreters/partial_eval.py
  jax/interpreters/pxla.py
  jax/interpreters/sharded_jit.py
  jax/interpreters/xla.py
  jax/jaxpr_util.py
  tests/api_test.py
  tests/core_test.py
  tests/sparsify_test.py
Labels: pull ready

#10546 jnp.unravel_index: avoid overflow for large dimension sizes
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#10490 Add jax.scipy.linalg.funm
  docs/jax.scipy.rst
  jax/_src/third_party/scipy/linalg.py
  jax/scipy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#10548 If optimization_barrier is not available, disable the jax2tf tests.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: pull ready

#10568 [sparse] incremental improvement to docs
  docs/jax.experimental.sparse.rst
  jax/experimental/sparse/__init__.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/coo.py
  jax/experimental/sparse/csr.py
Labels: pull ready

#10579 DOC: remove mentions of units
  docs/notebooks/Writing_custom_interpreters_in_Jax.ipynb
  docs/notebooks/Writing_custom_interpreters_in_Jax.md
Labels: pull ready

#10569 Enable effect lowering for while/for/scan
  jax/_src/debugging.py
  jax/_src/lax/control_flow.py
  jax/core.py
  tests/debugging_primitives_test.py
  tests/jaxpr_effects_test.py
Labels: pull ready

#10581 Enable batching rule for `debug_print`
  jax/_src/debugging.py
  tests/debugging_primitives_test.py
Labels: pull ready

#10582 Enable AD rules for `debug_print`
  jax/_src/debugging.py
  tests/debugging_primitives_test.py
Labels: pull ready

#10590 jax.scipy.sparse.linalg: support sparse matrices as operators
  jax/_src/scipy/sparse/linalg.py
  tests/lax_scipy_sparse_test.py
Labels: pull ready

#10566 [sparse] add bcoo_update_layout utility
  jax/experimental/sparse/__init__.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/util.py
  tests/sparse_test.py
Labels: pull ready

#10593 fix ad_checkpoint.checkpoint vmap rule
  jax/_src/ad_checkpoint.py
  jax/interpreters/batching.py
  tests/api_test.py
Labels: pull ready

#10577 Enable ordered effects in the `cond` of a while loop
  jax/_src/lax/control_flow.py
  tests/debugging_primitives_test.py
  tests/jaxpr_effects_test.py
Labels: pull ready

#10578 Enable ordered effects in cond lowering
  jax/_src/lax/control_flow.py
  tests/debugging_primitives_test.py
  tests/jaxpr_effects_test.py
Labels: pull ready

#10594 api_util: make shaped_abstractify respect raise_to_shaped
  jax/_src/api_util.py
  tests/pjit_test.py
Labels: pull ready

#10536 add more scan dce rule tests, fix issues
  jax/_src/config.py
  jax/_src/lax/control_flow.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: pull ready

#10604 Update workspace for jaxlib release for testing
  WORKSPACE
Labels: pull ready

#10607 DOC: add FAQ entry on jit-compiling methods
  docs/faq.rst
Labels: documentation, pull ready

#10393 Improve performance of array integer indexing
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#10612 [ROCm] Fixes to enable JAX to build on ROCm.
  jaxlib/rocm/BUILD.bazel
  jaxlib/rocm/hip_gpu_kernel_helpers.cc
  jaxlib/rocm/hip_linalg.cc
  jaxlib/rocm/hip_lu_pivot_kernels.cc
  jaxlib/rocm/hip_lu_pivot_kernels.hip.cc
  jaxlib/rocm/hip_prng.cc
  jaxlib/rocm/hip_prng_kernels.cc
  jaxlib/rocm/hip_prng_kernels.hip.cc
  jaxlib/rocm/hipblas.cc
  jaxlib/rocm/hipblas_kernels.cc
  jaxlib/rocm/hipsolver.cc
  jaxlib/rocm/hipsolver_kernels.cc
  jaxlib/rocm/hipsparse.cc
  jaxlib/rocm/hipsparse_kernels.cc
Labels: pull ready

#9868 Fix _lax_max_taylor_rule for broadcastable inputs
  jax/experimental/jet.py
Labels: pull ready

#10628 [jax2tf] Update JAX limitations
  jax/experimental/jax2tf/g3doc/jax_primitives_coverage.md
  jax/experimental/jax2tf/g3doc/primitives_with_limited_support.md
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
  jax/experimental/jax2tf/tests/jax_primitives_coverage_test.py
  jax/experimental/jax2tf/tests/primitive_harness.py
Labels: pull ready

#10629 [ROCm] Fix unit test failures on ROCm.
  jaxlib/gpu_prng.py
Labels: pull ready

#10620 Officially support Python 3.10
  .github/workflows/ci-build.yaml
  jaxlib/setup.py
  setup.py
Labels: pull ready

#10573 remove count attribute and total_ordering from core.Var
  jax/_src/checkify.py
  jax/_src/lax/control_flow.py
  jax/core.py
  jax/experimental/host_callback.py
  jax/experimental/maps.py
  jax/interpreters/partial_eval.py
  tests/core_test.py
Labels: pull ready

#10626 cosmetic edits in docs
  docs/jax-101/08-pjit.md
Labels: pull ready

#10636 DOC: clarify jupytext instructions
  docs/developer.md
Labels: pull ready

#10640 DOC: update myst-nb to v0.15.0
  docs/autodidax.ipynb
  docs/autodidax.md
  docs/conf.py
  docs/developer.md
  docs/jax-101/01-jax-basics.ipynb
  docs/jax-101/01-jax-basics.md
  docs/jax-101/02-jitting.ipynb
  docs/jax-101/02-jitting.md
  docs/jax-101/03-vectorization.ipynb
  docs/jax-101/03-vectorization.md
  docs/jax-101/04-advanced-autodiff.ipynb
  docs/jax-101/04-advanced-autodiff.md
  docs/jax-101/05-random-numbers.ipynb
  docs/jax-101/05-random-numbers.md
  docs/jax-101/05.1-pytrees.ipynb
  docs/jax-101/05.1-pytrees.md
  docs/jax-101/06-parallelism.ipynb
  docs/jax-101/06-parallelism.md
  docs/jax-101/07-state.ipynb
  docs/jax-101/07-state.md
  docs/jax-101/08-pjit.md
  docs/notebooks/Custom_derivative_rules_for_Python_code.ipynb
  docs/notebooks/Custom_derivative_rules_for_Python_code.md
  docs/notebooks/xmap_tutorial.ipynb
  docs/notebooks/xmap_tutorial.md
  docs/requirements.txt
Labels: pull ready

#10649 Small fix in FAQ documentation
  docs/faq.rst
Labels: pull ready

#10658 [ROCm] Disabled one and enabled several unit tests for ROCm.
  tests/array_interoperability_test.py
  tests/lax_numpy_test.py
  tests/linalg_test.py
  tests/qdwh_test.py
  tests/random_test.py
  tests/scipy_signal_test.py
  tests/sparse_test.py
  tests/svd_test.py
Labels: kokoro:force-run, pull ready

#10668 Update custom interpreter tutorial
  docs/notebooks/Writing_custom_interpreters_in_Jax.ipynb
  docs/notebooks/Writing_custom_interpreters_in_Jax.md
Labels: pull ready

#10671 Fixed a typo in `cloud_tpu_init.py`
  jax/_src/cloud_tpu_init.py
Labels: pull ready

#10669 fix grad(..., argnums=-1), regressed in #10453
  jax/_src/api_util.py
  tests/api_test.py
Labels: pull ready

#10595 make core_test.py pass with core.call
  jax/interpreters/ad.py
  tests/core_test.py
Labels: pull ready

#10616 improve partial_eval_jaxpr_custom
  jax/_src/ad_checkpoint.py
  jax/experimental/maps.py
  jax/interpreters/partial_eval.py
  jax/interpreters/xla.py
  tests/api_test.py
Labels: pull ready

#10642 Avoid generating trivial gathers when reversing array
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#10664 Make CUDA install instructions copy-pasteablee
  README.md
Labels: pull ready

#10679 DOC: explicitly enable dollarmath extension
  docs/conf.py
Labels: pull ready

#10681 Fix mypy warning
  jax/experimental/jax2tf/shape_poly.py
Labels: pull ready

#10686 tweak mlir shape_tensor helper, fewer MHLO ops
  jax/interpreters/mlir.py
Labels: pull ready

#10680 Remove unnecessary __future__ imports
  jax/interpreters/pxla.py
  tests/sharded_jit_test.py
Labels: pull ready

#10711 add core.closed_call_p
  jax/core.py
  jax/experimental/jax2tf/jax2tf.py
  jax/interpreters/ad.py
  jax/interpreters/mlir.py
  jax/interpreters/partial_eval.py
  jax/interpreters/xla.py
  tests/core_test.py
Labels: pull ready

#10584 remove jnp.array case for handling buffers w/ aval=None
  jax/_src/numpy/lax_numpy.py
  tests/pmap_test.py
Labels: pull ready

#10688 Enable colors when we are using a terminal
  jax/_src/config.py
  jax/_src/pretty_printer.py
Labels: pull ready

#10718 Fix jax 0.3.11 GPU breakge when used with jaxlib 0.3.10.
  jax/_src/lib/__init__.py
Labels: pull ready

#10693 [sparse] add BCOO.update_layout() method
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: pull ready

#10700 DOC: add references for haskell-style signatures
  docs/autodidax.ipynb
  docs/autodidax.md
  docs/autodidax.py
  docs/jaxpr.rst
  docs/notebooks/Custom_derivative_rules_for_Python_code.ipynb
  docs/notebooks/Custom_derivative_rules_for_Python_code.md
  docs/notebooks/autodiff_cookbook.ipynb
  docs/notebooks/autodiff_cookbook.md
  jax/_src/custom_derivatives.py
  jax/_src/lax/control_flow.py
Labels: documentation, pull ready

#10723 Include mlir.transforms and mlir.passmanager in jaxlib BUILD.
  build/BUILD.bazel
  build/build_wheel.py
  jaxlib/mlir/BUILD.bazel
  jaxlib/mlir/_mlir_libs/BUILD.bazel
  jaxlib/setup.py
Labels: pull ready

#10730 Update version + CHANGELOG for jax 0.3.13 release
  CHANGELOG.md
  jax/version.py
Labels: pull ready

#10705 Improve pjit logging when `JAX_DISTRIBUTED_DEBUG=1` is enabled.
  jax/experimental/pjit.py
Labels: pull ready

#10647 [jax2tf] Document the handling of custom JAX pytrees
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: pull ready

#10731 Add input validation for the padding argument to lax.conv_general_dil…
  jax/_src/lax/convolution.py
  tests/lax_test.py
Labels: pull ready

#10653 [jax2tf] add rudimentary scatter support for enable_xla=False
  jax/experimental/jax2tf/g3doc/no_xla_limitations.md
  jax/experimental/jax2tf/impl_no_xla.py
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
  jax/experimental/jax2tf/tests/primitive_harness.py
Labels: pull ready

#10736 update workspace TF commit
  WORKSPACE
Labels: pull ready

#10739 [sparse] raise better error for subtraction between sparse and dense
  jax/experimental/sparse/transform.py
Labels: pull ready

#10752 Fix windows copy
  build/build_wheel.py
Labels: pull ready

#10756 quick fix for #10750, add checks and todo
  jax/_src/custom_derivatives.py
  jax/_src/numpy/ufuncs.py
  jax/core.py
  tests/api_test.py
Labels: pull ready

#10758 Add TODO for removing output tokens
  jax/_src/dispatch.py
Labels: pull ready

#10759 add support for lambda-bound dynamic shape output (iree only)
  jax/_src/dispatch.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
  tests/custom_object_test.py
Labels: pull ready

#10603 Additional input validation for transformations
  jax/_src/api.py
  jax/_src/api_util.py
  jax/_src/scipy/linalg.py
  jax/_src/test_util.py
  tests/api_test.py
  tests/debug_nans_test.py
  tests/jax_jit_test.py
  tests/x64_context_test.py
Labels: pull ready

#10768 Disable tests with positional args
  tests/api_test.py
Labels: pull ready

#10765 Make `Effect` a hashable type
  jax/core.py
Labels: pull ready

#10764 [ROCm] Fix hipblas kernels for ROCm.
  jaxlib/rocm/hipblas_kernels.cc
Labels: pull ready

#10659 DeviceArray: Improve support for copy, deepcopy, and pickle
  CHANGELOG.md
  docs/jax.numpy.rst
  jax/_src/device_array.py
  jax/_src/numpy/lax_numpy.py
  jax/core.py
  tests/lax_numpy_test.py
  tests/pickle_test.py
Labels: pull ready

#10786 DOC: fix scipy intersphinx link
  docs/conf.py
Labels: pull ready

#10785 DOC: fix docs generator to group notebook code output
  docs/conf.py
Labels: pull ready

#10770 incorrect link in dpsgd example
  examples/differentially_private_sgd.py
Labels: pull ready

#10799 ENH _wraps() in jax._src.numpy.util is now returns a generic function
  jax/_src/numpy/linalg.py
  jax/_src/numpy/reductions.py
  jax/_src/numpy/util.py
  jax/_src/scipy/special.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#10782 [sparse] add sparse.eye() array creation routine
  jax/experimental/sparse/__init__.py
  jax/experimental/sparse/api.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/coo.py
  jax/experimental/sparse/csr.py
  tests/sparse_test.py
Labels: pull ready

#10803 [sparse] test corner cases of sparse.eye
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/coo.py
  jax/experimental/sparse/csr.py
  tests/sparse_test.py
Labels: pull ready

#10814 [x64] use explicit casting rules for promote_dtypes_inexact
  jax/_src/dtypes.py
  jax/_src/numpy/util.py
  tests/lax_numpy_test.py
  tests/lax_scipy_test.py
Labels: pull ready

#10824 [x64] add jax_numpy_dtype_promotion flag
  jax/__init__.py
  jax/_src/config.py
  jax/_src/dtypes.py
  tests/dtypes_test.py
Labels: pull ready

#10829 [djax] add support for dynamic-shape outputs
  jax/_src/api.py
  jax/_src/dispatch.py
  jax/_src/iree.py
  jax/core.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: pull ready

#10841 jnp.nonzero: require array-like input
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#10842 BUG: fix internal _jax_type for weak bfloat16
  jax/_src/dtypes.py
  tests/dtypes_test.py
Labels: pull ready

#10845 [x64] dtypes_test: run tests with jax_numpy_type_promotion=strict
  jax/_src/dtypes.py
  tests/dtypes_test.py
Labels: pull ready

#10846 [x64] linspace/logspace/geomspace: avoid problematic type promotions
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#10853 adding/testing Google Chat notification workflows.
  .github/workflows/broken-main-notify.yml
  .github/workflows/pull-request-notify.yml
  .github/workflows/release-notification.yml
Labels: pull ready

#10823 Add notes in buffer donation FAQ about key-word args limitation.
  docs/faq.rst
  jax/_src/api.py
Labels: pull ready

#10854 [x64] handle strict promotion for jnp.var
  jax/_src/numpy/reductions.py
Labels: pull ready

#10859 Fixing the interpolation errors and yaml syntax errors.
  .github/workflows/broken-main-notify.yml
  .github/workflows/pull-request-notify.yml
  .github/workflows/release-notification.yml
Labels: pull ready

#10856 [x64] jax.numpy reductions: avoid binary promotion for upcast_bf16
  jax/_src/numpy/reductions.py
Labels: pull ready

#10857 fix incorrect f-string format in xmap
  jax/experimental/maps.py
Labels: pull ready

#10862 Notifications
  .github/workflows/broken-main-notify.yml
  .github/workflows/pull-request-notify.yml
  .github/workflows/release-notification.yml
Labels: pull ready

#10858 [x64] make jax.random compatible with jax_numpy_dtype_promotion=strict
  jax/_src/prng.py
  jax/_src/random.py
  tests/random_test.py
Labels: pull ready

#10861 [x64] make jnp.unravel_index safe under strict promotion
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#10886 Relax test tolerance for spectral divide and conquer eigh test.
  tests/lax_scipy_test.py
Labels: pull ready

#10885 Fix macOS builds by updating the minimum OSX version target
  .bazelrc
  build/build_wheel.py
Labels: pull ready

#10890 [x64] Add to_complex_dtype utility function
  jax/_src/dtypes.py
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#10893 [x64] jnp.packbits: avoid implicit promotion of boolean inputs
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#10894 Update changelog to incorporate some recent changes.
  CHANGELOG.md
Labels: pull ready

#10896 [x64] jnp.ldexp & frexp: avoid implicit promotion
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#10902 [x64] make jnp.poly* functions work under strict dtype promotion
  jax/_src/numpy/polynomial.py
Labels: pull ready

#10895 [x64] jnp.quantile: don't require arguments to be promotion compatible
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#10901 CI: pin traitlets to <5.2 in doc build
  docs/requirements.txt
Labels: pull ready

#10900 [x64] jnp.searchsorted: avoid returning 64-bit indices in the default case
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#10907 [x64] make jnp.histogram and related functions work with strict promotion
  jax/_src/numpy/lax_numpy.py
Labels: pull ready
