Repository jax-ml/jax, pull requests merged in 2022-09, with the labels that each got.

#12170 internal rename: swap mentions of "custom eltypes" for "opaque dtypes"
  jax/_src/api.py
  jax/_src/dispatch.py
  jax/_src/dtypes.py
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/_src/prng.py
  jax/core.py
  jax/experimental/array.py
  jax/experimental/global_device_array.py
  jax/experimental/jax2tf/jax2tf.py
  jax/interpreters/mlir.py
  jax/interpreters/pxla.py
  tests/lax_test.py
  tests/random_test.py
Labels: pull ready

#12200 require scalar key arrays when seeding, splitting, and folding
  jax/_src/random.py
Labels: pull ready

#12201 [sparse] add sparse support for dynamic_slice
  jax/experimental/sparse/__init__.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/transform.py
  tests/sparse_test.py
  tests/sparsify_test.py
Labels: pull ready

#12203 Use lowering as impl rule for `pure_callback`
  jax/_src/callback.py
  tests/python_callback_test.py
Labels: pull ready

#12204 document AOT lowering and compilation
  CHANGELOG.md
  docs/aot.md
  docs/index.rst
  docs/jax.rst
  docs/jax.stages.rst
  jax/_src/stages.py
  jax/stages.py
Labels: pull ready

#12196 [jax2tf] Improves TF.js quickdraw example
  jax/experimental/jax2tf/examples/tf_js/README.md
  jax/experimental/jax2tf/examples/tf_js/quickdraw/input_pipeline.py
  jax/experimental/jax2tf/examples/tf_js/quickdraw/quickdraw.py
Labels: pull ready

#12205 [jax2tf] Refactor top-level jax2tf.convert
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#12230 [jax2tf] Refactor top-level jax2tf.convert
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#12225 Show link to GitHub repo in navbar
  docs/conf.py
Labels: pull ready

#12232 Checkify: Remove some `err` <-not-> `pred` flipping.
  jax/_src/checkify.py
Labels: pull ready

#12172 Add markers to run multi node gpu tests separately
  .github/workflows/slurm_job_scripts/multinode_pytest.sub
  pytest.ini
  tests/multiprocess_gpu_test.py
Labels: pull ready

#12223 Allow get_aval to work on ShapeDtypeStruct
  jax/_src/api.py
  tests/dynamic_api_test.py
Labels: pull ready

#12215 Enable `remat(for_loop)`
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/state/primitives.py
  jax/interpreters/partial_eval.py
  tests/lax_control_flow_test.py
Labels: pull ready

#12251 [jax2tf] Refactor the experimental_native_lowering path in jax2tf
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: pull ready

#12217 Dce and execute trivial
  jax/_src/ad_checkpoint.py
  jax/_src/custom_derivatives.py
  jax/_src/dispatch.py
  jax/_src/lax/control_flow/common.py
  jax/_src/lax/lax.py
  jax/_src/prng.py
  jax/core.py
  jax/experimental/array.py
  jax/interpreters/partial_eval.py
  jax/interpreters/pxla.py
  tests/api_test.py
  tests/array_test.py
  tests/debug_nans_test.py
  tests/multi_device_test.py
Labels: pull ready

#12268 Add missing Google-internal option to jax_test
  jaxlib/jax.bzl
Labels: pull ready

#12269 Ignore the mypy errors.
  jax/interpreters/pxla.py
Labels: pull ready

#12239 Split State effect into Read/Write/Accum effects and tie them to Refs
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/state/__init__.py
  jax/_src/state/primitives.py
  jax/_src/state/types.py
  tests/BUILD
  tests/state_test.py
Labels: pull ready

#12241 Add sound loop invariance detection for `for`
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/state/__init__.py
  jax/_src/state/types.py
  tests/lax_control_flow_test.py
Labels: pull ready

#12261 Drop support for non-MLIR modules in compile().
  jax/_src/dispatch.py
Labels: pull ready

#12296 Bump the minimum jaxlib version to 0.3.15.
  jax/_src/api.py
  jax/_src/distributed.py
  jax/_src/lax/convolution.py
  jax/_src/lax/lax.py
  jax/_src/lax/linalg.py
  jax/_src/lib/mlir/dialects/__init__.py
  jax/_src/lib/xla_bridge.py
  jax/_src/tree_util.py
  jax/version.py
  tests/clear_backends_test.py
Labels: pull ready

#12297 add _device attribute to PRNGKeyArray so that computation follows key placement
  jax/_src/numpy/ndarray.py
  jax/_src/prng.py
  tests/multi_device_test.py
Labels: pull ready

#12301 [dynamic-shapes] add basic vmap-of-indexing support
  jax/_src/iree.py
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/_src/numpy/lax_numpy.py
  jax/core.py
  tests/dynamic_api_test.py
Labels: pull ready

#12270 [jax2tf] Updates to the documentation
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/g3doc/convert_models_results.md
Labels: pull ready

#12308 lax.broadcast_shapes: clearer error for incompatible shapes
  jax/_src/lax/lax.py
Labels: kokoro:force-run, pull ready

#12311 jax.Array: support fast path for lax.transpose & lax.squeeze
  jax/_src/lax/lax.py
Labels: pull ready

#12332 jax.lax: ensure GatherDimensionNumbers contains tuples for hashability
  jax/_src/lax/slicing.py
  tests/lax_test.py
Labels: kokoro:force-run, pull ready

#12213 Add `jax.print_environment_info()` utility
  docs/jax.rst
  jax/__init__.py
  jax/_src/environment_info.py
  jax/_src/test_util.py
  tests/api_test.py
  tests/debugging_primitives_test.py
  tests/python_callback_test.py
Labels: pull ready

#12334 ensure_index: raise better error for traced inputs
  jax/_src/api_util.py
Labels: pull ready

#12300 jax._src.typing: add basic types and use them in lax.py
  jax/_src/lax/lax.py
  jax/_src/typing.py
  jax/core.py
  jax/experimental/jax2tf/shape_poly.py
Labels: pull ready

#11859 JEP: Type Annotations
  docs/_static/vscode-completion.png
  docs/jep/12049-type-annotations.md
  docs/jep/index.rst
Labels: pull ready, JEP

#12149 Add ability to close over `Ref`s in nested `for_loop`s
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/state/__init__.py
  jax/_src/state/discharge.py
  jax/_src/state/types.py
  tests/for_loop_test.py
  tests/lax_control_flow_test.py
Labels: pull ready

#12346 jax_array_test: set config once & fix X64 failure
  tests/array_test.py
Labels: kokoro:force-run, pull ready

#12342 Add typing_test.py
  .pre-commit-config.yaml
  jax/_src/typing.py
  tests/BUILD
  tests/typing_test.py
Labels: pull ready

#12368 add paper link about grad-relu-at-zero
  jax/_src/nn/functions.py
Labels: pull ready

#12372 jax.Array: add issubclass test corresponding to existing DeviceArray test
  tests/array_test.py
Labels: kokoro:force-run, pull ready

#12371 [typing] clear up logic in scatter_update
  jax/_src/ops/scatter.py
Labels: kokoro:force-run, pull ready

#12361 Implement unrolling for for_loop
  jax/_src/lax/control_flow/for_loop.py
  tests/for_loop_test.py
Labels: pull ready

#12369 [typing] Change case of typing.Dtype -> typing.DType
  docs/jep/12049-type-annotations.md
  jax/_src/lax/lax.py
  jax/_src/typing.py
  tests/typing_test.py
Labels: pull ready

#12143 JAX implementation of scipy.stats.multinomial pmf & logpmf
  jax/_src/scipy/stats/multinomial.py
  jax/scipy/stats/__init__.py
  jax/scipy/stats/multinomial.py
  tests/scipy_stats_test.py
Labels: pull ready

#12383 tests: fix is_valid_shape() function
  jax/_src/test_util.py
Labels: kokoro:force-run, pull ready

#12414 Bump XLA version.
  WORKSPACE
Labels: pull ready

#12419 multiprocess_gpu_test: kill open subprocesses to avoid warning
  tests/multiprocess_gpu_test.py
Labels: pull ready

#12422 docs: avoid deprecated matplotlib axis creation
  docs/notebooks/convolutions.ipynb
  docs/notebooks/convolutions.md
Labels: kokoro:force-run, pull ready

#12386 Add function to visualize `Sharding`s
  build/test-requirements.txt
  jax/_src/debugging.py
  jax/debug.py
  tests/debugging_primitives_test.py
Labels: pull ready

#12424 Limit console width for visualize_sharding
  jax/_src/debugging.py
  tests/debugging_primitives_test.py
Labels: pull ready

#12425 Add support for visualizing `PmapSharding`
  jax/_src/debugging.py
  tests/debugging_primitives_test.py
Labels: pull ready

#12428 [typing] Tracer: add missing __round__ and __reversed__ methods
  jax/core.py
  tests/lax_numpy_test.py
Labels: kokoro:force-run, pull ready

#12418 Update JEP-12049 implementation discussion
  docs/jep/12049-type-annotations.md
Labels: pull ready

#12389 Checkify: support batched while.
  jax/_src/checkify.py
  tests/checkify_test.py
Labels: pull ready

#12443 Fix mlir capi dll is missing chlo and stablehlo symbols
  .bazelrc
  jaxlib/jax.bzl
  jaxlib/mlir/_mlir_libs/BUILD.bazel
Labels: pull ready

#12451 [typing] add class-level declarations of Array members.
  jax/experimental/array.py
Labels: pull ready

#12370 [typing] overloaded type declaration for variadic lax.sort
  jax/_src/lax/lax.py
Labels: pull ready

#12152 Add slurm multi-process auto bootstrapping interface
  docs/multi_process.md
  jax/_src/clusters/__init__.py
  jax/_src/clusters/cloud_tpu_cluster.py
  jax/_src/clusters/cluster.py
  jax/_src/clusters/slurm_cluster.py
  jax/_src/distributed.py
  tests/multiprocess_gpu_test.py
Labels: pull ready

#12472 Fix example in `pjit` docstring
  jax/experimental/pjit.py
Labels: pull ready

#12476 [array] full_like: only match sharding if shape==None
  jax/_src/lax/lax.py
Labels: pull ready

#12484 Improve documentation for unique_indices.
  jax/_src/lax/slicing.py
Labels: pull ready

#11961 Use the pjrt plugin device client.
  .bazelrc
  build/build.py
  jax/_src/lib/xla_bridge.py
Labels: pull ready

#12471 [ROCM] Update Dockerfile.rocm to Ubuntu20
  build/rocm/Dockerfile.rocm
Labels: pull ready

#12481 Allow transpose axes to be negative to match (undocumented) NumPy behavior
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#12478 Update debugging docs to have sharding visualization
  docs/jax.debug.rst
  jax/_src/debugging.py
Labels: pull ready

#12490 fix leak checker internal error
  jax/interpreters/partial_eval.py
  tests/api_test.py
  tests/nn_test.py
Labels: pull ready

#12486 Fix xla extension version test in debugging.py
  jax/_src/debugging.py
Labels: pull ready

#12437 Add multi host pjit tests
  tests/multiprocess_gpu_test.py
Labels: pull ready

#12407 Removed repeated `nan_to_num` function name in docs
  docs/jax.numpy.rst
Labels: pull ready

#12510 Wrap multiprocess test popen() uses in a context manager.
  tests/multiprocess_gpu_test.py
Labels: pull ready

#12511 Jax and jaxlib 0.3.18 release candidate.
  CHANGELOG.md
  WORKSPACE
  setup.py
Labels: pull ready

#12421 Add initial implementation of jax.Array base class
  .pre-commit-config.yaml
  CHANGELOG.md
  jax/__init__.py
  jax/_src/api.py
  jax/_src/basearray.py
  jax/_src/basearray.pyi
  jax/_src/checkify.py
  jax/_src/device_array.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/ndarray.py
  jax/_src/random.py
  jax/_src/typing.py
  jax/core.py
  jax/experimental/array.py
  jax/interpreters/pxla.py
  jax/interpreters/xla.py
  tests/typing_test.py
Labels: pull ready

#12468 Checkify: misc improvements.
  jax/_src/checkify.py
  tests/checkify_test.py
Labels: pull ready

#12496 fix typo in test
  tests/nn_test.py
Labels: pull ready

#12513 Remove unused _remat_static_argnums import.
  jax/_src/api.py
Labels: pull ready

#12517 Update version and changelog for jax 0.3.18 release
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: pull ready

#12480 add `nvidia-smi` question to bug template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: pull ready

#12523 Fix bazel build alias
  jaxlib/jax.bzl
Labels: pull ready

#12524 Fix lax imports in `ad_checkpoint.py`
  jax/_src/ad_checkpoint.py
Labels: kokoro:force-run, pull ready

#12497 fix bug in djax type signature inference logic
  jax/interpreters/partial_eval.py
  jax/linear_util.py
  tests/dynamic_api_test.py
Labels: pull ready

#12382 [x64] add promote_integers argument to jnp.prod & jnp.sum
  jax/_src/numpy/reductions.py
  tests/lax_numpy_test.py
Labels: pull ready

#12546 [c++ jit] only set use_fastpath in cache_miss if all args are DeviceArrays
  jax/_src/api.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#12540 Fix lowering bug in effectful batched cond and add tests
  jax/_src/lax/control_flow/loops.py
  tests/debugging_primitives_test.py
Labels: pull ready

#12552 Fix test failure in GPU CI if NCCL_DEBUG is enabled.
  tests/multiprocess_gpu_test.py
Labels: pull ready

#12555 jax/jaxlib 0.3.20 release candidate.
  CHANGELOG.md
  WORKSPACE
  setup.py
Labels: pull ready

#12556 Disable multiprocess_gpu_test that fails on ROCm.
  tests/multiprocess_gpu_test.py
Labels: pull ready

#12538 [typing] setup: bundle *.pyi files with distribution
  setup.py
Labels: pull ready

#12565 Update version numbers after release.
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: pull ready

#12566 [dynamic-shapes] basic slicing support with dynamic shape result
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/_src/numpy/lax_numpy.py
  jax/core.py
  tests/dynamic_api_test.py
Labels: pull ready

#12444 Raise cond index into tracing context in case of effects
  jax/_src/lax/control_flow/conditionals.py
  tests/checkify_test.py
Labels: pull ready

#12579 Add options to `jnp.take` and use `unique_indices=True` in `random.permutation`
  jax/_src/numpy/lax_numpy.py
  jax/_src/random.py
  tests/lax_numpy_test.py
Labels: pull ready

#12588 [typing] use jax.Array annotations in random.py
  jax/_src/random.py
Labels: pull ready

#12594 Make persistent compilation cache warn instead of raise an error on cache read/write failures
  CHANGELOG.md
  jax/_src/config.py
  jax/_src/dispatch.py
  tests/compilation_cache_test.py
Labels: pull ready

#12602 Pin default jax.tools.colab_tpu.setup_tpu driver version.
  jax/tools/colab_tpu.py
Labels: pull ready

#12603 Fix typo in faq.rst.
  docs/faq.rst
Labels: pull ready

#12609 Fix jax2tf import so it works with both the latest tensorflow release (2.10.0) and tf-nightly
  jax/experimental/jax2tf/jax2tf.py
Labels: pull ready
