Repository jax-ml/jax, pull requests merged in 2022-02, with the labels that each got.

#9391 Add complex types to mlir constant handlers
  jax/interpreters/mlir.py
  tests/api_test.py
Labels: pull ready

#9394 update pre-commit package versions & fix new mypy errors
  .pre-commit-config.yaml
  docs/autodidax.md
  docs/autodidax.py
  docs/jax-101/01-jax-basics.md
  docs/jax-101/02-jitting.md
  docs/jax-101/03-vectorization.md
  docs/jax-101/04-advanced-autodiff.md
  docs/jax-101/05-random-numbers.md
  docs/jax-101/05.1-pytrees.md
  docs/jax-101/06-parallelism.md
  docs/jax-101/07-state.md
  docs/jax-101/08-pjit.md
  docs/notebooks/Common_Gotchas_in_JAX.md
  docs/notebooks/Custom_derivative_rules_for_Python_code.md
  docs/notebooks/How_JAX_primitives_work.md
  docs/notebooks/Neural_Network_and_Data_Loading.md
  docs/notebooks/Writing_custom_interpreters_in_Jax.md
  docs/notebooks/autodiff_cookbook.md
  docs/notebooks/convolutions.md
  docs/notebooks/neural_network_with_tfds_data.md
  docs/notebooks/quickstart.md
  docs/notebooks/thinking_in_jax.md
  docs/notebooks/vmapped_log_probs.md
  docs/notebooks/xmap_tutorial.md
  docs/transformations.md
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
  jax/experimental/maps.py
  jax/interpreters/mlir.py
  jax/interpreters/xla.py
Labels: pull ready

#9408 Bump jax version to 0.2.29 and update CHANGELOG
  CHANGELOG.md
  jax/version.py
Labels: kokoro:force-run, pull ready

#9401 [jax2tf] minor changes to the documentation for TF Lite
  jax/experimental/jax2tf/examples/tflite/mnist/README.md
Labels: pull ready

#9415 Work around call expansion in MHLO->HLO lowering.
  jax/_src/lax/lax.py
Labels: pull ready

#9416 Move design notes into docs/, and render them as part of the document…
  docs/design_notes/custom_derivatives.md
  docs/design_notes/index.rst
  docs/design_notes/omnistaging.md
  docs/design_notes/prng.md
  docs/index.rst
Labels: pull ready

#9425 [jax2tf] Add a TF version check for support of conv:batch_group_count
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/jax2tf.py
Labels: pull ready

#9430 Ensure that tree_util.Partial's .func attribute is stable.
  jax/_src/tree_util.py
  tests/tree_util_test.py
Labels: pull ready

#9417 Support string fft_type values in lax.fft.
  jax/_src/lax/fft.py
  tests/fft_test.py
Labels: pull ready

#9432 [sparse] fix bcoo_extract batching rule
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: pull ready

#9433 Cut a new jaxlib release
  WORKSPACE
Labels: pull ready

#4671 Add `lax.conv_general_dilated_local`
  docs/jax.lax.rst
  jax/_src/lax/other.py
  jax/lax/__init__.py
  tests/lax_test.py
Labels: cla: yes, pull ready

#9372 add pytree utilities for better errors
  jax/_src/api.py
  jax/_src/tree_util.py
  tests/tree_util_test.py
Labels: pull ready

#9440 Use the sphinx-book-theme for JAX documentation.
  docs/conf.py
  docs/requirements.txt
Labels: pull ready

#9446 Add `-j auto` to the suggested doc build instructions.
  docs/developer.md
Labels: pull ready

#9448 Fix rendering of cube root in docs.
  jax/_src/lax/lax.py
Labels: pull ready

#9395 NumpyUfuncTests: improve test generation
  jax/_src/test_util.py
  tests/lax_numpy_test.py
Labels: pull ready

#9437 DOC: move functions in jax.html to their own pages
  docs/jax.experimental.ann.rst
  docs/jax.experimental.global_device_array.rst
  docs/jax.experimental.host_callback.rst
  docs/jax.experimental.maps.rst
  docs/jax.experimental.rst
  docs/jax.experimental.sparse.rst
  docs/jax.rst
Labels: pull ready

#9441 tests: add unsigned ints to all_dtypes
  jax/_src/test_util.py
  tests/lax_numpy_test.py
Labels: pull ready

#9477 Update scipy intersphinx inventory for SciPy 1.8.0.
  docs/conf.py
Labels: pull ready

#9419 Introduce a new jax/jaxlib versioning scheme.
  docs/design_notes/index.rst
  docs/design_notes/jax_versioning.md
  jax/_src/api.py
  jax/_src/lib/__init__.py
  jax/experimental/compilation_cache/compilation_cache.py
  jax/version.py
  tests/version_test.py
Labels: pull ready

#9442 remove some unnecessary code
  jax/interpreters/ad.py
Labels: pull ready

#9488 Add jet-primitive for dynamic_slice
  jax/experimental/jet.py
  tests/jet_test.py
Labels: pull ready

#9489 Fix missing handler when lexically capturing a ShardedDeviceArray whe…
  jax/interpreters/pxla.py
  tests/pmap_test.py
Labels: pull ready

#9481 CI: during tests, error if docstring rewrite fails
  .github/workflows/ci-build.yaml
  jax/_src/numpy/util.py
Labels: pull ready

#9471 Add jax.numpy.generic
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.py
Labels: pull ready

#9461 Expand implementation of lax_numpy._quantile to allow the input of a …
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#9204 Checkify: rename some symbols and add some docstrings.
  docs/jax.experimental.rst
  jax/experimental/checkify.py
  tests/checkify_test.py
Labels: pull ready

#9494 Added an explicit Any return type to lax_numpy.ndarray methods
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#9509 [checkify] handle custom_jvp
  jax/experimental/checkify.py
  tests/checkify_test.py
Labels: pull ready

#9510 [checkify] support custom_vjp
  jax/experimental/checkify.py
  tests/checkify_test.py
Labels: pull ready

#9511 Replace core.pp_eqn_compact() with core.str_eqn_compact().
  jax/core.py
  jax/interpreters/mlir.py
  jax/interpreters/xla.py
Labels: pull ready

#9514 update TF commit for release
  WORKSPACE
Labels: pull ready

#9523 Update TF commit for release
  WORKSPACE
Labels: pull ready

#9330 tests: set numpy_rank_promotion='raise' by default
  CHANGELOG.md
  jax/_src/test_util.py
  jax/experimental/jax2tf/tests/tf_test_util.py
  tests/api_test.py
  tests/batching_test.py
  tests/fft_test.py
  tests/infeed_test.py
  tests/lax_autodiff_test.py
  tests/lax_numpy_einsum_test.py
  tests/lax_numpy_indexing_test.py
  tests/lax_numpy_test.py
  tests/lax_numpy_vectorize_test.py
  tests/lax_scipy_sparse_test.py
  tests/lax_scipy_test.py
  tests/lax_test.py
  tests/linalg_test.py
  tests/nn_test.py
  tests/pjit_test.py
  tests/pmap_test.py
  tests/qdwh_test.py
  tests/random_test.py
  tests/scipy_fft_test.py
  tests/scipy_ndimage_test.py
  tests/scipy_optimize_test.py
  tests/scipy_signal_test.py
  tests/sharded_jit_test.py
  tests/sparse_test.py
  tests/sparsify_test.py
  tests/xmap_test.py
Labels: pull ready

#9475 DOC: add ability to document extra parameters within _wraps
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
Labels: pull ready

#9526 tests: use lax.broadcast_shapes in place of custom logic
  tests/lax_numpy_test.py
Labels: pull ready

#9469 Recommend optax in jax.experimental_libraries.optimizers documentation.
  jax/example_libraries/optimizers.py
Labels: pull ready

#9456 add flag for jaxpr colorful syntax highlighting
  jax/_src/config.py
  jax/_src/lax/lax.py
  jax/_src/pretty_printer.py
  jax/core.py
Labels: pull ready

#9500 [remove units] make JaxprTrace.process_map not introduce units
  jax/core.py
  jax/interpreters/partial_eval.py
Labels: pull ready

#9491 Rename api wrapper functions to always refer to the JAX transform.
  jax/_src/api.py
Labels: pull ready

#9557 Checkify: handle named_call in process_call.
  jax/experimental/checkify.py
  tests/checkify_test.py
Labels: pull ready

#9559 Add constant handler for tokens.
  jax/interpreters/mlir.py
  jax/interpreters/xla.py
  tests/api_test.py
Labels: pull ready

#9563 Fix incorrect binary search comparison in lax.select_n lowering.
  jax/_src/lax/lax.py
  tests/lax_test.py
Labels: pull ready

#9562 JaxTestCase: set jax_numpy_rank_promotion='raise' by default
  CHANGELOG.md
  jax/_src/test_util.py
  tests/api_test.py
  tests/batching_test.py
  tests/fft_test.py
  tests/infeed_test.py
  tests/lax_autodiff_test.py
  tests/lax_numpy_einsum_test.py
  tests/lax_numpy_indexing_test.py
  tests/lax_numpy_test.py
  tests/lax_numpy_vectorize_test.py
  tests/lax_scipy_sparse_test.py
  tests/lax_scipy_test.py
  tests/lax_test.py
  tests/linalg_test.py
  tests/nn_test.py
  tests/pjit_test.py
  tests/pmap_test.py
  tests/qdwh_test.py
  tests/random_test.py
  tests/scipy_fft_test.py
  tests/scipy_ndimage_test.py
  tests/scipy_optimize_test.py
  tests/scipy_signal_test.py
  tests/sharded_jit_test.py
  tests/sparse_test.py
  tests/sparsify_test.py
  tests/xmap_test.py
Labels: pull ready

#9564 Add a warning to random.choice
  jax/_src/random.py
Labels: pull ready

#9407 Add type promotion design doc
  docs/conf.py
  docs/design_notes/index.rst
  docs/design_notes/type_promotion.ipynb
  docs/design_notes/type_promotion.md
  docs/type_promotion.rst
Labels: pull ready

#9485 Update compilation cache logging to log individual hashes
  jax/experimental/compilation_cache/compilation_cache.py
Labels: pull ready

#9573 Update the list of default CUDA capabilities used for wheel builds to…
  .bazelrc
  build/build.py
Labels: pull ready

#9587 Fix nomenclature in type promotion doc
  docs/_static/type_lattice.svg
  docs/type_promotion.rst
Labels: pull ready

#9585 type promotion design doc: minor typos
  docs/design_notes/type_promotion.ipynb
  docs/design_notes/type_promotion.md
Labels: pull ready

#9561 Add translation rule for optimization barrier.
  jax/_src/config.py
  jax/_src/lax/control_flow.py
  jax/experimental/jax2tf/jax2tf.py
  tests/api_test.py
Labels: pull ready

#9595 [jax2tf] Fixed stale documentation about XLA metadata.
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/jax2tf.py
Labels: pull ready

#9597 [jax2tf] Fixes shape polymorphism for jnp.take_along_axes
  jax/_src/numpy/lax_numpy.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#9602 Checkify: fix nd-error case in check_error when array only has 1 element.
  jax/experimental/checkify.py
  tests/checkify_test.py
Labels: pull ready

#9605 Add cloudpickle as a test requirement.
  build/test-requirements.txt
Labels: pull ready

#9544 Adds matrix sqrt
  jax/_src/scipy/linalg.py
  jax/scipy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#9609 implement `jnp.expand_dims` and `jnp.stack` for PRNGKeyArrays
  jax/_src/lax/lax.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/prng.py
  tests/random_test.py
Labels: pull ready

#9616 Clarify the NVidia driver version requirements.
  README.md
Labels: pull ready

#9615 err on repeated axes to `expand_dims`, as numpy does
  jax/_src/lax/lax.py
  tests/lax_numpy_test.py
Labels: pull ready

#9422 Add scipy.signal.stft.
  jax/_src/scipy/signal.py
  jax/_src/third_party/scipy/signal_helper.py
  jax/scipy/signal.py
  tests/scipy_signal_test.py
Labels: pull ready

#9621 Add jax.distributed and jax.dlpack to the docs.
  CHANGELOG.md
  docs/jax.distributed.rst
  docs/jax.dlpack.rst
  docs/jax.rst
  docs/jax.scipy.rst
  jax/_src/distributed.py
Labels: pull ready

#9620 Add deprecation warning to JaxTestCase and JaxTestLoader
  CHANGELOG.md
  jax/test_util.py
  tests/mesh_utils_test.py
  tests/svd_test.py
Labels: pull ready

#9631 [jax2tf] Added more links to the documentation
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/converters_eval/README.md
Labels: pull ready

#9594 fix: use boolean tf functions where possible instead of bool->int8->bool for jax2tf
  jax/experimental/jax2tf/jax2tf.py
Labels: pull ready

#9607 Index update operators: add scatter_apply()
  jax/_src/lax/slicing.py
  jax/_src/numpy/lax_numpy.py
  jax/lax/__init__.py
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#9617 in tests, compare jnp operations on PRNGKeyArrays to the same on jnp arrays
  tests/random_test.py
Labels: pull ready

#9636 Checkify: address initial feedback.
  jax/experimental/checkify/__init__.py
  jax/experimental/checkify/checkify_impl.py
  tests/checkify_test.py
Labels: pull ready

#9613 use singleton dims in broadcasting binop batchers
  jax/interpreters/batching.py
Labels: pull ready

#9052 Add jax.nn.initializers.constant
  jax/_src/nn/initializers.py
  jax/nn/initializers.py
Labels: pull ready

#9619 Remove jax.ops.index... functions.
  CHANGELOG.md
  docs/jax.ops.rst
  jax/_src/ops/scatter.py
  jax/ops/__init__.py
Labels: pull ready

#9658 Add copy button to code snippets in documentation
  docs/conf.py
  docs/requirements.txt
Labels: pull ready

#9684 Remove duplicate changelog entry
  CHANGELOG.md
Labels: pull ready

#9641 IREE's get_default_device_assignment should return List[Device]
  jax/_src/iree.py
Labels: pull ready

#9623 Fix Iree backend to for copy_to_device and executable results
  jax/_src/iree.py
Labels: kokoro:force-run, pull ready

#9702 BUG: return numpy arrays for jnp.load() with unsupported dtypes
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#9706 Relax tolerances slightly for MKL
  tests/custom_root_test.py
Labels: pull ready

#9701 DOC: update sharp bits info about fori_loop differentiability
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
Labels: pull ready

#9711 Remove an unnecessary condition.
  jax/_src/api.py
  jax/experimental/pjit.py
Labels: pull ready

#9721 jax.random.poisson: fix corner cases
  jax/_src/random.py
  tests/random_test.py
Labels: pull ready
