Repository jax-ml/jax, pull requests merged in 2022-06, with the labels that each got.

#10913 [x64] make jnp.histogram and related functions work with strict promotion
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#10904 [x64] make jnp.trapz compatible with strict dtype promotion
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#10921 [x64] jnp.ldexp: avoid implicit 64-bit promotion
  CHANGELOG.md
  jax/_src/numpy/ufuncs.py
  tests/lax_numpy_test.py
Labels: pull ready

#10925 Fix batching rule for convolution for batch dimensions of size 0.
  jax/_src/lax/convolution.py
  tests/lax_vmap_test.py
Labels: pull ready

#10931 [x64] make jnp.interp safe for use with strict dtype promotion
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#10935 [x64] make linspace, logspace, & geomspace compatible with strict promotion
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#10938 [x64] make jnp.corrcoef compatible with strict dtype promotion
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#10934 Disallow complex dtypes for lax ops rem, lt, le, gt, and ge.
  jax/_src/lax/lax.py
  tests/lax_test.py
Labels: pull ready

#10939 [x64] make jnp.insert compatible with strict dtype promotion
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#10936 [x64] make jnp.average compatible with strict promotion
  jax/_src/numpy/reductions.py
Labels: pull ready

#10942 [x64] make jax.numpy reductions respect input dtypes
  jax/_src/numpy/reductions.py
  tests/lax_numpy_test.py
Labels: pull ready

#10944 Bump minimum Mac OS version to 10.14 (Mojave).
  .bazelrc
  CHANGELOG.md
  build/build_wheel.py
Labels: pull ready

#10906 Store profiler server as a global variable and add a `stop_server` function
  CHANGELOG.md
  docs/profiling.md
  jax/_src/profiler.py
  jax/profiler.py
  tests/profiler_test.py
Labels: pull ready

#10933 Use util.unzipN() in more places instead of zip(*args).
  jax/_src/lax/convolution.py
  jax/_src/lax_reference.py
  jax/_src/scipy/ndimage.py
Labels: pull ready

#10945 Fix bitrot in IREE Python integration.
  jax/_src/iree.py
Labels: pull ready

#10946 2nd attempt at fixing IREE integration.
  jax/_src/iree.py
Labels: pull ready

#9118 Add `jax.default_device` context manager
  docs/faq.rst
  docs/jax.config.rst
  jax/__init__.py
  jax/_src/api.py
  jax/_src/config.py
  jax/_src/dispatch.py
  jax/linear_util.py
  tests/api_test.py
Labels: pull ready

#10954 Guard `has_explicit_device` with xla_client version
  jax/_src/api.py
Labels: pull ready

#10955 [IREE] Allow backend selection via a flag.
  jax/_src/iree.py
Labels: pull ready

#10950 [jax2tf] Added a test for SavedModel with pytrees
  jax/experimental/jax2tf/tests/savedmodel_test.py
Labels: pull ready

#10970 [ROCm] Enable XLA python callback on ROCm.
  jax/interpreters/mlir.py
  tests/array_interoperability_test.py
Labels: pull ready

#10978 [x64] make jnp.modf() compatible with strict dtype promotion
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#10937 Added random.gnormal and random.ball.
  CHANGELOG.md
  docs/jax.random.rst
  jax/_src/random.py
  jax/random.py
  tests/random_test.py
Labels: pull ready

#10964 Add `python -m jax.collect_profile` for manual trace capture
  .github/workflows/ci-build.yaml
  CHANGELOG.md
  docs/profiling.md
  jax/collect_profile.py
  tests/profiler_test.py
Labels: pull ready

#10988 correct spelling on comment
  docs/design_notes/sequencing_effects.md
  docs/jax-101/02-jitting.ipynb
  docs/jax-101/02-jitting.md
  docs/profiling.md
  jax/experimental/jet.py
Labels: pull ready

#11020 Enable debug print in xmap
  jax/experimental/maps.py
  tests/debugging_primitives_test.py
  tests/jaxpr_effects_test.py
Labels: pull ready

#11006 Update testReducerNoDtype and others to not run duplicate tests.
  jax/_src/test_util.py
  tests/lax_numpy_test.py
Labels: pull ready

#10979 lax_numpy_test: test bitwise ops on full input range
  jax/_src/test_util.py
  tests/lax_numpy_test.py
Labels: pull ready

#10980 Add jax.default_device to CHANGELOG
  CHANGELOG.md
Labels: pull ready

#11031 [x64] Make TPU svd compatible with strict type promotion
  jax/_src/lax/qdwh.py
  jax/_src/lax/svd.py
Labels: pull ready

#11030 jnp.unique: improve error when run under JIT
  jax/_src/numpy/setops.py
Labels: pull ready

#10827 Add a public facing `named_scope` function
  jax/__init__.py
  jax/_src/api.py
  tests/name_stack_test.py
Labels: pull ready

#11027 CI: unpin traitlets
  docs/requirements.txt
Labels: pull ready

#11041 Update changelog for `named_scope`
  CHANGELOG.md
  docs/jax.rst
Labels: pull ready

#11045 [x64] gmres: avoid problematic type promotions
  jax/_src/scipy/sparse/linalg.py
Labels: pull ready

#11048 Update lax.py
  jax/_src/lax/lax.py
Labels: pull ready

#11040 DOC: add FAQ section on zero gradients for rank-based operations
  docs/faq.rst
Labels: pull ready

#11057 Clarify that functions passed to jax.jit must be weakly referenceable.
  jax/_src/api.py
Labels: pull ready

#11058 Improve documentation for jax.tree_util.tree_map.
  jax/_src/tree_util.py
Labels: pull ready

#11044 [sparse][x64] prevent unnecessary dtype promotion in sparse impls
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/csr.py
Labels: pull ready

#10771 Using GFile for persistent compilation caching in JAX
  CHANGELOG.md
  jax/experimental/compilation_cache/compilation_cache.py
  jax/experimental/compilation_cache/file_system_cache.py
  jax/experimental/compilation_cache/gfile_cache.py
  tests/file_system_cache_test.py
  tests/gfile_cache_test.py
Labels: pull ready

#11073 Bump version of Tensorflow-Repo to fix MlirHLO build error in source builds
  WORKSPACE
Labels: pull ready

#11085 Change the remat rule registration to register a default with a GPU s…
  jax/_src/lax/control_flow/remat_impl.py
  jax/experimental/jax2tf/jax2tf.py
Labels: kokoro:force-run, pull ready

#11064 Add an undocumented method on jit() functions to clear the function c…
  jax/_src/api.py
  jax/_src/dispatch.py
  jax/linear_util.py
  tests/api_test.py
Labels: pull ready

#11052 [x64] make lax_scipy_test.py compatible with strict dtype promotion
  jax/_src/lax/eigh.py
  jax/_src/lax/qdwh.py
  jax/_src/scipy/linalg.py
  jax/_src/scipy/special.py
  tests/lax_scipy_test.py
Labels: pull ready

#10865 [x64] make lax_numpy_test compatible with strict dtype promotion
  tests/lax_numpy_test.py
Labels: pull ready

#10424 Annotate vmap
  jax/_src/api.py
Labels: pull ready

#11098 adding os env to track JAX platform
  jax/_src/cloud_tpu_init.py
Labels: pull ready

#11001 Allow doing reductions on empty arrays in some cases.
  jax/_src/numpy/reductions.py
  tests/lax_numpy_test.py
Labels: kokoro:force-run, pull ready

#11032 fix pjit doc
  jax/experimental/pjit.py
Labels: pull ready

#11105 Improve the comment in WORKSPACE describing how to override the TF re…
  WORKSPACE
Labels: kokoro:force-run, pull ready

#11101 [x64] make tree_util_test compatible with strict dtype promotion
  tests/tree_util_test.py
Labels: pull ready

#11043 Add bitwise XOR reducer to `lax.reduce`
  jax/_src/lax/lax.py
  jax/experimental/jax2tf/jax2tf.py
  jax/lax/__init__.py
  tests/lax_test.py
Labels: pull ready

#11117 BUG: avoid warning when specifying dtype=complex in X32 mode
  jax/_src/lax/lax.py
  tests/api_test.py
Labels: pull ready

#11083 Add stateful for loop primitives
  jax/_src/ad_util.py
  jax/_src/lax/control_flow/for_loop.py
  jax/core.py
  jax/interpreters/xla.py
  tests/lax_control_flow_test.py
Labels: pull ready

#11103 [x64] make api_test compatible with strict dtype promotion
  tests/api_test.py
Labels: pull ready

#11095 [x64] make sparse tests compatible with strict dtype promotion
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
  tests/sparsify_test.py
Labels: pull ready

#11110 [x64] make fft functionality compatible with strict dtype promotion
  jax/_src/lax/fft.py
  jax/_src/numpy/fft.py
  jax/_src/numpy/util.py
  jax/_src/scipy/fft.py
  tests/fft_test.py
Labels: pull ready

#11113 [x64] make image_test compatible with strict dtype promotion
  jax/_src/image/scale.py
Labels: pull ready

#11114 [x64] make lax_test compatible with strict dtype promotion
  tests/lax_test.py
Labels: pull ready

#11100 [x64] make scipy_stats_test.py compatible with strict dtype promotion
  jax/_src/scipy/stats/multivariate_normal.py
  tests/scipy_stats_test.py
Labels: pull ready

#11131 [x64] make lax_numpy_indexing_test pass with strict dtype promotion
  jax/_src/test_util.py
  tests/lax_numpy_indexing_test.py
  tests/lax_numpy_test.py
  tests/scipy_stats_test.py
  tests/sparse_test.py
Labels: kokoro:force-run, pull ready

#11132 [x64] make lax_numpy_vectorize_test work with strict dtype promotion
  tests/lax_numpy_vectorize_test.py
Labels: pull ready

#11134 [x64] make jaxpr_effects_test pass with strict dtype promotion
  tests/jaxpr_effects_test.py
Labels: pull ready

#11124 [x64] make linalg functions & tests compatible with strict dtype promotion
  jax/_src/lax/linalg.py
  jax/_src/numpy/linalg.py
  jax/_src/scipy/linalg.py
  tests/linalg_test.py
  tests/svd_test.py
Labels: pull ready

#11126 [x64] make nn_test pass with strict dtype promotion
  jax/_src/nn/functions.py
  jax/_src/nn/initializers.py
Labels: pull ready

#11136 [x64] make pmap_test compatible with strict dtype promotion
  tests/pmap_test.py
Labels: pull ready

#11135 [x64] make host_callback_test compatible with strict dtype promotion
  jax/_src/lax/lax.py
  tests/host_callback_test.py
Labels: pull ready

#11104 [x64] make scipy_ndimage_test compatible with strict dtype promotion
  tests/scipy_ndimage_test.py
Labels: pull ready

#11139 [x64] make examples/control_test compatible with strict dtype promotion
  examples/control.py
  examples/control_test.py
Labels: kokoro:force-run, pull ready

#11129 [x64] make checkify compatible with strict dtype promotion
  jax/_src/checkify.py
  tests/checkify_test.py
Labels: pull ready

#11149 Make sure libtpu is initialized before initializing TPU profiling.
  jax/_src/profiler.py
Labels: pull ready

#11148 [x64] make lax_control_flow_test compatible with strict dtype promotion
  tests/lax_control_flow_test.py
Labels: pull ready

#11116 [dynamic-shapes] initial support for dynamic shape typechecks
  jax/_src/custom_transpose.py
  jax/_src/dispatch.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/core.py
  jax/experimental/maps.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
  tests/core_test.py
Labels: pull ready

#11151 optimize grad-of-jit not to pass input-residuals as intermediate-residuals
  jax/interpreters/partial_eval.py
  tests/core_test.py
Labels: pull ready

#11155 [x64] make ode_test pass with strict dtype promotion
  jax/experimental/ode.py
  tests/ode_test.py
Labels: pull ready

#11157 [x64] make vmap_test compatible with strict dtype promotion
  tests/lax_vmap_test.py
Labels: pull ready

#11159 [x64] make pjit_test compatible with strict dtype promotion
  tests/pjit_test.py
Labels: pull ready

#11162 [x64] make sharded_jit_test compatible with strict dtype promotion
  tests/sharded_jit_test.py
Labels: pull ready

#11150 [x64] make jax.scipy.sparse.linalg compatible with strict dtype promotion
  jax/_src/scipy/sparse/linalg.py
  tests/lax_scipy_sparse_test.py
Labels: pull ready

#11158 [x64] make batching_test compatible with strict dtype promotion
  tests/batching_test.py
Labels: pull ready

#11163 [x64] make polynomial_test compatible with strict dtype promotion
  jax/_src/numpy/polynomial.py
Labels: pull ready

#11161 Remove spurious single quote in profiler.py
  jax/_src/profiler.py
Labels: pull ready

#10576 [new-remat] add scan rule for new remat
  jax/_src/ad_checkpoint.py
  jax/_src/lax/control_flow/loops.py
  jax/interpreters/ad.py
  jax/interpreters/mlir.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
  tests/lax_control_flow_test.py
  tests/pmap_test.py
Labels: pull ready

#10852 Checkify: support discharging checks from control-flow through effects.
  jax/_src/checkify.py
  jax/experimental/jax2tf/jax2tf.py
  tests/checkify_test.py
Labels: pull ready

#11160 [x64] make xmap_test compatible with strict dtype promotion
  tests/xmap_test.py
Labels: pull ready

#11184 CI: build docs with most recent myst-nb version
  docs/requirements.txt
Labels: pull ready

#11187 Update versions for jax/jaxlib release
  CHANGELOG.md
  WORKSPACE
  jaxlib/version.py
  setup.py
Labels: pull ready

#11189 DOC: clarify variable names
  jax/_src/api.py
Labels: pull ready

#11192 Update TF version for jaxlib build
  WORKSPACE
Labels: pull ready

#11147 [x64] make jax.scipy.signal compatible with strict dtype promotion.
  jax/_src/scipy/signal.py
  jax/_src/third_party/scipy/signal_helper.py
  tests/scipy_signal_test.py
Labels: pull ready

#11207 [x64] make scipy_optimize_test compatible with strict dtype promotion
  tests/scipy_optimize_test.py
Labels: pull ready

#11186 [x64] mention flag value in strict type promotion error
  jax/_src/dtypes.py
  tests/dtypes_test.py
Labels: pull ready

#10840 WIP: [x64] set jax_numpy_dtype_promotion='strict' in tests
  jax/_src/test_util.py
  jax/experimental/jax2tf/tests/tf_test_util.py
Labels: pull ready

#11173 Fix overflow of large prng computation
  jax/_src/prng.py
  tests/random_test.py
Labels: pull ready

#11156 [dynamic-shapes] basic jvp working, including with broadcast
  jax/_src/lax/lax.py
  jax/core.py
  jax/interpreters/ad.py
  tests/api_test.py
Labels: pull ready

#11229 Fix getting aval of BatchTracers that are not mapped.
  jax/interpreters/batching.py
Labels: pull ready

#11230 Make JAX compatible with numpy version 1.23.0
  build/test-requirements.txt
  jax/_src/custom_derivatives.py
  jax/_src/dispatch.py
  jax/_src/lax/lax.py
  jax/_src/numpy/util.py
  jax/_src/test_util.py
  jax/interpreters/ad.py
  jax/interpreters/xla.py
  tests/lax_numpy_test.py
  tests/random_test.py
Labels: pull ready

#11215 jnp.roots: better support for computation under JIT
  CHANGELOG.md
  jax/_src/numpy/polynomial.py
  tests/polynomial_test.py
Labels: pull ready

#11226 [jax2tf] Fix the documentation for handling dimension polynomials.
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#11231 Add a build flag that allows disabling remote TPU builds.
  build/BUILD.bazel
  build/build.py
  build/build_wheel.py
Labels: pull ready

#11247 Reduce size of double-sided maxwell random test.
  tests/random_test.py
Labels: pull ready

#11251 Increase the minimum scipy version to 1.5.
  jax/_src/scipy/stats/betabinom.py
  jaxlib/setup.py
  setup.py
  tests/scipy_optimize_test.py
  tests/scipy_stats_test.py
Labels: pull ready

#11255 Fix broken links for moved design_notes folder
  CHANGELOG.md
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
  jax/_src/config.py
  jax/experimental/jax2tf/README.md
Labels: pull ready

#11146 Change JAX_PLATFORMS to raise an exception when platform initialization fails
  CHANGELOG.md
  jax/_src/config.py
  jax/_src/lib/xla_bridge.py
Labels: pull ready

#11250 Checkify: add (checkify-of-)vmap-of-check.
  jax/_src/checkify.py
  tests/checkify_test.py
Labels: pull ready

#11244 Update XLA.
  WORKSPACE
Labels: pull ready

#11273 Update CHANGELOG.md and setup.py for 0.3.14 release.
  CHANGELOG.md
  setup.py
Labels: pull ready

#11248 jax.test_util: remove deprecated test classes.
  CHANGELOG.md
  jax/_src/test_util.py
  jax/test_util.py
Labels: pull ready

#11214 Add `for_loop` primitive and impl rule
  jax/_src/lax/control_flow/for_loop.py
  tests/lax_control_flow_test.py
Labels: pull ready

#11288 Disable test for GPU/TPU warning on Mac.
  tests/api_test.py
Labels: pull ready

#11287 random.choice: make compatible with strict promotion
  jax/_src/random.py
  tests/random_test.py
Labels: pull ready

#11294 Bump JAX/Jaxlib versions
  docs/jax.lib.rst
  jax/version.py
  jaxlib/version.py
  setup.py
Labels: pull ready

#11300 Bump minimum jaxlib version to 0.3.10
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/_src/lax/windowed_reductions.py
  jax/experimental/host_callback.py
  jax/interpreters/mlir.py
  jax/version.py
  jaxlib/pocketfft.py
  tests/debugging_primitives_test.py
  tests/jaxpr_effects_test.py
  tests/linalg_test.py
Labels: pull ready

#11237 Adding an implementation of scipy.stats.gaussian_kde
  CHANGELOG.md
  docs/jax.scipy.rst
  jax/_src/scipy/stats/kde.py
  jax/scipy/stats/__init__.py
  tests/scipy_stats_test.py
Labels: pull ready

#11292 (Github CI) Bump ci-build's pre-commit action version
  .github/workflows/ci-build.yaml
Labels: pull ready

#11234 jnp.ndarray: raise error for binary operations with lists and tuples
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
  tests/host_callback_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#11302 [ROCm] Upgrade ROCm build docker to ROCm version 5.2.
  build/rocm/Dockerfile.rocm
Labels: pull ready

#11308 DeviceArray: raise explicit NotImplementedError for arr.flat
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#11296 Expose ml_program dialect for MLIR builder
  build/BUILD.bazel
  build/build_wheel.py
  jax/_src/lib/mlir/dialects/__init__.py
  jaxlib/mlir/BUILD.bazel
Labels: pull ready

#11266 [ROCm] Fixes for compilation failures caused by compiler changes in R…
  .bazelrc
  jaxlib/rocm/hipsolver_kernels.cc
Labels: pull ready

#11301 Add scan implementation using `for` and tests
  jax/_src/lax/control_flow/for_loop.py
  tests/lax_control_flow_test.py
Labels: pull ready

#11311 vmap: better errors for mismatched axis in keyword arguments
  jax/_src/api.py
  tests/api_test.py
Labels: better_errors, pull ready

#10962 Add initial LOBPCG top-k eigenvalue solver (#3112)
  jax/experimental/sparse/__init__.py
  jax/experimental/sparse/linalg.py
  tests/lobpcg_test.py
Labels: pull ready

#11268 [dynamic-shapes] basic linearize and grad working
  jax/_src/ad_checkpoint.py
  jax/_src/dispatch.py
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/_src/util.py
  jax/core.py
  jax/interpreters/ad.py
  jax/interpreters/partial_eval.py
  jax/linear_util.py
  tests/api_test.py
Labels: pull ready

#11326 Skip F64 tests on GPU.
  tests/lobpcg_test.py
Labels: pull ready

#11298 Jax caches should depend on axis env.
  jax/_src/config.py
  jax/_src/numpy/lax_numpy.py
  jax/core.py
  tests/api_test.py
  tests/lax_control_flow_test.py
  tests/pmap_test.py
Labels: pull ready
