Repository jax-ml/jax, pull requests merged in 2022-04, with the labels that each got.

#10113 Don't compare versions as strings.
  jax/experimental/jax2tf/jax2tf.py
Labels: pull ready

#10103 Checkify: add axis and axis size to OOB error message.
  jax/experimental/checkify/checkify_impl.py
  tests/checkify_test.py
Labels: pull ready

#10058 Add istft to jax.scipy.signal.
  docs/jax.scipy.rst
  jax/_src/scipy/signal.py
  jax/scipy/signal.py
  tests/scipy_signal_test.py
Labels: pull ready

#10119 CI: pin pillow<9.1 to prevent deprecation warnings
  build/test-requirements.txt
Labels: pull ready

#10110 Fix race condition for weakref destructor by catching rare exceptions.
  jax/_src/util.py
  tests/util_test.py
Labels: pull ready

#10123 remove $ from commands
  docs/developer.md
Labels: pull ready

#10126 Deprecate jax.tree_util.tree_multimap
  CHANGELOG.md
  cloud_tpu_colabs/Wave_Equation.ipynb
  docs/jax-101/05.1-pytrees.ipynb
  docs/jax-101/05.1-pytrees.md
  docs/jax-101/06-parallelism.ipynb
  docs/jax-101/06-parallelism.md
  docs/jax-101/07-state.ipynb
  docs/jax-101/07-state.md
  jax/_src/api.py
  jax/_src/api_util.py
  jax/_src/custom_derivatives.py
  jax/_src/lax/control_flow.py
  jax/_src/scipy/sparse/linalg.py
  jax/_src/test_util.py
  jax/_src/tree_util.py
  jax/experimental/jax2tf/tests/tf_test_util.py
  jax/tree_util.py
  tests/core_test.py
  tests/lax_test.py
  tests/pmap_test.py
  tests/tree_util_test.py
Labels: pull ready

#10121 Avoid retracing when a host_callback.call is called multiple times wi…
  jax/experimental/host_callback.py
  tests/host_callback_test.py
Labels: pull ready

#10122 Changes `jax2tf`'s `test_name_scope` to use graph introspection instead of a side-effect
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: pull ready

#10130 remove string annotations from core.py
  jax/core.py
Labels: pull ready

#10139 CI Fix: Skip test outside x64
  tests/fft_test.py
Labels: pull ready

#10148 Add version int tuple `__version_info__` to JAX
  jax/__init__.py
  jax/version.py
Labels: pull ready

#10160 Implement `jnp.trace` in terms of `jnp.diagonal`
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#10164 Pin a newer @platforms in the Bazel workspace to fix Mac ARM builds.
  WORKSPACE
Labels: pull ready

#10173 [sparse] add bcoo_add_batchdim
  jax/experimental/sparse/__init__.py
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: pull ready

#10177 Jax 0.3.5 and jaxlib 0.3.5 release.
  CHANGELOG.md
  WORKSPACE
  jaxlib/version.py
  setup.py
Labels: pull ready

#10175 [sparse] make bcoo_spdot_general return a BCOO array, not raw buffers
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/transform.py
Labels: pull ready

#10039 Add scipy.linalg.rsf2csf
  CHANGELOG.md
  docs/jax.scipy.rst
  jax/_src/scipy/linalg.py
  jax/scipy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#10167 Consolidation of hipsolver/cusolver APIs.
  jax/_src/lax/linalg.py
  jax/_src/lib/__init__.py
Labels: pull ready

#10184 [sparse] consolidate flavors of bcoo_dot_general
  jax/experimental/sparse/__init__.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/transform.py
  tests/sparse_test.py
Labels: pull ready

#10185 Update libtpu version for jax 0.3.5 release.
  setup.py
Labels: pull ready

#10198 [sparse] fix autodiff bug in spdot_general
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: pull ready

#10176 Simplify `jnp.diagonal` and `jnp.trace`
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#10215 dispatch.py: type annotations, other minor tweaks
  jax/_src/dispatch.py
Labels: pull ready

#10120 prototyping dynamic shapes
  jax/_src/api.py
  jax/_src/config.py
  jax/_src/dispatch.py
  jax/_src/lax/control_flow.py
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/_src/lax/utils.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/tree_util.py
  jax/core.py
  jax/interpreters/ad.py
  jax/interpreters/batching.py
  jax/interpreters/mlir.py
  jax/interpreters/partial_eval.py
  jax/interpreters/xla.py
  jax/lax/__init__.py
  jax/linear_util.py
  tests/api_test.py
  tests/core_test.py
Labels: pull ready

#10249 Add Jaxpr effects tests for higher order primitives
  jax/_src/ad_checkpoint.py
  jax/_src/custom_derivatives.py
  jax/_src/dispatch.py
  jax/_src/lax/control_flow.py
  jax/core.py
  jax/experimental/maps.py
  jax/experimental/pjit.py
  jax/interpreters/partial_eval.py
  tests/jaxpr_effects_test.py
Labels: pull ready

#10260 Fix arguments to schur translation rule
  jax/_src/lax/linalg.py
Labels: pull ready

#10248 Fix#10247
  jax/_src/scipy/special.py
Labels: pull ready

#10220 Fix#10219
  jax/_src/scipy/stats/logistic.py
  tests/scipy_stats_test.py
Labels: pull ready

#10254 add default values to config context managers
  jax/_src/config.py
Labels: pull ready

#10263 Drop dead code now that the minimum jaxlib version is 0.3.2.
  jax/_src/dlpack.py
  jax/_src/lib/__init__.py
  jax/experimental/pjit.py
  tests/api_test.py
  tests/pjit_test.py
Labels: pull ready

#10262 better errors: check for callability of lax.control_flow arguments
  jax/_src/lax/control_flow.py
  tests/lax_control_flow_test.py
Labels: better_errors, pull ready

#10251 debug_nans: don't return results of successfully running de-optimized function
  jax/_src/dispatch.py
  tests/debug_nans_test.py
Labels: pull ready

#10264 Remove mention of six package from jaxlib build instructions.
  docs/developer.md
Labels: pull ready

#10226 Add np.polydiv numpy function
  docs/jax.numpy.rst
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/polynomial.py
  jax/numpy/__init__.py
  tests/lax_numpy_test.py
Labels: pull ready

#10265 Add libstdc++ workaround for conda users.
  jax/_src/lib/__init__.py
Labels: pull ready

#10268 Fix polydiv kokoro tests
  tests/lax_numpy_test.py
Labels: pull ready

#10289 Fix incorrect cross-reference breaking readthedocs build.
  CHANGELOG.md
Labels: pull ready

#10290 Comment on implementation of unzip2 & unzip3
  jax/_src/util.py
Labels: pull ready

#10286 Avoid broadcasting the input and indices in jnp.take_along_axis.
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#10294 [sparse] gate gpu lowering test to gpu backends
  tests/sparse_test.py
Labels: pull ready

#10216 Do not generate trivial gathers when indexing entire axis
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#9569 Clarified tree_flatten is_leaf docstring.
  jax/_src/tree_util.py
Labels: pull ready

#10309 Jax 0.3.7 and jaxlib 0.3.7 release.
  CHANGELOG.md
  WORKSPACE
  jaxlib/version.py
  setup.py
Labels: pull ready

#10288 Fix PRNGKeyArray.broadcast_to with scalar shape
  jax/_src/prng.py
  tests/random_test.py
Labels: pull ready

#10266 Deprecate DeviceArray.tile method
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#10312 2nd attempt at jax/jaxlib 0.3.7 release.
  CHANGELOG.md
  WORKSPACE
Labels: pull ready

#9809 Switch gpu, cpu and jax2tf to use the new OptimizationBarrier op.
  jax/_src/config.py
  jax/_src/lax/control_flow.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: pull ready

#10308 update mypy & related package versions
  .pre-commit-config.yaml
  jax/_src/nn/functions.py
  jax/interpreters/xla.py
Labels: pull ready, github_actions

#10253 DOC: add section on input validation in custom pytrees
  docs/pytrees.md
Labels: pull ready

#10239 [sparse] make bcoo_sort_indices a primitive
  jax/experimental/sparse/__init__.py
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: pull ready

#10314 Add a docstring for maps.Mesh
  docs/jax.experimental.maps.rst
  jax/interpreters/pxla.py
Labels: pull ready

#10318 Add another example of using `Mesh`.
  jax/interpreters/pxla.py
Labels: pull ready

#10326 Remove CpuDevice from documentation index.
  docs/jax.lib.rst
Labels: pull ready

#10217 [ROCm] ROCm specific fixes.
  jaxlib/hip_linalg.py
  jaxlib/hip_prng.py
Labels: pull ready

#10313 Add cross-reference to lax.GatherScatterMode from jax.numpy.ndarray.a…
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#10302 Improve the random module documentation.
  jax/random.py
Labels: pull ready

#10336 Fix typo in changelog.
  CHANGELOG.md
Labels: pull ready

#10325 Increase minimum jaxlib version to 0.3.7.
  jax/_src/lax/fft.py
  jax/_src/lax/lax.py
  jax/_src/lax/linalg.py
  jax/_src/lib/mlir/dialects/__init__.py
  jax/_src/lib/xla_bridge.py
  jax/_src/prng.py
  jax/experimental/compilation_cache/compilation_cache.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/coo.py
  jax/experimental/sparse/csr.py
  jax/interpreters/mlir.py
  jax/interpreters/pxla.py
  jax/version.py
  tests/fft_test.py
  tests/remote_transfer_test.py
Labels: pull ready

#10287 simplify _IndexGrid
  jax/_src/numpy/index_tricks.py
Labels: pull ready

#10221 Prefer `jnp.tile` over `concatenate`
  jax/_src/numpy/lax_numpy.py
  jax/_src/prng.py
Labels: pull ready

#10342 [sparse] fix bug in bcoo_sort_indices batching rule
  jax/experimental/sparse/bcoo.py
Labels: pull ready

#10344 Update the changelog to say sharded_jit is deprecated.
  CHANGELOG.md
Labels: pull ready

#10341 jnp.take: add documentation for mode parameter default
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#10351 Prevent negative output shapes in shape inference for reduce_window.
  jax/core.py
  jax/experimental/jax2tf/shape_poly.py
  tests/lax_test.py
Labels: pull ready

#10296 Fix some straggling name stack bugs
  jax/_src/dispatch.py
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/experimental/maps.py
  jax/interpreters/mlir.py
  tests/jax_to_ir_test.py
  tests/metadata_test.py
Labels: pull ready

#10367 relax requirements on pytrees in custom_jvp
  jax/_src/custom_derivatives.py
  tests/api_test.py
Labels: pull ready

#10364 Add quotes to install commands in README
  README.md
Labels: kokoro:force-run, pull ready

#10298 [sparse] make bcoo_sum_duplicates a primitive
  jax/experimental/sparse/__init__.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/random.py
  tests/sparse_test.py
Labels: pull ready

#10362 [fix: typing] Explicitly rexport `KeyArray` in `jax.random`
  jax/random.py
Labels: pull ready

#10368 Add an optional mode= argument to jnp.take_along_axis.
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#10358 Checkify: support checks on data-independent values.
  jax/_src/checkify.py
  jax/core.py
  tests/checkify_test.py
Labels: pull ready

#10385 Add comment explaining implementation in promote_types
  jax/_src/dtypes.py
Labels: pull ready

#10377 DOC: lax.linalg.eigh
  jax/_src/lax/linalg.py
Labels: pull ready

#10379 Use lax.broadcasted_iota in jax.nn.one_hot.
  jax/_src/nn/functions.py
Labels: pull ready

#10381 remove numpy.linalg._promote_arg_dtypes
  jax/_src/numpy/linalg.py
  jax/_src/scipy/linalg.py
Labels: pull ready

#10387 Fix typo of #10381
  jax/_src/scipy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#10392 remove lax._device_put_raw
  jax/_src/lax/control_flow.py
  jax/_src/lax/lax.py
  jax/experimental/jax2tf/call_tf.py
  tests/lax_test.py
Labels: pull ready

#10150 Avoid normalization of unsigned indices
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#10389 Deprecate remaining functionality in jax.test_util
  CHANGELOG.md
  jax/test_util.py
Labels: pull ready

#10408 Apply flake8 checks to xmap_test.py
  tests/xmap_test.py
Labels: pull ready

#10402 always lower/compile on the AOT jit path
  jax/_src/api.py
  jax/_src/dispatch.py
  jax/experimental/maps.py
  tests/api_test.py
Labels: pull ready

#10407 CHANGELOG: update test_util deprecation discussion
  CHANGELOG.md
Labels: pull ready

#10383 implement scipy.cluster.vq.vq
  CHANGELOG.md
  jax/_src/scipy/cluster/vq.py
  jax/scipy/__init__.py
  jax/scipy/cluster/__init__.py
  jax/scipy/cluster/vq.py
  tests/lax_scipy_test.py
Labels: pull ready

#10417 Fix typo in _scatter_add_lower_gpu
  jax/_src/lax/slicing.py
  tests/lax_test.py
Labels: pull ready

#10204 Use `lax.iota` also for `jnp.arange(0, stop)`
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#10428 remove old cond todos
  jax/_src/lax/control_flow.py
Labels: pull ready

#10431 [remove units] add partial_eval_jaxpr_nounits
  jax/interpreters/partial_eval.py
Labels: pull ready

#10432 [remove units] remove units from cond partial eval
  jax/_src/abstract_arrays.py
  jax/_src/lax/control_flow.py
  jax/_src/lax/lax.py
  jax/interpreters/partial_eval.py
Labels: pull ready

#10433 [remove units] remove units from while_loop partial eval
  jax/_src/lax/control_flow.py
  tests/lax_control_flow_test.py
Labels: pull ready

#10397 replace int with operator.index for numpy
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#10423 DOC: link to install instructions in HTML docs
  docs/index.rst
  docs/installation.rst
Labels: pull ready

#10439 compile_or_get_cached() is now more type-checker friendly
  jax/_src/dispatch.py
Labels: pull ready

#10441 Add missing __init__ file in jax._src.scipy.cluster
  jax/_src/scipy/cluster/__init__.py
Labels: pull ready

#10443 [sparse] improve error messages for unimplemented primitives
  jax/experimental/sparse/transform.py
  tests/sparsify_test.py
Labels: pull ready

#7772 Add unary xeinsum & allow named axis reductions for unary/binary xeinsums
  jax/_src/lax/parallel.py
  jax/_src/numpy/lax_numpy.py
  tests/xmap_test.py
Labels: cla: yes, pull ready

#10448 [remove-units] prevent scan partial eval from introducing units
  jax/_src/lax/control_flow.py
  jax/interpreters/partial_eval.py
Labels: pull ready

#10452 jax.scipy.qr: fix return type for mode='r'
  CHANGELOG.md
  jax/_src/scipy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#10453 [remove-units] remove units from argnums/argnames_partial
  jax/_src/ad_util.py
  jax/_src/api_util.py
  jax/interpreters/partial_eval.py
Labels: pull ready

#10455 [remove-units] prevent ad.py from introducing units
  jax/_src/api.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/interpreters/ad.py
  jax/interpreters/partial_eval.py
Labels: pull ready

#10459 [remove-units] roll forward #10448, fix dce bug
  jax/_src/lax/control_flow.py
  jax/interpreters/partial_eval.py
Labels: pull ready

#10419 try to improve docs for scipy.linalg with unused parameters
  jax/_src/scipy/linalg.py
Labels: pull ready

#10454 [sparse] bcoo_broadcast_in_dim: default to adding leading batch dimensions
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: pull ready

#10468 [remove-units] prevent remat's partial eval from introducing units
  jax/core.py
  jax/interpreters/ad.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: pull ready

#10469 [remove-units] prevent pjit partial eval from dealing with units
  jax/experimental/pjit.py
Labels: pull ready

#8554 add scan dce rule
  jax/_src/lax/control_flow.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: cla: yes, pull ready

#10466 [sparse] implement sparse rule for lax.concatenate_p
  jax/experimental/sparse/__init__.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/transform.py
  tests/sparse_test.py
  tests/sparsify_test.py
Labels: pull ready

#10484 fix redundant (harmless) axis env extension in pmap partial eval
  jax/interpreters/partial_eval.py
  tests/pmap_test.py
Labels: pull ready

#10482 Compatible with RngBitGeneratorOp builder modifications
  jax/_src/lax/lax.py
Labels: pull ready

#10483 [remove-units] avoid making xmap partial eval deal with units
  jax/experimental/maps.py
  jax/interpreters/partial_eval.py
Labels: pull ready

#10497 fix scan dce rule
  jax/_src/lax/control_flow.py
  tests/api_test.py
Labels: pull ready

#10495 Make lax.linalg.qr robust to zero-dimensional inputs
  jax/_src/lax/linalg.py
  tests/linalg_test.py
Labels: pull ready

#10500 dtypes.result_type: add optional return_weak_type_flag argument
  jax/_src/dtypes.py
  tests/dtypes_test.py
Labels: pull ready

#10501 [remove-units] remove partial_eval_jaxpr (no callers!)
  jax/interpreters/partial_eval.py
Labels: pull ready

#10458 Added random.orthogonal and random.unitary.
  CHANGELOG.md
  docs/jax.random.rst
  jax/_src/random.py
  jax/random.py
  tests/random_test.py
Labels: pull ready

#10505 [remove-units] remove units from custom_jvp/vjp
  jax/interpreters/partial_eval.py
Labels: pull ready

#10502 docs: pin myst-nb to 0.13.2
  docs/requirements.txt
Labels: pull ready

#10506 [remove-units] remove now-dead flax helper function
  jax/interpreters/partial_eval.py
Labels: pull ready

#10507 [remove-units] avoid units in new remat
  jax/_src/ad_checkpoint.py
Labels: pull ready

#10508 [remove-units] avoid unit-generating function in lax.reduce
  jax/_src/lax/lax.py
Labels: pull ready

#10509 [remove-units] avoid unit-generating function in jax.linear_transpose
  jax/_src/api.py
Labels: pull ready

#10512 update version and changelog for pypi
  CHANGELOG.md
  jax/version.py
Labels: pull ready

#10488 [sparse] display n_batch & n_dense in BCOO repr
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: pull ready
