Repository jax-ml/jax, pull requests merged in 2022-03, with the labels that each got.

#9724 Factor-out pieces of lax_numpy.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/ndarray.py
  jax/_src/numpy/ufuncs.py
  jax/_src/numpy/util.py
Labels: pull ready

#9732 implement jnp.copy
  docs/jax.numpy.rst
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.py
  tests/lax_numpy_test.py
Labels: pull ready

#9736 add regression test for #9731
  tests/lax_control_flow_test.py
Labels: pull ready

#9737 cleanup: remove _constant_like in favor of lax._const
  jax/_src/lax/linalg.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/random.py
  jax/_src/scipy/special.py
  jax/_src/scipy/stats/bernoulli.py
  jax/_src/scipy/stats/beta.py
  jax/_src/scipy/stats/betabinom.py
  jax/_src/scipy/stats/cauchy.py
  jax/_src/scipy/stats/chi2.py
  jax/_src/scipy/stats/dirichlet.py
  jax/_src/scipy/stats/gamma.py
  jax/_src/scipy/stats/geom.py
  jax/_src/scipy/stats/laplace.py
  jax/_src/scipy/stats/nbinom.py
  jax/_src/scipy/stats/norm.py
  jax/_src/scipy/stats/pareto.py
  jax/_src/scipy/stats/poisson.py
  jax/_src/scipy/stats/t.py
Labels: pull ready

#9750 jnp.unravel_index: simplify return statement
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#9546 Include `experimental.jet` into docs
  docs/jax.experimental.jet.rst
  docs/jax.experimental.rst
  jax/experimental/jet.py
Labels: pull ready

#9584 Update JAX to use new math libraries in ROCm-5.0.
  build/BUILD.bazel
  build/build.py
  build/build_wheel.py
  build/rocm/Dockerfile.rocm
  build/rocm/README.md
  build/rocm/build_common.sh
  build/rocm/build_rocm.sh
  build/rocm/ci_build.sh
  build/rocm/run_multi_gpu.sh
  build/rocm/run_single_gpu.py
  jax/_src/lax/linalg.py
  jax/_src/lib/__init__.py
  jax/_src/prng.py
  jax/experimental/sparse/api.py
  jax/experimental/sparse/coo.py
  jax/experimental/sparse/csr.py
  jaxlib/BUILD
  jaxlib/hip_gpu_kernel_helpers.cc
  jaxlib/hip_gpu_kernel_helpers.h
  jaxlib/hip_linalg.cc
  jaxlib/hip_linalg.py
  jaxlib/hip_lu_pivot_kernels.cc
  jaxlib/hip_lu_pivot_kernels.h
  jaxlib/hip_lu_pivot_kernels.hip.cc
  jaxlib/hip_prng.cc
  jaxlib/hip_prng.py
  jaxlib/hip_prng_kernels.cc
  jaxlib/hip_prng_kernels.h
  jaxlib/hip_prng_kernels.hip.cc
  jaxlib/hipblas.cc
  jaxlib/hipblas_kernels.cc
  jaxlib/hipblas_kernels.h
  jaxlib/hipsolver.cc
  jaxlib/hipsolver.py
  jaxlib/hipsolver_kernels.cc
  jaxlib/hipsolver_kernels.h
  jaxlib/hipsparse.cc
  jaxlib/hipsparse.py
  jaxlib/hipsparse_kernels.cc
  jaxlib/hipsparse_kernels.h
  jaxlib/jax.bzl
  jaxlib/rocblas.cc
  jaxlib/rocm_gpu_kernel_helpers.cc
  jaxlib/rocm_gpu_kernel_helpers.h
  jaxlib/rocsolver.py
  tests/custom_linear_solve_test.py
  tests/fft_test.py
  tests/host_callback_test.py
  tests/lax_numpy_test.py
  tests/lax_scipy_test.py
  tests/linalg_test.py
  tests/multi_device_test.py
  tests/qdwh_test.py
  tests/random_test.py
  tests/scipy_fft_test.py
  tests/scipy_signal_test.py
  tests/sparse_test.py
  tests/svd_test.py
Labels: pull ready

#9763 Fix the display of GDA docs
  docs/jax.experimental.global_device_array.rst
Labels: pull ready

#9622 Add an API compatibility policy.
  docs/api_compatibility.md
  docs/index.rst
Labels: pull ready

#9772 custom_prng: better error messages for key validation
  jax/_src/prng.py
Labels: pull ready

#9768 Increase minimum jaxlib version to 0.3.0.
  jax/_src/lax/control_flow.py
  jax/_src/lax/lax.py
  jax/_src/source_info_util.py
  jax/_src/traceback_util.py
  jax/interpreters/pxla.py
  jax/jaxpr_util.py
  jax/version.py
  tests/api_test.py
  tests/errors_test.py
  tests/jaxpr_util_test.py
  tests/pjit_test.py
  tests/pmap_test.py
  tests/tree_util_test.py
Labels: pull ready

#9746 Call _check_arraylike on inputs to broadcast_to and broadcast_arrays
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#9765 Convert to GDA docstring to doctest
  jax/experimental/global_device_array.py
Labels: pull ready

#9576 Validate `lax.broadcast_shape` inputs before control flow execution
  jax/_src/lax/lax.py
  tests/lax_vmap_test.py
Labels: pull ready

#9664 `custom_transpose` without staging
  jax/_src/api.py
  jax/_src/custom_transpose.py
  jax/core.py
  jax/interpreters/ad.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: pull ready

#9207 [sparse] change call signature of coo primitive wrappers
  jax/experimental/sparse/coo.py
  jax/experimental/sparse/csr.py
  tests/sparse_test.py
Labels: pull ready

#9787 [sparse] refactor internal implementation of sparsify transform
  jax/experimental/sparse/transform.py
  tests/sparsify_test.py
Labels: pull ready

#9783 Remove pjit warning.
  jax/experimental/pjit.py
Labels: pull ready

#9788 Document jax.nn.initializers.
  docs/jax.nn.initializers.rst
  jax/_src/nn/initializers.py
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#9785 remove `_const` from public `jax.lax` module
  jax/_src/lax/linalg.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/linalg.py
  jax/_src/prng.py
  jax/_src/random.py
  jax/_src/scipy/special.py
  jax/_src/scipy/stats/bernoulli.py
  jax/_src/scipy/stats/beta.py
  jax/_src/scipy/stats/betabinom.py
  jax/_src/scipy/stats/cauchy.py
  jax/_src/scipy/stats/chi2.py
  jax/_src/scipy/stats/dirichlet.py
  jax/_src/scipy/stats/gamma.py
  jax/_src/scipy/stats/geom.py
  jax/_src/scipy/stats/laplace.py
  jax/_src/scipy/stats/nbinom.py
  jax/_src/scipy/stats/norm.py
  jax/_src/scipy/stats/pareto.py
  jax/_src/scipy/stats/poisson.py
  jax/_src/scipy/stats/t.py
  jax/experimental/jet.py
  jax/lax/__init__.py
  tests/lax_test.py
Labels: pull ready

#9786 improve batch_jaxpr caching from #9196
  jax/interpreters/batching.py
Labels: pull ready

#9794 Fix arxiv reference for He initializers.
  jax/_src/nn/initializers.py
Labels: pull ready

#9798 Skip doctests for initializer examples.
  jax/_src/nn/initializers.py
Labels: pull ready

#9801 Update XLA.
  WORKSPACE
Labels: pull ready

#9774 Fix bug in jax.test_util._dtype
  jax/_src/test_util.py
Labels: pull ready

#9789 [sparse]: COO: check for sorted rows before cusparse lowering
  jax/experimental/sparse/coo.py
  tests/sparse_test.py
Labels: pull ready

#9800 Documentation improvements.
  docs/jax.example_libraries.rst
  docs/jax.image.rst
  jax/_src/dlpack.py
  jax/_src/flatten_util.py
  jax/_src/image/scale.py
  jax/_src/nn/functions.py
  jax/example_libraries/optimizers.py
  jax/example_libraries/stax.py
  jax/image/__init__.py
Labels: pull ready

#9805 remove internal functions from public `jax.lax` module
  jax/_src/api.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/prng.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  jax/experimental/jet.py
  jax/lax/__init__.py
  tests/core_test.py
  tests/filecheck/array.filecheck.py
  tests/lax_test.py
Labels: pull ready

#9807 [sparse] track sorted columns in COO
  jax/experimental/sparse/coo.py
  tests/sparse_test.py
Labels: pull ready

#9814 Add @jit decorators to functions in jax.nn.
  jax/_src/nn/functions.py
Labels: pull ready

#9820 Refactor Jaxpr pretty-printing to use a `JaxprPpSettings` named tuple
  jax/_src/lax/lax.py
  jax/core.py
  jax/experimental/djax.py
  jax/interpreters/partial_eval.py
  jax/interpreters/xla.py
Labels: pull ready

#9829 Suggest eigh() in the eig() not implemented error.
  jax/_src/lax/linalg.py
  jax/_src/numpy/linalg.py
Labels: pull ready

#9831 Speed up compilation time of segment_sum() operators with bucketing e…
  jax/_src/ops/scatter.py
Labels: kokoro:force-run, pull ready

#9826 remove remaining internal functions from public `jax.lax` module
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/linalg.py
  jax/_src/ops/scatter.py
  jax/_src/scipy/sparse/linalg.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/lax/__init__.py
  tests/dtypes_test.py
  tests/lax_numpy_indexing_test.py
  tests/lax_numpy_test.py
  tests/lax_test.py
  tests/lax_vmap_test.py
Labels: pull ready

#9838 Fix core.pytype_aval_mappings for _DeviceArray
  jax/_src/device_array.py
Labels: pull ready

#9842 Update jaxlib version to 0.3.2 to match jax
  jaxlib/version.py
Labels: pull ready

#9853 fixup from 5415306: remove extraneous lines
  jax/_src/lax/windowed_reductions.py
  tests/lax_vmap_test.py
Labels: pull ready

#9877 Update WORKSPACE for jaxlib 0.3.2, take 2
  WORKSPACE
Labels: pull ready

#9815 Fix fft dtype for norm='ortho'
  jax/_src/numpy/fft.py
  tests/fft_test.py
Labels: pull ready

#9889 segment_max: fix identity for boolean dtype
  jax/_src/ops/scatter.py
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#9890 DOC: add missing linalg functionality to docs
  docs/jax.lax.rst
  docs/jax.scipy.rst
  jax/_src/lax/linalg.py
Labels: pull ready

#9901 jnp.unique: avoid constructing arrays with explicit int64
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#9905 Add TPU v4 support to cloud_tpu_init
  jax/_src/cloud_tpu_init.py
Labels: pull ready

#9909 improvements to autodidax reduce_sum
  docs/autodidax.ipynb
  docs/autodidax.md
  docs/autodidax.py
Labels: pull ready

#9920 Update CHANGELOG and setup.py for jax + jaxlib 0.3.2 releases
  CHANGELOG.md
  setup.py
Labels: pull ready

#9921 Bump jax and jaxlib versions for 0.3.2 release
  CHANGELOG.md
  jax/version.py
  jaxlib/version.py
  setup.py
Labels: kokoro:force-run, pull ready

#9908 staging and compilation for `custom_transpose`
  jax/_src/custom_transpose.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: pull ready

#9924 fix #9823
  jax/core.py
Labels: pull ready

#9923 revise internal helper _is_perturbed to _maybe_perturbed, fix logic
  jax/_src/custom_derivatives.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#9891 [shape_poly] Improve error message and docs for shape polynomials used as JAX values
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#9938 DOC: more info on disable_jit
  jax/_src/api.py
Labels: pull ready

#9925 lax_numpy: factor indexing tricks into separate submodule
  jax/_src/numpy/index_tricks.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/ops/scatter.py
  jax/_src/scipy/special.py
  jax/numpy/__init__.py
Labels: pull ready

#9943 lax_numpy refactoring: directly import ufuncs
  jax/numpy/__init__.py
Labels: pull ready

#9944 lax_numpy: move poly functions into numpy.polynomial
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/polynomial.py
  jax/numpy/__init__.py
Labels: pull ready

#9942 jax.nn.glu: fix static argname issue
  jax/_src/nn/functions.py
  tests/nn_test.py
Labels: pull ready

#9947 update version and changelog for pypi
  CHANGELOG.md
  jax/version.py
Labels: pull ready

#9948 mark `xmap` as an API boundary
  jax/experimental/maps.py
Labels: pull ready

#9950 introduce a protocol for compilation wrappers
  jax/_src/api.py
  jax/_src/stages.py
  jax/experimental/maps.py
  jax/experimental/pjit.py
  jax/stages.py
Labels: pull ready

#9955 Add `itemsize` property to JAX arrays
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#9959 fix typo in #9923
  jax/_src/custom_derivatives.py
  tests/api_test.py
Labels: pull ready

#9962 update version and changelog for pypi
  CHANGELOG.md
  jax/version.py
Labels: pull ready

#9738 Factor-out reductions from lax_numpy.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/reductions.py
  jax/numpy/__init__.py
Labels: pull ready

#9964 [sparse] bcoo_mul: support mixing batch & sparse dims
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: pull ready

#9978 quickstart: fix outdated TPU reference
  docs/notebooks/quickstart.ipynb
  docs/notebooks/quickstart.md
Labels: pull ready

#9906 add random.loggamma and improve dirichlet & beta implementation
  CHANGELOG.md
  docs/jax.random.rst
  jax/_src/random.py
  jax/random.py
  tests/random_test.py
Labels: pull ready

#9971 Fix hessian logic
  jax/_src/api.py
  tests/api_test.py
Labels: pull ready

#9967 track input argument information in one tree at each AOT stage
  jax/_src/api.py
  jax/_src/stages.py
  jax/experimental/maps.py
  jax/experimental/pjit.py
Labels: pull ready

#9984 [sparse] add missing bcoo exports
  jax/experimental/sparse/__init__.py
Labels: pull ready

#9869 Experiment: add PDF export to readthedocs build
  .readthedocs.yml
Labels: pull ready

#9987 readthedocs: do not attempt to build PDF
  .readthedocs.yml
Labels: pull ready

#9992 Fix breakage due to LLVM change
  jax/interpreters/mlir.py
Labels: pull ready

#9995 fix jaxpr pretty-printing with unitvars
  jax/core.py
  tests/api_test.py
Labels: pull ready

#9998 protocols for the lowering and executable underlying `Lowered` and `Compiled`
  jax/_src/dispatch.py
  jax/_src/stages.py
  jax/interpreters/pxla.py
Labels: pull ready

#9996 avoid batching units in cond partial eval
  jax/_src/lax/control_flow.py
  jax/interpreters/batching.py
  tests/lax_control_flow_test.py
Labels: pull ready

#10001 remove unreachable code in `Lowered`
  jax/_src/stages.py
Labels: pull ready

#10012 Remove unused code
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#10009 DOC: add caveats to jnp.ndarray.astype
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#9919 random: add values test cases for various distributions
  tests/random_test.py
Labels: pull ready

#10010 DOC: clarify parameter types in cg/bicgstab
  jax/_src/scipy/sparse/linalg.py
Labels: documentation, pull ready

#10013 Rewrite __module__ attribute of jnp dtype-like objects
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#9966 Add weakreaf_lru_cache to prevent caches from pinning jaxprs.
  jax/_src/util.py
  jax/core.py
  jax/experimental/pjit.py
  jax/interpreters/partial_eval.py
Labels: pull ready

#10000 add jaxpr check in `partial_eval.trace_to_subjaxpr_dynamic`
  jax/interpreters/partial_eval.py
  tests/core_test.py
Labels: pull ready

#9968 Rename jax.nn.normalize to standardize. Add normalize alias with DeprecationWarning
  CHANGELOG.md
  jax/_src/nn/functions.py
  jax/example_libraries/stax.py
  jax/nn/__init__.py
  tests/nn_test.py
Labels: pull ready

#10020 maint: remove numpy reductions dependence on ufuncs
  jax/_src/numpy/reductions.py
Labels: pull ready

#10026 remove dead code
  jax/interpreters/partial_eval.py
Labels: pull ready

#9986 Fix for hipsparse in ROCm.
  jax/_src/lax/linalg.py
  jax/_src/lib/__init__.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/coo.py
  jax/experimental/sparse/csr.py
  tests/sparse_test.py
Labels: pull ready

#9766 [Doc] Add jaxlib build instructions for TPU
  docs/developer.md
Labels: pull ready

#10019 Add a documentation for the JAX transfer guard
  docs/index.rst
  docs/jax.config.rst
  docs/transfer_guard.rst
Labels: pull ready

#10029 Remove lax_numpy from jax.numpy namespace
  CHANGELOG.md
  jax/numpy/__init__.py
Labels: pull ready

#10034 improve caching of jax.remat
  jax/core.py
  jax/experimental/maps.py
  tests/api_test.py
Labels: pull ready

#10037 improve remat transpose caching (cf. #9661)
  jax/interpreters/ad.py
  tests/api_test.py
Labels: pull ready

#10041 retry #10038 (allow recursive uses of `custom_transpose`)
  jax/_src/custom_transpose.py
  jax/_src/lax/control_flow.py
  jax/interpreters/ad.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: pull ready

#10033 Checkify: add way to embed runtime info in error messages.
  jax/experimental/checkify/checkify_impl.py
  tests/checkify_test.py
Labels: pull ready

#10043 [shape_poly] Change internal representation of parametric shapes
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#10042 Fix a bug in fft helper appears when nperseg=1.
  jax/_src/scipy/signal.py
  tests/scipy_signal_test.py
Labels: pull ready

#10053 remove unused arg in call param jvp updater
  jax/interpreters/ad.py
  jax/interpreters/xla.py
Labels: pull ready

#10048 custom VJP by custom JVP and transpose
  jax/_src/config.py
  jax/_src/custom_derivatives.py
  jax/experimental/jax2tf/jax2tf.py
Labels: pull ready

#10054 add `custom_vjp` upgrade flag to `jax` module and fix doc rendering
  docs/jax.config.rst
  jax/__init__.py
  jax/_src/config.py
Labels: pull ready

#10064 [doc] Fix typo
  jax/_src/lax/lax.py
Labels: pull ready

#10049 Implement jnp.from* array creation functions
  CHANGELOG.md
  docs/jax.numpy.rst
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.py
  tests/lax_numpy_test.py
Labels: pull ready

#9369 require consistent output structure in custom vmap rules
  jax/_src/custom_batching.py
  tests/api_test.py
Labels: pull ready

#10068 Add note about enabling developer mode on Windows.
  docs/developer.md
Labels: pull ready

#10074 doc: add examples of using partial with jit
  docs/jax-101/02-jitting.ipynb
  docs/jax-101/02-jitting.md
  jax/_src/api.py
Labels: pull ready

#9689 Return consistent results for image.scale_and_translate with negative dims
  jax/_src/image/scale.py
  tests/image_test.py
Labels: pull ready

#9645 Update README.md to fix link to prng.md
  README.md
Labels: pull ready

#10069 make device_array.copy() return a device array
  jax/_src/api.py
  jax/_src/device_array.py
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#10073 docs: use intersphinx links for wrapped functions
  jax/_src/numpy/util.py
Labels: pull ready

#10087 Fixed a typo in the return type of _array_ir_types
  jax/interpreters/mlir.py
Labels: pull ready

#10090 Fix link to buffer-donation docs
  jax/interpreters/mlir.py
  jax/interpreters/xla.py
Labels: pull ready

#10091 Bump tensorflow version to 0dfdb8
  WORKSPACE
Labels: pull ready

#10095 Share compare_mhlo function between lax.py and mlir.py.
  jax/_src/lax/lax.py
  jax/interpreters/mlir.py
Labels: pull ready

#10096 Suppressed a few more errors in jax/interpreters/mlir.py
  jax/interpreters/mlir.py
  jax/interpreters/pxla.py
Labels: pull ready

#10101 Upgrade ROCm build docker to ROCm version 5.1.
  build/rocm/Dockerfile.rocm
Labels: pull ready

#10089 Remove redundant name-stack setting in `DynamicJaxprTrace`
  jax/interpreters/partial_eval.py
Labels: pull ready

#10102 [host_callback] Fix tests to ensure we use the correct platform
  tests/host_callback_test.py
Labels: pull ready

#10092 Sharp bits: add miscellaneous divergences from numpy
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
Labels: pull ready
