Repository jax-ml/jax, pull requests merged in 2023-09, with the labels that each got.

#17420 Remove stale references to //jaxlib:setup.cfg in Bazel build.
  jaxlib/BUILD
  jaxlib/tools/BUILD.bazel
Labels: pull ready

#17437 Fix Windows build failure.
  jaxlib/kernel_nanobind_helpers.h
Labels: pull ready

#16736 Lower jax.numpy matmul functions to mixed-precision dot_general
  jax/_src/numpy/lax_numpy.py
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: pull ready

#17446 CI: pin actions/checkout to v4
  .github/workflows/README.md
  .github/workflows/ci-build.yaml
  .github/workflows/cloud-tpu-ci-nightly.yml
  .github/workflows/nightly-ci-multiprocess-gpu.yml
  .github/workflows/upstream-nightly.yaml
  .github/workflows/wheel_win_x64.yml
  .github/workflows/windows_ci.yml
Labels: pull ready

#17406 Bug: support NamedTuples in deferring binary ops
  jax/_src/numpy/array_methods.py
  tests/lax_numpy_operators_test.py
Labels: pull ready

#17314 fix(pallas): flash attention tiled iteration upper bound too small when `block_q > block_k`
  jax/experimental/pallas/ops/attention.py
  tests/pallas/pallas_test.py
Labels: pull ready

#17453 build: write appropriate version strings to build artifacts
  jax/_src/test_util.py
  jax/version.py
  jaxlib/setup.py
  pyproject.toml
  setup.py
  tests/version_test.py
Labels: pull ready

#17491 Add a release note about a fixed Windows crash.
  CHANGELOG.md
Labels: pull ready

#17489 Update README to remove Haiku
  README.md
Labels: pull ready

#17501 Internal: add dtypes.safe_to_cast utility & use to generate indexing warning
  jax/_src/dtypes.py
  jax/_src/ops/scatter.py
  tests/dtypes_test.py
Labels: pull ready

#17505 Fix Bazel build failures from long command lines on Windows.
  .bazelrc
Labels: pull ready

#17506 jax.numpy: add preferred_element_type argument to matmul functions
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#17511 Fix dlpack type signatures to match Array API spec.
  jax/_src/array.py
  jax/_src/dlpack.py
Labels: kokoro:force-run, pull ready

#17515 jax.dtypes: fix dtypes.safe_to_cast() when output dtype is weak
  jax/_src/dtypes.py
  tests/dtypes_test.py
Labels: pull ready

#17519 Build: catch stderr when attempting git commands
  jax/version.py
Labels: pull ready

#17521 Add more extensive tests for version strings
  tests/version_test.py
Labels: pull ready

#17520 Add -lm to Linux flatbuffer builds.
  third_party/flatbuffers/flatbuffers.patch
Labels: pull ready

#17527 ROCm Build Updates
  build/rocm/Dockerfile.ms
  build/rocm/ci_build.sh
  jaxlib/rocm/BUILD.bazel
Labels: pull ready

#17524 Add missing preferred_element_type tests
  jax/_src/numpy/lax_numpy.py
  jax/_src/test_util.py
  tests/lax_numpy_test.py
Labels: pull ready

#17562 Import jax.version first
  jax/__init__.py
Labels: kokoro:force-run, pull ready

#17565 [typing] fix a few array type declarations
  jax/_src/basearray.pyi
  jax/_src/numpy/array_methods.py
Labels: kokoro:force-run, pull ready

#17566 [custom prng] make PRNGKeyArray a subclass of jax.Array
  jax/_src/prng.py
Labels: pull ready

#17568 Fix testDotGeneral() nightly failure on A100
  tests/batching_test.py
Labels: pull ready

#17564 Increase comparison tolerance in SciPy spatial RotationMean subtest
  tests/scipy_spatial_test.py
Labels: pull ready

#17584 fix typos in README.md
  README.md
Labels: pull ready

#17594 Deprecate random.KeyArray and random.PRNGKeyArray
  CHANGELOG.md
  jax/_src/nn/initializers.py
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
  jax/random.py
  tests/pjit_test.py
  tests/random_test.py
Labels: pull ready

#17593 Test changes for out-of-tree backend.
  jax/_src/test_util.py
  tests/aot_test.py
  tests/api_test.py
  tests/array_interoperability_test.py
  tests/array_test.py
  tests/checkify_test.py
  tests/debugger_test.py
  tests/experimental_rnn_test.py
  tests/pjit_test.py
  tests/python_callback_test.py
  tests/shard_map_test.py
  tests/xmap_test.py
Labels: pull ready

#17617 jnp.inner: add preferred_element_type argument
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#17651 move `wrap_key_data` to `jax.random`
  docs/jax.extend.rst
  docs/jax.random.rst
  jax/_src/extend/random.py
  jax/_src/random.py
  jax/extend/random.py
  jax/random.py
  tests/extend_test.py
  tests/random_test.py
Labels: pull ready

#17665 CI: update package versions for mypy pre-commit
  .pre-commit-config.yaml
Labels: pull ready

#17650 Better errors for array conversion to bool, int, float, complex, hex, oct, & index
  jax/_src/array.py
  jax/_src/core.py
  tests/api_test.py
Labels: pull ready

#17653 Run LSTM test using FP32 math
  jax/experimental/rnn.py
  jaxlib/gpu/rnn.cc
  jaxlib/gpu/rnn_kernels.cc
  jaxlib/gpu/rnn_kernels.h
  jaxlib/gpu_rnn.py
  tests/experimental_rnn_test.py
Labels: pull ready

#17668 Avoid references to symbols removed in numpy 2.0
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#17666 JEX: add jex.abstract_arrays.array_types
  jax/extend/__init__.py
  jax/extend/core.py
  tests/extend_test.py
Labels: pull ready

#17669 Use float32 for testNestedMap and testPdotBatching in XMapTest
  tests/xmap_test.py
Labels: pull ready

#17671 Remove deprecated submodule jax.abstract_arrays
  CHANGELOG.md
  jax/__init__.py
  jax/abstract_arrays.py
Labels: pull ready

#17674 Add Python 3.12.0-rc.3 to the Windows wheel releases.
  .github/workflows/wheel_win_x64.yml
Labels: pull ready

#17679 DOC: remove redundant backticks in pjit tutorial stub
  docs/jax-101/08-pjit.rst
Labels: pull ready

#17681 Fix test breakage in RNN test with old jaxlibs.
  jax/experimental/rnn.py
  tests/experimental_rnn_test.py
Labels: pull ready

#17297 JEP 9263: Typed keys & pluggable RNGs
  docs/_static/style.css
  docs/jep/9263-typed-keys.md
  docs/jep/index.rst
Labels: pull ready, JEP

#17685 Tests: fix some failures for upstream numpy
  tests/lax_numpy_test.py
  tests/lax_test.py
Labels: kokoro:force-run, pull ready

#17684 Fix pyright complaining about jnp.{linalg,fft} not existing.
  jax/numpy/__init__.pyi
Labels: pull ready

#17711 Fix some numpy 2.0 incompatibilities
  jax/_src/lax/lax.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/reductions.py
  tests/dtypes_test.py
  tests/stax_test.py
Labels: pull ready

#17698 [chore] Fix typo in CHANGELOG.md
  CHANGELOG.md
Labels: pull ready

#17692 [typing] better annotations for jnp.ufunc
  jax/_src/numpy/ufunc_api.py
  jax/_src/util.py
Labels: pull ready

#17710 dtypes: make issubdtype(dt, np.generic) work for custom types
  jax/_src/dtypes.py
  tests/dtypes_test.py
Labels: pull ready

#17700 [export] Handle dead input variables in presence of ordered effects
  jax/experimental/export/export.py
  jax/experimental/jax2tf/tests/call_tf_test.py
Labels: pull ready

#17720 MAINT Use a generator expression in tuple([... for ... in ...])
  jax/_src/core.py
  jax/_src/interpreters/batching.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/lax.py
  jax/_src/pallas/mosaic/lowering.py
  jax/_src/scipy/fft.py
  jax/_src/state/discharge.py
  jax/experimental/jax2tf/impl_no_xla.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/transform.py
  tests/state_test.py
Labels: pull ready

#17719 [random] deprecate named key creation functions
  CHANGELOG.md
  jax/_src/random.py
  jax/random.py
  tests/random_test.py
Labels: pull ready

#17709 dtypes.issubdtype: validate a when b is dtypes.extended
  CHANGELOG.md
  jax/_src/dtypes.py
  jax/random.py
  tests/dtypes_test.py
  tests/random_test.py
Labels: pull ready

#17724 Added `serial_dot_products` benchmark
  benchmarks/api_benchmark.py
Labels: pull ready

#17725 [Pallas] Fix out_specs in Pallas quickstart
  docs/pallas/quickstart.ipynb
  docs/pallas/quickstart.md
Labels: pull ready

#17659 [jax2tf] Fix higher-order differentiation.
  jax/experimental/export/export.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/call_tf_test.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/sharding_test.py
  tests/export_test.py
Labels: pull ready

#17713 DOC: reorganize jax.random API listing
  docs/jax.random.rst
Labels: pull ready

#17425 chore(test, pallas): fix deprecated shuffle in pallas test
  tests/pallas/pallas_test.py
Labels: pull ready

#17740 issubdtype: fix corner cases with extended dtypes
  jax/_src/dtypes.py
  tests/dtypes_test.py
  tests/random_test.py
Labels: pull ready

#17739 Improve behavior of core.valid_jaxtype
  jax/_src/core.py
  tests/api_test.py
  tests/core_test.py
Labels: pull ready

#17687 Deprecate non-array inputs to several jax.numpy functions
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
Labels: pull ready

#17746 Fix typos across the package
  docs/faq.rst
  docs/jax-101/01-jax-basics.ipynb
  docs/jax-101/01-jax-basics.md
  docs/jax-101/05.1-pytrees.ipynb
  docs/jax-101/05.1-pytrees.md
  docs/jep/12049-type-annotations.md
  docs/jep/17111-shmap-transpose.md
  docs/jep/9407-type-promotion.ipynb
  docs/jep/9407-type-promotion.md
  docs/notebooks/autodiff_remat.ipynb
  docs/notebooks/autodiff_remat.md
  docs/notebooks/convolutions.ipynb
  docs/notebooks/convolutions.md
  docs/notebooks/external_callbacks.ipynb
  docs/notebooks/external_callbacks.md
  docs/pallas/quickstart.ipynb
  docs/pallas/quickstart.md
  docs/pallas/tpu.rst
  jax/_src/cache_key.py
  jax/_src/clusters/cluster.py
  jax/_src/config.py
  jax/_src/custom_derivatives.py
  jax/_src/distributed.py
  jax/_src/errors.py
  jax/_src/interpreters/batching.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/ann.py
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/lax/lax.py
  jax/_src/lax/linalg.py
  jax/_src/lax/special.py
  jax/_src/numpy/array_methods.py
  jax/_src/pjit.py
  jax/_src/profiler.py
  jax/_src/scipy/special.py
  jax/_src/stages.py
  jax/_src/state/discharge.py
  jax/_src/xla_bridge.py
  jax/experimental/array_serialization/serialization.py
  jax/experimental/export/export.py
  jax/experimental/export/shape_poly.py
  jax/experimental/host_callback.py
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/impl_no_xla.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/back_compat_tf_test.py
  jax/experimental/jax2tf/tests/converters.py
  jax/experimental/jax2tf/tests/primitives_test.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  jax/experimental/rnn.py
  jax/experimental/sparse/bcsr.py
  jax/experimental/sparse/linalg.py
  jax/experimental/sparse/random.py
  jax/experimental/sparse/util.py
  jax/version.py
  tests/dtypes_test.py
  tests/shard_map_test.py
Labels: pull ready

#17744 Improve installation instructions.
  README.md
  docs/developer.md
  docs/index.rst
  docs/installation.md
  docs/installation.rst
Labels: pull ready

#17750 Fix test failures under SciPy 1.11 for scipy.stats.mode.
  CHANGELOG.md
  jax/_src/scipy/stats/_core.py
  tests/scipy_stats_test.py
Labels: pull ready

#17757 [export] Add mlir attributes to the platform index and dimension variables
  jax/_src/interpreters/mlir.py
  tests/export_test.py
Labels: pull ready

#17774 Test: adjust tolerances for upstream scipy.minimize
  tests/scipy_optimize_test.py
Labels: pull ready

#17766 [random] add itemsize property to custom PRNG
  jax/_src/prng.py
  tests/random_test.py
Labels: pull ready

#17733 ENH Use {} and () instead of dict() and tuple()
  jax/_src/scipy/optimize/line_search.py
  jax/experimental/host_callback.py
  jax/experimental/jax2tf/call_tf.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_triangular_solve_blas_trsm.py
Labels: pull ready

#17789 jnp.issubdtype: refactor for better performance
  jax/_src/dtypes.py
Labels: kokoro:force-run, pull ready

#17785 Update install instructions for AMD (ROCm) GPUs to point to AMD's doc…
  README.md
  docs/installation.md
Labels: pull ready

#17751 Remove the "No GPU/TPU found" warning
  jax/_src/xla_bridge.py
  tests/api_test.py
  tests/xla_bridge_test.py
Labels: pull ready

#17791 Fix detection of whether a GPU-enabled jaxlib is installed.
  jax/_src/xla_bridge.py
Labels: pull ready

#17795 Fix CI failures from https://github.com/google/jax/pull/17751
  jax/_src/xla_bridge.py
  tests/xla_bridge_test.py
Labels: pull ready

#17796 Update changelog.
  CHANGELOG.md
  setup.py
Labels: pull ready

#17799 Small improvements to build/build.py
  .github/workflows/wheel_win_x64.yml
  build/build.py
  build/test-requirements.txt
Labels: pull ready

#17800 Add missing raise to build.py
  build/build.py
Labels: pull ready

#17808 [Cloud TPU CI] Update job names to be more descriptive and add descri…
  .github/workflows/cloud-tpu-ci-nightly.yml
Labels: pull ready

#17813 Add notes about the new CUDA version restrictions to the changelog an…
  CHANGELOG.md
  docs/installation.md
Labels: pull ready

#17792 jnp.mean: for f16 inputs, accumulate in f32
  jax/_src/numpy/reductions.py
  tests/lax_numpy_reducers_test.py
Labels: pull ready

#17828 Fix incorrect backend allowlist in array_interoperability_test.
  tests/array_interoperability_test.py
Labels: pull ready

#17826 MAINT Reorder the overloads for `lax.sort`
  jax/_src/lax/lax.py
Labels: pull ready

#17827 Introduce a LoweringParameters dataclass for easier plumbing
  jax/_src/api.py
  jax/_src/dispatch.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  jax/_src/maps.py
  jax/_src/pjit.py
  jax/experimental/export/export.py
  jax/interpreters/mlir.py
  tests/api_test.py
  tests/export_test.py
Labels: pull ready

#17860 Bump NumpyLinalgTest.testEighRankDeficient tolerance
  tests/linalg_test.py
Labels: kokoro:force-run, pull ready

#17864 Clean up build_wheel.py and build_gpu_plugin_wheel.py.
  jax/tools/build_utils.py
  jaxlib/tools/build_gpu_plugin_wheel.py
  jaxlib/tools/build_wheel.py
Labels: pull ready
