Repository jax-ml/jax, pull requests merged in 2023-12, with the labels that each got.

#18679 [shape_poly] Simplify the indexing computations to be compatible with shape polymorphism
  jax/_src/numpy/lax_numpy.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  tests/shape_poly_test.py
Labels: pull ready

#18762 [shape_poly] Add heuristics for deciding >= 0
  jax/experimental/export/shape_poly.py
  tests/shape_poly_test.py
Labels: pull ready

#18774 Remove nightly NVIDIA GPU multiprocess CI.
  .github/workflows/cat_slurm_logs.py
  .github/workflows/nightly-ci-multiprocess-gpu.yml
  .github/workflows/slurm_job_scripts/extract_e2e_tests_metrics.py
  .github/workflows/slurm_job_scripts/oci_cluster_manager.py
  .github/workflows/slurm_job_scripts/requirements.txt
  .github/workflows/slurm_job_scripts/run_e2e_t5x_tests.sub
Labels: pull ready

#18757 Add jax.numpy.astype function
  docs/jax.numpy.rst
  jax/_src/numpy/array_methods.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#18783 Fix indexing with slices bug and add tests.
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
  tests/shape_poly_test.py
Labels: pull ready

#18761 [export] Simplify the handling of shardings in Exported.
  jax/_src/internal_test_util/export_back_compat_test_util.py
  jax/experimental/export/export.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/back_compat_test.py
  jax/experimental/jax2tf/tests/back_compat_testdata/tpu_Sharding.py
  jax/experimental/jax2tf/tests/back_compat_tf_test.py
Labels: pull ready

#18786 [export] Improve the testing of exporting with effects
  tests/export_test.py
Labels: pull ready

#18794 Use qualified Python names in metadata if available
  jax/_src/source_info_util.py
Labels: pull ready

#18795 [export] Add and fix a test for exporting higher-order gradients with sharding
  jax/_src/pjit.py
  jax/experimental/jax2tf/tests/sharding_test.py
  tests/export_test.py
Labels: pull ready

#18809 Test: fix casting warning in betainc test
  jax/_src/internal_test_util/lax_test_util.py
  tests/lax_test.py
Labels: pull ready

#18818 Fix indexing with slices when the slice elements are jax.Array.
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#18739 CI: add more pre-commit checks
  .pre-commit-config.yaml
Labels: pull ready

#18676 JAX docs tutorial: Autodiff 101
  docs/tutorials/advanced-autodiff.md
  docs/tutorials/automatic-differentiation.md
  docs/tutorials/working-with-pytrees.md
Labels: pull ready

#18843 Remove stale reference to _site_initialize_0 in wheel build script.
  jaxlib/tools/build_wheel.py
Labels: pull ready

#18833 jnp.solve: handle corner case in input shapes
  jax/_src/numpy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#18844 Deprecate arr.device_buffer and arr.device_buffers
  CHANGELOG.md
  jax/_src/api.py
  jax/_src/array.py
  jax/_src/test_util.py
  tests/notebooks/colab_cpu.ipynb
  tests/xmap_test.py
Labels: kokoro:force-run, pull ready

#18846 Add register_jax_dialects to jaxlib wheel.
  jaxlib/mlir/_mlir_libs/BUILD.bazel
  jaxlib/tools/build_wheel.py
Labels: pull ready

#18824 Expose PrecisionLike
  docs/jax.lax.rst
  jax/lax/__init__.py
Labels: pull ready

#18845 jaxpr: improve printed repr when eqn has no return values
  jax/_src/core.py
  tests/api_test.py
Labels: pull ready

#18853 improve a debug.callback type error message
  jax/_src/debugging.py
  tests/debugging_primitives_test.py
Labels: pull ready

#18856 improve an error message during Mesh creation
  jax/_src/mesh.py
  tests/api_test.py
Labels: pull ready

#18797 Add special.factorial function
  docs/jax.scipy.rst
  jax/_src/scipy/special.py
  jax/scipy/special.py
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#18864 JAX docs tutorial: Working with pytrees
  docs/tutorials/automatic-differentiation.md
  docs/tutorials/working-with-pytrees.md
Labels: pull ready

#18862 Print pjit name= before other params
  docs/jaxpr.rst
  jax/_src/core.py
  jax/_src/pjit.py
  tests/pjit_test.py
Labels: pull ready

#18841 [PALLAS Triton] Error Message Typo Fix
  jax/_src/pallas/triton/lowering.py
Labels: pull ready

#18885 must flatten defaultdict in key-sorted order, like regular dicts
  jax/_src/tree_util.py
  tests/tree_util_test.py
Labels: kokoro:force-run, pull ready

#18898 remove _use_xeinsum from jnp.einsum api
  jax/_src/numpy/lax_numpy.py
  tests/xmap_test.py
Labels: pull ready

#18899 don't call lax.xeinsum from jnp.einsum when str contains '{'
  jax/_src/numpy/lax_numpy.py
  tests/xmap_test.py
Labels: pull ready

#18914 Skip DLPack tests that are failing with the recent changes to the C API
  tests/array_interoperability_test.py
Labels: pull ready

#18923 CI: update actions/setup-python to v5
  .github/workflows/ci-build.yaml
  .github/workflows/jax-array-api.yml
  .github/workflows/wheel_win_x64.yml
  .github/workflows/windows_ci.yml
Labels: pull ready

#18924 CI: use ratchet to pin actions commits
  .github/workflows/ci-build.yaml
  .github/workflows/jax-array-api.yml
  .github/workflows/wheel_win_x64.yml
  .github/workflows/windows_ci.yml
Labels: pull ready

#18925 Remove enable_xla=False test harnesses from export test
  tests/export_harnesses_multi_platform_test.py
Labels: pull ready

#18262 Add experimental static key reuse checking
  docs/jax.experimental.key_reuse.rst
  docs/jax.experimental.rst
  jax/BUILD
  jax/__init__.py
  jax/_src/config.py
  jax/_src/core.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/pjit.py
  jax/_src/state/types.py
  jax/_src/test_util.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/back_compat_test.py
  jax/experimental/jax2tf/tests/jax_primitives_coverage_test.py
  jax/experimental/jax2tf/tests/tf_test_util.py
  jax/experimental/key_reuse/__init__.py
  jax/experimental/key_reuse/_common.py
  jax/experimental/key_reuse/_core.py
  jax/experimental/key_reuse/_forwarding.py
  jax/experimental/key_reuse/_simple.py
  tests/BUILD
  tests/batching_test.py
  tests/core_test.py
  tests/key_reuse_test.py
  tests/random_lax_test.py
  tests/shape_poly_test.py
Labels: pull ready

#18888 The pretty printer now de-duplicates identical jaxprs
  jax/_src/core.py
  jax/_src/pjit.py
  tests/pjit_test.py
Labels: pull ready

#18943 Add missing __future__ import
  jax/_src/xla_bridge.py
Labels: pull ready

#18928 array api: add jnp.linalg.cross & jnp.linalg.outer
  docs/jax.numpy.rst
  jax/_src/numpy/linalg.py
  jax/experimental/array_api/_linear_algebra_functions.py
  jax/numpy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#18946 Improve shape validation when jax_dynamic_shapes=True
  jax/_src/core.py
  tests/dynamic_api_test.py
Labels: pull ready

#18582 JAX docs tutorial: Debugging 101
  docs/tutorials/advanced-autodiff.md
  docs/tutorials/advanced-debugging.md
  docs/tutorials/automatic-differentiation.md
  docs/tutorials/debugging.md
  docs/tutorials/external-callbacks.md
  docs/tutorials/index.rst
  docs/tutorials/thinking-in-jax.md
Labels: pull ready

#18869 Update deprecated APIs in Working with pytrees
  docs/tutorials/working-with-pytrees.md
Labels: pull ready

#18581 JAX docs tutorial: How to think in JAX 101
  docs/tutorials/thinking-in-jax.md
Labels: pull ready

#18968 Minor updates to How to think in JAX and Working with pytrees
  docs/tutorials/thinking-in-jax.md
  docs/tutorials/working-with-pytrees.md
Labels: pull ready

#18987 Recommend the plugin in the CUDA installation instructions.
  README.md
  docs/installation.md
Labels: pull ready

#18983 fix a bug with eager pmap + vmap + custom_jvp interaction
  jax/_src/interpreters/pxla.py
Labels: pull ready

#18991 Revert "Recommend the plugin in the CUDA installation instructions."
  README.md
  docs/installation.md
Labels: pull ready

#18956 [export] Fix the serialization of effects
  jax/experimental/export/serialization.py
  jax/experimental/jax2tf/call_tf.py
  tests/export_test.py
Labels: pull ready

#18980 [export] Refactor the imports for the public API of jax.experimental.export
  CHANGELOG.md
  jax/_src/internal_test_util/export_back_compat_test_util.py
  jax/experimental/export/BUILD
  jax/experimental/export/__init__.py
  jax/experimental/export/_export.py
  jax/experimental/export/serialization.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/back_compat_test.py
  jax/experimental/jax2tf/tests/call_tf_test.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/tf_test_util.py
  tests/export_test.py
Labels: pull ready

#18989 Add a warning if the user calls os.fork().
  jax/_src/xla_bridge.py
Labels: pull ready

#19000 array-api: update CI to use latest array-api-tests commit
  .github/workflows/jax-array-api.yml
Labels: pull ready

#19002 jax.core: deprecate several private APIs
  jax/core.py
Labels: pull ready

#19006 Add unit test for catching log spam.
  tests/logging_test.py
Labels: pull ready

#19005 jnp.linalg: add matrix_norm, matrix_transpose, vector_norm, vector_transpose
  docs/jax.numpy.rst
  jax/_src/numpy/linalg.py
  jax/experimental/array_api/_linear_algebra_functions.py
  jax/experimental/array_api/linalg.py
  jax/numpy/linalg.py
  tests/array_api_test.py
  tests/linalg_test.py
Labels: pull ready

#19012 Set `TF_CPP_MIN_LOG_LEVEL=1` for new log spam test.
  tests/logging_test.py
Labels: pull ready

#19017 [export] Add test for exporting jit(shard_map)
  tests/export_test.py
Labels: pull ready

#19016 [export] Fix handling of float0 when exporting
  jax/experimental/export/export.py
  jax/experimental/export/serialization.fbs
  jax/experimental/export/serialization.py
  jax/experimental/export/serialization_generated.py
  tests/export_test.py
Labels: pull ready

#19032 CI: bump actions/upload-artifact from 3.1.3 to 4.0.0
  .github/workflows/wheel_win_x64.yml
  .github/workflows/windows_ci.yml
Labels: pull ready, CI

#19038 integrate.trapezoid: fix function name in error message
  jax/_src/scipy/integrate.py
Labels: pull ready

#19049 [shape_poly] Update the jax.ops.segment{max|...} to work with shape polymorphism
  jax/_src/ops/scatter.py
  tests/shape_poly_test.py
Labels: pull ready

#18967 [ROCm]: Lower sparse(some) ops correctly for ROCm
  jax/experimental/sparse/_lowerings.py
Labels: pull ready

#18952 Fix duplicate word occurrences
  cloud_tpu_colabs/Pmap_Cookbook.ipynb
  docs/autodidax.ipynb
  docs/autodidax.md
  docs/autodidax.py
  docs/gpu_performance_tips.md
  docs/jep/10657-sequencing-effects.md
  jax/_src/flatten_util.py
  jax/_src/lax/linalg.py
  jax/_src/lax/parallel.py
  jax/_src/random.py
  jax/_src/test_util.py
  jax/experimental/custom_partitioning.py
  jax/experimental/host_callback.py
  jax/experimental/jax2tf/examples/saved_model_lib.py
  jax/experimental/jax2tf/impl_no_xla.py
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
  jax/experimental/sparse/csr.py
  jax/experimental/sparse/linalg.py
  jaxlib/mosaic/dialect/tpu/transforms/apply_vector_layout.cc
  jaxlib/mosaic/python/apply_vector_layout.py
  tests/api_test.py
  tests/lax_numpy_indexing_test.py
  tests/random_test.py
Labels: pull ready

#19026 Add eval_shape example for function with static arguments
  jax/_src/api.py
Labels: pull ready

#19042 jnp.linalg: add matmul, tensordot, & svdvals
  docs/jax.numpy.rst
  jax/_src/numpy/linalg.py
  jax/experimental/array_api/_linear_algebra_functions.py
  jax/numpy/linalg.py
  tests/linalg_test.py
  tests/svd_test.py
Labels: pull ready

#19061 handle convert_element_type(complex -> real) in constant folding
  jax/_src/lax/lax.py
  tests/lax_test.py
Labels: pull ready

#19070 make hypothesis use in all_gather_test.py optional
  tests/pallas/all_gather_test.py
Labels: pull ready

#19071 tangent dtypes for extended dtypes
  jax/_src/core.py
  jax/_src/interpreters/ad.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/prng.py
  jax/experimental/host_callback.py
  jax/experimental/jax2tf/call_tf.py
  jax/interpreters/ad.py
  tests/random_test.py
Labels: pull ready

#19008 JAX docs tutorial: Advanced autodiff 201
  docs/tutorials/advanced-autodiff.md
  docs/tutorials/automatic-differentiation.md
Labels: pull ready

#19077 remove use of cast in ad_util
  jax/_src/ad_util.py
Labels: pull ready

#19072 jnp.vectorize: support excluding arguments by keyword
  jax/_src/numpy/vectorize.py
  tests/lax_numpy_vectorize_test.py
Labels: pull ready

#19084 Make Pallas work with older jaxlib
  jax/_src/pallas/mosaic/lowering.py
Labels: pull ready

#19054 jax.numpy: add trig aliases acos(h), asin(h), atan(h), atan2
  docs/jax.numpy.rst
  jax/_src/numpy/ufuncs.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_operators_test.py
Labels: pull ready

#19090 jnp.unique: add support for the equal_nan keyword
  jax/_src/numpy/setops.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#19086 linalg.lu: avoid NaNs in default lowering rule
  jax/_src/lax/linalg.py
  tests/linalg_test.py
Labels: pull ready

#19034 Support float8 in reduce_min & reduce_max
  jax/_src/dtypes.py
  jax/_src/lax/lax.py
  jax/_src/numpy/reductions.py
  jax/_src/public_test_util.py
  tests/lax_numpy_reducers_test.py
Labels: pull ready

#19093 in partial_eval_custom rule for pjit, cache ClosedJaxpr creation
  benchmarks/api_benchmark.py
  jax/_src/interpreters/partial_eval.py
Labels: pull ready

#19096 del add_any_p and zeros_like_p, replace aval-dispatched traceable
  jax/_src/abstract_arrays.py
  jax/_src/ad_util.py
  jax/_src/internal_test_util/test_harnesses.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/batching.py
  jax/_src/interpreters/mlir.py
  jax/_src/lax/control_flow/solves.py
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/_src/prng.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jet.py
  jax/interpreters/batching.py
  tests/api_test.py
  tests/lax_autodiff_test.py
  tests/random_test.py
Labels: pull ready

#19088 array api: add unique_* interfaces
  docs/jax.numpy.rst
  jax/_src/numpy/setops.py
  jax/experimental/array_api/_set_functions.py
  jax/experimental/array_api/skips.txt
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#19097 tweaks to enable adding custom tangent dtypes
  jax/_src/core.py
  jax/_src/lax/lax.py
  jax/_src/prng.py
  tests/dtypes_test.py
  tests/random_test.py
Labels: pull ready

#19116 revive tangent dtypes test broken by d5646db
  jax/_src/interpreters/mlir.py
  jax/_src/lax/lax.py
  tests/dtypes_test.py
Labels: pull ready

#19117 add test illustrating scale dtypes in scan
  jax/_src/lax/control_flow/loops.py
  tests/dtypes_test.py
Labels: pull ready

#19129 add jax.explain_cache_misses tracing cache miss explanations
  jax/_src/config.py
  jax/_src/linear_util.py
  jax/_src/numpy/ufuncs.py
  jax/_src/pjit.py
  tests/api_test.py
Labels: pull ready
