Repository jax-ml/jax, pull requests merged in 2023-07, with the labels that each got.

#16589 add `impl` option to random key constructors that picks the RNG implementation
  jax/_src/random.py
  tests/random_test.py
Labels: pull ready

#16605 increase random test coverage over RNG key constructors and representations
  tests/random_test.py
Labels: pull ready

#16601 [shape_poly] Cleanup the shape polymorphism APIs.
  jax/_src/api.py
  jax/_src/core.py
  jax/_src/image/scale.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/batching.py
  jax/_src/interpreters/mlir.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/convolution.py
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/_src/nn/functions.py
  jax/_src/numpy/array_methods.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/reductions.py
  jax/_src/numpy/util.py
  jax/_src/prng.py
  jax/core.py
  jax/experimental/jax2tf/impl_no_xla.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#16608 avoid raw uint32 key arrays in typed key sharding test
  tests/random_test.py
Labels: pull ready

#16606 broaden `random.fold_in` annotation to allow for int arrays
  jax/_src/random.py
Labels: pull ready

#16609 test non-threefry RNGs across both typed and raw uint32 key formats
  tests/random_test.py
Labels: pull ready

#16607 match behavior of double-threefry test RNG to standard threefry RNG
  tests/random_test.py
Labels: pull ready

#16610 clean up and parameterize random tests more
  tests/random_test.py
Labels: pull ready

#16635 clean up and parameterize random tests more
  tests/random_test.py
Labels: pull ready

#16642 DOC: improve documentation for lax slicing routines
  jax/_src/lax/slicing.py
Labels: pull ready

#16116 Add discharge rules for scan/while
  jax/_src/lax/control_flow/loops.py
  jax/_src/state/discharge.py
  tests/state_test.py
Labels: pull ready

#16541 Finish pile_map support enough for a basic transformer example
  jax/_src/core.py
  jax/_src/interpreters/batching.py
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  tests/dynamic_api_test.py
Labels: pull ready

#16654 Require ml_dtypes>=0.2
  .pre-commit-config.yaml
  CHANGELOG.md
  jax/_src/dtypes.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/public_test_util.py
  jax/numpy/__init__.py
  jaxlib/setup.py
  setup.py
  tests/dtypes_test.py
Labels: pull ready

#16668 Checkify: remove duplicate line.
  jax/_src/checkify.py
Labels: pull ready

#16645 Fixed _mapped_axis_size raising an uncaught TypeError
  jax/_src/api.py
  tests/api_test.py
Labels: pull ready

#16672 Fix scatter batching rule for scatter_apply
  jax/_src/lax/slicing.py
  tests/lax_numpy_indexing_test.py
  tests/lax_test.py
  tests/lax_vmap_test.py
Labels: pull ready

#16677 better AOT signature mismatch errors (plus docfix)
  docs/aot.md
  jax/_src/interpreters/pxla.py
  tests/api_test.py
  tests/pjit_test.py
  tests/pmap_test.py
  tests/xmap_test.py
Labels: pull ready

#16543 [ROCm]: Re-enable EighIdentity test
  tests/linalg_test.py
Labels: pull ready

#16491 Remove the old JAX/IREE integration.
  jax/BUILD
  jax/_src/iree.py
  jax/_src/xla_bridge.py
Labels: pull ready

#16523 [ROCm]: Update README.md
  build/rocm/README.md
Labels: pull ready

#16683 Note that the MSVC studio 2019 redistributable is required for JAX on…
  README.md
Labels: kokoro:force-run, pull ready, Windows

#16671 NumpySignaturesTest: account for 'mean' param to std/var
  tests/lax_numpy_test.py
Labels: pull ready

#16686 Remove several deprecated APIs
  CHANGELOG.md
  jax/__init__.py
  jax/_src/interpreters/pxla.py
  jax/interpreters/pxla.py
  jax/numpy/__init__.py
Labels: pull ready

#16681 Avoid duplicate symbol definition.
  jaxlib/mlir/_mlir_libs/passes/BUILD
Labels: pull ready

#16687 einsum: inf inputs could cause superfluous nan outputs
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_einsum_test.py
Labels: pull ready

#16644 `random.split`: generalize to optional shape parameter
  jax/_src/prng.py
  jax/_src/random.py
  jax/experimental/jax2tf/jax2tf.py
  tests/random_test.py
Labels: kokoro:force-run, pull ready

#16693 document and test `CustomVJPPrimal` type as API symbol
  jax/_src/custom_derivatives.py
  tests/api_test.py
Labels: pull ready

#16694 pre-commit: update mypy to most recent version
  .pre-commit-config.yaml
  jax/experimental/jax2tf/examples/tf_js/quickdraw/quickdraw.py
  jax/experimental/sparse/test_util.py
  pyproject.toml
Labels: pull ready

#16695 Remove obsolete jaxlib version checks
  jax/_src/compilation_cache.py
  jax/_src/lib/__init__.py
  jax/_src/prng.py
  jax/_src/util.py
  tests/compilation_cache_test.py
  tests/util_test.py
Labels: pull ready

#16696 Make jit work with custom float inputs
  jax/_src/interpreters/mlir.py
  jax/_src/test_util.py
  tests/api_test.py
Labels: pull ready

#16689 [shape_poly] More cleanup for the internal APIs for shape polymorphism.
  jax/_src/core.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/convolution.py
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/_src/lax/windowed_reductions.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/reductions.py
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  jax/interpreters/partial_eval.py
  tests/dynamic_api_test.py
Labels: pull ready

#16685 JIT through ragged axes
  jax/_src/interpreters/batching.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/_src/pjit.py
  jax/_src/sharding_impls.py
  tests/dynamic_api_test.py
Labels: pull ready

#16717 type promotion: improve implicit type promotion error for float8 & int4
  jax/_src/dtypes.py
  tests/dtypes_test.py
Labels: pull ready

#16724 Change default memory allocation to 75% instead of 90%
  docs/gpu_memory_allocation.rst
Labels: pull ready

#16482 [jax2tf] Add backwards compatibility test for linalg.cholesky custom call on CPU
  jax/experimental/jax2tf/tests/back_compat_test.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_cholesky_lapack_potrf.py
Labels: pull ready

#16518 [jax2tf] Add backwards compatibility tests for linalg.svd on CPU
  jax/experimental/jax2tf/jax_export.py
  jax/experimental/jax2tf/tests/back_compat_test.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_svd_lapack_gesdd.py
Labels: pull ready

#16481 [jax2tf] Add backward compatibility tests for linalg.eig on CPU.
  jax/experimental/jax2tf/tests/back_compat_test.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_eig_lapack_geev.py
Labels: pull ready

#16713 [shape_poly] More cleanup for the internal APIs for shape polymorphism.
  jax/_src/core.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/convolution.py
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/_src/lax/windowed_reductions.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/reductions.py
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  jax/interpreters/partial_eval.py
  tests/dynamic_api_test.py
Labels: pull ready

#16718 make scatter-apply jvp notimplemented (for now...)
  jax/_src/lax/slicing.py
  jax/experimental/jax2tf/jax2tf.py
  tests/lax_autodiff_test.py
Labels: pull ready

#16741 remove stray print statement
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#16759 Fix docstring for `jax.debug.{print,callback}`
  jax/_src/debugging.py
Labels: pull ready

#16767 mypy: suppress annotation-unchecked notes
  pyproject.toml
Labels: pull ready

#16740 [sparse] support preferred_element_type in dot_general
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/bcsr.py
  tests/sparse_test.py
  tests/sparsify_test.py
Labels: pull ready

#16769 support np.array(x) where x is a custom pytree with __jax_array__
  jax/_src/numpy/lax_numpy.py
  tests/api_test.py
Labels: pull ready

#16775 add details on randomness and numerics to API compatibility docs
  docs/api_compatibility.md
  tests/random_test.py
Labels: pull ready

#16751 [jax2tf] Add backwards compatibility test for lax.triangular_solve on CPU
  jax/experimental/jax2tf/jax_export.py
  jax/experimental/jax2tf/tests/back_compat_test.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_triangular_solve_blas_trsm.py
Labels: pull ready

#16752 [jax2tf] Add backwards compatibility for lax.linalg.schur on CPU
  jax/experimental/jax2tf/tests/back_compat_test.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_schur_lapack_gees.py
Labels: pull ready

#16793 Remove obsolete numpy version checks
  tests/lax_numpy_test.py
  tests/random_test.py
Labels: pull ready

#16794 Remove unneeded Python 3.9+ version checks
  jax/_src/api_util.py
  jax/_src/sharding_impls.py
Labels: pull ready

#16779 Re-parameterize jax.random.gamma for better behavior at endpoints
  CHANGELOG.md
  jax/_src/random.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  tests/random_test.py
Labels: pull ready

#16710 [shape_poly] Add support for max0 for symbolic dimensions.
  CHANGELOG.md
  jax/_src/core.py
  jax/_src/interpreters/mlir.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/test_util.py
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/jax_export.py
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/back_compat_test.py
  jax/experimental/jax2tf/tests/jax_export_test.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  jax/experimental/jax2tf/tests/sharding_test.py
Labels: kokoro:force-run, pull ready

#15679 make jvp(asarray, (1.,), (2.,)) produce Arrays
  jax/_src/lax/lax.py
  tests/api_test.py
Labels: pull ready

#16807 Use standard framework for jax.tree* deprecation.
  jax/__init__.py
  jax/_src/tree_util.py
Labels: pull ready

#16797 Cloud TPU CI: make sure we update test deps and upgrade protobuf version
  .github/workflows/cloud-tpu-ci-nightly.yml
  build/collect-profile-requirements.txt
Labels: pull ready

#16802 [jax2tf] Document the JAX serialization version numbers.
  jax/_src/config.py
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/jax_export.py
  jax/experimental/jax2tf/shape_poly.py
Labels: pull ready

#16795 Refactor opaque dtype implementation.
  jax/_src/core.py
  jax/_src/dtypes.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
  jax/_src/prng.py
  tests/lax_test.py
Labels: pull ready

#16721 Lower jax.numpy.dot to mixed-precision dot_general
  jax/_src/numpy/lax_numpy.py
  tests/api_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#16781 custom prng: introduce mechanism to identify key arrays by dtype
  docs/jax.dtypes.rst
  jax/_src/checkify.py
  jax/_src/dtypes.py
  jax/_src/prng.py
  jax/_src/random.py
  jax/dtypes.py
  tests/random_test.py
Labels: pull ready

#16822 CI: update jupytext to v0.14.7
  .pre-commit-config.yaml
  docs/autodidax.md
  docs/autodidax.py
  docs/developer.md
  docs/jax-101/01-jax-basics.md
  docs/jax-101/02-jitting.md
  docs/jax-101/03-vectorization.md
  docs/jax-101/04-advanced-autodiff.md
  docs/jax-101/05-random-numbers.md
  docs/jax-101/05.1-pytrees.md
  docs/jax-101/06-parallelism.md
  docs/jax-101/07-state.md
  docs/jep/9407-type-promotion.md
  docs/notebooks/Common_Gotchas_in_JAX.md
  docs/notebooks/Custom_derivative_rules_for_Python_code.md
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.md
  docs/notebooks/How_JAX_primitives_work.md
  docs/notebooks/Neural_Network_and_Data_Loading.md
  docs/notebooks/Writing_custom_interpreters_in_Jax.md
  docs/notebooks/autodiff_cookbook.md
  docs/notebooks/autodiff_remat.md
  docs/notebooks/convolutions.md
  docs/notebooks/external_callbacks.md
  docs/notebooks/neural_network_with_tfds_data.md
  docs/notebooks/quickstart.md
  docs/notebooks/thinking_in_jax.md
  docs/notebooks/vmapped_log_probs.md
  docs/notebooks/xmap_tutorial.md
Labels: pull ready

#16829 replace use of has_opaque_dtype
  jax/_src/lax/lax.py
Labels: pull ready

#16820 [jax2tf] Added error for attempting to use wrong jax_serialization_version
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/jax_export.py
  jax/experimental/jax2tf/tests/back_compat_test_util.py
  jax/experimental/jax2tf/tests/jax_export_test.py
  jax/experimental/jax2tf/tests/tf_test_util.py
Labels: pull ready

#16839 fix deprecations in core.py
  jax/core.py
Labels: kokoro:force-run, pull ready

#16833 [jax2tf] Add support for serialization version 8.
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/jax_export.py
  jax/experimental/jax2tf/tests/back_compat_test_util.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/jax_export_test.py
Labels: pull ready

#16842 lax.dynamic_slice: avoid negative index correction for unsigned indices
  jax/_src/lax/slicing.py
  tests/lax_test.py
Labels: kokoro:force-run, pull ready

#16846 [shape_poly] Fix handling of dot_general with different lhs_dtype and rhs_dtype
  jax/_src/lax/lax.py
  jax/experimental/jax2tf/g3doc/jax_primitives_coverage.md
  jax/experimental/jax2tf/g3doc/primitives_with_limited_support.md
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
  jax/experimental/jax2tf/tests/primitive_harness.py
Labels: pull ready

#16849 Make //jax:tpu_custom_call respect --//jax:build_jaxlib=false
  jax/BUILD
Labels: pull ready

#16826 make _dot_general_batch_rule handle python builtin numeric types
  jax/_src/lax/lax.py
  tests/lax_test.py
Labels: pull ready

#16844 Add implementation of jnp.put
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#16852 Check `build` and `wheel` are installed before building `jaxlib`.
  build/build.py
Labels: pull ready

#16433 Update incorrect Dirichlet PDF in documentation
  jax/_src/random.py
Labels: pull ready

#16869 Update WORKSPACE and setup.py in preparation for jax/jaxlib 0.4.14 re…
  WORKSPACE
  setup.py
Labels: pull ready

#16870 Slightly downgrade xla version to avoid PJRT C API incompat
  WORKSPACE
Labels: kokoro:force-run, pull ready

#16656 Add kl_div and rel_entr functions
  docs/jax.scipy.rst
  jax/_src/scipy/special.py
  jax/scipy/special.py
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#16877 Update versions and changelog for jax 0.4.14 release
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: pull ready

#16878 Bump ProfilerTest.test_remote_profiler to run computations for 10 seconds.
  tests/profiler_test.py
Labels: pull ready

#16883 add an exp2 primitive and lax.exp2
  jax/_src/internal_test_util/lax_test_util.py
  jax/_src/lax/lax.py
  jax/_src/lax_reference.py
  jax/_src/numpy/ufuncs.py
  jax/experimental/jax2tf/jax2tf.py
  jax/lax/__init__.py
  tests/lax_autodiff_test.py
Labels: pull ready

#16304 Add `jax_debug_log_modules` config option.
  jax/BUILD
  jax/__init__.py
  jax/_src/config.py
  jax/_src/dispatch.py
  jax/_src/logging_config.py
  tests/BUILD
  tests/logging_test.py
Labels: pull ready
