Repository jax-ml/jax, pull requests merged in 2023-10, with the labels that each got.

#17423 [jax_export] Add the next part of multi-platform lowering support.
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  tests/export_test.py
Labels: pull ready

#17882 Update test to skip np.bitwise_count ufunc
  tests/lax_numpy_test.py
Labels: pull ready

#17888 Add CHANGELOG entry for the jnp annotation change
  CHANGELOG.md
Labels: pull ready

#17889 [typing] allow Sequence inputs in several jax.numpy functions
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.pyi
Labels: pull ready

#17760 MAINT Clean up leftover ``Array = Any`` aliases in jax/_src/**.py
  jax/BUILD
  jax/_src/interpreters/batching.py
  jax/_src/lax/ann.py
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/convolution.py
  jax/_src/lax/windowed_reductions.py
  jax/_src/nn/functions.py
  jax/_src/nn/initializers.py
  jax/_src/ops/scatter.py
  jax/_src/scipy/optimize/_lbfgs.py
  jax/_src/state/types.py
Labels: pull ready

#17851 tweak readme to call out broader numerical computing
  README.md
Labels: pull ready

#17905 Update XLA commit and versions for jax 0.4.17 release
  setup.py
  third_party/xla/workspace.bzl
Labels: pull ready

#17885 Add jax.numpy.bitwise_count()
  CHANGELOG.md
  docs/jax.numpy.rst
  jax/_src/numpy/ufuncs.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_operators_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#17907 fix typo in deprecation message
  jax/tree_util.py
Labels: pull ready

#17906 Remove the LD_PRELOAD workaround introduced in https://github.com/goo…
  .github/workflows/cloud-tpu-ci-nightly.yml
Labels: pull ready

#17908 Move the prerequisites to the beginning of the tests instructions.
  docs/developer.md
Labels: pull ready

#17909 Update versions and CHANGELOG after jax 0.4.17 release
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: kokoro:force-run, pull ready

#17910 Remove references to the ROCm TensorFlow repository in AMD build inst…
  docs/developer.md
Labels: kokoro:force-run, pull ready, AMD GPU

#17911 Use the released version of Python 3.12 in the Windows wheel builds.
  .github/workflows/wheel_win_x64.yml
Labels: pull ready

#17925 jax.random: fix NaN corner-case in loggamma
  jax/_src/random.py
  tests/random_test.py
Labels: pull ready

#17933 Condition numpy versios based on python versions
  setup.py
Labels: pull ready

#17938 jnp.bitwise_count: call into lax.population_count
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#17929 Simplify the torch data loader collate function using tree_map.
  docs/notebooks/Neural_Network_and_Data_Loading.ipynb
  docs/notebooks/Neural_Network_and_Data_Loading.md
Labels: pull ready

#17921 [export] Improve primitive harnesses to use jax.random.key
  jax/experimental/jax2tf/tests/multi_platform_export_test.py
  jax/experimental/jax2tf/tests/primitive_harness.py
Labels: pull ready

#17965 Asynchronous dispatch doc update regarding jax.Array migration
  docs/async_dispatch.rst
Labels: pull ready

#17928 [run_state] add scan nested test, tweak rule name to mention 'state'
  jax/_src/lax/control_flow/loops.py
  tests/state_test.py
Labels: pull ready

#17932 [run_state] add pjit run_state discharge rule and basic test
  jax/_src/pjit.py
  jax/_src/state/discharge.py
  tests/state_test.py
Labels: pull ready

#17968 random_test: remove unnecessary test utilities
  tests/random_lax_test.py
  tests/random_test.py
Labels: pull ready

#17978 Check dtypes in fft_p's abstract eval rule.
  jax/_src/lax/fft.py
  tests/fft_test.py
Labels: pull ready

#17979 Fix tests that mistakenly used assertRaises(..., msg=...) to match…
  tests/array_test.py
  tests/deprecation_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#17981 Improve CUDA install documenation.
  CHANGELOG.md
  docs/installation.md
Labels: kokoro:force-run, pull ready

#17988 test `jax.extend` custom PRNG construction round trip
  tests/extend_test.py
Labels: kokoro:force-run, pull ready

#17959 lax.abs: better error for unsigned inputs
  jax/_src/lax/lax.py
Labels: pull ready

#17962 jnp.bitwise_count: fix issue with unsigned ints
  jax/_src/numpy/ufuncs.py
  tests/lax_numpy_operators_test.py
Labels: pull ready

#17987 jax.lax: deprecate inadvertent exports & internal utilities
  CHANGELOG.md
  jax/lax/__init__.py
Labels: pull ready

#17989 Update setup.py and CHANGELOG for jax 0.4.18 release
  CHANGELOG.md
  setup.py
Labels: pull ready

#17984 DOC: add missing jax.lax API docs
  docs/jax.lax.rst
Labels: documentation, pull ready

#17991 api_test: fix platform-dependent deprecation warning
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#17990 random_test: fix deprecation warnings for key tests
  tests/random_lax_test.py
  tests/random_test.py
Labels: pull ready

#17992 test: prevent regressions on object comparisons
  jax/_src/test_util.py
  tests/array_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#17994 Update versions post jax 0.4.18 release
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: kokoro:force-run, pull ready

#17996 fix pow jvp rule with int exponent (broken since #16419)
  jax/_src/lax/lax.py
  tests/lax_autodiff_test.py
Labels: kokoro:force-run, pull ready

#18012 Ignore patch versions of cufft and cusolver in CUDA version checks.
  jax/_src/xla_bridge.py
Labels: kokoro:force-run, pull ready

#18015 fix typo in scatter_add doc
  jax/_src/lax/slicing.py
Labels: pull ready

#18010 Fix test failure in lax_control_flow_test on Mac ARM.
  tests/lax_control_flow_test.py
Labels: pull ready

#18017 jnp.frompyfunc: fix .at() edge case
  jax/_src/numpy/ufunc_api.py
  tests/lax_numpy_ufuncs_test.py
Labels: pull ready

#18023 jax.make_jaxpr: fix __name__ & related attributes
  jax/_src/api.py
  tests/api_test.py
Labels: pull ready

#18038 Fix mypy errors in flash_attention
  jax/experimental/pallas/ops/tpu/flash_attention.py
Labels: kokoro:force-run, pull ready

#18040 Set -P when testing whether a package is installed during build.py.
  build/build.py
Labels: pull ready

#18035 Update README.md so that CPU install instruction works
  README.md
Labels: pull ready

#18042 Define jax.typing.DTypeLike
  CHANGELOG.md
  docs/jax.typing.rst
  jax/typing.py
Labels: pull ready

#18044 Update references to aarch64 support in the README.
  README.md
  docs/installation.md
Labels: kokoro:force-run, pull ready

#18048 MAINT Use a generator expression with `all()` and `any()`
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/numpy/lax_numpy.py
  jax/experimental/jax2tf/call_tf.py
  jax/experimental/jax2tf/impl_no_xla.py
  jax/experimental/jax2tf/tests/jax_primitives_coverage_test.py
  jax/experimental/jax2tf/tests/primitive_harness.py
  tests/array_interoperability_test.py
  tests/core_test.py
  tests/sparse_test.py
Labels: pull ready

#18052 [random] add shaped_abstractify handler for custom PRNG key
  jax/_src/prng.py
Labels: pull ready

#18062 Add a version constraint on nvidia-nvjitlink-cu12.
  setup.py
Labels: kokoro:force-run, pull ready

#18066 CI: update mypy to v1.6.0
  .pre-commit-config.yaml
  jax/_src/array.py
  jax/_src/core.py
Labels: pull ready

#18071 Fix typo in setup.py
  setup.py
Labels: kokoro:force-run, pull ready

#18030 jax.core: deprecate some inadvertent exports
  jax/core.py
Labels: pull ready

#18041 Set RPATH, not RUNPATH in JAX CUDA builds.
  .bazelrc
  CHANGELOG.md
Labels: pull ready

#18022 Update xmap guide - add jit/shard_map note
  docs/notebooks/xmap_tutorial.ipynb
  docs/notebooks/xmap_tutorial.md
Labels: pull ready

#17892 typing: add some type assertions to typing_test
  tests/typing_test.py
Labels: pull ready

#18096 fix: typo inside docs/notebooks/How_JAX_primitives_work.md
  docs/notebooks/How_JAX_primitives_work.ipynb
  docs/notebooks/How_JAX_primitives_work.md
Labels: pull ready

#18102 JEX: add jax.extend.source_info_util
  jax/extend/__init__.py
  jax/extend/source_info_util.py
Labels: pull ready

#18095 fix: typo inside docs/jep/12049-type-annotations.md
  docs/jep/12049-type-annotations.md
Labels: pull ready

#18108 Fix libtpu path on older jaxlibs.
  jax/_src/xla_bridge.py
Labels: pull ready

#17980 [export] Adapt several collective lowering rules for multi-platform lowering
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/parallel.py
  jax/experimental/jax2tf/tests/multi_platform_export_test.py
Labels: pull ready

#18110 jax.core: point deprecation to jax.extend
  jax/core.py
Labels: pull ready

#18111 MAINT Drop underscore from the name of externally-referenced state objects
  jax/_src/maps.py
  jax/_src/test_util.py
  jax/experimental/jax2tf/tests/sharding_test.py
  tests/multiprocess_gpu_test.py
  tests/pjit_test.py
  tests/python_callback_test.py
  tests/shard_map_test.py
  tests/state_test.py
  tests/xmap_test.py
Labels: pull ready

#18112 [typing] allow scalar shape for jnp.broadcast_to
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
  jax/numpy/__init__.pyi
Labels: pull ready

#18120 Enhance the speed of slogdet with qr method
  jax/_src/numpy/linalg.py
Labels: pull ready

#18104 [jax2tf] First step to enable multi-platform native lowering
  jax/experimental/export/export.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/back_compat_test_util.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  tests/export_test.py
Labels: pull ready

#18105 [random] Avoid references to PRNGKeyArray type
  jax/_src/random.py
  tests/random_test.py
Labels: pull ready

#18117 jax.interpreters.ad: deprecate inadvertently exported symbols
  jax/interpreters/ad.py
Labels: pull ready

#18070 Setup compatibility testing to support the oldest supported libtpu ve…
  .github/workflows/cloud-tpu-ci-nightly.yml
Labels: pull ready

#18156 [random] remove internal uses of deprecated prng.seed_with_impl()
  jax/_src/prng.py
  jax/_src/random.py
  jax/extend/random.py
  tests/pjit_test.py
  tests/random_lax_test.py
Labels: pull ready

#18138 [shard_map] fix axis env extension bug
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#18126 feat: add wrapcauchy logpdf and pdf
  docs/jax.scipy.rst
  jax/_src/scipy/stats/wrapcauchy.py
  jax/scipy/stats/__init__.py
  jax/scipy/stats/wrapcauchy.py
  tests/scipy_stats_test.py
Labels: pull ready

#18162 [random] cleanup internal implementation
  jax/_src/prng.py
Labels: pull ready

#18159 Set public module for exported jax.dtypes APIs
  jax/BUILD
  jax/_src/dtypes.py
Labels: pull ready

#18176 [random] deprecate jax.random.threefry_2x32 & threefry_2x32_p
  jax/_src/random.py
  jax/random.py
Labels: pull ready

#18161 [random] make PRNG impl attributes private
  docs/jep/9263-typed-keys.md
  jax/_src/prng.py
  jax/_src/random.py
  jax/experimental/jax2tf/jax2tf.py
  tests/random_test.py
Labels: pull ready

#18191 Avoid numpy.core import for NumPy 2.0
  jax/numpy/__init__.py
Labels: pull ready

#18189 Cleanup untile lowering to remove platform dependence.
  jax/_src/maps.py
Labels: pull ready

#18190 [export] Improve the calling of multi-platform exported module
  jax/experimental/export/export.py
  tests/export_test.py
Labels: pull ready

#18093 output-forwarding residual optimization for jit and shard_map
  jax/_src/interpreters/partial_eval.py
  jax/_src/pjit.py
  jax/_src/util.py
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#18197 [random] deprecate jax.random.default_prng_impl()
  jax/experimental/jax2tf/tests/primitive_harness.py
  jax/random.py
  tests/api_test.py
  tests/random_test.py
Labels: pull ready

#18202 [export] Add jax.global_constant MLIR attributes for dimension variable arguments
  jax/_src/interpreters/mlir.py
  jax/_src/test_util.py
  jax/experimental/export/export.py
  jax/experimental/jax2tf/README.md
  tests/export_test.py
Labels: pull ready

#18195 [export] Drop backwards-compatible lowering_platform in export
  jax/experimental/export/export.py
Labels: pull ready

#18163 Fix oldest supported libtpu install command
  .github/workflows/cloud-tpu-ci-nightly.yml
Labels: pull ready

#18168 MAINT Do not import the config object in JAX internals
  jax/experimental/x64_context.py
  tests/cache_key_test.py
  tests/experimental_rnn_test.py
  tests/mosaic_test.py
  tests/scipy_spatial_test.py
Labels: pull ready

#18154 [typing] regularize types of jax.random API
  jax/_src/prng.py
  jax/_src/random.py
  tests/random_test.py
Labels: pull ready

#17783 [export] Add support for exporting functions with effects
  jax/_src/interpreters/mlir.py
  jax/experimental/export/export.py
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/back_compat_test_util.py
  jax/experimental/jax2tf/tests/call_tf_test.py
  tests/export_test.py
Labels: pull ready

#18180 Add jax.numpy.fill_diagonal.
  CHANGELOG.md
  docs/jax.numpy.rst
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#18000 Add precision warning and workaround to jnp.arange documentation
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#18236 [CI] avoid referencing numpy.core to fix nightly CI
  jax/numpy/__init__.py
Labels: pull ready

#18256 Allow array-like inputs to random.seed_impl
  jax/_src/prng.py
Labels: pull ready

#18217 [call_tf] Fix multi-platform lowering
  jax/experimental/export/export.py
  jax/experimental/jax2tf/call_tf.py
  jax/experimental/jax2tf/tests/call_tf_test.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: pull ready

#18277 DOC: set navigation_with_keys=False
  docs/conf.py
Labels: kokoro:force-run, pull ready

#18305 Deprecated the `jax.config` submodule
  jax/config.py
Labels: pull ready

#18274 Deprecated `define_*` and `DEFINE_*` methods on `jax.config`
  jax/_src/config.py
  tests/BUILD
  tests/config_test.py
Labels: pull ready

#18323 CI: update pre-commit hooks to latest version
  .pre-commit-config.yaml
  docs/autodidax.md
  docs/autodidax.py
  docs/developer.md
  docs/jax-101/01-jax-basics.md
  docs/jax-101/02-jitting.md
  docs/jax-101/03-vectorization.md
  docs/jax-101/04-advanced-autodiff.md
  docs/jax-101/05-random-numbers.md
  docs/jax-101/05.1-pytrees.md
  docs/jax-101/06-parallelism.md
  docs/jax-101/07-state.md
  docs/jep/9407-type-promotion.md
  docs/notebooks/Common_Gotchas_in_JAX.md
  docs/notebooks/Custom_derivative_rules_for_Python_code.md
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.md
  docs/notebooks/How_JAX_primitives_work.md
  docs/notebooks/Neural_Network_and_Data_Loading.md
  docs/notebooks/Writing_custom_interpreters_in_Jax.md
  docs/notebooks/autodiff_cookbook.md
  docs/notebooks/autodiff_remat.md
  docs/notebooks/convolutions.md
  docs/notebooks/external_callbacks.md
  docs/notebooks/neural_network_with_tfds_data.md
  docs/notebooks/quickstart.md
  docs/notebooks/thinking_in_jax.md
  docs/notebooks/vmapped_log_probs.md
  docs/notebooks/xmap_tutorial.md
  docs/pallas/quickstart.md
Labels: pull ready

#18324 jnp.einsum: mention default value for optimize param
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#18158 draft docs on gpu performance tuning
  docs/gpu_performance_tips.md
  docs/user_guides.rst
Labels: pull ready

#18269 Documentation: add stub files for new tutorial structure
  docs/tutorial/advanced-autodiff.md
  docs/tutorial/advanced-compilation.md
  docs/tutorial/automatic-differentiation.md
  docs/tutorial/debugging.md
  docs/tutorial/external-callbacks.md
  docs/tutorial/index.rst
  docs/tutorial/installation.md
  docs/tutorial/jax-as-accelerated-numpy.md
  docs/tutorial/jax-internals.md
  docs/tutorial/jit-compilation.md
  docs/tutorial/parallelism.md
  docs/tutorial/profiling-and-performance.md
  docs/tutorial/quickstart.md
  docs/tutorial/random-numbers.md
  docs/tutorial/simple-neural-network.md
  docs/tutorial/single-host-sharding.md
  docs/tutorial/stateful-computations.md
  docs/tutorial/working-with-pytrees.md
Labels: pull ready

#18338 add `jax.threefry_partitionable` context manager
  jax/__init__.py
  jax/_src/config.py
Labels: pull ready
