Repository jax-ml/jax, pull requests merged in 2023-03, with the labels that each got.

#14737 Add "Open in Kaggle" buttons to Jupyter notebooks.
  docs/jax-101/01-jax-basics.ipynb
  docs/jax-101/01-jax-basics.md
  docs/jax-101/02-jitting.ipynb
  docs/jax-101/02-jitting.md
  docs/jax-101/03-vectorization.ipynb
  docs/jax-101/03-vectorization.md
  docs/jax-101/04-advanced-autodiff.ipynb
  docs/jax-101/04-advanced-autodiff.md
  docs/jax-101/05-random-numbers.ipynb
  docs/jax-101/05-random-numbers.md
  docs/jax-101/05.1-pytrees.ipynb
  docs/jax-101/05.1-pytrees.md
  docs/jax-101/06-parallelism.ipynb
  docs/jax-101/06-parallelism.md
  docs/jax-101/07-state.ipynb
  docs/jax-101/07-state.md
  docs/jep/9407-type-promotion.ipynb
  docs/jep/9407-type-promotion.md
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
  docs/notebooks/Custom_derivative_rules_for_Python_code.ipynb
  docs/notebooks/Custom_derivative_rules_for_Python_code.md
  docs/notebooks/How_JAX_primitives_work.ipynb
  docs/notebooks/How_JAX_primitives_work.md
  docs/notebooks/Neural_Network_and_Data_Loading.ipynb
  docs/notebooks/Neural_Network_and_Data_Loading.md
  docs/notebooks/Writing_custom_interpreters_in_Jax.ipynb
  docs/notebooks/Writing_custom_interpreters_in_Jax.md
  docs/notebooks/autodiff_cookbook.ipynb
  docs/notebooks/autodiff_cookbook.md
  docs/notebooks/convolutions.ipynb
  docs/notebooks/convolutions.md
  docs/notebooks/neural_network_with_tfds_data.ipynb
  docs/notebooks/neural_network_with_tfds_data.md
  docs/notebooks/quickstart.ipynb
  docs/notebooks/quickstart.md
  docs/notebooks/thinking_in_jax.ipynb
  docs/notebooks/thinking_in_jax.md
  docs/notebooks/vmapped_log_probs.ipynb
  docs/notebooks/vmapped_log_probs.md
Labels: kokoro:force-run, pull ready

#14736 DOC: fix readthedocs for sphinx-book-theme=1.0
  docs/conf.py
Labels: pull ready

#14738 DOC: update sphinx & sphinx-autodoc-typehints
  docs/_static/style.css
  docs/index.rst
  docs/requirements.txt
Labels: pull ready

#14728 [custom_vjp] bwd function should not be WrappedFun, may run multiple times
  jax/_src/custom_derivatives.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/batching.py
  jax/_src/tree_util.py
  tests/api_test.py
Labels: pull ready

#14747 Fix Typo in `scipy.stats.vonmise`
  jax/_src/scipy/stats/vonmises.py
Labels: pull ready

#14754 DOC: clarify variable names in scan doc
  jax/_src/lax/control_flow/loops.py
Labels: pull ready

#14755 Add repr for UnspecifiedValue
  jax/_src/interpreters/pxla.py
Labels: kokoro:force-run, pull ready

#14702 attach debug info to jaxpr, pass to mlir/mhlo
  jax/_src/ad_checkpoint.py
  jax/_src/api.py
  jax/_src/checkify.py
  jax/_src/core.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  jax/_src/util.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: pull ready

#14531 [sparse] modify impl rules to always use lowering path
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/bcsr.py
  jax/experimental/sparse/coo.py
  jax/experimental/sparse/csr.py
Labels: pull ready

#14761 Bump version and changelog after jax 0.4.5 release
  CHANGELOG.md
  jax/version.py
Labels: pull ready

#14764 attach debug info to jaxpr, pass to mlir/mhlo
  jax/_src/ad_checkpoint.py
  jax/_src/api.py
  jax/_src/checkify.py
  jax/_src/core.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  jax/_src/util.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: pull ready

#14696 [shape_poly] Add support for jnp.cum{sum,prod,max,min} with shape polymorphism
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/windowed_reductions.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#14734 [shape_poly, call_tf] Add support for call_tf in a shape polymorphic program
  CHANGELOG.md
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/call_tf.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/call_tf_test.py
Labels: pull ready

#14788 (Static type-checking fix) `BatchingRule` type annotation now supports `not_mapped`.
  jax/_src/interpreters/batching.py
Labels: pull ready

#14790 Use jax2tf with static type checking
  jax/experimental/jax2tf/__init__.py
Labels: pull ready

#14785 Add changelog description for pytree key path API
  CHANGELOG.md
Labels: pull ready

#14789 (Static type-checking fix) Add `_ScalarMeta(dtype=...)` field.
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#14809 [sparse] fix OOB index correction
  jax/experimental/sparse/bcoo.py
Labels: pull ready

#14813 add result info to mhlo
  jax/_src/ad_checkpoint.py
  jax/_src/api.py
  jax/_src/api_util.py
  jax/_src/checkify.py
  jax/_src/core.py
  jax/_src/custom_batching.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/control_flow/common.py
  jax/experimental/custom_partitioning.py
  jax/experimental/sparse/bcoo.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
  tests/pjit_test.py
Labels: pull ready

#14749 [shape_poly] Add support for shape polymorphism for jnp.{argsort,bincount,insert,nonzero}
  jax/_src/numpy/lax_numpy.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#14782 avoid unnecessary broadcasting in jax.numpy.vectorize
  jax/_src/numpy/vectorize.py
  tests/lax_numpy_vectorize_test.py
Labels: pull ready

#14792 Fix `loc` and `scale` parameters in `scipy.logistic.*`. Add CDF and SF for several distributions.
  docs/jax.scipy.rst
  jax/_src/scipy/stats/beta.py
  jax/_src/scipy/stats/cauchy.py
  jax/_src/scipy/stats/chi2.py
  jax/_src/scipy/stats/gamma.py
  jax/_src/scipy/stats/logistic.py
  jax/_src/scipy/stats/norm.py
  jax/_src/scipy/stats/t.py
  jax/scipy/stats/beta.py
  jax/scipy/stats/cauchy.py
  jax/scipy/stats/chi2.py
  jax/scipy/stats/gamma.py
  jax/scipy/stats/norm.py
  tests/scipy_stats_test.py
Labels: pull ready

#14835 `ravel_pytree` now accepted by static linters
  jax/flatten_util.py
Labels: pull ready

#14836 Add "compare_all" method to searchsorted
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#14823 [sparse] more careful handling of index_dtype in rand_bcoo
  jax/experimental/sparse/random.py
Labels: pull ready

#14829 [sparse] improve worst-case nse in spdot_general
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: pull ready

#14855 [sparse] add support for integer_pow
  jax/experimental/sparse/transform.py
  tests/sparsify_test.py
Labels: pull ready

#14838 internal: avoid unused imports in lax_numpy
  jax/_src/lax/eigh.py
  jax/_src/lax/linalg.py
  jax/_src/numpy/fft.py
  jax/_src/numpy/index_tricks.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/linalg.py
  jax/_src/numpy/polynomial.py
  jax/_src/numpy/setops.py
  jax/_src/ops/scatter.py
  jax/_src/ops/special.py
  jax/_src/prng.py
  jax/_src/random.py
  jax/_src/scipy/cluster/vq.py
  jax/_src/scipy/linalg.py
  jax/_src/scipy/ndimage.py
  jax/_src/scipy/signal.py
  jax/_src/scipy/special.py
  jax/_src/scipy/stats/_core.py
  jax/_src/scipy/stats/bernoulli.py
  jax/_src/scipy/stats/beta.py
  jax/_src/scipy/stats/betabinom.py
  jax/_src/scipy/stats/cauchy.py
  jax/_src/scipy/stats/chi2.py
  jax/_src/scipy/stats/dirichlet.py
  jax/_src/scipy/stats/expon.py
  jax/_src/scipy/stats/gamma.py
  jax/_src/scipy/stats/gennorm.py
  jax/_src/scipy/stats/geom.py
  jax/_src/scipy/stats/kde.py
  jax/_src/scipy/stats/laplace.py
  jax/_src/scipy/stats/logistic.py
  jax/_src/scipy/stats/multinomial.py
  jax/_src/scipy/stats/multivariate_normal.py
  jax/_src/scipy/stats/nbinom.py
  jax/_src/scipy/stats/norm.py
  jax/_src/scipy/stats/pareto.py
  jax/_src/scipy/stats/poisson.py
  jax/_src/scipy/stats/t.py
  jax/_src/scipy/stats/truncnorm.py
  jax/_src/scipy/stats/uniform.py
  jax/_src/scipy/stats/vonmises.py
  jax/_src/test_util.py
  jax/_src/third_party/numpy/linalg.py
  jax/_src/third_party/scipy/betaln.py
  jax/_src/third_party/scipy/interpolate.py
  jax/_src/third_party/scipy/linalg.py
  jax/_src/third_party/scipy/signal_helper.py
  jax/experimental/sparse/coo.py
  jax/experimental/sparse/csr.py
Labels: pull ready

#14841 Add argnames and resultnames to pmap.
  jax/_src/interpreters/pxla.py
  tests/pmap_test.py
Labels: pull ready

#14840 update relu6 grad at 0 and 6 to match pytorch convention
  jax/_src/nn/functions.py
  tests/nn_test.py
Labels: pull ready

#14565 deprecation_module: Move to new internal_test_util directory.
  jax/_src/internal_test_util/deprecation_module.py
  tests/BUILD
  tests/deprecation_test.py
Labels: pull ready

#14861 add api_boundary decorator to jax.eval_shape
  jax/_src/api.py
Labels: pull ready

#14849 Fix implicit rank promotion.
  jax/_src/lax/linalg.py
Labels: pull ready

#14863 [shard_map] make debug_print work with shard_map (eager and jit)
  docs/debugging/index.md
  jax/_src/debugging.py
  jax/experimental/shard_map.py
  tests/python_callback_test.py
  tests/shard_map_test.py
Labels: pull ready

#14881 Update WORKSPACE and setup.py for jax/jaxlib 0.4.6 release
  WORKSPACE
  setup.py
Labels: pull ready

#14837 [Doc] GPU custom ops tutorial updates.
  docs/Custom_Operation_for_GPUs.md
Labels: pull ready

#14888 Update versions and changelog for jax + jaxlib 0.4.6 release
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: pull ready

#14896 [shard_map] bug fix: extend axis env in partial_eval_custom rule
  jax/experimental/shard_map.py
  jax/interpreters/partial_eval.py
  tests/shard_map_test.py
Labels: pull ready

#14897 [jax2tf] Refactor the JAX native lowering to separate out the TF-specific parts
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: pull ready

#14908 Fix jnp.sort & jnp.vdot in no-jit mode
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#14887 Add xla garbage collection to gc.callback
  jax/_src/lib/__init__.py
  tests/api_test.py
Labels: pull ready

#14912 jnp.argmin/max: correctly handle out argument
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#14919 checkify_test: avoid passing argument to at[i].get()
  tests/checkify_test.py
Labels: pull ready

#14940 [jax2tf] Refactor and simplify the native lowering
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#14953 update docs to remove stale reference to laziness optimization
  docs/faq.rst
Labels: pull ready

#14915 jnp.argsort: fix annotations & behavior under disable_jit
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#14956 Correct register_pytree_with_keys annotation
  jax/_src/tree_util.py
Labels: pull ready

#14954 use Partial to make ravel_pytree unflatteners jit-friendly
  jax/_src/flatten_util.py
  jax/_src/util.py
  jax/experimental/shard_map.py
  tests/tree_util_test.py
Labels: pull ready

#14965 [typing] add type annotations to index_update code
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#14952 jnp.ndarray.at: deprecate passing additional arguments by position
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#14987 [sparse] add BCOO lowering for div
  jax/experimental/sparse/transform.py
  tests/sparsify_test.py
Labels: pull ready

#14928 jnp.arange: better validation of inputs
  jax/_src/dtypes.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
  tests/lax_numpy_test.py
Labels: kokoro:force-run, pull ready

#14975 [jax2tf] Documentation for the native serialization mode
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/jax2tf.py
Labels: pull ready

#15006 README: improve Colab TPU installation discussion
  README.md
Labels: documentation, pull ready

#14986 [dynamic-shapes] don't require buf objects have dtype attribute
  jax/_src/dispatch.py
  tests/dynamic_api_test.py
Labels: pull ready

#15030 Add regression test for #4780
  tests/api_test.py
Labels: pull ready

#15031 jnp.einsum: make signature match documentation.
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#15008 jax.numpy reductions: validate axis for scalar input
  jax/_src/numpy/reductions.py
Labels: pull ready

#15048 add test for #7155, fixes #7155
  tests/api_test.py
Labels: pull ready

#15057 Improve error for tolist() and tobytes() on tracer objects
  jax/_src/core.py
  tests/lax_numpy_test.py
Labels: kokoro:force-run, pull ready

#15063 DOC: remove jax 0.4.1 banner from index page
  docs/index.rst
Labels: pull ready

#15064 Sharp bits: refer to ndarray.at in out-of-bound indexing discussion
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
Labels: kokoro:force-run, pull ready

#15075 [jax2tf] Minor improvement in an error message
  jax/_src/lax/control_flow/loops.py
Labels: pull ready

#15097 Improve error for indexing with string
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: kokoro:force-run, pull ready

#15071 [pytrees] fix function underlying tree-flattening with keys
  jax/_src/tree_util.py
  tests/tree_util_test.py
Labels: pull ready

#15080 make mlir arg and result names work with static_argnums/argnames
  jax/_src/api.py
  jax/_src/api_util.py
  jax/_src/core.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  jax/_src/pjit.py
  jax/_src/tree_util.py
  jax/_src/util.py
  jax/experimental/shard_map.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
  tests/pmap_test.py
Labels: pull ready

#15105 Typo fix in ResizeMethod docstring, scale.py
  jax/_src/image/scale.py
Labels: pull ready

#15079 separate register_pytree_node and register_pytree_with_keys tests
  tests/tree_util_test.py
Labels: pull ready

#15092 [jax2tf] Ensure that the gradient function is serialized natively.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: pull ready

#15120 Fix inspect_array_sharding with grad.
  jax/_src/debugging.py
  tests/debugging_primitives_test.py
Labels: pull ready

#15126 Document ShapeDtypeStruct
  docs/jax.rst
  jax/_src/api.py
Labels: pull ready

#15088 `custom_vjp` symbolic zeros support
  jax/_src/checkify.py
  jax/_src/core.py
  jax/_src/custom_derivatives.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/batching.py
  jax/_src/interpreters/pxla.py
  jax/experimental/jax2tf/jax2tf.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: pull ready

#15129 [jax2tf] Fix grad of pjit in native lowering.
  jax/_src/pjit.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/sharding_test.py
Labels: pull ready

#15114 Add `wald` distribution to `random.py`
  docs/jax.random.rst
  jax/_src/random.py
  jax/random.py
  tests/random_test.py
Labels: pull ready

#15139 jax.random: remove scale from wald function
  jax/_src/random.py
  tests/random_test.py
Labels: kokoro:force-run, pull ready

#15140 DOC: add formulae for distributions in jax.random
  jax/_src/random.py
Labels: kokoro:force-run, pull ready

#15143 WAR the dependency issue in the nightly CI container.
  .github/workflows/slurm_job_scripts/run_e2e_t5x_tests.sub
Labels: pull ready

#15148 Add print statement to help debug spurious test failure
  tests/compilation_cache_test.py
Labels: pull ready

#15151 add experimental jax_log_checkpoint_residuals option
  jax/_src/ad_checkpoint.py
  jax/_src/config.py
  tests/api_test.py
Labels: pull ready

#15154 enable pjit recursive typechecking
  jax/_src/core.py
  jax/_src/custom_derivatives.py
  jax/_src/custom_transpose.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/_src/maps.py
  jax/_src/pjit.py
  jax/experimental/shard_map.py
  tests/core_test.py
Labels: pull ready

#15123 jnp.mean: fix incorrect return value for large arrays
  jax/_src/numpy/reductions.py
  tests/lax_numpy_test.py
Labels: pull ready

#15179 Fix mypy issue in jax/experimental/jet.py
  jax/experimental/jet.py
Labels: pull ready

#15180 Adds the trailing-whitespace pre-commit hook
  .pre-commit-config.yaml
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_lapack_syev.py
Labels: pull ready

#15172 internal: refactor array methods into separate private submodule
  jax/_src/numpy/array_methods.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/prng.py
  jax/numpy/__init__.py
Labels: pull ready

#15178 improve scan error messages
  jax/_src/lax/control_flow/common.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/tree_util.py
  tests/lax_control_flow_test.py
Labels: pull ready

#15184 lax_numpy: move quantile-based functions to reductions.py
  jax/_src/lax/eigh.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/reductions.py
  jax/numpy/__init__.py
  tests/lax_numpy_reducers_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#14309 Increase minimum NumPy version to 1.21.
  CHANGELOG.md
  build/build.py
  jaxlib/setup.py
  setup.py
  tests/lax_numpy_reducers_test.py
  tests/scipy_stats_test.py
Labels: pull ready

#15187 [dynamic-shapes] djax+pjit staging to jaxpr
  jax/_src/api.py
  jax/_src/lax/lax.py
  jax/_src/pjit.py
  jax/interpreters/partial_eval.py
  tests/dynamic_api_test.py
Labels: pull ready

#15192 fix jax.Array.round()
  jax/_src/numpy/array_methods.py
  tests/lax_numpy_test.py
Labels: pull ready

#15203 [CI] remove another dependency not currently needed.
  .github/workflows/slurm_job_scripts/run_e2e_t5x_tests.sub
Labels: pull ready

#15175 WAR ssh timeout
  .github/workflows/nightly-ci-multiprocess-gpu.yml
Labels: pull ready

#15212 Remove 'pjrt_c_api_unimplemented' pytest mark.
  .github/workflows/cloud-tpu-ci-nightly.yml
  pytest.ini
  tests/clear_backends_test.py
  tests/debugger_test.py
  tests/debugging_primitives_test.py
  tests/host_callback_test.py
  tests/host_callback_to_tf_test.py
  tests/infeed_test.py
  tests/jaxpr_effects_test.py
  tests/pjit_test.py
  tests/python_callback_test.py
Labels: kokoro:force-run, pull ready

#15234 [shape_poly] Fixed bug with dimension variables in unused args
  jax/_src/interpreters/pxla.py
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#15228 Fix hessian llnk
  README.md
Labels: pull ready

#15218 Suppress mypy warnings about missing imports.
  mypy.ini
Labels: pull ready

#8633 autodidax: fix jaxpr_subcomp return type annotation
  docs/autodidax.ipynb
  docs/autodidax.md
  docs/autodidax.py
Labels: cla: yes, pull ready

#15241 jax.typing: recommend instance check in Python 3.10 or newer
  jax/typing.py
Labels: pull ready

#15206 jax.scipy.linalg.expm: support batched inputs
  jax/_src/scipy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#15258 [shape_poly] Refactor the computation of the dimension variables in native serialization
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/jax_export.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#15251 CI: add numpy & scipy to mypy env
  .pre-commit-config.yaml
Labels: pull ready

#15263 Add deprecation warnings for several top-level jax imports
  jax/__init__.py
  tests/api_test.py
Labels: pull ready

#15266 Fixed spelling error in msgs
  jax/experimental/shard_map.py
Labels: pull ready

#15269 Bump minimum jaxlib version from 0.4.6 to 0.4.7.
  CHANGELOG.md
  jax/_src/api.py
  jax/_src/array.py
  jax/_src/config.py
  jax/_src/dlpack.py
  jax/_src/lax/lax.py
  jax/_src/random.py
  jax/_src/xla_bridge.py
  jax/experimental/host_callback.py
  jax/experimental/jax2tf/jax_export.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  jax/version.py
  tests/jax_jit_test.py
  tests/lax_test.py
Labels: pull ready

#15270 Turn on PJRT C API by default.
  CHANGELOG.md
  docs/debugging/print_breakpoint.md
  jax/_src/cloud_tpu_init.py
Labels: pull ready

#15279 Add version constraints to CUDA pip wheel dependencies.
  setup.py
Labels: pull ready, NVIDIA GPU

#15286 Recommend --local_test_jobs in bazel test command line on GPU.
  docs/developer.md
Labels: pull ready

#15278 Update the CUDA installation instructions.
  README.md
Labels: kokoro:force-run, pull ready, NVIDIA GPU

#15283 Remove `scale` parameter info in `random.wald` docstring
  jax/_src/random.py
Labels: pull ready

#15299 DOC: pin pydata-sphinx-theme to fix incompatibility
  docs/requirements.txt
Labels: pull ready

#15297 jnp.finfo: add missing properties
  jax/_src/dtypes.py
  tests/dtypes_test.py
Labels: pull ready

#15287 [shape_poly] Improved computation of dimension variables for native serialization
  jax/_src/interpreters/mlir.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/jax_export.py
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  jax/interpreters/mlir.py
Labels: pull ready

#15282 add `geometric` to `random.py`
  docs/jax.random.rst
  jax/_src/random.py
  jax/random.py
  tests/random_test.py
Labels: pull ready

#15301 Add 1-hour timeout to each Cloud TPU CI job.
  .github/workflows/cloud-tpu-ci-nightly.yml
Labels: pull ready

#15300 Update version and changelog after jax 0.4.8 release
  CHANGELOG.md
  jax/version.py
Labels: pull ready

#15328 Fix broadcasting in jax.random.geometric
  jax/_src/random.py
Labels: pull ready

#15327 DOC: fix headings in user_guides
  docs/user_guides.rst
Labels: pull ready

#15332 [shard-map] handle closed-over vmap tracers
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#15331 [typing] use protocol for cumulative reductions
  jax/_src/numpy/reductions.py
Labels: pull ready

#15329 [typing] use protocol for pad stat_func
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#15322 CI: add EOF and debug precommit hooks
  .pre-commit-config.yaml
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_lapack_syev.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cuda_cusolver_geqrf.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cuda_cusolver_syev.py
  jax/experimental/jax2tf/tests/back_compat_testdata/tpu_Qr.py
Labels: pull ready

#15255 Fix typo in betaln.py
  jax/_src/third_party/scipy/betaln.py
Labels: pull ready

#15335 add assertions for axis name shadowing bugs
  jax/_src/interpreters/batching.py
  tests/pmap_test.py
Labels: pull ready

#15337 fix bug from #15335 by checking main_trace tag
  jax/_src/core.py
  jax/_src/interpreters/batching.py
  tests/pmap_test.py
  tests/shard_map_test.py
Labels: pull ready

#15232 [shape_poly] Extend the handling of jnp.arange with shape polymorphism.
  jax/_src/numpy/lax_numpy.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#15323 Fix broadcasting in jax.random.rayleigh
  jax/_src/random.py
Labels: pull ready

#15317 [ROCm]: Run pmap test on specific number of GPUs
  build/rocm/run_multi_gpu.sh
Labels: pull ready

#15321 Remove deprecated function jnp.msort
  CHANGELOG.md
  docs/jax.numpy.rst
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.py
  tests/lax_numpy_test.py
Labels: pull ready

#15342 DOC: pin newest sphinx-book-theme
  docs/requirements.txt
Labels: pull ready
