Repository jax-ml/jax, pull requests merged in 2023-01, with the labels that each got.

#13814 validate shape & dtype in ShapeDtypeStruct
  jax/_src/api.py
  tests/api_test.py
Labels: pull ready

#13831 [Typing] Add `Optional` to parameter `boundary` of `stft`.
  jax/_src/scipy/signal.py
Labels: pull ready

#13639 Instructions to create custom operation for GPUs
  docs/Custom_Operation_for_GPUs.md
  docs/index.rst
Labels: pull ready

#13828 [sparse] automate gradient tests for bcoo_todense/bcoo_fromdense
  tests/sparse_test.py
Labels: pull ready

#13849 Improve vmap error
  jax/_src/api_util.py
Labels: pull ready

#13860 [typing] improve sphinx rendering of type aliases
  docs/conf.py
Labels: documentation, pull ready

#13865 [sparse] mark several slow tests
  tests/sparse_test.py
Labels: pull ready

#13881 Make Shard.device and Shard.data read-only properties.
  jax/_src/array.py
Labels: pull ready

#13859 tweak remat named policies
  jax/_src/ad_checkpoint.py
Labels: pull ready

#13883 Fix typo in checkify guide.
  docs/debugging/checkify_guide.md
Labels: kokoro:force-run, pull ready

#13790 [jax2tf] Enable Trace to handle dimension polynomials used as constants
  jax/_src/core.py
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#13884 Explicitly set utf-8 encoding in setup.py
  setup.py
Labels: pull ready

#13900 CI: fix doc requirements
  docs/requirements.txt
Labels: kokoro:force-run, pull ready

#13589 DOC: clarify behavior of lax.cond & lax.select
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/lax.py
Labels: pull ready

#13902 Fix broken link in readme
  README.md
Labels: pull ready

#13908 core.get_aval: use correct weak_type
  jax/_src/abstract_arrays.py
Labels: bug, kokoro:force-run, pull ready

#13916 [jax2tf] Add more pjit tests
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: pull ready

#13910 Update jax.xmap notebook title, make "xmap" tutorial more discoverable
  docs/notebooks/xmap_tutorial.ipynb
  docs/notebooks/xmap_tutorial.md
Labels: pull ready

#13925 DOC: change requirements pinnings to prevent timeout
  docs/requirements.txt
Labels: pull ready

#13917 [jax2tf] Fixed the conversion of a function that contains an inner pjit
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/sharding_test.py
Labels: pull ready

#13937 Add tests of dtypes.finfo properties
  jax/_src/dtypes.py
  tests/dtypes_test.py
Labels: pull ready

#13948 Fix finfo test for older numpy versions
  tests/dtypes_test.py
Labels: kokoro:force-run, pull ready

#13944 DOC: add note about localhost & friends in jax.distributed.initialize
  jax/_src/distributed.py
Labels: pull ready

#13946 DOC: add FAQ entry on converting a tracer to an array
  docs/faq.rst
Labels: documentation, pull ready

#13950 DOC: fix heading levels in GPU custom ops
  docs/Custom_Operation_for_GPUs.md
Labels: pull ready

#13872 [jax2tf] Fixed the shape-polymorphic lowering for lax.pad
  jax/_src/lax/lax.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  jax/interpreters/mlir.py
Labels: pull ready

#13958 add pjit partial_eval_jaxpr_custom rule
  jax/_src/core.py
  jax/_src/pjit.py
  jax/interpreters/partial_eval.py
Labels: pull ready

#13967 [typing] add missing attributes to jax.Array
  jax/_src/basearray.pyi
Labels: pull ready

#13929 Add Open MPI automatic distributed initialization
  docs/multi_process.md
  jax/_src/clusters/__init__.py
  jax/_src/clusters/ompi_cluster.py
  jax/_src/distributed.py
  tests/multiprocess_gpu_test.py
Labels: pull ready

#13909 [sparse] add nfold_vmap utility
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/bcsr.py
  jax/experimental/sparse/util.py
Labels: pull ready

#13889 [sparse] generalize batch rule for bcoo_spdot_general
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/test_util.py
  tests/sparse_test.py
Labels: pull ready

#13887 [sparse] generalize batch rule for bcoo_dot_general
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: pull ready

#13977 Add `pjrt_c_api_unimplemented` pytest marker to skip unsupported tests.
  jax/_src/test_util.py
  pytest.ini
  tests/clear_backends_test.py
  tests/debugger_test.py
  tests/debugging_primitives_test.py
  tests/host_callback_test.py
  tests/host_callback_to_tf_test.py
  tests/infeed_test.py
  tests/jaxpr_effects_test.py
  tests/pjit_test.py
  tests/python_callback_test.py
Labels: pull ready

#13892 [sparse] generalize batch rule for bcoo_sum_duplicates & improve tests
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/test_util.py
  tests/sparse_test.py
Labels: pull ready

#13940 [docs] change donate_argnums FAQ link to rst format
  jax/_src/api.py
  jax/_src/pjit.py
  jax/experimental/maps.py
Labels: pull ready

#13862 [sparse] bcoo_extract: add assume_unique keyword
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: pull ready

#13869 [sparse] add higher-level version of bcoo_extract & improve tests
  jax/experimental/sparse/api.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/bcsr.py
  tests/sparse_test.py
Labels: pull ready

#13285 Add beginner, advanced, and contributors guide
  docs/_static/style.css
  docs/advanced_guide.rst
  docs/beginner_guide.rst
  docs/conf.py
  docs/contributor_guide.rst
  docs/index.rst
  docs/jax-101/index.rst
  docs/notes.rst
  docs/requirements.txt
  docs/user_guides.rst
Labels: pull ready

#14020 fix transcription error for initial_step_size (thanks @AlbertMitjans)
  jax/experimental/ode.py
Labels: pull ready

#13980 [call_tf] Add has_side_effects parameter
  CHANGELOG.md
  jax/experimental/jax2tf/call_tf.py
  jax/experimental/jax2tf/tests/call_tf_test.py
Labels: pull ready

#14027 cond transpose, use UndefinedPrimal not `linear` for transpose inputs
  jax/_src/lax/control_flow/conditionals.py
  tests/lax_control_flow_test.py
Labels: pull ready

#14030 [shape_poly] Improve error message from vmap axis size inconsistency
  jax/_src/api.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#14047 DOC: add GPU & TPU installation tabs on index page
  docs/index.rst
Labels: documentation, pull ready

#13423 Multinode CICD using on-demand HPC cluster + e2e T5X tests
  .github/workflows/cat_slurm_logs.py
  .github/workflows/nightly-ci-multiprocess-gpu.yml
  .github/workflows/slurm_job_scripts/extract_e2e_tests_metrics.py
  .github/workflows/slurm_job_scripts/multinode_pytest_jaxlib_nightly.sub
  .github/workflows/slurm_job_scripts/multinode_pytest_jaxlib_release.sub
  .github/workflows/slurm_job_scripts/oci_cluster_manager.py
  .github/workflows/slurm_job_scripts/requirements.txt
  .github/workflows/slurm_job_scripts/run_e2e_t5x_tests.sub
  .github/workflows/slurm_job_scripts/slurm_utils_common.sh
Labels: pull ready

#13911 Fix headings in JAX Custom operations for GPUs and Building from source guides
  docs/Custom_Operation_for_GPUs.md
  docs/developer.md
Labels: pull ready

#14031 [jax2tf] Adjust jax2tf for the pjit==jit API migration.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/tf_test_util.py
Labels: pull ready

#14059 Fix excessive recompiles in lax.cond
  jax/_src/core.py
  jax/_src/lax/control_flow/conditionals.py
  tests/lax_control_flow_test.py
Labels: pull ready

#14053 [shape_poly] Fix handling of weak_type for jnp.array(x.shape[0])
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#14008 Don't set TPU topology env vars in cloud_tpu_init.py
  jax/_src/cloud_tpu_init.py
  jax/_src/clusters/cloud_tpu_cluster.py
Labels: pull ready

#14066 Update lax_control_flow_test.py
  tests/lax_control_flow_test.py
Labels: pull ready

#14037 FAQ: fix discussion of marking self as static
  docs/faq.rst
Labels: pull ready

#14049 DOC: make grid placement responsive for smaller screens
  docs/index.rst
Labels: documentation, pull ready

#14062 DOC: make API doc titles more uniform
  docs/jax.config.rst
  docs/jax.debug.rst
  docs/jax.distributed.rst
  docs/jax.dlpack.rst
  docs/jax.example_libraries.optimizers.rst
  docs/jax.example_libraries.rst
  docs/jax.example_libraries.stax.rst
  docs/jax.experimental.checkify.rst
  docs/jax.experimental.global_device_array.rst
  docs/jax.experimental.host_callback.rst
  docs/jax.experimental.jet.rst
  docs/jax.experimental.maps.rst
  docs/jax.experimental.pjit.rst
  docs/jax.experimental.rst
  docs/jax.experimental.sparse.rst
  docs/jax.flatten_util.rst
  docs/jax.image.rst
  docs/jax.lax.rst
  docs/jax.lib.rst
  docs/jax.nn.initializers.rst
  docs/jax.nn.rst
  docs/jax.numpy.rst
  docs/jax.ops.rst
  docs/jax.profiler.rst
  docs/jax.random.rst
  docs/jax.rst
  docs/jax.scipy.rst
  docs/jax.sharding.rst
  docs/jax.stages.rst
  docs/jax.tree_util.rst
Labels: pull ready

#13995 Added shape error checking for compute_fans
  jax/_src/nn/initializers.py
  tests/nn_test.py
Labels: pull ready

#14077 [sparse] update primitive coverage in module doc
  jax/experimental/sparse/__init__.py
Labels: pull ready

#14038 Sharp bits: raise exceptions directly
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
Labels: documentation, pull ready

#14079 Reorganization among notes, user guides, advanced guides
  docs/advanced_guide.rst
  docs/index.rst
  docs/notes.rst
  docs/user_guides.rst
Labels: documentation, pull ready

#14042 Sharp bits dynamic shapes
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
Labels: pull ready

#14029 Make JAX Debugging and Profiling guides more visible
  docs/debugging/index.md
  docs/notes.rst
  docs/user_guides.rst
Labels: kokoro:force-run, pull ready

#14083 Remove more uses of tan() in reduction tests.
  tests/lax_control_flow_test.py
Labels: pull ready

#14090 CI: update deprecated uses of set-output
  .github/workflows/ci-build.yaml
  .github/workflows/upstream-nightly.yaml
Labels: pull ready

#14089 Clarify the docstring for vjp.
  jax/_src/api.py
Labels: pull ready

#14094 Updates for jax + jaxlib 0.4.2 release
  CHANGELOG.md
  WORKSPACE
  jax/tools/colab_tpu.py
  setup.py
Labels: kokoro:force-run, pull ready

#14096 [sparse] refactor tests to improve runtime
  jax/experimental/sparse/test_util.py
  tests/sparse_test.py
Labels: kokoro:force-run, pull ready

#14093 specialize tree prefix error message for list/tuple
  jax/_src/tree_util.py
  tests/pjit_test.py
  tests/tree_util_test.py
Labels: pull ready

#14085 CI: adjust permissions for upstream-nightly build
  .github/workflows/upstream-nightly.yaml
Labels: pull ready

#14106 [shape_poly] Generalize binary operations with symbolic dimensions.
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#14113 Adding info to CG and BICGSTAB
  jax/_src/scipy/sparse/linalg.py
Labels: pull ready

#14102 Raise an error when attempting to mutate Jaxpr objects
  CHANGELOG.md
  jax/_src/core.py
  jax/_src/lax/control_flow/loops.py
  jax/experimental/host_callback.py
  tests/core_test.py
Labels: pull ready

#14120 CI: update flake8 to v6.0.0
  .pre-commit-config.yaml
Labels: pull ready

#14091 [sparse] add a few missing methods to BCOO
  jax/experimental/sparse/transform.py
Labels: pull ready

#14123 Use __slots__ in Jaxpr & ClosedJaxpr
  jax/_src/core.py
Labels: pull ready

#13535 CI: update jupytext version in pre-commit
  .pre-commit-config.yaml
  docs/autodidax.ipynb
  docs/autodidax.md
  docs/autodidax.py
  docs/developer.md
  docs/jax-101/01-jax-basics.md
  docs/jax-101/02-jitting.md
  docs/jax-101/03-vectorization.md
  docs/jax-101/04-advanced-autodiff.md
  docs/jax-101/05-random-numbers.md
  docs/jax-101/05.1-pytrees.md
  docs/jax-101/06-parallelism.md
  docs/jax-101/07-state.md
  docs/jep/9407-type-promotion.md
  docs/notebooks/Common_Gotchas_in_JAX.md
  docs/notebooks/Custom_derivative_rules_for_Python_code.md
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.md
  docs/notebooks/How_JAX_primitives_work.md
  docs/notebooks/Neural_Network_and_Data_Loading.md
  docs/notebooks/Writing_custom_interpreters_in_Jax.md
  docs/notebooks/autodiff_cookbook.md
  docs/notebooks/convolutions.md
  docs/notebooks/external_callbacks.md
  docs/notebooks/neural_network_with_tfds_data.md
  docs/notebooks/quickstart.md
  docs/notebooks/thinking_in_jax.md
  docs/notebooks/vmapped_log_probs.md
  docs/notebooks/xmap_tutorial.md
  docs/transformations.md
Labels: pull ready

#14131 CI: fix mypy jaxlib version
  .pre-commit-config.yaml
  jax/_src/lib/mlir/dialects/__init__.py
  jax/experimental/rnn.py
Labels: pull ready

#14135 Update WORKSPACE for jaxlib 0.4.2 release (again)
  WORKSPACE
Labels: pull ready

#14148 Update libtpu version for jaxlib 0.4.2 release (again)
  setup.py
Labels: pull ready

#14097 DOC: Adding @custom_partitioning to jax.experimental API doc
  docs/jax.experimental.custom_partitioning.rst
  docs/jax.experimental.rst
  jax/experimental/custom_partitioning.py
Labels: pull ready

#14137 Checkify: Validate format arguments to make sure they're arrays
  jax/_src/checkify.py
  tests/checkify_test.py
Labels: pull ready

#14154 Link to JAXopt in example_libraries.optimizers
  jax/example_libraries/optimizers.py
Labels: pull ready

#13537 [TPU CI] Send chat notification on cancellation as well as failure.
  .github/workflows/cloud-tpu-ci-nightly.yml
Labels: pull ready

#14156 DOC: more guidance within getting started guide
  docs/beginner_guide.rst
Labels: documentation, pull ready

#14161 Update versions for jaxlib 0.4.2 release.
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: pull ready

#14167 Add new jtu.pytest_filterwarnings_if_available and use to fix failing test
  tests/pjit_test.py
Labels: pull ready

#14158 DOC: organize content in advanced guide
  docs/advanced_guide.rst
  docs/notebooks/convolutions.ipynb
  docs/notebooks/convolutions.md
  docs/notebooks/vmapped_log_probs.ipynb
  docs/notebooks/vmapped_log_probs.md
  docs/notes.rst
  docs/user_guides.rst
Labels: documentation, pull ready

#14108 [shape_poly] Add better support for division, and working with strides
  CHANGELOG.md
  jax/_src/lax/convolution.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/prng.py
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#14175 DOC: fix autodidax
  docs/autodidax.ipynb
  docs/autodidax.md
  docs/autodidax.py
  tests/api_test.py
Labels: pull ready

#14170 DOC: clarify purpose of the jax-array doc
  docs/jax_array_migration.md
Labels: kokoro:force-run, pull ready

#14169 Removed deprecated polar_unitary as per phawkins comment.
  CHANGELOG.md
  docs/jax.scipy.rst
  jax/_src/scipy/linalg.py
  jax/scipy/linalg.py
Labels: pull ready

#14189 remove rules translating opaquely dtyped avals directly to MLIR types
  jax/_src/core.py
  jax/_src/lax/lax.py
  jax/_src/prng.py
  jax/interpreters/mlir.py
  tests/lax_test.py
Labels: kokoro:force-run, pull ready

#14187 Fix typo in autodidax test
  tests/api_test.py
Labels: pull ready

#14192 [sparse] add BCSR.to_bcoo and from_bcoo methods
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/bcsr.py
  jax/experimental/sparse/test_util.py
  tests/sparse_test.py
Labels: pull ready

#14204 DOC: re-organize notes section
  docs/notes.rst
  docs/rank_promotion_warning.rst
  docs/user_guides.rst
Labels: documentation, kokoro:force-run, pull ready

#14206 Begin deprecation of public jax.ShapedArray
  benchmarks/api_benchmark.py
  jax/__init__.py
  jax/_src/sharding.py
  jax/experimental/multihost_utils.py
  jax/tools/jax_to_ir.py
  tests/api_test.py
  tests/array_test.py
  tests/infeed_test.py
  tests/multiprocess_gpu_test.py
  tests/pjit_test.py
  tests/pmap_test.py
Labels: pull ready

#14209 Add implementation of jnp.partition
  docs/jax.numpy.rst
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.py
  tests/lax_numpy_test.py
Labels: pull ready

#14211 Update signature of ad.defbilinear to simplify transpose rules
  jax/_src/lax/convolution.py
  jax/_src/lax/lax.py
  jax/_src/lax/parallel.py
  jax/experimental/jax2tf/impl_no_xla.py
  jax/experimental/jax2tf/jax2tf.py
  jax/interpreters/ad.py
Labels: pull ready

#14230 Remove unused CacheInfo namedtuple
  jax/_src/util.py
Labels: pull ready

#14234 Fix documentation broken by 8dc1dff6
  docs/jax.lib.rst
Labels: kokoro:force-run, pull ready
