Repository jax-ml/jax, pull requests merged in 2023-04, with the labels that each got.

#15341 [jax2tf] Cleanup of handling of tf.custom_gradient
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: pull ready

#15340 [shape_poly] Cleanup handling of dimension variables.
  jax/_src/core.py
  jax/_src/interpreters/mlir.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/jax_export.py
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#15169 Correctly handle seq_lengths in lstm_ref
  jax/experimental/rnn.py
  tests/experimental_rnn_test.py
Labels: pull ready

#15289 Add missing key_path functions to tree_util api reference
  docs/jax.tree_util.rst
Labels: pull ready

#15390 checkify: catch OOB errors in dynamic_slice
  jax/_src/checkify.py
  tests/checkify_test.py
Labels: pull ready

#15086 Support extrapolation in jnp.interp
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#15396 future-proof lax.convert_element_type
  jax/_src/lax/lax.py
  tests/lax_test.py
Labels: kokoro:force-run, pull ready

#15415 [sparse] allow sparse-dense add when the output is the same size as dense input
  jax/experimental/sparse/transform.py
  tests/sparsify_test.py
Labels: kokoro:force-run, pull ready

#15401 fix conj transpose on symbolic zero
  jax/_src/lax/lax.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#15428 fix a `__jax_array__` bug in convert_element_type
  jax/_src/lax/lax.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#15399 [shard-map] debugging shmap + prngkey bugs
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  jax/_src/prng.py
  jax/experimental/shard_map.py
  tests/lax_test.py
  tests/pjit_test.py
  tests/shard_map_test.py
Labels: pull ready

#15397 [typing] fix annotation of jnp.split
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#15445 Add nightly to TPU test matrix
  .github/workflows/cloud-tpu-ci-nightly.yml
Labels: kokoro:force-run, pull ready

#15461 fix formatting in pjit doc
  jax/_src/api.py
  jax/_src/pjit.py
Labels: pull ready

#15441 Use the nightly whl in the CI.
  .github/workflows/slurm_job_scripts/run_e2e_t5x_tests.sub
Labels: pull ready

#15458 Explicitly re-export all names from jax.debug
  jax/debug.py
Labels: pull ready

#15224 first implementation of scipy fftconvolve
  docs/jax.scipy.rst
  jax/_src/scipy/signal.py
  jax/scipy/signal.py
  tests/scipy_signal_test.py
Labels: pull ready

#15440 Add documentation for callback functions
  docs/notebooks/external_callbacks.ipynb
  docs/notebooks/external_callbacks.md
Labels: pull ready

#15475 [shard-map] don't fail on error message formatting if f.__name__ fails
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#15474 add docs for jax.clear_caches
  docs/jax.rst
  jax/_src/api.py
Labels: pull ready

#15477 [shard-map] improve error message when in_specs is None
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#15432 [jax2tf] Refactor the gradient machinery for native serialization
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/jax_export.py
  jax/experimental/jax2tf/tests/back_compat_test.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/sharding_test.py
  jax/experimental/shard_map.py
Labels: pull ready

#15480 separate `PRNGKeyArray` implementation from interface
  jax/_src/prng.py
  tests/random_test.py
Labels: pull ready

#15221 `custom_vjp` symbolic zeros support, take two
  jax/_src/checkify.py
  jax/_src/core.py
  jax/_src/custom_derivatives.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/batching.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/interpreters/pxla.py
  jax/_src/linear_util.py
  jax/custom_derivatives.py
  jax/experimental/jax2tf/jax2tf.py
  tests/api_test.py
Labels: pull ready

#15481 [shard-map] add scan rep rule
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#15485 update prng docs to mention jax_threefry_partitionable
  docs/jax.random.rst
  jax/random.py
Labels: pull ready

#15495 [shard-map] better rep-rule-not-implemented error
  jax/experimental/shard_map.py
Labels: pull ready

#15442 [shard-map] better errors for not-implemented-in-eager features
  jax/_src/core.py
  jax/_src/interpreters/pxla.py
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#15497 [shard-map] fix jaxpr_shardings logic for shmap with no outputs
  jax/_src/dispatch.py
  tests/shard_map_test.py
Labels: pull ready

#15479 jnp.einsum: add preferred_element_type argument
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_einsum_test.py
Labels: pull ready

#15491 Fix typo in CI config
  .github/workflows/ci-build.yaml
Labels: pull ready

#15524 [shard-map] "support" device_put in shmap bodies (error if nontrivial)
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#15531 fix typo in functions.py
  jax/_src/nn/functions.py
Labels: pull ready

#15521 [shard-map] add dce rule, basically like call dce rule + params handling
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#15532 update skipping logic
  tests/util_test.py
Labels: kokoro:force-run, pull ready

#15522 jax.scipy.signal.convolve: support method='fft'
  jax/_src/scipy/signal.py
  tests/scipy_signal_test.py
Labels: pull ready

#15518 [typing]: add type annotations for jnp.einsum
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#15520 Fix uint32 scatter assignment
  jax/_src/ops/scatter.py
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#15526 lax.arraylike: avoid binding device_put_p
  jax/_src/lax/lax.py
Labels: pull ready

#15534 fix debug callback docstring (and return value)
  jax/_src/debugging.py
Labels: pull ready

#15378 check that overflow is raised on builtin int overflow
  tests/api_test.py
  tests/random_test.py
Labels: pull ready

#15541 Try to fix strange error where DATE end up being empty.
  .github/workflows/slurm_job_scripts/run_e2e_t5x_tests.sub
Labels: pull ready

#15550 lower all all_to_all to AllToAll
  jax/_src/lax/parallel.py
  tests/pmap_test.py
  tests/shard_map_test.py
Labels: pull ready

#15561 [shape_poly] Add support for shape polymorphism for lax.top_k
  jax/_src/lax/lax.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#15545 DOC: add docstrings for callback functions
  docs/jax.rst
  jax/_src/callback.py
  jax/_src/debugging.py
Labels: pull ready

#15574 Fix ndarray comparision in sharding_impls.py
  jax/_src/sharding_impls.py
Labels: kokoro:force-run, pull ready

#15569 Checkify: close over all arguments.
  jax/_src/checkify.py
  tests/checkify_test.py
Labels: pull ready

#15589 Change np.prod->math.prod
  benchmarks/api_benchmark.py
  jax/_src/core.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/linalg.py
  jax/_src/lax/slicing.py
  jax/_src/maps.py
  jax/_src/mesh.py
  jax/_src/nn/initializers.py
  jax/_src/numpy/reductions.py
  jax/_src/prng.py
  jax/_src/scipy/signal.py
  jax/_src/sharding_specs.py
  jax/_src/test_util.py
  jax/experimental/host_callback.py
  jax/experimental/jax2tf/impl_no_xla.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/back_compat_test.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  jax/experimental/jax2tf/tests/sharding_test.py
  jax/experimental/sparse/bcoo.py
  tests/array_test.py
  tests/custom_object_test.py
  tests/lax_numpy_test.py
  tests/lax_test.py
  tests/pjit_test.py
  tests/pmap_test.py
  tests/random_test.py
  tests/sparse_test.py
  tests/sparsify_test.py
  tests/xmap_test.py
Labels: pull ready

#15592 [shard-map] handle scalar residuals in post_process partial eval
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#15602 [shard-map] tweak error message to suggest P() for scalars
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#15563 [multi-node CI] Try to WAR date not working
  .github/workflows/slurm_job_scripts/run_e2e_t5x_tests.sub
Labels: pull ready

#15620 fix custom_jvp docs typo
  docs/notebooks/Custom_derivative_rules_for_Python_code.ipynb
  docs/notebooks/Custom_derivative_rules_for_Python_code.md
Labels: pull ready

#15619 `jit` the threefry seed function
  jax/_src/prng.py
  tests/random_test.py
Labels: pull ready

#15621 fix opaque dtype case of `dtypes.dtype`
  jax/_src/dtypes.py
  tests/random_test.py
Labels: pull ready

#15408 [shape_poly] Lowering sharding annotations in presence of dynamic shapes
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  jax/_src/maps.py
  jax/_src/pjit.py
  jax/experimental/jax2tf/tests/sharding_test.py
  jax/experimental/shard_map.py
Labels: pull ready

#15630 [NVIDIA nightly CI] Print the error
  .github/workflows/slurm_job_scripts/run_e2e_t5x_tests.sub
Labels: pull ready

#15634 [typing] ignore zstandard in mypy
  pyproject.toml
Labels: pull ready

#15635 mypy: type-check ml_dtypes
  .pre-commit-config.yaml
  pyproject.toml
Labels: kokoro:force-run, pull ready

#15377 jax.numpy indexing: lower to dynamic_slice for more cases
  jax/_src/numpy/lax_numpy.py
  tests/array_test.py
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#15636 Implement iDCT and iDCTN
  docs/jax.scipy.rst
  jax/_src/scipy/fft.py
  jax/scipy/fft.py
  tests/scipy_fft_test.py
Labels: pull ready

#15643 BUG: fix x.at[i].apply() with non-unit slice sizes
  jax/_src/lax/slicing.py
  jax/_src/numpy/array_methods.py
  tests/lax_numpy_indexing_test.py
Labels: kokoro:force-run, pull ready

#15639 checkify: dynamic_update_slice OOB index check
  jax/_src/checkify.py
  tests/checkify_test.py
Labels: pull ready

#15610 jax.Array: dynamically define abstract methods
  jax/_src/core.py
  jax/_src/numpy/array_methods.py
  jax/_src/prng.py
Labels: pull ready

#15658 jax.scipy.special: fix gradient for xlogy & xlog1py
  jax/_src/scipy/special.py
  tests/lax_scipy_test.py
Labels: pull ready

#15662 [CI] pytest* just got removed. Fix the CI due to this missing file.
  .github/workflows/nightly-ci-multiprocess-gpu.yml
  .github/workflows/slurm_job_scripts/run_e2e_t5x_tests.sub
Labels: pull ready

#15666 DOC: explicitly mention io_callback in FAQ
  docs/faq.rst
Labels: pull ready

#15673 Make i0e gradient test more robust
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#15656 feat (scipy.special): Add a xla version of scipy.special.gamma function
  docs/jax.scipy.rst
  jax/_src/scipy/special.py
  jax/scipy/special.py
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#15665 Use the traceback of the call site when assigning a source location t…
  jax/_src/core.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/pjit.py
  tests/BUILD
  tests/source_info_test.py
Labels: pull ready

#15664 Update TPU install on main docs page
  docs/index.rst
Labels: pull ready

#15671 jnp.delete: add assume_unique_indices for JIT-compatibility
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#15698 jax.errors: set obj.__module__ to public module
  jax/_src/errors.py
  jax/_src/util.py
Labels: pull ready

#15700 Add test framework for module attribute
  jax/_src/errors.py
  jax/_src/nn/initializers.py
  jax/nn/initializers.py
  tests/BUILD
  tests/package_structure_test.py
Labels: pull ready

#15702 jnp.array: internal cleanup related to DeviceArray removal
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#15694 [djax] handle simple reshapes and size-0 checks
  jax/_src/core.py
  jax/_src/numpy/array_methods.py
  tests/dynamic_api_test.py
Labels: pull ready

#15707 Fix typo in `random.pareto` docstring
  jax/_src/random.py
Labels: pull ready

#15704 internal: remove aliasing of builtins from lax_numpy
  jax/_src/lax/control_flow/loops.py
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#15720 custom prng: remove stackable override for jnp.concatenate
  jax/_src/dtypes.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
  jax/_src/prng.py
  tests/random_test.py
Labels: pull ready

#15721 random.KeyArray: more comprehensive operator tests
  tests/random_test.py
Labels: pull ready

#15724 KeyArray: remove _stackable registration mechanism
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
  jax/_src/prng.py
  tests/random_test.py
Labels: pull ready

#15677 add custom_jvp for jax.nn.softmax
  jax/__init__.py
  jax/_src/config.py
  jax/_src/nn/functions.py
  tests/nn_test.py
Labels: pull ready

#15457 [jax2tf] Refactor and simplify jax2tf.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/jax_export.py
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/back_compat_test.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#15731 [jax2tf] Fix numpy deprecation warning in test harness
  jax/experimental/jax2tf/tests/primitive_harness.py
Labels: pull ready

#15725 KeyArray: improve errors for unimplemented primitives
  jax/_src/lax/lax.py
  jax/_src/lax/utils.py
  tests/random_test.py
Labels: pull ready

#15741 fix pjit_test:testWithCustomPRNGKey
  tests/pjit_test.py
Labels: pull ready

#15740 PRNGKeyArray: fix compatibility with eval_shape
  jax/_src/api.py
  jax/_src/dtypes.py
  tests/random_test.py
Labels: kokoro:force-run, pull ready

#15737 grad(entr)(0.0): return inf instead of NaN
  jax/_src/scipy/special.py
  tests/lax_scipy_test.py
Labels: pull ready

#15744 Make shard_map_test compatible with custom_prng
  tests/shard_map_test.py
Labels: pull ready

#15743 PRNGKeyArray: make compatible with jnp.result_type
  jax/_src/dtypes.py
  tests/random_test.py
Labels: pull ready

#15746 PRNGKeyArray: allow opaque dtype passed as dtype arg
  jax/_src/dtypes.py
  jax/_src/numpy/lax_numpy.py
  tests/random_test.py
Labels: pull ready

#15745 Add test of private xlogx gradient
  tests/lax_scipy_test.py
Labels: pull ready

#15732 [jax2tf] Fix float0 representation under native serialization
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#15755 Document jax.lax.with_sharding_constraint
  docs/jax.lax.rst
  jax/_src/pjit.py
  jax/lax/__init__.py
Labels: pull ready

#15748 PRNGKeyArray: implement scatter/gather via .at()
  jax/_src/lax/slicing.py
  jax/_src/prng.py
  tests/random_test.py
Labels: pull ready

#15757 KeyArray: better errors for operators
  jax/_src/prng.py
  tests/random_test.py
Labels: pull ready

#15753 [shape_poly] Refactor the unification of the argument abstract value with the actual arguments
  jax/_src/core.py
  jax/_src/interpreters/mlir.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/jax_export.py
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/jax_export_test.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#15770 [call_tf] Some cleanup of call_tf implementation
  jax/experimental/jax2tf/call_tf.py
  jax/experimental/jax2tf/tests/call_tf_test.py
Labels: pull ready

#15790 DOC: document jax.experimental.sparse.linalg
  docs/jax.experimental.sparse.rst
  jax/experimental/sparse/linalg.py
Labels: documentation, pull ready
