Repository jax-ml/jax, pull requests merged in 2023-08, with the labels that each got.

#16735 `jax.debug.breakpoint` now supports being DCE'd. Drive-by: fix #16186
  jax/_src/debugger/core.py
Labels: pull ready

#16900 [shape_poly] Fix handling of dot_general with different lhs_dtype and rhs_type
  jax/_src/lax/lax.py
  jax/experimental/jax2tf/g3doc/jax_primitives_coverage.md
  jax/experimental/jax2tf/g3doc/primitives_with_limited_support.md
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
  jax/experimental/jax2tf/tests/jax_primitives_coverage_test.py
  jax/experimental/jax2tf/tests/primitive_harness.py
Labels: pull ready

#16843 [shmap-partial-auto] start adding partial auto / partial manual to shmap
  jax/experimental/shard_map.py
Labels: pull ready

#16932 Fix type annotations for jnp.where
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#16933 Implement jax.numpy.place with required inplace parameter
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#16947 Improve the sharding documentation.
  docs/jax.sharding.rst
  jax/_src/partition_spec.py
  jax/_src/sharding.py
  jax/_src/sharding_impls.py
Labels: pull ready

#16940 Add initial documentation for Pallas
  docs/_static/pallas/BlockSpec.png
  docs/_static/pallas/grid.png
  docs/conf.py
  docs/pallas/index.rst
  docs/pallas/quickstart.ipynb
  docs/pallas/quickstart.md
  docs/user_guides.rst
Labels: pull ready

#16949 Tracebacks no longer have JAX-internal frames prepended by default
  jax/_src/config.py
  jax/_src/traceback_util.py
  jax/errors.py
  tests/errors_test.py
Labels: pull ready

#16927 fix(docs): typo in `jax.lax.scan`
  jax/_src/lax/control_flow/loops.py
Labels: pull ready

#16953 [Pallas] Add Pallas design doc
  docs/_static/pallas/pallas_flow.png
  docs/conf.py
  docs/pallas/design.md
  docs/pallas/index.rst
Labels: pull ready

#16979 Documented the shortening of tracebacks
  CHANGELOG.md
Labels: pull ready

#16938 Add autodiff rules for spsolve_p
  jax/experimental/sparse/linalg.py
  tests/sparse_test.py
Labels: pull ready

#16981 Crash fix from ndim
  jax/_src/lax/lax.py
Labels: pull ready

#16975 Disable some tests that appear to crash on Windows.
  tests/sparse_test.py
Labels: pull ready

#16965 Add support for float8_e4m3fnuz and float8_e5m2fnuz.
  jax/_src/dtypes.py
  jax/_src/interpreters/mlir.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/public_test_util.py
  jax/_src/random.py
  jax/_src/test_util.py
  jax/numpy/__init__.py
  tests/dtypes_test.py
Labels: pull ready

#16960 Add `random.triangular` and `random.lognormal`
  docs/jax.random.rst
  jax/_src/random.py
  jax/random.py
  tests/random_test.py
Labels: pull ready

#16972 ENH: Update numpy exceptions imports
  jax/_src/lax/lax.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/reductions.py
  jax/_src/util.py
  tests/lax_autodiff_test.py
  tests/lax_numpy_indexing_test.py
  tests/lax_numpy_reducers_test.py
  tests/lax_numpy_test.py
  tests/lax_test.py
Labels: pull ready

#17007 DOC: callback doc is no longer work-in-progress
  docs/notebooks/external_callbacks.ipynb
  docs/notebooks/external_callbacks.md
Labels: pull ready

#16987 [Pallas] Fix rendering of math in quickstart
  docs/pallas/quickstart.ipynb
  docs/pallas/quickstart.md
Labels: pull ready

#16971 Add a guide for writing Pallas TPU kernels
  docs/pallas/index.rst
  docs/pallas/tpu.rst
Labels: pull ready

#17015 [pallas] skip indexing tests when hypothesis not available
  tests/pallas/indexing_test.py
Labels: kokoro:force-run, pull ready

#17032 jax.dtypes.extended: fix docstring example
  jax/_src/dtypes.py
Labels: pull ready

#17042 Fix for log-normal prior in example.
  examples/gaussian_process_regression.py
Labels: pull ready

#17069 jnp.unpackbits: fix handling of count & add tests
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#17080 Add requests dependency to jax[tpu]
  setup.py
Labels: pull ready

#17054 Add jnp.ufunc and jnp.frompyfunc
  CHANGELOG.md
  docs/jax.numpy.rst
  jax/_src/numpy/ufunc_api.py
  jax/numpy/__init__.py
  tests/BUILD
  tests/lax_numpy_test.py
  tests/lax_numpy_ufuncs_test.py
Labels: pull ready

#17086 [jax_export] Add backwards compatibility tests for shape_assertion.
  jax/experimental/jax2tf/tests/back_compat_test.py
  jax/experimental/jax2tf/tests/back_compat_test_util.py
  jax/experimental/jax2tf/tests/back_compat_testdata/stablehlo_dynamic_top_k.py
  jax/experimental/jax2tf/tests/back_compat_tf_test.py
Labels: pull ready

#17103 Ignore numpy deprecation warning
  pyproject.toml
Labels: kokoro:force-run, pull ready

#17101 jnp.ufunc: add __hash__ method and jit methods by default
  jax/_src/numpy/ufunc_api.py
  tests/lax_numpy_ufuncs_test.py
Labels: pull ready

#17108 de-emphasize internal array implementation type in key array `repr`
  jax/_src/prng.py
Labels: kokoro:force-run, pull ready

#17109 Small Cloud TPU CI debugging improvements
  .github/workflows/cloud-tpu-ci-nightly.yml
Labels: pull ready

#17115 jnp.ufunc: minor cleanups & test fixes
  jax/_src/numpy/ufunc_api.py
  tests/lax_numpy_ufuncs_test.py
Labels: pull ready

#16733 jnp.einsum: lower to mixed-precision dot_general when possible
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_einsum_test.py
Labels: pull ready

#17141 Update JAX F.A.Q. to remove an outdated reference
  docs/faq.rst
Labels: kokoro:force-run, pull ready

#17145 Fix mypy error on Python 3.9
  pyproject.toml
Labels: pull ready

#17142 Create lax.polygamma with native HLO lowering
  docs/jax.lax.rst
  jax/_src/lax/special.py
  jax/_src/scipy/special.py
  jax/experimental/jax2tf/jax2tf.py
  jax/lax/__init__.py
Labels: pull ready

#17147 CI: bump mypy to version 1.5.0
  .pre-commit-config.yaml
  jax/_src/api.py
Labels: pull ready

#17149 Fix type annotation for tree_util.default_registry
  jax/_src/api.py
  jax/_src/interpreters/pxla.py
  jax/_src/pjit.py
  jax/_src/tree_util.py
Labels: pull ready

#17154 [shape_poly] Relax the limit on the number of error inputs for shape assertions
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/jax_export_test.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#17152 [jax2tf] Fix for dot_general with different dtypes for graph serialization
  jax/experimental/jax2tf/impl_no_xla.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
  jax/experimental/jax2tf/tests/primitive_harness.py
Labels: pull ready

#17163 Add missing jax.scipy.stats docs
  docs/jax.scipy.rst
Labels: pull ready

#17160 deprecate jax.numpy.issubsctype
  docs/jax.numpy.rst
  jax/_src/dtypes.py
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.py
Labels: pull ready

#17144 Create lax.zeta with native HLO lowering
  docs/jax.lax.rst
  jax/_src/lax/special.py
  jax/_src/scipy/special.py
  jax/experimental/jax2tf/jax2tf.py
  jax/lax/__init__.py
  tests/lax_scipy_special_functions_test.py
  tests/lax_scipy_test.py
Labels: pull ready

#17164 Update JAX README.md - remove jax.example_libraries, stax
  README.md
Labels: pull ready

#17169 Fix typo in hlo_helpers.py
  jaxlib/hlo_helpers.py
Labels: pull ready

#17181 Improve jax.nn documentation.
  jax/_src/nn/functions.py
Labels: kokoro:force-run, pull ready

#17182 Deprecate jax.scipy.linalg.tril and jax.scipy.linalg.triu.
  CHANGELOG.md
  jax/scipy/linalg.py
Labels: pull ready

#17184 Replace references to DeviceArray with Array.
  cloud_tpu_colabs/Pmap_Cookbook.ipynb
  docs/autodidax.ipynb
  docs/autodidax.md
  docs/autodidax.py
  docs/jax-101/01-jax-basics.ipynb
  docs/jax-101/01-jax-basics.md
  docs/jax-101/02-jitting.ipynb
  docs/jax-101/03-vectorization.ipynb
  docs/jax-101/04-advanced-autodiff.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
  docs/notebooks/Custom_derivative_rules_for_Python_code.ipynb
  docs/notebooks/Custom_derivative_rules_for_Python_code.md
  docs/notebooks/autodiff_cookbook.ipynb
  docs/notebooks/external_callbacks.ipynb
  docs/notebooks/thinking_in_jax.ipynb
  docs/notebooks/vmapped_log_probs.ipynb
  jax/_src/array.py
  jax/_src/core.py
  jax/_src/dlpack.py
  jax/_src/interpreters/batching.py
  jax/_src/interpreters/pxla.py
  jax/_src/numpy/array_methods.py
  jax/_src/profiler.py
  jax/_src/sharding_specs.py
  jax/experimental/array_serialization/serialization.py
  jax/experimental/jax2tf/call_tf.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/bcsr.py
  tests/api_test.py
  tests/array_test.py
  tests/dtypes_test.py
  tests/lax_control_flow_test.py
  tests/lax_numpy_test.py
  tests/multiprocess_gpu_test.py
  tests/pickle_test.py
  tests/pmap_test.py
Labels: pull ready

#17202 special.logsumexp: fix incorrect annotation
  jax/_src/ops/special.py
Labels: pull ready

#17060 Add a link to JAX Toolbox containers
  README.md
Labels: pull ready

#17204 stats.norm.sf: more accurate values near zero
  jax/_src/scipy/stats/norm.py
  jax/scipy/stats/norm.py
  tests/scipy_stats_test.py
Labels: pull ready

#17208 Add Kaggle TPU VM link, update Distributed Arrays and Auto Parallelization guide
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.ipynb
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.md
Labels: pull ready

#17233 Deprecate jax.numpy.row_stack
  CHANGELOG.md
  docs/jax.numpy.rst
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
Labels: pull ready

#17206 jax.scipy.stats: add logsf & make sf more accurate near zero
  docs/jax.scipy.rst
  jax/_src/scipy/stats/beta.py
  jax/_src/scipy/stats/cauchy.py
  jax/_src/scipy/stats/chi2.py
  jax/_src/scipy/stats/gamma.py
  jax/_src/scipy/stats/truncnorm.py
  jax/scipy/stats/beta.py
  jax/scipy/stats/cauchy.py
  jax/scipy/stats/chi2.py
  jax/scipy/stats/gamma.py
  tests/scipy_stats_test.py
Labels: pull ready

#17225 [random] add jax_legacy_prng_key flag
  jax/__init__.py
  jax/_src/config.py
  jax/_src/random.py
  tests/random_test.py
Labels: pull ready

#16419 fix pow_p jvp rule at x=0. y=0
  jax/_src/lax/lax.py
  jax/_src/lax/utils.py
  jax/_src/numpy/ufuncs.py
  jax/_src/numpy/util.py
  tests/dynamic_api_test.py
  tests/lax_autodiff_test.py
Labels: pull ready

#17234 Default to PJRT TPU runtime instead of StreamExecutor on older jaxlibs.
  jax/_src/cloud_tpu_init.py
Labels: pull ready

#17016 [custom-jvp/vjp] allow rules to be run more than once, explicitly manage store lifetimes
  jax/_src/custom_derivatives.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/linear_util.py
  jax/experimental/host_callback.py
  tests/api_test.py
  tests/pytorch_interoperability_test.py
Labels: pull ready

#17253 Add jax.scipy.special.bernoulli
  docs/jax.scipy.rst
  jax/_src/scipy/special.py
  jax/scipy/special.py
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#17262 Fix tolerance on bernoulli test
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#17261 Deprecate jax.numpy.in1d.
  CHANGELOG.md
  jax/numpy/__init__.py
  pyproject.toml
Labels: pull ready

#17271 Fix typo in shape_poly_test.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#17270 Updated versions of pre-commit hooks and modified files accordingly.
  .pre-commit-config.yaml
Labels: pull ready

#17276 Remove dtypes_test.py:testFinfo
  tests/dtypes_test.py
Labels: pull ready

#17289 Update nanobind version to 1.5.2.
  third_party/nanobind/workspace.bzl
Labels: pull ready

#17295 lax.pow: fix shape mismatch failure in jvp rule
  jax/_src/lax/lax.py
  tests/lax_autodiff_test.py
Labels: pull ready

#17302 Add generated MLIR _enum_gen.py files to jaxlib wheel.
  jaxlib/tools/build_wheel.py
Labels: pull ready

#17305 Fix typo in jnp.interp docstring.
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#17275 jnp.ufunc: support where argument in ufunc.reduce
  jax/_src/numpy/ufunc_api.py
  tests/lax_numpy_ufuncs_test.py
Labels: pull ready

#17322 Update __init__.py to include dlpack module
  jax/__init__.py
Labels: pull ready

#17113 jnp.ufunc: add fast paths for add/prod reductions
  jax/_src/numpy/ufunc_api.py
  tests/lax_numpy_ufuncs_test.py
Labels: pull ready

#17300 Tests: set jax_legacy_prng_key='error'
  jax/_src/test_util.py
  jax/experimental/jax2tf/tests/back_compat_test.py
  jax/experimental/jax2tf/tests/jax_primitives_coverage_test.py
  jax/experimental/jax2tf/tests/tf_test_util.py
  tests/api_test.py
  tests/batching_test.py
  tests/checkify_test.py
  tests/experimental_rnn_test.py
  tests/for_loop_test.py
  tests/jet_test.py
  tests/lax_control_flow_test.py
  tests/linalg_test.py
  tests/multi_device_test.py
  tests/nn_test.py
  tests/pickle_test.py
  tests/pmap_test.py
  tests/random_test.py
  tests/scipy_stats_test.py
  tests/shard_map_test.py
  tests/sparse_test.py
  tests/state_test.py
  tests/stax_test.py
  tests/x64_context_test.py
  tests/xmap_test.py
Labels: pull ready

#17331 DOC: mention static values in debug.print docs
  docs/debugging/print_breakpoint.md
Labels: pull ready

#17228 DOC: re-enable execution of thinking_in_jax.ipynb
  docs/conf.py
  docs/notebooks/thinking_in_jax.ipynb
  docs/notebooks/thinking_in_jax.md
Labels: documentation, pull ready

#17334 Turn down jax_persistent_cache_min_compile_time_secs logging from info to debug.
  jax/_src/compiler.py
Labels: pull ready

#17337 DOC: add missing docs for jax.random functions
  docs/jax.extend.rst
  docs/jax.random.rst
Labels: pull ready

#17351 Fix mypy error
  jax/_src/mesh.py
Labels: pull ready

#17369 Update versions and changelog post 0.4.15 release
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: pull ready

#17355 jax.tree_util: use standard deprecation framework for deprecated items
  jax/_src/tree_util.py
  jax/tree_util.py
Labels: pull ready

#17353 Deprecate the contents of jax.prng
  CHANGELOG.md
  jax/prng.py
  tests/random_test.py
Labels: pull ready

#17368 [shard-map] add rewrite for efficient transposition
  docs/jep/17111-shmap-transpose.md
  docs/jep/index.rst
  jax/_src/core.py
  jax/_src/custom_derivatives.py
  jax/_src/interpreters/ad.py
  jax/_src/lax/lax.py
  jax/_src/lax/parallel.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#17316 [export] Implement the calling convention for exporting with multi-platform lowering
  jax/_src/interpreters/mlir.py
  jax/experimental/jax2tf/jax_export.py
  jax/experimental/jax2tf/tests/back_compat_test_util.py
  jax/experimental/jax2tf/tests/jax_export_test.py
Labels: pull ready

#17388 typing: annotate NumpyComplexWarning
  jax/_src/util.py
Labels: pull ready
