Repository jax-ml/jax, pull requests merged in 2023-06, with the labels that each got.

#16150 Improve error message for reverse-mode of while loop
  jax/_src/lax/control_flow/loops.py
Labels: pull ready

#16199 [shape_poly] Keep track of whether a lowering contains shape polymorphism
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  jax/experimental/jax2tf/jax_export.py
  jax/experimental/jax2tf/tests/back_compat_test.py
  jax/experimental/jax2tf/tests/jax_export_test.py
Labels: pull ready

#15382 Add key path related guide & code to the documentation.
  docs/jax-101/05.1-pytrees.ipynb
  docs/jax-101/05.1-pytrees.md
  docs/jax.tree_util.rst
  jax/_src/tree_util.py
Labels: pull ready

#16212 DOC: fix doc formatting
  docs/jax-101/05.1-pytrees.ipynb
  docs/jax-101/05.1-pytrees.md
Labels: pull ready

#16168 Remove some dead code (followup to #16159)
  jax/_src/interpreters/xla.py
Labels: pull ready

#16189 Update profiling docs.
  docs/device_memory_profiling.md
  docs/profiling.md
Labels: pull ready

#16123 revise vmap's axis_frame-getting logic
  jax/_src/interpreters/batching.py
Labels: pull ready

#16209 jax.nn.softmax: fix fill value when where is specified
  jax/_src/nn/functions.py
  tests/nn_test.py
Labels: pull ready

#16217 jnp.roll: more efficient implementation for static shifts
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#16224 Fix incorrect wrapped docstring of `jax.scipy.special.gamma`
  jax/_src/scipy/special.py
Labels: pull ready

#16213 custom prng: add shard methods to PRNGKeyArrayImpl
  jax/_src/array.py
  jax/_src/prng.py
  tests/random_test.py
Labels: pull ready

#16232 Deprecate jax.numpy functions alltrue, sometrue, product, cumproduct
  CHANGELOG.md
  docs/jax.numpy.rst
  jax/_src/numpy/reductions.py
  jax/numpy/__init__.py
Labels: pull ready

#16230 CI: set maxfail=20 for nightly tests
  .github/workflows/upstream-nightly.yaml
Labels: pull ready

#16231 Change uses of np.product to np.prod
  jax/_src/interpreters/xla.py
  jax/_src/third_party/numpy/linalg.py
  jax/experimental/mesh_utils.py
Labels: pull ready

#16240 Add .editorconfig
  .editorconfig
Labels: pull ready

#16256 Include SASS/PTX for Hopper GPUs.
  .bazelrc
  CHANGELOG.md
Labels: pull ready, NVIDIA GPU

#16234 [shape_poly] Improve DimExpr comparison for "a - mod(b, a) >= 1"
  jax/_src/numpy/lax_numpy.py
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#16265 Allow duck-typed inputs to zeros_like, ones_like, etc.
  jax/_src/lax/lax.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/typing.py
  tests/lax_numpy_test.py
Labels: pull ready

#16283 fix key opaque dtype physical HLO sharding
  jax/_src/interpreters/mlir.py
  jax/_src/prng.py
  tests/shard_map_test.py
Labels: kokoro:force-run, pull ready

#16284 Disable threading in MLIR contexts.
  jax/_src/interpreters/mlir.py
Labels: pull ready

#15637 Raise a better error
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/partial_eval.py
  tests/api_test.py
Labels: pull ready

#16299 fix checkify + custom_vjp after symbolic zeros change
  jax/_src/checkify.py
  tests/checkify_test.py
Labels: pull ready

#16309 Typo: remove stray tick in jax.numpy docs
  docs/jax.numpy.rst
Labels: pull ready

#16271 Mark jax.abstract_arrays as deprecated.
  CHANGELOG.md
  docs/notebooks/How_JAX_primitives_work.ipynb
  docs/notebooks/How_JAX_primitives_work.md
  jax/__init__.py
  jax/abstract_arrays.py
Labels: pull ready

#16307 Fix test_util for new float8 type
  jax/_src/public_test_util.py
Labels: pull ready

#16276 Add maxfail=20 to some pytest commands, take 2
  .github/workflows/ci-build.yaml
Labels: pull ready

#16072 Convert piles from concatenated to stacked-and-padded, and revive existing tests
  jax/_src/core.py
  jax/_src/interpreters/batching.py
  jax/_src/lax/lax.py
  jax/experimental/shard_map.py
  jax/interpreters/batching.py
  tests/dynamic_api_test.py
Labels: pull ready

#16305 Update WORKSPACE and setup.py for jax + jaxlib 0.4.12 release
  WORKSPACE
  setup.py
Labels: pull ready

#16327 Update versions and changelog post 0.4.12 release
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: pull ready

#16364 Fix cuda12 pip install.
  CHANGELOG.md
  setup.py
Labels: pull ready

#16339 Fix `BatchTrace.process_call`.
  jax/_src/interpreters/batching.py
Labels: pull ready

#16367 Don't include the --subcommands on the Bazel command line for Windows…
  .github/workflows/wheel_win_x64.yml
  .github/workflows/windows_ci.yml
Labels: pull ready

#16371 build/BUILD.bazel: remove unused import
  build/BUILD.bazel
Labels: pull ready

#16347 [jax2tf] Add native_lowering_disabled_checks parameter to jax2tf.convert
  CHANGELOG.md
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/__init__.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/jax_export.py
  jax/experimental/jax2tf/tests/back_compat_test.py
  jax/experimental/jax2tf/tests/call_tf_test.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/jax_export_test.py
Labels: pull ready

#16378 Use larger runners for Windows CI.
  .github/workflows/windows_ci.yml
Labels: pull ready

#16379 Update OS in windows CI to use 16 core variant.
  .github/workflows/windows_ci.yml
Labels: kokoro:force-run, pull ready

#16381 Try another name for the Windows CI runner.
  .github/workflows/windows_ci.yml
Labels: pull ready

#16383 Windows CI: write wheel into usual location.
  .github/workflows/windows_ci.yml
Labels: pull ready, Windows

#16211 [shape_poly] Improve compile-time shape checking.
  jax/_src/test_util.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/jax_export.py
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/jax_export_test.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#16324 Expand RaggedAxis representation to support raggedly-shaped broadcasting
  jax/_src/core.py
  jax/_src/interpreters/batching.py
  jax/_src/lax/lax.py
  tests/dynamic_api_test.py
Labels: pull ready

#16384 Windows CI improvements
  .github/workflows/wheel_win_x64.yml
  .github/workflows/windows_ci.yml
Labels: pull ready

#16388 Windows CI fixes:
  .github/workflows/windows_ci.yml
Labels: pull ready, Windows

#16389 Window CI: fix syntax error.
  .github/workflows/wheel_win_x64.yml
  .github/workflows/windows_ci.yml
Labels: pull ready

#16391 Windows CI: don't fail-fast.
  .github/workflows/wheel_win_x64.yml
Labels: pull ready, Windows

#16390 Fix FileExistsError for tests/gfile_cache_test.py::FileSystemCacheTest::test_threads
  jax/_src/gfile_cache.py
Labels: pull ready, Windows

#16344 Cleanup: Remove unused variable in lax.scan test
  tests/lax_control_flow_test.py
Labels: pull ready

#16405 Remove matplotlib from the test requirements.
  build/test-requirements.txt
  tests/lobpcg_test.py
Labels: kokoro:force-run, pull ready, Windows

#16408 Add NumPy as a test requirement.
  build/test-requirements.txt
Labels: pull ready, Windows

#16410 Tag the wheels generated by the Windows CI as dev versions.
  .github/workflows/windows_ci.yml
Labels: kokoro:force-run, pull ready, Windows

#16399 jax errors: improve leading info in error docs
  jax/_src/errors.py
Labels: pull ready

#16401 DOC: fix formatting in FAQ
  docs/faq.rst
Labels: pull ready

#16425 [shape_poly] Change lowering for shape polymorphism to simplify shape refinement
  jax/experimental/jax2tf/jax_export.py
Labels: pull ready

#16423 Made scatter-transpose more efficient
  jax/_src/lax/slicing.py
Labels: pull ready

#16050 Added argument `jax.linearize(..., has_aux=...)`
  jax/_src/api.py
  tests/api_test.py
Labels: pull ready

#16407 Remove older plugin device integration.
  .bazelrc
  build/build.py
  jax/_src/xla_bridge.py
Labels: pull ready

#16392 Fix invalid cond param linear of type str, tuple of bool required:\nmulti\nline
  jax/_src/lax/control_flow/common.py
Labels: pull ready

#16444 Enable colored output in pytest under github actions.
  .github/workflows/ci-build.yaml
  .github/workflows/cloud-tpu-ci-nightly.yml
  .github/workflows/upstream-nightly.yaml
  .github/workflows/wheel_win_x64.yml
  .github/workflows/windows_ci.yml
Labels: pull ready

#16397 [shape_poly] Fix the lowering of lax.dynamic_slice with shape poly
  jax/_src/interpreters/mlir.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#16427 Custom PRNG: fix incorrect assertion in select lowering rule
  jax/_src/lax/lax.py
  tests/random_test.py
Labels: pull ready

#16450 Fix xla_bridge_test.py test failures.
  .github/workflows/wheel_win_x64.yml
  .github/workflows/windows_ci.yml
  tests/xla_bridge_test.py
Labels: pull ready, Windows

#16451 Fix test failure in lax_control_flow_test.py on Windows due to line e…
  jax/_src/lax/control_flow/common.py
  tests/lax_control_flow_test.py
Labels: pull ready

#16452 Fix Windows portability problem in dtypes_test.py
  tests/dtypes_test.py
Labels: pull ready

#16453 Disable a test that fails under Windows with a NumPy exception.
  tests/lax_numpy_test.py
Labels: pull ready

#16454 Document how to enable concurrent kernel tracing on GPU.
  docs/profiling.md
Labels: documentation, kokoro:force-run, pull ready, NVIDIA GPU

#16406 Raise an exception if plugin initialization fails
  jax/_src/xla_bridge.py
  tests/xla_bridge_test.py
Labels: pull ready

#16458 Fix the docs build
  jax/_src/pjit.py
Labels: kokoro:force-run, pull ready

#16459 Don't allow the use of stale cache entries in Github actions CI.
  .github/workflows/ci-build.yaml
Labels: pull ready

#16478 [jax2tf] Refactor the backward compatibility tests.
  jax/experimental/jax2tf/tests/back_compat_test.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_ducc_fft.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_lapack_geqrf.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_lapack_syev.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cuda_cusolver_geqrf.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cuda_cusolver_syev.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cuda_threefry2x32.py
  jax/experimental/jax2tf/tests/back_compat_testdata/tpu_ApproxTopK.py
  jax/experimental/jax2tf/tests/back_compat_testdata/tpu_Eigh.py
  jax/experimental/jax2tf/tests/back_compat_testdata/tpu_Lu.py
  jax/experimental/jax2tf/tests/back_compat_testdata/tpu_Qr.py
  jax/experimental/jax2tf/tests/back_compat_testdata/tpu_Sharding.py
Labels: pull ready

#16480 [jax2tf] Rename some backwards compatibility tests.
  jax/experimental/jax2tf/tests/back_compat_test.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_eigh_lapack_syev.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_qr_lapack_geqrf.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cuda_eigh_cusolver_syev.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cuda_qr_cusolver_geqrf.py
Labels: pull ready

#16483 Disable some problematic rotation tests
  tests/scipy_spatial_test.py
Labels: pull ready

#16486 Fix problematic rotation tests
  tests/scipy_spatial_test.py
Labels: pull ready

#16488 Fix xla_bridge_test test failures under Windows.
  tests/xla_bridge_test.py
Labels: pull ready

#16457 Add a CI presubmit that renders the documentation.
  .github/workflows/ci-build.yaml
  docs/notebooks/external_callbacks.ipynb
Labels: pull ready

#16489 Add a warning if a non-allowlisted plugin is used.
  jax/_src/xla_bridge.py
  tests/xla_bridge_test.py
Labels: pull ready

#16497 Rename Github actions so they have more consistent naming.
  .github/workflows/cloud-tpu-ci-nightly.yml
  .github/workflows/nightly-ci-multiprocess-gpu.yml
  .github/workflows/upstream-nightly.yaml
  .github/workflows/wheel_win_x64.yml
  .github/workflows/windows_ci.yml
Labels: kokoro:force-run, pull ready

#16498 [ROCm]: Updates defaults in build script
  build/rocm/build_rocm.sh
Labels: pull ready

#16333 profiler_test.py fixes and add coverage to Cloud TPU CI
  .github/workflows/cloud-tpu-ci-nightly.yml
  build/collect-profile-requirements.txt
  build/test-requirements.txt
  tests/profiler_test.py
Labels: pull ready

#16404 Errors: avoid printing tracer repr for concretization errors
  jax/_src/core.py
  jax/_src/errors.py
  tests/api_test.py
  tests/lax_numpy_test.py
Labels: better_errors, pull ready

#16484 random.key: error for non-scalar seeds.
  jax/_src/random.py
  tests/random_test.py
Labels: pull ready

#16499 Issue warning if JAX_USE_PJRT_C_API_ON_TPU=false
  jax/_src/cloud_tpu_init.py
Labels: pull ready

#16508 Add a link to the Apple Metal plugin to the JAX README.
  README.md
Labels: pull ready

#16527 Jax 0.4.13 release.
  .github/workflows/wheel_win_x64.yml
  CHANGELOG.md
  README.md
  WORKSPACE
  setup.py
Labels: kokoro:force-run, pull ready

#16531 Update version numbers and changelog post 0.4.13 release
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: pull ready

#16428 Custom PRNG: improve test coverage when enable_custom_prng=false
  tests/random_test.py
Labels: pull ready

#16514 Fix typos in documentation
  jax/_src/core.py
Labels: pull ready

#16386 Implement einsum for (at least some combinations) of arrays with ragged dimensions
  jax/_src/core.py
  jax/_src/interpreters/batching.py
  jax/_src/lax/lax.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
  tests/dynamic_api_test.py
Labels: pull ready

#16535 Drop support for numpy 1.21
  CHANGELOG.md
  build/build.py
  build/test-requirements.txt
  jaxlib/setup.py
  setup.py
  tests/api_test.py
  tests/array_interoperability_test.py
  tests/dtypes_test.py
  tests/lax_numpy_reducers_test.py
  tests/lax_numpy_test.py
  tests/scipy_stats_test.py
Labels: pull ready

#16487 jnp.convolve: add support for preferred_element_type
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#16533 Update README to mention Windows support.
  README.md
Labels: pull ready

#16467 [jax2tf] Add a safety check for which dialects are allowed in native serialization
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/jax_export.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/jax_export_test.py
Labels: pull ready

#16562 outline jitted threefry `split` and `fold_in` subroutines
  jax/_src/prng.py
Labels: pull ready

#16567 Fix integer overflow in gather batching rule
  jax/_src/lax/slicing.py
  tests/lax_test.py
Labels: pull ready

#16502 jax.interpreters.pxla: remove deprecated functions:
  CHANGELOG.md
  jax/interpreters/pxla.py
Labels: pull ready

#16581 add corner-case `cond` resolution fix to changelog
  CHANGELOG.md
Labels: pull ready

#16600 schur: fix broken jvp rule
  jax/_src/lax/linalg.py
Labels: pull ready
