Repository jax-ml/jax, pull requests merged in 2023-11, with the labels that each got.

#18340 [random] add more information to KeyArray deprecation error
  jax/random.py
Labels: pull ready

#18325 Update versions for jax + jaxlib 0.4.20 release
  setup.py
Labels: pull ready

#18295 Add a lax.platform_dependent API for writing platform-dependent code.
  jax/_src/lax/control_flow/__init__.py
  jax/_src/lax/control_flow/conditionals.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/lax/__init__.py
  tests/export_test.py
  tests/lax_control_flow_test.py
Labels: pull ready

#18354 Finish deprecation of allow_opaque_dtype
  jax/_src/dtypes.py
Labels: pull ready

#18363 Update versions and CHANGELOG after jax 0.4.20 release
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: kokoro:force-run, pull ready

#18376 Fix wording in TFDS example
  docs/notebooks/neural_network_with_tfds_data.ipynb
  docs/notebooks/neural_network_with_tfds_data.md
Labels: pull ready

#18137 JEP 18137: Scope of JAX NumPy & SciPy Wrappers
  docs/jep/18137-numpy-scipy-scope.md
  docs/jep/index.rst
Labels: pull ready, JEP

#18382 [random] better errors for unsupported operations on prng keys
  jax/_src/numpy/util.py
  tests/random_lax_test.py
  tests/random_test.py
Labels: pull ready

#18397 feat (scipy.special): Add beta function
  docs/jax.scipy.rst
  jax/_src/scipy/special.py
  jax/scipy/special.py
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#18379 jnp.nanmean: avoid integer overflow for large arrays
  jax/_src/numpy/reductions.py
Labels: pull ready

#18380 jnp.cross: account for numpy 2.0 deprecation
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#18072 Discussion: Change deprecation policy from NEP 29 to SPEC 0
  docs/deprecation.md
Labels: pull ready

#11625 Remove deprecated function jax.random.shuffle
  docs/jax.random.rst
  jax/random.py
  tests/random_lax_test.py
Labels: pull ready

#18411 Add Kaggle integration for JAX pmap cookbook
  cloud_tpu_colabs/Pmap_Cookbook.ipynb
Labels: pull ready

#18414 Make jax.scipy.optimize test compatible with upstream scipy
  tests/scipy_optimize_test.py
Labels: pull ready

#18413 [sparse] fix concretization error for nse
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/bcsr.py
  jax/experimental/sparse/util.py
Labels: pull ready

#18415 Fix dtype-related docs for cumsum/cumprod
  jax/_src/numpy/reductions.py
Labels: kokoro:force-run, pull ready

#18386 [Pallas]: Fix CUDA kernel grid dimensions that are too large in Y and Z
  jax/_src/pallas/triton/lowering.py
  tests/pallas/pallas_test.py
Labels: bug, pull ready, pallas

#18439 jax.nn.normalize: deprecate using standard framework
  jax/_src/nn/functions.py
  jax/nn/__init__.py
Labels: pull ready

#18431 jnp.histogram: avoid flattening input
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#18402 Fix hashcode for `HashablePartial` to get equal hashes for equal objects
  jax/_src/util.py
Labels: pull ready

#17973 [multihost_utils] fix docstring wording
  jax/experimental/multihost_utils.py
Labels: pull ready

#18396 [DOC] Fix the Custom operations for GPUs tutorial following API changes.
  docs/Custom_Operation_for_GPUs.md
  jax/_src/interpreters/mlir.py
Labels: pull ready

#18463 jnp.eye: handle larger-than int32 offsets
  jax/_src/lax/lax.py
  tests/lax_numpy_test.py
Labels: pull ready

#18409 [shape_poly] Fixes for shape polynorphism for jvp(scatter).
  jax/_src/lax/slicing.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#18469 jnp.unique: small implementation cleanup
  jax/_src/numpy/setops.py
Labels: pull ready

#18464 Annotate jax.numpy.atleast_xd functions
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.pyi
Labels: pull ready

#18458 Lightly proofread Pallas documentation.
  docs/pallas/design.md
  docs/pallas/quickstart.ipynb
  docs/pallas/quickstart.md
  docs/pallas/tpu.rst
Labels: pull ready

#18444 [random] support key dtype in custom_vjp
  jax/_src/interpreters/ad.py
  jax/_src/prng.py
  tests/random_test.py
Labels: pull ready

#18441 jnp.vectorize: support None arguments
  jax/_src/numpy/vectorize.py
  tests/lax_numpy_vectorize_test.py
Labels: pull ready

#18465 Annotate jaxpr
  jax/_src/core.py
  jax/_src/interpreters/partial_eval.py
Labels: pull ready

#18497 [shape_poly] Refactor shape_poly_test in preparation for moving out of jax2tf
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#18515 [export] Fix casts to and from dynamically shaped args for booleans
  jax/_src/interpreters/mlir.py
  jax/experimental/export/export.py
  tests/export_test.py
Labels: pull ready

#18532 add psum_scatter to docs index
  docs/jax.lax.rst
Labels: pull ready

#18533 Fix test_util.is_cloud_tpu()
  jax/_src/test_util.py
Labels: kokoro:force-run, pull ready

#18534 improve psum_scatter docstring (formatting and content)
  jax/_src/lax/parallel.py
Labels: pull ready

#17850 Doc about regression investigation.
  docs/contributor_guide.rst
  docs/investigating_a_regression.md
Labels: documentation, pull ready

#18527 Add nn.squareplus.
  CHANGELOG.md
  docs/faq.rst
  docs/jax.nn.rst
  jax/_src/nn/functions.py
  jax/nn/__init__.py
  tests/nn_test.py
Labels: pull ready

#18546 Fix boolean indexing check with newaxis
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#18499 Implementation of poch and hyp1f1
  docs/jax.scipy.rst
  jax/_src/scipy/special.py
  jax/scipy/special.py
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#18554 rot90 validate argument has ndim at least 2
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#18553 add error hint about common jnp.ones / jnp.zeros mistake
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#18559 CI: fix doc build
  docs/conf.py
Labels: pull ready

#18550 jax.vmap: improve docs & error for structured in_axes
  jax/_src/api.py
  jax/_src/api_util.py
  tests/api_test.py
Labels: better_errors, pull ready

#18552 Prefer `expand_dims` over `reshape`
  jax/_src/numpy/ufunc_api.py
  jax/_src/prng.py
  jax/_src/scipy/signal.py
Labels: pull ready

#18539 Switch from flake8 to Ruff
  .pre-commit-config.yaml
  docs/contributing.md
  docs/developer.md
  jax/_src/api.py
  jax/_src/interpreters/pxla.py
  jax/_src/jaxpr_util.py
  jax/_src/lax/parallel.py
  jax/_src/lib/mlir/__init__.py
  jax/_src/lib/mlir/dialects/__init__.py
  jax/_src/pallas/indexing.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pallas/triton/lowering.py
  jax/_src/scipy/fft.py
  jax/_src/tree_util.py
  jax/_src/xla_bridge.py
  jax/experimental/export/shape_poly.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/back_compat_test_util.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_cholesky_lapack_potrf.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_eig_lapack_geev.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_eigh_lapack_syev.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_lu_lapack_getrf.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_qr_lapack_geqrf.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_schur_lapack_gees.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_svd_lapack_gesdd.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cpu_triangular_solve_blas_trsm.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cuda_eigh_cusolver_syev.py
  jax/experimental/jax2tf/tests/back_compat_testdata/cuda_qr_cusolver_geqrf.py
  jax/experimental/jax2tf/tests/back_compat_testdata/stablehlo_dynamic_rng_bit_generator.py
  jax/experimental/jax2tf/tests/back_compat_testdata/stablehlo_dynamic_top_k.py
  jax/experimental/jax2tf/tests/back_compat_testdata/tpu_ApproxTopK.py
  jax/experimental/jax2tf/tests/back_compat_testdata/tpu_Eigh.py
  jax/experimental/jax2tf/tests/back_compat_testdata/tpu_Lu.py
  jax/experimental/jax2tf/tests/back_compat_testdata/tpu_Qr.py
  jax/experimental/jax2tf/tests/back_compat_testdata/tpu_stablehlo_dynamic_reduce_window.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  jax/experimental/mesh_utils.py
  jax/experimental/multihost_utils.py
  jax/experimental/pjit.py
  jax/lib/__init__.py
  jax/lib/xla_bridge.py
  jaxlib/mosaic/python/tpu.py
  jaxlib/tpu_mosaic.py
  pyproject.toml
  setup.cfg
  tests/ann_test.py
  tests/custom_object_test.py
  tests/export_test.py
  tests/linalg_test.py
  tests/tree_util_test.py
Labels: pull ready

#18566 go back to raising TypeError, not ValueError
  jax/_src/numpy/array_methods.py
Labels: kokoro:force-run, pull ready

#16099 Initial implementation of the Python Array API standard
  .github/workflows/jax-array-api.yml
  docs/jax.experimental.array_api.rst
  docs/jax.experimental.rst
  jax/BUILD
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_array_methods.py
  jax/experimental/array_api/_constants.py
  jax/experimental/array_api/_creation_functions.py
  jax/experimental/array_api/_data_type_functions.py
  jax/experimental/array_api/_dtypes.py
  jax/experimental/array_api/_elementwise_functions.py
  jax/experimental/array_api/_fft_functions.py
  jax/experimental/array_api/_indexing_functions.py
  jax/experimental/array_api/_linear_algebra_functions.py
  jax/experimental/array_api/_manipulation_functions.py
  jax/experimental/array_api/_searching_functions.py
  jax/experimental/array_api/_set_functions.py
  jax/experimental/array_api/_sorting_functions.py
  jax/experimental/array_api/_statistical_functions.py
  jax/experimental/array_api/_utility_functions.py
  jax/experimental/array_api/_version.py
  jax/experimental/array_api/fft.py
  jax/experimental/array_api/linalg.py
  jax/experimental/array_api/skips.txt
  pyproject.toml
Labels: pull ready

#18516 [shape_poly] Fix handling of core.non_negative_dim symbolic expressions.
  jax/experimental/export/export.py
  jax/experimental/export/shape_poly.py
  tests/export_test.py
Labels: pull ready

#18564 Deprecate passing of None to jax.numpy.array
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#18584 Move docs/tutorial to docs/tutorials
  docs/tutorials/advanced-autodiff.md
  docs/tutorials/advanced-compilation.md
  docs/tutorials/automatic-differentiation.md
  docs/tutorials/debugging.md
  docs/tutorials/external-callbacks.md
  docs/tutorials/index.rst
  docs/tutorials/installation.md
  docs/tutorials/jax-as-accelerated-numpy.md
  docs/tutorials/jax-internals.md
  docs/tutorials/jit-compilation.md
  docs/tutorials/parallelism.md
  docs/tutorials/profiling-and-performance.md
  docs/tutorials/quickstart.md
  docs/tutorials/random-numbers.md
  docs/tutorials/simple-neural-network.md
  docs/tutorials/single-host-sharding.md
  docs/tutorials/stateful-computations.md
  docs/tutorials/working-with-pytrees.md
Labels: documentation, pull ready

#18583 [array api] update array-api-tests
  .github/workflows/jax-array-api.yml
Labels: pull ready

#18369 Cleanup the code to pick lowering rules based on platform.
  jax/_src/interpreters/mlir.py
  jax/_src/lax/control_flow/conditionals.py
  tests/lax_control_flow_test.py
Labels: pull ready

#18593 Add missing f-strings identifiers in xeinsum error message
  jax/_src/lax/parallel.py
Labels: pull ready

#18228 Add `random.binomial`
  docs/jax.random.rst
  jax/_src/random.py
  jax/random.py
  tests/random_lax_test.py
Labels: pull ready

#18600 Document the compilation cache
  docs/jax.experimental.compilation_cache.rst
  docs/jax.experimental.rst
  jax/_src/compilation_cache.py
Labels: pull ready

#18608 CI: pin actions/setup-python & actions/github-script to recent release
  .github/workflows/ci-build.yaml
  .github/workflows/jax-array-api.yml
  .github/workflows/nightly-ci-multiprocess-gpu.yml
  .github/workflows/upstream-nightly.yaml
  .github/workflows/wheel_win_x64.yml
  .github/workflows/windows_ci.yml
Labels: pull ready

#18610 DOC: update package requirements
  docs/requirements.txt
Labels: pull ready

#18602 [shape_poly] Clean up the shape_poly_test.py
  tests/shape_poly_test.py
Labels: pull ready

#18616 JAX tutorials: add External Callbacks
  docs/tutorials/external-callbacks.md
  docs/tutorials/index.rst
Labels: documentation, pull ready

#18615 Apply #18220 with jupytext sync.
  docs/jax-101/04-advanced-autodiff.ipynb
  docs/jax-101/04-advanced-autodiff.md
Labels: kokoro:force-run, pull ready

#18626 JAX tutorials: add automatic vectorization
  docs/tutorials/automatic-vectorization.md
  docs/tutorials/index.rst
Labels: documentation, pull ready

#18563 random: clean up fold_in implementation
  jax/_src/random.py
Labels: pull ready

#18599 [shard_map] add eager axis_index implementation and tests
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#18628 Request specific version information in the bug template.
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: pull ready

#18634 improve error message for e.g. jnp.zeros(5)[:, 0]
  jax/_src/array.py
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#18627 JAX tutorials: add intro to jit compilation
  docs/tutorials/jit-compilation.md
Labels: documentation, pull ready

#18631 JAX tutorials: pseudorandom numbers
  docs/jep/9263-typed-keys.md
  docs/tutorials/random-numbers.md
Labels: documentation, pull ready

#18649 multiprocess_test: print error message on failure
  tests/multiprocess_gpu_test.py
Labels: pull ready

#18651 xla_bridge: add logic to avoid version skew
  jax/_src/xla_bridge.py
Labels: pull ready

#18646 version: fix commit hash extraction
  jax/version.py
Labels: pull ready

#18647 DOC: document preferred_element_type argument to dot functions
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#18652 small tweaks to jax.debug.print docstring
  jax/_src/debugging.py
Labels: pull ready

#18682 Fix debug_nans issue in sort
  jax/_src/lax/lax.py
Labels: pull ready

#18683 Fix sign of jax.scipy.special.gamma for negative inputs
  jax/_src/scipy/special.py
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#18685 [array-api] add simple smoketest target for standard CI testing
  tests/BUILD
  tests/array_api_test.py
Labels: pull ready

#18658 [shape_poly] Simplify the API for processing polymorphic_shape specifications
  jax/_src/internal_test_util/export_back_compat_test_util.py
  jax/_src/typing.py
  jax/experimental/export/export.py
  jax/experimental/export/shape_poly.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  tests/export_test.py
  tests/shape_poly_test.py
Labels: pull ready

#18684 Update array-api-tests to most recent commit
  .github/workflows/jax-array-api.yml
  pyproject.toml
Labels: pull ready

#18613 JAX Docs tutorials: quickstart
  docs/tutorials/automatic-differentiation.md
  docs/tutorials/installation.md
  docs/tutorials/jit-compilation.md
  docs/tutorials/quickstart.md
Labels: documentation, pull ready

#18660 Solution for https://github.com/google/jax/pull/18641
  docs/developer.md
Labels: pull ready

#18614 add jax.custom_gradient to readthedocs
  docs/jax.rst
Labels: pull ready

#18706 Fix grad of jnp.i0 at zero
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_operators_test.py
Labels: pull ready

#18712 Fix typo in deprecation warning
  jax/_src/numpy/util.py
Labels: pull ready

#18714 [sparse] canonicalize sparse shapes
  jax/experimental/sparse/_base.py
Labels: kokoro:force-run, pull ready

#18711 [shard-map] fix transpose replication checking bug with integer_pow
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#18718 [sparse] add sparsify support for conj_p
  jax/experimental/sparse/_base.py
  jax/experimental/sparse/transform.py
  tests/sparsify_test.py
Labels: kokoro:force-run, pull ready

#18632 [shard_map] implement eager custom_jvp / custom_vjp
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#18724 Downgrade a bunch of logging to DEBUG
  jax/_src/compilation_cache.py
  jax/_src/compiler.py
Labels: pull ready

#18708 Deprecate non-array inputs to jnp.array_equal & jnp.array_equiv
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#18728 Deprecate arr.device_buffer and arr.device_buffers
  CHANGELOG.md
  docs/faq.rst
  jax/_src/api.py
  jax/_src/array.py
  jax/_src/test_util.py
  tests/array_test.py
  tests/notebooks/colab_cpu.ipynb
  tests/pjit_test.py
  tests/shard_map_test.py
  tests/xmap_test.py
Labels: pull ready

#18736 fix grad device_put src inference, and a small device_put bug
  jax/_src/api.py
  jax/_src/dispatch.py
  tests/multi_device_test.py
Labels: pull ready

#18731 [shard-map] replace jaxpr interpreters with final-style-xform-of-eval-jaxpr
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#18741 [shard-map] fix test running broken by 0aec40a
  tests/shard_map_test.py
Labels: pull ready

#18752 [shard-map] add rewrite and replication checking rules for remat
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#18753 tests: improve warnings-related tests
  jax/_src/test_util.py
  tests/api_test.py
  tests/jaxpr_effects_test.py
  tests/lax_numpy_indexing_test.py
  tests/lax_numpy_test.py
  tests/memories_test.py
  tests/pmap_test.py
  tests/xla_bridge_test.py
Labels: pull ready

#18730 Deprecate the device() method of JAX arrays
  CHANGELOG.md
  docs/faq.rst
  jax/_src/array.py
  jax/_src/interpreters/pxla.py
  tests/api_test.py
  tests/array_interoperability_test.py
  tests/array_test.py
  tests/multi_device_test.py
  tests/multibackend_test.py
  tests/notebooks/colab_cpu.ipynb
  tests/notebooks/colab_gpu.ipynb
  tests/pjit_test.py
  tests/pmap_test.py
  tests/random_test.py
Labels: pull ready

#18756 [array-api] remove some test skips
  jax/experimental/array_api/skips.txt
Labels: pull ready
