Repository jax-ml/jax, pull requests merged in 2023-02, with the labels that each got.

#14235 DOC: improve documentation of OOB indices in jnp.take
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#14236 Update docs that jax.debug is unsupported on Cloud TPUs
  docs/debugging/print_breakpoint.md
Labels: kokoro:force-run, pull ready

#14254 Remove jax.dtypes._jax_types
  jax/dtypes.py
Labels: pull ready

#14251 [sparse] implement __len__ on sparse objects
  jax/experimental/sparse/_base.py
  tests/sparse_test.py
Labels: pull ready

#14250 checkify: cache jaxpr formation so we don't always retrace
  jax/_src/checkify.py
  tests/checkify_test.py
Labels: pull ready

#14257 [sparse] implement sparse rule for lax.rev
  jax/experimental/sparse/__init__.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/transform.py
  tests/sparse_test.py
  tests/sparsify_test.py
Labels: pull ready

#14262 revert #14113 per #14249, with added test
  jax/_src/scipy/sparse/linalg.py
  tests/lax_scipy_sparse_test.py
Labels: pull ready

#14263 skip custom_jvp/vjp tests which dont work with initial-style staging
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#14270 Export Device as jax.Device.
  docs/jax.lib.rst
  docs/jax.rst
  jax/__init__.py
  jax/_src/api.py
Labels: pull ready

#14269 Remove placeholder functions for unimplemented NumPy functions.
  docs/jax.numpy.rst
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.py
  jax/numpy/fft.py
  jax/numpy/linalg.py
  tests/fft_test.py
  tests/lax_numpy_test.py
  tests/linalg_test.py
Labels: pull ready

#14272 Sharp bits: mention alternatives to lax.cond
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
Labels: documentation, pull ready

#14174 Add PJRT C API to Cloud TPU test matrix
  .github/workflows/cloud-tpu-ci-nightly.yml
  tests/pjit_test.py
  tests/python_callback_test.py
Labels: pull ready

#14276 minor tweaks to type annotations, specialize code on those types
  jax/_src/core.py
  jax/_src/custom_derivatives.py
Labels: pull ready

#14283 Add static_argnums to custom_partitioning.
  jax/experimental/custom_partitioning.py
  tests/pjit_test.py
Labels: pull ready

#14290 [shape_poly] Fix the hashing and equality of symbolic dimensions
  jax/_src/numpy/lax_numpy.py
  jax/core.py
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#14291 Fix checkify caching with nested call primitives
  jax/_src/checkify.py
  tests/checkify_test.py
Labels: pull ready

#14271 [sparse] support all unbatched 1D convolutions
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/transform.py
  tests/sparse_test.py
  tests/sparsify_test.py
Labels: pull ready

#14280 [sparse] improve performance of bcoo_broadcast_in_dim
  jax/experimental/sparse/bcoo.py
Labels: pull ready

#14274 [sparse] support BCSR in sparsify transform
  jax/experimental/sparse/__init__.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/bcsr.py
  jax/experimental/sparse/transform.py
  tests/sparsify_test.py
Labels: pull ready

#14321 [shard_map] add rep rule for axis_index, trivial test
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#14323 [shard-map] add a lot of trivial rules
  jax/experimental/shard_map.py
Labels: kokoro:force-run, pull ready

#14319 DOC: update contributing guide
  docs/contributing.md
Labels: pull ready

#14303 Add scipy.stats.rankdata.
  CHANGELOG.md
  docs/jax.scipy.rst
  jax/_src/scipy/stats/_core.py
  jax/scipy/stats/__init__.py
  tests/scipy_stats_test.py
Labels: pull ready

#14335 DOC: add transformations doc back to website
  docs/conf.py
  docs/transformations.md
Labels: documentation, kokoro:force-run, pull ready

#14340 [ROCm] Re-enable some linalg and sparse tests
  tests/linalg_test.py
  tests/sparse_test.py
Labels: pull ready

#14342 Update WORKSPACE and setup.py for jax/jaxlib 0.4.3 release
  WORKSPACE
  jax/tools/colab_tpu.py
  setup.py
Labels: kokoro:force-run, pull ready

#14343 Change the executable_build_options check in compilation_cache.py to be more robust.
  jax/experimental/compilation_cache/compilation_cache.py
Labels: pull ready

#14353 Fix the jaxpr after jit-pjit merge
  docs/jaxpr.rst
Labels: pull ready

#14355 tril/triu_indices: compute arrays at runtime
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#14357 Post 0.4.3 release updates
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: kokoro:force-run, pull ready

#14362 [shard-map] add remat support, very basic test
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: kokoro:force-run, pull ready

#14361 lax.top_k: improve documentation and errors on invalid values
  jax/_src/lax/lax.py
Labels: documentation, pull ready

#14370 Implement jax.numpy.argpartition
  docs/jax.numpy.rst
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.py
  tests/lax_numpy_test.py
Labels: pull ready

#14373 [shard-map] if check_rep=False, don't call rep rules in eager
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#14379 [shard-map] add vmap spmd_axis_name support, fix vmap rule bug
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#14384 simpler pretty-print for pjit, tweak custom pp rule signature
  docs/jaxpr.rst
  jax/_src/core.py
  jax/_src/interpreters/xla.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/lax.py
  jax/_src/pjit.py
  jax/_src/state/primitives.py
Labels: pull ready

#14387 [ROCm]: Re-enable Dirichlet Tests on ROCm
  tests/random_test.py
Labels: pull ready

#14388 [sparse] implement autodiff rules for bcsr primitives
  jax/experimental/sparse/bcsr.py
  tests/sparse_test.py
Labels: pull ready

#14391 [ROCm]: Move dockerfile to ROCm5.4
  build/rocm/Dockerfile.rocm
Labels: pull ready

#14400 [shape_poly] Better error message for functions that do not use inputs
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#11727 [call_tf] Improve error reporting for calling TF functions returning non-arrays
  jax/experimental/jax2tf/call_tf.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/call_tf_test.py
Labels: pull ready

#14394 [typing] define additional methods & properties on jax.Array
  jax/_src/basearray.pyi
  jax/_src/core.py
Labels: pull ready

#14395 [sparse] implement autodiff rules for bcsr_dot_general
  jax/experimental/sparse/api.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/bcsr.py
  tests/sparse_test.py
Labels: pull ready

#14364 tril_indices/triu_indices: fix call signature & add type annotations
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#14411 Drop support for NVIDIA Kepler series GPUs in jaxlib builds.
  .bazelrc
  CHANGELOG.md
Labels: pull ready

#14408 added scipy special spence
  docs/jax.scipy.rst
  jax/_src/scipy/special.py
  jax/scipy/special.py
  tests/lax_scipy_test.py
Labels: pull ready

#14331 Add sentence explaining user guide
  docs/user_guides.rst
Labels: documentation, pull ready

#14418 generalize vmap spmd_axis_name to accept tuples of axis names
  jax/_src/api.py
  jax/_src/interpreters/batching.py
  jax/_src/pjit.py
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#14419 [sparse] add CPU lowering rule for sparse.linalg.spsolve
  jax/experimental/sparse/linalg.py
  tests/sparse_test.py
Labels: pull ready

#14415 [sparse] implement BCSR.__matmul__
  jax/experimental/sparse/bcsr.py
  jax/experimental/sparse/csr.py
  jax/experimental/sparse/transform.py
  jaxlib/gpu_sparse.py
  tests/sparse_test.py
Labels: pull ready

#14424 A few developer workflow enhancements for working with jaxlib.
  .bazelrc
  .gitignore
  build/build_wheel.py
Labels: pull ready

#14432 [jax2tf] Minor fix: remove redundant check
  jax/experimental/jax2tf/call_tf.py
Labels: pull ready

#14444 fix change to csr lowering rule
  jax/experimental/sparse/bcsr.py
  jax/experimental/sparse/csr.py
  jaxlib/gpu_sparse.py
Labels: pull ready

#14365 jax.numpy reductions: better validation of initial value
  jax/_src/numpy/reductions.py
  tests/lax_numpy_reducers_test.py
Labels: pull ready

#14457 fix minor broadcasting bug
  jax/_src/lax/lax.py
Labels: pull ready

#14456 Expose jax.typing & update docs
  CHANGELOG.md
  docs/jax.numpy.rst
  docs/jax.rst
  docs/jax.typing.rst
  jax/_src/basearray.py
  jax/typing.py
  setup.cfg
Labels: pull ready

#14453 DOC: add docs for jax.dtypes module
  docs/jax.dtypes.rst
  docs/jax.rst
  jax/_src/dtypes.py
Labels: pull ready

#14472 Shard_map jep fixes
  docs/jep/14273-shard-map.md
Labels: pull ready

#14474 DOC: improve documentation for jax.Array methods
  jax/_src/array.py
  jax/_src/basearray.py
  jax/_src/device_array.py
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#14446 jax.numpy reductions: require initial to be a scalar
  CHANGELOG.md
  jax/_src/numpy/reductions.py
  tests/lax_numpy_reducers_test.py
Labels: pull ready

#14469 [shape_poly] Add support for shape polymorphism to jnp.{percentile,qu…
  jax/_src/numpy/lax_numpy.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#14491 [jax2tf] Add a test to verify that native lowering can be nested insi…
  jax/experimental/jax2tf/tests/call_tf_test.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: pull ready

#14488 DOC: add better documentation for array methods
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#14420 [sparse] implement bcsr_broadcast_in_dim
  jax/experimental/sparse/__init__.py
  jax/experimental/sparse/bcsr.py
  jax/experimental/sparse/transform.py
  tests/sparse_test.py
Labels: pull ready

#14496 [sparse] implement bcsr_concatenate
  jax/experimental/sparse/__init__.py
  jax/experimental/sparse/bcsr.py
  jax/experimental/sparse/transform.py
  tests/sparse_test.py
  tests/sparsify_test.py
Labels: pull ready

#14489 jnp.copy: ensure inputs are array-like
  jax/_src/numpy/lax_numpy.py
Labels: kokoro:force-run, pull ready

#14500 [sparse] add bcsr_matmul batching tests
  tests/sparse_test.py
Labels: pull ready

#14518 DOC: fix typo in sph_harm
  jax/_src/scipy/special.py
Labels: pull ready

#14482 Small update to jax profiling docs
  docs/profiling.md
Labels: pull ready

#14503 Add some info in the docs about using `jax.debug.print` with f-strings
  docs/debugging/print_breakpoint.md
  jax/_src/debugging.py
Labels: pull ready

#14526 jnp.ndarray.view: implement all dtypes
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#14535 [sparse] bring sparse.csr API in line with sparse.coo
  jax/experimental/sparse/csr.py
  tests/sparse_test.py
Labels: pull ready

#14536 [sparse] test out-of-bound csr/coo indices on GPU
  jax/experimental/sparse/coo.py
  tests/sparse_test.py
Labels: pull ready

#14513 [shard-map] add systematic tests for eager, jit, autodiff
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#14554 Reexport jax.interpreters.mlir.token_type.
  jax/interpreters/mlir.py
Labels: pull ready

#14529 lax.bitcast_convert_type: better input validation
  jax/_src/lax/lax.py
Labels: pull ready

#14556 DOC: add alternative for pytree initialization
  docs/pytrees.md
Labels: documentation, pull ready

#13613 [ROCm] jax-rocm runtime/ci dockerfile multistages
  build/rocm/Dockerfile.ms
  build/rocm/README.md
  build/rocm/build_rocm.sh
  build/rocm/ci_build.sh
Labels: pull ready

#14555 BUG: avoid passing functions directly to abstractmethod
  jax/_src/basearray.py
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#14564 jnp.ndarray.view: implement all dtypes
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#14550 [shard-map] add annotations and notes to shard_map_test.py
  tests/shard_map_test.py
Labels: pull ready

#14549 Refactor effects system to use effect types, not objects
  jax/_src/ad_checkpoint.py
  jax/_src/api.py
  jax/_src/callback.py
  jax/_src/checkify.py
  jax/_src/core.py
  jax/_src/custom_derivatives.py
  jax/_src/debugging.py
  jax/_src/dispatch.py
  jax/_src/effects.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/control_flow/common.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/lax.py
  jax/_src/maps.py
  jax/_src/pjit.py
  jax/_src/state/types.py
  jax/core.py
  jax/experimental/jax2tf/call_tf.py
  jax/interpreters/partial_eval.py
  tests/jaxpr_effects_test.py
  tests/python_callback_test.py
Labels: pull ready

#14567 DOC: improve usage recommendation in jax.typing
  docs/jax.typing.rst
  jax/_src/typing.py
  jax/typing.py
Labels: pull ready

#14613 Add `--pre` to nightly libtpu pip install command.
  .github/workflows/cloud-tpu-ci-nightly.yml
Labels: kokoro:force-run, pull ready

#14594 [jax2tf] Enable strict platform checking for native serialized modules.
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/primitives_test.py
Labels: pull ready

#14628 Fix __module__ of jax.nn.initializers.* to be jax.nn.initializers.
  jax/nn/initializers.py
Labels: pull ready

#14629 Export device_put_p as jax.lax.device_put_p.
  jax/lax/__init__.py
Labels: pull ready

#14610 Add `JaxprInputEffect` and refactor `StateEffect`s to use it
  jax/_src/core.py
  jax/_src/debugging.py
  jax/_src/effects.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/pjit.py
  jax/_src/state/primitives.py
  jax/_src/state/types.py
  jax/interpreters/partial_eval.py
  tests/jaxpr_effects_test.py
  tests/state_test.py
Labels: pull ready

#14638 Update conda GPU install instructions.
  README.md
Labels: pull ready

#14648 DOC: add is_ready() to CHANGELOG
  CHANGELOG.md
Labels: documentation, pull ready

#14598 Update student-t sampling to use correct key for gamma
  jax/_src/random.py
  tests/random_test.py
Labels: pull ready

#14630 [sparse] bcoo_dot_general_sampled: faster special case
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: pull ready

#14632 [sparse] fix bug in oob index correction
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/bcsr.py
Labels: pull ready

#14631 [sparse] remove handling of padded indices from COO/CSR
  jax/experimental/sparse/coo.py
  jax/experimental/sparse/csr.py
  tests/sparse_test.py
Labels: pull ready

#14652 Fix nondeterminism issue with ordered effects
  jax/_src/interpreters/mlir.py
  jax/_src/pjit.py
  tests/jaxpr_effects_test.py
Labels: kokoro:force-run, pull ready

#14653 Deprecate three jax.Array methods:
  CHANGELOG.md
  jax/_src/api.py
  jax/_src/basearray.pyi
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#14650 [sparse] bcoo_dot_general_sampled: another special case
  jax/experimental/sparse/bcoo.py
  tests/sparse_test.py
Labels: pull ready

#13756 add remat tutorial docs
  docs/advanced_guide.rst
  docs/conf.py
  docs/index.rst
  docs/notebooks/autodiff_remat.ipynb
  docs/notebooks/autodiff_remat.md
  jax/_src/ad_checkpoint.py
Labels: pull ready

#14614 Refactor `Ref` abstract type to contain other `AbstractValue`s
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/state/__init__.py
  jax/_src/state/discharge.py
  jax/_src/state/primitives.py
  jax/_src/state/types.py
  tests/state_test.py
Labels: pull ready

#14684 Remove TokenSet needing to have effects in a certain order
  jax/_src/interpreters/mlir.py
Labels: pull ready

#14673 Small fix to GPU custom ops documentation and JAX primitive.
  docs/Custom_Operation_for_GPUs.md
  docs/notebooks/How_JAX_primitives_work.ipynb
  docs/notebooks/How_JAX_primitives_work.md
Labels: pull ready

#14701 DOC: fix jax.numpy.Array discussion
  docs/jax.numpy.rst
Labels: pull ready

#14703 [sparse] use precision=HIGHEST in bcoo_dot_general_sampled
  jax/experimental/sparse/bcoo.py
Labels: kokoro:force-run, pull ready

#14708 Update Cloud TPU install command to be simpler.
  README.md
Labels: pull ready

#14570 custom_jvp symbolic zeros support
  jax/_src/ad_util.py
  jax/_src/checkify.py
  jax/_src/core.py
  jax/_src/custom_derivatives.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/batching.py
  jax/_src/interpreters/pxla.py
  jax/custom_derivatives.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jet.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: pull ready

#14587 [jax2tf] Add support for cross-platform lowering in native serialization
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/cross_compilation_check.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#14722 DOC: mention scale/rate parameter in random.gamma
  jax/_src/random.py
Labels: pull ready
