Repository jax-ml/jax, pull requests merged in 2024-10, with the labels that each got.

#23984 jnp.mask_indices: add docs & tests
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: documentation, pull ready

#24034 Improve docs for jnp.ldexp and jnp.frexp
  jax/_src/numpy/ufuncs.py
Labels: documentation, pull ready

#24048 Document jnp.packbits & jnp.unpackbits
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#24039 add checkify rule for remat
  jax/_src/checkify.py
  tests/checkify_test.py
Labels: pull ready

#23951 Add support for passing array attributes via ffi_call and an example demonstrating the different attribute APIs supported by the FFI
  examples/ffi/CMakeLists.txt
  examples/ffi/src/jax_ffi_example/attrs.cc
  examples/ffi/src/jax_ffi_example/attrs.py
  examples/ffi/tests/attrs_test.py
  jax/_src/extend/ffi.py
  jax/_src/interpreters/mlir.py
  tests/extend_test.py
Labels: pull ready

#24032 Add timeout to requests calls
  jax/_src/clusters/cloud_tpu_cluster.py
  jax/experimental/jax2tf/examples/serving/model_server_request.py
  jax/experimental/jax2tf/examples/tf_js/quickdraw/input_pipeline.py
Labels: pull ready

#24065 docs: update Custom_Operation_for_GPUs.md
  docs/Custom_Operation_for_GPUs.md
Labels: pull ready

#24071 Fix Windows CI to install the jaxlib wheel it builds.
  .github/workflows/windows_ci.yml
Labels: pull ready, windows:force-run

#24070 Better docs for jnp.issubdtype & jnp.result_type
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#23738 Add config flag to enable/disable remat HLO pass
  jax/_src/compiler.py
  jax/_src/config.py
Labels: pull ready

#24077 README: fix badge href links
  README.md
Labels: pull ready

#24080 Fix lint at HEAD.
  jax/_src/compiler.py
  jax/_src/config.py
Labels: pull ready

#23740 [NVIDIA] Throw an error for unsupported bias shape when cudnn backend is used in `nn.dot_product_attention`
  jax/_src/nn/functions.py
  jax/experimental/jax2tf/jax2tf.py
  tests/nn_test.py
Labels: pull ready

#24094 Add a nightly ASAN build.
  .github/workflows/asan.yaml
Labels: pull ready

#23881 Deprecate the `vectorized` argument to pure_callback and ffi_call
  CHANGELOG.md
  docs/ffi.ipynb
  docs/ffi.md
  examples/ffi/src/jax_ffi_example/rms_norm.py
  jax/_src/callback.py
  jax/_src/extend/ffi.py
  tests/extend_test.py
  tests/host_callback_test.py
  tests/python_callback_test.py
Labels: pull ready

#24095 Change asan build to use a self-hosted runner and Ubuntu 24.04.
  .github/workflows/asan.yaml
  tests/logging_test.py
Labels: pull ready

#24100 Fix missing line continuation character in asan build.
  .github/workflows/asan.yaml
Labels: pull ready

#24081 Implement jax.numpy.spacing
  docs/jax.numpy.rst
  jax/_src/numpy/ufuncs.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_operators_test.py
Labels: pull ready

#24088 DOC: Improve docs for `jax.numpy`: `isfinite`, `isinf`, `isposinf`, `isneginf` and `isnan`
  jax/_src/numpy/ufuncs.py
Labels: documentation, pull ready

#24101 DOC: Better doc for `jnp.reciprocal`
  jax/_src/numpy/ufuncs.py
Labels: documentation, pull ready

#24116 Fix some typos in lax_numpy.py
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#24123 Merge v0.4.34 release branch
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: pull ready

#24127 [jax2tf] Disable test involving tan on older TF versions
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: pull ready

#24113 DOC: Better doc for `jnp.heaviside`
  jax/_src/numpy/ufuncs.py
Labels: documentation, pull ready

#24124 Remove code to support jaxlib <= 0.4.33.
  jax/_src/interpreters/pxla.py
  jax/_src/lax/linalg.py
  jax/_src/pjit.py
  jax/experimental/host_callback.py
  tests/export_back_compat_test.py
  tests/lax_test.py
  tests/layout_test.py
  tests/memories_test.py
  tests/pjit_test.py
  tests/tree_util_test.py
Labels: pull ready

#24129 Remove extraneous backslash in asan.yaml build.
  .github/workflows/asan.yaml
Labels: pull ready

#23656 Fix jax.numpy.linalg.inv with shape polymorphism
  jax/_src/lax/linalg.py
  tests/shape_poly_test.py
Labels: pull ready

#24146 Fix wrong date in changelog
  CHANGELOG.md
Labels: pull ready

#24118 Better docs for fftshift & ifftshift
  jax/_src/numpy/fft.py
Labels: documentation, pull ready

#24122 DOC: Better doc for `jnp.hypot`
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#24154 Bump "oldest supported" libtpu version to fall within the 12w window in CI
  .github/workflows/cloud-tpu-ci-nightly.yml
Labels: pull ready

#24139 Make `_cuda_path` more reliable
  jax/_src/lib/__init__.py
  pyproject.toml
Labels: pull ready, NVIDIA GPU

#24174 Move ASAN build to Python 3.13.0.
  .github/workflows/asan.yaml
Labels: pull ready

#24210 Better documentation for jnp.nan_to_num
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#24167 DOC: Better docs for `jnp.left_shift`
  jax/_src/numpy/ufuncs.py
  tests/lax_numpy_test.py
Labels: documentation, pull ready

#24214 Add jax.make_mesh to API docs
  docs/jax.rst
Labels: pull ready

#24172 Adopt jax.extend.backend.get_backend in Jax-Metal tests
  tests/lax_metal_test.py
Labels: pull ready

#24130 Update ci-build to use new runners
  .github/workflows/ci-build.yaml
Labels: pull ready

#24218 Use py_deps("absl/testing") instead of //third_party/py/absl/testing
  tests/pallas/BUILD
Labels: pull ready

#24158 Use the current minimum jaxlib version for type checking on the CI
  .pre-commit-config.yaml
  jax/_src/pallas/mosaic/error_handling.py
  jax/_src/pjit.py
Labels: pull ready

#24185 [pallas] Added API docs for Triton and Mosaic GPU backends
  docs/jax.experimental.pallas.mosaic_gpu.rst
  docs/jax.experimental.pallas.rst
  docs/jax.experimental.pallas.tpu.rst
  docs/jax.experimental.pallas.triton.rst
  docs/jax.experimental.rst
  jax/_src/pallas/mosaic_gpu/core.py
  jax/experimental/pallas/mosaic_gpu.py
Labels: pull ready

#24193 Fix listing of `vectorized` deprecation in changelog.
  CHANGELOG.md
Labels: pull ready

#24242 [JAX] bazel build rocm changes
  jaxlib/jax.bzl
  jaxlib/rocm_plugin_extension.cc
Labels: pull ready

#24241 Port autodidax to use StableHLO instead of classic HLO.
  docs/autodidax.ipynb
  docs/autodidax.md
  docs/autodidax.py
Labels: pull ready

#24232 [ROCm] Bring up clang support for JAX+XLA
  .bazelrc
  build/build.py
  build/rocm/Dockerfile.ms
  build/rocm/build_wheels/Dockerfile.manylinux_2_28_x86_64.rocm
  build/rocm/docker/Dockerfile.jax-ubu22
  build/rocm/docker/Dockerfile.jax-ubu24
  build/rocm/tools/build_wheels.py
  jaxlib/BUILD
Labels: pull ready

#24274 [ROCm] Ci linalg fix
  jaxlib/rocm/BUILD
Labels: pull ready

#24264 [ROCm] apt update
  build/rocm/tools/get_rocm.py
Labels: pull ready

#24271 Improve documentation for jnp.histogram & related APIs
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#23467 Revert to nvtx_kern_sum to get correct profiling info and adding post processing logic
  jax/tools/pgo_nsys_converter.py
Labels: pull ready

#24258 Remove checks for jaxlib v0.4.33 in tests
  tests/fft_test.py
  tests/lax_test.py
Labels: pull ready

#24299 Better docs for jnp.apply_along_axis & apply_over_axes
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#24251 Raise error when converting dot_general with unsupported precision in jax2tf
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: pull ready

#23684 Fix curly brace-related errors when prefix does not match pytree
  jax/_src/tree_util.py
  tests/tree_util_test.py
Labels: pull ready

#24294 Improve docs for jnp.invert and related functions
  jax/_src/numpy/ufuncs.py
  tests/lax_numpy_test.py
Labels: documentation, pull ready

#24305 Better docs for jnp.signbit
  jax/_src/numpy/ufuncs.py
Labels: documentation, pull ready

#24316 [ROCm] build script fix
  build/rocm/ci_build
Labels: pull ready

#24315 Improve array setitem error
  jax/_src/numpy/array_methods.py
Labels: better_errors, pull ready

#24312 Improve docs for lax.gather & lax.scatter
  jax/_src/lax/slicing.py
Labels: documentation, pull ready

#23831 [DOC] Document jax.checkpoint policies
  docs/gradient-checkpointing.md
  jax/_src/ad_checkpoint.py
Labels: pull ready

#24341 Update docs/cuda_custom_call (P1)
  docs/cuda_custom_call/cuda_custom_call_test.py
Labels: pull ready

#24322 [Mosaic GPU] Skip OSS Flash Attention test unless running on sm90
  jax/experimental/mosaic/gpu/examples/flash_attention.py
Labels: pull ready

#24323 DOC: Improved documentation for jax.numpy.tile
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#24343 Fix undefined names in jax.numpy type interface
  jax/numpy/__init__.pyi
  pyproject.toml
Labels: pull ready

#24347 CI: enable additional ruff formatting checks
  docs/notebooks/Custom_derivative_rules_for_Python_code.ipynb
  docs/notebooks/Custom_derivative_rules_for_Python_code.md
  jax/_src/numpy/polynomial.py
  pyproject.toml
Labels: pull ready

#24348 Cleanup: fix unused imports & mark exported names
  jax/__init__.py
  jax/_src/clusters/__init__.py
  jax/_src/cudnn/__init__.py
  jax/_src/debugger/__init__.py
  jax/_src/lax/control_flow/__init__.py
  jax/_src/lib/__init__.py
  jax/_src/state/__init__.py
  jax/ad_checkpoint.py
  jax/api_util.py
  jax/cloud_tpu_init.py
  jax/core.py
  jax/custom_derivatives.py
  jax/dtypes.py
  jax/experimental/array_serialization/serialization.py
  jax/experimental/array_serialization/serialization_test.py
  jax/experimental/jax2tf/examples/mnist_lib.py
  jax/experimental/jax2tf/tests/cross_compilation_check.py
  jax/experimental/jax2tf/tests/jax_primitives_coverage_test.py
  jax/experimental/jax2tf/tests/primitives_test.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  jax/experimental/jax2tf/tests/sharding_test.py
  jax/experimental/key_reuse/_core.py
  jax/experimental/mosaic/__init__.py
  jax/experimental/mosaic/dialects.py
  jax/experimental/mosaic/gpu/__init__.py
  jax/experimental/mosaic/gpu/examples/flash_attention.py
  jax/experimental/mosaic/gpu/examples/matmul.py
  jax/experimental/mosaic/gpu/utils.py
  jax/experimental/multihost_utils.py
  jax/experimental/pallas/__init__.py
  jax/experimental/pallas/mosaic_gpu.py
  jax/experimental/pallas/ops/gpu/rms_norm.py
  jax/experimental/pallas/ops/tpu/megablox/__init__.py
  jax/experimental/pallas/ops/tpu/paged_attention/__init__.py
  jax/experimental/pallas/ops/tpu/splash_attention/__init__.py
  jax/experimental/pallas/ops/tpu/splash_attention/splash_attention_mask_info.py
  jax/experimental/pallas/tpu.py
  jax/experimental/pallas/triton.py
  jax/experimental/serialize_executable.py
  jax/experimental/shard_map.py
  jax/experimental/sparse/api.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/bcsr.py
  jax/experimental/sparse/csr.py
  jax/experimental/sparse/test_util.py
  jax/experimental/sparse/util.py
  jax/experimental/topologies.py
  jax/interpreters/mlir.py
  jax/interpreters/pxla.py
  jax/lax/linalg.py
  jax/numpy/__init__.py
  jax/scipy/stats/nbinom.py
  jax/sharding.py
  jax_plugins/cuda/__init__.py
  jax_plugins/rocm/__init__.py
  pyproject.toml
Labels: pull ready

#24351 Improve docs for jnp.sinc
  jax/_src/numpy/ufuncs.py
Labels: documentation, pull ready

#24326 Better docs for `jax.numpy`: `equal` and `not_equal`
  jax/_src/numpy/ufuncs.py
Labels: documentation, pull ready

#24355 [export] Fix github links in the export documentation
  docs/export/export.md
  jax/_src/export/_export.py
Labels: pull ready

#24300 [ROCm] Change ROCm documentation
  README.md
  build/rocm/README.md
  docs/developer.md
Labels: pull ready

#24345 Update docs/cuda_custom_call (P2)
  docs/cuda_custom_call/foo.cu.cc
Labels: pull ready

#24403 Better documentation for jnp.load
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.pyi
Labels: documentation, pull ready

#24342 [export] Add support for serialization for some custom PyTree nodes
  jax/_src/export/_export.py
  jax/_src/export/serialization.fbs
  jax/_src/export/serialization.py
  jax/_src/export/serialization_generated.py
  jax/experimental/export/__init__.py
  jax/export.py
  tests/export_test.py
Labels: pull ready

#24417 Update warning message for jit-of-pmap
  jax/_src/interpreters/pxla.py
Labels: pull ready

#24421 Better docs for jnp.cross
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#24400 Make jnp.subtract a ufunc
  jax/_src/basearray.pyi
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/ufuncs.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_ufuncs_test.py
Labels: documentation, pull ready

#24434 Update Pallas distributed tutorials with jax.make_mesh
  docs/pallas/tpu/distributed.ipynb
  docs/pallas/tpu/distributed.md
Labels: pull ready

#24437 Fix jnp.diff for boolean inputs
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#22410 Update installation instructions
  README.md
  docs/installation.md
Labels: documentation, pull ready

#24425 Rename vmap methods for callbacks
  docs/ffi.ipynb
  docs/ffi.md
  examples/ffi/src/jax_ffi_example/rms_norm.py
  jax/_src/callback.py
  jax/_src/extend/ffi.py
  tests/extend_test.py
  tests/python_callback_test.py
Labels: pull ready

#24442 Better documentation for jnp.lexsort
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#24412 Better docs for jnp.fromfunction
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#24467 Add back the import of `jtu` in `flash_attention.py`
  jax/experimental/mosaic/gpu/examples/flash_attention.py
Labels: pull ready

#24452 Better docs for jnp.insert
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#21524 Raise an error when an MLIR lowering is registered for an unknown platform
  jax/_src/interpreters/mlir.py
  jax/_src/xla_bridge.py
  tests/extend_test.py
Labels: pull ready

#24465 Fix mypy error
  jax/_src/pjit.py
Labels: pull ready

#24469 Better documentation for jnp.indices
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#24446 [docs] Added two new APIs to the export API docs
  docs/jax.export.rst
Labels: pull ready

#24482 Better docs for jnp.unwrap
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#24487 Improve docs for jnp.block
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#24427 [NVIDIA] Adjust the atol/rtol of JAX SDPA API tests
  tests/nn_test.py
Labels: pull ready

#24490 Perform searchsorted binary search using unsigned intermediate values.
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#24511 improve concreteness error message in remat
  jax/_src/ad_checkpoint.py
  tests/api_test.py
Labels: pull ready

#24505 [jax2tf] Fixes a bad interaction between jax2tf.convert, TF, and call_tf
  jax/experimental/jax2tf/call_tf.py
  jax/experimental/jax2tf/tests/call_tf_test.py
Labels: pull ready

#24525 Remove duplicate entry in CHANGELOG.
  CHANGELOG.md
Labels: pull ready

#24523 [ROCm] ci build fixes
  build/rocm/ci_build.sh
Labels: pull ready

#24500 [shape_poly] Expands support for random.choice
  jax/_src/prng.py
  jax/_src/random.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  tests/shape_poly_test.py
Labels: pull ready

#24470 sharding cleanup: use inline checks for unimplemented and auto
  jax/_src/export/_export.py
  jax/_src/interpreters/pxla.py
  jax/_src/layout.py
  jax/_src/pjit.py
  jax/_src/sharding_impls.py
  jax/_src/stages.py
  jax/experimental/jax2tf/jax2tf.py
  jax/interpreters/pxla.py
Labels: pull ready

#24433 Add support for layouts and other advanced features in ffi_call
  jax/_src/callback.py
  jax/_src/extend/ffi.py
  tests/extend_test.py
Labels: pull ready

#24524 Re-enable jax2tf test for dot algorithm with stricter TF version check
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: pull ready

#24391 Document jax config to disable remat HLO pass
  docs/gpu_memory_allocation.rst
Labels: pull ready

#24495 fix the wrong output of pallas attention kernel when q_len!=kv_len
  jax/experimental/pallas/ops/gpu/attention.py
Labels: pull ready

#24031 Fix vmap error message when args passed by keyword
  jax/_src/api.py
  tests/api_test.py
Labels: bug, pull ready

#24542 Fix lint at head
  jax/_src/lib/__init__.py
Labels: pull ready

#24537 Add some missing jax.numpy documentation
  jax/_src/dtypes.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/ufunc_api.py
Labels: documentation, pull ready

#24538 Add new jnp.cumulative_prod function.
  docs/jax.numpy.rst
  jax/_src/numpy/reductions.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_reducers_test.py
Labels: pull ready

#24554 Remove int4 from jtu.dtypes.all_dtypes.
  jax/_src/test_util.py
Labels: pull ready

#24488 Improve docs for jnp.arctan2
  jax/_src/numpy/ufuncs.py
  tests/lax_numpy_test.py
Labels: documentation, pull ready

#24492 Remove obsolete implements() decorator & fix tests
  jax/_src/numpy/util.py
  tests/lax_numpy_test.py
Labels: pull ready

#24545 fix jax.custom_gradient to allow closing over non-autodiff tracers
  jax/_src/custom_derivatives.py
  tests/api_test.py
Labels: pull ready

#24572 Adjust copyright notice.
  docs/conf.py
Labels: documentation, pull ready

#24579 Remove some dead code from gpu_prng.py
  jaxlib/gpu_prng.py
Labels: kokoro:force-run, pull ready

#24580 Fix segfault caused by uninitialized LAPACK in FFI test
  tests/extend_test.py
Labels: kokoro:force-run, pull ready

#24510 Allow dot algorithms in default_matmul_precision config
  jax/_src/config.py
  tests/lax_test.py
Labels: pull ready

#24589 Implement device_get for typed PRNG keys
  jax/_src/api.py
  jax/_src/prng.py
  tests/random_test.py
Labels: pull ready

#24600 Fix a reference cycle bug.
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/partial_eval.py
Labels: pull ready

#24606 Remove deprecated jax.experimental.export module.
  CHANGELOG.md
  jax/experimental/export/BUILD
  jax/experimental/export/__init__.py
  tests/BUILD
  tests/export_test.py
Labels: pull ready

#24480 Run dot algorithm tests with PJRT plugin
  tests/lax_test.py
Labels: pull ready

#24190 Migrate CUDA FFI example to GitHub Actions using hosted GPU runner
  .github/workflows/ci-build.yaml
  docs/cuda_custom_call/BUILD
  docs/cuda_custom_call/Makefile
  docs/cuda_custom_call/cuda_custom_call_test.py
  examples/ffi/CMakeLists.txt
  examples/ffi/src/jax_ffi_example/cuda_e2e.cu
  examples/ffi/src/jax_ffi_example/cuda_e2e.py
  examples/ffi/tests/attrs_test.py
  examples/ffi/tests/cuda_e2e_test.py
  examples/ffi/tests/rms_norm_test.py
Labels: pull ready
