Repository jax-ml/jax, pull requests merged in 2024-11, with the labels that each got.

#24647 Add a register_dataclass example to the pytree tutorial.
  docs/jit-compilation.md
  docs/working-with-pytrees.md
Labels: pull ready

#24649 [array api] update test suite to latest commit
  .github/workflows/jax-array-api.yml
  tests/array_api_skips.txt
Labels: pull ready

#24652 Remove a number of expired deprecations.
  jax/__init__.py
  jax/core.py
  jax/interpreters/ad.py
  jax/interpreters/xla.py
  jax/lax/__init__.py
  jax/nn/__init__.py
  jax/numpy/__init__.py
  jax/random.py
Labels: pull ready

#24665 remove busted example from shmap jep
  docs/jep/14273-shard-map.md
Labels: pull ready

#24667 Fix array API tests.
  tests/array_api_skips.txt
Labels: pull ready

#24669 Fix signatures test: new axis argument in trim_zeros
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: kokoro:force-run, pull ready

#24684 Fix `_cuda_path` for case when `cuda_nvcc` is a namespace package
  jax/_src/lib/__init__.py
Labels: pull ready

#24692 issue #24691
  jax/_src/numpy/linalg.py
Labels: pull ready

#24543 Update pre-commit workflow to cache on jax version
  .github/workflows/ci-build.yaml
Labels: pull ready

#24703 Update JAX landing page - Flax
  docs/index.rst
Labels: pull ready

#24702 Update details on JAX libraries in JAX README.md
  README.md
Labels: pull ready

#23969 [jax.distributed] Enable grpc channel compression
  jax/_src/distributed.py
Labels: pull ready

#23468 Adding `JAX_LOGGING_LEVEL` configuration option
  docs/persistent_compilation_cache.md
  jax/_src/config.py
  jax/_src/logging_config.py
  tests/logging_test.py
Labels: pull ready

#24710 Fix Typos
  docs/export/export.md
  docs/export/shape_poly.md
  jax/experimental/jax2tf/README.md
Labels: pull ready

#24717 Improve efficiency of jax.scipy.stats.rankdata
  jax/_src/scipy/stats/_core.py
Labels: pull ready

#24704 Update link to algebraic_simplifier.cc to point to OpenXLA instead of TF
  docs/faq.rst
Labels: pull ready

#24729 Fixes to jax logging on TPU and if `TF_CPP_MIN_LOG_LEVEL` is modified
  tests/logging_test.py
Labels: pull ready

#24722 Make Tracers non-hashable
  CHANGELOG.md
  jax/_src/basearray.py
  jax/_src/core.py
  tests/array_test.py
Labels: pull ready

#24723 scipy.special.beta: remove deprecated x and y parameters
  jax/_src/scipy/special.py
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#24733 Fix debug_nans false positive in jnp.quantile
  jax/_src/numpy/reductions.py
Labels: pull ready

#24602 GPU Pallas `decode_attention` improvements
  jax/experimental/pallas/ops/gpu/decode_attention.py
  tests/pallas/gpu_attention_test.py
Labels: pull ready

#24645 [Mosaic GPU] Improve correctness of benchmarking scripts
  jax/experimental/mosaic/gpu/examples/flash_attention.py
  jax/experimental/mosaic/gpu/examples/matmul.py
Labels: pull ready

#24700 register_dataclass: allow marking static fields via dataclass.field
  CHANGELOG.md
  jax/_src/tree_util.py
  tests/tree_util_test.py
Labels: pull ready

#24759 start an 'about the project' docs page
  docs/about.md
  docs/index.rst
  jax/extend/__init__.py
Labels: pull ready

#24657 Fix argmin docstring to not say "maximum"
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#24778 (follow-up #23852) add missing `typename` keyword to work with `gcc`
  jaxlib/gpu/solver_kernels_ffi.cc
Labels: pull ready

#24786 Don't perform size 0 slices into scipy rotations.
  tests/scipy_spatial_test.py
Labels: pull ready

#24481 Error on numpy array conversion of PRNG key array
  CHANGELOG.md
  jax/_src/prng.py
  tests/random_test.py
Labels: pull ready

#24774 don't warn on unused `type: ignore`
  pyproject.toml
Labels: pull ready

#24818 [shape_poly] Remove caching for the symbolic shape evaluator
  jax/_src/export/_export.py
  jax/_src/export/shape_poly.py
Labels: pull ready

#24839 [Mosaic GPU] Only run tests requiring sm90a on Hopper
  jax/_src/test_util.py
  jax/experimental/mosaic/gpu/examples/flash_attention.py
  tests/mosaic/flash_attention_test.py
  tests/mosaic/matmul_test.py
  tests/pallas/mgpu_attention_test.py
  tests/pallas/mosaic_gpu_test.py
Labels: pull ready

#24814 jnp.bincount: support boolean inputs
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#24770 jax.device_get: handle generic extended dtypes
  jax/_src/api.py
  jax/_src/prng.py
Labels: pull ready

#24822 Cleanup more remnants of the jax.experimental.host_callback
  jax/_src/core.py
  jax/_src/dispatch.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/interpreters/pxla.py
  jax/core.py
Labels: pull ready

#24823 [shape_poly] Fix the handling of jvp(lax.sort)
  jax/_src/lax/lax.py
  tests/shape_poly_test.py
Labels: pull ready

#24854 Make sure compilation_cache.is_cache_used always returns a bool
  jax/_src/compilation_cache.py
Labels: pull ready

#24772 Allow 64-bit output types from ffi_call regardless of enable_x64 flag
  jax/_src/extend/ffi.py
  tests/extend_test.py
Labels: pull ready

#24860 Add GPU overflow bugfix (#24846) to changelog.
  CHANGELOG.md
Labels: pull ready

#24806 Internal: create decorators for defining ufuncs
  jax/_src/numpy/ufuncs.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: pull ready

#24792 Update some outdated syntax in FFI tutorial
  docs/ffi.ipynb
  docs/ffi.md
  docs/ffi/rms_norm.cc
  examples/ffi/src/jax_ffi_example/attrs.cc
  examples/ffi/src/jax_ffi_example/cuda_e2e.cu
  examples/ffi/src/jax_ffi_example/rms_norm.cc
Labels: pull ready

#24842 jax.scipy.linalg.toeplitz: support implicit batching
  CHANGELOG.md
  jax/_src/scipy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#24069 Re-enable cudnn_fusion_test on A100.
  tests/BUILD
  tests/cudnn_fusion_test.py
Labels: pull ready

#22899 When caching is enabled, also enable XLA caching features as well
  docs/persistent_compilation_cache.md
  jax/BUILD
  jax/_src/compiler.py
  jax/_src/config.py
  tests/compilation_cache_test.py
Labels: pull ready

#24883 doc: link directly to installation on the main page
  docs/_static/style.css
  docs/index.rst
Labels: documentation, pull ready

#24886 Fix typos: Change 'arugments' to 'arguments'.
  docs/Custom_Operation_for_GPUs.md
  docs/Custom_Operation_for_GPUs.py
  jax/_src/callback.py
Labels: pull ready

#24810 Specialize ufunc.reduce for monoidal binary ufuncs.
  jax/_src/numpy/reductions.py
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#24889 Don't override --xla_tpu_use_enhanced_launch_barrier if explicitly set
  jax/_src/cloud_tpu_init.py
Labels: pull ready

#23805 Add an example demonstrating how FFI calls can use global state
  examples/ffi/CMakeLists.txt
  examples/ffi/README.md
  examples/ffi/src/jax_ffi_example/counter.cc
  examples/ffi/src/jax_ffi_example/counter.py
  examples/ffi/tests/counter_test.py
Labels: pull ready

#24899 Fixed typo in asan.yaml
  .github/workflows/asan.yaml
Labels: pull ready

#24865 finalize deprecation of jax.clear_backends
  CHANGELOG.md
  jax/__init__.py
Labels: pull ready

#24751 Allow setting default_device with platform names.
  jax/_src/config.py
  jax/_src/interpreters/pxla.py
  tests/api_test.py
Labels: pull ready

#24896 Make the jaxpr for jnp.pad in "constant" mode more succinct.
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#24897 Don't use an out-of-line lowering for integer_pow for small powers.
  jax/_src/lax/lax.py
Labels: pull ready

#24864 jnp.logaddexp2: simplify implementation
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#24904 Update array-api-tests commit
  .github/workflows/jax-array-api.yml
Labels: pull ready

#24567 Add a link to the Intel OneAPI plugin for JAX
  README.md
  docs/installation.md
Labels: pull ready

#24905 cleanup: delete unused argument from internal reduction helper
  jax/_src/numpy/reductions.py
Labels: pull ready

#24871 Add numpy.put_along_axis.
  CHANGELOG.md
  docs/jax.numpy.rst
  jax/_src/numpy/lax_numpy.py
  jax/_src/test_util.py
  jax/_src/util.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#24881 Add a shard map replication rule for ffi_call
  jax/experimental/shard_map.py
  tests/extend_test.py
  tests/shard_map_test.py
Labels: pull ready

#24907 Update array-api-tests commit
  .github/workflows/jax-array-api.yml
  pyproject.toml
Labels: pull ready

#24862 Move the Control Flow section of Sharp Bits into its own tutorial.
  README.md
  docs/control-flow.md
  docs/faq.rst
  docs/jit-compilation.md
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
  docs/stateful-computations.md
  docs/tutorials.rst
Labels: documentation, pull ready

#24918 Add an example on logical operators to the tutorial.
  docs/control-flow.md
Labels: pull ready

#24914 Add missing functions to jax.numpy type interface
  jax/numpy/__init__.pyi
Labels: pull ready

#24917 Consolidate material on PRNGs and add a short summary to Key Concepts.
  README.md
  docs/key-concepts.md
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
  docs/random-numbers.md
  jax/_src/errors.py
Labels: pull ready

#24930 Deduplicate constants in StableHLO lowering.
  jax/_src/interpreters/mlir.py
Labels: pull ready

#24932 Return a ndarray in shape_as_value if the shape is known to be constant.
  jax/_src/lax/lax.py
Labels: pull ready

#24912 Set `__module__` attribute for objects in jax.numpy
  jax/_src/dtypes.py
  jax/_src/numpy/index_tricks.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/polynomial.py
  jax/_src/numpy/reductions.py
  jax/_src/numpy/setops.py
  jax/_src/numpy/ufunc_api.py
  jax/_src/numpy/ufuncs.py
  jax/_src/numpy/vectorize.py
  tests/package_structure_test.py
Labels: pull ready

#24903 Make logaddexp and logaddexp2 into ufuncs
  jax/_src/numpy/reductions.py
  jax/_src/numpy/ufuncs.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_ufuncs_test.py
Labels: pull ready

#24957 Disable some complex function accuracy tests that fail on Mac ARM.
  tests/lax_test.py
Labels: pull ready

#24958 Adds font fallbacks
  docs/_static/style.css
Labels: pull ready

#24861 [JAX/version] Support adding custom version suffix.
  jax/version.py
  tests/version_test.py
Labels: pull ready

#24853 [JAX/distributed] Small clean ups on warning emissions in jax.distributed.
  jax/_src/clusters/cluster.py
  jax/_src/distributed.py
Labels: pull ready

#24970 Add a new API jax.lax.split.
  CHANGELOG.md
  docs/jax.lax.rst
  jax/_src/lax/lax.py
  jax/_src/numpy/array_methods.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/pallas/mosaic/lowering.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jet.py
  jax/lax/__init__.py
  tests/lax_autodiff_test.py
  tests/lax_test.py
  tests/lax_vmap_test.py
Labels: pull ready

#24593 represent `random.key_impl` of builtin RNGs by canonical string name
  jax/_src/random.py
  tests/extend_test.py
  tests/random_test.py
Labels: pull ready

#25007 Deprecate several private APIs in jax.lib
  CHANGELOG.md
  jax/lib/xla_client.py
  jax/lib/xla_extension.py
Labels: pull ready

#25005 Mention python 3.13 in docs & package metadata
  docs/deprecation.md
  jaxlib/setup.py
  setup.py
Labels: pull ready

#25004 Make a direct linearize trace
  jax/_src/config.py
  jax/_src/interpreters/ad.py
  tests/api_test.py
Labels: pull ready

#25008 Fix KeyError recently introduced in cloud_tpu_init.py
  jax/_src/cloud_tpu_init.py
Labels: pull ready

#25013 Mention stackless in the release notes.
  CHANGELOG.md
Labels: pull ready

#25011 Set __module__ attribute of jax.numpy.linalg APIs
  jax/_src/numpy/linalg.py
  tests/package_structure_test.py
Labels: pull ready

#25019 DOC: add examples for jax.lax.pad
  jax/_src/lax/lax.py
Labels: documentation, pull ready

#25020 jax.lax.pad: improve input validation
  jax/_src/lax/lax.py
  tests/lax_test.py
Labels: kokoro:force-run, pull ready

#25018 [array api] use most recent version of array_api_tests
  .github/workflows/jax-array-api.yml
  pyproject.toml
  tests/array_api_skips.txt
Labels: pull ready

#25034 [shape_poly] Adding shape polymorphism support for the state primitives.
  benchmarks/shape_poly_benchmark.py
  jax/_src/core.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/state/indexing.py
  tests/shape_poly_test.py
  tests/state_test.py
Labels: pull ready

#25009 Remove internal KeyArray alias
  jax/_src/blocked_sampler.py
  jax/_src/nn/initializers.py
  jax/_src/random.py
Labels: pull ready

#25048 Change signature of linearization rules.
  jax/_src/interpreters/ad.py
  jax/_src/lax/lax.py
  tests/api_test.py
Labels: pull ready

#25070 Add linearization rule for pjit_p
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/lax.py
  jax/_src/pjit.py
  tests/api_test.py
Labels: pull ready

#25041 Refactor FFI examples to consolidate several examples into one submodule
  examples/ffi/CMakeLists.txt
  examples/ffi/README.md
  examples/ffi/src/jax_ffi_example/attrs.py
  examples/ffi/src/jax_ffi_example/counter.cc
  examples/ffi/src/jax_ffi_example/cpu_examples.cc
  examples/ffi/src/jax_ffi_example/cpu_examples.py
  examples/ffi/src/jax_ffi_example/cuda_examples.cu
  examples/ffi/src/jax_ffi_example/cuda_examples.py
  examples/ffi/tests/counter_test.py
  examples/ffi/tests/cpu_examples_test.py
  examples/ffi/tests/cuda_examples_test.py
Labels: pull ready

#25084 [ROCm] Add ROCm version metadata to pip show output for `jax-rocm60-plugin` and `jax-rocm60-pjrt`
  jax_plugins/rocm/plugin_setup.py
  jax_plugins/rocm/setup.py
Labels: pull ready

#25096 Update ROCm scripts to match new build.py usage
  build/rocm/dev_build_rocm.py
  build/rocm/tools/build_wheels.py
Labels: pull ready

#25153 Add experimental JAX roofline API.
  jax/BUILD
  jax/experimental/roofline/__init__.py
  jax/experimental/roofline/roofline.py
  jax/experimental/roofline/rooflines.py
  tests/BUILD
  tests/roofline_test.py
Labels: pull ready

#25137 [ROCm] Update http to https in amd artifactory url.
  build/rocm/tools/get_rocm.py
Labels: pull ready

#25091 [cuda] Bump nvidia-cuda-nvcc-cu12 dependency to 12.6.85
  jax_plugins/cuda/plugin_setup.py
Labels: pull ready

#25128 [ROCm] [ROCm] fix jax and wheelhouse relative paths
  build/rocm/ci_build
Labels: pull ready
