Repository jax-ml/jax, pull requests merged in 2024-07, with the labels that each got.

#22208 Revived the workaround for not-expanding type aliases
  docs/conf.py
Labels: kokoro:force-run, pull ready

#21925 Add an `ffi_call` function with a similar signature to `pure_callback`
  docs/jax.extend.ffi.rst
  jax/_src/callback.py
  jax/_src/extend/ffi.py
  jax/extend/ffi.py
  tests/extend_test.py
Labels: pull ready

#22167 DOC: Improve docs of `jnp.var` and `std`
  jax/_src/numpy/reductions.py
Labels: pull ready

#22119 Remove `linear` parameter from `lax.cond_p`
  docs/jaxpr.rst
  jax/_src/checkify.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/pallas/mosaic/lowering.py
  jax/_src/pallas/triton/lowering.py
  jax/experimental/host_callback.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/sparse/transform.py
  tests/api_test.py
  tests/host_callback_test.py
  tests/lax_control_flow_test.py
  tests/metadata_test.py
Labels: pull ready

#21982 Improve compilation cache tests
  tests/compilation_cache_test.py
Labels: pull ready

#22199 [export] Disable serialization in export_test if flatbuffers is not installed
  tests/export_test.py
Labels: pull ready

#22222 add more info to xla_computation deprecation warning
  jax/__init__.py
Labels: pull ready

#21981 DOC: Improved docs for polynomial arithmetic functions of jax.numpy
  jax/_src/numpy/polynomial.py
Labels: pull ready

#22231 [ROCM] Replace xla::Status with absl::Status in rocm_plugin_extension.cc
  jaxlib/rocm_plugin_extension.cc
Labels: pull ready

#22232 [ROCM] add typed XLA FFI support in rocm specific code
  jaxlib/rocm/BUILD.bazel
Labels: pull ready

#22233 [ROCM] make mosaic dependency cuda specific
  jaxlib/tools/BUILD.bazel
Labels: pull ready

#21926 [`LRUCache`] Storing the last access time of a cache entry in a separate file
  jax/_src/lru_cache.py
  tests/lru_cache_test.py
Labels: pull ready

#22191 better log2 doc
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#21766 Improve vmap out_axes error
  jax/_src/api.py
  jax/_src/interpreters/batching.py
  tests/api_test.py
Labels: pull ready

#22237 Prefer __qualname__ as a pjit_p name
  jax/_src/pjit.py
  jax/_src/util.py
Labels: pull ready

#22257 Fix compatibility with nightly numpy
  tests/lax_numpy_reducers_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#22211 Don't wrap singleton ir.Values with tuples during HLO lowering.
  jax/_src/ad_checkpoint.py
  jax/_src/array.py
  jax/_src/callback.py
  jax/_src/custom_derivatives.py
  jax/_src/debugging.py
  jax/_src/export/_export.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/lax.py
  jax/_src/lax/linalg.py
  jax/_src/lax/parallel.py
  jax/_src/lax/slicing.py
  jax/_src/lax/windowed_reductions.py
  jax/_src/maps.py
  jax/_src/pjit.py
  jax/experimental/jax2tf/call_tf.py
  jax/experimental/shard_map.py
  jax/experimental/sparse/bcsr.py
  jax/interpreters/mlir.py
  tests/export_test.py
  tests/jaxpr_effects_test.py
Labels: pull ready

#22260 Fix lint error at head.
  jax/_src/ad_checkpoint.py
Labels: pull ready

#19614 add batch_size argument to jax.lax.map
  jax/_src/lax/control_flow/loops.py
  tests/api_test.py
Labels: pull ready

#21819 Compilation cache doc
  docs/persistent_compilation_cache.md
Labels: pull ready

#22173 [pallas] Improve some error messages and add API tests.
  jax/_src/pallas/core.py
  jax/_src/pallas/mosaic/core.py
  jax/_src/pallas/mosaic/lowering.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pjit.py
  jax/_src/stages.py
  jax/_src/tree_util.py
  tests/pallas/pallas_test.py
  tests/pallas/tpu/pallas_call_test.py
  tests/pallas/tpu/pallas_random_test.py
Labels: pull ready

#22269 Handle missing ``debug_info`` in ``explain_tracing_cache_miss``
  jax/_src/pjit.py
  tests/api_test.py
Labels: pull ready

#22253 Clean up old `GFileCache` implementation
  jax/BUILD
  jax/_src/compilation_cache.py
  jax/_src/compiler.py
  jax/_src/gfile_cache.py
  jax/_src/lru_cache.py
  jax/_src/path.py
  tests/BUILD
  tests/gfile_cache_test.py
Labels: pull ready

#22285 Silenced the deprecation warning coming from TF dependencies
  pyproject.toml
Labels: pull ready

#22284 ``debug_info`` no longer requires non-None ``func_src_info``
  jax/_src/api_util.py
  jax/_src/core.py
  jax/_src/linear_util.py
  jax/_src/pjit.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#22287 [shape_poly] Small improvement in the documentation
  docs/export/shape_poly.md
Labels: pull ready

#22301 Fix mypy error
  jax/_src/cudnn/fused_attention_stablehlo.py
Labels: pull ready

#22160 jnp.arange: fix incorrect type annotation
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.pyi
Labels: pull ready

#22271 Update persistent compilation cache doc
  docs/persistent_compilation_cache.md
Labels: pull ready

#22189 Better docs for jnp.sort & jnp.argsort
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#22312 Fix debug_nans false positive in jnp.var
  jax/_src/numpy/reductions.py
Labels: kokoro:force-run, pull ready

#22304 [pallas] Improve error messages for input_output_aliasing
  jax/_src/pallas/pallas_call.py
  tests/pallas/pallas_test.py
Labels: pull ready

#22193 Improve documentation of jax.numpy.clip
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#22282 [Pallas TPU] Add lowering for `lax.erf_inv` 32 bit
  jax/_src/pallas/mosaic/lowering.py
  tests/pallas/tpu/tpu_ops_test.py
Labels: pull ready

#22317 Fix lint errors at HEAD
  jax/_src/nn/functions.py
  tests/nn_test.py
Labels: pull ready

#22279 [Pallas TPU] Add lowering for `lax.shift_right_arithmetic`
  jax/_src/pallas/mosaic/lowering.py
  tests/pallas/ops_test.py
Labels: pull ready

#20174 Enable opt-in autodetection of distributed configuration for mpi4py
  jax/BUILD
  jax/_src/clusters/__init__.py
  jax/_src/clusters/cloud_tpu_cluster.py
  jax/_src/clusters/cluster.py
  jax/_src/clusters/mpi4py_cluster.py
  jax/_src/clusters/ompi_cluster.py
  jax/_src/clusters/slurm_cluster.py
  jax/_src/distributed.py
  tests/multiprocess_gpu_test.py
Labels: pull ready

#22316 jnp.vectorize: respect numpy_rank_promotion config
  jax/_src/numpy/vectorize.py
  jax/_src/scipy/spatial/transform.py
  tests/lax_numpy_test.py
  tests/lax_numpy_ufuncs_test.py
  tests/lax_numpy_vectorize_test.py
  tests/linalg_test.py
  tests/scipy_spatial_test.py
Labels: pull ready

#22192 better log10 doc
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#22275 [pallas] Fix the interpreter for block_shape not dividing the overall shape
  docs/pallas/grid_blockspec.md
  jax/_src/pallas/pallas_call.py
  jax/_src/test_util.py
  tests/pallas/pallas_test.py
Labels: pull ready

#22248 DOC: Improved docs for jnp.ptp and count_nonzero
  jax/_src/numpy/reductions.py
Labels: pull ready

#22258 DOC: Improved docs for `jnp.fft.fftn`
  jax/_src/numpy/fft.py
Labels: pull ready

#22241 jax.numpy: better docstring for array_equiv function
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#22347 DOC: Improved docs for jnp.fft.ifftn
  jax/_src/numpy/fft.py
Labels: pull ready

#22366 DOC: Improved docs for `jnp.nanmin` and `jnp.nanmax`
  jax/_src/numpy/reductions.py
Labels: pull ready

#22392 DOC: Improved docs for `jnp.nanmean`
  jax/_src/numpy/reductions.py
Labels: pull ready

#22369 DOC: Improved docs for `jnp.nansum` and `nanprod`
  jax/_src/numpy/reductions.py
Labels: pull ready

#22244 make remat reduce precision of saved values to avoid xla excess precision
  jax/_src/ad_checkpoint.py
  tests/api_test.py
Labels: pull ready

#22403 Improve docs for jnp.repeat
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#22391 [pallas] Added a CHANGELOG for Pallas
  CHANGELOG.md
  docs/pallas/CHANGELOG.md
  docs/pallas/index.rst
Labels: pull ready

#22400 DOC: Improved docs for `jnp.nanvar` and `jnp.nanstd`
  jax/_src/numpy/reductions.py
Labels: pull ready

#22370 [pallas] Document the indexing_mode=Unblocked()
  docs/pallas/grid_blockspec.md
  jax/_src/pallas/pallas_call.py
  jax/experimental/pallas/__init__.py
  tests/pallas/pallas_test.py
  tests/pallas/tpu_pallas_test.py
Labels: pull ready

#22419 [ROCM] Fix version checks after rocm pjrt integration
  tests/linalg_test.py
  tests/sparse_bcoo_bcsr_test.py
  tests/sparse_test.py
Labels: pull ready

#22359 jax.numpy: better docstring for allclose and isclose functions
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#22443 [docs] Fix docs building error
  docs/jax.experimental.rst
Labels: pull ready

#22402 Deduped three identical implementations of ``hoist_consts_to_refs``
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/pallas/pallas_call.py
  jax/_src/state/utils.py
Labels: pull ready

#22114 [memories] Transfer to pinned_host fast path in async_serialize
  jax/experimental/array_serialization/serialization.py
  jax/experimental/array_serialization/serialization_test.py
Labels: pull ready

#22169 [memories] Overlap shard transfers in async_serialize
  jax/experimental/array_serialization/serialization.py
  jax/experimental/array_serialization/serialization_test.py
Labels: pull ready

#22405 [shape_poly] Expand the support for shape polymorphism for jnp.pad
  jax/_src/export/shape_poly.py
  jax/_src/numpy/lax_numpy.py
  tests/shape_poly_test.py
Labels: pull ready

#22375 DOC: improve mypy/pre-commit instructions
  docs/contributing.md
  docs/developer.md
Labels: pull ready

#22440 [pallas] Some minor test housekeeping.
  tests/pallas/tpu_pallas_test.py
Labels: pull ready

#22448 Update references to jaxlib_nightly_releases (which is a legacy index…
  .github/workflows/cloud-tpu-ci-nightly.yml
  .github/workflows/metal_plugin_ci.yml
Labels: pull ready

#22445 Fix compatibility of `jnp.unique` with numpy nightly
  jax/_src/numpy/setops.py
  tests/lax_numpy_test.py
Labels: pull ready

#22450 [NVIDIA] Update JAX doc to include `jax.nn.dot_product_attention`
  docs/jax.nn.rst
Labels: pull ready

#22463 Disable some tests that fail on Cloud TPU.
  tests/memories_test.py
  tests/pallas/tpu_pallas_test.py
Labels: pull ready

#22465 [ROCM] test_computation_follows_data fix for rocm and cuda
  tests/multi_device_test.py
Labels: pull ready

#22475 Fix lint at head
  jax/_src/nn/functions.py
Labels: pull ready

#22441 Add some hypothesis testing utilities and developer documentation.
  docs/developer.md
  jax/_src/test_util.py
  tests/pallas/indexing_test.py
  tests/pallas/tpu_splash_attention_kernel_test.py
  tests/state_test.py
Labels: pull ready

#22418 DOC: Improved docs for `jnp.median` and `nanmedian`
  jax/_src/numpy/reductions.py
Labels: pull ready

#22386 Unifying persistent cache messages
  jax/__init__.py
  jax/_src/compilation_cache.py
  jax/_src/compiler.py
  tests/compilation_cache_test.py
Labels: pull ready

#20021 [Pallas TPU] Add matrix multiplication tutorial
  docs/conf.py
  docs/pallas/tpu/index.rst
  docs/pallas/tpu/matmul.ipynb
  docs/pallas/tpu/matmul.md
Labels: pull ready

#22263 Don't wrap singleton ir.Types during HLO lowering.
  jax/_src/ad_checkpoint.py
  jax/_src/export/_export.py
  jax/_src/interpreters/mlir.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/_src/pjit.py
  jax/experimental/jax2tf/call_tf.py
  jax/interpreters/mlir.py
  tests/jaxpr_effects_test.py
Labels: pull ready

#22439 DOC: Improved docs for `jnp.fft.fft` and `jnp.fft.ifft`
  jax/_src/numpy/fft.py
Labels: pull ready

#22497 re-export RNG primitives from `jax.extend.core.primitives`
  jax/extend/core/primitives.py
Labels: pull ready

#22517 adopt numpy rank promotion config in metal test
  tests/lax_metal_test.py
Labels: pull ready

#22520 [Pallas TPU] Minor matmul docs improvement
  docs/pallas/tpu/matmul.ipynb
  docs/pallas/tpu/matmul.md
Labels: pull ready

#22529 Export `jaxlib.xla_client.register_custom_call_target` as `jax.extend.ffi.register_ffi_target`
  docs/jax.extend.ffi.rst
  jax/_src/extend/ffi.py
  jax/extend/ffi.py
Labels: pull ready

#22526 [Pallas TPU] Copy improvements to Matmul Tutorial
  docs/pallas/tpu/matmul.ipynb
  docs/pallas/tpu/matmul.md
Labels: pull ready

#21567 skip _origin_msg invar debug info if invar_pos/arg_info is malformed
  jax/_src/core.py
  jax/_src/interpreters/partial_eval.py
Labels: pull ready

#22442 [pallas] Thread the interpret= parameter to pallas_call.
  jax/experimental/pallas/ops/tpu/splash_attention/splash_attention_kernel.py
  tests/pallas/BUILD
  tests/pallas/gpu_attention_test.py
  tests/pallas/gpu_ops_test.py
  tests/pallas/tpu_splash_attention_kernel_test.py
Labels: pull ready

#22541 make core.as_named_shape treat `int` like `tuple[int]`
  jax/_src/core.py
  tests/random_test.py
Labels: pull ready

#22519 Support `pathlib.Path` input to `start_trace`
  jax/_src/profiler.py
  tests/profiler_test.py
Labels: pull ready

#22543 [shard_map] shard_map check_rep=True rules for custom_linear_solve
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#22550 [pallas] Fix the handling of captured consts
  jax/_src/pallas/core.py
  jax/_src/pallas/mosaic/lowering.py
  jax/_src/pallas/mosaic/pallas_call_registration.py
  jax/_src/pallas/mosaic_gpu/pallas_call_registration.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pallas/triton/lowering.py
  jax/_src/pallas/triton/pallas_call_registration.py
  jax/_src/state/utils.py
  tests/pallas/pallas_test.py
  tests/pallas/pallas_vmap_test.py
  tests/pallas/tpu_pallas_test.py
Labels: pull ready

#22540 Fix docstring of jnp.nonzero
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#22515 Speed up pre-commit by filtering jupytext to only run on files in docs
  .pre-commit-config.yaml
Labels: pull ready

#22567 jax.scipy.fft: error for unsupported norm argument
  jax/_src/scipy/fft.py
Labels: pull ready

#22514 Fixing dtype canonicalization in sharp edges tutorial
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
Labels: pull ready

#22544 [shard_map] fix psum rewrite rule's pbroadcast logic
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#22512 Fix dtype canonicalization in `jnp.indices`
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#22571 jax.scipy.fft.dct: implement & test norm='backward'
  jax/_src/scipy/fft.py
  tests/scipy_fft_test.py
Labels: pull ready

#22530 Documented a few more Pallas APIs and added them to the API docs
  docs/jax.experimental.pallas.rst
  jax/_src/pallas/primitives.py
Labels: pull ready

#22579 Removed unused ``_broadcast_translate``
  jax/_src/lax/lax.py
Labels: pull ready

#22582 add test for #17691
  tests/shard_map_test.py
Labels: pull ready

#22585 make grad-of-pmap with out_axes=None raise NotImplementedError
  jax/_src/interpreters/ad.py
Labels: pull ready

#22558 Fixed pl.BlockSpec argument ordering in the Pallas TPU matmul tutorial
  docs/pallas/tpu/matmul.ipynb
  docs/pallas/tpu/matmul.md
Labels: pull ready

#22559 Another take at enabling Pallas GPU tests on x64
  jax/_src/core.py
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pallas/primitives.py
  jax/_src/pallas/triton/BUILD
  jax/_src/pallas/triton/lowering.py
  jax/_src/state/primitives.py
  jax/_src/state/types.py
  tests/pallas/BUILD
  tests/pallas/pallas_test.py
Labels: pull ready

#22487 DOC: Improved docs for jnp.fft.rfft and irfft
  jax/_src/numpy/fft.py
Labels: pull ready

#22588 DOC: Improved docs for `jnp.tri`, `jnp.tril` and `jnp.triu`
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#22594 Add missing parameters to jnp.compress type interface
  jax/numpy/__init__.pyi
Labels: pull ready

#22574 Remove the unaccelerate_deprecation utility
  jax/_src/api.py
  jax/_src/deprecations.py
  jax/_src/test_util.py
  pyproject.toml
  tests/api_test.py
Labels: pull ready

#22597 [array API] add device property & to_device method
  CHANGELOG.md
  jax/_src/array.py
  jax/_src/basearray.py
  jax/_src/basearray.pyi
  jax/_src/core.py
  jax/_src/earray.py
  jax/_src/numpy/array_methods.py
  jax/experimental/array_api/_array_methods.py
  tests/array_test.py
Labels: pull ready

#22610 fix memory leak in cond jaxpr tracing
  jax/_src/lax/control_flow/common.py
  tests/core_test.py
  tests/lax_control_flow_test.py
Labels: pull ready

#22552 [pallas] Simplify GridMapping
  docs/pallas/grid_blockspec.md
  jax/_src/pallas/core.py
  jax/_src/pallas/mosaic/core.py
  jax/_src/pallas/mosaic/lowering.py
  jax/_src/pallas/mosaic/pallas_call_registration.py
  jax/_src/pallas/mosaic_gpu/lowering.py
  jax/_src/pallas/mosaic_gpu/pallas_call_registration.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pallas/triton/lowering.py
  jax/_src/pallas/triton/pallas_call_registration.py
  tests/export_back_compat_test.py
  tests/pallas/gpu_ops_test.py
  tests/pallas/pallas_shape_poly_test.py
  tests/pallas/pallas_test.py
  tests/pallas/pallas_vmap_test.py
  tests/pallas/tpu_pallas_test.py
  tests/pallas/tpu_splash_attention_kernel_test.py
Labels: pull ready

#22636 lax_numpy_test: fix some typos
  tests/lax_numpy_test.py
Labels: pull ready

#22555 DOC: Improved docs for `jnp.fft.fft2` and `jnp.fft.ifft2`
  jax/_src/numpy/fft.py
Labels: pull ready

#22616 DOC: Improved docs for `jnp.triu_indices` and `jnp.tril_indices`
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#22629 Don't broadcast scalar conditions in the jnp.where implementation().
  jax/_src/numpy/util.py
Labels: pull ready

#22640 Fix incorrect usage of assertWarns in tests
  tests/deprecation_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#22625 Simplify implementation of _broadcast_to.
  jax/_src/numpy/util.py
  tests/dynamic_api_test.py
Labels: pull ready

#22634 [array API] clean up some unused/unnecessary code
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_array_methods.py
  jax/experimental/array_api/_linear_algebra_functions.py
  jax/experimental/array_api/_statistical_functions.py
  jax/experimental/array_api/linalg.py
Labels: pull ready

#21069 remove named shapes from avals
  jax/_src/api.py
  jax/_src/api_util.py
  jax/_src/array.py
  jax/_src/core.py
  jax/_src/custom_derivatives.py
  jax/_src/export/_export.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/lax.py
  jax/_src/lax/parallel.py
  jax/_src/lax/utils.py
  jax/_src/nn/initializers.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pjit.py
  jax/_src/prng.py
  jax/_src/random.py
  jax/_src/state/types.py
  jax/core.py
  jax/experimental/shard_map.py
  tests/api_test.py
  tests/core_test.py
  tests/lax_test.py
Labels: pull ready

#22628 Simplify promote_shapes.
  jax/_src/lax/lax.py
  jax/_src/numpy/util.py
Labels: pull ready

#22605 [cuDNN SDPA] add sm86/sm89 flash attention support
  jax/_src/cudnn/fused_attention_stablehlo.py
  tests/fused_attention_stablehlo_test.py
Labels: pull ready

#22642 [ROCM] rocm plugin is no longer experiemental!
  jax/_src/xla_bridge.py
Labels: pull ready

#22653 Fix `jnp.triu_indices_from` and `jnp.tril_indices_from` to emulate NumPy's behavior for non 2-D input
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#22663 [array API] clean up some superseded definitions
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_data_type_functions.py
  jax/experimental/array_api/skips.txt
Labels: pull ready

#22665 DOC: Better docs for jnp.triu_indices_from and tril_indices_from
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#22619 Simplify and rename GPU process mocking settings
  jax/_src/xla_bridge.py
  tests/mock_gpu_test.py
Labels: pull ready

#22668 Show elapsed time in nanoseconds
  jax/_src/interpreters/pxla.py
  jax/_src/pjit.py
Labels: pull ready

#22669 Simplify jaxpr for jnp.repeat in scalar repeat case.
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#22674 remove pdot and xeinsum (since xmap is gone)
  jax/_src/lax/parallel.py
  jax/lax/__init__.py
  tests/batching_test.py
  tests/pmap_test.py
Labels: pull ready

#22673 deflake cond memory leak regression test
  tests/lax_control_flow_test.py
Labels: pull ready

#22283 [Pallas TPU] Add lowering for `lax.sign`
  jax/_src/pallas/mosaic/lowering.py
  tests/pallas/tpu_ops_test.py
Labels: pull ready

#22556 Show cache key when logging compilation cache hits/misses
  jax/_src/compilation_cache.py
  jax/_src/compiler.py
Labels: pull ready

#22680 Bumped jaxlib version mypy uses on the CI
  .pre-commit-config.yaml
  jax/_src/array.py
  jax/_src/core.py
  jax/_src/custom_partitioning.py
  jax/_src/debugging.py
  jax/_src/export/_export.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/lax.py
  jax/_src/lax/other.py
  jax/_src/lru_cache.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/linalg.py
  jax/_src/pallas/triton/pallas_call_registration.py
  jax/_src/xla_bridge.py
  pyproject.toml
Labels: pull ready

#22080 Added device kwarg to jnp.linspace and jnp.asarray
  jax/_src/lax/lax.py
  jax/_src/numpy/lax_numpy.py
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_creation_functions.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#22684 `random` doc: implementation differences and vmap compatibility
  jax/random.py
Labels: pull ready

#22593 [pallas] More simplification of grid mapping and calling convention
  docs/jax.experimental.pallas.rst
  docs/pallas/CHANGELOG.md
  jax/_src/core.py
  jax/_src/pallas/core.py
  jax/_src/pallas/mosaic/core.py
  jax/_src/pallas/mosaic/lowering.py
  jax/_src/pallas/mosaic/pallas_call_registration.py
  jax/_src/pallas/mosaic/pipeline.py
  jax/_src/pallas/mosaic_gpu/lowering.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pallas/triton/lowering.py
  jax/_src/pallas/triton/pallas_call_registration.py
  jax/experimental/pallas/__init__.py
Labels: pull ready

#22690 Improve documentation for jnp.put, jnp.place, jnp.fill_diagonal
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#19760 Update sparse.grad() to support re-packing gradients into PyTrees
  jax/experimental/sparse/ad.py
  tests/sparse_test.py
Labels: pull ready

#22703 Skip cuda backend initialization if no nvidia GPUs are visible
  jax/_src/hardware_utils.py
  jax/_src/xla_bridge.py
Labels: pull ready

#22734 [array API] move api metadata into jax.numpy namespace
  jax/_src/numpy/array_api_metadata.py
  jax/_src/numpy/array_methods.py
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_array_methods.py
  jax/numpy/__init__.py
Labels: pull ready

#22736 [array API] add device argument to fftfreq & rfftfreq
  jax/_src/basearray.pyi
  jax/_src/numpy/fft.py
  jax/experimental/array_api/_fft_functions.py
  jax/experimental/array_api/fft.py
Labels: pull ready

#22716 Added a trivial discharge rule for debug_callback_p
  jax/_src/debugging.py
  tests/pallas/ops_test.py
Labels: pull ready

#22481 Enable the passed tests for memories and layout
  tests/layout_test.py
  tests/memories_test.py
Labels: pull ready

#22704 [pallas] Improve error localization
  CHANGELOG.md
  docs/pallas/CHANGELOG.md
  jax/_src/interpreters/partial_eval.py
  jax/_src/pallas/core.py
  jax/_src/pallas/mosaic/pipeline.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pallas/primitives.py
  tests/pallas/pallas_test.py
  tests/pallas/tpu_pallas_test.py
Labels: pull ready

#22764 [array API] move api metadata into jax.numpy namespace
  jax/_src/numpy/array_api_metadata.py
  jax/_src/numpy/array_methods.py
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_array_methods.py
  jax/numpy/__init__.py
Labels: pull ready

#22085 Follow-up on adding device kwarg to jnp.fft.fftfreq and jnp.fft.rfftfreq
  jax/_src/numpy/fft.py
  tests/fft_test.py
Labels: pull ready

#22766 [array api] remove redundant definitions for clip() & hypot()
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_elementwise_functions.py
Labels: pull ready

#22768 jnp.reshape: add copy argument for Array API
  jax/_src/numpy/lax_numpy.py
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_manipulation_functions.py
Labels: pull ready

#22781 Fix arcsinh accuracy test failure
  tests/lax_test.py
Labels: pull ready

#22744 Fix `jax.scipy.stats.betabinom.logpmf` and `binom.logpmf` for JAX to emulate SciPy's behavior when `k=n=0`
  jax/_src/scipy/stats/betabinom.py
  jax/_src/scipy/stats/binom.py
  tests/scipy_stats_test.py
Labels: pull ready

#22735 Add optional automatic remat optimization to custom_vjp
  jax/_src/custom_derivatives.py
  jax/custom_derivatives.py
  jax/experimental/jax2tf/jax2tf.py
  tests/api_test.py
Labels: pull ready

#22746 [pallas] Disallow capturing of consts by kernel functions
  docs/pallas/CHANGELOG.md
  jax/_src/pallas/core.py
  jax/_src/pallas/mosaic/lowering.py
  jax/_src/pallas/mosaic_gpu/pallas_call_registration.py
  jax/_src/pallas/pallas_call.py
  tests/pallas/ops_test.py
  tests/pallas/pallas_test.py
  tests/pallas/pallas_vmap_test.py
  tests/pallas/tpu_pallas_test.py
Labels: pull ready

#22792 temporary flag for vmap shmap error suppression
  jax/_src/config.py
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#22477 [NVIDIA] Support GQA and MQA for `jax.nn.dot_product_attention`.
  jax/_src/nn/functions.py
  tests/nn_test.py
Labels: pull ready

#22797 Improve error when indexing with too many indices
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#22800 jnp.where: explicitly use mode='drop' when out-of-bound indices expected
  jax/_src/numpy/lax_numpy.py
Labels: pull ready
