Repository jax-ml/jax, pull requests merged in 2024-12, with the labels that each got.

#25136 [ROCm] Add argument to override base docker in dockerfile
  build/rocm/Dockerfile.ms
  build/rocm/ci_build
  build/rocm/ci_build.sh
Labels: pull ready

#25117 Use next after tiny as smallest floating point value in complex functions accuracy tests on Mac ARM.
  jax/_src/test_util.py
  tests/lax_test.py
Labels: pull ready

#25216 [shape_poly] Remove obsolete part of the shape polymorphism documentation
  docs/export/shape_poly.md
Labels: kokoro:force-run, pull ready

#24964 Add an option to deactivate automatic cluster detection in jax.distributed.initialize().
  jax/_src/distributed.py
Labels: pull ready

#25210 Skip vecmat & matvec in NumPy tests.
  tests/lax_numpy_test.py
Labels: pull ready

#25231 Fix nightly numpy test
  tests/lax_numpy_test.py
Labels: pull ready

#25162 Fix some typos
  docs/gpu_performance_tips.md
  docs/gradient-checkpointing.md
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
  docs/notebooks/autodiff_remat.ipynb
  docs/notebooks/autodiff_remat.md
  docs/xla_flags.md
Labels: pull ready

#24748 jnp.reshape: raise TypeError when specifying newshape
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#25237 Improve trace-time performance of jnp.isscalar
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#25246 Fix Windows portability problem in compilation cache test.
  tests/compilation_cache_test.py
Labels: pull ready

#25239 Fix indexing corner case with empty ellipses
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#25264 CI: update array-api-tests to latest commit
  .github/workflows/jax-array-api.yml
Labels: pull ready

#25199 Return residuals in the decode attention pallas kernel
  jax/experimental/pallas/ops/gpu/decode_attention.py
  tests/pallas/gpu_attention_test.py
Labels: pull ready

#25114 Add exec_time_optimization_effort and memory_fitting_effort flags - fixes #24715
  CHANGELOG.md
  jax/_src/compiler.py
  jax/_src/config.py
Labels: pull ready

#25276 remove vestigial ad.reducing_transposes table
  jax/_src/ad_checkpoint.py
  jax/_src/interpreters/ad.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/pjit.py
Labels: pull ready

#25271 jnp.linalg.vector_norm: properly support multiple axes
  jax/_src/numpy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#25290 jax.numpy: require boolean dtype for where argument
  jax/_src/deprecations.py
  jax/_src/numpy/reductions.py
  tests/lax_numpy_reducers_test.py
Labels: pull ready

#25269 [Pallas] Pallas documentation cleanup
  docs/pallas/design/async_note.md
  docs/pallas/design/design.md
  docs/pallas/design/index.rst
  docs/pallas/grid_blockspec.md
  docs/pallas/index.rst
  docs/pallas/quickstart.ipynb
  docs/pallas/quickstart.md
  docs/pallas/tpu/pipelining.ipynb
  docs/pallas/tpu/pipelining.md
Labels: pull ready

#25296 Postrelease
  jax/version.py
  setup.py
Labels: pull ready

#25252 [shape_poly] Fix the handling of __pow__ for symbolic dimensions
  jax/_src/export/shape_poly.py
  tests/shape_poly_test.py
Labels: pull ready

#25205 Fix error when swapping a ref with a trivial indexing transform.
  jax/_src/state/discharge.py
  tests/state_test.py
Labels: pull ready

#25082 Document cudaMallocAsync
  docs/gpu_memory_allocation.rst
Labels: pull ready

#25338 Fix type annotation for numpy.linalg.matrix_norm argument 'ord'.
  jax/_src/numpy/linalg.py
Labels: pull ready

#25349 Use private names for args in api_util to avoid shadowing kwargs keys
  jax/_src/api_util.py
Labels: pull ready

#25294 array API: improve test coverage
  .github/workflows/jax-array-api.yml
  tests/array_api_skips.txt
Labels: pull ready

#25355 Avoid index out of range error in carry structure check
  CHANGELOG.md
  jax/_src/lax/control_flow/loops.py
  tests/lax_control_flow_test.py
Labels: pull ready

#25272 [Pallas] Update TPU documentation
  docs/_static/pallas/vector_layout_example.svg
  docs/pallas/tpu/details.rst
  docs/pallas/tpu/sparse.ipynb
  docs/pallas/tpu/sparse.md
Labels: pull ready

#25368 Merge release/0.4.37 into main.
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: pull ready

#25371 CI: temporarily pin numpy version for mypy check
  .pre-commit-config.yaml
Labels: kokoro:force-run, pull ready

#25335 [export] Improved the documentation.
  docs/developer.md
  docs/jax.export.rst
  jax/_src/export/_export.py
Labels: pull ready

#25374 Update conda-forge installation docs after drop of support for CUDA 11
  docs/installation.md
Labels: pull ready

#25369 Add a `freeze` primitive to delimit ref lifetimes for AD.
  jax/_src/core.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/lax.py
  jax/_src/pjit.py
  jax/_src/state/discharge.py
  jax/_src/state/primitives.py
  tests/mutable_array_test.py
Labels: pull ready

#25378 Remove code in jax2tf for compatibility with TF 2.10 or earlier.
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: pull ready

#25357 jax.core: deprecate a number of APIs
  CHANGELOG.md
  docs/contributor_guide.rst
  docs/jax.extend.core.rst
  docs/jax.extend.rst
  docs/jax_internal_api.rst
  jax/_src/cudnn/fused_attention_stablehlo.py
  jax/_src/cudnn/fusion.py
  jax/_src/pallas/mosaic/pallas_call_registration.py
  jax/_src/pallas/mosaic_gpu/BUILD
  jax/_src/pallas/mosaic_gpu/pallas_call_registration.py
  jax/_src/pallas/triton/BUILD
  jax/_src/pallas/triton/pallas_call_registration.py
  jax/_src/pallas/triton/primitives.py
  jax/_src/tpu_custom_call.py
  jax/core.py
  jax/experimental/mosaic/gpu/core.py
  jax/experimental/sparse/_lowerings.py
  jax/experimental/sparse/nm.py
  tests/key_reuse_test.py
  tests/pjit_test.py
Labels: pull ready

#25361 Adding more tests for multi-head attention
  tests/pallas/gpu_ops_test.py
Labels: pull ready

#25392 Add test of relu grad at zero. Update paper links.
  jax/_src/nn/functions.py
  tests/nn_test.py
Labels: pull ready

#25390 jax.numpy: implement matvec & vecmat
  docs/jax.numpy.rst
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#25387 jax.core: more API deprecations
  jax/core.py
Labels: pull ready

#25403 Minor change in the README, remove "expect bugs"
  README.md
Labels: pull ready

#25395 [shape_poly] Improve reasoning for >= in presence of == constraints.
  jax/_src/export/shape_poly.py
  jax/_src/export/shape_poly_decision.py
  tests/shape_poly_test.py
Labels: pull ready

#25401 Add Rotation return type hint to Rotation.__mul__()
  jax/_src/scipy/spatial/transform.py
Labels: pull ready

#25407 [ROCm] Remove cuda include from gpu plugin extension
  jaxlib/BUILD
  jaxlib/gpu_plugin_extension.cc
Labels: pull ready

#23225 aarch64: add aarch64 mkldnn+acl build config
  .bazelrc
  build/build.py
Labels: pull ready

#25414 Finalize some deprecations in jax.core, jax.lib.xla_bridge, and jax.lib.xla_client
  CHANGELOG.md
  docs/jax.lib.rst
  jax/core.py
  jax/lib/xla_bridge.py
  jax/lib/xla_client.py
Labels: pull ready

#25419 jax.lax: raise TypeError for mismatched dtypes
  jax/_src/lax/lax.py
  tests/lax_test.py
Labels: pull ready

#25422 internal: simplify broadcast_shapes logic
  jax/_src/lax/lax.py
Labels: kokoro:force-run, pull ready

#25381 Run mypy with latest NumPy
  .pre-commit-config.yaml
  jax/_src/dtypes.py
  jax/_src/interpreters/mlir.py
  jax/_src/mesh_utils.py
  jax/_src/numpy/linalg.py
  jax/_src/numpy/polynomial.py
  jax/_src/op_shardings.py
  jax/_src/sharding_impls.py
  jax/_src/sharding_specs.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/linalg.py
Labels: pull ready, CI

#25424 internal: dedupe lax broadcasting logic
  jax/_src/lax/lax.py
Labels: pull ready

#25425 Fixes to direct linearize
  jax/_src/interpreters/ad.py
Labels: pull ready

#25426 Don't monkey-patch functions in test_utils to count events for tests.
  examples/ffi/tests/cpu_examples_test.py
  jax/_src/array.py
  jax/_src/dispatch.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  jax/_src/pjit.py
  jax/_src/stages.py
  jax/_src/test_util.py
  jax/_src/util.py
  jax/experimental/colocated_python/func.py
  tests/api_test.py
  tests/checkify_test.py
  tests/colocated_python_test.py
  tests/lax_control_flow_test.py
  tests/layout_test.py
  tests/memories_test.py
  tests/multi_device_test.py
  tests/pgle_test.py
  tests/pjit_test.py
  tests/pmap_test.py
  tests/python_callback_test.py
  tests/random_lax_test.py
  tests/random_test.py
  tests/shard_alike_test.py
  tests/shard_map_test.py
Labels: pull ready

#25409 [shape_poly] Improve handling of mod(e, k) == 0 constraints.
  jax/_src/export/shape_poly.py
  tests/shape_poly_test.py
Labels: pull ready

#25442 Cleanup: remove uses of no-op raise_to_shaped
  jax/_src/abstract_arrays.py
  jax/_src/ad_util.py
  jax/_src/api.py
  jax/_src/api_util.py
  jax/_src/checkify.py
  jax/_src/custom_batching.py
  jax/_src/custom_derivatives.py
  jax/_src/custom_partitioning.py
  jax/_src/export/_export.py
  jax/_src/export/shape_poly.py
  jax/_src/extend/ffi.py
  jax/_src/lax/control_flow/common.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/control_flow/solves.py
  jax/_src/pallas/mosaic/primitives.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pjit.py
  jax/_src/random.py
  jax/_src/state/types.py
  jax/_src/state/utils.py
  jax/experimental/attrs.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/sparse/transform.py
Labels: pull ready

#25452 Cleanup: replace lax._abstractify with core.get_aval
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/_src/lax/windowed_reductions.py
Labels: pull ready

#25454 Add flag desc to gpu_performance_tips.md
  docs/gpu_performance_tips.md
Labels: pull ready

#25459 Use a broadcasted gather in the sort JVP, rather than forming explici…
  jax/_src/lax/lax.py
  tests/lax_autodiff_test.py
Labels: pull ready

#25451 temporarily un-deprecate several jax.core APIs.
  CHANGELOG.md
  jax/core.py
Labels: pull ready

#25444 Remove deprecated XLA GPU flags from docs.
  docs/gpu_performance_tips.md
Labels: pull ready

#24536 Limit self-hosted jobs to JAX main repo
  .github/workflows/asan.yaml
  .github/workflows/ci-build.yaml
Labels: pull ready

#25481 Implement `process_call` for LinearizeTrace
  jax/_src/interpreters/ad.py
  jax/_src/pjit.py
Labels: pull ready

#25487 fix `gamma_p` in vmap-based impl rule mode
  jax/_src/random.py
Labels: pull ready

#25435 [export] Expand exporting to work with AbstractMesh.
  CHANGELOG.md
  docs/export/export.md
  jax/_src/export/_export.py
  jax/_src/interpreters/pxla.py
  jax/_src/mesh.py
  tests/export_test.py
Labels: pull ready

#25511 Fix incorrect capitalization in scan error message
  jax/_src/lax/control_flow/loops.py
  tests/lax_control_flow_test.py
Labels: pull ready

#25508 Re-deprecate a number of symbols from jax.core
  jax/core.py
Labels: pull ready

#25473 get_githash: fix support for missing git
  build/tools/utils.py
Labels: pull ready

#25456 Cleanup: toward merging core.concrete_aval & xla.abstractify
  benchmarks/api_benchmark.py
  jax/_src/abstract_arrays.py
  jax/_src/api_util.py
  jax/_src/array.py
  jax/_src/core.py
  jax/_src/dispatch.py
  jax/_src/export/shape_poly.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  jax/_src/interpreters/xla.py
  jax/_src/pjit.py
  jax/_src/prng.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/roofline/roofline.py
  tests/lax_test.py
Labels: pull ready

#25538 Raise rather than return error
  jax/_src/core.py
Labels: pull ready

#25534 Streamline some core.concrete_aval compute paths
  jax/_src/abstract_arrays.py
Labels: pull ready

#25544 Always use the same code for array avals
  jax/_src/abstract_arrays.py
  jax/_src/array.py
Labels: pull ready

#25550 Merge release/0.4.38 branch and update version numbers.
  CHANGELOG.md
  jax/_src/tree_util.py
  jax/version.py
  setup.py
Labels: pull ready

#25548 [Mosaic GPU] Enable 64-bit types in test_scalar_argument
  tests/mosaic/gpu_test.py
Labels: pull ready

#25555 Remove core.concrete_aval and replace with abstractify
  CHANGELOG.md
  jax/_src/abstract_arrays.py
  jax/_src/array.py
  jax/_src/core.py
  jax/_src/export/shape_poly.py
  jax/_src/interpreters/xla.py
  jax/_src/prng.py
  jax/core.py
  jax/interpreters/xla.py
  tests/lax_test.py
Labels: pull ready

#24516 improve checkpoint / remat concreteness error with static_argnums
  jax/_src/ad_checkpoint.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/linear_util.py
  jax/_src/pallas/core.py
  jax/interpreters/partial_eval.py
  tests/api_test.py
Labels: better_errors, pull ready

#25449 add error checks for refs, behind a flag
  jax/_src/config.py
  jax/_src/core.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/pjit.py
  tests/attrs_test.py
  tests/mutable_array_test.py
Labels: pull ready

#25559 Bump xla_extension_version after jaxlib release.
  jax/_src/tree_util.py
  tests/aot_test.py
  tests/colocated_python_test.py
  tests/layout_test.py
Labels: pull ready

#23830 Use StableHLO acos. Update complex acos accuracy tests.
  jax/_src/lax/lax.py
  jax/experimental/jax2tf/jax2tf.py
  tests/lax_test.py
Labels: pull ready

#25412 [Pallas-Triton] Fix squeeze lowering required sharding argument
  jax/_src/pallas/triton/lowering.py
Labels: pull ready

#25490 More linearize fixes
  jax/_src/interpreters/ad.py
Labels: pull ready

#25596 remove whitespace from distributed arrays doc
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.ipynb
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.md
Labels: pull ready

#25593 add mutable array ref error checks to scan
  jax/BUILD
  jax/_src/api_util.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/pjit.py
  tests/mutable_array_test.py
Labels: pull ready

#25595 Refactor: move shaped_abstractify to core
  jax/_src/abstract_arrays.py
  jax/_src/api_util.py
  jax/_src/array.py
  jax/_src/core.py
  jax/_src/earray.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/prng.py
Labels: pull ready

#25590 jax.nn.one_hot: deprecate non-integer inputs
  jax/_src/deprecations.py
  jax/_src/nn/functions.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  tests/nn_test.py
  tests/shape_poly_test.py
Labels: pull ready

#25516 JEP: effort-based versioning (EffVer)
  docs/jep/25516-effver.md
  docs/jep/index.rst
Labels: pull ready

#25148 [ROCm] ci build and dockerfile changes
  build/rocm/build_wheels/Dockerfile.manylinux_2_28_x86_64.rocm
  build/rocm/ci_build
  build/rocm/tools/get_rocm.py
Labels: pull ready

#25440 [ROCm] Create PyPI wheel upload script and setup.py bindings
  README.md
  build/rocm/README.md
  build/rocm/tools/build_wheels.py
  docs/developer.md
  docs/installation.md
  setup.py
Labels: pull ready

#25606 Add support for N-D FFTs with N>3
  CHANGELOG.md
  jax/_src/numpy/fft.py
  tests/fft_test.py
Labels: pull ready

#25614 Remove internal uses of api_util.shaped_abstractify
  benchmarks/api_benchmark.py
  jax/_src/ad_checkpoint.py
  jax/_src/api.py
  jax/_src/api_util.py
  jax/_src/array.py
  jax/_src/debugging.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/numpy/util.py
  jax/_src/pjit.py
  jax/_src/shard_alike.py
  jax/api_util.py
  jax/experimental/jet.py
  jax/experimental/shard_map.py
  tests/jax_jit_test.py
Labels: kokoro:force-run, pull ready

#25625 add mutable array ref error checks to cond and custom_vjp
  jax/_src/custom_derivatives.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/control_flow/common.py
  jax/_src/lax/control_flow/conditionals.py
  tests/mutable_array_test.py
Labels: pull ready

#25616 Unify abstractify & shaped_abstractify rules
  jax/_src/abstract_arrays.py
  jax/_src/api.py
  jax/_src/core.py
  jax/_src/export/shape_poly.py
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#25646 Add int4/uint4 support to bitcast_convert_type
  jax/_src/dtypes.py
  jax/_src/lax/lax.py
  jax/_src/lax_reference.py
  tests/lax_test.py
Labels: pull ready

#25648 Avoid calls to warnings.catch_warnings in JAX core code.
  jax/_src/flatten_util.py
  jax/_src/lax/lax.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/reductions.py
Labels: kokoro:force-run, pull ready

#25416 DOC: clarify API compatibility discussion
  docs/api_compatibility.md
  docs/jep/25516-effver.md
Labels: pull ready

#25650 Support int4/uint4 in jnp.ndarray.view
  jax/_src/dtypes.py
  jax/_src/numpy/array_methods.py
  tests/lax_numpy_test.py
Labels: pull ready

#25667 [mosaic_gpu] Include Mosaic GPU dialect fiels into jaxlib
  jaxlib/mosaic/BUILD
  jaxlib/setup.py
  jaxlib/tools/build_wheel.py
Labels: pull ready

#24607 [NVIDIA] Cudnn dot_product_attention supports head size up to 256
  jax/_src/cudnn/fused_attention_stablehlo.py
  tests/fused_attention_stablehlo_test.py
Labels: pull ready

#25651 Internal: use a single registry for abstractify APIs
  jax/_src/abstract_arrays.py
  jax/_src/api.py
  jax/_src/array.py
  jax/_src/core.py
  jax/_src/earray.py
  jax/_src/export/shape_poly.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/prng.py
  jax/core.py
Labels: pull ready

#25673 changelog: link to api compatibility & python version docs
  CHANGELOG.md
Labels: pull ready

#25669 Remove casting from jax.nn.one_hot
  jax/_src/nn/functions.py
Labels: pull ready

#25672 Finalize deprecation of some symbols from jax.lib.xla_client
  CHANGELOG.md
  jax/lib/xla_client.py
Labels: pull ready

#25692 Fixes incorrect sharding lowering for key<fry> in shard_map partial-auto
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready
