Repository jax-ml/jax, pull requests merged in 2024-09, with the labels that each got.

#23298 docs: batched wording edits
  docs/debugging.md
  docs/debugging/checkify_guide.md
  docs/debugging/flags.md
  docs/debugging/index.md
  docs/debugging/print_breakpoint.md
  docs/distributed_data_loading.md
  docs/installation.md
  docs/investigating_a_regression.md
  docs/multi_process.md
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
  docs/notebooks/Custom_derivative_rules_for_Python_code.ipynb
  docs/notebooks/Custom_derivative_rules_for_Python_code.md
  docs/notebooks/autodiff_cookbook.ipynb
  docs/notebooks/autodiff_cookbook.md
  docs/notebooks/autodiff_remat.ipynb
  docs/notebooks/autodiff_remat.md
  docs/notebooks/shard_map.ipynb
  docs/notebooks/shard_map.md
  docs/sharded-computation.ipynb
  docs/sharded-computation.md
Labels: documentation, pull ready

#23284 Adding sliding window attention support in cuDNN SDPA API
  jax/_src/cudnn/fused_attention_stablehlo.py
  tests/fused_attention_stablehlo_test.py
Labels: pull ready

#23386 Fixed the return type of ``jax.random.key_impl``
  jax/_src/random.py
Labels: pull ready

#23361 use `jax.tree` consistently in example optimizers
  jax/example_libraries/optimizers.py
Labels: pull ready

#23365 DOC:Better docs for jax.numpy: sin, cos and tan
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#23387 tweak shmap implementation to work better with leak checker
  jax/experimental/shard_map.py
Labels: pull ready

#23371 DOC: Better docs for `jax.numpy`: `round`, `around` and `round_`
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#23353 refactor jax.lax to not depend on jax.numpy
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/control_flow/solves.py
  jax/_src/lax/eigh.py
  jax/_src/lax/fft.py
  jax/_src/lax/lax.py
  jax/_src/lax/linalg.py
  jax/_src/lax/other.py
  jax/_src/lax/parallel.py
  jax/_src/lax/qdwh.py
  jax/_src/lax/slicing.py
  jax/_src/lax/stack.py
  jax/_src/lax/svd.py
  jax/_src/scipy/linalg.py
Labels: pull ready

#22843 feat(lib): add real-valued implementation of `jax.scipy.special.fresnel`
  docs/jax.scipy.rst
  jax/_src/third_party/scipy/special.py
  jax/scipy/special.py
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#23397 Deprecate `jax.numpy.round_`
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.py
Labels: pull ready

#23396 Relax test tolerances to fix CI failures on Mac ARM.
  tests/for_loop_test.py
  tests/lax_control_flow_test.py
Labels: pull ready

#23407 Add TPU v6e to the list of known TPUs.
  jax/_src/hardware_utils.py
Labels: pull ready

#23394 [ffi] Add support for token inputs and outputs
  jax/_src/extend/ffi.py
  tests/extend_test.py
Labels: pull ready

#23422 Update sharded-computation doc to use `make_mesh()`
  docs/sharded-computation.ipynb
  docs/sharded-computation.md
Labels: kokoro:force-run, pull ready

#23417 better true_divide and divide docs
  jax/_src/numpy/ufuncs.py
  tests/lax_numpy_test.py
Labels: kokoro:force-run, pull ready

#23398 Fix pytype errors and args for jax.Array methods
  jax/_src/basearray.pyi
  jax/_src/numpy/array_methods.py
Labels: pull ready

#23364 DOC: Better docs for jax.numpy: log and log1p
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#23433 random.key_impl: improve repr of output
  jax/_src/random.py
  tests/random_test.py
Labels: pull ready

#23434 Remove unused docstring addition: `_PRECISION_DOC`
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23430 update example optimizers library docstring
  jax/example_libraries/optimizers.py
Labels: pull ready

#23412 Refactor & document cumulative reductions
  jax/_src/numpy/reductions.py
  jax/numpy/__init__.pyi
  tests/filecheck/subcomputations.filecheck.py
Labels: documentation, pull ready

#23257 Add citation for random.orthogonal.
  jax/_src/random.py
Labels: pull ready

#22699 Add cudnn_fusion decorator lowering computations to XLA cuDNN fusions.
  jax/_src/cudnn/__init__.py
  jax/_src/cudnn/fusion.py
  tests/BUILD
  tests/cudnn_fusion_test.py
Labels: pull ready

#23458 Add support for the DeviceLocalLayout API when lowering FFI calls.
  jax/_src/extend/ffi.py
  tests/extend_test.py
Labels: pull ready

#23465 Typos in documentation
  docs/_tutorials/jax-primitives.md
  docs/type_promotion.rst
Labels: pull ready

#23451 DOC: Better doc for `jnp.rot90`
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23466 Make optimization_barrier a public lax API.
  CHANGELOG.md
  docs/jax.lax.rst
  jax/_src/ad_checkpoint.py
  jax/_src/lax/control_flow/__init__.py
  jax/_src/lax/lax.py
  jax/lax/__init__.py
  tests/lax_test.py
Labels: pull ready

#23107 Add md page about XLA&XLA_FLAGS in JAX
  docs/advanced_guide.rst
  docs/xla_flags.md
Labels: pull ready

#23419 Better bitwise right shift doc
  jax/_src/numpy/ufuncs.py
  tests/lax_numpy_operators_test.py
  tests/lax_numpy_test.py
Labels: kokoro:force-run, pull ready

#23454 Fix expression parentheses in shape polymorphism docs for division of symbolic dimensions.
  docs/export/shape_poly.md
  jax/experimental/jax2tf/README.md
Labels: pull ready

#23470 [shape_poly] Improve handling of equality shape constraints
  docs/export/shape_poly.md
  jax/_src/export/shape_poly.py
  jax/_src/export/shape_poly_decision.py
  jax/experimental/jax2tf/jax2tf.py
  tests/shape_poly_test.py
Labels: pull ready

#23369 [NFC] Remove unused argument, fix help string.
  jax/tools/pgo_nsys_converter.py
Labels: pull ready

#23490 tweak readme title to be more about what jax can do for you, dear user
  README.md
Labels: pull ready

#23462 Fix triton capi_objects target to depend on MLIR CAPIIRObjects bazel
  jaxlib/triton/BUILD
Labels: pull ready

#23469 DOC: Better docs for `jax.numpy`: `minimum` and `maximum`
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#23459 Improve docs for jnp.split & related APIs
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#23484 [Pallas] Update Pallas docs with new figures and TPUCompilerParams
  docs/_static/pallas/distributed/reduce_sum_1.svg
  docs/_static/pallas/distributed/reduce_sum_2.svg
  docs/pallas/tpu/details.rst
  docs/pallas/tpu/distributed.ipynb
  docs/pallas/tpu/distributed.md
  docs/pallas/tpu/matmul.ipynb
  docs/pallas/tpu/matmul.md
  docs/pallas/tpu/pipelining.ipynb
  docs/pallas/tpu/pipelining.md
Labels: pull ready

#23502 Fixed validation in `jax.debug.format`
  jax/_src/debugging.py
  tests/debugging_primitives_test.py
Labels: pull ready

#23511 More explicit docstring on the limitations of `spsolve`
  jax/experimental/sparse/linalg.py
Labels: pull ready

#23512 Add array_api intersphinx & document jnp.permute_dims
  docs/conf.py
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23514 array API: use latest array-api-tests commit hash
  .github/workflows/jax-array-api.yml
Labels: pull ready

#23526 Change nightly install commands to include all packages.
  docs/installation.md
Labels: pull ready

#23540 DOC: Improve docs for `jnp.trim_zeros`
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23536 DOC: Improve docs for `jax.numpy`: `float_power` and `nextafter`
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#23478 Add the FFI functions and tutorial to the changelog.
  CHANGELOG.md
  docs/ffi.ipynb
  docs/ffi.md
Labels: pull ready

#23443 DOC: Improved documentation for jax.numpy.kron and jax.numpy.outer
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23549 Update the docs for conv_general_dilated to clarify 'W' 'H'.
  jax/_src/lax/convolution.py
  jax/_src/lax/other.py
Labels: pull ready

#23545 trying on another readme header
  README.md
Labels: pull ready

#23546 Improve docs for jnp.stack, jnp.concat, & related functions
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#23566 Fix typo in `jax.typing` module doc
  jax/typing.py
Labels: pull ready

#22702 Remove custom partitioning pointer from pre-compiled HLO
  jax/_src/cache_key.py
  jax/_src/compilation_cache.py
  jax/_src/config.py
  tests/cache_key_test.py
Labels: pull ready

#23578 Update version numbers after v0.4.32 release.
  .github/workflows/wheel_win_x64.yml
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: pull ready

#23572 DOC: Improve docs for `jax.numpy` arithmetic comparison operations.
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#23534 [Pallas] Fix array indexing error when dimension size is not a multiple of stride
  jax/_src/state/discharge.py
  tests/pallas/indexing_test.py
Labels: pull ready, pallas

#23587 Update complex arctan and arctanh accuracy tests
  jax/_src/test_util.py
  tests/lax_test.py
Labels: pull ready

#23591 Enable more layout tests on GPUs
  tests/layout_test.py
Labels: pull ready

#23586 DOC: Improve doc for` jnp.resize`
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23602 Redisable complex arctan tests on older jaxlibs.
  tests/lax_test.py
Labels: pull ready

#23603 Redisable one more complex arctan test.
  tests/lax_test.py
Labels: pull ready

#23593 DOC: Improve docs for `jax.numpy`: `diff` and `ediff1d`
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23605 shmap in_spec None shouldn't require hashability
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#23618 [export] Improve the forward compatibility documentation
  docs/export/export.md
Labels: pull ready

#23553 DOC: Improved documentation for jax.numpy.fromstring
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23642 tweak error logic to save a comment :)
  jax/_src/interpreters/partial_eval.py
Labels: pull ready

#23623 DOC: Improve docs for `jax.numpy`: `power` and `pow`
  jax/_src/numpy/ufuncs.py
  tests/lax_numpy_test.py
Labels: pull ready

#23643 Fixed func ref in shared-computation
  docs/developer.md
  docs/sharded-computation.ipynb
  docs/sharded-computation.md
Labels: kokoro:force-run, pull ready

#23654 Better documentation for jnp.atleast_*d
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23655 Improve doc for `jnp.logaddexp2`
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#23665 Remove unused string global
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23556 DOC: Improved documentation for numpy.frombuffer
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23670 Merge release/0.4.33 into main and update versions.
  CHANGELOG.md
  jax/version.py
  setup.py
  third_party/xla/tanh.patch
  third_party/xla/workspace.bzl
Labels: pull ready

#23672 Remove XLA tanh fix cherry-pick, to avoid CI breakages when the XLA c…
  third_party/xla/tanh.patch
  third_party/xla/workspace.bzl
Labels: pull ready

#23652 Add `scalar_first` argument to `scipy.spatial.transform.Rotation.as_quat`
  jax/_src/scipy/spatial/transform.py
  tests/scipy_spatial_test.py
Labels: pull ready

#23676 CI: set concurrency for workflows
  .github/workflows/ci-build.yaml
  .github/workflows/jax-array-api.yml
  .github/workflows/metal_plugin_ci.yml
  .github/workflows/wheel_win_x64.yml
  .github/workflows/windows_ci.yml
Labels: pull ready

#23704 Raise a clearer error message when `closure_convert`ed function is called with inputs with the wrong structure
  jax/_src/custom_derivatives.py
  tests/api_test.py
Labels: pull ready

#23669 Add underlying method argument to jax.numpy.digitize
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#23679 DOC: Improved documentation for jax.numpy.sort_complex
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23682 [Pallas] Add design note for async ops
  docs/pallas/async_note.md
  docs/pallas/index.rst
Labels: pull ready

#23653 Add basic PyTorch integration for Mosaic GPU
  jax/experimental/mosaic/gpu/__init__.py
  jaxlib/mosaic/gpu/custom_call.cc
  jaxlib/tools/BUILD.bazel
  jaxlib/tools/gpu_version_script.lds
  tests/mosaic/gpu_test.py
Labels: pull ready

#23563 Deprecate passing `NdArrays with ndim != 1` and `non-arraylike` inputs to `jnp.trim_zeros`
  CHANGELOG.md
  jax/_src/deprecations.py
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#23698 Add a note to the developer docs making it clear that clang is the only
  docs/developer.md
Labels: pull ready

#23708 jnp.sort_complex: fix output for N-dimensional inputs
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#23723 Replace plat-name with plat_name.
  jaxlib/tools/build_gpu_kernels_wheel.py
  jaxlib/tools/build_gpu_plugin_wheel.py
  jaxlib/tools/build_wheel.py
Labels: pull ready

#23667 Unconditionally lower jnp.dot to lax.dot_general.
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23247 [NVIDIA] Add the sliding window to `jax.nn.dot_product_attention`
  jax/_src/nn/functions.py
  tests/nn_test.py
Labels: pull ready

#23737 Improve documentation for jnp.digitize
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.pyi
Labels: documentation, pull ready

#23736 Add Python 3.13 wheels to changelog.
  CHANGELOG.md
Labels: pull ready

#22310 [Pallas TPU] Add lowering for `lax.erf_inv` 64 bit
  jax/_src/pallas/mosaic/lowering.py
  jax/_src/pallas/triton/lowering.py
  jax/_src/pallas/utils.py
  tests/pallas/ops_test.py
Labels: pull ready, pallas

#23761 DOC: Improve doc of `jnp.vander`
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23769 Add a note to the changelog about the new CPU thunks backend, enabled…
  CHANGELOG.md
Labels: pull ready

#23674 [Pallas] Add block-sparse kernel tutorial
  docs/_static/pallas/sparse/block_coo.svg
  docs/_static/pallas/sparse/prefetch_map.svg
  docs/_static/pallas/sparse/sparse_matmul.svg
  docs/conf.py
  docs/pallas/tpu/index.rst
  docs/pallas/tpu/sparse.ipynb
  docs/pallas/tpu/sparse.md
Labels: pull ready

#23779 custom_vjp: don't drop tangents just because they have a different dtype than the primal
  jax/_src/custom_derivatives.py
Labels: pull ready

#23790 Better doc for `jax.numpy.i0`
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#23802 Format MLIR dump names with leading zeros.
  jax/_src/interpreters/mlir.py
Labels: pull ready

#23788 DOC: Improve docs for `jax.numpy`: `deg2rad`, `rad2deg`, `degrees`, `radians`
  jax/_src/numpy/ufuncs.py
  tests/lax_numpy_test.py
Labels: documentation, pull ready

#23734 DOC: Improve docs for `jax.numpy`: `remainder`, `mod` and `fmod`
  jax/_src/numpy/ufuncs.py
  tests/lax_numpy_test.py
Labels: pull ready

#22302 Add Kubernetes Jobset support to `jax.distributed.initialize`
  jax/BUILD
  jax/_src/clusters/__init__.py
  jax/_src/clusters/k8s_cluster.py
  pyproject.toml
  setup.py
Labels: pull ready

#23812 add jax.experimental.primal_tangent_dtype helper
  jax/_src/core.py
  jax/_src/dtypes.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/lax.py
  jax/_src/lax/slicing.py
  jax/_src/sharding_impls.py
  jax/experimental/__init__.py
  tests/dtypes_test.py
Labels: pull ready

#23165 Create JAX Advanced Tutorials (section, move/create docs)
  docs/_tutorials/index.rst
  docs/advanced-autodiff.md
  docs/conf.py
  docs/extensions.rst
  docs/external-callbacks.md
  docs/ffi.ipynb
  docs/ffi.md
  docs/glossary.rst
  docs/gradient-checkpointing.md
  docs/index.rst
  docs/jax-primitives.md
  docs/jaxpr.md
  docs/jaxpr.rst
  docs/jit-compilation.md
  docs/notebooks/How_JAX_primitives_work.ipynb
  docs/notebooks/How_JAX_primitives_work.md
  docs/notebooks/external_callbacks.ipynb
  docs/notebooks/external_callbacks.md
  docs/tutorials.rst
  docs/user_guides.rst
Labels: pull ready

#23821 Test that jax.numpy docstrings include examples
  jax/_src/numpy/polynomial.py
  jax/_src/numpy/ufuncs.py
  jax/_src/numpy/vectorize.py
  tests/lax_numpy_test.py
Labels: documentation, pull ready

#23816 DOC: Improve docs for jax.numpy: conjugate, conj, imag and real
  jax/_src/numpy/ufuncs.py
  tests/lax_numpy_test.py
Labels: documentation, pull ready

#23834 DOC: Improve docs for `jax.numpy`: `square`, `sqrt` and `modf`
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#23837 Improve docs for `jnp.logspace` and `jnp.geomspace`
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23852 [ROCM] add missing typename keyword to work with gcc
  jaxlib/gpu/solver_kernels_ffi.cc
Labels: pull ready

#23801 Better docs for jnp.meshgrid
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#23739 ufuncs: improve jnp.add.at & jnp.multiply.at
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#23807 [NVIDIA] Fix unsupported dbias in bwd batcher of cudnn sdpa API
  jax/_src/cudnn/fused_attention_stablehlo.py
  tests/fused_attention_stablehlo_test.py
Labels: pull ready

#23741 declare buffer donation and compilation cache support for platform "neuron"
  jax/_src/compilation_cache.py
  jax/_src/interpreters/mlir.py
Labels: pull ready

#23862 trigger array API tests for all PRs.
  .github/workflows/jax-array-api.yml
Labels: pull ready

#23861 Remove warning filters from pyproject.toml, add local warning
  pyproject.toml
  tests/array_interoperability_test.py
  tests/compilation_cache_test.py
  tests/scipy_stats_test.py
Labels: pull ready

#23744 Make jnp.negative a ufunc & add unary ufunc tests
  jax/_src/numpy/array_methods.py
  jax/_src/numpy/ufuncs.py
  tests/lax_numpy_ufuncs_test.py
Labels: pull ready

#23860 Add more informative error when static argument is passed to non-static JIT parameter
  jax/_src/pjit.py
  tests/api_test.py
  tests/lax_test.py
Labels: pull ready

#23873 Fix an incorrect output for jnp.cumsum.
  CHANGELOG.md
  jax/_src/numpy/reductions.py
  tests/lax_numpy_reducers_test.py
Labels: pull ready

#23806 [ffi] Support handler bundles in GPU plugin extension
  jaxlib/cuda_plugin_extension.cc
  jaxlib/rocm_plugin_extension.cc
Labels: pull ready

#23823 Simplify extended dtype convert logic
  jax/_src/core.py
  jax/_src/dtypes.py
  jax/_src/lax/lax.py
  jax/_src/pallas/core.py
  jax/_src/prng.py
  jax/experimental/jax2tf/jax2tf.py
  tests/dtypes_test.py
  tests/dynamic_api_test.py
Labels: pull ready

#23409 Add FFI example project and test on CI
  .github/workflows/ci-build.yaml
  examples/ffi/CMakeLists.txt
  examples/ffi/README.md
  examples/ffi/pyproject.toml
  examples/ffi/src/jax_ffi_example/__init__.py
  examples/ffi/src/jax_ffi_example/rms_norm.cc
  examples/ffi/src/jax_ffi_example/rms_norm.py
  examples/ffi/tests/rms_norm_test.py
  pyproject.toml
Labels: pull ready

#23910 Update pillow version in JAX build test-requirements.txt
  build/test-requirements.txt
Labels: pull ready

#23914 DOC: Fix Typos
  docs/key-concepts.md
  docs/quickstart.md
Labels: pull ready

#23874 DOC: Improve docs for `jax.numpy`: `arcsin`, `arccos` and `arctan`
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#23917 Fix dtype bug in jax.scipy.fft.idct
  jax/_src/scipy/fft.py
  tests/scipy_fft_test.py
Labels: pull ready

#23916 Improve documentation for jnp.interp
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#23924 Fix make_remote_async_copy -> make_async_remote_copy in async doc
  docs/pallas/async_note.md
Labels: pull ready

#23899 DOC: Better doc for `jnp.trace`
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#23928 [Mosaic GPU] Fix mbarrier inline ptx for newer CTK
  jax/experimental/mosaic/gpu/utils.py
Labels: pull ready

#23927 Improve docs for jnp.pad
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
Labels: documentation, pull ready

#23921 Raise `ValueError` when `axis1==axis2` for `jnp.trace`
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#23940 Improve documentation for jax.jacobian
  docs/jax.rst
  jax/_src/api.py
Labels: documentation, pull ready

#23949 DOC: Improve docs for `jax.numpy`: `sinh`, `cosh` and `tanh`
  jax/_src/numpy/ufuncs.py
Labels: documentation, pull ready

#23853 Enable the activation offloading test
  tests/memories_test.py
Labels: pull ready

#23965 Enable weight offloading tests that are supported on GPUs now
  tests/memories_test.py
Labels: pull ready

#23980 actions: remove use of ratchet tool
  .github/workflows/ci-build.yaml
  .github/workflows/cloud-tpu-ci-nightly.yml
  .github/workflows/jax-array-api.yml
  .github/workflows/upstream-nightly.yml
  .github/workflows/wheel_win_x64.yml
  .github/workflows/windows_ci.yml
Labels: pull ready

#23961 Remove pylint sections from pyproject.toml (use ruff instead)
  pyproject.toml
Labels: pull ready

#23804 Don't pass --nocheck_visibility to Bazel.
  .bazelrc
  jax_plugins/BUILD.bazel
Labels: pull ready

#23870 Fix stdout buffer error in JAX UT api_test.py
  tests/api_test.py
Labels: pull ready

#23977 DOC: Improve docs for `jax.numpy`: `arcsinh`, `arccosh` and `arctanh`
  jax/_src/numpy/ufuncs.py
Labels: documentation, pull ready

#23981 actions/checkout: pin specific hash
  .github/workflows/metal_plugin_ci.yml
Labels: pull ready

#23957 Better documentation for jnp.choose
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.pyi
Labels: documentation, pull ready

#23982 Add support for FFI calls with side effects via ffi_call
  jax/_src/extend/ffi.py
  tests/extend_test.py
Labels: pull ready

#24024 DOC: Better doc for jnp.cbrt
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#23505 Fix and reenable cudnn_fusion_test.
  tests/BUILD
  tests/cudnn_fusion_test.py
Labels: pull ready

#24025 Better docs for jnp.gradient
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
  tests/lax_numpy_test.py
Labels: pull ready

#23995 Update docs for jnp.trapezoid
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#23923 Add custom_jvp to jax.numpy.ldexp.
  CHANGELOG.md
  jax/_src/numpy/ufuncs.py
  tests/lax_numpy_test.py
Labels: pull ready
