Repository jax-ml/jax, pull requests merged in 2024-01, with the labels that each got.

#19166 stats.binom.pmf: return zero for k > n
  jax/_src/scipy/stats/binom.py
  tests/scipy_stats_test.py
Labels: pull ready

#19135 сhanged concatenation of strings to f-strings to improve readability
  jax/_src/numpy/fft.py
Labels: pull ready

#19182 jnp.ndarray.item(): add args support
  CHANGELOG.md
  jax/_src/numpy/array_methods.py
  tests/lax_numpy_test.py
Labels: pull ready

#19186 [array API] support copy argument to jnp.asarray
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#19204 DOC: remove unnecessary doc build requirement
  docs/requirements.txt
Labels: pull ready

#19201 [array api] add stable & descending params to jnp.sort & jnp.argsort
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
  jax/experimental/array_api/_sorting_functions.py
  jax/experimental/array_api/skips.txt
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#19227 [shape_poly] Fixes for the lexicographic ordering of monomials.
  jax/experimental/export/shape_poly.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  tests/export_test.py
  tests/shape_poly_test.py
Labels: pull ready

#19228 [shape_poly] Cache the hash values for symbolic expressions
  jax/experimental/export/shape_poly.py
  tests/shape_poly_test.py
Labels: pull ready

#19221 [array api] fix linalg.solve and enable test
  jax/experimental/array_api/_linear_algebra_functions.py
  jax/experimental/array_api/skips.txt
Labels: pull ready

#19224 jnp.linalg.solve: fully implement batched cases
  jax/_src/numpy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#19231 [shape_poly] Simplify and speed-up the __eq__ functions for symbolic expressions
  CHANGELOG.md
  jax/experimental/export/shape_poly.py
Labels: pull ready

#19235 [shape_poly] Improve error messages for shape polymorphism
  jax/experimental/export/shape_poly.py
  tests/shape_poly_test.py
Labels: pull ready

#19230 Improve some deprecation error messages related to shape polymorphism
  jax/core.py
Labels: pull ready

#19236 [shape_poly] Improved the tests for inequality comparisons.
  CHANGELOG.md
  tests/shape_poly_test.py
Labels: pull ready

#19238 [shape_poly] Minor improvements for handling of dilation in convolution
  jax/_src/lax/convolution.py
  jax/_src/lax/lax.py
Labels: pull ready

#19243 Fix unused import error
  tests/export_back_compat_test.py
Labels: pull ready

#19245 Remove reference to np.ComplexWarning
  jax/_src/lax/lax.py
Labels: kokoro:force-run, pull ready

#19220 jnp.argsort/sort: explicitly deprecate the kind argument
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#19244 [array api] add jax.numpy.permute_dims function
  docs/jax.numpy.rst
  jax/_src/numpy/lax_numpy.py
  jax/experimental/array_api/_manipulation_functions.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#19247 List several NumPy 2.0 ufuncs as unimplemented
  tests/lax_numpy_test.py
Labels: pull ready

#19248 NumPy 2.0: skip complex atanh test
  tests/lax_numpy_test.py
Labels: pull ready

#19253 jnp.bitwise_count: promote input to numeric
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#19252 jnp.linalg.vecdot: fix broadcasting & conjugation semantics
  jax/_src/numpy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#18953 [shape_poly] Replace non_negative_dim with max_dim and min_dim.
  CHANGELOG.md
  jax/_src/core.py
  jax/core.py
  jax/experimental/export/shape_poly.py
  tests/export_test.py
  tests/shape_poly_test.py
Labels: pull ready

#19258 [shape_poly] Improve the lexicographic ordering of symbolic expressions
  jax/experimental/export/shape_poly.py
  tests/shape_poly_test.py
Labels: pull ready

#19270 Adjust permute_dims signature to match NumPy
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#19272 pallas: improve indexing trace time
  jax/_src/state/indexing.py
Labels: pull ready

#19092 JAX docs tutorial: Gradient checkpointing
  docs/requirements.txt
  docs/tutorials/gradient-checkpointing.md
  docs/tutorials/index.rst
Labels: pull ready

#19277 CI: update jupytext version
  .pre-commit-config.yaml
  docs/autodidax.md
  docs/autodidax.py
  docs/developer.md
  docs/jax-101/01-jax-basics.md
  docs/jax-101/02-jitting.md
  docs/jax-101/03-vectorization.md
  docs/jax-101/04-advanced-autodiff.md
  docs/jax-101/05-random-numbers.md
  docs/jax-101/05.1-pytrees.md
  docs/jax-101/06-parallelism.md
  docs/jax-101/07-state.md
  docs/jep/9407-type-promotion.md
  docs/notebooks/Common_Gotchas_in_JAX.md
  docs/notebooks/Custom_derivative_rules_for_Python_code.md
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.md
  docs/notebooks/How_JAX_primitives_work.md
  docs/notebooks/Neural_Network_and_Data_Loading.md
  docs/notebooks/Writing_custom_interpreters_in_Jax.md
  docs/notebooks/autodiff_cookbook.md
  docs/notebooks/autodiff_remat.md
  docs/notebooks/convolutions.md
  docs/notebooks/external_callbacks.md
  docs/notebooks/neural_network_with_tfds_data.md
  docs/notebooks/quickstart.md
  docs/notebooks/thinking_in_jax.md
  docs/notebooks/vmapped_log_probs.md
  docs/notebooks/xmap_tutorial.md
  docs/pallas/quickstart.md
  docs/tutorials/advanced-autodiff.md
  docs/tutorials/advanced-debugging.md
  docs/tutorials/automatic-differentiation.md
  docs/tutorials/automatic-vectorization.md
  docs/tutorials/debugging.md
  docs/tutorials/external-callbacks.md
  docs/tutorials/gradient-checkpointing.md
  docs/tutorials/jit-compilation.md
  docs/tutorials/quickstart.md
  docs/tutorials/random-numbers.md
  docs/tutorials/thinking-in-jax.md
  docs/tutorials/working-with-pytrees.md
Labels: pull ready

#19147 JAX docs tutorial: JAX internals 301 - The jaxpr language
  docs/tutorials/index.rst
  docs/tutorials/jaxpr.md
Labels: pull ready

#19279 lint: fix jupytext version
  docs/tutorials/jaxpr.md
Labels: pull ready

#19275 docs/pallas: fix mismatched pytree specs
  docs/pallas/quickstart.ipynb
  docs/pallas/quickstart.md
Labels: pull ready

#19282 [shape_poly] Introduce is_symbolic_dim and deprecate is_poly_dim.
  CHANGELOG.md
  jax/experimental/export/__init__.py
  jax/experimental/export/shape_poly.py
  jax/experimental/jax2tf/__init__.py
  jax/experimental/jax2tf/examples/saved_model_lib.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#19289 CI: update array API tests pin
  .github/workflows/jax-array-api.yml
Labels: pull ready

#19276 CI: bump mypy to version 1.8.0
  .pre-commit-config.yaml
  jax/_src/state/utils.py
Labels: pull ready

#19274 Add jnp.vecdot
  docs/jax.numpy.rst
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/linalg.py
  jax/_src/test_util.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
  tests/linalg_test.py
Labels: pull ready

#19278 array api: add jnp.bitwise_* aliases
  docs/jax.numpy.rst
  jax/_src/numpy/ufuncs.py
  jax/experimental/array_api/_elementwise_functions.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_operators_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#19293 [array API] implement jnp.pow; alias for jnp.power
  docs/jax.numpy.rst
  jax/_src/numpy/ufuncs.py
  jax/experimental/array_api/_elementwise_functions.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_operators_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#19303 improve block matrix alignment in pallas docs
  docs/pallas/quickstart.ipynb
  docs/pallas/quickstart.md
Labels: pull ready

#19299 array api: simplify some wrappers
  jax/experimental/array_api/_array_methods.py
  jax/experimental/array_api/_elementwise_functions.py
  jax/experimental/array_api/_manipulation_functions.py
Labels: pull ready

#19321 [array API] add jnp.linalg.diagonal
  docs/jax.numpy.rst
  jax/_src/numpy/linalg.py
  jax/experimental/array_api/_linear_algebra_functions.py
  jax/numpy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#19080 Fix accuracy error caused by too many devices in lax_control_flow_test.py
  tests/lax_control_flow_test.py
Labels: pull ready

#19284 [shape_poly] Deprecate shape_poly.PolySpec.
  CHANGELOG.md
  jax/experimental/export/shape_poly.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
Labels: pull ready

#19283 [shape_poly] Improve and rename export.args_specs.
  CHANGELOG.md
  jax/_src/internal_test_util/export_back_compat_test_util.py
  jax/experimental/export/__init__.py
  jax/experimental/export/_export.py
  jax/experimental/export/shape_poly.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  tests/export_test.py
  tests/shape_poly_test.py
Labels: pull ready

#19345 DOC: add a note about installing older GPU wheels
  docs/installation.md
  docs/tutorials/installation.md
Labels: pull ready

#19323 [array api] add jax.numpy.concat
  docs/jax.numpy.rst
  jax/_src/numpy/lax_numpy.py
  jax/experimental/array_api/_manipulation_functions.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#19348 Test: make scipy version parsing compatible with pre-releases
  jax/_src/test_util.py
  tests/linalg_test.py
  tests/scipy_spatial_test.py
  tests/scipy_stats_test.py
Labels: pull ready

#19007 Enabling xla_tpu_use_enhanced_launch_barrier for all the supported clout tpus
  jax/BUILD
  jax/_src/cloud_tpu_init.py
  jax/_src/hardware_utils.py
  jax/_src/xla_bridge.py
Labels: pull ready

#19363 [shape_poly] Improve core.max_dim and core.min_dim
  jax/_src/core.py
  jax/experimental/export/_shape_poly.py
  tests/shape_poly_test.py
Labels: pull ready

#19375 [shard-map] add approx_top_k replication rule
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#19377 Included a few more Triton files into the jaxlib wheel
  jaxlib/BUILD
  jaxlib/setup.py
  jaxlib/tools/build_wheel.py
Labels: pull ready

#19380 [typing] add where paramter in any/all type declaration
  jax/_src/basearray.pyi
Labels: pull ready

#19384 JEP 9263: update deprecation status of KeyArray and PRNGKeyArray
  docs/jep/9263-typed-keys.md
Labels: pull ready

#19351 added cdf and ppf to jax.scipy.stats.uniform
  .gitignore
  docs/jax.scipy.rst
  jax/_src/scipy/stats/uniform.py
  jax/scipy/stats/uniform.py
  tests/scipy_stats_test.py
Labels: pull ready

#19320 jnp.unique: make return_inverse shape match NumPy 2.0
  CHANGELOG.md
  jax/_src/numpy/setops.py
  jax/experimental/sparse/bcoo.py
  tests/lax_numpy_test.py
Labels: pull ready

#19387 TST: make searchsorted test compatible with NumPy 2.0
  tests/lax_numpy_test.py
Labels: pull ready

#19388 random_test: test random.bits directly
  tests/random_test.py
Labels: pull ready

#19390 jnp.sign: use x/abs(x) for complex arguments
  CHANGELOG.md
  jax/_src/numpy/ufuncs.py
  tests/lax_numpy_operators_test.py
Labels: pull ready

#19347 [array api] return NamedTuple from np.linalg APIs
  jax/_src/numpy/linalg.py
  jax/experimental/array_api/_linear_algebra_functions.py
Labels: pull ready

#19400 Add jnp.isdtype function, following np.isdtype in NumPy 2.0
  docs/jax.numpy.rst
  jax/_src/dtypes.py
  jax/experimental/array_api/_data_type_functions.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/dtypes_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#19379 jax.random: deprecate passing of batched keys to APIs
  CHANGELOG.md
  jax/_src/random.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  tests/key_reuse_test.py
  tests/random_lax_test.py
  tests/shape_poly_test.py
Labels: pull ready

#19403 [array API] add jnp.bool
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#19280 [shard-map] first draft of shard_map tutorial
  docs/advanced_guide.rst
  docs/conf.py
  docs/notebooks/shard_map.ipynb
  docs/notebooks/shard_map.md
Labels: pull ready

#19416 CI: avoid parallelizing sphinx build to fix pydata-sphinx-theme warning
  .github/workflows/ci-build.yaml
Labels: pull ready

#19413 Deprecate `jax.lax.tie_in`
  CHANGELOG.md
  jax/experimental/jax2tf/tests/control_flow_ops_test.py
  jax/lax/__init__.py
  tests/api_test.py
  tests/lax_numpy_test.py
  tests/lax_test.py
Labels: pull ready

#19432 [typing] fix incorrect annotation
  jaxlib/gpu_sparse.py
Labels: pull ready

#19441 Guard shard_alike usage on xla_extension_version
  jax/_src/lax/lax.py
  jax/_src/shard_alike.py
  tests/shard_alike_test.py
Labels: pull ready

#18127 Made make_array_from_single_device_arrays docs easier to understand
  jax/_src/array.py
Labels: pull ready

#19437 Add shard_map doc title
  docs/notebooks/shard_map.ipynb
  docs/notebooks/shard_map.md
Labels: pull ready

#19462 DOC Add a noop implementation of the legacy directive to fix the build
  docs/sphinxext/jax_extensions.py
Labels: pull ready

#19445 lax.full: add sharding argument
  jax/_src/lax/lax.py
  tests/lax_test.py
Labels: kokoro:force-run, pull ready

#19463 TST: add unimplemented parameters in numpy signatures test
  tests/lax_numpy_test.py
Labels: kokoro:force-run, pull ready

#19464 Bump actions/cache from 3.3.3 to 4.0.0
  .github/workflows/ci-build.yaml
Labels: pull ready

#19455 ROCm docker rocm6.0 updates
  build/rocm/Dockerfile.ms
  build/rocm/build_rocm.sh
  build/rocm/ci_build.sh
  build/rocm/custom_install.sh
  build/rocm/setup.rocm.sh
  jaxlib/gpu/vendor.h
Labels: pull ready

#19438 Add __init__ for splash_attention
  jax/experimental/pallas/ops/tpu/splash_attention/__init__.py
Labels: pull ready

#19472 [shard-map] fix typos in docs
  docs/notebooks/shard_map.ipynb
  docs/notebooks/shard_map.md
Labels: pull ready

#19466 lax.full_like: add sharding argument
  jax/_src/lax/lax.py
  tests/lax_test.py
Labels: pull ready

#19474 [shard-map] fix disable_jit-of-shmap
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#19285 [shape_poly] Add support for symbolic constraints on dimension variables
  jax/experimental/export/__init__.py
  jax/experimental/export/_export.py
  jax/experimental/export/_serialization.py
  jax/experimental/export/_shape_poly.py
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  tests/export_test.py
  tests/shape_poly_test.py
Labels: pull ready

#19473 DOC: run shard_map docs as part of the doc build
  docs/conf.py
  docs/notebooks/shard_map.ipynb
  docs/notebooks/shard_map.md
Labels: documentation, pull ready

#19481 [shape_poly] Forgot to update CHANGELOG for #19235.
  CHANGELOG.md
Labels: pull ready

#19484 Test: move lax.full sharding tests to multi_device_test
  tests/lax_test.py
  tests/multi_device_test.py
Labels: pull ready

#19489 Update version numbers for 0.4.24 release
  setup.py
Labels: pull ready

#19145 JAX docs tutorial: JAX internals 301 - JAX primitives
  docs/tutorials/index.rst
  docs/tutorials/jax-internals.md
  docs/tutorials/jax-primitives.md
Labels: pull ready

#19492 [shape_poly] Add more tests for reasoning about inequalities.
  tests/shape_poly_test.py
Labels: pull ready

#19495 Update JAX docs copyright year (2024)
  docs/conf.py
Labels: pull ready

#19503 Test: add weights to unsupported arguments
  tests/lax_numpy_test.py
Labels: pull ready

#19497 [ROCM]: Generating pytest html logs from unit-tests.
  build/rocm/Dockerfile.ms
  build/rocm/run_multi_gpu.sh
  build/rocm/run_single_gpu.py
Labels: pull ready

#19470 jax.numpy: support device argument for full, empty, zeros, ones
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#19509 Remove unnecessary Array.register
  jax/_src/prng.py
Labels: pull ready

#19507 Rename _wraps to implements
  jax/_src/numpy/fft.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/linalg.py
  jax/_src/numpy/polynomial.py
  jax/_src/numpy/reductions.py
  jax/_src/numpy/setops.py
  jax/_src/numpy/ufunc_api.py
  jax/_src/numpy/ufuncs.py
  jax/_src/numpy/util.py
  jax/_src/scipy/cluster/vq.py
  jax/_src/scipy/fft.py
  jax/_src/scipy/integrate.py
  jax/_src/scipy/linalg.py
  jax/_src/scipy/ndimage.py
  jax/_src/scipy/signal.py
  jax/_src/scipy/spatial/transform.py
  jax/_src/scipy/special.py
  jax/_src/scipy/stats/_core.py
  jax/_src/scipy/stats/bernoulli.py
  jax/_src/scipy/stats/beta.py
  jax/_src/scipy/stats/betabinom.py
  jax/_src/scipy/stats/binom.py
  jax/_src/scipy/stats/cauchy.py
  jax/_src/scipy/stats/chi2.py
  jax/_src/scipy/stats/dirichlet.py
  jax/_src/scipy/stats/expon.py
  jax/_src/scipy/stats/gamma.py
  jax/_src/scipy/stats/gennorm.py
  jax/_src/scipy/stats/geom.py
  jax/_src/scipy/stats/kde.py
  jax/_src/scipy/stats/laplace.py
  jax/_src/scipy/stats/logistic.py
  jax/_src/scipy/stats/multinomial.py
  jax/_src/scipy/stats/multivariate_normal.py
  jax/_src/scipy/stats/nbinom.py
  jax/_src/scipy/stats/norm.py
  jax/_src/scipy/stats/pareto.py
  jax/_src/scipy/stats/poisson.py
  jax/_src/scipy/stats/t.py
  jax/_src/scipy/stats/truncnorm.py
  jax/_src/scipy/stats/uniform.py
  jax/_src/scipy/stats/vonmises.py
  jax/_src/scipy/stats/wrapcauchy.py
  jax/_src/third_party/numpy/linalg.py
  jax/_src/third_party/scipy/interpolate.py
  jax/_src/third_party/scipy/linalg.py
  tests/lax_numpy_test.py
Labels: pull ready

#19520 [key reuse] don't consume key in fold_in
  jax/experimental/key_reuse/_forwarding.py
  jax/experimental/key_reuse/_simple.py
  tests/key_reuse_test.py
Labels: pull ready

#19485 [ROCM]: enable linalg_test.py::test_tridiagonal_solve.
  tests/linalg_test.py
Labels: pull ready

#19518 nn.softmax: use double-where when where is specified
  jax/_src/nn/functions.py
  tests/nn_test.py
Labels: pull ready

#19504 jnp.full_like & co: support device parameter
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#19511 lax.asarray: avoid explicit device_put
  jax/_src/lax/lax.py
  tests/lax_test.py
Labels: pull ready

#19517 Fix `jax.lax.fori_loop(..., unroll=True)` with non-positive length
  jax/_src/lax/control_flow/loops.py
  tests/lax_control_flow_test.py
Labels: pull ready

#19536 [key reuse] fix key reuse type for cond with sources
  jax/experimental/key_reuse/_forwarding.py
  jax/experimental/key_reuse/_simple.py
  tests/key_reuse_test.py
Labels: pull ready

#19540 make hypothesis test dependence optional
  tests/pallas/splash_attention_kernel_test.py
Labels: kokoro:force-run, pull ready

#19532 integrate attrs in jax.jit
  jax/BUILD
  jax/_src/ad_checkpoint.py
  jax/_src/api.py
  jax/_src/checkify.py
  jax/_src/custom_batching.py
  jax/_src/custom_derivatives.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/batching.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/control_flow/common.py
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/lax.py
  jax/_src/maps.py
  jax/_src/pallas/core.py
  jax/_src/pallas/mosaic/lowering.py
  jax/_src/pallas/mosaic/primitives.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pallas/triton/lowering.py
  jax/_src/pjit.py
  jax/_src/state/discharge.py
  jax/_src/state/utils.py
  jax/experimental/attrs.py
  jax/experimental/custom_partitioning.py
  jax/experimental/jet.py
  jax/experimental/key_reuse/_forwarding.py
  jax/experimental/key_reuse/_simple.py
  jax/experimental/shard_map.py
  jax/experimental/sparse/transform.py
  jax/interpreters/partial_eval.py
  tests/BUILD
  tests/attrs_test.py
  tests/core_test.py
  tests/pallas/pallas_call_tpu_test.py
  tests/state_test.py
Labels: pull ready

#19551 Slice.from_slice now works for slices with a negative start index
  jax/_src/state/indexing.py
Labels: pull ready

#19528 Replaced most usages of abc.ABC with util.StrictABC
  jax/BUILD
  jax/_src/compilation_cache_interface.py
  jax/_src/core.py
  jax/_src/dtypes.py
  jax/_src/numpy/index_tricks.py
  jax/_src/pretty_printer.py
  jax/_src/util.py
  jax/experimental/array_serialization/serialization.py
  jax/experimental/sparse/_base.py
  jax/experimental/topologies.py
Labels: pull ready

#19554 testOgrid: make test compatible with NumPy 2.0
  tests/lax_numpy_test.py
Labels: pull ready

#19515 [shape_poly] Add a decision procedure for inequalities.
  jax/experimental/export/BUILD
  jax/experimental/export/__init__.py
  jax/experimental/export/_shape_poly.py
  jax/experimental/export/_shape_poly_decision.py
  tests/shape_poly_test.py
Labels: pull ready

#19574 Clarify a comment slightly
  docs/jax-101/01-jax-basics.ipynb
  docs/jax-101/01-jax-basics.md
Labels: pull ready

#19583 [key reuse] print signature on failure
  jax/experimental/key_reuse/_forwarding.py
  jax/experimental/key_reuse/_simple.py
Labels: pull ready

#19587 [key reuse] better info for scan & while failures
  jax/experimental/key_reuse/_common.py
  jax/experimental/key_reuse/_forwarding.py
  jax/experimental/key_reuse/_simple.py
Labels: pull ready

#19566 add getstate/setstate in pjit transpose, for bwd pass effects
  jax/_src/pjit.py
  tests/attrs_test.py
Labels: pull ready

#19591 [key reuse] simplify slice_p reuse rule
  jax/experimental/key_reuse/_forwarding.py
  jax/experimental/key_reuse/_simple.py
Labels: pull ready

#19593 Add type annotation to pl.load
  jax/_src/pallas/primitives.py
Labels: pull ready

#19606 jnp.linalg.cholesky: add upper argument
  .github/workflows/jax-array-api.yml
  jax/_src/numpy/linalg.py
  jax/experimental/array_api/_linear_algebra_functions.py
  tests/linalg_test.py
Labels: pull ready
