Repository jax-ml/jax, pull requests merged in 2024-03, with the labels that each got.

#19795 [key reuse] Eager checks
  jax/_src/config.py
  jax/_src/pjit.py
  jax/_src/prng.py
  jax/experimental/key_reuse/_common.py
  jax/experimental/key_reuse/_core.py
  tests/key_reuse_test.py
  tests/pmap_test.py
  tests/random_lax_test.py
  tests/random_test.py
  tests/scipy_stats_test.py
  tests/state_test.py
  tests/x64_context_test.py
Labels: pull ready

#20026 [mutable-arrays] allow state effects in jit by building in run_state
  jax/BUILD
  jax/_src/core.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/interpreters/pxla.py
  jax/_src/pjit.py
  jax/_src/state/discharge.py
  jax/experimental/export/_export.py
  tests/state_test.py
Labels: pull ready

#20043 add upgrade (aka to-be-removed) flag for new select rule
  jax/_src/config.py
  jax/_src/lax/lax.py
  tests/lax_numpy_test.py
Labels: pull ready

#20044 [mutable-arrays] move MutableArray, add eager, improve tests, fix bug
  jax/_src/core.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/interpreters/pxla.py
  jax/_src/interpreters/xla.py
  jax/_src/state/primitives.py
  tests/state_test.py
Labels: pull ready

#19808 Added check for CUDA device compute capability
  jax/_src/xla_bridge.py
  jaxlib/cuda/versions.cc
  jaxlib/cuda/versions_helpers.cc
  jaxlib/cuda/versions_helpers.h
Labels: pull ready

#20067 jnp.array: fix failure under numpy 2.0 copy semantics
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#20069 [key reuse] don't consume on equality check
  jax/experimental/key_reuse/_core.py
  tests/key_reuse_test.py
Labels: pull ready

#20071 [key reuse] improve module docs
  jax/experimental/key_reuse/__init__.py
Labels: pull ready

#20070 [key reuse] improve some key reuse errors.
  jax/experimental/key_reuse/__init__.py
  jax/experimental/key_reuse/_common.py
  jax/experimental/key_reuse/_core.py
  tests/key_reuse_test.py
Labels: pull ready

#20077 Add copy argument to Array.__array__
  jax/_src/array.py
  jax/_src/basearray.pyi
  tests/lax_numpy_test.py
Labels: kokoro:force-run, pull ready

#20078 ignore NamedAxisEffect for remat and dce purposes
  jax/_src/ad_checkpoint.py
  jax/_src/interpreters/partial_eval.py
  tests/shard_map_test.py
Labels: pull ready

#20081 Use shorter error message for jax.tools.colab_tpu.setup_tpu()
  jax/tools/colab_tpu.py
Labels: pull ready

#20083 [attrs] fix tracer lifetime bug, fixes #20082
  jax/experimental/attrs.py
  tests/attrs_test.py
Labels: pull ready

#20087 DOC: fix two minor doc issues
  docs/jax.scipy.rst
  jax/_src/scipy/fft.py
Labels: pull ready

#20101 Include <cstdint> in files where it is used
  jaxlib/gpu/lu_pivot_kernels.cu.cc
  jaxlib/gpu/lu_pivot_kernels.h
  jaxlib/gpu/prng_kernels.cu.cc
  jaxlib/gpu/prng_kernels.h
Labels: pull ready

#20103 remove dead code in `random`
  jax/_src/random.py
Labels: kokoro:force-run, pull ready

#20105 Remove some dead code
  jax/_src/core.py
Labels: pull ready

#20042 Adding script to convert NVIDIA nsys profiles to pbtxt
  jax/tools/pgo_nsys_converter.py
Labels: pull ready

#20126 lint: fix unused import
  jax/tools/pgo_nsys_converter.py
Labels: pull ready

#20108 minor modification for silu and swish func description
  jax/_src/nn/functions.py
Labels: pull ready

#20127 Guard script against execution on import
  jax/tools/pgo_nsys_converter.py
Labels: pull ready

#20136 Fix typo for `random.py`
  jax/random.py
Labels: pull ready

#20139 [key reuse] add jax.random.clone
  docs/jax.experimental.key_reuse.rst
  docs/jax.random.rst
  jax/_src/lax/control_flow/loops.py
  jax/_src/prng.py
  jax/_src/random.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/key_reuse/__init__.py
  jax/experimental/key_reuse/_core.py
  jax/random.py
  tests/key_reuse_test.py
  tests/random_test.py
  tests/state_test.py
Labels: pull ready

#20141 [key reuse] define KeyReuseError in jax.errors
  docs/errors.rst
  docs/jax.experimental.key_reuse.rst
  jax/_src/errors.py
  jax/errors.py
  jax/experimental/key_reuse/__init__.py
  jax/experimental/key_reuse/_core.py
  tests/core_test.py
  tests/key_reuse_test.py
Labels: pull ready

#20142 [key reuse] improve KeyReuseSignature semantics
  jax/experimental/key_reuse/_core.py
  tests/key_reuse_test.py
Labels: pull ready

#20094 define a loop-free untrue batching rule for `rng_bit_generator`
  jax/_src/lax/control_flow/loops.py
  jax/_src/random.py
  tests/BUILD
  tests/lax_test.py
  tests/random_lax_test.py
Labels: pull ready

#20143 Removed `__dlpack__` extraction leading to forced legacy path
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#20147 [key reuse] fix random_clone impl rule
  jax/_src/random.py
  tests/key_reuse_test.py
Labels: kokoro:force-run, pull ready

#17741 upgrade random docs to typed RNG keys
  docs/Custom_Operation_for_GPUs.md
  docs/async_dispatch.rst
  docs/device_memory_profiling.md
  docs/jax-101/05-random-numbers.ipynb
  docs/jax-101/05-random-numbers.md
  docs/jax-101/06-parallelism.ipynb
  docs/jax-101/06-parallelism.md
  docs/jax-101/07-state.ipynb
  docs/jax-101/07-state.md
  docs/jax.nn.initializers.rst
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.ipynb
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.md
  docs/notebooks/Neural_Network_and_Data_Loading.ipynb
  docs/notebooks/Neural_Network_and_Data_Loading.md
  docs/notebooks/Writing_custom_interpreters_in_Jax.ipynb
  docs/notebooks/Writing_custom_interpreters_in_Jax.md
  docs/notebooks/autodiff_cookbook.ipynb
  docs/notebooks/autodiff_cookbook.md
  docs/notebooks/convolutions.ipynb
  docs/notebooks/convolutions.md
  docs/notebooks/neural_network_with_tfds_data.ipynb
  docs/notebooks/neural_network_with_tfds_data.md
  docs/notebooks/quickstart.ipynb
  docs/notebooks/quickstart.md
  docs/notebooks/vmapped_log_probs.ipynb
  docs/notebooks/vmapped_log_probs.md
  docs/pallas/quickstart.ipynb
  docs/pallas/quickstart.md
  docs/profiling.md
  examples/advi.py
  examples/differentially_private_sgd.py
  examples/examples_test.py
  examples/gaussian_process_regression.py
  examples/mnist_classifier.py
  examples/mnist_vae.py
  jax/_src/api.py
  jax/_src/core.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/nn/initializers.py
  jax/_src/random.py
  jax/example_libraries/README.md
  jax/example_libraries/stax.py
  jax/experimental/sparse/random.py
  jax/experimental/sparse/transform.py
  jax/random.py
Labels: pull ready

#20161 Fixed Several Typos
  docs/jax-101/06-parallelism.ipynb
  docs/jax-101/06-parallelism.md
  docs/jep/18137-numpy-scipy-scope.md
  docs/pallas/quickstart.ipynb
  docs/pallas/quickstart.md
  docs/pallas/tpu/details.rst
  docs/pallas/tpu/pipelining.ipynb
  docs/pallas/tpu/pipelining.md
  docs/tutorials/advanced-autodiff.md
  docs/tutorials/jax-primitives.md
  docs/tutorials/jaxpr.md
  docs/tutorials/quickstart.md
  docs/tutorials/working-with-pytrees.md
Labels: pull ready

#20181 [key reuse] improve repr for signatures
  jax/experimental/key_reuse/_core.py
  tests/key_reuse_test.py
Labels: pull ready

#20183 [key reuse] define rule for lax.concatenate
  jax/experimental/key_reuse/_core.py
  tests/key_reuse_test.py
Labels: pull ready

#20182 Add a deprecation warning to the xmap function and the corresponding tutorial
  docs/notebooks/xmap_tutorial.ipynb
  docs/notebooks/xmap_tutorial.md
  jax/_src/maps.py
Labels: pull ready

#20197 Fix typos in `multi_process.md`
  docs/multi_process.md
Labels: pull ready

#20194 Update error type in `__dlpack__` and `__dlpack_device__` to match Array API
  jax/_src/array.py
Labels: pull ready

#20201 [attrs] raise an error if we see attrs in a path that hasn't been updated to handle attrs
  jax/_src/interpreters/partial_eval.py
Labels: pull ready

#20204 [shard-map] fix typos in shard_map tutorial
  docs/notebooks/shard_map.ipynb
  docs/notebooks/shard_map.md
Labels: pull ready

#20215 [key-reuse] fix flaky test
  tests/key_reuse_test.py
Labels: pull ready

#20128 setup ci for jax-metal plugin
  .github/workflows/metal_plugin_ci.yml
  jax/_src/test_util.py
  tests/BUILD
  tests/lax_metal_test.py
Labels: pull ready

#20218 [mutable-arrays] support closed-over mutable arrays in jit
  jax/_src/core.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/interpreters/pxla.py
  jax/_src/pjit.py
  jax/experimental/export/_export.py
  tests/state_test.py
Labels: pull ready

#20225 Fix doc typos
  docs/Custom_Operation_for_GPUs.md
  docs/debugging/print_breakpoint.md
  docs/faq.rst
  docs/gpu_performance_tips.md
  docs/jaxpr.rst
  docs/profiling.md
  docs/pytrees.md
  jax/_src/errors.py
Labels: pull ready

#20233 Fix solve broadcasting test
  tests/linalg_test.py
Labels: pull ready

#18395 Fix annotations
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/polynomial.py
  jax/_src/state/types.py
  jax/_src/util.py
Labels: pull ready

#19009 add a shape mismatch check and error to custom_vjp
  jax/_src/custom_derivatives.py
  tests/api_test.py
Labels: pull ready

#20249 Register shard_map rules for random primitives
  jax/experimental/shard_map.py
Labels: pull ready

#19985 DOC: update JAX quick description
  README.md
  docs/index.rst
Labels: documentation, pull ready

#20273 maybe fix forwarding
  jax/_src/pjit.py
  tests/api_test.py
  tests/core_test.py
Labels: pull ready

#20036 Enable host offloading lowering and tests on GPU
  jax/_src/dispatch.py
  tests/memories_test.py
  tests/pjit_test.py
Labels: pull ready

#20277 re-enable pjit forwarding optimization, add tests
  jax/_src/pjit.py
  tests/api_test.py
  tests/core_test.py
Labels: pull ready

#20278 add forwarding optimization test for shard_map
  jax/_src/interpreters/partial_eval.py
  tests/api_test.py
  tests/shard_map_test.py
Labels: pull ready

#20289 micro typo in faq.rst
  docs/faq.rst
Labels: pull ready

#20285 make print_saved_residuals show more checkpoint_name names
  jax/_src/ad_checkpoint.py
  tests/api_test.py
Labels: pull ready

#19602 jax.lax.pbroadcast
  jax/_src/lax/parallel.py
  jax/lax/__init__.py
  tests/pmap_test.py
Labels: pull ready

#20250 Add key reuse config to trace context
  jax/_src/config.py
  tests/key_reuse_test.py
Labels: pull ready

#20258 Fix `jnp.digitize` corner case with no bins
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#20314 Remove internal references to deprecated jax.experimental.maps
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/sharding_test.py
  tests/compilation_cache_test.py
  tests/debug_nans_test.py
  tests/debugging_primitives_test.py
  tests/jaxpr_effects_test.py
  tests/lax_control_flow_test.py
  tests/pjit_test.py
  tests/python_callback_test.py
  tests/xmap_test.py
Labels: kokoro:force-run, pull ready

#20307 [array-api] update to latest array_api_tests commit
  .github/workflows/jax-array-api.yml
Labels: pull ready

#20322 lax_test: make ComplexPlane sign tests compatible with numpy 2
  tests/lax_test.py
Labels: pull ready

#20323 doctest: avoid modifying global flag state
  jax/experimental/key_reuse/__init__.py
Labels: pull ready

#20251 Fix `axis=None, keepdims=True` for `jnp.quantile` and `jnp.median`
  jax/_src/numpy/reductions.py
  tests/lax_numpy_reducers_test.py
Labels: pull ready

#20343 Formatting fix in docstring for lax.full
  jax/_src/lax/lax.py
Labels: pull ready

#20306 DOC: read-through and edit the new jax tutorials
  docs/jep/263-prng.md
  docs/tutorials/advanced-debugging.md
  docs/tutorials/automatic-differentiation.md
  docs/tutorials/debugging.md
  docs/tutorials/external-callbacks.md
  docs/tutorials/index.rst
  docs/tutorials/installation.md
  docs/tutorials/jax-as-accelerated-numpy.md
  docs/tutorials/jit-compilation.md
  docs/tutorials/quickstart.md
  docs/tutorials/random-numbers.md
  docs/tutorials/single-host-sharding.md
  docs/tutorials/thinking-in-jax.md
  docs/tutorials/working-with-pytrees.md
Labels: documentation, pull ready

#20347 DOC: add key concepts doc
  docs/glossary.rst
  docs/tutorials/index.rst
  docs/tutorials/key-concepts.md
Labels: documentation, pull ready

#20357 [host_callback] Deprecate the jax.experimental.host_callback module.
  CHANGELOG.md
  jax/experimental/host_callback.py
  pyproject.toml
Labels: pull ready

#20359 Update discharge.py
  jax/_src/state/discharge.py
Labels: pull ready

#20236 [key reuse] print information about key reuse location
  jax/_src/prng.py
  jax/experimental/key_reuse/_core.py
Labels: pull ready

#20373 Evaluate the correctness of JAX complex functions using mpmath as a reference
  build/test-requirements.txt
  jax/_src/test_util.py
  tests/lax_test.py
Labels: pull ready

#20257 [JAX cuDNN SDPA API] Add is_training and fix seqlen/head_dim checks
  jax/_src/cudnn/fused_attention_stablehlo.py
  tests/BUILD
  tests/fused_attention_stablehlo_test.py
Labels: pull ready

#20436 Update complex function accurancy tests for expm1 and log1p
  tests/lax_test.py
Labels: pull ready

#20445 [scan] don't traverse body jaxpr in lowering
  jax/_src/core.py
  jax/_src/interpreters/mlir.py
  jax/_src/lax/control_flow/loops.py
  jax/experimental/jax2tf/jax2tf.py
Labels: pull ready
