Repository jax-ml/jax, pull requests merged in 2024-06, with the labels that each got.

#21593 Slightly rearranged NDIndexer.from_indices_shape and added missing tests
  jax/_src/state/indexing.py
  tests/pallas/indexing_test.py
Labels: pull ready

#21519 Add pycapsule utility to jax.extend.ffi
  jax/_src/extend/ffi.py
  jax/extend/ffi.py
Labels: pull ready

#21606 [export] Add a helper function to create XLACompatibleShardings for in_shardings
  jax/experimental/export/_export.py
  jax/experimental/export/_serialization.py
  tests/export_test.py
Labels: pull ready

#21439 Add reference to Flax NNX
  README.md
Labels: pull ready

#21485 DOC: Add code example to jax.scipy.fft.dctn doc
  jax/_src/scipy/fft.py
Labels: pull ready

#21624 Fix to scipy.ndimage.map_coordinates documentation.
  jax/_src/scipy/ndimage.py
Labels: pull ready

#21506 Added a link to array-api-tests fix for the tests
  jax/experimental/array_api/skips.txt
Labels: pull ready

#21620 Add default shape to random.rademacher.
  jax/_src/random.py
Labels: pull ready

#21489 Add validation that tests do not change global configs
  jax/_src/test_util.py
  jax/experimental/jax2tf/tests/call_tf_test.py
  tests/pallas/ops_test.py
  tests/pallas/paged_attention_kernel_test.py
Labels: pull ready

#21641 Avoid dynamic docstring generation for jax.tree aliases
  jax/_src/tree.py
  tests/tree_util_test.py
Labels: pull ready

#21500 device-side heap experiment ("slab")
  jax/experimental/slab/djax.py
  jax/experimental/slab/slab.py
Labels: pull ready

#21668 [windows] Add --no-progress to LLVM install command to avoid excessiv…
  .github/workflows/windows_ci.yml
Labels: pull ready

#21646 Simplify flaky test of grad-of-pmap cache hits
  tests/pmap_test.py
Labels: pull ready

#21651 Test: use context manager to set jax_serialization_version
  jax/experimental/jax2tf/tests/call_tf_test.py
  tests/export_test.py
Labels: pull ready

#21571 Updating jnp.abs/absolute docs
  jax/_src/numpy/ufuncs.py
  tests/lax_numpy_test.py
Labels: pull ready

#21494 Add a comment about x86 builds of Python to cpu_feature_guard
  jaxlib/cpu_feature_guard.c
Labels: pull ready

#21676 shape_poly_test: adjust configs via jtu.global_config_context
  jax/_src/test_util.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  tests/shape_poly_test.py
Labels: pull ready

#21418 DOC: Add code examples to jax.scipy.fft.dct doc
  jax/_src/scipy/fft.py
Labels: pull ready

#21679 tests: set configs with jtu.with_config rather than manually
  tests/debug_nans_test.py
  tests/memories_test.py
  tests/mock_gpu_test.py
  tests/multiprocess_gpu_test.py
  tests/transfer_guard_test.py
Labels: pull ready

#21657 DOC: Add code examples to `jax.scipy.fft.idct` and `jax.scipy.fft.idctn` docs
  jax/_src/scipy/fft.py
Labels: pull ready

#21629 Fix typo
  jax/_src/config.py
  jax/_src/internal_test_util/export_back_compat_test_util.py
  jax/_src/numpy/setops.py
Labels: pull ready

#21685 better docs for bitwise_count
  jax/_src/numpy/ufuncs.py
Labels: documentation, kokoro:force-run, pull ready

#21655 [export] Add a LoweringParameters.for_export boolean context for exporting
  jax/_src/interpreters/mlir.py
  jax/experimental/export/_export.py
  tests/export_test.py
Labels: pull ready

#21704 Update release notes for 0.4.29 release.
  CHANGELOG.md
Labels: pull ready

#21702 Make CuDNN SDPA API work with JAX with a CUDA plugin configuration.
  jax/_src/lib/__init__.py
  jax/_src/lib/mosaic_gpu.py
  pyproject.toml
Labels: pull ready

#21688 [slab] support both static- and dynamic-shaped arguments to `djit`ed functions
  jax/experimental/slab/djax.py
Labels: pull ready

#21694 Fix some doc typos
  jax/_src/numpy/lax_numpy.py
  jax/_src/scipy/linalg.py
Labels: pull ready

#21484 Add a helper function for building custom call lowering rules
  jax/_src/extend/ffi.py
  jax/extend/ffi.py
  tests/extend_test.py
Labels: pull ready

#21716 [export] Rename in_shardings and out_shardings field.
  CHANGELOG.md
  jax/_src/internal_test_util/export_back_compat_test_util.py
  jax/experimental/export/_export.py
  jax/experimental/export/_serialization.py
  jax/experimental/jax2tf/jax2tf.py
  tests/export_test.py
Labels: pull ready

#21711 test cleanup: use ExitStack to reduce test boilerplate
  jax/_src/test_util.py
  jax/experimental/array_serialization/serialization_test.py
  jax/experimental/jax2tf/tests/sharding_test.py
  tests/array_test.py
  tests/debugger_test.py
  tests/debugging_primitives_test.py
  tests/export_test.py
  tests/host_callback_test.py
  tests/jaxpr_effects_test.py
  tests/layout_test.py
  tests/multi_device_test.py
  tests/pjit_test.py
  tests/pmap_test.py
  tests/python_callback_test.py
  tests/shard_alike_test.py
  tests/shard_map_test.py
  tests/xmap_test.py
Labels: pull ready

#21710 jax2tf_test: ensure no modification of global config
  jax/experimental/jax2tf/tests/jax2tf_test.py
Labels: pull ready

#21656 fix typo in Custom_Operation_for_GPUs.md
  docs/Custom_Operation_for_GPUs.md
Labels: pull ready

#21692 DOC: Improve documentation for `jnp.fliplr` and `jnp.flipud`
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#21731 fix typo in `jax.numpy.linalg.cross` docstring
  jax/_src/numpy/linalg.py
Labels: pull ready

#21501 softmax: document NaN outputs for infinite inputs
  jax/_src/nn/functions.py
Labels: pull ready

#21690 DOC: Improve docs for `jnp.angle` & `jnp.flip`
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#21733 Edit `pycapsule` docstring to provide a little bit more context
  docs/jax.extend.ffi.rst
  docs/jax.extend.rst
  jax/_src/extend/ffi.py
Labels: pull ready

#21680 [ROCm] Add rocm support in nm.py lowering code
  jax/experimental/sparse/nm.py
Labels: pull ready

#21744 Removed unnecessary mypy exclusions from pyproject.toml
  jax/_src/internal_test_util/test_harnesses.py
  pyproject.toml
Labels: pull ready

#21615 jax.numpy: better docstring for append function
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#21718 pallas/mosaic test: avoid leaking global config state
  tests/mosaic/gpu_test.py
  tests/mosaic/matmul_test.py
  tests/pallas/gpu_attention_test.py
  tests/pallas/pallas_test.py
Labels: pull ready

#21507 increase default precision for hyp1f1
  jax/_src/scipy/special.py
Labels: pull ready

#21759 Fix Typos
  jax/_src/scipy/stats/_core.py
  jax/_src/scipy/stats/bernoulli.py
  jax/_src/scipy/stats/multivariate_normal.py
  jax/_src/scipy/stats/norm.py
Labels: pull ready

#21765 Prepare for 0.4.29 release.
  setup.py
Labels: pull ready

#21763 [export] Create the jax.export module APIs.
  benchmarks/shape_poly_benchmark.py
  jax/_src/export/_export.py
  jax/_src/export/serialization.py
  jax/_src/internal_test_util/export_back_compat_test_util.py
  jax/_src/stages.py
  jax/experimental/export/__init__.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/call_tf_test.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  jax/experimental/jax2tf/tests/tf_test_util.py
  jax/export.py
  tests/export_harnesses_multi_platform_test.py
  tests/export_test.py
  tests/shape_poly_test.py
Labels: pull ready

#21745 better docs for right_shift
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#21774 tree_all: add support for is_leaf
  CHANGELOG.md
  jax/_src/tree.py
  jax/_src/tree_util.py
  tests/tree_util_test.py
Labels: pull ready

#21781 Update version numbers after v0.4.29 release.
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: pull ready

#21516 [DOC] small improvement to the multi-process documentation.
  docs/gpu_performance_tips.md
  docs/multi_process.md
Labels: pull ready

#21791 Remove unused variable
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#21782 Simplify definition of jax.scipy.special.kl_div
  jax/_src/scipy/special.py
Labels: pull ready

#21800 Removed unused ``cuda_options`` from ``lower_jaxpr_to_triton_module``
  jax/_src/pallas/triton/lowering.py
  jax/_src/pallas/triton/pallas_call_registration.py
Labels: kokoro:force-run, pull ready

#21729 Updated the type annotations of *_spec= parameters of pl.pallas_call
  jax/_src/pallas/core.py
  jax/_src/pallas/mosaic/core.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pallas/primitives.py
  jax/experimental/pallas/ops/tpu/flash_attention.py
Labels: kokoro:force-run, pull ready

#21803 [export] Cleaned up types of [in|out]_shardings
  jax/_src/export/_export.py
  jax/_src/export/serialization.fbs
  jax/_src/export/serialization.py
  jax/_src/export/shape_poly.py
  tests/export_test.py
Labels: pull ready

#21772 jax.scipy.special.beta: deprecate x,y in favor of a,b
  CHANGELOG.md
  jax/_src/scipy/special.py
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#21802 Added filelock to test-requirements.txt and requirements lock files
  build/requirements_lock_3_10.txt
  build/requirements_lock_3_11.txt
  build/requirements_lock_3_12.txt
  build/requirements_lock_3_9.txt
  build/test-requirements.txt
Labels: pull ready

#21762 DOC: Add example code snippets to jax.scipy.signal.convolve2d, correlate and correlate2d docs
  jax/_src/scipy/signal.py
Labels: pull ready

#21725 DOC: Add example code snippets to `jax.scipy.linalg.expm` and `jax.scipy.linalg.polar` docs
  jax/_src/scipy/linalg.py
Labels: pull ready

#21394 Implement LRU cache eviction for persistent compilation cache
  jax/BUILD
  jax/_src/compilation_cache.py
  jax/_src/config.py
  jax/_src/gfile_cache.py
  jax/_src/lru_cache.py
  pyproject.toml
  tests/BUILD
  tests/lru_cache_test.py
Labels: pull ready

#21799 [pallas] Add support for cross-platform lowering
  jax/_src/interpreters/mlir.py
  jax/_src/pallas/mosaic/pallas_call_registration.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pallas/triton/pallas_call_registration.py
  tests/export_test.py
  tests/pallas/export_pallas_test.py
Labels: pull ready

#21769 [export] Add documentation for jax.export
  .github/workflows/ci-build.yaml
  docs/aot.md
  docs/export/export.md
  docs/export/index.rst
  docs/export/jax2tf.md
  docs/export/shape_poly.md
  docs/jax.export.rst
  docs/jax.rst
  docs/user_guides.rst
  jax/_src/export/_export.py
  jax/_src/export/shape_poly.py
  tests/export_test.py
Labels: pull ready

#21823 Removed BlockSpec.__init__
  jax/_src/pallas/core.py
  jax/_src/pallas/mosaic/core.py
Labels: pull ready

#21832 Document jax.export serialization version numbers
  docs/export/export.md
  docs/jax.export.rst
  jax/_src/export/_export.py
Labels: pull ready

#21837 Document jax.tree.* directly
  docs/jax.tree_util.rst
  jax/_src/tree.py
  jax/_src/tree_util.py
Labels: documentation, pull ready

#21846 Fixing the naming conventions in signal.py
  jax/_src/scipy/signal.py
Labels: pull ready

#21848 Update JAX dependencies, extras, and documentation for plugins.
  CHANGELOG.md
  README.md
  docs/installation.md
  docs/quickstart.md
  jax_plugins/cuda/plugin_setup.py
  jaxlib/setup.py
  setup.py
Labels: pull ready

#21851 Readd cuda12_pip extra to keep CI users happy.
  setup.py
Labels: pull ready

#21804 DOC: Better docs for `jnp.convolve` & `jnp.correlate`
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#21834 avoid globally silencing the jit backend/device warning
  pyproject.toml
  tests/api_test.py
  tests/host_callback_test.py
  tests/multibackend_test.py
  tests/pjit_test.py
Labels: pull ready

#21829 Deprecate internal pretty-printing APIs, jax.core.pp_*
  CHANGELOG.md
  jax/core.py
Labels: pull ready

#21853 jax.dtypes: avoid erroring on non-hashable dtype
  jax/_src/dtypes.py
  tests/dtypes_test.py
Labels: pull ready

#21857 fix multi_backend_tests
  tests/multibackend_test.py
Labels: pull ready

#21859 Add option to force windows CI run by adding label
  .github/workflows/windows_ci.yml
Labels: pull ready, windows:force-run

#21861 Add --allow-downgrade to LLVM install on Windows.
  .github/workflows/windows_ci.yml
Labels: pull ready, windows:force-run

#21847 [export] Deprecate jax.experimental.export
  CHANGELOG.md
  docs/export/export.md
  jax/experimental/export/__init__.py
  tests/export_test.py
  tests/pallas/export_pallas_test.py
Labels: pull ready

#21865 Temporarily reinstate the jax[cpu] in the install instructions.
  README.md
  docs/installation.md
Labels: pull ready

#20728 Doc: Fix example code snippet format in `jax.experimental.multihost_utils.global_array_to_host_local_array` doc
  jax/experimental/multihost_utils.py
Labels: pull ready

#21864 Added docstrings to pl.num_programs() and pl.program_id()
  jax/_src/pallas/core.py
  jax/_src/pallas/mosaic/pipeline.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pallas/primitives.py
Labels: pull ready

#21863 Deprecate hashing of tracers
  CHANGELOG.md
  jax/BUILD
  jax/__init__.py
  jax/_src/core.py
  jax/_src/scipy/optimize/line_search.py
  tests/array_test.py
Labels: pull ready

#21871 fix some additional warnings related to #21834
  tests/api_test.py
  tests/linalg_test.py
  tests/multi_device_test.py
  tests/multibackend_test.py
  tests/transfer_guard_test.py
Labels: kokoro:force-run, pull ready

#21879 [export] Fix a couple of missed deprecated fields.
  jax/experimental/jax2tf/jax2tf.py
Labels: pull ready

#21856 Deprecate passing of arrays in place of dtypes.
  CHANGELOG.md
  jax/_src/dtypes.py
  tests/dtypes_test.py
Labels: pull ready

#21890 Update nightly installation instructions to reflect new jax/jaxlib de…
  docs/installation.md
Labels: pull ready

#21888 lax.mul: accept boolean inputs
  jax/_src/lax/lax.py
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#21880 [shape_poly] Add documentation for shape polymorphism
  docs/_static/style.css
  docs/export/export.md
  docs/export/jax2tf.md
  docs/export/shape_poly.md
  jax/_src/config.py
  jax/_src/export/_export.py
  jax/_src/export/shape_poly.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  tests/export_test.py
  tests/shape_poly_test.py
Labels: pull ready

#21897 Fixing installation docs: needed quotes; markdown fix
  docs/installation.md
Labels: pull ready

#21901 Fix CUDNN requirement inconsistency in installation.md
  docs/installation.md
Labels: pull ready

#21904 Fixing the naming conventions in lax_numpy.py
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#21911 [shape_poly] Add documentation for workaround with dimension parameters.
  docs/export/shape_poly.md
  jax/_src/export/shape_poly.py
Labels: pull ready

#21905 Fix Typos
  jax/_src/lax/lax.py
  jax/_src/lax/parallel.py
  jax/_src/lax/svd.py
  jax/_src/numpy/linalg.py
  jax/_src/numpy/setops.py
  jax/_src/numpy/ufunc_api.py
Labels: pull ready

#21912 Added some docs to ``_hoist_consts_to_refs``
  jax/_src/pallas/pallas_call.py
Labels: pull ready

#21922 Use NumPy 2.0.0 and SciPy 1.13.1 in builds.
  .github/workflows/wheel_win_x64.yml
  .github/workflows/windows_ci.yml
  build/requirements.in
  build/requirements_lock_3_10.txt
  build/requirements_lock_3_11.txt
  build/requirements_lock_3_12.txt
  build/requirements_lock_3_9.txt
Labels: pull ready

#21645 Add CUDA custom call example as a JAX test
  docs/cuda_custom_call/BUILD
  docs/cuda_custom_call/Makefile
  docs/cuda_custom_call/cuda_custom_call_test.py
  docs/cuda_custom_call/foo.cu.cc
  jax/_src/test_util.py
  tests/gpu_memory_flags_test.py
Labels: pull ready

#21945 Prepare for 0.4.30 release.
  setup.py
Labels: pull ready

#21949 Add --allow-downgrade to Windows wheel builds.
  .github/workflows/wheel_win_x64.yml
Labels: pull ready

#21957 Skip export_pallas_test.py on Windows
  tests/pallas/export_pallas_test.py
Labels: pull ready

#21955 Fix typo in `jax.export` migration guide
  docs/export/export.md
Labels: pull ready

#21809 [ROCm]: Pallas updates for ROCm
  jax/_src/pallas/triton/lowering.py
  jax/_src/pallas/triton/pallas_call_registration.py
Labels: pull ready

#21956 Bump minimum jaxlib version to v0.4.30.
  jax/_src/array.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/ann.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/linalg.py
  jax/_src/pjit.py
  jax/_src/sharding_impls.py
  jax/_src/test_util.py
  jax/_src/xla_bridge.py
  jax/version.py
  tests/api_test.py
  tests/array_test.py
  tests/cholesky_update_test.py
  tests/export_back_compat_test.py
  tests/extend_test.py
  tests/memories_test.py
  tests/pgle_test.py
  tests/shape_poly_test.py
  tests/shard_map_test.py
  tests/xla_bridge_test.py
Labels: pull ready

#21960 Remove `[cpu]` extra from installation instructions.
  README.md
  docs/installation.md
Labels: kokoro:force-run, pull ready

#21961 Update Windows Actions workflow name
  .github/workflows/windows_ci.yml
Labels: pull ready

#20761 Changed the naming of internal config APIs
  jax/_src/compiler.py
  jax/_src/config.py
  jax/_src/core.py
  jax/_src/interpreters/mlir.py
  jax/_src/maps.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pretty_printer.py
  jax/_src/test_util.py
  jax/_src/tpu_custom_call.py
  jax/_src/xla_bridge.py
  jax/experimental/host_callback.py
Labels: pull ready

#22030 Fix the eager mode execution for lax.platform_dependent
  jax/_src/lax/control_flow/conditionals.py
  tests/lax_control_flow_test.py
Labels: pull ready

#22032 Rename "Example" to "Examples" in docstrings.
  jax/_src/array.py
  jax/_src/config.py
  jax/_src/custom_derivatives.py
  jax/_src/distributed.py
  jax/_src/lax/lax.py
  jax/_src/maps.py
  jax/_src/mesh.py
  jax/_src/nn/functions.py
  jax/_src/nn/initializers.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/linalg.py
  jax/_src/numpy/ufuncs.py
  jax/_src/random.py
  jax/_src/scipy/fft.py
  jax/_src/scipy/linalg.py
  jax/_src/scipy/signal.py
  jax/_src/sharding_impls.py
  jax/_src/test_util.py
  jax/_src/third_party/scipy/interpolate.py
  jax/_src/third_party/scipy/linalg.py
  jax/_src/tree.py
  jax/_src/tree_util.py
  jax/experimental/array_serialization/serialization.py
  jax/experimental/custom_partitioning.py
  jax/experimental/mosaic/gpu/fragmented_array.py
  jax/experimental/sparse/ad.py
Labels: pull ready

#22027 DOC: Add code examples to `jax.scipy.stats.mode` docs
  jax/_src/scipy/stats/_core.py
Labels: pull ready

#22014 jax.numpy: better docstring for iscomplex function
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#21973 Improve docs for jnp.poly and polyval
  jax/_src/numpy/polynomial.py
Labels: pull ready

#22028 Fix the behavior of `jax.scipy.stats.sem` when `keepdims=True`.
  jax/_src/scipy/stats/_core.py
  tests/scipy_stats_test.py
Labels: pull ready

#22042 Update minimum NumPy version to v1.24.
  CHANGELOG.md
  jaxlib/setup.py
  setup.py
  tests/array_interoperability_test.py
  tests/lax_metal_test.py
  tests/lax_numpy_reducers_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#21966 jax.numpy: better docstring for iscomplexobj function
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#21991 Improved docs for jnp.polyint and jnp.polyder
  jax/_src/numpy/polynomial.py
Labels: pull ready

#20731 Copy nn.{softmax,log_softmax} to scipy.special
  docs/jax.scipy.rst
  jax/_src/scipy/special.py
  jax/scipy/special.py
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#21951 Improve docs for jnp.roots and jnp.polyfit
  jax/_src/numpy/polynomial.py
Labels: pull ready

#22056 DOC: Add code examples to `jax.scipy.stats.sem` docs
  jax/_src/scipy/stats/_core.py
Labels: pull ready

#22063 Internal: remove one_to_one_unop factory
  jax/_src/numpy/ufuncs.py
  tests/lax_numpy_test.py
Labels: pull ready

#21978 [export] Fix multi-platform lowering for unknown platform, with donated_argnums
  jax/_src/export/_export.py
  jax/_src/interpreters/mlir.py
  tests/export_test.py
Labels: pull ready

#22066 Internal: remove binary operation ufunc factories
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#22069 faster inline jaxpr by avoiding creating Tracers for intermediates
  jax/_src/interpreters/partial_eval.py
Labels: pull ready

#21984 Better rint doc
  jax/_src/numpy/ufuncs.py
Labels: kokoro:force-run, pull ready

#22000 better copysign doc
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#22082 [pallas] Break long lines in the Pallas docs
  docs/pallas/design.md
  docs/pallas/quickstart.ipynb
  docs/pallas/quickstart.md
  docs/pallas/tpu/pipelining.ipynb
  docs/pallas/tpu/pipelining.md
Labels: pull ready

#22081 DOC: Better doc for ``jnp.sum``
  jax/_src/numpy/reductions.py
Labels: pull ready

#22083 Update jnp.max/amax docs
  jax/_src/numpy/reductions.py
  tests/lax_numpy_test.py
Labels: pull ready

#21441 Updated jnp.ceil/floor/trunc to preserve int dtypes
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/ufuncs.py
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_elementwise_functions.py
  tests/jet_test.py
  tests/pallas/pallas_test.py
Labels: pull ready

#22098 remove double dots from an error message
  jax/_src/core.py
  tests/api_test.py
Labels: pull ready

#22097 jax.numpy: better docstring for isreal and isrealobj functions
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#22099 fix error message path since #22069 allowed Literals in jaxpr builder eqns
  jax/_src/interpreters/partial_eval.py
  tests/api_test.py
Labels: pull ready

#21916 [ROCM] JAX pjrt plugin for rocm
  .bazelrc
  build/build.py
  build/rocm/build_rocm.sh
  jax/_src/test_util.py
  jax/tools/build_utils.py
  jax_plugins/BUILD.bazel
  jax_plugins/rocm/BUILD.bazel
  jax_plugins/rocm/__init__.py
  jax_plugins/rocm/plugin_pyproject.toml
  jax_plugins/rocm/plugin_setup.py
  jax_plugins/rocm/pyproject.toml
  jax_plugins/rocm/setup.py
  jaxlib/BUILD
  jaxlib/gpu_linalg.py
  jaxlib/gpu_prng.py
  jaxlib/gpu_solver.py
  jaxlib/gpu_sparse.py
  jaxlib/gpu_triton.py
  jaxlib/rocm/BUILD.bazel
  jaxlib/rocm_plugin_extension.cc
  jaxlib/tools/BUILD.bazel
  jaxlib/tools/build_gpu_kernels_wheel.py
  jaxlib/tools/build_gpu_plugin_wheel.py
  jaxlib/tools/build_wheel.py
Labels: pull ready

#22047 Fix type annotations for jnp.poly* functions
  jax/_src/numpy/polynomial.py
  jax/numpy/__init__.pyi
Labels: pull ready

#22039 [ROCM] Fix rocm platform name in nm.py
  jax/experimental/sparse/nm.py
Labels: pull ready

#22062 [ROCM] Fix export test for rocm
  tests/export_test.py
Labels: pull ready

#22106 Fix pre-commit formatting errors
  build/build.py
  build/rocm/run_single_gpu.py
Labels: pull ready

#22091 Update flags gpu_performance_tips.md
  docs/gpu_performance_tips.md
Labels: pull ready

#22087 jax.config: validate on set()
  jax/_src/config.py
  tests/BUILD
  tests/config_test.py
  tests/logging_test.py
Labels: pull ready

#21673 make cond forward inputs to outputs, reduces vmap lifting
  jax/_src/lax/control_flow/conditionals.py
  tests/lax_control_flow_test.py
Labels: pull ready

#21806 prune cond passthrough outputs
  jax/_src/lax/control_flow/conditionals.py
  tests/lax_control_flow_test.py
Labels: pull ready

#22102 DOC: Update jnp.min/amin docs
  jax/_src/numpy/reductions.py
  tests/lax_numpy_test.py
Labels: pull ready

#22113 Update minimum Python version to 3.10.
  .bazelrc
  .github/workflows/ci-build.yaml
  CHANGELOG.md
  WORKSPACE
  build/build.py
  build/requirements.in
  build/requirements_lock_3_9.txt
  docs/contributing.md
  jax/BUILD
  jax/_src/ops/scatter.py
  jax/_src/xla_bridge.py
  jax_plugins/cuda/plugin_setup.py
  jaxlib/jax.bzl
  jaxlib/setup.py
  pyproject.toml
  setup.py
  tests/mosaic/flash_attention_test.py
  tests/mosaic/gpu_test.py
  tests/mosaic/matmul_test.py
Labels: pull ready

#22009 better floor_division doc
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#22116 jax_default_matmul_precision: allow 'default', 'high', and 'highest'
  jax/_src/config.py
Labels: pull ready

#22093 Fix bug in bcoo_spdot_general abstract_eval
  jax/experimental/sparse/bcoo.py
  tests/sparse_bcoo_bcsr_test.py
Labels: pull ready

#22118 Run `pyupgrade --py310-plus` on .pyi files.
  jax/_src/basearray.pyi
  jax/numpy/__init__.pyi
Labels: pull ready

#22103 DOC: Update jnp.prod docs
  jax/_src/numpy/reductions.py
Labels: pull ready

#22071 Better docs for empty/zeros/ones/full
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#22049 [shard-map] allow in_specs=None to work with arbitrary objects
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#22105 DOC: Update docs of jnp.all and jnp.any
  jax/_src/numpy/reductions.py
Labels: pull ready

#21980 Added device to `jnp.arange`, `jnp.eye` and tests
  jax/_src/numpy/lax_numpy.py
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_creation_functions.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#22126 CI: set ruff to Python 3.10
  pyproject.toml
Labels: pull ready

#22123 tweak dynamic trace state to only depend on level int, not MainTrace
  jax/_src/config.py
  jax/_src/core.py
Labels: pull ready

#22128 Improved docs for eye & identity
  jax/_src/numpy/lax_numpy.py
Labels: pull ready
