Repository jax-ml/jax, pull requests merged in 2024-08, with the labels that each got.

#22802 DOC: Improved documentation for diag_indices and diag_indices_from
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#22779 Add concretization error check in core.min_dim and core.max_dim
  jax/_src/core.py
  jax/_src/lax/lax.py
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
  tests/shape_poly_test.py
Labels: pull ready

#22816 Fix issue with multiple arguments when using custom_vjp with optimize_remat
  jax/_src/custom_derivatives.py
  tests/api_test.py
Labels: pull ready

#22810 type: add annot
  jax/_src/numpy/array_methods.py
Labels: pull ready

#22794 [array api] use jnp.astype directly
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_data_type_functions.py
Labels: pull ready

#22818 Finalize array API in jax.numpy & deprecate jax.experimental.array_api
  .github/workflows/ci-build.yaml
  .github/workflows/jax-array-api.yml
  CHANGELOG.md
  docs/jax.experimental.array_api.rst
  docs/jax.numpy.rst
  jax/BUILD
  jax/_src/basearray.pyi
  jax/_src/numpy/array_api_metadata.py
  jax/_src/numpy/array_methods.py
  jax/experimental/__init__.py
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_version.py
  jax/experimental/array_api/fft.py
  jax/experimental/array_api/linalg.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/array_api_skips.txt
  tests/array_api_test.py
Labels: pull ready

#22095 Add `ffi_call` tutorial
  docs/_tutorials/index.rst
  docs/conf.py
  docs/ffi.ipynb
  docs/ffi.md
  docs/ffi/.gitignore
  docs/ffi/CMakeLists.txt
  docs/ffi/rms_norm.cc
  docs/jax.lax.rst
  docs/requirements.txt
  docs/user_guides.rst
Labels: pull ready

#22814 Bumped mypy to 1.11.0 and jaxlib to 0.4.31 on the CI
  .pre-commit-config.yaml
  jax/_src/api.py
  jax/_src/custom_derivatives.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/layout.py
  jax/_src/linear_util.py
  jax/_src/pallas/core.py
  jax/_src/pretty_printer.py
  jax/_src/scipy/signal.py
  jax/_src/scipy/special.py
  jax/_src/scipy/stats/norm.py
  jax/_src/test_util.py
  jax/_src/tree_util.py
  jax/experimental/pallas/ops/tpu/flash_attention.py
  jax/experimental/pallas/ops/tpu/paged_attention/paged_attention_kernel.py
  pyproject.toml
Labels: pull ready

#22812 Removed various ununsed functions
  jax/_src/abstract_arrays.py
  jax/_src/interpreters/mlir.py
  jax/_src/lax/ann.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/lax.py
  jax/_src/lax/parallel.py
  jax/_src/pallas/core.py
  jax/_src/pallas/mosaic/lowering.py
  jax/_src/scipy/sparse/linalg.py
  jax/_src/state/discharge.py
  jax/_src/state/primitives.py
Labels: pull ready

#22840 remove jax.extend.backend.default_backend in favor of jax.default_backend
  jax/extend/backend.py
  jax/lib/xla_bridge.py
  tests/extend_test.py
Labels: pull ready

#22784 Update complex functions accuracy tests
  jax/_src/test_util.py
  tests/lax_test.py
Labels: pull ready

#22828 [ROCM] Add support to continue on fail, fix script paths and update Dockerfile to add necessary packages
  build/rocm/Dockerfile.ms
  build/rocm/run_multi_gpu.sh
  build/rocm/run_single_gpu.py
Labels: pull ready

#22857 improve while_loop carry pytree/type mismatch errors
  jax/_src/lax/control_flow/loops.py
  tests/lax_control_flow_test.py
Labels: pull ready

#22849 Improve documentation for jnp.from_dlpack
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#22141 Update CUDA custom call example code to use `ffi_call`
  docs/cuda_custom_call/cuda_custom_call_test.py
Labels: pull ready

#22844 Tighten the public API for jax.lib.xla_client & xla_extension
  .github/workflows/ci-build.yaml
  jax/lib/__init__.py
  jax/lib/xla_client.py
  jax/lib/xla_extension.py
Labels: pull ready

#22836 Added a custom JVP rule for jax.nn.logsumexp
  jax/_src/ops/special.py
  tests/lax_scipy_test.py
Labels: pull ready

#22608 [NVIDIA] Fix CUDA version checks
  jax/_src/test_util.py
Labels: pull ready

#22885 Deprecate `jax.lib.xla_client._xla`
  jax/lib/xla_client.py
Labels: kokoro:force-run, pull ready

#22896 CI: pin sphinx to avoid build errors on 8.0
  docs/requirements.txt
Labels: pull ready

#22834 DOC: Better docs for `jnp.fft.hfft` and `jnp.fft.ihfft`
  jax/_src/numpy/fft.py
Labels: pull ready

#22901 [ROCM] Fix hipsolverSsyevd tests due to align with the rocm behavior.
  jaxlib/gpu_solver.py
Labels: pull ready

#22649 [ROCM] Fix export harness tests
  jax/_src/export/_export.py
  jax/_src/internal_test_util/export_back_compat_test_data/rocm_eigh_hipsolver_syev.py
  jax/_src/internal_test_util/export_back_compat_test_data/rocm_qr_hipsolver_geqrf.py
  tests/export_back_compat_test.py
Labels: pull ready

#22900 deprecate jax.lib.xla_client.bfloat16
  jax/lib/xla_client.py
Labels: pull ready

#22914 DOC: Better docs for `jnp.fft.rfft2` and `jnp.fft.irfft2`
  jax/_src/numpy/fft.py
Labels: pull ready

#22908 [pallas] Add a warning message about experimental and incomplete status
  docs/pallas/index.rst
Labels: pull ready

#22869 Small tweaks to custom_vmap UI
  jax/_src/api_util.py
  jax/_src/custom_batching.py
  jax/_src/custom_derivatives.py
  tests/api_test.py
Labels: pull ready

#22897 Support empty boolean indexing
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#22820 Faster MHA backwards pass
  jax/experimental/pallas/ops/gpu/attention.py
  tests/pallas/gpu_ops_test.py
Labels: pull ready

#22830 [NVIDIA] Support vmap usage of `jax.nn.dot_product_attention`
  jax/_src/cudnn/fused_attention_stablehlo.py
  jax/_src/nn/functions.py
  tests/nn_test.py
Labels: pull ready

#22909 [ROCM] Fix BUILD.bazel library source paths
  jaxlib/gpu/solver.cc
  jaxlib/gpu/vendor.h
  jaxlib/rocm/BUILD.bazel
Labels: pull ready

#22920 CI: fix mypy errors
  jax/_src/nn/functions.py
Labels: pull ready

#22925 Remove PositionalSharding from distributed array doc
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.ipynb
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.md
Labels: pull ready

#22923 Small performance improvement to pallas MHA
  jax/experimental/pallas/ops/gpu/attention.py
Labels: pull ready

#22937 Improve error message for missing vmap rule in custom_vmap
  jax/_src/custom_batching.py
  tests/api_test.py
Labels: pull ready

#22916 Improve documentation for jnp.piecewise & jnp.select
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#22903 [array API] update test suite to most recent commit
  .github/workflows/jax-array-api.yml
  pyproject.toml
  tests/array_api_skips.txt
Labels: pull ready

#22373 [jax.distributed] Allow setting local device ids via env var
  jax/_src/distributed.py
Labels: pull ready

#22887 [Pallas] Add pallas distributed computation tutorial
  docs/_static/pallas/distributed/all_gather.svg
  docs/_static/pallas/distributed/race_condition.svg
  docs/_static/pallas/distributed/rdma_recv.svg
  docs/_static/pallas/distributed/rdma_send.svg
  docs/_static/pallas/distributed/rdma_start.svg
  docs/_static/pallas/distributed/reduce_scatter_1.svg
  docs/_static/pallas/distributed/reduce_scatter_2.svg
  docs/_static/pallas/distributed/reduce_sum_1.svg
  docs/_static/pallas/distributed/reduce_sum_2.svg
  docs/conf.py
  docs/pallas/tpu/distributed.ipynb
  docs/pallas/tpu/distributed.md
  docs/pallas/tpu/index.rst
Labels: pull ready

#22958 DOC: Improved docs for `jnp.fft.rfftn` and `jnp.fft.irfftn`
  jax/_src/numpy/fft.py
Labels: pull ready

#22988 indent code consistently in auto-parallelization and shard_map tutorials
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.ipynb
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.md
  docs/notebooks/shard_map.ipynb
  docs/notebooks/shard_map.md
Labels: documentation, pull ready

#22992 in `dot` docstring, format and link to `dot_general`
  jax/_src/lax/lax.py
Labels: documentation, pull ready

#22989 update README and several docs to use typed RNG keys
  README.md
  benchmarks/api_benchmark.py
  benchmarks/sparse_benchmark.py
  cloud_tpu_colabs/JAX_NeurIPS_2020_demo.ipynb
  cloud_tpu_colabs/JAX_demo.ipynb
  cloud_tpu_colabs/Lorentz_ODE_Solver.ipynb
  cloud_tpu_colabs/Pmap_Cookbook.ipynb
  docs/Custom_Operation_for_GPUs.md
  docs/Custom_Operation_for_GPUs.py
  docs/_tutorials/advanced-autodiff.md
  docs/notebooks/shard_map.ipynb
  docs/notebooks/shard_map.md
  jax/_src/nn/initializers.py
Labels: documentation, pull ready

#22991 emphasize typed over legacy RNG keys in `random` module docs
  docs/jax.random.rst
  jax/_src/random.py
Labels: documentation, pull ready

#22667 [ROCm]: Add get_arch_details for triton kernel call
  jaxlib/gpu/triton.cc
  jaxlib/gpu_triton.py
Labels: pull ready

#22997 Collapsed a few unnecessary ``if TYPE_CHECKING`` blocks
  jax/_src/lax/lax.py
  jax/_src/util.py
Labels: pull ready

#22979 jnp.intersect1d: add support for static size argument.
  jax/_src/numpy/setops.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#22600 [ROCm] Update ROCm builds for manylinux_2_28
  build/rocm/Dockerfile.ms
  build/rocm/build_rocm.sh
  build/rocm/build_wheels/Dockerfile.manylinux_2_28_x86_64.rocm
  build/rocm/ci_build
  build/rocm/ci_build.sh
  build/rocm/setup.rocm.sh
  build/rocm/tools/blacken.sh
  build/rocm/tools/build_wheels.py
  build/rocm/tools/fixwheel.py
  build/rocm/tools/get_rocm.py
  build/rocm/tools/libc.py
  build/rocm/tools/symbols.py
Labels: pull ready

#23023 docs: consistent case (sentence)
  docs/advanced_guide.rst
  docs/building_on_jax.md
  docs/contributing.md
  docs/contributor_guide.rst
  docs/device_memory_profiling.md
  docs/faq.rst
  docs/glossary.rst
  docs/index.rst
  docs/investigating_a_regression.md
  docs/jaxpr.rst
  docs/notebooks/Neural_Network_and_Data_Loading.ipynb
  docs/notebooks/Neural_Network_and_Data_Loading.md
  docs/notebooks/convolutions.ipynb
  docs/notebooks/convolutions.md
  docs/notebooks/external_callbacks.ipynb
  docs/notebooks/external_callbacks.md
  docs/notebooks/neural_network_with_tfds_data.ipynb
  docs/notebooks/neural_network_with_tfds_data.md
  docs/notebooks/thinking_in_jax.ipynb
  docs/notebooks/thinking_in_jax.md
  docs/persistent_compilation_cache.md
  docs/stateful-computations.md
  docs/user_guides.rst
Labels: documentation, pull ready

#22976 Better docs for array, asarray, linspace
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
Labels: documentation, pull ready

#23017 test: improve test cases for set-like operations
  tests/lax_numpy_test.py
Labels: pull ready

#23027 docs: more case fixes
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
Labels: documentation, pull ready

#23020 jnp.setxor1d: add support for static size argument
  jax/_src/numpy/setops.py
  tests/lax_numpy_test.py
Labels: pull ready

#23000 Fix bug in custom_vjp with optimize_remat and custom_vmap
  jax/_src/custom_derivatives.py
  tests/api_test.py
Labels: pull ready

#23036 docs: tidy up titles and headings
  docs/advanced_guide.rst
  docs/debugging/index.md
  docs/device_memory_profiling.md
  docs/errors.rst
  docs/faq.rst
  docs/ffi.ipynb
  docs/ffi.md
  docs/glossary.rst
  docs/index.rst
  docs/installation.md
  docs/key-concepts.md
  docs/notebooks/external_callbacks.ipynb
  docs/notebooks/external_callbacks.md
  docs/notebooks/vmapped_log_probs.ipynb
  docs/notebooks/vmapped_log_probs.md
  docs/profiling.md
  docs/tutorials.rst
Labels: documentation, pull ready

#23042 doc: clarify data_fields & meta_fields in register_dataclass
  jax/_src/tree_util.py
Labels: documentation, kokoro:force-run, pull ready

#23047 docs: fix `shard_map` guide headings
  docs/notebooks/shard_map.ipynb
  docs/notebooks/shard_map.md
Labels: documentation, pull ready

#23040 Add method argument for jnp.isin
  jax/_src/numpy/setops.py
  tests/lax_numpy_test.py
Labels: pull ready

#23060 Deprecate several internal utilities in jax.core
  CHANGELOG.md
  jax/core.py
Labels: pull ready

#23069 Document methods of custom_jvp/custom_vjp
  docs/jax.rst
  jax/_src/custom_derivatives.py
Labels: documentation, pull ready

#23039 docs: reorganize sections
  docs/advanced_guide.rst
  docs/contributor_guide.rst
  docs/distributed_data_loading.md
  docs/extensions.rst
  docs/index.rst
  docs/jax.rst
  docs/jax_internal_api.rst
  docs/user_guides.rst
Labels: documentation, pull ready

#23080 document jax.Array methods and attributes
  docs/jax.rst
  jax/_src/numpy/array_methods.py
Labels: documentation, pull ready

#23088 Passing bazel options to requirements update commands in build.py
  build/build.py
Labels: pull ready

#23103 DOC: Remove the unused `_CONV_PREFERRED_ELEMENT_TYPE_DESCRIPTION`
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23094 Improve type annotations for jax.Array methods
  jax/_src/basearray.pyi
  jax/_src/numpy/array_methods.py
Labels: pull ready

#23045 DOC: Improved documentation for diagflat, diag and diagonal.
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#22586 Use pathlib for profiler log_dir
  jax/_src/profiler.py
  jax/collect_profile.py
Labels: pull ready

#23102 DOC: Better docs for `jnp.fmin` and `jnp.fmax`
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#22523 fix basic scan bug with attrs
  jax/_src/lax/control_flow/loops.py
  tests/attrs_test.py
Labels: pull ready

#23129 Added py::mod_gil_not_used() to PYBIND11_MODULE register_jax_dialects
  jaxlib/mlir/_mlir_libs/register_jax_dialects.cc
Labels: pull ready

#23130 Added `PyUnstable_Module_SetGIL` to `PyInit_cpu_feature_guard`
  jaxlib/cpu_feature_guard.c
Labels: pull ready

#22924 [ROCm] Fix run single gpu script to avoid duplicates
  build/rocm/Dockerfile.ms
  build/rocm/run_single_gpu.py
Labels: pull ready

#23118 remove trailing comma
  jax/_src/basearray.pyi
Labels: pull ready

#23119 Improve documentation for jnp.copy
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#23143 Added `py::mod_gil_not_used()` to `PYBIND11_MODULE` for `_triton_ext` and `_tpu_ext`
  jaxlib/mlir/_mlir_libs/tpu_ext.cc
  jaxlib/mlir/_mlir_libs/triton_ext.cc
Labels: pull ready

#23152 Update jax landing page
  docs/_static/style.css
  docs/index.rst
Labels: documentation, pull ready

#23154 Fix argument names for jnp.arctan2/jnp.atan2
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#23166 [ROCm] Fix bazel build issue
  jaxlib/rocm/BUILD.bazel
Labels: pull ready

#23146 [ROCm] Rocm62 fixes
  build/rocm/ci_build
  build/rocm/ci_build.sh
  build/rocm/tools/build_wheels.py
  build/rocm/tools/get_rocm.py
Labels: pull ready

#23183 DOC: Improved documentation for jax.numpy.roll
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23196 Register several jax.numpy argument name deprecations
  jax/__init__.py
  jax/_src/deprecations.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/linalg.py
  jax/_src/numpy/reductions.py
  tests/lax_numpy_reducers_test.py
  tests/lax_numpy_test.py
  tests/linalg_test.py
Labels: pull ready

#23222 add experimental jax.no_tracing context manager
  jax/__init__.py
  jax/_src/config.py
  jax/_src/pjit.py
  tests/api_test.py
Labels: pull ready

#23228 improve `scan` error message on non-concrete `length` argument
  jax/_src/lax/control_flow/loops.py
  tests/lax_control_flow_test.py
Labels: better_errors, pull ready

#23197 Better docs for jnp quantile & percentile
  jax/_src/numpy/reductions.py
Labels: documentation, pull ready

#23229 improve `scan` error message on non-concrete `unroll` argument
  jax/_src/lax/control_flow/loops.py
  tests/lax_control_flow_test.py
Labels: better_errors, pull ready

#23236 jnp.mean: fix normalizer for large arrays
  jax/_src/numpy/reductions.py
Labels: pull ready

#23240 DOC: update docstrings for broadcast-related functions
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#23207 Clarify meaning of tall and wide Jacobian matrices in autodiff docs.
  docs/_tutorials/advanced-autodiff.md
  docs/notebooks/autodiff_cookbook.ipynb
  docs/notebooks/autodiff_cookbook.md
Labels: pull ready

#23274 Fix mypy error
  build/rocm/run_single_gpu.py
  build/rocm/tools/build_wheels.py
  build/rocm/tools/symbols.py
Labels: pull ready

#23233 DOC: Improved docs for jnp.fix and jnp.trunc
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23271 Fast jvp for 3x3 and 2x2 determinants
  jax/_src/numpy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#22972 Update pgo_nsys_converter.py NVTX kern sum report name
  jax/tools/pgo_nsys_converter.py
Labels: pull ready

#23279 CI: update ruff to v0.6.1
  .pre-commit-config.yaml
  cloud_tpu_colabs/JAX_NeurIPS_2020_demo.ipynb
  cloud_tpu_colabs/JAX_demo.ipynb
  cloud_tpu_colabs/Wave_Equation.ipynb
  docs/_tutorials/advanced-autodiff.md
  docs/jep/9407-type-promotion.ipynb
  docs/jep/9407-type-promotion.md
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
  docs/notebooks/Custom_derivative_rules_for_Python_code.ipynb
  docs/notebooks/Custom_derivative_rules_for_Python_code.md
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.ipynb
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.md
  docs/notebooks/How_JAX_primitives_work.ipynb
  docs/notebooks/How_JAX_primitives_work.md
  docs/notebooks/Neural_Network_and_Data_Loading.ipynb
  docs/notebooks/Neural_Network_and_Data_Loading.md
  docs/notebooks/Writing_custom_interpreters_in_Jax.ipynb
  docs/notebooks/Writing_custom_interpreters_in_Jax.md
  docs/notebooks/autodiff_cookbook.ipynb
  docs/notebooks/autodiff_cookbook.md
  docs/notebooks/autodiff_remat.ipynb
  docs/notebooks/autodiff_remat.md
  docs/notebooks/convolutions.ipynb
  docs/notebooks/convolutions.md
  docs/notebooks/external_callbacks.ipynb
  docs/notebooks/external_callbacks.md
  docs/notebooks/neural_network_with_tfds_data.ipynb
  docs/notebooks/neural_network_with_tfds_data.md
  docs/notebooks/vmapped_log_probs.ipynb
  docs/notebooks/vmapped_log_probs.md
  docs/sharded-computation.ipynb
  docs/sharded-computation.md
  jax/_src/core.py
  jax/_src/cudnn/fused_attention_stablehlo.py
  jax/_src/pallas/mosaic/pipeline.py
  jax/_src/test_util.py
  pyproject.toml
  tests/mosaic/gpu_test.py
  tests/notebooks/colab_cpu.ipynb
  tests/pallas/indexing_test.py
Labels: pull ready, CI

#23285 pre-commit: update hooks & pin using hashes
  .pre-commit-config.yaml
  docs/_tutorials/advanced-autodiff.md
  docs/_tutorials/advanced-debugging.md
  docs/_tutorials/external-callbacks.md
  docs/_tutorials/gradient-checkpointing.md
  docs/_tutorials/jax-primitives.md
  docs/_tutorials/jaxpr.md
  docs/autodidax.md
  docs/autodidax.py
  docs/automatic-differentiation.md
  docs/automatic-vectorization.md
  docs/debugging.md
  docs/distributed_data_loading.md
  docs/ffi.md
  docs/jep/9407-type-promotion.md
  docs/jit-compilation.md
  docs/key-concepts.md
  docs/notebooks/Common_Gotchas_in_JAX.md
  docs/notebooks/Custom_derivative_rules_for_Python_code.md
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.md
  docs/notebooks/How_JAX_primitives_work.md
  docs/notebooks/Neural_Network_and_Data_Loading.md
  docs/notebooks/Writing_custom_interpreters_in_Jax.md
  docs/notebooks/autodiff_cookbook.md
  docs/notebooks/autodiff_remat.md
  docs/notebooks/convolutions.md
  docs/notebooks/external_callbacks.md
  docs/notebooks/neural_network_with_tfds_data.md
  docs/notebooks/shard_map.md
  docs/notebooks/thinking_in_jax.md
  docs/notebooks/vmapped_log_probs.md
  docs/pallas/quickstart.md
  docs/pallas/tpu/distributed.md
  docs/pallas/tpu/matmul.md
  docs/pallas/tpu/pipelining.md
  docs/quickstart.md
  docs/random-numbers.md
  docs/sharded-computation.md
  docs/stateful-computations.md
  docs/working-with-pytrees.md
Labels: pull ready

#23290 Update `jnp.fabs` to emulate the behavior of `np.fabs` for `complex` inputs.
  CHANGELOG.md
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#23282 DOC: Improved documentation for jax.numpy.gcd and jax.numpy.lcm
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23287 Divide inputs using BlockSpecs when possible
  jax/experimental/pallas/ops/gpu/attention.py
Labels: pull ready

#23291 DOC: Better docs for `jnp.floor` and `jnp.ceil`
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#22882 Fix check_is_flash_attention
  jax/_src/cudnn/fused_attention_stablehlo.py
  tests/fused_attention_stablehlo_test.py
Labels: pull ready

#23297 refactor lax.loops to avoid importing from jax.numpy
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/other.py
  jax/_src/lax/windowed_reductions.py
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#23193 [Pallas GPU] Disable implicit type conversion during type matching
  jax/_src/pallas/triton/lowering.py
  tests/pallas/ops_test.py
Labels: pull ready

#23321 new README tagline
  README.md
Labels: pull ready

#23326 Fix inaccuracy in jnp.matmul docs
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#23331 Typo in documentation
  jax/_src/numpy/linalg.py
Labels: pull ready

#23336 DOC: Use `:obj:` instead of `:func:` in ufuncs.py
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#23238 fixes cache miss in abstract_eval_shape for bcoo dot general
  jax/experimental/sparse/bcoo.py
Labels: pull ready

#23310 DOC: Better dos for `jax.numpy`: `exp`, `exp2`, and `expm1`
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#23309 DOC: Better docs for `jax.numpy`: `positive`, `negative` and `sign`
  jax/_src/numpy/ufuncs.py
Labels: pull ready

#23304 First pass at ufunc interfaces for several jax.numpy functions
  CHANGELOG.md
  jax/_src/numpy/reductions.py
  jax/_src/numpy/ufunc_api.py
  jax/_src/numpy/ufuncs.py
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_ufuncs_test.py
Labels: pull ready
