Repository jax-ml/jax, pull requests merged in 2024-05, with the labels that each got.

#21017 [omnitracing] pop frames, see if anything downstream breaks
  jax/_src/core.py
Labels: pull ready

#20980 DOC: improve docs for reshape() and ravel()
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: documentation, pull ready

#20847 jax.scipy.stats: manually document functions to avoid scipy import
  docs/jax.scipy.rst
  jax/_src/scipy/stats/_core.py
  jax/_src/scipy/stats/bernoulli.py
  jax/_src/scipy/stats/beta.py
  jax/_src/scipy/stats/betabinom.py
  jax/_src/scipy/stats/binom.py
  jax/_src/scipy/stats/cauchy.py
  jax/_src/scipy/stats/chi2.py
  jax/_src/scipy/stats/dirichlet.py
  jax/_src/scipy/stats/expon.py
  jax/_src/scipy/stats/gamma.py
  jax/_src/scipy/stats/gennorm.py
  jax/_src/scipy/stats/geom.py
  jax/_src/scipy/stats/kde.py
  jax/_src/scipy/stats/laplace.py
  jax/_src/scipy/stats/logistic.py
  jax/_src/scipy/stats/multinomial.py
  jax/_src/scipy/stats/multivariate_normal.py
  jax/_src/scipy/stats/nbinom.py
  jax/_src/scipy/stats/norm.py
  jax/_src/scipy/stats/pareto.py
  jax/_src/scipy/stats/poisson.py
  jax/_src/scipy/stats/t.py
  jax/_src/scipy/stats/truncnorm.py
  jax/_src/scipy/stats/uniform.py
  jax/_src/scipy/stats/vonmises.py
  jax/_src/scipy/stats/wrapcauchy.py
Labels: documentation, pull ready

#20937 Remove extraneous pure_callback_api wrapper
  jax/__init__.py
  jax/_src/callback.py
Labels: pull ready

#21029 Bundle MLIR .pyi files with jaxlib
  jaxlib/mlir/BUILD.bazel
  jaxlib/setup.py
  jaxlib/tools/build_wheel.py
Labels: pull ready

#20992 DOC: Improve docstrings for jax.scipy.signal
  docs/jax.scipy.rst
  jax/_src/scipy/signal.py
Labels: documentation, pull ready

#21018 DOC: Improve docstrings for jax.scipy.linalg
  jax/_src/scipy/linalg.py
Labels: documentation, pull ready

#20936 API deprecation doc: explicitly list some dates
  docs/deprecation.md
Labels: documentation, pull ready

#20971 Add tests for scan with mutable arrays. Move mutable array tests to separate file.
  jax/_src/core.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/state/discharge.py
  jax/_src/util.py
  jax/util.py
  tests/BUILD
  tests/mutable_array_test.py
  tests/state_test.py
Labels: pull ready

#21035 jet_test: float32 matmul precision
  tests/jet_test.py
Labels: pull ready

#21038 DOC: Fix typos and math rendering in `jax.random` docs
  jax/_src/random.py
Labels: pull ready

#21013 Refactor `array_api` namespace, relying more directly on `jax.numpy`
  jax/_src/dtypes.py
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_array_methods.py
  jax/experimental/array_api/_constants.py
  jax/experimental/array_api/_creation_functions.py
  jax/experimental/array_api/_data_type_functions.py
  jax/experimental/array_api/_dtypes.py
  jax/experimental/array_api/_elementwise_functions.py
  jax/experimental/array_api/_fft_functions.py
  jax/experimental/array_api/_indexing_functions.py
  jax/experimental/array_api/_linear_algebra_functions.py
  jax/experimental/array_api/_manipulation_functions.py
  jax/experimental/array_api/_searching_functions.py
  jax/experimental/array_api/_set_functions.py
  jax/experimental/array_api/_sorting_functions.py
  jax/experimental/array_api/_statistical_functions.py
  jax/experimental/array_api/_utility_functions.py
  jax/experimental/array_api/_version.py
  jax/experimental/array_api/fft.py
  jax/experimental/array_api/linalg.py
  jax/experimental/array_api/skips.txt
  pyproject.toml
  tests/array_api_test.py
Labels: pull ready

#21044 [omnitracing] partially un-regress dispatch time
  jax/_src/core.py
Labels: kokoro:force-run, pull ready

#21043 Remove remaining top-level scipy imports
  jax/_src/scipy/signal.py
Labels: pull ready

#21042 DOC: Improve remaining jax.scipy docstrings
  docs/jax.scipy.rst
  jax/_src/scipy/cluster/vq.py
  jax/_src/scipy/integrate.py
  jax/_src/scipy/ndimage.py
  jax/_src/scipy/spatial/transform.py
  tests/scipy_ndimage_test.py
Labels: documentation, pull ready

#21047 Make linkcode_resolve() a bit more robust
  docs/conf.py
Labels: pull ready

#21032 fix vmap-grad-shmap bug with spmd_axis_name
  jax/experimental/shard_map.py
Labels: pull ready

#21055 Recursively pull out __wrapped__ in linkcode_resolve()
  docs/conf.py
Labels: pull ready

#21057 Remove last scipy imports
  jax/_src/scipy/signal.py
  jax/_src/third_party/scipy/interpolate.py
  jax/_src/third_party/scipy/linalg.py
  jax/_src/third_party/scipy/signal_helper.py
Labels: kokoro:force-run, pull ready

#21059 Refactor jax.numpy docstring tests
  tests/lax_numpy_test.py
Labels: pull ready

#21058 jnp.delete: better docs
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#21056 fix vmap-grad-remat-shmap bug with spmd_axis_name
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#21078 jnp.linalg: improve API documentation
  jax/_src/numpy/linalg.py
Labels: documentation, pull ready

#21084 random_lax_test: fix kstest for newer NumPy
  tests/random_lax_test.py
Labels: pull ready

#21087 CI: print numpy/scipy version in upstream job
  .github/workflows/upstream-nightly.yml
Labels: pull ready

#21079 jnp.linalg tensorinv & tensorsolve: improve implementation & docs
  jax/_src/numpy/linalg.py
  jax/_src/third_party/numpy/linalg.py
  jax/numpy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#20842 Refactored common upcast for integral-type accumulators
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/reductions.py
  jax/experimental/array_api/_data_type_functions.py
  tests/lax_numpy_reducers_test.py
Labels: pull ready

#20327 Added code examples for ix_ function with better doc string.
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#21070 update Jax-Metal CI runner with nightly jaxlib config
  .github/workflows/metal_plugin_ci.yml
  tests/lax_metal_test.py
Labels: pull ready

#21081 Compute source maps when pretty-printing jaxprs.
  jax/_src/core.py
  jax/_src/pretty_printer.py
  tests/BUILD
  tests/pretty_printer_test.py
Labels: pull ready

#21077 Fix a typo in jax.jit docstring
  jax/_src/api.py
Labels: pull ready

#21105 Minor doc fix to `jaxpr.rst`
  docs/jaxpr.rst
Labels: pull ready

#21090 Add optional size argument to jnp.compress & jnp.extract
  jax/_src/numpy/array_methods.py
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#21110 CI: fix typo in workflow
  .github/workflows/upstream-nightly.yml
Labels: pull ready

#21111 CHANGELOG: move change from 0.4.27 to 0.4.28
  CHANGELOG.md
Labels: pull ready

#21104 Updated the Pallas GPU lowering to work with older jaxlib versions
  jax/_src/pallas/triton/lowering.py
Labels: pull ready

#21103 Fixed Mosaic GPU build following #21029
  jaxlib/mlir/BUILD.bazel
  jaxlib/mlir/_mlir_libs/BUILD.bazel
  jaxlib/setup.py
  jaxlib/tools/build_wheel.py
Labels: pull ready

#21092 jax.numpy: better docs for matmul-like functions
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/linalg.py
Labels: documentation, pull ready

#21115 Implement jnp.linalg.multi_dot using opt_einsum
  docs/aot.md
  jax/_src/numpy/linalg.py
  jax/_src/third_party/numpy/linalg.py
  jax/numpy/linalg.py
Labels: kokoro:force-run, pull ready

#21129 Removed stale version guards and try/except blocks from Pallas GPU
  jax/_src/pallas/triton/lowering.py
  tests/pallas/export_back_compat_pallas_test.py
  tests/pallas/ops_test.py
  tests/pallas/pallas_test.py
  tests/sparse_nm_test.py
Labels: pull ready

#21128 Enable logging_test on all CI platforms.
  tests/BUILD
Labels: pull ready

#21136 Removed ``get_compute_capability`` from ``jax.experimental.pallas.gpu``
  CHANGELOG.md
  jax/_src/pallas/triton/__init__.py
  jax/_src/pallas/triton/pallas_call_registration.py
  jax/_src/test_util.py
  jax/experimental/pallas/gpu.py
  tests/pallas/export_back_compat_pallas_test.py
  tests/pallas/gpu_attention_test.py
  tests/pallas/ops_test.py
  tests/pallas/pallas_test.py
  tests/sparse_nm_test.py
Labels: pull ready

#21137 Renamed is_device_gpu_at_least to is_cuda_compute_capability_at_least
  jax/_src/test_util.py
  tests/pallas/export_back_compat_pallas_test.py
  tests/pallas/gpu_attention_test.py
  tests/pallas/ops_test.py
  tests/pallas/pallas_test.py
  tests/sparse_nm_test.py
Labels: pull ready

#21139 TST: fix Lpmn test for new scipy
  tests/lax_scipy_test.py
Labels: pull ready

#21146 jnp.linalg.multi_dot: use optimize='auto'
  jax/_src/numpy/linalg.py
Labels: pull ready

#21138 jnp.einsum: improve documentation
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.pyi
Labels: documentation, pull ready

#21106 jnp.linalg: add precision & preferred_element_type to dot-like functions
  jax/_src/numpy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#21135 Prepare 0.4.28 release.
  CHANGELOG.md
  setup.py
Labels: pull ready

#21107 Fix failing smem_hbm_dma test
  tests/pallas/pallas_call_tpu_test.py
Labels: pull ready

#21130 Deprecate `newshape` argument of `jnp.reshape`
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
  jax/experimental/array_api/_manipulation_functions.py
  jax/numpy/__init__.pyi
  tests/random_test.py
Labels: pull ready

#21157 Update line127 error, debugging.md
  docs/debugging.md
Labels: pull ready

#21148 jnp.einsum: support optimize=False, and improve docs for this keyword.
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_einsum_test.py
Labels: pull ready

#21167 jnp.einsum_path: improve docs & annotations
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_einsum_test.py
Labels: documentation, pull ready

#21173 Force float32 matmuls in examples_test.
  examples/examples_test.py
Labels: pull ready

#21174 Disable tests that trigger warning if x64 mode isn't enabled.
  tests/sparse_nm_test.py
Labels: pull ready

#21168 Upgrade JAX Parallelism - Sharded Computation 101 doc
  docs/sharded-computation.ipynb
  docs/sharded-computation.md
Labels: pull ready

#21202 Guarded Pallas GPU import in tests/pallas/pallas_test.py
  tests/pallas/pallas_test.py
Labels: pull ready

#21191 [export] Simplify export internals, prepare for integration with AOT APIs
  jax/_src/interpreters/mlir.py
  jax/experimental/export/_export.py
  jax/experimental/export/_shape_poly.py
  jax/experimental/jax2tf/README.md
  jax/experimental/jax2tf/tests/sharding_test.py
  tests/export_test.py
Labels: pull ready

#21169 Disable bfloat16 on long seq lengths for splash attention kernel test
  tests/pallas/splash_attention_kernel_test.py
Labels: pull ready

#21203 [export] Relax the check that exported modules are used with same number of devices as when exported
  jax/experimental/export/_export.py
  tests/export_test.py
Labels: pull ready

#21048 Better documentation for several jax.numpy functions
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#21119 jnp.linalg.cond: improve implementation & docs
  jax/_src/numpy/linalg.py
  jax/_src/third_party/numpy/linalg.py
  jax/numpy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#21176 shard_map: add API docs
  docs/jax.experimental.rst
  docs/jax.experimental.shard_map.rst
  jax/experimental/shard_map.py
Labels: documentation, pull ready

#21211 Remove type promotion for mixed fp8 matmuls.
  jax/_src/lax/lax.py
  tests/lax_test.py
Labels: pull ready

#21215 Improve docs for jax.numpy set-like operations
  jax/_src/numpy/setops.py
  jax/numpy/__init__.pyi
Labels: kokoro:force-run, pull ready

#21216 Fix PRNGKey handling under jit-of-pmap
  jax/_src/interpreters/pxla.py
  tests/pmap_test.py
Labels: bug, pull ready

#21223 kl_div: fix incorrect formula in doc
  jax/_src/scipy/special.py
Labels: pull ready

#21227 jnp.eye: allow k to be dynamic
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#21226 Rename `rcond/tol` to `rtol` in `linalg.matrix_rank` and `linalg.pinv`
  CHANGELOG.md
  jax/_src/numpy/linalg.py
  jax/experimental/array_api/_linear_algebra_functions.py
Labels: pull ready

#21222 Fix typo in advanced-autodiff.md
  docs/_tutorials/advanced-autodiff.md
Labels: pull ready

#21237 Cleanup token handling during lowering
  jax/_src/interpreters/mlir.py
  jax/experimental/export/_export.py
Labels: pull ready

#21247 Add more informative error message for invalid `unroll` parameter in `lax.scan`
  jax/_src/lax/control_flow/loops.py
  tests/lax_control_flow_test.py
Labels: pull ready

#21251 Fix warning filter in test_pmap_of_prng_key
  tests/pmap_test.py
Labels: pull ready

#21244 Add core count to tpu nightly, fix v5 job
  .github/workflows/cloud-tpu-ci-nightly.yml
Labels: pull ready

#21267 jnp.quantile & friends: properly deprecate interpolation
  jax/_src/numpy/reductions.py
  jax/numpy/__init__.pyi
Labels: pull ready

#21181 Add Distributed data loading in a multi-host/multi-process environment doc
  docs/_static/distributed_data_loading/1.svg
  docs/_static/distributed_data_loading/10.svg
  docs/_static/distributed_data_loading/11.svg
  docs/_static/distributed_data_loading/12.svg
  docs/_static/distributed_data_loading/13.svg
  docs/_static/distributed_data_loading/14.svg
  docs/_static/distributed_data_loading/15.svg
  docs/_static/distributed_data_loading/16.svg
  docs/_static/distributed_data_loading/17.svg
  docs/_static/distributed_data_loading/18.svg
  docs/_static/distributed_data_loading/19.svg
  docs/_static/distributed_data_loading/2.svg
  docs/_static/distributed_data_loading/20.svg
  docs/_static/distributed_data_loading/21.svg
  docs/_static/distributed_data_loading/22.svg
  docs/_static/distributed_data_loading/3.svg
  docs/_static/distributed_data_loading/4.svg
  docs/_static/distributed_data_loading/5.svg
  docs/_static/distributed_data_loading/6.svg
  docs/_static/distributed_data_loading/7.svg
  docs/_static/distributed_data_loading/8.svg
  docs/_static/distributed_data_loading/9.svg
  docs/advanced_guide.rst
  docs/conf.py
  docs/distributed_data_loading.md
Labels: pull ready

#21268 Document jax.tree_util.register_dataclass
  docs/jax.tree_util.rst
  jax/_src/tree_util.py
Labels: pull ready

#21261 Bumped mypy to 1.10.0 and ruff to 0.4.4
  .pre-commit-config.yaml
  jax/_src/api_util.py
  jax/_src/cache_key.py
  jax/_src/compiler.py
  jax/_src/core.py
  jax/_src/debugging.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/lax.py
  jax/_src/lax/parallel.py
  jax/_src/lax/windowed_reductions.py
  jax/_src/maps.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/pallas/mosaic/lowering.py
  jax/_src/prng.py
  jax/_src/scipy/ndimage.py
  jax/_src/scipy/signal.py
  jax/experimental/custom_partitioning.py
  jax/experimental/export/_export.py
  jax/experimental/pallas/ops/tpu/splash_attention/splash_attention_mask_info.py
  jax/experimental/rnn.py
  tests/shard_map_test.py
Labels: pull ready

#21281 Enable remat-scan activation offloading test
  tests/memories_test.py
Labels: pull ready

#21283 Add RegularGridInterpolator to generated API docs
  docs/jax.scipy.rst
Labels: pull ready

#21289 jax.experimental.export: fix stacklevel for warning
  jax/experimental/export/_export.py
Labels: pull ready

#21231 [DOC] Add documentation for jax.experimental.serialize_executable module
  docs/jax.experimental.rst
  docs/jax.experimental.serialize_executable.rst
Labels: pull ready

#21292 [ROCm] Cholesky update kernel fixes for ROCm
  jaxlib/gpu/cholesky_update_kernel.cu.cc
  jaxlib/rocm/BUILD.bazel
Labels: pull ready

#21305 Support scalar boolean indices in arr.at[idx].set(vals)
  jax/_src/ops/scatter.py
  tests/lax_numpy_indexing_test.py
Labels: pull ready

#21318 CI: fix mypy error
  jax/_src/cudnn/fused_attention_stablehlo.py
Labels: pull ready

#21319 [export] Fix device assignment error for grad of exported.
  jax/experimental/export/_export.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/sharding_test.py
  tests/export_test.py
Labels: pull ready

#21258 CompatTest.test_cuda_eigh_cusolver_syev_dtype=f32_syevd: skip for CUDA 12.4+
  tests/export_back_compat_test.py
Labels: pull ready

#21324 Ignore deprecation warnings locally rather than globally
  .github/workflows/ci-build.yaml
  pyproject.toml
  tests/host_callback_test.py
Labels: pull ready

#21315 jax.tree_util: test serialize_using_proto
  tests/tree_util_test.py
Labels: kokoro:force-run, pull ready

#21280 [export] Relax the check that exported modules are used with same number of devices as when exported
  jax/experimental/export/_export.py
  tests/export_test.py
Labels: pull ready

#21357 Add __buffer__ and __releasebuffer__ to the Array type stub.
  jax/_src/basearray.pyi
Labels: kokoro:force-run, pull ready

#21358 Fix mypy errors:
  jax/_src/sharding_impls.py
  jax/experimental/custom_partitioning.py
Labels: kokoro:force-run, pull ready

#20884 Propagate the available axes to the partitioning function
  jax/experimental/custom_partitioning.py
  tests/pjit_test.py
Labels: pull ready

#21278 Order axis names for shard_map residuals
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#21360 Pin matplotlib < 3.9 for Python 3.10 and earlier.
  build/requirements.in
Labels: pull ready

#21366 slightly better error message in splash_attention: bkv_compute % NUM_…
  jax/experimental/pallas/ops/tpu/splash_attention/splash_attention_kernel.py
Labels: pull ready

#21329 Package XLA FFI headers with jaxlib wheel
  jax/BUILD
  jax/__init__.py
  jax/_src/ffi.py
  jax/ffi.py
  jaxlib/setup.py
  jaxlib/tools/BUILD.bazel
  jaxlib/tools/build_wheel.py
  tests/BUILD
  tests/ffi_test.py
Labels: pull ready

#21404 Bumped the minimum ml_dtypes version to 0.4.0
  CHANGELOG.md
  jax/_src/dtypes.py
  jax/_src/public_test_util.py
  jaxlib/setup.py
  setup.py
Labels: pull ready

#21406 Removed mentions of iree from the test suite
  .github/workflows/ci-build.yaml
  jax/_src/test_util.py
  pyproject.toml
  tests/dynamic_api_test.py
  tests/lobpcg_test.py
Labels: kokoro:force-run, pull ready

#21423 Add note to release notes about #21403.
  CHANGELOG.md
Labels: pull ready

#21362 `jnp.var` returns nan if `N-ddof <= 0`
  jax/_src/numpy/reductions.py
  tests/lax_numpy_reducers_test.py
Labels: pull ready

#21414 add pjit input-output forwarding rule
  jax/_src/interpreters/partial_eval.py
  jax/_src/pjit.py
  tests/api_test.py
  tests/dynamic_api_test.py
  tests/jaxpr_util_test.py
  tests/pjit_test.py
  tests/shard_map_test.py
Labels: pull ready

#21433 avoid singleton dim in scan lowering when unroll==1
  jax/_src/lax/control_flow/loops.py
  tests/lax_control_flow_test.py
Labels: pull ready

#21448 [export] Simplify construction of shardings for the VJP
  jax/experimental/export/_export.py
  tests/export_test.py
Labels: kokoro:force-run, pull ready

#21453 Fix type annotation for index-update
  jax/_src/basearray.pyi
Labels: pull ready

#21193 fix: scipy rel_entr edge case
  jax/_src/scipy/special.py
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#21452 jnp.take_along_axis: support fill_value
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#21462 Update quickstart to suggested jax[cuda12] installation
  docs/quickstart.md
Labels: pull ready

#20705 Fixed missing channel handle plumbing
  jax/_src/lax/parallel.py
Labels: pull ready

#21463 Improve documentation for jnp.take & jnp.take_along_axis
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#21457 Improve docstrings for unravel_index & ravel_multi_index
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#21466 CI: remove stale warning filters
  pyproject.toml
Labels: pull ready

#21467 Improve documentation for jnp.bincount
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#21447 Add the function name, the Jaxpr, and lowering platforms to stages.Lowered
  jax/_src/api.py
  jax/_src/interpreters/pxla.py
  jax/_src/maps.py
  jax/_src/pjit.py
  jax/_src/stages.py
  jax/experimental/export/_export.py
Labels: pull ready

#21479 [jax2tf] Fix device assignment error for grad under native serialization
  jax/experimental/export/_export.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/sharding_test.py
Labels: pull ready

#21469 [array api] update test suite to most recent commit
  .github/workflows/jax-array-api.yml
  jax/experimental/array_api/skips.txt
Labels: pull ready

#21468 jnp.searchsorted: support sorter argument
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#21486 JaxTestCase: set default configs during class setup
  jax/_src/test_util.py
Labels: kokoro:force-run, pull ready

#21478 Make attrs work with pytrees
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/pjit.py
  jax/experimental/attrs.py
  tests/attrs_test.py
Labels: pull ready

#21497 logging_test: avoid modifying global config state
  tests/logging_test.py
Labels: pull ready

#21493 Avoid global state in compilation_cache_test
  tests/compilation_cache_test.py
Labels: pull ready

#21487 Improve documentation for jnp.searchsorted
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#21473 Add a link to another page with XLA flags.
  docs/gpu_performance_tips.md
Labels: pull ready

#21481 [shape_poly] Add support for jnp.tril.
  jax/_src/lax/lax.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  tests/shape_poly_test.py
Labels: pull ready

#21442 Added trace alias to jnp.linalg
  docs/jax.numpy.rst
  jax/_src/numpy/linalg.py
  jax/experimental/array_api/linalg.py
  jax/numpy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#21504 [shape_poly] Fixes for approx_top_k when `aggregated_to_topk=True`
  jax/_src/lax/ann.py
  tests/shape_poly_test.py
Labels: pull ready

#21440 Added op name and dtype into testcase name for tests in lax_numpy_operators_test.py
  tests/lax_numpy_operators_test.py
Labels: pull ready

#21071 add error checks for vmap spmd_axis_name
  jax/_src/pjit.py
  jax/experimental/shard_map.py
  tests/pjit_test.py
  tests/shard_map_test.py
Labels: pull ready

#19538 fix error message for vjp arguments
  jax/_src/api.py
  jax/_src/core.py
  tests/api_test.py
Labels: pull ready

#21430 remove is_training from cuDNN SDPA API
  jax/_src/cudnn/fused_attention_stablehlo.py
  tests/fused_attention_stablehlo_test.py
Labels: pull ready

#21544 Fix parenthesis in "Gradients contain NaN where using where"
  docs/faq.rst
Labels: pull ready

#21531 Move `jax.ffi` submodule to `jax.extend.ffi`
  jax/BUILD
  jax/__init__.py
  jax/_src/extend/ffi.py
  jax/extend/BUILD
  jax/extend/__init__.py
  jax/extend/ffi.py
  tests/BUILD
  tests/ffi_test.py
Labels: pull ready

#21563 Remove failing ffi test
  tests/BUILD
  tests/ffi_test.py
Labels: pull ready

#21568 [custom_vjp] allow bwd rule to produce top-level list (not just tuple)
  jax/_src/custom_derivatives.py
  tests/api_test.py
Labels: pull ready
