Repository jax-ml/jax, pull requests merged in 2024-04, with the labels that each got.

#20454 Temporarily disable log1p success unit tests
  tests/lax_test.py
Labels: pull ready

#20474 Change vmap argument from axis to in_axes for Inadvertent transposing of key buffers in 9263-typed-keys.md
  docs/jep/9263-typed-keys.md
Labels: pull ready

#20383 A few more comments about how the deprecations work
  jax/_src/deprecations.py
Labels: pull ready

#20514 [callback] Improve caching effectiveness in presence of callbacks.
  jax/_src/callback.py
  tests/python_callback_test.py
Labels: pull ready

#20543 test: skip complex geomspace test under numpy 2.0
  tests/lax_numpy_test.py
Labels: pull ready

#20542 test: fix solve test for NumPy 2.0
  tests/linalg_test.py
Labels: pull ready

#20536 jnp.broadcast_to: better error for invalid shape
  jax/_src/numpy/util.py
  tests/lax_numpy_test.py
Labels: better_errors, pull ready

#20548 jnp.floor_div: lower directly to div for unsigned int
  jax/_src/numpy/ufuncs.py
Labels: kokoro:force-run, pull ready

#20552 jnp.geomspace: make complex behavior consistent with NumPy 2.0
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#20534 [callback] Allow external callbacks to return 64-bit values in 32-bit mode
  jax/_src/callback.py
  jax/_src/interpreters/mlir.py
  tests/python_callback_test.py
Labels: pull ready

#20560 Workaround mpmath bug in log1p at complex infinities
  jax/_src/test_util.py
  tests/lax_test.py
Labels: pull ready

#20562 jax.distributed.initialize: specify bind address.
  docs/multi_process.md
  jax/_src/distributed.py
Labels: pull ready

#20571 Prepare for 0.4.26 release.
  CHANGELOG.md
  setup.py
Labels: pull ready

#20569 test: work around issue with kstest in scipy>1.12
  tests/random_lax_test.py
Labels: pull ready

#20561 Fixed a few typos in the matmul example in "Pallas Design"
  docs/pallas/design.md
Labels: pull ready

#20573 small simplification to asymptotic complexity of make_jaxpr_effects
  jax/_src/interpreters/partial_eval.py
Labels: pull ready

#20558 Add jax.nn.mish.
  docs/jax.nn.rst
  jax/_src/nn/functions.py
  jax/nn/__init__.py
  tests/nn_test.py
Labels: pull ready

#20572 [mutable-arrays] enable refs without cps, and not just at top level
  jax/_src/core.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/interpreters/pxla.py
  jax/_src/state/discharge.py
  tests/state_test.py
Labels: pull ready

#20062 Add environment variable to remove debug information in MLIR module dump
  jax/_src/interpreters/mlir.py
  tests/api_test.py
Labels: pull ready

#20588 Call cuInit before querying compute capability
  jaxlib/cuda/versions_helpers.cc
Labels: pull ready

#20593 Restore upstream-nightly github action
  .github/workflows/upstream-nightly.yml
Labels: pull ready

#20175 Add support for `device` and `copy` kwargs in `from_dlpack` to match Array API
  jax/_src/dlpack.py
  jax/_src/numpy/lax_numpy.py
  jax/experimental/array_api/_creation_functions.py
  jax/numpy/__init__.pyi
  tests/array_interoperability_test.py
Labels: pull ready

#20550 Update `jnp.clip` to Array API 2023 standard and introduces `jax.experimental.array_api.clip`
  CHANGELOG.md
  jax/_src/numpy/array_methods.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/scipy/special.py
  jax/_src/typing.py
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_elementwise_functions.py
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
  jax/experimental/ode.py
  jax/numpy/__init__.pyi
  tests/array_api_test.py
  tests/lax_metal_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#20516 [callback] Add a flag to implement host_callback in terms of io_callback
  CHANGELOG.md
  jax/BUILD
  jax/experimental/host_callback.py
  tests/host_callback_test.py
  tests/host_callback_to_tf_test.py
  tests/python_callback_test.py
Labels: pull ready

#20599 add a temporary config option to disable custom_vjp shape checking
  jax/_src/config.py
  jax/_src/custom_derivatives.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#20266 add a jax.Array analog that can contain extended dtypes
  jax/BUILD
  jax/_src/earray.py
  jax/experimental/__init__.py
  tests/dtypes_test.py
Labels: pull ready

#20380 [NVIDIA] Support BNTH input formats for the fused attention
  jax/_src/cudnn/fused_attention_stablehlo.py
  tests/fused_attention_stablehlo_test.py
Labels: pull ready

#20623 Updated ubuntu os version in `readthedocs.yml` file to the latest recommended version
  .readthedocs.yml
Labels: pull ready

#20622 Updated all the pre-commit hooks versions
  .pre-commit-config.yaml
  docs/autodidax.md
  docs/autodidax.py
  docs/jax-101/01-jax-basics.md
  docs/jax-101/02-jitting.md
  docs/jax-101/03-vectorization.md
  docs/jax-101/04-advanced-autodiff.md
  docs/jax-101/05-random-numbers.md
  docs/jax-101/05.1-pytrees.md
  docs/jax-101/06-parallelism.md
  docs/jax-101/07-state.md
  docs/jep/9407-type-promotion.md
  docs/notebooks/Common_Gotchas_in_JAX.md
  docs/notebooks/Custom_derivative_rules_for_Python_code.md
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.md
  docs/notebooks/How_JAX_primitives_work.md
  docs/notebooks/Neural_Network_and_Data_Loading.md
  docs/notebooks/Writing_custom_interpreters_in_Jax.md
  docs/notebooks/autodiff_cookbook.md
  docs/notebooks/autodiff_remat.md
  docs/notebooks/convolutions.md
  docs/notebooks/external_callbacks.md
  docs/notebooks/neural_network_with_tfds_data.md
  docs/notebooks/quickstart.md
  docs/notebooks/shard_map.md
  docs/notebooks/thinking_in_jax.md
  docs/notebooks/vmapped_log_probs.md
  docs/notebooks/xmap_tutorial.md
  docs/pallas/quickstart.md
  docs/pallas/tpu/pipelining.md
  docs/tutorials/advanced-autodiff.md
  docs/tutorials/advanced-debugging.md
  docs/tutorials/automatic-differentiation.md
  docs/tutorials/automatic-vectorization.md
  docs/tutorials/debugging.md
  docs/tutorials/external-callbacks.md
  docs/tutorials/gradient-checkpointing.md
  docs/tutorials/jax-primitives.md
  docs/tutorials/jaxpr.md
  docs/tutorials/jit-compilation.md
  docs/tutorials/key-concepts.md
  docs/tutorials/quickstart.md
  docs/tutorials/random-numbers.md
  docs/tutorials/thinking-in-jax.md
  docs/tutorials/working-with-pytrees.md
Labels: pull ready

#20528 Update jax.scipy.special.ndtri to return NaN for the values outside of the range [0, 1]
  jax/_src/scipy/special.py
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#20179 Custom gpu ops partitioning
  docs/Custom_Operation_for_GPUs.md
  docs/Custom_Operation_for_GPUs.py
  docs/build_custom_gpu.sh
  docs/gpu_ops/gpu_ops.cpp
  docs/gpu_ops/kernel_helpers.h
  docs/gpu_ops/kernels.h
  docs/gpu_ops/pybind11_kernel_helpers.h
  docs/gpu_ops/rms_norm_kernels.cu
Labels: pull ready

#20642 CI: pin actions dependencies to most recent release
  .github/workflows/upstream-nightly.yml
Labels: pull ready

#20589 BUG: fix sign of beta()
  jax/_src/scipy/special.py
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#20578 Add where argument to logsumexp.
  jax/_src/ops/special.py
  tests/lax_scipy_test.py
Labels: pull ready

#20629 fix: Fixed raising `TypeError` instead or `ValueError` for invalid type
  jax/_src/api.py
  jax/_src/checkify.py
  jax/_src/config.py
  jax/_src/layout.py
  jax/experimental/sparse/bcoo.py
Labels: pull ready

#20648 CI: avoid deprecated ruff configurations
  pyproject.toml
Labels: pull ready

#20643 Let initial=-jnp.inf by default for nn.softmax and nn.log_softmax.
  jax/_src/nn/functions.py
Labels: pull ready

#20649 Fix typos in comments
  jax/_src/core.py
Labels: pull ready

#20646 [ROCm]: fix tsl path
  jaxlib/rocm/BUILD.bazel
Labels: pull ready

#20637 [array api] allow Python scalar arguments to functions
  jax/experimental/array_api/_data_type_functions.py
  jax/experimental/array_api/_elementwise_functions.py
Labels: pull ready

#20665 test: fix testClipStaticBounds complex warning
  tests/lax_numpy_test.py
Labels: pull ready

#20666 better unsupported indexing handling in lax_numpy.py
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#20644 Make complex_arr.astype(bool) follow NumPy's semantics
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#20673 Clean up sparse test run conditions
  jax/experimental/sparse/test_util.py
  tests/sparse_bcoo_bcsr_test.py
  tests/sparse_test.py
Labels: pull ready

#20685 _version_from_git_tree: avoid git describe
  jax/version.py
Labels: pull ready

#20688 Workaround mpmath 1.3 bugs in tan and tanh evaluation at infinities. Restore log1p and arctanh success tests.
  jax/_src/test_util.py
  tests/lax_test.py
Labels: pull ready

#20709 DOC: Fix :ref: format
  docs/glossary.rst
Labels: pull ready

#20687 Fix Typos in docs
  docs/developer.md
  docs/faq.rst
  docs/gpu_performance_tips.md
  docs/jax-101/06-parallelism.ipynb
  docs/jax-101/06-parallelism.md
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
Labels: pull ready

#20713 DOC: update Colab mention in distributed arrays doc
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.ipynb
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.md
Labels: pull ready

#20198 Add support for `max_version, dl_device, copy` kwargs in `__dlpack__` to match Array API
  jax/_src/array.py
  jax/_src/dlpack.py
  jax/_src/typing.py
  jax/experimental/jax2tf/call_tf.py
  tests/array_interoperability_test.py
Labels: pull ready

#20294 Add __array_namespace_info__ and corresponding utilities
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_utility_functions.py
  tests/BUILD
  tests/array_api_test.py
Labels: pull ready

#20716 [key reuse] handle reuse of closed-over constants
  jax/_src/pjit.py
  jax/experimental/key_reuse/_core.py
  tests/key_reuse_test.py
Labels: pull ready

#20692 [key reuse] refactor & unify key reuse rule registration
  jax/experimental/key_reuse/_core.py
Labels: pull ready

#20723 alias jax.sharding.NamedSharding -> jax.NamedSharding
  jax/__init__.py
  tests/api_test.py
Labels: pull ready

#20712 [key reuse] call key reuse logic directly in dispatch
  jax/_src/core.py
  jax/experimental/key_reuse/_core.py
Labels: pull ready

#20690 softmax: deprecate initial argument & always set to -inf internally
  CHANGELOG.md
  jax/_src/nn/functions.py
  tests/nn_test.py
Labels: pull ready

#20725 [callbacks] io_callback batching rule accidentally called pure_callback
  jax/_src/callback.py
  tests/python_callback_test.py
Labels: kokoro:force-run, pull ready

#20603 Doc: Fix Typos
  CHANGELOG.md
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/solves.py
  jax/_src/lax/slicing.py
Labels: pull ready

#20730 Minor typo fix for `jax.lax.psum` docstring
  jax/_src/lax/parallel.py
Labels: pull ready

#19604 Updated FAQ to include section on CUDA library initialization failures
  docs/faq.rst
Labels: pull ready

#19605 Improves warning message for occasional CUDA memory error
  jax/_src/xla_bridge.py
Labels: pull ready

#20726 [callbacks] io_callback while_loop batching rule fix ~(^.~!)z
  jax/_src/lax/control_flow/loops.py
  tests/python_callback_test.py
Labels: pull ready

#20727 simple fix to make_jaxpr docstring
  jax/_src/api.py
Labels: documentation, pull ready

#20595 Add a zeros rule for mutable arrays and test it using a custom vjp.
  jax/_src/lax/lax.py
  jax/_src/pjit.py
  tests/state_test.py
Labels: pull ready

#20736 DOC: document strict dtype promotion mode
  docs/type_promotion.rst
Labels: documentation, pull ready

#20217 add and populate `jax.extend.core.primitives`
  jax/extend/BUILD
  jax/extend/core/__init__.py
  jax/extend/core/primitives.py
Labels: pull ready

#20586 Bumped the minimum jaxlib to 0.4.23
  CHANGELOG.md
  jax/_src/dispatch.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/fft.py
  jax/_src/xla_bridge.py
  jax/version.py
  tests/api_test.py
  tests/array_interoperability_test.py
  tests/export_back_compat_test.py
  tests/layout_test.py
  tests/linalg_test.py
  tests/pjit_test.py
Labels: pull ready

#20762 DOC: Correct a name in the ScatterDimensionNumbers docstring
  jax/_src/lax/slicing.py
Labels: pull ready

#20753 Expose existing functions in array API namespace
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_elementwise_functions.py
  jax/experimental/array_api/_manipulation_functions.py
  jax/experimental/array_api/_searching_functions.py
  tests/array_api_test.py
Labels: pull ready

#20703 CI: run the metal CI nightly & on PRs touching the config file
  .github/workflows/metal_plugin_ci.yml
  tests/lax_metal_test.py
Labels: pull ready

#20754 Fixed hypot bug on nan/inf pairings, began deprecation of non-real values
  CHANGELOG.md
  jax/_src/numpy/ufuncs.py
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_elementwise_functions.py
  tests/array_api_test.py
  tests/lax_numpy_operators_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#20734 Install fork() warning during backend initialization, rather than jax…
  jax/_src/xla_bridge.py
Labels: pull ready

#20755 Add new unstack function to numpy/array_api namespaces
  CHANGELOG.md
  docs/jax.numpy.rst
  jax/_src/numpy/lax_numpy.py
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_manipulation_functions.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/array_api_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#20771 DOC: Fix docstring typos in `jax._src.scipy.special.py`
  jax/_src/scipy/special.py
Labels: pull ready

#20657 fix: Made the `error messages` when raising `TypeError` better
  jax/_src/config.py
Labels: pull ready

#20773 [array api] update to latest test repo commit
  .github/workflows/jax-array-api.yml
  jax/experimental/array_api/skips.txt
Labels: pull ready

#20779 Add sharding 101 doc
  docs/conf.py
  docs/tutorials/index.rst
  docs/tutorials/key-concepts.md
  docs/tutorials/sharded-computation.ipynb
  docs/tutorials/sharded-computation.md
  docs/tutorials/single-host-sharding.md
  docs/tutorials/thinking-in-jax.md
Labels: documentation, pull ready

#20778 Import web_pdb lazily
  jax/_src/debugger/web_debugger.py
Labels: pull ready

#20756 Add new cumulative_sum function to numpy and array_api namespaces
  CHANGELOG.md
  docs/jax.numpy.rst
  jax/_src/numpy/reductions.py
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_statistical_functions.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/array_api_test.py
  tests/lax_numpy_reducers_test.py
Labels: pull ready

#20787 Import rich lazily
  jax/_src/debugging.py
Labels: pull ready

#20784 DOC: update installation guide
  docs/installation.md
  docs/tutorials/index.rst
  docs/tutorials/installation.md
Labels: documentation, pull ready

#20794 Pin sphinx version to avoid error in 7.3.0
  docs/requirements.txt
Labels: pull ready

#20732 DOC: add stateful computation doc
  docs/tutorials/stateful-computations.md
Labels: pull ready

#20792 DOC: fix Mesh construction in sharding doc
  docs/tutorials/sharded-computation.ipynb
  docs/tutorials/sharded-computation.md
Labels: kokoro:force-run, pull ready

#20800 DOC: pin sphinx to >=7.3.2
  docs/requirements.txt
Labels: pull ready

#20768 Add more imports to jax.extend.core
  jax/extend/core/__init__.py
Labels: pull ready

#20806 DOC: one last readthrough of the new 101 tutorials
  docs/tutorials/advanced-autodiff.md
  docs/tutorials/automatic-differentiation.md
  docs/tutorials/automatic-vectorization.md
  docs/tutorials/debugging.md
  docs/tutorials/jax-primitives.md
  docs/tutorials/jaxpr.md
  docs/tutorials/jit-compilation.md
  docs/tutorials/key-concepts.md
  docs/tutorials/quickstart.md
  docs/tutorials/working-with-pytrees.md
Labels: pull ready

#20537 README: improve TPU accuracy discussion
  README.md
Labels: pull ready

#20816 Added int4 and uint4 to dtype-specific tests
  jax/_src/test_util.py
  jax/tools/jax_to_ir.py
  tests/dtypes_test.py
  tests/jax_to_ir_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#20823 Remove outdated section in cloud_tpu_colabs README
  cloud_tpu_colabs/README.md
Labels: pull ready

#20825 Add jax.scipy.special.gammasgn
  docs/jax.scipy.rst
  jax/_src/scipy/special.py
  jax/scipy/special.py
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#20836 quickstart tweaks (from https://github.com/google/jax/pull/20819)
  docs/tutorials/quickstart.md
Labels: pull ready

#20840 Update outdated comment Pmap_Cookbook
  cloud_tpu_colabs/Pmap_Cookbook.ipynb
Labels: pull ready

#20870 redundant phrase 'every time' removed
  jax/_src/config.py
Labels: pull ready

#20849 tweak jit docstring
  jax/_src/api.py
Labels: kokoro:force-run, pull ready

#20317 [XLA:Python] Add a flag for creating the mpi collectives
  CHANGELOG.md
  jax/_src/xla_bridge.py
Labels: pull ready

#20195 Add support for `copy` kwarg in `astype` to match Array API
  CHANGELOG.md
  jax/_src/numpy/array_methods.py
  jax/_src/numpy/lax_numpy.py
  jax/experimental/array_api/_data_type_functions.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_reducers_test.py
  tests/lax_numpy_test.py
Labels: pull ready

#20891 Fix `jax.scipy.stats.poisson.logpmf` to emulate `scipy.stats.poisson.logpmf` for non-integer values of `k`
  jax/_src/scipy/stats/poisson.py
  tests/scipy_stats_test.py
Labels: pull ready

#20897 DOC: respond to mattjj comments
  docs/tutorials/automatic-differentiation.md
  docs/tutorials/jit-compilation.md
  docs/tutorials/key-concepts.md
Labels: pull ready

#20885 Fix `jax.scipy.stats.beta.logpdf` to emulate `scipy.stats.beta.logpdf`
  jax/_src/scipy/stats/beta.py
  tests/scipy_stats_test.py
Labels: pull ready

#20901 Let xs=None by default in lax.scan.
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/lax/control_flow/loops.py
  tests/lax_control_flow_test.py
Labels: pull ready

#20896 Workaround mpmath 1.3 issues in asin and asinh evaluation at infinities and on branch cuts
  jax/_src/test_util.py
Labels: pull ready

#20917 pallas flash attention: explicitly use dtype
  jax/experimental/pallas/ops/tpu/flash_attention.py
Labels: pull ready

#20858 DOC: Fix doc typos
  CHANGELOG.md
  jax/_src/debugger/core.py
  jax/_src/distributed.py
  jax/_src/dlpack.py
  jax/_src/nn/functions.py
  jax/_src/profiler.py
Labels: pull ready

#19868 [jaxpr.rst] Remove extraneous 'let' in Jaxpr grammar.
  docs/jaxpr.rst
Labels: pull ready

#20954 Expose tile function in array_api namespace
  jax/experimental/array_api/__init__.py
  jax/experimental/array_api/_manipulation_functions.py
  tests/array_api_test.py
Labels: pull ready

#20959 set tensorstore settings in cloudtpu to make serialization more robust
  jax/_src/cloud_tpu_init.py
  jax/experimental/array_serialization/serialization.py
Labels: pull ready

#20941 DOC: improve documentation of where, nonzero, and related functions
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: documentation, pull ready

#20977 Fix pytest failures from compilation cache test.
  pyproject.toml
Labels: pull ready

#20957 DOC: improve docs of transpose & matrix_transpose
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: documentation, pull ready

#20982 Cache (most) calls to dtypes.issubdtype
  jax/_src/dtypes.py
Labels: performance, pull ready

#20976 Fix mlir.merge_mlir_modules to properly remember the inlined symbols
  jax/_src/interpreters/mlir.py
  jax/experimental/export/_export.py
  jax/experimental/jax2tf/call_tf.py
  tests/export_test.py
Labels: pull ready

#20799 jax.scipy.fft: manually document functions to avoid scipy import
  jax/_src/scipy/fft.py
Labels: documentation, pull ready

#20822 jax.scipy.special: manually document functions to avoid scipy import
  docs/conf.py
  jax/_src/ops/special.py
  jax/_src/scipy/special.py
Labels: documentation, pull ready

#20923 Workaround mpmath 1.3 issues in asinh evaluation at infinities
  jax/_src/test_util.py
Labels: pull ready

#20875 DOC: Remove dependency on sphinx_autodoc_typehints
  .readthedocs.yml
  docs/conf.py
  docs/requirements.txt
Labels: documentation, pull ready

#20985 test: fix reshape signature test for NumPy 2.1
  tests/lax_numpy_test.py
Labels: pull ready

#21001 Fix warnings in CI from compilation_cache_test.
  tests/compilation_cache_test.py
Labels: pull ready

#21016 skip pallas/gmm_test.py if we don't have hypothesis
  tests/pallas/gmm_test.py
Labels: pull ready

#20961 DOC: link docstrings to github source
  docs/conf.py
Labels: documentation, pull ready
