Repository jax-ml/jax, pull requests merged in 2024-02, with the labels that each got.

#19580 jax.make_array_from_callback: better errors in traced context
  jax/_src/array.py
  tests/array_test.py
Labels: better_errors, pull ready

#19621 BUG: fix cholesky upper implementation
  jax/_src/numpy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#19622 DOC: clarify lax.rng_uniform behavior for b<=a
  jax/_src/lax/lax.py
Labels: pull ready

#19662 jax 0.4.24 release take 2: update libtpu version
  setup.py
Labels: pull ready

#19665 document that under disable_jit, individual primitives are still compiled
  jax/_src/api.py
Labels: documentation, pull ready

#19599 [ROCm]: Add ROCm command buffer support for triton kernel
  jaxlib/gpu/triton_kernels.cc
  jaxlib/gpu/vendor.h
Labels: pull ready

#19629 [key reuse] fix pjit false positive
  jax/experimental/key_reuse/_forwarding.py
  jax/experimental/key_reuse/_simple.py
  tests/key_reuse_test.py
Labels: pull ready

#19634 [key reuse] fix scan single-key consumption issue
  jax/experimental/key_reuse/_forwarding.py
  jax/experimental/key_reuse/_simple.py
  tests/key_reuse_test.py
Labels: pull ready

#19667 Improve repr for empty jax.Array
  jax/_src/array.py
  tests/array_test.py
Labels: pull ready

#19668 [array API] update to recent array API test version
  .github/workflows/jax-array-api.yml
  jax/experimental/array_api/skips.txt
Labels: pull ready

#19601 [shmap] Support multiple axes for standard collectives in shard_map
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: pull ready

#19675 jaxlib/triton: ensure python 3.9 compatibility
  jaxlib/triton/dialect.py
Labels: pull ready

#19674 jnp.linalg.solve: deprecate batched 1D solves when b.ndim > 1
  CHANGELOG.md
  jax/_src/numpy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#19681 Update version numbers post-0.4.24 release
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: kokoro:force-run, pull ready

#19683 [shape_poly] Change the representation of symbolic dimension expressions
  jax/experimental/export/_shape_poly.py
  jax/experimental/export/_shape_poly_decision.py
Labels: pull ready

#19233 Add CUDA Array Interface consumer support
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
  tests/array_interoperability_test.py
Labels: cla: yes, pull ready, NVIDIA GPU

#19698 linalg_test: ignore jnp.linalg.solve FutureWarning
  tests/linalg_test.py
Labels: pull ready

#19703 Make test of jnp.unique compatible with NumPy 2.0
  tests/lax_numpy_test.py
Labels: pull ready

#19701 test_util: avoid overflow errors in NumPy 2.0
  jax/_src/test_util.py
Labels: pull ready

#19721 update sparse _reshape docstring to match jax.Array.reshape
  jax/experimental/sparse/transform.py
Labels: pull ready

#19723 Fix jax 0.4.24 changelog
  CHANGELOG.md
Labels: pull ready

#19577 [key reuse]: handle remat
  jax/experimental/key_reuse/_forwarding.py
  jax/experimental/key_reuse/_simple.py
  tests/key_reuse_test.py
Labels: pull ready

#19722 jax.numpy: implement scalar boolean indexing
  CHANGELOG.md
  jax/_src/array.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/ops/scatter.py
  jax/experimental/array_api/skips.txt
  tests/lax_numpy_indexing_test.py
Labels: enhancement, pull ready

#19737 Register jax.Array device method deprecation
  jax/_src/array.py
  tests/random_test.py
Labels: pull ready

#19740 testUnique: avoid invalid fill_value
  tests/lax_numpy_test.py
Labels: pull ready

#19739 streamline jnp.atleast_nd implementations
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#19743 [shape_poly] Performance improvements for symbolic dimension manipulations (step 1).
  jax/experimental/export/_shape_poly.py
  jax/experimental/export/_shape_poly_decision.py
  tests/shape_poly_test.py
Labels: pull ready

#19766 Add JAX mesh_utils docs
  docs/jax.experimental.mesh_utils.rst
  docs/jax.experimental.rst
Labels: pull ready

#19588 Add jax.tree module
  CHANGELOG.md
  docs/jax.rst
  docs/jax.tree.rst
  jax/BUILD
  jax/__init__.py
  jax/_src/tree.py
  jax/_src/tree_util.py
  jax/tree.py
  tests/tree_util_test.py
Labels: pull ready

#19788 Increase atol for Pallas fused attention test from 0.13 to 0.14
  tests/pallas/pallas_test.py
Labels: pull ready

#19790 Streamline github issue template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: pull ready

#19791 jax.print_environment_info: add platform.uname()
  jax/_src/environment_info.py
Labels: pull ready

#19794 [attrs] add a jvp function with attrs support
  jax/_src/interpreters/ad.py
  jax/experimental/attrs.py
  tests/attrs_test.py
Labels: pull ready

#19796 [attrs] allow passing a jax-attrs object to jit functions
  jax/_src/api_util.py
  jax/_src/pjit.py
  jax/experimental/attrs.py
  tests/attrs_test.py
Labels: pull ready

#19777 [shape_poly] Improve the handling of equality external constraints.
  jax/experimental/export/_shape_poly.py
  tests/shape_poly_test.py
Labels: pull ready

#19813 Define reuse_key primitive in jax._src.prng
  docs/jax.experimental.key_reuse.rst
  jax/_src/lax/control_flow/loops.py
  jax/_src/prng.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/key_reuse/__init__.py
  jax/experimental/key_reuse/_common.py
  jax/experimental/key_reuse/_forwarding.py
  jax/experimental/key_reuse/_simple.py
  tests/key_reuse_test.py
Labels: pull ready

#19780 Fix jvp of convert_element_type for integer types
  jax/_src/lax/lax.py
  tests/api_test.py
Labels: pull ready

#19776 [shape_poly] Add support for jnp.split
  jax/_src/core.py
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
  tests/shape_poly_test.py
Labels: pull ready

#19804 [shape_poly] Performance improvements for symbolic dimension manipulations (step 2)
  jax/experimental/export/_shape_poly.py
  jax/experimental/export/_shape_poly_decision.py
  tests/shape_poly_test.py
Labels: pull ready

#19831 [key reuse] remove alternate simple implementation
  jax/experimental/key_reuse/_common.py
  jax/experimental/key_reuse/_core.py
  jax/experimental/key_reuse/_forwarding.py
  jax/experimental/key_reuse/_simple.py
  tests/key_reuse_test.py
Labels: pull ready

#19837 [key reuse] simplify key reuse logic through context-free jaxpr evaluation
  jax/experimental/key_reuse/_core.py
  tests/key_reuse_test.py
Labels: kokoro:force-run, pull ready

#19819 [scan] don't traverse body jaxpr in lowering
  jax/_src/core.py
  jax/_src/interpreters/mlir.py
  jax/_src/lax/control_flow/loops.py
  jax/experimental/jax2tf/jax2tf.py
Labels: pull ready

#19847 [adx3] Add string labels for second-order primitive subjaxprs.
  docs/adx3/core.py
  docs/adx3/lax.py
Labels: kokoro:force-run, pull ready

#19845 [shape_poly] Performance improvements for symbolic dimension manipulations (step 3)
  jax/experimental/export/_shape_poly.py
  jax/experimental/export/_shape_poly_decision.py
  tests/shape_poly_test.py
Labels: pull ready

#19832 tree_transpose: optionally infer inner_treedef
  CHANGELOG.md
  jax/_src/tree_util.py
  tests/tree_util_test.py
Labels: pull ready

#19842 fix typo in docs
  docs/faq.rst
Labels: pull ready

#19871 [shape_poly] Fix handling of stride_in_dim with symbolic stride.
  jax/_src/lax/slicing.py
  jax/experimental/export/_shape_poly_decision.py
  tests/shape_poly_test.py
Labels: pull ready

#19288 Prevent silent overflow in lapack worker size calculations.
  jaxlib/cpu/BUILD
  jaxlib/cpu/lapack_kernels.cc
Labels: bug, pull ready, CPU

#19859 [array api] update to latest test suite version
  .github/workflows/jax-array-api.yml
Labels: pull ready

#19901 Fix test flake which occurred due to a spurious cache misses.
  jax/_src/config.py
  tests/pmap_test.py
Labels: pull ready

#19907 [shape_poly] Cleaning up naming of terms and factors
  jax/_src/core.py
  jax/_src/interpreters/mlir.py
  jax/experimental/export/_shape_poly.py
  jax/experimental/export/_shape_poly_decision.py
  tests/shape_poly_test.py
Labels: pull ready

#19909 [custom_vjp] handle Nones in subtrees returned by bwd rule
  jax/_src/custom_derivatives.py
  tests/api_test.py
Labels: pull ready

#19918 Fixing tiny typo in jax.numpy type definitions
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.pyi
Labels: pull ready

#19933 Mention re-instated xla APIs in the CHANGELOG
  CHANGELOG.md
Labels: pull ready

#19932 Better error message for XLA negative axes
  jax/_src/lax/control_flow/loops.py
Labels: pull ready

#19499 Fix type annotation for `array_api.broadcast_to`
  jax/experimental/array_api/_manipulation_functions.py
Labels: pull ready

#19936 Promote `isclose` arguments to inexact dtype (fixes #19935).
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#19960 [attrs] add linearize and vjp support
  jax/_src/api.py
  jax/experimental/attrs.py
  tests/attrs_test.py
Labels: pull ready

#19964 Bump nanobind version to v1.9.2.
  third_party/nanobind/workspace.bzl
Labels: pull ready

#19970 [xmap-removal] remove reduce_axes from grad / vjp / backward_pass
  jax/_src/ad_checkpoint.py
  jax/_src/api.py
  jax/_src/custom_derivatives.py
  jax/_src/interpreters/ad.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/maps.py
  jax/_src/pallas/primitives.py
  jax/_src/pjit.py
  jax/_src/state/discharge.py
  jax/experimental/attrs.py
  jax/experimental/shard_map.py
  jax/interpreters/ad.py
  tests/api_test.py
  tests/pallas/splash_attention_kernel_test.py
  tests/xmap_test.py
Labels: pull ready

#19911 fix sdpa unit test with mask
  tests/fused_attention_stablehlo_test.py
Labels: pull ready

#19981 DOC: mention a few recommended tools
  docs/index.rst
Labels: pull ready

#19823 Fix complex sin and cos on inputs with small absolute value or large pure imaginary part
  jax/_src/lax/lax.py
  jax/_src/test_util.py
  tests/filecheck/shapes.filecheck.py
  tests/lax_test.py
Labels: pull ready

#19958 Cleanup: access tree utilities via jax.tree.*
  tests/api_test.py
  tests/core_test.py
  tests/custom_linear_solve_test.py
  tests/custom_root_test.py
  tests/export_harnesses_multi_platform_test.py
  tests/export_test.py
  tests/filecheck/jax_filecheck_helpers.py
  tests/host_callback_test.py
  tests/infeed_test.py
  tests/jet_test.py
  tests/lax_control_flow_test.py
  tests/lax_numpy_test.py
  tests/lax_scipy_test.py
  tests/lax_test.py
  tests/ode_test.py
  tests/optimizers_test.py
  tests/pallas/splash_attention_kernel_test.py
  tests/pjit_test.py
  tests/pmap_test.py
  tests/random_test.py
  tests/scipy_stats_test.py
  tests/shape_poly_test.py
  tests/shard_map_test.py
  tests/sparse_test.py
Labels: pull ready

#19986 Fix bug where axis size selected incorrectly in pure_callback vmap rule
  jax/_src/callback.py
  tests/python_callback_test.py
Labels: pull ready

#20017 simplify code generated by select_n transpose with bool `which`
  jax/_src/lax/lax.py
  tests/lax_numpy_test.py
Labels: kokoro:force-run, pull ready

#20001 [Pallas TPU] Add Pipelining and BlockSpecs documentation for Pallas TPU
  docs/conf.py
  docs/pallas/index.rst
  docs/pallas/tpu/details.rst
  docs/pallas/tpu/index.rst
  docs/pallas/tpu/pipelining.ipynb
  docs/pallas/tpu/pipelining.md
  docs/user_guides.rst
Labels: pull ready

#20020 Add int8 as an allowed constant type in Pallas.
  jax/_src/pallas/mosaic/lowering.py
Labels: pull ready

#20000 Finalize deprecation of non-array arguments to array_equal/array_equiv
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#20025 [key reuse] avoid inadvertently duplicated test cases
  tests/key_reuse_test.py
Labels: pull ready
