Repository jax-ml/jax, pull requests merged in 2025-07, with the labels that each got.

#29864 Correct documentation in `gpu_memory_allocation.rst`
  docs/gpu_memory_allocation.rst
Labels: kokoro:force-run, pull ready

#29898 simplify our jaxpr builder not to hold strong refs to tracers
  jax/_src/interpreters/partial_eval.py
Labels: kokoro:force-run, pull ready

#29857 Use more numerically stable computation for `jax.random.logistic`.
  jax/_src/random.py
Labels: kokoro:force-run, pull ready

#29433 Disallow aliased mutable array arguments to vmap.
  jax/_src/api.py
  tests/mutable_array_test.py
Labels: kokoro:force-run, pull ready

#29930 Document out_sharding in jax.numpy functions
  jax/_src/numpy/array_creation.py
Labels: documentation, kokoro:force-run, pull ready

#29943 [dep] remove some finalized deprecations in jax.core
  jax/core.py
Labels: kokoro:force-run, pull ready

#28988 [JAX][DOC] Add optimizer state offloading doc
  docs/notebooks/host-offloading.ipynb
  docs/notebooks/host-offloading.md
Labels: kokoro:force-run, pull ready

#29937 Avoid strong refs to tracers in DynamicJaxprTrace.
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/lax.py
  jax/_src/pjit.py
  jax/_src/shard_map.py
  tests/core_test.py
  tests/dynamic_api_test.py
Labels: kokoro:force-run, pull ready

#29966 [mutable-arrays] several fixes for direct-linearize + mutable arrays
  jax/BUILD
  jax/_src/core.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/lax.py
  jax/_src/pjit.py
  jax/_src/public_test_util.py
  jax/_src/state/primitives.py
  tests/mutable_array_test.py
Labels: kokoro:force-run, pull ready

#29995 tweak pe._drop_unused_vars so we only call make_jaxpr_effects once
  jax/_src/interpreters/partial_eval.py
Labels: kokoro:force-run, pull ready

#29988 Fix typo in references for `numpy.column_stack()`
  jax/_src/numpy/lax_numpy.py
Labels: kokoro:force-run, pull ready

#30010 Deprecate jax.scipy.special.sph_harm
  CHANGELOG.md
  jax/scipy/special.py
  tests/lax_scipy_test.py
Labels: kokoro:force-run, pull ready

#30011 Fix breakage indroduced in lax.parallel build refactor
  jax/_src/lax/parallel.py
Labels: kokoro:force-run, pull ready

#29977 Updated links in NamedSharding and Mesh docstrings
  jax/_src/mesh.py
  jax/_src/named_sharding.py
Labels: documentation, kokoro:force-run, pull ready

#30013 Finalize deprecation of jax.extend.ffi
  CHANGELOG.md
  docs/jax.ffi.rst
  jax/extend/__init__.py
  jax/extend/ffi.py
Labels: kokoro:force-run, pull ready

#30025 Remove deprecated APIs jax.lib.xla_extension.ArrayImpl and XlaRuntimeError
  jax/lib/xla_extension.py
Labels: kokoro:force-run, pull ready

#30022 [caches] Simplifications in the management of caches
  CHANGELOG.md
  jax/_src/api.py
  jax/_src/linear_util.py
  jax/_src/util.py
  jax/extend/backend.py
Labels: kokoro:force-run, pull ready

#30026 [mutable-arrays] fix scan ad bug
  jax/_src/core.py
  jax/_src/interpreters/ad.py
  jax/_src/lax/control_flow/loops.py
  tests/mutable_array_test.py
Labels: kokoro:force-run, pull ready

#30039 [caches] Register weakref_lru_caches with util._caches
  jax/_src/util.py
Labels: kokoro:force-run, pull ready

#30034 Add heartbeat argument to distributed.initialize.
  jax/_src/distributed.py
Labels: kokoro:force-run, pull ready

#30071 Remove print statement from tree_util_test.TreeTest.testStringRepresentation.
  tests/tree_util_test.py
Labels: kokoro:force-run, pull ready

#28839 In print_environment_info, print environment variables that start with XLA_
  jax/_src/environment_info.py
Labels: kokoro:force-run, pull ready

#30037 Fix broken JAX AI Stack links and tweak surrounding wording + styling
  docs/_static/style.css
  docs/index.rst
Labels: documentation, kokoro:force-run, pull ready

#29570 Add entry to .gitignore to ignore build produced by 'pip install --config-settings editable-mode=strict -e .'
  .gitignore
Labels: kokoro:force-run, pull ready

#30082 Deprecate jax.interpreters.xla.canonicalize_dtype.
  CHANGELOG.md
  jax/interpreters/xla.py
Labels: kokoro:force-run, pull ready

#30062 On-the-fly trace-time DCE using Python ref counting
  jax/_src/ad_checkpoint.py
  jax/_src/checkify.py
  jax/_src/core.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/__init__.py
  jax/_src/lax/lax.py
  jax/_src/pallas/mosaic/primitives.py
  jax/_src/pallas/mosaic_gpu/primitives.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pallas/primitives.py
  jax/_src/state/discharge.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/key_reuse/_core.py
  jax/lax/__init__.py
  tests/api_test.py
  tests/checkify_test.py
  tests/hijax_test.py
  tests/key_reuse_test.py
  tests/pallas/fusion_test.py
  tests/pallas/mosaic_gpu_test.py
  tests/state_test.py
Labels: kokoro:force-run, pull ready

#30023 fix cudnn sdpa invalid seqlen for unused segments
  jax/_src/cudnn/fused_attention_stablehlo.py
Labels: kokoro:force-run, pull ready

#30159 [Mosaic GPU] Fix a race in test_remote_async_copy
  jax/experimental/mosaic/gpu/__init__.py
  jax/experimental/mosaic/gpu/utils.py
  tests/mosaic/gpu_test_distributed.py
Labels: kokoro:force-run, pull ready, CI Optional GPU Presubmit

#30167 Add clarification to softmax and log_softmax regarding masked-out elements.
  jax/_src/nn/functions.py
Labels: kokoro:force-run, pull ready

#30212 remove caveat about random bit generation from auto-parallelization doc
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.ipynb
  docs/notebooks/Distributed_arrays_and_automatic_parallelization.md
Labels: kokoro:force-run, pull ready

#30211 [shape_poly] Add support for triu_indices and tril_indices
  jax/_src/numpy/lax_numpy.py
  tests/shape_poly_test.py
Labels: kokoro:force-run, pull ready

#30179 Add default window_strides and padding to lax.reduce_window.
  jax/_src/lax/windowed_reductions.py
Labels: kokoro:force-run, pull ready

#30227 Mark the jax.util submodule as deprecated
  jax/__init__.py
  jax/util.py
Labels: pull ready

#30225 [doc] add docs for jax.lax.reduce_window
  jax/_src/lax/windowed_reductions.py
Labels: documentation, kokoro:force-run, pull ready

#30206 Add nn.logmeanexp.
  CHANGELOG.md
  docs/jax.nn.rst
  jax/_src/nn/functions.py
  jax/_src/numpy/reductions.py
  jax/_src/ops/special.py
  jax/nn/__init__.py
  tests/nn_test.py
Labels: kokoro:force-run, pull ready

#30340 [mutable-arrays] basic shard_map + mutable arrays support
  jax/_src/core.py
  jax/_src/shard_map.py
  jax/_src/state/discharge.py
  jax/_src/state/types.py
  tests/shard_map_test.py
Labels: kokoro:force-run, pull ready

#29370 [mutable-arrays] remat discharge rule
  jax/_src/ad_checkpoint.py
  jax/_src/core.py
  tests/mutable_array_test.py
Labels: kokoro:force-run, pull ready

#30351 Add note about direct linearize to changelog
  CHANGELOG.md
  docs/direct_linearize_migration.md
Labels: kokoro:force-run, pull ready

#29343 gumbel distribution implementation
  docs/jax.scipy.rst
  jax/_src/scipy/stats/gumbel_l.py
  jax/_src/scipy/stats/gumbel_r.py
  jax/scipy/stats/__init__.py
  jax/scipy/stats/gumbel_l.py
  jax/scipy/stats/gumbel_r.py
  tests/scipy_stats_test.py
Labels: documentation, kokoro:force-run, pull ready

#30356 jnp.fft.fftfreq: fix regression in complex dtype support
  jax/_src/numpy/fft.py
  tests/fft_test.py
Labels: kokoro:force-run, pull ready

#30368 write docs about controlling array layouts
  docs/advanced_guide.rst
  docs/conf.py
  docs/notebooks/layout.ipynb
  docs/notebooks/layout.md
Labels: documentation, kokoro:force-run, pull ready

#30440 Use the correct tracing context when creating zeros in linearize_from_jvp
  jax/_src/interpreters/ad.py
Labels: kokoro:force-run, pull ready

#30446 avoid top-level imports in source_info_util
  jax/BUILD
  jax/_src/source_info_util.py
Labels: pull ready

#30420 Refactoring HTTIJ and surrounding pages, take 2
  docs/_tutorials/index.rst
  docs/beginner_guide.rst
  docs/conf.py
  docs/faq.rst
  docs/glossary.rst
  docs/index.rst
  docs/key-concepts.md
  docs/notebooks/thinking_in_jax.ipynb
  docs/notebooks/thinking_in_jax.md
  docs/quickstart.md
  docs/tutorials.rst
  docs/user_guides.rst
Labels: kokoro:force-run, pull ready

#30447 [Mosaic GPU] Fix some typos in docs
  docs/pallas/gpu/reference.md
Labels: kokoro:force-run, pull ready

#30258 Skip Pallas and Mosaic GPU tests that don't fit on RTX 6000 PRO
  jax/_src/test_util.py
  tests/mosaic/gpu_test.py
  tests/pallas/mosaic_gpu_test.py
  tests/pallas/ops_test.py
Labels: kokoro:force-run, pull ready, CI Optional GPU Presubmit

#30534 [jaxpr consts] Add an internal implementation note
  docs/contributor_guide.rst
  docs/developer.md
  docs/internals/constants.md
  docs/internals/index.rst
  jax/_src/core.py
  jax/_src/interpreters/mlir.py
  jax/_src/pjit.py
Labels: documentation, kokoro:force-run, pull ready

#30467 Correctly apply global scale in nvfp4 quantization.
  jax/_src/cudnn/scaled_matmul_stablehlo.py
  tests/scaled_matmul_stablehlo_test.py
Labels: kokoro:force-run, pull ready

#30576 Use ml_dtypes 0.5.3 in bazel tests.
  build/requirements.in
  build/requirements_lock_3_11.txt
  build/requirements_lock_3_12.txt
  build/requirements_lock_3_13.txt
  build/requirements_lock_3_13_ft.txt
  build/requirements_lock_3_14.txt
  build/requirements_lock_3_14_ft.txt
Labels: kokoro:force-run, pull ready

#30577 Don't build scipy from source in tsan ci builds
  .github/workflows/tsan.yaml
  build/requirements_lock_3_14.txt
  build/requirements_lock_3_14_ft.txt
Labels: pull ready

#30582 Update requirements files so 3.14 lock files can be generated the usual
  .github/workflows/pytest_cpu.yml
  .github/workflows/pytest_cuda.yml
  .github/workflows/tsan.yaml
  build/freethreading-requirements.txt
  build/nonfreethreading-requirements.txt
  build/requirements.in
  build/requirements_lock_3_11.txt
  build/requirements_lock_3_12.txt
  build/requirements_lock_3_13.txt
  build/requirements_lock_3_13_ft.txt
  build/requirements_lock_3_14.txt
  build/requirements_lock_3_14_ft.txt
  build/test-requirements.txt
Labels: pull ready

#30585 add prototype scheduling_group call primitive
  jax/BUILD
  jax/_src/core.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/partial_eval.py
  jax/experimental/scheduling_groups.py
  tests/BUILD
  tests/scheduling_groups_test.py
Labels: kokoro:force-run, pull ready

#30584 [jaxprs] Improve AOT lowering in presence of const args.
  docs/internals/constants.md
  jax/_src/BUILD
  jax/_src/api.py
  jax/_src/compiler.py
  jax/_src/interpreters/pxla.py
  jax/_src/pjit.py
  jax/_src/stages.py
  jax/_src/test_util.py
  jax/experimental/serialize_executable.py
  tests/aot_test.py
  tests/compilation_cache_test.py
  tests/debug_info_test.py
  tests/pmap_test.py
Labels: pull ready

#30588 docs: Use self-documenting f-string exprs in thinking_with_jax
  docs/notebooks/thinking_in_jax.ipynb
  docs/notebooks/thinking_in_jax.md
Labels: kokoro:force-run, pull ready

#30633 Bump the minimum cudnn version in the installation docs.
  docs/installation.md
Labels: pull ready
