Repository jax-ml/jax, pull requests merged in 2025-04, with the labels that each got.

#27540 jnp.power: support __jax_array__ on inputs
  jax/_src/numpy/ufuncs.py
  tests/array_extensibility_test.py
Labels: kokoro:force-run, pull ready

#26964 AutoPGLE: force-disable graphs less
  jax/_src/compiler.py
  tests/pgle_test.py
Labels: kokoro:force-run, pull ready

#27643 jnp.select: support __jax_array__ for inputs
  jax/_src/numpy/lax_numpy.py
  tests/array_extensibility_test.py
Labels: kokoro:force-run, pull ready

#27648 jnp.einsum: add support for __jax_array__
  jax/_src/numpy/einsum.py
  tests/array_extensibility_test.py
Labels: kokoro:force-run, pull ready

#27632 Clarify documentation of jnp.heaviside
  jax/_src/numpy/ufuncs.py
Labels: kokoro:force-run, pull ready

#27651 [mutable-arrays] add vmap rule for mutable_array_p, very basic test
  jax/_src/interpreters/batching.py
  tests/mutable_array_test.py
Labels: kokoro:force-run, pull ready

#27086 [mosaic-gpu] add reduction support in copy_smem_to_gmem
  jax/_src/pallas/mosaic_gpu/primitives.py
  jax/experimental/mosaic/gpu/launch_context.py
  jaxlib/mosaic/gpu/runtime.cc
  tests/pallas/mosaic_gpu_test.py
Labels: kokoro:force-run, pull ready

#27644 cumulative reductions: support __jax_array__ on inputs
  jax/_src/numpy/reductions.py
  tests/array_extensibility_test.py
Labels: kokoro:force-run, pull ready

#27463 [better_errors] Fix the handling of kwargs for debug_info.
  jax/_src/api.py
  jax/_src/api_util.py
  jax/_src/pjit.py
  tests/debug_info_test.py
Labels: kokoro:force-run, pull ready

#27662 upgrade docs from `jax.core` to `jax.extend.core` where needed to fix doc build
  docs/jax-primitives.md
  docs/notebooks/Writing_custom_interpreters_in_Jax.ipynb
  docs/notebooks/Writing_custom_interpreters_in_Jax.md
Labels: kokoro:force-run, pull ready

#27628 make random_gamma_grad not a primitive anymore
  jax/_src/checkify.py
  jax/_src/lax/special.py
  jax/extend/core/primitives.py
  jax/lax/__init__.py
Labels: kokoro:force-run, pull ready

#27389 Added TSAN free-threading CI job for 3.14 cpython
  .github/workflows/tsan-suppressions_3.13.txt
  .github/workflows/tsan-suppressions_3.14.txt
  .github/workflows/tsan.yaml
  WORKSPACE
  build/build.py
  build/requirements_lock_3_13_ft.txt
  build/requirements_lock_3_14_ft.txt
  build/tools/utils.py
  jaxlib/jax.bzl
Labels: kokoro:force-run, pull ready

#27671 Disabled default env var LOBPCG_EMIT_DEBUG_PLOTS=1
  tests/BUILD
  tests/lobpcg_test.py
Labels: kokoro:force-run, pull ready

#27650 jnp.isinf & friends: support __jax_array__
  jax/_src/numpy/ufuncs.py
  tests/array_extensibility_test.py
Labels: kokoro:force-run, pull ready

#27660 let XLA metadata be unset in nested dynamic scopes
  jax/_src/core.py
  jax/_src/xla_metadata.py
  tests/xla_metadata_test.py
Labels: kokoro:force-run, pull ready

#27678 jnp.concat and friends: support __jax_array__
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
  tests/array_extensibility_test.py
Labels: kokoro:force-run, pull ready

#27680 [array_api] update array_api_version to 2024.12
  .github/workflows/jax-array-api.yml
  jax/_src/numpy/array_api_metadata.py
  tests/array_api_skips.txt
Labels: pull ready

#24197 Add CI workflow to check JAX distibuted initialize within K8s jobsets
  .github/workflows/k8s.yaml
  .pre-commit-config.yaml
  examples/k8s/example.yaml
  examples/k8s/svc-acct.yaml
  jax/_src/clusters/k8s_cluster.py
Labels: kokoro:force-run, pull ready

#27677 Fix custom_transpose when composed with custom_jvp and use_direct_linearize=True
  jax/_src/custom_transpose.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#27084 Prune passthrough outputs in lax.switch.
  jax/_src/lax/control_flow/conditionals.py
  tests/lax_control_flow_test.py
Labels: kokoro:force-run, pull ready

#27688 add an `out_sharding` option to `jax.random.randint`
  jax/_src/random.py
  tests/pjit_test.py
Labels: kokoro:force-run, pull ready

#27635 docs: compilation_cache_expect_pgle option
  docs/gpu_performance_tips.md
Labels: kokoro:force-run, pull ready

#27304 Straight-through estimator for nvfp4
  jax/_src/cudnn/scaled_matmul_stablehlo.py
  tests/scaled_matmul_stablehlo_test.py
Labels: kokoro:force-run, pull ready

#27708 Only trigger K8s CI on changes to cluster config and distributed initialize
  .github/workflows/k8s.yaml
Labels: kokoro:force-run, pull ready

#27681 jax.numpy: support __jax_array__ in several more functions
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
  tests/array_extensibility_test.py
Labels: kokoro:force-run, pull ready

#27691 [export] Add support for override_lowering_rules to jax.export.
  jax/_src/config.py
  jax/_src/export/_export.py
  jax/_src/interpreters/mlir.py
  tests/export_test.py
Labels: kokoro:force-run, pull ready

#27717 add an `out_sharding` option to `jax.random.permutation`
  jax/_src/random.py
  tests/pjit_test.py
Labels: kokoro:force-run, pull ready

#27707 Fixed deadlock in NamedSharding ctor
  jaxlib/xla/sharding.cc
Labels: kokoro:force-run, pull ready

#27730 add an `out_sharding` option to `jax.random.truncated_normal`
  jax/_src/random.py
  tests/pjit_test.py
Labels: kokoro:force-run, pull ready

#27731 fix(docs): corrected the name of the function call in the document
  docs/gradient-checkpointing.md
Labels: kokoro:force-run, pull ready

#27735 Apply forwarding in pjit linearization rule to avoid intermediate copies
  jax/_src/interpreters/ad.py
  jax/_src/pjit.py
Labels: kokoro:force-run, pull ready

#26853 Add scalar event logging function
  jax/_src/monitoring.py
  jax/monitoring.py
  tests/monitoring_test.py
Labels: pull ready

#27797 [shard-map] in eager shmap, handle all rep rule output cases
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: kokoro:force-run, pull ready

#27716 jax.numpy: support __jax_array__ in remaining APIs
  jax/_src/numpy/lax_numpy.py
  tests/array_extensibility_test.py
Labels: kokoro:force-run, pull ready

#27793 Apply output forwarding in lin rule for pjit
  jax/_src/interpreters/partial_eval.py
  jax/_src/pjit.py
Labels: kokoro:force-run, pull ready

#27814 Harden compilation cache against libtpu version mismatch
  jax/_src/cache_key.py
  tests/cache_key_test.py
Labels: kokoro:force-run, pull ready, skill issue

#27776 [export] Add support for serializing functions with PRNG keys as inputs/outputs
  jax/_src/export/serialization.fbs
  jax/_src/export/serialization.py
  jax/_src/export/serialization_generated.py
  jax/_src/prng.py
  tests/export_test.py
Labels: kokoro:force-run, pull ready

#27827 Add a skeleton for Pallas:Mosaic GPU documentation
  docs/_static/pallas/gpu/nvidia_sm.svg
  docs/pallas/gpu/index.rst
  docs/pallas/gpu/reference.md
  docs/pallas/index.rst
Labels: kokoro:force-run, pull ready

#27803 [shard-map] add while_loop rep rule
  jax/_src/util.py
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: kokoro:force-run, pull ready

#27809 [shard-map] canonicalize rep=None to be rep={all possible axes}
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: kokoro:force-run, pull ready

#27836 jnp.repeat: don't cast repeats to array, as they must be static.
  jax/_src/numpy/lax_numpy.py
  tests/array_extensibility_test.py
Labels: kokoro:force-run, pull ready

#27807 jnp.linalg: add symmetrize_input argument & docs
  jax/_src/numpy/linalg.py
  tests/linalg_test.py
Labels: documentation, kokoro:force-run, pull ready

#27821 Clarify jax.make_jaxpr docstring
  jax/_src/api.py
Labels: documentation, kokoro:force-run, pull ready

#27503 [NVIDIA] Enable JAX Documentation for scaled_matmul and scaled_dot_general
  docs/jax.nn.rst
  jax/_src/nn/functions.py
  jax/nn/__init__.py
  tests/nn_test.py
Labels: kokoro:force-run, pull ready

#27804 Disable second order vjp tests in RunStateHypothesisTest.test_vjp if JAX_SKIP_SLOW_TESTS=true
  .github/workflows/tsan-suppressions_3.13.txt
  .github/workflows/tsan.yaml
  build/requirements_lock_3_14_ft.txt
  jax/_src/test_util.py
  jaxlib/jax.bzl
  tests/state_test.py
Labels: kokoro:force-run, pull ready

#27866 Fix data race in weakref_lru_cache under free-threading.
  jaxlib/weakref_lru_cache.cc
Labels: kokoro:force-run, pull ready

#27870 Fix build for clang >=19
  .bazelrc
Labels: kokoro:force-run, pull ready

#27879 [shard-map] fix another bug where we incorrectly handled None in check_rep
  jax/experimental/shard_map.py
  tests/shard_map_test.py
Labels: kokoro:force-run, pull ready

#27893 [shard-map] add docs for VMAs
  docs/notebooks/shard_map.ipynb
  docs/notebooks/shard_map.md
Labels: kokoro:force-run, pull ready

#27888 Added update_one_slot race tsan suppression for 3.14
  .github/workflows/tsan-suppressions_3.14.txt
Labels: kokoro:force-run, pull ready

#27895 Refactor random_lax_test.py
  tests/random_lax_test.py
Labels: kokoro:force-run, pull ready

#27843 Add JVP rule for linear_call
  jax/_src/custom_derivatives.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#27903 [shard-map] good errors for pvary issues
  jax/_src/lax/control_flow/common.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/loops.py
  tests/lax_control_flow_test.py
  tests/shard_map_test.py
Labels: pull ready

#27849 Automatically document `jax.config` options
  docs/conf.py
  docs/config_options.rst
  docs/index.rst
  docs/sphinxext/jax_list_config_options.py
  jax/_src/config.py
Labels: documentation, kokoro:force-run, pull ready

#27924 Enable execution of explicit-sharding notebook in docs
  docs/conf.py
Labels: documentation, kokoro:force-run, pull ready

#27937 optimize while_loop by moving readonly carry components to be consts
  jax/_src/lax/control_flow/loops.py
  tests/checkify_test.py
  tests/lax_control_flow_test.py
Labels: kokoro:force-run, pull ready

#27938 Bump scipy build requirement on Python 3.13.
  build/requirements.in
  build/requirements_lock_3_13_ft.txt
Labels: pull ready

#27685 Add an option to expose cudnn attention residual to user
  jax/_src/cudnn/fused_attention_stablehlo.py
  tests/fused_attention_stablehlo_test.py
Labels: kokoro:force-run, pull ready

#27916 [cache_misses] Skip tracing-cache-miss explanations for JAX-internal functions
  jax/_src/linear_util.py
  jax/_src/pjit.py
  jax/_src/traceback_util.py
  tests/api_test.py
  tests/debug_info_test.py
Labels: kokoro:force-run, pull ready

#27876 [export] Add test that exporting works for experimental.compute_on.
  jax/_src/api.py
  jax/_src/interpreters/mlir.py
  tests/export_test.py
  tests/memories_test.py
Labels: kokoro:force-run, pull ready

#27873 Make `trace` and `lower` class attributes for `jax.jit`.
  CHANGELOG.md
  jax/_src/api.py
  jax/_src/pjit.py
  tests/memories_test.py
  tests/pjit_test.py
  tests/xla_metadata_test.py
Labels: pull ready

#27970 roll-forward: optimize while_loop by moving readonly carry components to be consts
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/control_flow/loops.py
  tests/checkify_test.py
  tests/jaxpr_effects_test.py
  tests/lax_control_flow_test.py
Labels: kokoro:force-run, pull ready

#27981 Properly center and size the SM image in the GPU docs
  docs/pallas/gpu/reference.md
Labels: pull ready

#27868 Add reference docs for Pallas:MGPU synchronization primitives
  docs/pallas/gpu/reference.md
Labels: kokoro:force-run, pull ready

#27973 add a brief description of the jax.Array-has-no-__iadd__ gotcha
  docs/notebooks/Common_Gotchas_in_JAX.ipynb
  docs/notebooks/Common_Gotchas_in_JAX.md
Labels: documentation, kokoro:force-run, pull ready

#27980 [explain-cache-miss] Improve tracing-cache-miss explanations
  jax/_src/pjit.py
  tests/api_test.py
  tests/debug_info_test.py
  tests/pjit_test.py
Labels: kokoro:force-run, pull ready

#27925 Fix grep used for skipping PR builds on Read the Docs
  .readthedocs.yml
Labels: documentation, kokoro:force-run, pull ready

#27997 Remove accidental tab characters from Pallas:MGPU docs
  docs/pallas/gpu/reference.md
Labels: pull ready

#27971 Fix typo in jax.lax.linalg.symmetric_product description
  jax/_src/lax/linalg.py
Labels: kokoro:force-run, pull ready

#27993 [explain_cache_miss] Add to explanations the duration of the missed function call
  jax/_src/linear_util.py
  jax/_src/pjit.py
Labels: kokoro:force-run, pull ready

#27966 jax.jit: deprecate non-standard call signature.
  CHANGELOG.md
  jax/_src/api.py
  jax/_src/deprecations.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#28007 jnp.power: better docs for invalid input
  jax/_src/numpy/ufuncs.py
Labels: kokoro:force-run, pull ready

#28020 Update issue template with correct URL for untemplated issue
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: pull ready

#27919 [NVIDIA] Keep old scale_matmul arg names
  jax/_src/nn/functions.py
Labels: kokoro:force-run, pull ready

#28012 Reinstate the "lifegiving chaos" line to the PRNG docs.
  docs/random-numbers.md
Labels: kokoro:force-run, pull ready

#27999 Fixed the way to skip tests using optional python dependencies
  tests/colocated_python_test.py
  tests/mosaic/matmul_test.py
  tests/pallas/indexing_test.py
  tests/pallas/ops_test.py
  tests/pallas/tpu_all_gather_test.py
  tests/pallas/tpu_gmm_test.py
  tests/pallas/tpu_ops_test.py
  tests/pallas/tpu_pallas_pipeline_test.py
  tests/pallas/tpu_splash_attention_kernel_test.py
  tests/state_test.py
Labels: kokoro:force-run, pull ready

#28027 Add explicit_axes section to the doc
  docs/notebooks/explicit-sharding.ipynb
  docs/notebooks/explicit-sharding.md
Labels: documentation, pull ready

#28036 [ROCm] Fix lowering code for ROCm RNN
  jax/experimental/rnn.py
Labels: kokoro:force-run, pull ready

#28022 jax.random.bernoulli: use higher-resolution sampler
  CHANGELOG.md
  jax/_src/random.py
  tests/random_lax_test.py
Labels: kokoro:force-run, pull ready

#28047 Clean up softmax initial deprecation
  jax/_src/nn/functions.py
Labels: pull ready

#27984 Minor improvements to doc for jax.nn.logsumexp.
  jax/_src/ops/special.py
Labels: documentation, kokoro:force-run, pull ready

#27983 Add docs for GPU memory spaces in Pallas:MGPU
  docs/_static/pallas/gpu/grid_tiling_off.svg
  docs/_static/pallas/gpu/grid_tiling_on.svg
  docs/pallas/gpu/reference.md
Labels: documentation, kokoro:force-run, pull ready

#28056 [Pallas:MGPU] Add a diagram outlining GPU memory spaces
  docs/_static/pallas/gpu/memory_spaces.svg
  docs/pallas/gpu/reference.md
Labels: documentation, kokoro:force-run, pull ready

#28004 Add basic documentation for Pallas:MGPU layouts and transforms
  docs/pallas/gpu/reference.md
Labels: documentation, kokoro:force-run, pull ready

#28018 disable cudnn attention packed layout test on old arch prior to hopper
  jax/_src/cudnn/fused_attention_stablehlo.py
  tests/fused_attention_stablehlo_test.py
Labels: kokoro:force-run, pull ready

#28052 [Pallas] Refactor pipelining docs.
  docs/conf.py
  docs/pallas/index.rst
  docs/pallas/pipelining.ipynb
  docs/pallas/pipelining.md
Labels: kokoro:force-run, pull ready

#28062 Add explicit sharding to Introduction to parallel programming doc
  docs/conf.py
  docs/notebooks/explicit-sharding.ipynb
  docs/notebooks/explicit-sharding.md
  docs/sharded-computation.ipynb
  docs/sharded-computation.md
Labels: documentation, kokoro:force-run, pull ready

#28072 [Pallas] Move pipelining doc figures to static folder
  docs/_static/pallas/pipelining_bandwidth_bound.svg
  docs/_static/pallas/pipelining_compute_bound.svg
  docs/_static/pallas/pipelining_example.svg
  docs/_static/pallas/pipelining_latency_multistage.svg
  docs/_static/pallas/pipelining_mem_hierarchy.svg
  docs/pallas/pipelining.ipynb
  docs/pallas/pipelining.md
Labels: pull ready

#28069 Fix bug in argnums_partial_except when static_argnums is unsorted
  jax/_src/api_util.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#28078 [Pallas] Fix relative links in pipelining docs
  docs/pallas/pipelining.ipynb
  docs/pallas/pipelining.md
Labels: pull ready

#28077 Merge 0.6.0 release branch and update version numbers.
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: pull ready

#27963 [Pallas] Fix potential barrier race condition in Pallas TPU docs
  docs/pallas/tpu/distributed.ipynb
  docs/pallas/tpu/distributed.md
Labels: kokoro:force-run, pull ready

#28103 Don't recompute source_info for each tracer during staging
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/pjit.py
  jax/experimental/attrs.py
  jax/experimental/shard_map.py
Labels: kokoro:force-run, pull ready

#28063 Ensure outputs are tracers when inlining jit
  jax/_src/pjit.py
  tests/pjit_test.py
Labels: kokoro:force-run, pull ready

#27733 Add jax.fwd_and_bwd
  jax/__init__.py
  jax/_src/api.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#28141 fix: typo
  tests/multi_device_test.py
Labels: kokoro:force-run, pull ready

#28146 Fixed cached mlir module mutation issue in export
  jax/_src/export/_export.py
Labels: kokoro:force-run, pull ready

#28130 jax.random.bernoulli: add mode='high' for improved sampling for small p
  jax/_src/random.py
  tests/random_lax_test.py
Labels: kokoro:force-run, pull ready

#28155 [docs] fix typo in doc link
  docs/jit-compilation.md
Labels: kokoro:force-run, pull ready

#28156 implement _replace_with for PRNGKeyArray
  jax/_src/prng.py
  tests/mutable_array_test.py
Labels: kokoro:force-run, pull ready

#28098 [Mosaic GPU] Align on device profiler array in smem to 8 bytes
  jax/experimental/mosaic/gpu/core.py
Labels: kokoro:force-run, pull ready

#28106 jnp.frexp: add custom JVP rule for proper derivatives.
  jax/_src/numpy/ufuncs.py
  tests/lax_numpy_test.py
Labels: kokoro:force-run, pull ready

#28166 Add support for generating freethreaded pip lockfiles.
  build/BUILD.bazel
  build/build.py
  build/freethreading-requirements.txt
  build/nonfreethreading-requirements.txt
  build/requirements.in
  build/requirements_lock_3_10.txt
  build/requirements_lock_3_11.txt
  build/requirements_lock_3_12.txt
  build/requirements_lock_3_13.txt
  build/requirements_lock_3_13_ft.txt
  tests/lax_scipy_test.py
Labels: kokoro:force-run, pull ready

#28092 Fix ensure_compile_time_eval context after stackless
  jax/_src/interpreters/partial_eval.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#24074 BUG: return one covariance matrix per `rhs` in `polyfit`
  jax/_src/numpy/polynomial.py
  tests/lax_numpy_test.py
Labels: kokoro:force-run, pull ready

#28100 [Pallas] Update TPU pipelining docs
  docs/pallas/design/async_note.md
  docs/pallas/pipelining.ipynb
  docs/pallas/pipelining.md
  docs/pallas/quickstart.ipynb
  docs/pallas/quickstart.md
  docs/pallas/tpu/pipelining.ipynb
  docs/pallas/tpu/pipelining.md
Labels: documentation, kokoro:force-run, pull ready

#28150 Fix handling of `SymbolicZero` output when batching `custom_jvp`
  jax/_src/interpreters/batching.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#28158 jnp.ldexp: avoid overflow for large exponent
  jax/_src/numpy/ufuncs.py
  tests/lax_numpy_test.py
Labels: kokoro:force-run, pull ready

#28185 Update tsan requirements patch after lockfile update.
  .github/workflows/requirements_lock_3_13_ft.patch
Labels: kokoro:force-run, pull ready

#28182 DOC: link to ai-stack tutorials from JAX's front page
  docs/index.rst
Labels: documentation, kokoro:force-run, pull ready

#27914 Account for versioned clang binaries
  build/tools/utils.py
Labels: kokoro:force-run, pull ready

#28191 Replace reference to `jax.readthedocs.io` with `docs.jax.dev` in `jax/_src/shard_map.py`
  jax/_src/shard_map.py
Labels: kokoro:force-run, pull ready

#26975 Update install docs for AMDGPU
  docs/installation.md
Labels: kokoro:force-run, pull ready

#28059 Inline literals while tracing instead of in a separate pass
  jax/_src/core.py
  jax/_src/interpreters/partial_eval.py
Labels: kokoro:force-run, pull ready

#28187 Cleanup: don't redefine softmax in jax.random
  jax/_src/random.py
Labels: kokoro:force-run, pull ready

#28195 TSAN FT CI, install cython from nightly wheels
  .github/workflows/tsan.yaml
Labels: kokoro:force-run, pull ready

#28177 jax.numpy: make standard input utilities respect __jax_array__
  jax/_src/numpy/util.py
Labels: kokoro:force-run, pull ready

#28223 Update FFI tutorial to new shard_map
  docs/ffi.ipynb
  docs/ffi.md
Labels: documentation, kokoro:force-run, pull ready

#28239 Update README.md to remove jax.pmap
  README.md
Labels: kokoro:force-run, pull ready

#28009 Added new multi-controller JAX guide.
  docs/_static/multi_process/controller_and_local_devices.png
  docs/_static/multi_process/mcjax_overview.png
  docs/multi_process.md
Labels: kokoro:force-run, pull ready

#28246 [readme] include teaser example of shardings
  README.md
Labels: kokoro:force-run, pull ready

#28245 Updated TSAN suppressions files to get traceback of crashed process
  .github/workflows/tsan-suppressions_3.13.txt
  .github/workflows/tsan-suppressions_3.14.txt
Labels: kokoro:force-run, pull ready

#28249 fix: make build.py use /usr/bin/env python3 as shebang
  build/build.py
Labels: kokoro:force-run, pull ready

#28210 [scan] when a carry is read-only, move it to be a const
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/control_flow/loops.py
  tests/api_test.py
  tests/core_test.py
  tests/lax_control_flow_test.py
Labels: kokoro:force-run, pull ready

#28209 jax.numpy: move linspace & friends into array_creation
  jax/_src/numpy/array_creation.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
  jax/numpy/__init__.py
Labels: kokoro:force-run, pull ready

#28276 Minor optim in profiler on session stop and export
  jax/_src/profiler.py
Labels: kokoro:force-run, pull ready

#28244 Edit print_environment_info to print environment variables that start with JAX_.
  jax/_src/environment_info.py
Labels: kokoro:force-run, pull ready

#28168 Implement Gauss hypergeometric function 2F1
  jax/_src/scipy/special.py
  jax/scipy/special.py
  tests/lax_scipy_special_functions_test.py
Labels: kokoro:force-run, pull ready

#28340 Relax constraints in `jnp.vectorize` for output shapes with default signature
  jax/_src/numpy/vectorize.py
  tests/lax_numpy_vectorize_test.py
Labels: kokoro:force-run, pull ready

#28288 Ensure __jax_array__ works properly with JIT disabled.
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/reductions.py
  jax/_src/numpy/tensor_contractions.py
  jax/_src/numpy/ufuncs.py
  jax/_src/numpy/util.py
  tests/array_extensibility_test.py
Labels: kokoro:force-run, pull ready

#28345 Handle extended dtypes in FFI lowering
  jax/_src/ffi.py
  tests/debugging_primitives_test.py
  tests/ffi_test.py
Labels: kokoro:force-run, pull ready

#28357 [jax/docs] - Fix link in quickstart.md
  docs/quickstart.md
Labels: kokoro:force-run, pull ready

#28359 Disable logsumexp test under SciPy 1.15.
  tests/lax_scipy_test.py
Labels: kokoro:force-run, pull ready

#28358 chore: load py_library from rules_python
  jaxlib/jax.bzl
Labels: kokoro:force-run, pull ready

#28344 Remove unused parameters in emit_python_callback
  jax/_src/callback.py
Labels: kokoro:force-run, pull ready

#28381 fix: use backend to call xb.process_count in _raise_warnings_or_error…
  jax/_src/interpreters/pxla.py
Labels: kokoro:force-run, pull ready

#28346 Fix deprecation warnings in cudnn scaled matmul
  jax/_src/cudnn/scaled_matmul_stablehlo.py
Labels: kokoro:force-run, pull ready

#28372 SPMD with jax.jit, namedsharding and partition spec
  examples/spmd_mnist_classifier_fromscratch.py
Labels: kokoro:force-run, pull ready

#28390 Fix test failure in autodidax due to compile() API change.
  docs/autodidax.ipynb
  docs/autodidax.md
  docs/autodidax.py
Labels: pull ready

#28347 Show Literal dtypes when pretty printing Jaxprs
  docs/aot.md
  jax/_src/api.py
  jax/_src/core.py
  jax/_src/state/indexing.py
  tests/api_test.py
  tests/pjit_test.py
  tests/state_test.py
Labels: kokoro:force-run, pull ready

#28365 Deactivate automatic cluster detection in tests.
  tests/distributed_test.py
Labels: kokoro:force-run, pull ready

#28407 chore: switch to pypi hub instead of underlying repos
  BUILD.bazel
  jaxlib/jax.bzl
  jaxlib/tools/BUILD.bazel
Labels: kokoro:force-run, pull ready

#28170 Added additional stream annotation E2E tests
  tests/memories_test.py
Labels: kokoro:force-run, pull ready

#28319 [JAX][Docs] Add an example of device compute on host memory space
  docs/notebooks/host-offloading.ipynb
  docs/notebooks/host-offloading.md
Labels: kokoro:force-run, pull ready

#28415 Use sharding in types in spmd example
  examples/spmd_mnist_classifier_fromscratch.py
Labels: kokoro:force-run, pull ready
