Repository jax-ml/jax, pull requests merged in 2025-09, with the labels that each got.

#31496 Fix custom_jvp DCE behavior with symbolic_zeros.
  jax/_src/custom_derivatives.py
  tests/custom_api_test.py
Labels: kokoro:force-run, pull ready

#31632 add no-execution config option
  jax/__init__.py
  jax/_src/config.py
  jax/_src/interpreters/pxla.py
  jax/_src/pjit.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#31648 In `jax.numpy.fft`, error immediately if any element of `shape` <= 0.
  jax/_src/numpy/fft.py
Labels: kokoro:force-run, pull ready

#31637 jnp.unwrap: properly handle integer case
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: kokoro:force-run, pull ready

#31677 [hijax] un-skip scan test
  jax/_src/hijax.py
  tests/hijax_test.py
Labels: kokoro:force-run, pull ready

#31686 reduce entropy
  jax/_src/api.py
  jax/_src/api_util.py
  jax/_src/linear_util.py
Labels: kokoro:force-run, pull ready, skill issue

#31685 Add a lower-to-lojax rule for cond
  jax/_src/core.py
  jax/_src/hijax.py
  jax/_src/lax/control_flow/common.py
  jax/_src/lax/control_flow/conditionals.py
  tests/hijax_test.py
Labels: kokoro:force-run, pull ready

#31696 [debug-info] invalidate debug_info by default in jaxpr.replace
  jax/_src/core.py
Labels: kokoro:force-run, pull ready

#31822 fix typo
  jax/_src/api.py
Labels: kokoro:force-run, pull ready

#31790 [hijax] support refs to hijax types
  docs/array_refs.ipynb
  docs/array_refs.md
  docs/array_refs.py
  jax/__init__.py
  jax/_src/core.py
  jax/_src/hijax.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/pjit.py
  jax/_src/ref.py
  jax/_src/state/discharge.py
  jax/_src/state/primitives.py
  jax/_src/state/types.py
  jax/ref.py
  tests/hijax_test.py
Labels: kokoro:force-run, pull ready

#31809 [docs] Replaced `&#151;` with `---` in remat and checkpointing docs
  docs/gradient-checkpointing.md
  docs/notebooks/autodiff_remat.ipynb
  docs/notebooks/autodiff_remat.md
Labels: documentation, kokoro:force-run, pull ready

#31848 Update jax artifacts and libtpu versions in the requirements lock files
  build/requirements.in
  build/requirements_lock_3_11.txt
  build/requirements_lock_3_12.txt
  build/requirements_lock_3_13.txt
  build/requirements_lock_3_13_ft.txt
  build/requirements_lock_3_14.txt
  build/requirements_lock_3_14_ft.txt
Labels: kokoro:force-run, pull ready

#31844 Postrelease 0.7.2
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: kokoro:force-run, pull ready

#31850 Fix a concurrency problem in jax_explain_cache_misses.
  jax/_src/pjit.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#31942 Suppress warnings in SlogdetTest on Mac.
  tests/linalg_test.py
Labels: pull ready

#31975 [mutable-arrays] add pin and unpin ops, basic tests
  jax/_src/config.py
  jax/_src/state/discharge.py
  jax/_src/state/primitives.py
  jax/_src/state/types.py
  tests/pallas/mosaic_gpu_test.py
  tests/state_test.py
Labels: kokoro:force-run, pull ready

#31978 fix typo
  tests/pallas/mosaic_gpu_test.py
Labels: pull ready

#31993 Use `@wraps` in `@explicit_axes`
  jax/_src/pjit.py
Labels: kokoro:force-run, pull ready

#31896 Update some stale CUDA 12 references in the documentation.
  docs/installation.md
Labels: pull ready

#31974 jax.scipy.special.ndtri: refactor implementation in terms of polyval
  jax/_src/scipy/special.py
Labels: kokoro:force-run, pull ready

#31979 Fix a typo in pipelining pseudocode
  docs/pallas/pipelining.ipynb
  docs/pallas/pipelining.md
Labels: kokoro:force-run, pull ready

#30133 Simplify tree_reduce signature using Unspecified bare class.
  jax/_src/tree.py
  jax/_src/tree_util.py
Labels: kokoro:force-run, pull ready

#32085 [hijax] vmap is a primitive, behind a flag
  jax/_src/BUILD
  jax/_src/ad_checkpoint.py
  jax/_src/api.py
  jax/_src/config.py
  jax/_src/core.py
  jax/_src/custom_derivatives.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/batching.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/lax.py
  jax/_src/pjit.py
  jax/_src/shard_map.py
  jax/_src/util.py
  tests/hijax_test.py
Labels: kokoro:force-run, pull ready

#32095 Bumped mypy to 1.18.2 and ruff to 0.13.1
  .pre-commit-config.yaml
Labels: pull ready

#30703 [docs] New tutorial on Tracing
  docs/faq.rst
  docs/jax-101.rst
  docs/jit-compilation.md
  docs/key-concepts.md
  docs/notebooks/thinking_in_jax.ipynb
  docs/notebooks/thinking_in_jax.md
  docs/tracing.md
Labels: kokoro:force-run, pull ready
