Repository jax-ml/jax, pull requests merged in 2025-10, with the labels that each got.

#32220 [doc] fix formatting in jax.export API docs
  jax/_src/export/_export.py
Labels: documentation, kokoro:force-run, pull ready

#32228 cache convert_const_himutables
  jax/_src/interpreters/partial_eval.py
Labels: kokoro:force-run, pull ready

#32302 In jax.scipy.linalg.block_diag, form a single wider concatenation rat…
  jax/_src/scipy/linalg.py
Labels: kokoro:force-run, pull ready

#32305 jnp.cov: return NaN for empty inputs
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_reducers_test.py
Labels: kokoro:force-run, pull ready

#32142 [mutable arrays] remove internal aliases
  docs/the-training-cookbook.py
  jax/_src/core.py
  jax/_src/error_check.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/batching.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/lax.py
  jax/_src/pallas/helpers.py
  jax/_src/pallas/mosaic/sc_core.py
  jax/_src/pjit.py
  jax/_src/ref.py
  jax/_src/state/discharge.py
  jax/_src/state/primitives.py
  tests/aot_test.py
  tests/mutable_array_test.py
  tests/pallas/indexing_test.py
  tests/pjit_test.py
  tests/shard_map_test.py
Labels: kokoro:force-run, pull ready

#32343 jnp.average: support multi-dimensional weights
  jax/_src/numpy/reductions.py
  tests/lax_numpy_reducers_test.py
Labels: kokoro:force-run, pull ready

#32432 don't use defvectorized for dce_sink batcher
  jax/_src/lax/lax.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#32434 [mutable-arrays] fix indexing of effects in pjit typecheck
  jax/_src/core.py
  jax/_src/pjit.py
  tests/jaxpr_effects_test.py
Labels: pull ready

#32429 Add jax.enable_x64 and deprecate jax.experimental aliases
  CHANGELOG.md
  docs/jax.rst
  jax/__init__.py
  jax/experimental/__init__.py
  jax/experimental/x64_context.py
  tests/pickle_test.py
  tests/x64_context_test.py
Labels: kokoro:force-run, pull ready
