Repository jax-ml/jax, pull requests merged in 2025-01, with the labels that each got.

#25661 Tensorboard profiling plugin nightly instructions
  docs/profiling.md
Labels: pull ready

#25706 Fix log10 and log2 for large inputs.
  jax/_src/numpy/ufuncs.py
  tests/lax_test.py
Labels: pull ready

#25710 Fix OSS build for the Mosaic GPU dialect
  jaxlib/mlir/_mlir_libs/BUILD.bazel
  jaxlib/mosaic/dialect/gpu/BUILD
  jaxlib/mosaic/python/mosaic_gpu.py
Labels: pull ready

#25686 Fix formatting in docs for transposing pytrees
  docs/working-with-pytrees.md
Labels: pull ready

#25713 jax.debug.print: respect trace-time np.printoptions
  jax/_src/debugging.py
  tests/debugging_primitives_test.py
Labels: pull ready

#25715 [ROCm] Update package indentation fix
  build/rocm/tools/get_rocm.py
Labels: pull ready

#25675 Deprecate scipy.special.lpmn & lpmn_values
  CHANGELOG.md
  jax/scipy/special.py
  tests/lax_scipy_test.py
Labels: pull ready

#25699 [shmap/partial-auto] Fixes lowering for jax.lax.axis_index in shard_map for degenerated shmaps.
  jax/_src/lax/parallel.py
  tests/shard_map_test.py
Labels: pull ready

#25214 jnp.einsum: default to optimize='auto'
  CHANGELOG.md
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#25740 Remove deprecated jax.experimental.array_api
  .github/workflows/ci-build.yaml
  CHANGELOG.md
  docs/developer.md
  docs/jax.experimental.array_api.rst
  docs/jax.experimental.rst
  docs/jax.numpy.rst
  jax/BUILD
  jax/experimental/array_api/__init__.py
  tests/BUILD
  tests/array_api_test.py
Labels: pull ready

#25728 Fix the doc error: module 'scipy.misc' has no attribute 'face'
  docs/notebooks/convolutions.ipynb
  docs/notebooks/convolutions.md
  docs/requirements.txt
Labels: pull ready

#25731 [shape_poly] Improve threefry with symbolic shapes
  jax/_src/export/shape_poly_decision.py
  jax/_src/prng.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  tests/shape_poly_test.py
Labels: pull ready

#25633 Move `jax.extend.ffi` module to top level `jax.ffi`
  CHANGELOG.md
  docs/conf.py
  docs/ffi.ipynb
  docs/ffi.md
  docs/jax.extend.ffi.rst
  docs/jax.extend.rst
  docs/jax.ffi.rst
  docs/jax.rst
  examples/ffi/src/jax_ffi_example/cpu_examples.py
  examples/ffi/src/jax_ffi_example/cuda_examples.py
  examples/ffi/src/jax_ffi_example/rms_norm.py
  jax/BUILD
  jax/__init__.py
  jax/_src/ffi.py
  jax/_src/lax/linalg.py
  jax/experimental/mosaic/gpu/profiler.py
  jax/experimental/shard_map.py
  jax/extend/ffi.py
  jax/ffi.py
  tests/BUILD
  tests/extend_test.py
  tests/ffi_test.py
Labels: kokoro:force-run, pull ready

#25748 Fix type signature for __divmod__
  jax/_src/basearray.pyi
Labels: pull ready

#25441 Update the advanced autodiff tutorial and replace some vmap with grad
  docs/advanced-autodiff.md
Labels: pull ready

#25042 Add an example demonstrating input-output aliasing with the FFI
  examples/ffi/src/jax_ffi_example/cpu_examples.cc
  examples/ffi/src/jax_ffi_example/cpu_examples.py
  examples/ffi/tests/cpu_examples_test.py
Labels: pull ready

#25761 [array api] update test suite to latest commit
  .github/workflows/jax-array-api.yml
Labels: pull ready

#25594 Update the tutorial for jax.checkpoint activation offloading policies by add examples
  docs/gradient-checkpointing.md
Labels: pull ready

#25754 [Mosaic GPU] Use `num_q_heads=2` in `flash_attention.py`
  jax/experimental/mosaic/gpu/examples/flash_attention.py
Labels: pull ready

#25527 Avoid adding conflicting `--repo_env=HERMETIC_PYTHON_VERSION=` to bazel command
  build/build.py
Labels: pull ready

#25786 Added 3.13 ft requirements lock file and updated WORKSPACE
  WORKSPACE
  build/build.py
  build/requirements_lock_3_13_ft.txt
Labels: pull ready

#25801 Add docstring for `lax.reduce_window`
  jax/_src/lax/windowed_reductions.py
Labels: pull ready

#25626 Switch to a new thread-safe utility for catching warnings.
  jax/BUILD
  jax/_src/test_util.py
  jax/_src/test_warning_util.py
  tests/BUILD
  tests/compilation_cache_test.py
  tests/deprecation_test.py
  tests/lax_numpy_reducers_test.py
  tests/lax_numpy_test.py
  tests/warnings_util_test.py
  tests/xla_bridge_test.py
Labels: pull ready

#25753 Add `sph_harm_y` to `jax.scipy.special` and deprecate `sph_harm`
  jax/_src/deprecations.py
  jax/_src/scipy/special.py
  jax/scipy/special.py
  tests/lax_scipy_test.py
Labels: kokoro:force-run, pull ready

#25803 Fix struct string encoding non-determinism in the RNN descriptor.
  jaxlib/gpu/rnn_kernels.h
  tests/experimental_rnn_test.py
Labels: pull ready

#25797 [aot] Add support for as_text(debug_info=True).
  CHANGELOG.md
  docs/aot.md
  jax/_src/stages.py
  tests/aot_test.py
  tests/api_test.py
  tests/name_stack_test.py
  tests/nn_test.py
  tests/pmap_test.py
  tests/shard_map_test.py
Labels: pull ready

#25800 [better_errors] Improve error message for lax.switch branches output structure mismatch
  jax/_src/lax/control_flow/common.py
  jax/_src/lax/control_flow/conditionals.py
  jax/experimental/sparse/transform.py
  tests/lax_control_flow_test.py
  tests/sparsify_test.py
Labels: pull ready

#20282 Implement column-pivoted QR via geqp3 (CPU lowering only)
  jax/_src/lax/linalg.py
  jax/_src/lax/svd.py
  jax/_src/numpy/linalg.py
  jax/_src/scipy/linalg.py
  jax/experimental/jax2tf/jax2tf.py
  jaxlib/cpu/cpu_kernels.cc
  jaxlib/cpu/lapack.cc
  jaxlib/cpu/lapack_kernels.cc
  jaxlib/cpu/lapack_kernels.h
  jaxlib/cpu/lapack_kernels_using_lapack.cc
  tests/linalg_test.py
Labels: pull ready

#25831 Avoid creating float0 JVPTracers
  jax/_src/interpreters/ad.py
Labels: pull ready

#25838 Simplify failure reporting for nightly CI job
  .github/workflows/parse_logs.py
  .github/workflows/upstream-nightly.yml
Labels: pull ready

#25787 Add a JVP rule for lax.linalg.tridiagonal_solve, fixing some bugs along the way
  jax/_src/lax/linalg.py
  tests/linalg_test.py
Labels: pull ready

#25791 fix grad(logsumexp) to produce 0s where `where` is False
  jax/_src/ops/special.py
  tests/lax_scipy_test.py
Labels: pull ready

#25741 jnp.linalg.solve: finalize deprecation of batched 1D solves
  CHANGELOG.md
  jax/_src/numpy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#25817 [internal] add deprecation test utilities
  jax/_src/test_util.py
  tests/deprecation_test.py
  tests/ffi_test.py
  tests/lax_numpy_reducers_test.py
  tests/lax_numpy_test.py
  tests/linalg_test.py
  tests/nn_test.py
Labels: pull ready

#25833 More linearize fixes
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/pxla.py
  jax/experimental/attrs.py
  jax/experimental/shard_map.py
Labels: pull ready

#25798 [better_errors] Ensure that tracer errors in for_loop point to use code
  jax/_src/api_util.py
  jax/_src/lax/control_flow/loops.py
  tests/lax_control_flow_test.py
Labels: pull ready

#25875 Mention expected tangent aval in error message, see #25517.
  jax/_src/api.py
Labels: pull ready

#25827 [better_errors] Add debug_info to DynamicJaxprTrace and JaxprStackFrame
  jax/_src/api.py
  jax/_src/api_util.py
  jax/_src/core.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/linear_util.py
  jax/_src/pjit.py
Labels: better_errors, pull ready

#25872 [jax2tf] Fix bitrot in docs
  jax/experimental/jax2tf/README.md
Labels: pull ready

#25864 More linearization fixes
  jax/_src/core.py
  jax/_src/interpreters/ad.py
  jax/experimental/shard_map.py
Labels: pull ready

#25911 Update the JAX version to 0.5.0.
  CHANGELOG.md
  jax/version.py
Labels: kokoro:force-run, pull ready

#25906 [ROCm] Add gfx12xx architecture support
  .bazelrc
  build/build.py
  build/rocm/Dockerfile.ms
  build/rocm/build_wheels/Dockerfile.manylinux_2_28_x86_64.rocm
  build/rocm/docker/Dockerfile.jax-ubu22
  build/rocm/docker/Dockerfile.jax-ubu24
  build/rocm/setup.rocm.sh
  build/rocm/tools/build_wheels.py
Labels: pull ready

#25917 [ROCm] Fix run_multi_gpu script multi-gpu issue and refactor code
  build/rocm/run_multi_gpu.sh
Labels: pull ready

#25952 Tweak documentation of jnp.cov to include scalar return for M = 1
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#25957 [key reuse] fix signature for device_put
  jax/experimental/key_reuse/_core.py
  tests/key_reuse_test.py
Labels: kokoro:force-run, pull ready

#25642 Fix backwards attention test for larger head dims
  jax/experimental/pallas/ops/gpu/attention.py
  tests/pallas/BUILD
  tests/pallas/gpu_ops_test.py
Labels: pull ready

#25936 Add ensure_arraylike utility for lax.numpy implementations
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
Labels: pull ready

#25958 Add performance note at the top of sparse docs
  docs/jax.experimental.sparse.rst
Labels: pull ready

#25961 Merge 0.5.0 release branch and update version numbers.
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: kokoro:force-run, pull ready

#25962 Remove code that supported jaxlib < 0.5.
  jax/_src/compiler.py
  jax/_src/lax/linalg.py
  jax/_src/pallas/mosaic/lowering.py
  jax/_src/xla_bridge.py
  tests/cache_key_test.py
  tests/compilation_cache_test.py
  tests/export_back_compat_test.py
  tests/lax_numpy_test.py
  tests/linalg_test.py
  tests/magma_linalg_test.py
  tests/pallas/tpu_ops_test.py
  tests/pallas/tpu_pallas_test.py
  tests/pgle_test.py
  tests/shard_map_test.py
Labels: pull ready

#25976 add f-string to mosaic memory space error msg
  jax/_src/pallas/mosaic/lowering.py
Labels: pull ready

#25969 internal: check integer overflow in lax.asarray
  jax/_src/lax/lax.py
  jax/_src/numpy/util.py
Labels: pull ready

#25916 [better_errors] Improvements in propagation of debugging info
  jax/_src/ad_checkpoint.py
  jax/_src/api.py
  jax/_src/api_util.py
  jax/_src/core.py
  jax/_src/custom_derivatives.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/linear_util.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pjit.py
  jax/_src/state/discharge.py
  tests/state_test.py
Labels: pull ready

#25988 [better_errors] Refactor debug info tests
  tests/BUILD
  tests/api_test.py
  tests/debug_info_test.py
  tests/lax_control_flow_test.py
  tests/pmap_test.py
Labels: pull ready

#25984 Replace exp2 with exp
  jax/experimental/pallas/ops/gpu/attention.py
Labels: pull ready

#25982 Update docs of callbacks
  docs/external-callbacks.md
  jax/_src/callback.py
  jax/_src/debugging.py
Labels: pull ready

#25647 Fix attention backwards pass
  jax/experimental/pallas/ops/gpu/attention.py
  tests/pallas/gpu_ops_test.py
Labels: pull ready

#25992 [better_errors] Ensure debug_info.arg_names is never None.
  jax/_src/ad_checkpoint.py
  jax/_src/api_util.py
  jax/_src/core.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/linear_util.py
  jax/_src/pallas/core.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pjit.py
  tests/debug_info_test.py
  tests/pallas/pallas_test.py
Labels: pull ready

#26028 [better_errors] Expand the tests for debug_info
  jax/_src/jaxpr_util.py
  tests/BUILD
  tests/debug_info_test.py
Labels: pull ready

#26024 jax.numpy setops: use ensure_arraylike & avoid asarray
  jax/_src/numpy/setops.py
Labels: pull ready

#26044 Set __slots__ on core.Trace subclasses.
  jax/_src/core.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/interpreters/pxla.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jet.py
  jax/experimental/shard_map.py
  jax/experimental/sparse/transform.py
Labels: pull ready

#25889 Fix cache init when JAX Array is created early (#25768)
  jax/_src/compilation_cache.py
  tests/compilation_cache_test.py
Labels: pull ready

#26050 DOC: mention adoption of EffVer in JEP
  docs/jep/25516-effver.md
Labels: pull ready

#26060 Remove code that sets CUDA rpath option from .bazelrc.
  .bazelrc
Labels: pull ready

#26063 internal: move more NumPy APIs to ensure_arraylike
  jax/_src/numpy/fft.py
  jax/_src/numpy/polynomial.py
Labels: pull ready

#26046 increase sdpa dbias unit test error tolerance
  tests/nn_test.py
Labels: pull ready

#26072 Add jax.test_util to public API docs
  docs/jax.rst
  docs/jax.test_util.rst
  jax/_src/public_test_util.py
Labels: pull ready

#26082 docs: outdated link for index update syntax
  docs/notebooks/thinking_in_jax.ipynb
  docs/notebooks/thinking_in_jax.md
Labels: pull ready

#25839 Adding GPU paged attention kernel
  jax/experimental/pallas/ops/gpu/paged_attention.py
  tests/pallas/BUILD
  tests/pallas/gpu_paged_attention_test.py
Labels: pull ready

#25963 Add DCE rules for custom_jvp and custom_vjp
  jax/_src/custom_derivatives.py
  tests/api_test.py
Labels: pull ready

#26092 improve make_array_from_single_device_arrays error
  jax/_src/array.py
  tests/array_test.py
Labels: pull ready

#26093 [better_errors] Add more debug info test coverage
  tests/BUILD
  tests/api_test.py
  tests/debug_info_test.py
Labels: pull ready

#26097 [better_errors] Refactor more uses of pe.tracing_debug_info (part 1)
  jax/_src/ad_checkpoint.py
  jax/_src/api_util.py
  jax/_src/custom_batching.py
  jax/_src/custom_dce.py
  jax/_src/interpreters/batching.py
  jax/_src/lax/control_flow/common.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/control_flow/solves.py
  jax/_src/lax/lax.py
  tests/debug_info_test.py
Labels: pull ready

#26099 [better_errors] Refactor more uses of pe.tracing_debug_info (part 2)
  jax/_src/pallas/core.py
  jax/_src/pallas/pallas_call.py
  tests/debug_info_test.py
Labels: pull ready

#26128 jnp.linalg.norm: better documentation & error text for axis
  jax/_src/numpy/linalg.py
Labels: pull ready

#26129 DOC: update osx x86 entry in installation grid
  docs/installation.md
Labels: pull ready

#26133 tpu_pallas_distributed_test: skip unless on TPU
  tests/pallas/tpu_pallas_distributed_test.py
Labels: kokoro:force-run, pull ready

#25213 Support dynamic masks in splash attention
  jax/experimental/pallas/ops/tpu/splash_attention/splash_attention_kernel.py
  jax/experimental/pallas/ops/tpu/splash_attention/splash_attention_mask_info.py
  tests/pallas/tpu_splash_attention_kernel_test.py
  tests/pallas/tpu_splash_attention_mask_test.py
Labels: pull ready

#26134 [Pallas] Be explicit about accumulation dtype in reference impls
  jax/experimental/pallas/ops/gpu/paged_attention.py
  tests/pallas/ops_test.py
  tests/pallas/pallas_test.py
Labels: pull ready

#24898 Added CI job with TSAN and free-threading
  .github/workflows/requirements_lock_3_13_ft.patch
  .github/workflows/tsan-suppressions.txt
  .github/workflows/tsan.yaml
Labels: pull ready

#26157 DOC: avoid deprecated argument in external callbacks
  docs/external-callbacks.md
Labels: pull ready

#26154 DOC: add discussion of exceptions in pure_callback
  docs/external-callbacks.md
  jax/_src/callback.py
Labels: pull ready

#26151 [better_errors] Expand debug info testing with eager mode, and MLIR module checking.
  jax/_src/interpreters/mlir.py
  jax/_src/test_util.py
  tests/debug_info_test.py
Labels: pull ready

#25980 Add test case for jit compile of vmap on gpu
  tests/jax_jit_test.py
Labels: pull ready

#26188 Revert #25982 since callbacks can now use JAX functions
  docs/external-callbacks.md
  jax/_src/callback.py
  jax/_src/debugging.py
Labels: pull ready

#26100 [better_errors] Refactor more uses of pe.tracing_debug_info (part 3)
  jax/_src/api.py
  jax/_src/api_util.py
  jax/_src/checkify.py
  jax/_src/core.py
  jax/_src/custom_partitioning.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/interpreters/pxla.py
  jax/_src/linear_util.py
  jax/_src/pjit.py
  jax/interpreters/partial_eval.py
  tests/debug_info_test.py
Labels: pull ready

#26189 Added CPython cache steps in tsan.yaml CI workflow
  .github/workflows/tsan.yaml
Labels: pull ready

#26208 Skip ragged collective tests on CPU
  tests/ragged_collective_test.py
Labels: pull ready

#26221 Disable source mapper test for optimized hlo
  tests/source_mapper_test.py
Labels: pull ready

#26218 [array api] bump test suite to latest commit
  .github/workflows/jax-array-api.yml
Labels: pull ready

#26220 jax.lax: improve documentation for several functions
  jax/_src/lax/lax.py
Labels: documentation, pull ready

#26236 Adjust docs/conf.py to remove prompt when copying docs examples by default
  docs/conf.py
Labels: pull ready

#26194 Improve `jax.distributed.initialize` runtime error message
  jax/_src/distributed.py
Labels: pull ready

#26239 test: change random matrix generation for Rotation
  tests/scipy_spatial_test.py
Labels: pull ready

#26238 Disable two tests of GC behavior if there are multiple threads per pr…
  tests/core_test.py
Labels: pull ready

#26247 Add additional tsan suppressions for races.
  .github/workflows/tsan-suppressions.txt
Labels: pull ready

#26195 Add TSAN numpy step
  .github/workflows/tsan.yaml
Labels: pull ready

#26249 Fix dtype issue in stirling approximation
  jax/_src/random.py
  tests/random_lax_test.py
Labels: pull ready

#25766 Add mode='fan_geo_avg' to nn.initializers.variance_scaling.
  jax/_src/nn/initializers.py
  tests/nn_test.py
Labels: pull ready
