Repository jax-ml/jax, pull requests merged in 2025-03, with the labels that each got.

#26697 Use the same name for aliased Vars when pretty-printing Jaxprs.
  jax/_src/core.py
  jax/_src/lax/lax.py
  jax/_src/pjit.py
  tests/pjit_test.py
Labels: pull ready

#26895 Fix wrong results in multidimensional pad.
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: pull ready

#26876 Fix linalg.norm to return zero for proper norms of empty matrices.
  jax/_src/numpy/linalg.py
  tests/linalg_test.py
Labels: pull ready

#26897 doc: in lax.cond, note that both branches will be traced
  jax/_src/lax/control_flow/conditionals.py
Labels: documentation, kokoro:force-run, pull ready

#26862 doc: fix description of logsumexp axis
  jax/_src/ops/special.py
Labels: documentation, pull ready

#26865 Improved errors when indexing with floats
  jax/_src/numpy/indexing.py
  tests/lax_numpy_indexing_test.py
Labels: better_errors, kokoro:force-run, pull ready

#26883 Update jnp.unique to support upstream interface changes.
  jax/_src/numpy/setops.py
  tests/lax_numpy_test.py
Labels: pull ready

#26765 fix Initializer protocol
  jax/_src/nn/initializers.py
Labels: pull ready

#26912 Improve error messages when input argument resolution fails in custom_* APIs.
  jax/_src/api_util.py
  jax/_src/custom_batching.py
  jax/_src/custom_dce.py
  jax/_src/custom_derivatives.py
  tests/api_test.py
Labels: pull ready

#26916 Update array-api-tests to latest commit
  .github/workflows/jax-array-api.yml
Labels: pull ready

#26901 Fix detection of epath
  jax/_src/compilation_cache_interface.py
  jax/_src/path.py
Labels: pull ready

#26641 jax.numpy ndim/shape/size: deprecate non-array input
  CHANGELOG.md
  jax/_src/numpy/util.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: pull ready

#26627 Remove fmha rewriter dependency in cuDNN SDPA api
  jax/_src/cudnn/fused_attention_stablehlo.py
  tests/fused_attention_stablehlo_test.py
Labels: pull ready

#26691 fix member access to packed CUDA struct
  jaxlib/mosaic/gpu/mosaic_gpu_ext.cc
Labels: pull ready

#26934 Remove a TSAN suppression.
  .github/workflows/tsan-suppressions.txt
Labels: pull ready, free threading

#26952 vmap mismatch size error message: handle *args
  jax/_src/api.py
  tests/api_test.py
Labels: pull ready

#26927 Merge release/0.5.2 + version bump
  CHANGELOG.md
  jax/version.py
Labels: pull ready

#26950 add pmap axes hints
  jax/_src/api.py
Labels: pull ready

#26979 [mutable-arrays] read values should have the same explicit sharding as ref
  jax/_src/state/indexing.py
  jax/_src/state/primitives.py
  jax/_src/state/types.py
  tests/mutable_array_test.py
Labels: pull ready

#27001 [scan] when num_trips==0, don't generate weird size-zero reshapes
  jax/_src/lax/control_flow/loops.py
Labels: pull ready

#26427 [direct-linearize] shmap and final-style fixes
  jax/_src/api.py
  jax/_src/core.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/lax.py
  jax/_src/mesh.py
  jax/_src/pjit.py
  jax/_src/state/primitives.py
  jax/experimental/shard_map.py
  tests/core_test.py
  tests/mutable_array_test.py
  tests/pmap_test.py
  tests/shard_map_test.py
Labels: pull ready

#27005 fixups that we meant to include in #26427
  jax/_src/interpreters/ad.py
  jax/_src/state/primitives.py
  tests/debug_info_test.py
Labels: pull ready

#27010 [direct-linearize] fix name_stack bugs
  jax/_src/interpreters/ad.py
  jax/_src/source_info_util.py
Labels: pull ready

#27006 A few more fixes for debug_info tests with direct_linearize.
  jax/_src/pjit.py
  tests/debug_info_test.py
  tests/pmap_test.py
Labels: pull ready

#26811 Update ad.backward_pass to support non-linear functions of constants
  jax/_src/interpreters/ad.py
  tests/api_test.py
Labels: pull ready

#27032 Avoid using array operations within lax.py operations.
  jax/_src/lax/lax.py
Labels: pull ready

#27035 Add file and zip to tsan.yaml
  .github/workflows/tsan.yaml
Labels: pull ready

#26977 Prevent tracer leaks in scipy.special.expn
  jax/_src/scipy/special.py
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#27038 Internal: make it easier to detect the vmap sentinel
  jax/_src/api_util.py
  tests/api_test.py
Labels: pull ready

#26839 Fixed printing order of results in `jax.debug.print` documentation
  docs/debugging/print_breakpoint.md
Labels: pull ready

#26840 DOC: Remove duplicate `JAX version 0.4.37` heading in `Changelog`
  CHANGELOG.md
Labels: pull ready

#27059 jax.disable_jit: ensure while_loop behaves similarly to non-disable_jit version
  jax/_src/lax/control_flow/loops.py
  tests/lax_control_flow_test.py
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#20699 Fix scipy.special.gammainc/gammaincc evaluation at boundary points
  jax/_src/lax/special.py
  jax/_src/scipy/stats/gamma.py
  jax/experimental/jax2tf/tests/jax2tf_limitations.py
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#27041 Fix the ValueError message for random.binomial (forgot to use string formatting).
  jax/_src/random.py
Labels: pull ready

#27092 Update gammainc and gammaincc against scipy 1.16
  jax/_src/lax/special.py
  tests/lax_scipy_special_functions_test.py
Labels: pull ready

#27044 Add navigation breadcrumbs to docs.
  docs/_static/style.css
  docs/conf.py
Labels: pull ready

#26524 Add jax.random.multinomial.
  CHANGELOG.md
  docs/jax.random.rst
  jax/_src/random.py
  jax/random.py
  tests/random_lax_test.py
Labels: pull ready

#26944 Support NVFP4 in scaled_matmul and scaled_dot_general
  jax/_src/cudnn/scaled_matmul_stablehlo.py
  tests/scaled_matmul_stablehlo_test.py
Labels: pull ready

#27165 Explicit sharding docs
  docs/advanced_guide.rst
  docs/conf.py
  docs/notebooks/explicit-sharding.ipynb
  docs/notebooks/explicit-sharding.md
Labels: pull ready

#27173 Fix notebook formatting
  docs/notebooks/explicit-sharding.ipynb
Labels: kokoro:force-run, pull ready

#27015 [direct-linearize] shmap fixes
  jax/_src/interpreters/ad.py
  jax/experimental/shard_map.py
Labels: pull ready

#27174 add experimental lax.optimization_barrier autodiff rules
  jax/_src/lax/lax.py
  tests/lax_test.py
Labels: pull ready

#27177 Add an example to the sharding-in-types doc about mixing modes
  docs/notebooks/explicit-sharding.ipynb
  docs/notebooks/explicit-sharding.md
Labels: pull ready

#27176 Better docs for jax.lax add/sub/mul/div
  jax/_src/lax/lax.py
Labels: documentation, pull ready

#27157 Use `lax.top_k` instead of jnp.argsort in Gumbel top-k trick for weighted sampling in `jax.random.choice`
  jax/_src/random.py
Labels: pull ready

#26980 Add replace option to random.categorical to enable sampling without replacement.
  CHANGELOG.md
  jax/_src/random.py
  tests/random_lax_test.py
Labels: pull ready

#27164 [CI] Add B200 1GPU continuous job
  .github/workflows/pytest_cuda.yml
  .github/workflows/wheel_tests_continuous.yml
Labels: kokoro:force-run, pull ready, CI Connection Halt - On Retry

#27198 jax.lax: improve docs for several APIs
  jax/_src/lax/lax.py
Labels: documentation, pull ready

#27094 TSAN yaml CI job fix for numpy dependency
  .github/workflows/requirements_lock_3_13_ft.patch
  .github/workflows/tsan.yaml
Labels: pull ready

#27227 [Pallas] Adds option to init buffers to NaNs or zeros in TPU interpret mode
  jax/_src/pallas/mosaic/interpret.py
  tests/pallas/tpu_pallas_interpret_test.py
Labels: pull ready

#27258 Fix lint error on main
  jax/experimental/pallas/ops/tpu/ragged_paged_attention.py
  tests/pallas/tpu_ragged_paged_attention_test.py
Labels: pull ready

#27255 Rename arguments x, y of assertAllClose and friends to actual, desired.
  jax/_src/test_util.py
Labels: pull ready

#27260 Merge release/0.5.3 branch into main, update version numbers.
  .github/workflows/wheel_win_x64.yml
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: pull ready

#27254 [Pallas] Fix input_output_aliases for non-HBM kernel args in TPU interpret mode.
  jax/_src/pallas/mosaic/interpret.py
  tests/pallas/tpu_pallas_interpret_test.py
Labels: pull ready

#27274 Fixes the stream annotation compute on box.
  jax/_src/interpreters/mlir.py
  tests/memories_test.py
Labels: kokoro:force-run, pull ready

#27273 Fix doc for random.categorical replace argument.
  jax/_src/random.py
Labels: kokoro:force-run, pull ready

#27107 Update handling of betainc edge cases
  jax/_src/lax/special.py
  jax/_src/test_util.py
  tests/lax_scipy_special_functions_test.py
Labels: kokoro:force-run, pull ready

#26387 Add sharding support for dynamic masks in TPU splash attention
  jax/experimental/pallas/ops/tpu/splash_attention/splash_attention_kernel.py
  jax/experimental/pallas/ops/tpu/splash_attention/splash_attention_mask_info.py
  tests/pallas/BUILD
  tests/pallas/tpu_splash_attention_kernel_sharded_test.py
  tests/pallas/tpu_splash_attention_kernel_test.py
  tests/pallas/tpu_splash_attention_mask_test.py
Labels: kokoro:force-run, pull ready

#27034 Enable multi-threading in Jax Context with shared thread pool
  jax/_src/interpreters/mlir.py
Labels: kokoro:force-run, pull ready, free threading

#27238 [CI] Create optional cuda presubmit.
  .github/workflows/bazel_optional_cuda.yml
Labels: pull ready

#26624 Bump ml_dtypes>=0.5.0
  setup.py
Labels: kokoro:force-run, pull ready

#27308 Increased test timeout in TSAN CI
  .github/workflows/tsan.yaml
  tests/nn_test.py
Labels: kokoro:force-run, pull ready

#27326 Increase the test timeout for tsan builds.
  .github/workflows/tsan-suppressions.txt
Labels: pull ready

#27353 fix a linearize-of-remat-of-while_loop-fixpoint bug
  jax/_src/lax/control_flow/loops.py
  tests/lax_control_flow_test.py
Labels: kokoro:force-run, pull ready

#27337 [Pallas] Fixes scalar prefetch in TPU interpret mode.
  jax/_src/pallas/mosaic/interpret.py
  tests/pallas/tpu_pallas_interpret_test.py
Labels: pull ready

#27364 Reenable tsan suppression, mark some tests as thread-unsafe.
  .github/workflows/tsan-suppressions.txt
  .github/workflows/tsan.yaml
  tests/cache_key_test.py
  tests/pjit_test.py
Labels: pull ready

#26775 [ROCm] Fix ROCm builds not finding numa library
  build/rocm/build_wheels/Dockerfile.manylinux_2_28_x86_64.rocm
Labels: pull ready

#27266 jax.numpy: add tests for __jax_array__ handling
  tests/BUILD
  tests/array_extensibility_test.py
Labels: kokoro:force-run, pull ready

#27380 Fix mac wheel build.
  jaxlib/tools/build_wheel.py
Labels: kokoro:force-run, pull ready

#27363 Small cleanup to pretty-printer.
  jax/_src/pretty_printer.py
Labels: kokoro:force-run, pull ready

#27398 [attrs] allow setattr on a previously non-existent attr
  jax/_src/interpreters/partial_eval.py
  jax/_src/pjit.py
  jax/experimental/attrs.py
  tests/attrs_test.py
Labels: kokoro:force-run, pull ready

#27313 [Pallas] In TPU interpret mode, add initial barrier for kernels without one
  jax/_src/pallas/mosaic/interpret.py
  tests/pallas/tpu_pallas_interpret_distributed_test.py
Labels: pull ready

#27382 [ROCm] Constrain auditwheel to >=6,<6.3
  build/rocm/tools/build_wheels.py
Labels: kokoro:force-run, pull ready

#26673 [Pallas] [1/3] Move communication primitives from mosaic to core
  jax/_src/pallas/core.py
  jax/_src/pallas/mosaic/core.py
  jax/_src/pallas/mosaic/helpers.py
  jax/_src/pallas/mosaic/interpret.py
  jax/_src/pallas/mosaic/lowering.py
  jax/_src/pallas/mosaic/primitives.py
  jax/_src/pallas/primitives.py
  jax/experimental/pallas/__init__.py
  jax/experimental/pallas/tpu.py
Labels: kokoro:force-run, pull ready

#26292 Finalize some deprecations from jax.lib.xla_client
  CHANGELOG.md
  jax/lib/xla_client.py
Labels: kokoro:force-run, pull ready

#27394 Support __jax_array__ in jnp.full_like & co
  jax/_src/numpy/array_creation.py
  tests/array_extensibility_test.py
Labels: kokoro:force-run, pull ready

#27017 add jax.experimental.saved_input_vjp to let user pass primal inputs to bwd pass
  jax/_src/api.py
  jax/experimental/__init__.py
  tests/api_test.py
Labels: pull ready

#27448 Some codebase fixes required for python 3.14
  jax/_src/basearray.py
  jax/_src/util.py
Labels: kokoro:force-run, pull ready

#27421 Clean up a number of finalized deprecations
  jax/__init__.py
  jax/_src/numpy/lax_numpy.py
  jax/core.py
  jax/interpreters/xla.py
  jax/lib/xla_bridge.py
  jax/lib/xla_client.py
  jax/numpy/__init__.py
  jax/numpy/__init__.pyi
  jax/sharding.py
  tests/lax_numpy_test.py
Labels: kokoro:force-run, pull ready

#27404 Add pascal matrix to jax.scipy.linalg
  docs/jax.scipy.rst
  jax/_src/scipy/linalg.py
  jax/scipy/linalg.py
  tests/linalg_test.py
Labels: kokoro:force-run, pull ready

#27530 Add sm_100 and sm_120 to the list of CUDA GPU achitectures for which …
  .bazelrc
Labels: kokoro:force-run, pull ready

#27536 allow saved_input_vjp functions to be jit inputs/outputs
  jax/_src/api.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#27444 Deprecate jax.tree_* aliases
  CHANGELOG.md
  jax/__init__.py
Labels: kokoro:force-run, pull ready

#27445 [Pallas] A few fixes for TPU interpret mode:
  jax/_src/pallas/mosaic/BUILD
  jax/_src/pallas/mosaic/interpret.py
Labels: pull ready

#27562 Fixes failing FFI example builds.
  examples/ffi/pyproject.toml
Labels: kokoro:force-run, pull ready

#27558 Marked some tests as thread_unsafe_test
  tests/api_test.py
  tests/pjit_test.py
Labels: kokoro:force-run, pull ready

#27488 [array API] make capabilities more accurate
  jax/_src/numpy/array_api_metadata.py
  tests/array_api_test.py
Labels: pull ready

#27575 Set NB_DOMAIN=jax
  .bazelrc
Labels: kokoro:force-run, pull ready

#27579 Implement `nbytes` for `PRNGKeyArray`
  jax/_src/prng.py
  tests/random_test.py
Labels: kokoro:force-run, pull ready

#27525 cleanup now that we depend on ml_dtypes>=0.5
  jax/_src/dtypes.py
  jax/_src/export/serialization.py
  jax/_src/interpreters/mlir.py
  jax/_src/lax/lax.py
  jax/_src/numpy/scalar_types.py
  jax/_src/public_test_util.py
  jax/_src/test_util.py
  jax/numpy/__init__.py
  jax/tools/jax_to_ir.py
  jaxlib/xla/xla_client.py
  tests/dtypes_test.py
  tests/jax_to_ir_test.py
Labels: pull ready

#27583 scan: improve docs & errors around dynamic length
  jax/_src/lax/control_flow/loops.py
Labels: documentation, better_errors, kokoro:force-run, pull ready

#27309 add discord release action
  .github/workflows/community_release_actions.yml
Labels: kokoro:force-run, pull ready

#27585 DOC: add documentation note about default dtypes
  docs/default_dtypes.md
  docs/notes.rst
  docs/user_guides.rst
  jax/_src/numpy/array_creation.py
Labels: documentation, kokoro:force-run, pull ready

#27446 jax.core: finalize a number of deprecations for JAX v0.6.0
  CHANGELOG.md
  jax/core.py
Labels: kokoro:force-run, pull ready

#27616 [array api] return all devices in devices()
  jax/_src/numpy/array_api_metadata.py
  tests/array_api_test.py
Labels: kokoro:force-run, pull ready

#27627 __jax_array__: add support in jnp.reshape, jnp.transpose, jnp.matrix_transpose
  jax/_src/numpy/lax_numpy.py
  tests/array_extensibility_test.py
Labels: kokoro:force-run, pull ready
