Repository jax-ml/jax, pull requests merged in 2025-02, with the labels that each got.

#26174 Make `JAX_CPU_COLLECTIVES_IMPLEMENTATION` and `JAX_NUM_CPU_DEVICES` env vars
  CHANGELOG.md
  jax/_src/config.py
  jax/_src/test_util.py
  jax/_src/xla_bridge.py
Labels: pull ready

#26243 Avoid call to asarray in jnp.einsum
  jax/_src/numpy/lax_numpy.py
Labels: pull ready

#25812 Add cuDNN flash attention sequence packing
  jax/_src/cudnn/fused_attention_stablehlo.py
  tests/fused_attention_stablehlo_test.py
Labels: pull ready

#25474 Update compilation docs with a note on mocking GPUs
  docs/persistent_compilation_cache.md
Labels: pull ready

#26261 Fix folder problem in TSAN numpy step
  .github/workflows/tsan.yaml
Labels: pull ready

#26262 [better_errors] Merge the JaxprDebugInfo and TracingDebugInfo into core.DebugInfo
  jax/_src/ad_checkpoint.py
  jax/_src/api.py
  jax/_src/api_util.py
  jax/_src/checkify.py
  jax/_src/core.py
  jax/_src/custom_batching.py
  jax/_src/custom_dce.py
  jax/_src/custom_partitioning.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/control_flow/common.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/control_flow/solves.py
  jax/_src/lax/lax.py
  jax/_src/linear_util.py
  jax/_src/pallas/core.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pjit.py
  jax/_src/state/discharge.py
  jax/core.py
  tests/debug_info_test.py
Labels: pull ready

#26246 jax.lax: improve docs for floor, ceil, round.
  jax/_src/lax/lax.py
Labels: documentation, pull ready

#26277 Format sourcemap directory names to work on windows
  jax/experimental/source_mapper/generate_map.py
Labels: pull ready

#25688 Add jax.random.multinomial.
  CHANGELOG.md
  docs/jax.random.rst
  jax/_src/random.py
  jax/random.py
  tests/random_lax_test.py
Labels: pull ready

#26275 Handle effects in lax.custom_linear_solve
  jax/_src/lax/control_flow/solves.py
  tests/custom_linear_solve_test.py
Labels: pull ready

#25655 Simplify implementation of random.orthogonal.
  jax/_src/random.py
Labels: pull ready

#26290 [direct-linearize] fix name stack tests
  jax/_src/interpreters/ad.py
  tests/name_stack_test.py
Labels: pull ready

#26289 documentation: fix function name
  docs/autodidax.ipynb
  docs/autodidax.md
  docs/autodidax.py
Labels: pull ready

#26300 Set cron to 05:00 UTC in tsan.yaml
  .github/workflows/tsan.yaml
Labels: pull ready

#26302 Readded missing part to use locally built numpy in the build in tsan.yml
  .github/workflows/tsan.yaml
Labels: pull ready

#26307 Remove the FFI examples workflow cache
  .github/workflows/ci-build.yaml
Labels: pull ready

#26310 Use uv for dependency resolution on CI
  .github/workflows/ci-build.yaml
  .github/workflows/jax-array-api.yml
Labels: pull ready

#26281 jax.lax: improve docs for exp & log functions
  jax/_src/lax/lax.py
Labels: documentation, pull ready

#26325 Remove libtpu-nightly dependency from jax[tpu].
  CHANGELOG.md
  setup.py
Labels: pull ready

#26324 skip tests with extra requirements
  tests/colocated_python_test.py
  tests/export_test.py
Labels: pull ready

#26159 [Mosaic GPU] Add simple Blackwell matmul example
  jax/experimental/mosaic/gpu/examples/matmul_blackwell.py
Labels: pull ready

#26313 [better_errors] Add debug info to the Jaxprs formed for AD (step 2)
  jax/BUILD
  jax/_src/ad_checkpoint.py
  jax/_src/api.py
  jax/_src/api_util.py
  jax/_src/checkify.py
  jax/_src/core.py
  jax/_src/custom_derivatives.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/control_flow/common.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/control_flow/solves.py
  jax/_src/lax/lax.py
  jax/_src/linear_util.py
  jax/_src/pjit.py
  jax/_src/state/discharge.py
  jax/experimental/shard_map.py
  tests/api_test.py
  tests/debug_info_test.py
Labels: pull ready

#26259 feat(gh-13291): Add exponential distribution functions: `cdf`, `logcdf`, `sf`, `logsf`, and `ppf`
  docs/jax.scipy.rst
  jax/_src/scipy/stats/expon.py
  jax/scipy/stats/expon.py
  tests/scipy_stats_test.py
Labels: pull ready

#26339 doc: add note about f16 casting in jnp.mean
  jax/_src/numpy/reductions.py
Labels: pull ready

#26363 [mutable-arrays] tweak an error message on mutable arrays
  jax/_src/interpreters/partial_eval.py
Labels: pull ready

#26342 doc: improve docs for jax.lax trig functions
  docs/jax.lax.rst
  jax/_src/lax/lax.py
Labels: documentation, pull ready

#26369 Temporarily disable source mapper on win32
  tests/source_mapper_test.py
Labels: pull ready

#25097 Start a new TPU interpret mode for Pallas
  jax/BUILD
  jax/_src/pallas/mosaic/BUILD
  jax/_src/pallas/mosaic/interpret.py
  jax/_src/pallas/pallas_call.py
  tests/pallas/BUILD
  tests/pallas/tpu_pallas_interpret_distributed_test.py
  tests/pallas/tpu_pallas_interpret_test.py
Labels: pull ready

#26372 refactor: move scalar type defs out of lax_numpy.py
  jax/_src/lax/eigh.py
  jax/_src/numpy/fft.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/linalg.py
  jax/_src/numpy/scalar_types.py
  jax/_src/ops/scatter.py
  jax/_src/scipy/linalg.py
  jax/_src/scipy/stats/kde.py
  jax/_src/third_party/scipy/special.py
  jax/numpy/__init__.py
Labels: kokoro:force-run, pull ready

#26375 DOC: update numpy/scipy versions in deprecation doc
  docs/deprecation.md
Labels: documentation, pull ready

#26380 Remove the tutorial about legacy custom calls
  docs/Custom_Operation_for_GPUs.md
  docs/Custom_Operation_for_GPUs.py
  docs/_tutorials/advanced-compilation.md
  docs/conf.py
  docs/extensions.rst
  docs/gpu_ops/gpu_ops.cpp
  docs/gpu_ops/kernel_helpers.h
  docs/gpu_ops/kernels.h
  docs/gpu_ops/pybind11_kernel_helpers.h
  docs/gpu_ops/rms_norm_kernels.cu
Labels: kokoro:force-run, pull ready

#26368 Fix invalid lowerings for ROCm in Pallas
  jax/_src/pallas/triton/lowering.py
Labels: pull ready

#26344 disable cuDNN flash attention head dim 256 on blackwell
  jax/_src/cudnn/fused_attention_stablehlo.py
  tests/fused_attention_stablehlo_test.py
Labels: pull ready

#25810 [ROCm] Add post-merge check on main for AMD GPUs
  .github/workflows/rocm-ci.yml
  build/rocm/build_wheels/Dockerfile.manylinux_2_28_x86_64.rocm
  build/rocm/ci_build
  build/rocm/run_single_gpu.py
  build/rocm/tools/build_wheels.py
Labels: pull ready

#26383 refactor: move sorting ops out of lax_numpy
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/setops.py
  jax/_src/numpy/sorting.py
  jax/numpy/__init__.py
  tests/debug_info_test.py
Labels: pull ready

#26409 Fix a missing "f" on an f-string.
  build/tools/utils.py
Labels: pull ready

#26376 refactor: move array creation routines out of lax_numpy.py
  jax/_src/dtypes.py
  jax/_src/numpy/array_creation.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
  jax/numpy/__init__.py
Labels: pull ready

#26377 [mutable-arrays] persist shardings through xla computations
  jax/_src/core.py
  jax/_src/interpreters/pxla.py
  tests/mutable_array_test.py
Labels: pull ready

#26406 jax.lax: better docs for hyperbolic trig functions
  jax/_src/lax/lax.py
Labels: documentation, pull ready

#26407 DOC: make clear that printoptions are NumPy aliases
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: documentation, pull ready

#26436 Bump the minimum Mac OS X version for x86 builds to 11.0.
  .bazelrc
  jaxlib/jax.bzl
Labels: pull ready

#26426 Document behavior of linalg.solve in case the system matrix is singular
  jax/_src/numpy/linalg.py
  jax/_src/scipy/linalg.py
Labels: pull ready

#26450 Fix debug_info_test.py regexp for Windows paths.
  tests/debug_info_test.py
Labels: pull ready, windows:force-run

#26399 [better_errors] Continue adding debug info to Jaxprs (step 6)
  jax/_src/api_util.py
  jax/_src/checkify.py
  jax/_src/custom_derivatives.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/control_flow/solves.py
  jax/_src/linear_util.py
  jax/_src/pallas/mosaic/lowering.py
  jax/_src/pallas/pallas_call.py
  jax/_src/state/utils.py
  jax/experimental/attrs.py
  jax/experimental/jax2tf/jax2tf.py
  jax/experimental/jax2tf/tests/shape_poly_test.py
  jax/experimental/shard_map.py
  jax/experimental/sparse/bcoo.py
  jax/experimental/sparse/transform.py
  tests/core_test.py
  tests/debug_info_test.py
  tests/shard_map_test.py
Labels: pull ready

#26470 jax.lax: improve docs for real, imag, complex, conj, and abs.
  jax/_src/lax/lax.py
Labels: documentation, pull ready

#26446 Add public wrappers for lax monoidal reductions.
  CHANGELOG.md
  docs/jax.lax.rst
  jax/_src/internal_test_util/lax_test_util.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/lax/lax.py
  jax/_src/lax/parallel.py
  jax/_src/lax/slicing.py
  jax/experimental/jet.py
  jax/lax/__init__.py
  tests/core_test.py
  tests/filecheck/array.filecheck.py
  tests/lax_test.py
Labels: pull ready

#26476 update AOT walkthrough to cover explicit tracing stage
  docs/aot.md
Labels: pull ready

#26478 docstrings and API reference doc listing for the traced AOT stage
  docs/jax.stages.rst
  jax/_src/stages.py
Labels: kokoro:force-run, pull ready

#26455 [better_errors] Continue adding debug info to Jaxprs (step 8)
  jax/_src/custom_partitioning.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/pxla.py
  jax/_src/linear_util.py
  jax/experimental/shard_map.py
  tests/pallas/tpu_pallas_test.py
Labels: pull ready

#25955 Enable pivoted QR on GPU via MAGMA.
  CHANGELOG.md
  jax/_src/lax/linalg.py
  jax/_src/scipy/linalg.py
  jaxlib/ffi_helpers.h
  jaxlib/gpu/hybrid.cc
  jaxlib/gpu/hybrid_kernels.cc
  jaxlib/gpu/hybrid_kernels.h
  jaxlib/gpu/solver_kernels_ffi.cc
  tests/linalg_test.py
  tests/magma_linalg_test.py
Labels: pull ready

#24910 Add JAX_COMPILATION_CACHE_EXPECT_PGLE option
  jax/_src/compilation_cache.py
  jax/_src/compiler.py
  jax/_src/config.py
  jax/_src/profiler.py
  pyproject.toml
  tests/pgle_test.py
Labels: pull ready

#26403 jax.numpy reductions: avoid upcast of f16 when dtype is specified by user
  jax/_src/numpy/reductions.py
  tests/lax_numpy_reducers_test.py
Labels: pull ready

#26503 Fix doc string for PmapSharding
  jax/_src/sharding_impls.py
Labels: pull ready

#26373 Part 1 of a new autodidax based on "stackless"
  docs/autodidax2_part1.ipynb
  docs/autodidax2_part1.md
  docs/autodidax2_part1.py
  docs/conf.py
  docs/contributor_guide.rst
Labels: pull ready

#26486 Migrated to mypy 1.15.0 with --allow_redefinition
  .pre-commit-config.yaml
  jax/_src/checkify.py
  jax/_src/debugging.py
  jax/_src/image/scale.py
  jax/_src/interpreters/pxla.py
  jax/_src/numpy/polynomial.py
  jax/_src/numpy/ufunc_api.py
  jax/_src/numpy/util.py
  jax/_src/pallas/mosaic_gpu/primitives.py
  jax/_src/pallas/pallas_call.py
  jax/_src/state/indexing.py
  jax/experimental/rnn.py
  jaxlib/cpu/_lapack/eig.pyi
  jaxlib/cpu/_lapack/schur.pyi
  pyproject.toml
Labels: pull ready

#26472 refactor: move jnp.einsum impl into its own submodule
  jax/_src/export/shape_poly.py
  jax/_src/numpy/einsum.py
  jax/_src/numpy/lax_numpy.py
  jax/numpy/__init__.py
Labels: pull ready

#26461 [ROCm] Only run core tests for ROCm post-build checks
  .github/workflows/rocm-ci.yml
Labels: pull ready

#26509 Skip Hopper-specific Pallas Mosaic GPU tests unless running on Hopper
  jax/_src/test_util.py
  tests/pallas/mosaic_gpu_test.py
Labels: pull ready

#26518 Removed unused ``# type: ignore`` comments
  jax/_src/api.py
  jax/_src/array.py
  jax/_src/checkify.py
  jax/_src/cloud_tpu_init.py
  jax/_src/core.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/lax/lax.py
  jax/_src/lax/utils.py
  jax/_src/mesh_utils.py
  jax/_src/numpy/array_methods.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/util.py
  jax/_src/op_shardings.py
  jax/_src/pallas/core.py
  jax/_src/pallas/hlo_interpreter.py
  jax/_src/pallas/mosaic/interpret.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pallas/triton/pallas_call_registration.py
  jax/_src/pjit.py
  jax/_src/sharding_impls.py
  jax/_src/sharding_specs.py
  jax/_src/state/discharge.py
  jax/_src/tree_util.py
  jax/experimental/jax2tf/tests/model_harness.py
  jax/experimental/shard_map.py
Labels: pull ready

#26522 [Mosaic GPU] Factor out Mosaic GPU dialect arch-specific tests
  tests/mosaic/gpu_test.py
Labels: pull ready

#26523 [Mosaic GPU] Use gettatr to import version-specific dialect ops
  jax/experimental/mosaic/gpu/dialect_lowering.py
Labels: pull ready

#26498 refactor: move lax_numpy indexing routines to their own submodule
  jax/_src/array.py
  jax/_src/numpy/array_methods.py
  jax/_src/numpy/indexing.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/linalg.py
  jax/_src/numpy/setops.py
  jax/_src/numpy/ufunc_api.py
  jax/_src/ops/scatter.py
  jax/experimental/sparse/transform.py
  jax/numpy/__init__.py
Labels: pull ready

#26542 Fix breakage in indexing refactor
  jax/_src/numpy/indexing.py
Labels: pull ready

#26528 jax.lax: improve docs for pow & related functions
  jax/_src/lax/lax.py
Labels: documentation, pull ready

#26529 Don't write atime file if JAX_COMPILATION_CACHE_MAX_SIZE == -1
  CHANGELOG.md
  jax/_src/lru_cache.py
  tests/lru_cache_test.py
Labels: pull ready

#25887 [shard_map] fix jax.debug.print/callback under partial auto
  jax/_src/debugging.py
  tests/shard_map_test.py
Labels: pull ready

#26570 Fix test failure in PGLE tests.
  tests/pgle_test.py
Labels: pull ready

#26571 Fix typos in ffi examples
  docs/ffi/rms_norm.cc
  examples/ffi/src/jax_ffi_example/rms_norm.cc
Labels: pull ready

#26550 jax.lax: improve docs for bitwise operators.
  jax/_src/lax/lax.py
Labels: documentation, pull ready

#26172 add `jax.distributed.is_initialized`
  jax/_src/distributed.py
  jax/distributed.py
  tests/BUILD
  tests/distributed_test.py
  tests/multiprocess_gpu_test.py
Labels: pull ready

#26615 fix scan doc on the `unroll` argument.
  jax/_src/lax/control_flow/loops.py
Labels: kokoro:force-run, pull ready

#26591 jax.lax: improve docs for comparison operators
  jax/_src/lax/lax.py
Labels: pull ready

#26607 Add dtype dispatching to FFI example.
  examples/ffi/src/jax_ffi_example/rms_norm.cc
  examples/ffi/src/jax_ffi_example/rms_norm.py
  examples/ffi/tests/rms_norm_test.py
Labels: pull ready

#26649 Internal: improved type annotations for lu.WrappedFun
  jax/_src/interpreters/partial_eval.py
  jax/_src/linear_util.py
Labels: pull ready

#26569 [better_errors] Cleanup use of DebugInfo.arg_names and result_paths
  docs/aot.md
  docs/export/export.md
  jax/_src/ad_checkpoint.py
  jax/_src/api.py
  jax/_src/api_util.py
  jax/_src/core.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/mlir.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/linear_util.py
  jax/_src/pjit.py
  tests/debug_info_test.py
  tests/mutable_array_test.py
  tests/pjit_test.py
Labels: pull ready

#26690 fix getting gcc major version
  build/tools/utils.py
Labels: pull ready

#26708 Merge 0.5.1 release branch and update version numbers
  .github/workflows/ci-build.yaml
  CHANGELOG.md
  jax/version.py
  setup.py
Labels: pull ready

#26713 Change documentation to recommend libtpu from pypi instead of GCS.
  README.md
  docs/installation.md
  setup.py
Labels: pull ready

#26058 [better_errors] Port the Pallas debug info mechanisms to the new JAX debugging info
  jax/_src/interpreters/mlir.py
  jax/_src/linear_util.py
  jax/_src/pallas/core.py
  jax/_src/pallas/hlo_interpreter.py
  jax/_src/pallas/mosaic/interpret.py
  jax/_src/pallas/mosaic/lowering.py
  jax/_src/pallas/mosaic/pallas_call_registration.py
  jax/_src/pallas/mosaic_gpu/lowering.py
  jax/_src/pallas/mosaic_gpu/pallas_call_registration.py
  jax/_src/pallas/pallas_call.py
  jax/_src/pallas/triton/lowering.py
  jax/_src/pallas/triton/pallas_call_registration.py
  tests/debug_info_test.py
  tests/pallas/export_pallas_test.py
  tests/pallas/pallas_test.py
Labels: pull ready

#26564 Add jax.experimental._mini_mpmd
  jax/experimental/_private_mm/BUILD
  jax/experimental/_private_mm/__init__.py
  jax/experimental/_private_mm/examples/example_basic.py
  jax/experimental/_private_mm/examples/example_overlap.py
  jax/experimental/_private_mm/examples/example_pp.py
  jax/experimental/_private_mm/examples/example_tests.py
  jax/experimental/_private_mm/examples/launch_utils.py
  jax/experimental/_private_mm/mini_dime.py
  jax/experimental/_private_mm/mm.py
  jax/experimental/_private_mm/profile_utils.py
Labels: kokoro:force-run, pull ready

#26734 Update tsan suppressions.
  .github/workflows/tsan-suppressions.txt
Labels: pull ready

#26327 Check "jax_rocm_visible_devices" at client creation.
  jax/_src/xla_bridge.py
Labels: pull ready, AMD GPU

#26676 Allow query and keys that aren’t multiples of 128
  jax/experimental/pallas/ops/tpu/splash_attention/splash_attention_kernel.py
  tests/pallas/tpu_splash_attention_kernel_test.py
Labels: pull ready

#26762 Fix failures in TSAN free threading CI.
  .github/workflows/tsan-suppressions.txt
  tests/lax_control_flow_test.py
Labels: kokoro:force-run, pull ready

#26712 Remove code present to support jaxlib < 0.5.1.
  jax/_src/array.py
  jax/_src/compiler.py
  jax/_src/dispatch.py
  jax/_src/dtypes.py
  jax/_src/interpreters/mlir.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/pallas/triton/pallas_call_registration.py
  jax/experimental/jax2tf/call_tf.py
  jax/experimental/transfer.py
  tests/api_test.py
  tests/array_test.py
  tests/colocated_python_test.py
  tests/debugging_primitives_test.py
  tests/ffi_test.py
  tests/layout_test.py
  tests/linalg_test.py
  tests/magma_linalg_test.py
  tests/memories_test.py
  tests/mosaic/gpu_test.py
  tests/pjit_test.py
  tests/ragged_collective_test.py
  tests/string_array_test.py
Labels: pull ready

#26740 Add --system to uv commands in upstream-nightly workflow.
  .github/workflows/upstream-nightly.yml
Labels: pull ready

#26291 Extend `random.orthogonal` to semi-orthogonal matrices and simplify `initializers.orthogonal`
  jax/_src/nn/initializers.py
  jax/_src/random.py
  tests/random_lax_test.py
Labels: pull ready

#26835 Update setup.py to automatically pick up libtpu patch releases
  setup.py
Labels: pull ready
