Repository jax-ml/jax, pull requests merged in 2025-08, with the labels that each got.

#30669 [mutable-arrays] add ArrayRef docs
  docs/advanced_guide.rst
  docs/array_refs.ipynb
  docs/array_refs.md
  docs/array_refs.py
  docs/conf.py
  docs/jax.ref.rst
  docs/jax.rst
  jax/__init__.py
Labels: documentation, kokoro:force-run, pull ready

#30675 [mutable-arrays] scan autodiff fix, internal vjp-with-refs api prototype
  jax/_src/api.py
  jax/_src/interpreters/ad.py
  jax/_src/lax/control_flow/loops.py
  jax/interpreters/ad.py
  tests/mutable_array_test.py
Labels: kokoro:force-run, pull ready

#30697 [hijax] refactor so hijax interface and boxes are in jax._src.hijax
  jax/BUILD
  jax/_src/BUILD
  jax/_src/hijax.py
  tests/hijax_test.py
Labels: kokoro:force-run, pull ready

#30696 Add python 3.14 nightly tests
  .github/workflows/wheel_tests_nightly_release.yml
Labels: kokoro:force-run, pull ready

#30009 Fix cache leaks for pe._cached_abstract_eval; add util.multi_weakref_lru_cache
  jax/_src/core.py
  jax/_src/dispatch.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/util.py
  tests/lax_control_flow_test.py
  tests/util_test.py
Labels: kokoro:force-run, pull ready

#30733 Add missing changelog entry to v0.7.0
  CHANGELOG.md
Labels: pull ready

#30746 doc: fix incorrect markup in changelog
  CHANGELOG.md
Labels: pull ready

#30750 [hijax] improve box error message
  jax/_src/hijax.py
  jax/ref.py
Labels: pull ready

#30646 Update stateful-computations.md link
  docs/stateful-computations.md
Labels: kokoro:force-run, pull ready

#30809 Add hyp2f1 to the docs.
  docs/jax.scipy.rst
Labels: documentation, kokoro:force-run, pull ready

#30790 fix(docs): typo ufunc_api.py
  jax/_src/numpy/ufunc_api.py
Labels: kokoro:force-run, pull ready

#30798 Deprecate the jax.experimental.host_callback module
  .github/workflows/ci-build.yaml
  CHANGELOG.md
  jax/_src/deprecations.py
  jax/experimental/BUILD
  jax/experimental/host_callback.py
Labels: kokoro:force-run, pull ready

#30830 [mutable arrays] ensure addupdate returns None as annotated
  jax/_src/state/primitives.py
Labels: kokoro:force-run, pull ready

#30833 [mutable arrays] add API docs for `jax.ref` module
  jax/_src/core.py
  jax/_src/ref.py
  jax/_src/state/primitives.py
  jax/_src/state/types.py
Labels: documentation, kokoro:force-run, pull ready

#30172 Add tip to tree reduce and reduce_associative about how to exclude leaves from the reduction.
  jax/_src/tree.py
Labels: kokoro:force-run, pull ready

#30859 [mutable-arrays] add prototypes of vjp3 and backward_pass3
  jax/_src/api.py
  jax/_src/core.py
  jax/_src/interpreters/ad.py
  jax/_src/lax/utils.py
  jax/_src/state/primitives.py
  jax/_src/state/types.py
  tests/pallas/pallas_test.py
Labels: kokoro:force-run, pull ready

#30870 [mutable-arrays] add scan fancy transpose for vjp3
  jax/_src/api.py
  jax/_src/interpreters/ad.py
  jax/_src/lax/control_flow/loops.py
  tests/mutable_array_test.py
Labels: pull ready

#30875 [mutable-arrays] add jit fancy transpose rule for vjp3
  jax/_src/api.py
  jax/_src/core.py
  jax/_src/interpreters/ad.py
  jax/_src/pjit.py
  jax/_src/state/types.py
  tests/mutable_array_test.py
Labels: pull ready

#30892 Remove NumPy version pin in CI.
  .github/workflows/pytest_cpu.yml
Labels: kokoro:force-run, pull ready

#30922 [mutable-arrays] add fancy transpose for custom_jvp
  jax/_src/custom_derivatives.py
  tests/custom_api_test.py
Labels: kokoro:force-run, pull ready

#30885 [mosaic_gpu] Enabled mypy in all Mosaic GPU sources
  jax/experimental/mosaic/gpu/core.py
  jax/experimental/mosaic/gpu/equations.py
  jax/experimental/mosaic/gpu/fragmented_array.py
  jax/experimental/mosaic/gpu/launch_context.py
  jax/experimental/mosaic/gpu/layout_inference.py
  jax/experimental/mosaic/gpu/layout_inference2.py
  jax/experimental/mosaic/gpu/mma_utils.py
  jax/experimental/mosaic/gpu/profiler.py
  jax/experimental/mosaic/gpu/tcgen05.py
  jax/experimental/mosaic/gpu/transform_inference.py
  jax/experimental/mosaic/gpu/utils.py
  jax/experimental/mosaic/gpu/wgmma.py
Labels: kokoro:force-run, pull ready

#30956 [CI]Always run B200 tests on PRs that modify higher risk mosaic paths
  .github/workflows/bazel_cuda_h100_b200.yml
Labels: kokoro:force-run, pull ready

#30949 [mutable-arrays] add vjp3 test: ref grads for value primals
  jax/_src/core.py
  jax/_src/state/types.py
  tests/mutable_array_test.py
Labels: kokoro:force-run, pull ready

#30516 fix bnth layout shardy and infer_fwd_ouput_sharding
  jax/_src/cudnn/fused_attention_stablehlo.py
  tests/fused_attention_stablehlo_test.py
Labels: kokoro:force-run, pull ready

#30957 Use standard deprecation path for jax.experimental.compilation_cache
  jax/_src/compilation_cache.py
  jax/experimental/compilation_cache/compilation_cache.py
Labels: kokoro:force-run, pull ready

#30979 Removed more dead code
  jax/_src/state/discharge.py
  jax/experimental/rnn.py
  jax/experimental/slab/djax.py
Labels: kokoro:force-run, pull ready

#30980 [ref] Respect short_dtypes and mesh_axis_types when pretty-printing AbstractRefs
  jax/_src/state/types.py
Labels: kokoro:force-run, pull ready

#30999 Let axis=-1 by default in take_along_axis to match NumPy.
  jax/_src/numpy/indexing.py
  jax/numpy/__init__.pyi
  tests/lax_numpy_test.py
Labels: kokoro:force-run, pull ready

#31005 [test] use explicit version checks rather than hasattr checks
  tests/lax_metal_test.py
  tests/lax_numpy_operators_test.py
  tests/lax_numpy_test.py
  tests/string_array_test.py
Labels: pull ready

#29281 [ROCm] ROCm7 Plugin Updates
  jaxlib/plugin_support.py
  jaxlib/rocm/BUILD
Labels: kokoro:force-run, pull ready

#30995 Document and test order and stability properties of lax.top_k.
  jax/_src/lax/lax.py
  jax/_src/lax_reference.py
  tests/lax_test.py
Labels: kokoro:force-run, pull ready

#31014 Attempt to fix flaky test
  tests/lax_control_flow_test.py
Labels: pull ready

#31034 Add reminder to run tests in 64-bit mode to contributing.md.
  docs/contributing.md
Labels: kokoro:force-run, pull ready

#31017 [DOC] Fix link in register_dataclass docstring
  jax/_src/tree_util.py
Labels: kokoro:force-run, pull ready

#31042 Fix some typos in RST/MD markup
  docs/notebooks/host-offloading.ipynb
  docs/notebooks/host-offloading.md
  jax/_src/export/_export.py
  jax/_src/pallas/mosaic_gpu/primitives.py
  jax/experimental/sparse/bcoo.py
Labels: pull ready

#31046 Use Python 3.14 context aware warnings if they are enabled.
  jax/_src/test_warning_util.py
Labels: kokoro:force-run, pull ready

#31053 Fix a test failure in free-threaded Mac CI.
  tests/lax_control_flow_test.py
Labels: pull ready

#31056 Fix requirements_update rule.
  build/build.py
Labels: pull ready

#31065 Deprecate a number of jax.interpreters.ad APIs
  jax/interpreters/ad.py
Labels: kokoro:force-run, pull ready

#31086 [pre-commit] update ruff to v0.12.9
  .pre-commit-config.yaml
Labels: pull ready

#31087 [pre-commit] bump pre-commit-hooks version
  .pre-commit-config.yaml
Labels: pull ready

#30986 [jaxpr consts] Fix AOT execution with 64-bit captured constants
  docs/internals/constants.md
  jax/_src/interpreters/pxla.py
  tests/aot_test.py
Labels: pull ready

#31112 Fix scaled_matmul_stablehlo_test.
  tests/scaled_matmul_stablehlo_test.py
Labels: kokoro:force-run, pull ready

#31196 Fix arctan2 doctest
  jax/_src/numpy/ufuncs.py
Labels: kokoro:force-run, pull ready

#31208 Skip while partial_eval_custom when all inputs are known.
  jax/_src/lax/control_flow/loops.py
Labels: kokoro:force-run, pull ready

#31224 [doc] Remove outdated link from README
  README.md
Labels: kokoro:force-run, pull ready

#31164 [ref] Define get_aval on RefAccum and ValAccum
  jax/_src/interpreters/ad.py
  jax/_src/lax/control_flow/loops.py
Labels: kokoro:force-run, pull ready

#31241 Fix log10(10) == 1 equality
  jax/_src/numpy/ufuncs.py
Labels: kokoro:force-run, pull ready

#31242 [fused] fix fused prototype to use customcall backend_config
  jax/experimental/fused.py
  tests/fused_test.py
Labels: kokoro:force-run, pull ready

#31275 [vjp3] make NotNeeded an empty pytree node
  jax/_src/api.py
Labels: kokoro:force-run, pull ready

#31281 [debug-info] don't propagate incorrect debug info in remat transpose
  jax/_src/ad_checkpoint.py
  tests/debug_info_test.py
Labels: kokoro:force-run, pull ready

#31285 DOC: Clarify jax.scipy.linalg.eigh only supports the standard eigenvalue (GH#31267)
  jax/_src/scipy/linalg.py
Labels: kokoro:force-run, pull ready

#31278 [remat] add prototype partial cse prevention for remat
  jax/_src/ad_checkpoint.py
  tests/api_test.py
Labels: pull ready

#30177 Document all checkpoint policies in one place, on the JAX public API page.
  docs/gradient-checkpointing.md
  docs/jax.rst
  docs/notebooks/autodiff_remat.ipynb
  docs/notebooks/autodiff_remat.md
  jax/_src/ad_checkpoint.py
Labels: documentation, kokoro:force-run, pull ready

#31141 [shmap] when pytree prefix broadcasting, dont stick in objects
  jax/_src/shard_map.py
Labels: kokoro:force-run, pull ready

#31317 Use `sys.stdout.write` in `debug.print` to make pytest happy
  jax/_src/debugging.py
Labels: kokoro:force-run, pull ready

#31310 make ad_checkpoint.checkpoint_name map over pytree inputs
  jax/_src/ad_checkpoint.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#31341 Avoid cache miss when using pure_callback
  jax/_src/pjit.py
  tests/python_callback_test.py
Labels: kokoro:force-run, pull ready

#31389 [mutable-arrays] allow internal-only refs in remat
  jax/_src/core.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/pallas/core.py
  jax/_src/state/primitives.py
Labels: kokoro:force-run, pull ready

#31269 Reorganize the tutorials, take 2
  CHANGELOG.md
  docs/_static/style.css
  docs/_tutorials/advanced-debugging.md
  docs/_tutorials/index.rst
  docs/advanced_guide.rst
  docs/advanced_guides.rst
  docs/beginner_guide.rst
  docs/building_on_jax.md
  docs/conf.py
  docs/debugging.md
  docs/debugging/flags.md
  docs/index.rst
  docs/jax-101.rst
  docs/notebooks/thinking_in_jax.ipynb
  docs/notebooks/thinking_in_jax.md
  docs/tutorials.rst
  docs/user_guides.rst
Labels: documentation, kokoro:force-run, pull ready

#31408 [mutable-arrays] checks are enabled by default, so update docs
  docs/array_refs.ipynb
  docs/array_refs.md
  docs/array_refs.py
Labels: documentation, kokoro:force-run, pull ready
