Repository jax-ml/jax, pull requests merged in 2025-06, with the labels that each got.

#29127 [mutable-arrays] don't let scan AD hoist mutable operations
  jax/_src/lax/control_flow/loops.py
  tests/mutable_array_test.py
Labels: kokoro:force-run, pull ready

#29170 [cleanup] inline uses of NumpyComplexWarning
  jax/_src/lax/lax.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/util.py
  tests/lax_autodiff_test.py
  tests/lax_metal_test.py
  tests/lax_numpy_indexing_test.py
  tests/lax_numpy_reducers_test.py
  tests/lax_numpy_test.py
  tests/lax_test.py
Labels: pull ready

#29168 always compile Pallas calls, enabling `pallas_call` under `disable_jit`
  jax/_src/pallas/pallas_call.py
  tests/pallas/pallas_test.py
Labels: kokoro:force-run, pull ready

#29153 Simplify `jnp.isclose`
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: kokoro:force-run, pull ready

#29245 Add a general system for keeping track of quasi-dynamic data (QDD)
  jax/_src/core.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/pjit.py
  tests/hijax_test.py
Labels: kokoro:force-run, pull ready

#29224 jnp.array: avoid call to stack
  jax/_src/numpy/lax_numpy.py
Labels: kokoro:force-run, pull ready

#29087 doc: clarified lack of gpu support for schur and sqrtm
  jax/_src/scipy/linalg.py
Labels: documentation, kokoro:force-run, pull ready

#29246 lax_numpy: move array and asarray to their own submodule
  jax/_src/numpy/array.py
  jax/_src/numpy/array_creation.py
  jax/_src/numpy/index_tricks.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/scalar_types.py
  jax/numpy/__init__.py
Labels: kokoro:force-run, pull ready

#29273 [cleanup] remove core.gensym, and Var.suffix
  jax/_src/ad_checkpoint.py
  jax/_src/core.py
  jax/_src/interpreters/batching.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/control_flow/common.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/pallas/hlo_interpreter.py
  tests/core_test.py
Labels: kokoro:force-run, pull ready

#29254 lax.top_k: raise error if indices will overflow
  jax/_src/lax/lax.py
  tests/lax_test.py
Labels: kokoro:force-run, pull ready

#29311 [mutable-arrays] make partial_eval_jaxpr forward input-residuals
  jax/_src/custom_derivatives.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/batching.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/pallas/fuser/fusible_dtype.py
  jax/_src/pjit.py
  tests/api_test.py
  tests/custom_api_test.py
  tests/debug_info_test.py
  tests/mutable_array_test.py
Labels: kokoro:force-run, pull ready

#29330 Don't trigger debug_infs in ndtri unless an inf is returned
  jax/_src/scipy/special.py
  tests/lax_scipy_special_functions_test.py
Labels: kokoro:force-run, pull ready

#29332 jax.nn.standardize: improve documentation
  jax/_src/nn/functions.py
Labels: kokoro:force-run, pull ready

#29344 [array-api] pin array-api-tests to 2025.05.23
  .github/workflows/jax-array-api.yml
Labels: pull ready

#29352 [mutable-arrays] make custom_api_test.py pass with JAX_MUTABLE_ARRAY_CHECKS=1
  jax/_src/custom_derivatives.py
  tests/mutable_array_test.py
Labels: kokoro:force-run, pull ready

#29257 fix type annotation for _IndexUpdateRef.get
  jax/_src/basearray.pyi
  jax/_src/numpy/array_methods.py
Labels: kokoro:force-run, pull ready

#29350 [Pallas] Fix shard_map + Megacore in TPU interpret mode.
  jax/_src/pallas/mosaic/interpret.py
  tests/pallas/tpu_pallas_interpret_distributed_test.py
Labels: kokoro:force-run, pull ready

#29294 //tests:scaled_matmul_stablehlo_test: fix for xla#27096
  tests/scaled_matmul_stablehlo_test.py
Labels: kokoro:force-run, pull ready

#29405 Migrated to mypy 1.16.0
  .pre-commit-config.yaml
  jax/_src/lax/lax.py
  jax/_src/pallas/mosaic_gpu/pipeline.py
Labels: kokoro:force-run, pull ready

#29129 [XProf] Change tensorboard-plugin-profile to new xprof package
  build/collect-profile-requirements.txt
  docs/profiling.md
  jax/collect_profile.py
  pyproject.toml
  setup.py
  tests/profiler_test.py
Labels: documentation, kokoro:force-run, pull ready

#29423 Fix GPU quantized paged attention tests for < sm89
  tests/pallas/gpu_paged_attention_test.py
Labels: kokoro:force-run, pull ready

#29362 Improve batching for lax.platform_dependent
  jax/_src/interpreters/ad.py
  jax/_src/lax/control_flow/conditionals.py
  tests/lax_control_flow_test.py
Labels: kokoro:force-run, pull ready

#29425 add missing dtypes to jax.numpy.__init__.pyi
  jax/numpy/__init__.pyi
Labels: kokoro:force-run, pull ready

#29441 [doc] fix some inaccuracies in jnp.bincount docs
  jax/_src/numpy/lax_numpy.py
Labels: documentation, pull ready

#28931 Add extra cuBLAS/cuDNN version checks
  jax_plugins/cuda/__init__.py
Labels: kokoro:force-run, pull ready

#29462 Load CUDA libraries up front with cdll.LoadLibrary().
  build/requirements.in
  build/requirements_lock_3_10.txt
  build/requirements_lock_3_11.txt
  build/requirements_lock_3_12.txt
  build/requirements_lock_3_13.txt
  build/requirements_lock_3_13_ft.txt
  jax_plugins/cuda/__init__.py
  jax_plugins/cuda/plugin_setup.py
  jaxlib/tools/BUILD.bazel
Labels: kokoro:force-run, pull ready

#29504 [TSAN CI] Removed fixed cpython suppressions
  .github/workflows/tsan-suppressions_3.13.txt
  .github/workflows/tsan-suppressions_3.14.txt
Labels: kokoro:force-run, pull ready

#29410 add jax.nn module type hints (__init__.pyi)
  .pre-commit-config.yaml
  jax/BUILD
  jax/nn/__init__.pyi
Labels: kokoro:force-run, pull ready

#29528 JAX release v0.6.2
  CHANGELOG.md
  jax/version.py
  setup.py
  third_party/xla/llvm_fix.patch
  third_party/xla/workspace.bzl
Labels: pull ready

#29549 Finalize a number of deprecations for JAX v0.7.0
  jax/dlpack.py
  jax/lib/xla_client.py
  jax/lib/xla_extension.py
  jax/tree_util.py
  jax/util.py
Labels: kokoro:force-run, pull ready

#29558 Remove some dangling references from the docs.
  docs/jax.dlpack.rst
  docs/jax.tree_util.rst
Labels: pull ready

#29554 [Pallas] Fixes in the double_buffered_pipeline example
  docs/pallas/pipelining.md
Labels: kokoro:force-run, pull ready

#29563 [doc] fix build error
  jax/_src/pallas/pallas_call.py
Labels: documentation, kokoro:force-run, pull ready

#29560 Update requirements lock files after 0.6.2 release
  build/requirements.in
  build/requirements_lock_3_11.txt
  build/requirements_lock_3_12.txt
  build/requirements_lock_3_13.txt
  build/requirements_lock_3_13_ft.txt
Labels: kokoro:force-run, pull ready

#29434 Add `wrap_negative_indices` paramter to `jnp.ndarray.at[]`
  jax/_src/basearray.pyi
  jax/_src/numpy/array_methods.py
  jax/_src/numpy/indexing.py
  tests/lax_numpy_indexing_test.py
Labels: documentation, kokoro:force-run, pull ready

#28135 [Pallas] [Mosaic GPU] Add GPU pipelining docs
  docs/_static/pallas/gpu/pipeline_matmul.svg
  docs/_static/pallas/gpu/pipeline_matmul_ws.svg
  docs/_static/pallas/gpu/warp_specialization.svg
  docs/conf.py
  docs/pallas/gpu/index.rst
  docs/pallas/gpu/pipelining.ipynb
  docs/pallas/gpu/pipelining.md
  docs/pallas/pipelining.ipynb
  docs/pallas/pipelining.md
Labels: kokoro:force-run, pull ready

#29421 [mutable-arrays] re-land #29353
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/control_flow/loops.py
  tests/lax_control_flow_test.py
  tests/mutable_array_test.py
Labels: kokoro:force-run, pull ready

#29629 instantiate symbolic zero cotangents in _linear_solve_transpose_rule
  jax/_src/lax/control_flow/solves.py
  tests/custom_linear_solve_test.py
Labels: kokoro:force-run, pull ready

#29565 disable cudnn sdpa on blackwell gb300
  jax/_src/cudnn/fused_attention_stablehlo.py
  tests/fused_attention_stablehlo_test.py
Labels: kokoro:force-run, pull ready

#29626 jax._src.numpy: avoid top-level imports
  jax/_src/numpy/array_api_metadata.py
  jax/_src/numpy/array_creation.py
  jax/_src/numpy/array_methods.py
  jax/_src/numpy/einsum.py
  jax/_src/numpy/fft.py
  jax/_src/numpy/indexing.py
  jax/_src/numpy/lax_numpy.py
  jax/_src/numpy/linalg.py
  jax/_src/numpy/polynomial.py
  jax/_src/numpy/reductions.py
  jax/_src/numpy/setops.py
  jax/_src/numpy/sorting.py
  jax/_src/numpy/tensor_contractions.py
  jax/_src/numpy/ufunc_api.py
  jax/_src/numpy/util.py
Labels: kokoro:force-run, pull ready

#29649 don't pass `self` to `raise AttributeError(...)`
  jax/_src/core.py
Labels: kokoro:force-run, pull ready

#29696 Remove obsolete submodule jax._src.scipy.interpolate
  jax/_src/scipy/interpolate/__init__.py
Labels: pull ready

#29616 Deprecate jax.dtypes.SUPPORTED_DTYPES and add is_supported_dtype()
  CHANGELOG.md
  docs/jax.dlpack.rst
  jax/_src/dlpack.py
  jax/dlpack.py
  jax/experimental/jax2tf/call_tf.py
  jax/experimental/jax2tf/tests/call_tf_test.py
  tests/array_interoperability_test.py
Labels: kokoro:force-run, pull ready

#29507 Use more concise tracer reprs by default.
  jax/_src/api.py
  jax/_src/core.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/batching.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/tree_util.py
  tests/core_test.py
Labels: kokoro:force-run, pull ready

#29739 cuFFT: remove deprecated enum values
  jaxlib/gpu/gpu_kernel_helpers.cc
Labels: kokoro:force-run, pull ready

#29738 [jaxpr consts] Propagate closed-over constants in lax.composite
  jax/_src/lax/lax.py
  tests/debug_info_test.py
  tests/lax_test.py
Labels: kokoro:force-run, pull ready

#29786 disable gb300 sdpa test until cudnn supports it properly
  tests/nn_test.py
Labels: kokoro:force-run, pull ready

#29797 [mutable-arrays] fix mutable array AD bug with HOPs
  jax/_src/interpreters/ad.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/pjit.py
  tests/mutable_array_test.py
Labels: pull ready

#29768 [jaxpr consts] Propagate closed-over constants to the top-level jit (take 2)
  jax/_src/config.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/pjit.py
  tests/api_test.py
  tests/debug_info_test.py
  tests/pjit_test.py
Labels: kokoro:force-run, pull ready

#29539 [debug_info] Improve debug info for loop constructs.
  jax/_src/api_util.py
  jax/_src/custom_batching.py
  jax/_src/lax/control_flow/common.py
  jax/_src/lax/control_flow/for_loop.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/pallas/core.py
  tests/debug_info_test.py
Labels: kokoro:force-run, pull ready
