Repository jax-ml/jax, pull requests merged in 2025-05, with the labels that each got.

#28408 Fix incorrect backward argument in cudnn sdpa api when using return_residual
  jax/_src/cudnn/fused_attention_stablehlo.py
  tests/fused_attention_stablehlo_test.py
Labels: kokoro:force-run, pull ready

#28318 initial commit of boxes/lists
  jax/_src/api.py
  jax/_src/core.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/pjit.py
  jax/_src/util.py
  jax/experimental/attrs.py
  tests/attrs_test.py
Labels: kokoro:force-run, pull ready

#28464 Update shard_map.md's API specification section
  docs/notebooks/shard_map.ipynb
  docs/notebooks/shard_map.md
  jax/_src/shard_map.py
Labels: kokoro:force-run, pull ready

#28482 DOC: hide config options TOC on front page
  docs/index.rst
Labels: pull ready

#28283 Add retry to certain K8s-related calls to overcome transient failure
  jax/BUILD
  jax/_src/clusters/k8s_cluster.py
Labels: kokoro:force-run, pull ready

#28429 Update requirements files:
  build/BUILD.bazel
  build/freethreading-requirements.txt
  build/gpu-test-requirements.txt
  build/nonfreethreading-requirements.txt
  build/requirements.in
  build/requirements_lock_3_10.txt
  build/requirements_lock_3_11.txt
  build/requirements_lock_3_12.txt
  build/requirements_lock_3_13.txt
  build/requirements_lock_3_13_ft.txt
  build/test-requirements.txt
Labels: pull ready

#28489 chore: disable legacy external runfiles
  .bazelrc
Labels: kokoro:force-run, pull ready

#28498 Fix `dlpack` docs formatting
  jax/_src/dlpack.py
Labels: kokoro:force-run, pull ready

#28500 Improve TSAN CI build.
  .github/workflows/requirements_lock_3_13_ft.patch
  .github/workflows/tsan-suppressions_3.13.txt
  .github/workflows/tsan-suppressions_3.14.txt
  .github/workflows/tsan.yaml
  WORKSPACE
  build/requirements_lock_3_13_ft.txt
Labels: kokoro:force-run, pull ready

#28461 [Mosaic GPU] Deallocate TMEM using a single warp
  jax/experimental/mosaic/gpu/core.py
Labels: kokoro:force-run, pull ready, CI Optional GPU Presubmit

#28513 jax-cuda12-plugin: require nvidia-cublas-cu12<12.9
  jax_plugins/cuda/plugin_setup.py
Labels: kokoro:force-run, pull ready

#28485 [Mosaic GPU] Print instead of warning when skipping flash_attention test
  jax/experimental/mosaic/gpu/examples/flash_attention.py
Labels: kokoro:force-run, pull ready

#28533 Fix defaults overriding each other in tests/mutliprocess_gpu_test
  tests/multiprocess_gpu_test.py
Labels: kokoro:force-run, pull ready

#28507 Update sharded-computation.md
  docs/sharded-computation.ipynb
  docs/sharded-computation.md
Labels: kokoro:force-run, pull ready

#28387 Fixed deadlock in MakeShardFn on static var assignment under free-threading
  jaxlib/BUILD
  jaxlib/py_values.cc
  jaxlib/sharding.cc
Labels: kokoro:force-run, pull ready

#28396 Do constant folding and forwarding while tracing instead of as a separate pass
  jax/_src/interpreters/partial_eval.py
  jax/_src/lax/lax.py
  jax/_src/pjit.py
  tests/pjit_test.py
  tests/shard_map_test.py
Labels: kokoro:force-run, pull ready

#28593 jnp.packbits: fix handling of negative entries
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: kokoro:force-run, pull ready

#28584 jax.scipy.signal.istft: support array input for window
  jax/_src/dtypes.py
  jax/_src/scipy/signal.py
  tests/scipy_signal_test.py
Labels: kokoro:force-run, pull ready

#28606 Fix docs build by constraining snowballstemmer version
  docs/requirements.txt
Labels: pull ready

#28279 Add argnums param to fwd_and_bwd
  jax/_src/api.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#28610 jnp.put: check inplace before other conditions
  jax/_src/numpy/indexing.py
Labels: pull ready

#28612 jnp.linalg.matrix_power: support non-float inputs
  jax/_src/numpy/linalg.py
  tests/linalg_test.py
Labels: kokoro:force-run, pull ready

#28608 Add a pretty printing rule for custom_jvp
  jax/_src/custom_derivatives.py
  tests/api_test.py
Labels: kokoro:force-run, pull ready

#28642 Use cython from pypi in tsan CI build.
  .github/workflows/tsan.yaml
Labels: pull ready

#28650 pytest: use importlib mode by default
  pyproject.toml
Labels: kokoro:force-run, pull ready

#28656 Disable profiler tests under Python 3.14 if multithreaded.
  tests/profiler_test.py
Labels: pull ready

#28626 Remove __div__ and __rdiv__ from jax.Array
  jax/_src/numpy/array_methods.py
Labels: kokoro:force-run, pull ready

#28664 [si_vjp] fix bugs around symbolic zeros
  jax/_src/api.py
  tests/api_test.py
Labels: pull ready

#28695 [array API] update test suite to most recent version
  .github/workflows/jax-array-api.yml
  tests/array_api_skips.txt
Labels: pull ready

#28607 [platform_dependent] Ensure that platform_dependent only lowers for intended platforms
  jax/_src/checkify.py
  jax/_src/interpreters/mlir.py
  jax/_src/lax/control_flow/__init__.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/pallas/mosaic/lowering.py
  jax/_src/pallas/mosaic_gpu/lowering.py
  jax/experimental/jax2tf/jax2tf.py
  tests/lax_control_flow_test.py
Labels: kokoro:force-run, pull ready

#28589 Consolidate initial/final style custom_vjp primitives into one
  jax/_src/checkify.py
  jax/_src/custom_derivatives.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/pallas/cost_estimate.py
  jax/custom_derivatives.py
  jax/experimental/jax2tf/jax2tf.py
  jax/extend/core/primitives.py
  tests/custom_api_test.py
Labels: kokoro:force-run, pull ready

#28690 Revert pytest: use importlib mode by default
  pyproject.toml
Labels: kokoro:force-run, pull ready

#28711 Don't instantiate zeros passed to custom_lin_p
  jax/_src/interpreters/ad.py
Labels: kokoro:force-run, pull ready

#28715 Add a pretty printing rule for custom_vjp
  jax/_src/custom_derivatives.py
  tests/custom_api_test.py
Labels: kokoro:force-run, pull ready

#28355 Deprecate parsing of __jax_array__ during abstractification.
  jax/_src/core.py
  jax/_src/deprecations.py
  jax/_src/numpy/lax_numpy.py
  tests/api_test.py
  tests/array_extensibility_test.py
Labels: kokoro:force-run, pull ready

#28661 JEP 28661: the __jax_array__ protocol
  docs/jep/28661-jax-array-protocol.md
  docs/jep/index.rst
Labels: kokoro:force-run, pull ready

#28722 [doc] mention jaxlib in the API compatibility doc
  docs/api_compatibility.md
Labels: kokoro:force-run, pull ready

#28635 Skip CSR matmat and matvec float tests on ROCm <6.4 (NaN issue with beta==0)
  tests/sparse_test.py
Labels: kokoro:force-run, pull ready

#28743 test: support accelerated deprecation for jax.extend.ffi
  tests/ffi_test.py
Labels: kokoro:force-run, pull ready

#28732 Removed few tsan cpython suppressions as fixed
  .github/workflows/tsan-suppressions_3.13.txt
  .github/workflows/tsan-suppressions_3.14.txt
Labels: kokoro:force-run, pull ready

#28750 Add requirements needed for building wheels under Python 3.14t.
  WORKSPACE
  build/requirements_lock_3_14_ft.txt
Labels: pull ready

#28747 Warn when __jax_array__ is seen in xla dtype canonicalization
  jax/BUILD
  jax/_src/interpreters/xla.py
Labels: kokoro:force-run, pull ready

#28751 Move definition of pjrt_c_api_gpu_plugin.so into jax_plugins/{cuda,rocm}
  jax_plugins/cuda/BUILD.bazel
  jax_plugins/cuda/__init__.py
  jax_plugins/cuda/gpu_version_script.lds
  jax_plugins/rocm/BUILD.bazel
  jax_plugins/rocm/__init__.py
  jax_plugins/rocm/gpu_version_script.lds
  jaxlib/tools/BUILD.bazel
  jaxlib/tools/build_gpu_plugin_wheel.py
Labels: pull ready

#28748 Add a linearization rule for scan
  jax/_src/lax/control_flow/loops.py
  tests/lax_control_flow_test.py
Labels: kokoro:force-run, pull ready

#28753 Simplify the Bazel logic used to add dependencies to tests.
  jax/BUILD
  jax_plugins/cuda/BUILD.bazel
  jax_plugins/rocm/BUILD.bazel
  jaxlib/jax.bzl
Labels: pull ready

#28755 Reenable CUDA version checks from Python.
  CHANGELOG.md
  jax/_src/xla_bridge.py
  jax_plugins/cuda/__init__.py
Labels: kokoro:force-run, pull ready

#28757 improve error message with when custom_vjp bwd rule produces wrong shape/dtype
  jax/_src/core.py
  jax/_src/custom_derivatives.py
  jax/_src/lax/control_flow/common.py
  jax/_src/lax/control_flow/conditionals.py
  jax/_src/lax/control_flow/loops.py
Labels: better_errors, pull ready, skill issue

#28771 Workaround a crash on aarch64 due to a NumPy bug.
  .bazelrc
Labels: kokoro:force-run, pull ready

#28317 Add docs for multi-process run in Kubernetes
  .github/workflows/k8s.yaml
  docs/multi_process.md
  jax/_src/clusters/k8s_cluster.py
Labels: kokoro:force-run, pull ready

#28721 jax.numpy: make type stubs consistent with runtime
  jax/numpy/__init__.pyi
Labels: kokoro:force-run, pull ready

#28779 [pre-commit] bump pre-commit version to v5.0.0
  .pre-commit-config.yaml
Labels: pull ready

#28781 [hijax] prototype hijax pieces
  jax/_src/ad_util.py
  jax/_src/api.py
  jax/_src/core.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/pjit.py
  tests/attrs_test.py
Labels: kokoro:force-run, pull ready

#28785 Added dict_dict_merge/split_keys_entry_added suppression to 3.14 TSAN CI job
  .github/workflows/tsan-suppressions_3.14.txt
Labels: kokoro:force-run, pull ready

#28792 Add OMP_NUM_THREADS workaround to more aarch64 CI configuations.
  .bazelrc
Labels: pull ready

#28778 [pre-commit] update mypy to v1.15.0
  .pre-commit-config.yaml
  jax/_src/checkify.py
  jax/_src/export/_export.py
Labels: kokoro:force-run, pull ready

#28780 [pre-commit] bump ruff to v0.11.9
  .pre-commit-config.yaml
  pyproject.toml
Labels: kokoro:force-run, pull ready

#28802 Fix test failures in GPU CI.
  BUILD.bazel
  tests/BUILD
Labels: pull ready

#28804 [hijax] type-changing boxes with pytree contents
  jax/_src/core.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/pjit.py
  tests/BUILD
  tests/attrs_test.py
  tests/hijax_test.py
Labels: kokoro:force-run, pull ready

#28808 Increase some test shardings to work around CI timeouts.
  tests/BUILD
  tests/pallas/BUILD
Labels: pull ready

#28828 Disable cusolver version check.
  jax_plugins/cuda/__init__.py
Labels: pull ready

#28829 Bump NumPy version to 2.2.6 for 3.13+ Python versions.
  .bazelrc
  build/freethreading-requirements.txt
  build/nonfreethreading-requirements.txt
  build/requirements.in
  build/requirements_lock_3_10.txt
  build/requirements_lock_3_11.txt
  build/requirements_lock_3_12.txt
  build/requirements_lock_3_13.txt
  build/requirements_lock_3_13_ft.txt
  build/requirements_lock_3_14.txt
Labels: pull ready

#28848 Update scipy.signal.welch tests to be compatible with upstream dev version
  jax/_src/third_party/scipy/signal_helper.py
  tests/scipy_signal_test.py
Labels: kokoro:force-run, pull ready

#28856 Add a TSAN suppression for python/cpython#132214 under Python 3.13
  .github/workflows/tsan-suppressions_3.13.txt
Labels: pull ready

#28838 cleanup: load python rules from rules_python
  build/BUILD.bazel
  jaxlib/mlir/BUILD.bazel
  jaxlib/mlir/_mlir_libs/BUILD.bazel
Labels: pull ready

#28863 Remove tsan suppression from python/cpython#129748
  .github/workflows/tsan-suppressions_3.13.txt
  .github/workflows/tsan-suppressions_3.14.txt
  .github/workflows/tsan.yaml
Labels: pull ready

#28871 Reland the limit on the number of OpenBLAS threads.
  .bazelrc
Labels: pull ready

#28887 Use uv for installing packages on Read the Docs
  .readthedocs.yml
  docs/conf.py
Labels: documentation, kokoro:force-run, pull ready

#28886 Skip generating source links for re-exported numpy functions in docs
  docs/conf.py
Labels: documentation, kokoro:force-run, pull ready

#28897 Revert "jax-cuda12-plugin: require nvidia-cublas-cu12<12.9"
  jax_plugins/cuda/plugin_setup.py
Labels: kokoro:force-run, pull ready

#28904 Merge release/0.6.1 branch into main and update version numbers after release
  CHANGELOG.md
  jax/experimental/jax2tf/tests/jax2tf_test.py
  jax/version.py
  setup.py
Labels: pull ready

#28909 Expose tree prefix broadcasting as a public API in tree utils.
  CHANGELOG.md
  docs/jax.tree.rst
  docs/jax.tree_util.rst
  jax/_src/tree.py
  jax/_src/tree_util.py
  jax/tree.py
  jax/tree_util.py
  tests/tree_util_test.py
Labels: kokoro:force-run, pull ready

#28923 fix custom_vjp optimize_remat=True with collectives
  jax/_src/core.py
  jax/_src/custom_derivatives.py
  tests/shard_map_test.py
Labels: kokoro:force-run, pull ready

#28935 Prevent tests of TPU interpret mode from being run in parallel.
  tests/pallas/tpu_pallas_interpret_distributed_test.py
  tests/pallas/tpu_pallas_interpret_test.py
Labels: kokoro:force-run, pull ready

#28945 Update the trove classifiers for JAX packages.
  jax_plugins/cuda/plugin_setup.py
  jax_plugins/cuda/setup.py
  jaxlib/setup.py
  setup.py
Labels: kokoro:force-run, pull ready

#28946 jax.random: thread mode parameter through categorical and choice
  jax/_src/random.py
  tests/random_lax_test.py
Labels: kokoro:force-run, pull ready

#28899 Use the default python logging instead of absl log.
  docs/export/export.md
  jax/_src/compiler.py
  jax/_src/export/_export.py
Labels: kokoro:force-run, pull ready

#28978 Fix 'Current gotchas' link in README
  README.md
Labels: kokoro:force-run, pull ready

#28979 [tree_util] raise more informative error when pytree equality check fails
  jaxlib/pytree.cc
  jaxlib/xla_client.py
  tests/tree_util_test.py
Labels: better_errors, kokoro:force-run, pull ready

#28992 Add marin to ecosystem
  docs/index.rst
Labels: kokoro:force-run, pull ready

#28595 [Mosaic GPU] Use PTX ISA version = min(ptxas, LLVM)
  jaxlib/mosaic/gpu/custom_call.cc
  jaxlib/mosaic/gpu/target.cc
  jaxlib/mosaic/gpu/target.h
Labels: kokoro:force-run, pull ready, CI Optional GPU Presubmit

#29001 Updated: Clarify that upper bound takes precedence in jnp.clip where bounds are incongruent
  jax/_src/numpy/lax_numpy.py
  tests/lax_numpy_test.py
Labels: kokoro:force-run, pull ready

#29043 Update lock files for jaxlib 0.6.1
  build/requirements.in
  build/requirements_lock_3_10.txt
  build/requirements_lock_3_11.txt
  build/requirements_lock_3_12.txt
  build/requirements_lock_3_13.txt
  build/requirements_lock_3_13_ft.txt
Labels: pull ready

#29069 Skip TPU metadata server query when not using TPU.
  jax/_src/cloud_tpu_init.py
Labels: kokoro:force-run, pull ready

#29074 [CI] Update actions to adhere to best practices
  .github/actionlint.yaml
  .github/workflows/asan.yaml
  .github/workflows/bazel_cpu_py_import_rbe.yml
  .github/workflows/bazel_cpu_rbe.yml
  .github/workflows/bazel_cuda_non_rbe.yml
  .github/workflows/bazel_cuda_rbe.yml
  .github/workflows/bazel_optional_h100_b200.yml
  .github/workflows/build_artifacts.yml
  .github/workflows/ci-build.yaml
  .github/workflows/cloud-tpu-ci-nightly.yml
  .github/workflows/cloud-tpu-ci-presubmit.yml
  .github/workflows/jax-array-api.yml
  .github/workflows/k8s.yaml
  .github/workflows/metal_plugin_ci.yml
  .github/workflows/numpy_nightly.yml
  .github/workflows/oldest_supported_numpy.yml
  .github/workflows/pytest_cpu.yml
  .github/workflows/pytest_cuda.yml
  .github/workflows/pytest_tpu.yml
  .github/workflows/release-notification.yml
  .github/workflows/rocm-ci.yml
  .github/workflows/tsan.yaml
  .github/workflows/upstream-nightly.yml
  .github/workflows/wheel_tests_nightly_release.yml
Labels: kokoro:force-run, pull ready

#28985 Apply extensive input to extensive output forwarding in scan.
  jax/_src/lax/control_flow/loops.py
  tests/lax_control_flow_test.py
Labels: kokoro:force-run, pull ready

#29090 cloud_tpu_init: Remove verbose logging.
  jax/_src/cloud_tpu_init.py
Labels: kokoro:force-run, pull ready

#28972 [TSAN CI] Make jax build/test step fail if missing deps wheels
  .github/workflows/tsan.yaml
Labels: kokoro:force-run, pull ready

#29076 Update dtype arg collective_matmul_mgpu.py
  jax/experimental/pallas/ops/gpu/collective_matmul_mgpu.py
  tests/pallas/mgpu_collective_matmul_test.py
Labels: kokoro:force-run, pull ready, CI Optional GPU Presubmit

#29101 [hijax] all pre-existing Box tests passing, still using typechange env
  jax/_src/core.py
  jax/_src/interpreters/ad.py
  jax/_src/interpreters/partial_eval.py
  jax/_src/interpreters/pxla.py
  jax/_src/lax/control_flow/loops.py
  jax/_src/pjit.py
  tests/attrs_test.py
  tests/hijax_test.py
Labels: kokoro:force-run, pull ready

#29097 [CI] Lock down more permissions and update default usage for some workflows
  .github/workflows/bazel_cpu_py_import_rbe.yml
  .github/workflows/bazel_cuda_non_rbe.yml
  .github/workflows/build_artifacts.yml
  .github/workflows/pytest_cpu.yml
  .github/workflows/pytest_cuda.yml
  .github/workflows/pytest_tpu.yml
Labels: kokoro:force-run, pull ready

#29113 Remove Mac x86 from the installation instructions.
  README.md
  docs/installation.md
Labels: pull ready

#29120 [typing] adjust axis annotation for ufunc.reduce
  jax/_src/numpy/ufunc_api.py
Labels: pull ready

#29130 [mutable-arrays] add basic tests for vmap + mutable array
  jax/_src/state/primitives.py
  tests/mutable_array_test.py
Labels: kokoro:force-run, pull ready
